import { universe } from "../_build";

export const bouddhisme = universe("religions", "Bouddhisme", [
  // --- Faciles (5) ---
  { id: "boud-f1", d: 1, t: "Quel personnage est à l'origine du bouddhisme ?", a: "Le Bouddha", x: ["Jésus", "Mahomet", "Moïse"], acc: ["bouddha", "le bouddha"] },
  { id: "boud-f2", d: 1, t: "Comment nomme-t-on l'état d'éveil et de libération visé par le bouddhisme ?", a: "Le nirvana", x: ["Le paradis", "Le karma", "Le déluge"], acc: ["nirvana"] },
  { id: "boud-f3", d: 1, t: "Quel chef spirituel est la grande figure du bouddhisme tibétain ?", a: "Le dalaï-lama", x: ["Le pape", "Le calife", "Le grand rabbin"], acc: ["dalai-lama", "dalaï-lama", "dalai lama"] },
  { id: "boud-f4", d: 1, t: "Sur quel continent le bouddhisme est-il né ?", a: "L'Asie", x: ["L'Afrique", "L'Europe", "L'Amérique"], acc: ["asie"] },
  { id: "boud-f5", d: 1, t: "Quelle pratique de concentration et de pleine conscience est centrale dans le bouddhisme ?", a: "La méditation", x: ["Le jeûne", "Le baptême", "Le sacrifice"], acc: ["meditation", "méditation"] },
  // --- Moyennes (10) ---
  { id: "boud-m1", d: 2, t: "Quel est le nom du prince indien devenu le Bouddha ?", a: "Siddhârta Gautama", x: ["Lao Tseu", "Confucius", "Ashoka"], acc: ["siddharta", "siddhartha", "gautama", "siddharta gautama"] },
  { id: "boud-m2", d: 2, t: "Comment appelle-t-on l'arbre sous lequel le Bouddha connut l'éveil ?", a: "L'arbre de la Bodhi", x: ["L'arbre de vie", "Le baobab sacré", "L'if millénaire"], acc: ["arbre de la bodhi", "bodhi"] },
  { id: "boud-m3", d: 2, t: "Quelle loi lie nos actes à leurs conséquences dans les vies futures selon le bouddhisme ?", a: "Le karma", x: ["Le dogme", "Le péché", "La grâce"], acc: ["karma"] },
  { id: "boud-m4", d: 2, t: "Comment nomme-t-on le cycle des renaissances dont le bouddhisme cherche à sortir ?", a: "Le samsara", x: ["Le nirvana", "Le déluge", "L'apocalypse"], acc: ["samsara"] },
  { id: "boud-m5", d: 2, t: "Quel mot désigne la communauté des pratiquants bouddhistes ?", a: "Le sangha", x: ["Le clergé", "La oumma", "La paroisse"], acc: ["sangha"] },
  { id: "boud-m6", d: 2, t: "Quel mot désigne l'enseignement et la loi transmis par le Bouddha ?", a: "Le dharma", x: ["Le karma", "La torah", "Le coran"], acc: ["dharma"] },
  { id: "boud-m7", d: 2, t: "Quels sont les deux grands courants du bouddhisme ?", a: "Theravada et Mahayana", x: ["Sunnite et chiite", "Catholique et orthodoxe", "Ashkénaze et séfarade"], acc: ["theravada et mahayana"] },
  { id: "boud-m8", d: 2, t: "De quelle couleur est traditionnellement la robe des moines bouddhistes d'Asie du Sud-Est ?", a: "Safran", x: ["Blanche", "Noire", "Pourpre"], acc: ["safran", "orange"] },
  { id: "boud-m9", d: 2, t: "Quel symbole à huit rayons représente l'enseignement du Bouddha ?", a: "La roue du Dharma", x: ["Le croissant", "La croix latine", "L'étoile de David"], acc: ["roue du dharma", "dharmachakra"] },
  { id: "boud-m10", d: 2, t: "Quelle fleur, qui s'élève pure hors de la boue, symbolise l'éveil dans le bouddhisme ?", a: "Le lotus", x: ["Le lys", "La rose", "L'orchidée"], acc: ["lotus"] },
  // --- Dures (15) ---
  { id: "boud-d1", d: 3, t: "Dans quel actuel pays se trouve Lumbini, lieu de naissance du Bouddha ?", a: "Le Népal", x: ["L'Inde", "La Chine", "Le Tibet"], acc: ["nepal", "népal"] },
  { id: "boud-d2", d: 3, t: "Dans quelle ville d'Inde le Bouddha a-t-il atteint l'éveil ?", a: "Bodh-Gaya", x: ["Sarnath", "Varanasi", "Lumbini"], acc: ["bodh-gaya", "bodh gaya", "bodhgaya"] },
  { id: "boud-d3", d: 3, t: "Dans quel parc, près de Varanasi, le Bouddha a-t-il prononcé son premier sermon ?", a: "Sarnath", x: ["Bodh-Gaya", "Lhassa", "Kushinagar"], acc: ["sarnath"] },
  { id: "boud-d4", d: 3, t: "Combien de « Nobles Vérités » forment le socle de l'enseignement bouddhiste ?", a: "Quatre", x: ["Trois", "Cinq", "Sept"], acc: ["4", "quatre"] },
  { id: "boud-d5", d: 3, t: "Combien d'étapes compte le « Noble Chemin » menant à la fin de la souffrance ?", a: "Huit", x: ["Cinq", "Sept", "Dix"], acc: ["8", "huit"] },
  { id: "boud-d6", d: 3, t: "Quel nom porte le courant du bouddhisme pratiqué au Tibet ?", a: "Le vajrayana", x: ["Le theravada", "Le shintoïsme", "Le taoïsme"], acc: ["vajrayana"] },
  { id: "boud-d7", d: 3, t: "Quel courant du bouddhisme, né en Chine, s'est épanoui au Japon autour de la méditation assise ?", a: "Le zen", x: ["Le vajrayana", "Le theravada", "Le jaïnisme"], acc: ["zen"] },
  { id: "boud-d8", d: 3, t: "Comment nomme-t-on la méditation assise centrale du bouddhisme zen ?", a: "Le zazen", x: ["Le koan", "Le mantra", "Le yoga"], acc: ["zazen"] },
  { id: "boud-d9", d: 3, t: "Comment appelle-t-on l'énigme absurde que médite l'élève zen, comme « le bruit d'une seule main » ?", a: "Le koan", x: ["Le sutra", "Le mantra", "Le mandala"], acc: ["koan"] },
  { id: "boud-d10", d: 3, t: "Quel célèbre mantra tibétain invoque la compassion ?", a: "Om mani padme hum", x: ["Alléluia", "Bismillah", "Shema Israël"], acc: ["om mani padme hum"] },
  { id: "boud-d11", d: 3, t: "Comment nomme-t-on un être éveillé qui renonce au nirvana pour aider les autres ?", a: "Un bodhisattva", x: ["Un imam", "Un prophète", "Un apôtre"], acc: ["bodhisattva"] },
  { id: "boud-d12", d: 3, t: "Quel empereur indien du IIIe siècle avant notre ère a grandement diffusé le bouddhisme ?", a: "Ashoka", x: ["Akbar", "Cyrus", "Auguste"], acc: ["ashoka"] },
  { id: "boud-d13", d: 3, t: "Comment nomme-t-on le recueil des textes fondateurs du bouddhisme theravada, écrit en pali ?", a: "Le Tipitaka", x: ["Le Coran", "La Torah", "Le Talmud"], acc: ["tipitaka", "tripitaka"] },
  { id: "boud-d14", d: 3, t: "Quelle fête célèbre la naissance, l'éveil et la mort du Bouddha ?", a: "Le Vesak", x: ["Le Diwali", "Le Nouvel An chinois", "La Toussaint"], acc: ["vesak"] },
  { id: "boud-d15", d: 3, t: "Quel principe de non-violence envers tout être vivant le bouddhisme partage-t-il avec l'hindouisme ?", a: "L'ahimsa", x: ["Le djihad", "La charia", "Le jeûne"], acc: ["ahimsa"] },
  // --- Pro (20) ---
  { id: "boud-p1", d: 4, t: "Quel numéro d'ordre porte l'actuel dalaï-lama, Tenzin Gyatso ?", a: "Le quatorzième", x: ["Le dixième", "Le septième", "Le vingtième"], acc: ["14", "quatorzieme", "quatorzième"] },
  { id: "boud-p2", d: 4, t: "Dans quelle ville d'Inde le dalaï-lama vit-il en exil depuis 1959 ?", a: "Dharamsala", x: ["Lhassa", "Katmandou", "Bangkok"], acc: ["dharamsala"] },
  { id: "boud-p3", d: 4, t: "Le bouddhisme theravada est majoritaire au Sri Lanka et dans quel autre pays ?", a: "La Thaïlande", x: ["Le Japon", "La Corée", "La Mongolie"], acc: ["thailande", "thaïlande"] },
  { id: "boud-p4", d: 4, t: "Quelle « voie », entre ascèse extrême et plaisirs, le Bouddha préconise-t-il ?", a: "La voie du Milieu", x: ["La voie royale", "La voie lactée", "La voie sacrée"], acc: ["voie du milieu"] },
  { id: "boud-p5", d: 4, t: "Que signifie littéralement le mot « Bouddha » ?", a: "L'Éveillé", x: ["Le Sauveur", "L'Envoyé", "Le Prophète"], acc: ["eveille", "éveillé", "l'eveille"] },
  { id: "boud-p6", d: 4, t: "Comment nomme-t-on le monument bouddhiste en forme de dôme abritant des reliques ?", a: "Un stupa", x: ["Un minaret", "Une ziggourat", "Une basilique"], acc: ["stupa"] },
  { id: "boud-p7", d: 4, t: "Comment se prénommait la mère du Bouddha ?", a: "Maya", x: ["Yashodhara", "Tara", "Sujata"], acc: ["maya", "mayadevi"] },
  { id: "boud-p8", d: 4, t: "Quelle épouse le prince Siddhârta a-t-il quittée pour partir en quête de vérité ?", a: "Yashodhara", x: ["Maya", "Tara", "Sujata"], acc: ["yashodhara"] },
  { id: "boud-p9", d: 4, t: "Quel royaume himalayen a fait du bouddhisme sa religion d'État et mesure le « bonheur national brut » ?", a: "Le Bhoutan", x: ["Le Népal", "Le Sri Lanka", "Le Cambodge"], acc: ["bhoutan"] },
  { id: "boud-p10", d: 4, t: "Quel gigantesque temple bouddhiste de l'île de Java est le plus grand du monde ?", a: "Borobudur", x: ["Angkor Vat", "Le Potala", "Bagan"], acc: ["borobudur"] },
  { id: "boud-p11", d: 4, t: "Quel palais de Lhassa fut la résidence des dalaï-lamas ?", a: "Le Potala", x: ["Le Taj Mahal", "La Cité interdite", "Borobudur"], acc: ["potala"] },
  { id: "boud-p12", d: 4, t: "Quel bouddha, encore à venir, apparaîtra dans le futur selon la tradition ?", a: "Maitreya", x: ["Amitabha", "Vairocana", "Bhaisajyaguru"], acc: ["maitreya"] },
  { id: "boud-p13", d: 4, t: "Le bouddhisme de la Terre pure voue un culte à quel bouddha de la lumière infinie ?", a: "Amitabha", x: ["Maitreya", "Gautama", "Vairocana"], acc: ["amitabha"] },
  { id: "boud-p14", d: 4, t: "Quel bodhisattva de la compassion est vénéré en Chine sous le nom de Guanyin ?", a: "Avalokiteshvara", x: ["Maitreya", "Manjushri", "Amitabha"], acc: ["avalokiteshvara"] },
  { id: "boud-p15", d: 4, t: "Quel objet cylindrique les bouddhistes tibétains font-ils tourner pour réciter des prières ?", a: "Le moulin à prières", x: ["Le chapelet", "L'encensoir", "Le bénitier"], acc: ["moulin à prières", "moulin a prieres"] },
  { id: "boud-p16", d: 4, t: "Comment nomme-t-on le diagramme de sable coloré réalisé puis détruit par les moines tibétains ?", a: "Le mandala", x: ["Le koan", "Le sutra", "Le stupa"], acc: ["mandala"] },
  { id: "boud-p17", d: 4, t: "Comment appelle-t-on les textes rapportant les discours attribués au Bouddha ?", a: "Les sutras", x: ["Les psaumes", "Les hadiths", "Les évangiles"], acc: ["sutra", "sutras"] },
  { id: "boud-p18", d: 4, t: "Concernant un dieu créateur du monde, quelle est la particularité du bouddhisme ?", a: "Il n'en reconnaît aucun", x: ["Il en vénère trois", "Il en compte mille", "Il adore le soleil"], acc: ["aucun", "il n'en reconnait aucun"] },
  { id: "boud-p19", d: 4, t: "Ignorance, avidité et haine forment les « trois » quoi, causes de la souffrance ?", a: "Les trois poisons", x: ["Les trois joyaux", "Les trois vertus", "Les trois grâces"], acc: ["trois poisons"] },
  { id: "boud-p20", d: 4, t: "Quelle relique du Bouddha est vénérée dans un temple de Kandy, au Sri Lanka ?", a: "Une dent", x: ["Un cheveu", "Un os du bras", "Une sandale"], acc: ["dent", "une dent"] },
]);
