import { universe } from "../_build";

export const catholicisme = universe("religions", "Catholicisme", [
  // --- Faciles (5) ---
  { id: "cath-f1", d: 1, t: "Qui est le chef de l'Église catholique ?", a: "Le pape", x: ["Le calife", "Le dalaï-lama", "Le patriarche"], acc: ["pape", "le pape"] },
  { id: "cath-f2", d: 1, t: "Dans quel État minuscule, au cœur de Rome, réside le pape ?", a: "Le Vatican", x: ["Monaco", "Saint-Marin", "Malte"], acc: ["vatican"] },
  { id: "cath-f3", d: 1, t: "Comment appelle-t-on le bâtiment où les catholiques célèbrent la messe ?", a: "L'église", x: ["La mosquée", "La synagogue", "La pagode"], acc: ["eglise", "église"] },
  { id: "cath-f4", d: 1, t: "Quel livre saint les catholiques lisent-ils ?", a: "La Bible", x: ["Le Coran", "La Torah", "Les Védas"], acc: ["bible"] },
  { id: "cath-f5", d: 1, t: "Quel symbole, rappelant la mort du Christ, est central chez les catholiques ?", a: "La croix", x: ["Le croissant", "L'étoile", "La roue"], acc: ["croix", "la croix"] },
  // --- Moyennes (10) ---
  { id: "cath-m1", d: 2, t: "Quel apôtre est considéré comme le tout premier pape ?", a: "Saint Pierre", x: ["Saint Paul", "Saint Jean", "Saint Jacques"], acc: ["pierre", "saint pierre"] },
  { id: "cath-m2", d: 2, t: "Combien de sacrements l'Église catholique reconnaît-elle ?", a: "Sept", x: ["Trois", "Cinq", "Dix"], acc: ["7", "sept"] },
  { id: "cath-m3", d: 2, t: "Comment nomme-t-on la célébration catholique du dimanche ?", a: "La messe", x: ["Le sabbat", "La prière du vendredi", "Le shabbat"], acc: ["messe"] },
  { id: "cath-m4", d: 2, t: "Quelle femme, mère de Jésus, est particulièrement vénérée par les catholiques ?", a: "La Vierge Marie", x: ["Marie-Madeleine", "Sainte Anne", "Sainte Thérèse"], acc: ["marie", "vierge marie"] },
  { id: "cath-m5", d: 2, t: "Quel objet fait de perles sert à réciter des prières comme le « Je vous salue Marie » ?", a: "Le chapelet", x: ["Le calice", "L'encensoir", "Le ciboire"], acc: ["chapelet"] },
  { id: "cath-m6", d: 2, t: "Quel ministre célèbre la messe dans une paroisse catholique ?", a: "Le prêtre", x: ["L'imam", "Le rabbin", "Le pasteur"], acc: ["pretre", "prêtre"] },
  { id: "cath-m7", d: 2, t: "Quel sacrement consiste à confier ses péchés à un prêtre pour être pardonné ?", a: "La confession", x: ["Le baptême", "La communion", "Le mariage"], acc: ["confession", "reconciliation", "pénitence"] },
  { id: "cath-m8", d: 2, t: "Quel sacrement, célébré avec de l'eau, fait entrer dans la communauté chrétienne ?", a: "Le baptême", x: ["La confirmation", "L'eucharistie", "L'onction des malades"], acc: ["bapteme", "baptême"] },
  { id: "cath-m9", d: 2, t: "Quelle grande fête catholique célèbre la naissance de Jésus ?", a: "Noël", x: ["Pâques", "La Pentecôte", "L'Ascension"], acc: ["noel", "noël"] },
  { id: "cath-m10", d: 2, t: "Quelle fête catholique célèbre la résurrection du Christ ?", a: "Pâques", x: ["Noël", "La Toussaint", "L'Épiphanie"], acc: ["paques", "pâques"] },
  // --- Dures (15) ---
  { id: "cath-d1", d: 3, t: "Quelle basilique du Vatican est le plus grand édifice de la chrétienté ?", a: "La basilique Saint-Pierre", x: ["Notre-Dame de Paris", "La basilique Saint-Marc", "La cathédrale de Cologne"], acc: ["saint-pierre", "basilique saint-pierre"] },
  { id: "cath-d2", d: 3, t: "Dans quelle chapelle du Vatican, peinte par Michel-Ange, se tient le conclave ?", a: "La chapelle Sixtine", x: ["La chapelle palatine", "La Sainte-Chapelle", "La chapelle des Médicis"], acc: ["sixtine", "chapelle sixtine"] },
  { id: "cath-d3", d: 3, t: "Comment nomme-t-on la réunion des cardinaux qui élisent un nouveau pape ?", a: "Le conclave", x: ["Le concile", "Le synode", "Le consistoire"], acc: ["conclave"] },
  { id: "cath-d4", d: 3, t: "Quelle couleur de fumée annonce l'élection d'un nouveau pape ?", a: "Blanche", x: ["Noire", "Rouge", "Dorée"], acc: ["blanche", "blanc"] },
  { id: "cath-d5", d: 3, t: "De quelle couleur est traditionnellement l'habit des cardinaux ?", a: "Rouge", x: ["Violette", "Blanche", "Verte"], acc: ["rouge"] },
  { id: "cath-d6", d: 3, t: "Comment nomme-t-on la transformation du pain et du vin au corps et au sang du Christ à la messe ?", a: "La transsubstantiation", x: ["La transfiguration", "La consubstantiation", "La résurrection"], acc: ["transsubstantiation"] },
  { id: "cath-d7", d: 3, t: "Le Père, le Fils et le Saint-Esprit forment quel mystère central de la foi catholique ?", a: "La Trinité", x: ["L'Incarnation", "La Rédemption", "La Cène"], acc: ["trinite", "trinité"] },
  { id: "cath-d8", d: 3, t: "Combien de jours dure le Carême avant Pâques ?", a: "Quarante", x: ["Trente", "Cinquante", "Sept"], acc: ["40", "quarante"] },
  { id: "cath-d9", d: 3, t: "Quel jour, marqué d'une croix de cendres sur le front, ouvre le Carême ?", a: "Le mercredi des Cendres", x: ["Le Vendredi saint", "Le dimanche des Rameaux", "Le jeudi saint"], acc: ["mercredi des cendres"] },
  { id: "cath-d10", d: 3, t: "Quelle coiffe pointue l'évêque porte-t-il lors des cérémonies ?", a: "La mitre", x: ["La tiare", "La calotte", "La couronne"], acc: ["mitre"] },
  { id: "cath-d11", d: 3, t: "Quel bâton recourbé, symbole du berger, l'évêque tient-il ?", a: "La crosse", x: ["Le sceptre", "Le trident", "La férule"], acc: ["crosse"] },
  { id: "cath-d12", d: 3, t: "Quel corps de gardes en uniforme coloré assure la protection rapprochée du pape ?", a: "La Garde suisse", x: ["Les Templiers", "Les Janissaires", "Les Hospitaliers"], acc: ["garde suisse"] },
  { id: "cath-d13", d: 3, t: "Quel état d'attente et de purification après la mort est propre à la doctrine catholique ?", a: "Le purgatoire", x: ["Les limbes", "Le paradis", "Le shéol"], acc: ["purgatoire"] },
  { id: "cath-d14", d: 3, t: "Quel dogme proclamé en 1870 rend le pape « infaillible » quand il parle en matière de foi ?", a: "L'infaillibilité pontificale", x: ["L'Immaculée Conception", "L'Assomption", "La Transsubstantiation"], acc: ["infaillibilite pontificale", "infaillibilité pontificale", "infaillibilité"] },
  { id: "cath-d15", d: 3, t: "Comment nomme-t-on le titre du pape en tant que successeur de Pierre à la tête de Rome ?", a: "L'évêque de Rome", x: ["Le patriarche d'Orient", "Le primat des Gaules", "Le métropolite"], acc: ["eveque de rome", "évêque de rome"] },
  // --- Pro (20) ---
  { id: "cath-p1", d: 4, t: "Quel pape argentin, premier jésuite de l'Histoire, a régné de 2013 à 2025 ?", a: "François", x: ["Benoît XVI", "Jean-Paul II", "Léon XIV"], acc: ["francois", "françois", "pape françois"] },
  { id: "cath-p2", d: 4, t: "Quel pape, premier Américain de l'Histoire, a été élu en 2025 ?", a: "Léon XIV", x: ["François", "Benoît XVI", "Pie XII"], acc: ["leon xiv", "léon xiv"] },
  { id: "cath-p3", d: 4, t: "Quel est le nom de naissance du pape Léon XIV ?", a: "Robert Prevost", x: ["Jorge Bergoglio", "Joseph Ratzinger", "Karol Wojtyla"], acc: ["prevost", "robert prevost"] },
  { id: "cath-p4", d: 4, t: "De quelle nationalité était le pape Jean-Paul II ?", a: "Polonaise", x: ["Italienne", "Allemande", "Argentine"], acc: ["polonaise", "polonais"] },
  { id: "cath-p5", d: 4, t: "Quel pape a surpris le monde en renonçant à sa charge en 2013 ?", a: "Benoît XVI", x: ["Jean-Paul II", "François", "Pie XII"], acc: ["benoit xvi", "benoît xvi"] },
  { id: "cath-p6", d: 4, t: "Quelle basilique de Rome est la véritable cathédrale du pape en tant qu'évêque de la ville ?", a: "Saint-Jean-de-Latran", x: ["Sainte-Marie-Majeure", "Saint-Paul-hors-les-Murs", "Saint-Pierre"], acc: ["saint-jean-de-latran", "latran"] },
  { id: "cath-p7", d: 4, t: "Quel concile des années 1960 a modernisé l'Église et autorisé la messe en langue locale ?", a: "Vatican II", x: ["Le concile de Trente", "Vatican I", "Le concile de Nicée"], acc: ["vatican ii", "concile vatican ii"] },
  { id: "cath-p8", d: 4, t: "Quel concile du XVIe siècle a organisé la Contre-Réforme catholique ?", a: "Le concile de Trente", x: ["Vatican II", "Le concile de Nicée", "Le concile de Constance"], acc: ["trente", "concile de trente"] },
  { id: "cath-p9", d: 4, t: "Quelle langue fut pendant des siècles celle de la liturgie catholique romaine ?", a: "Le latin", x: ["Le grec", "L'araméen", "L'hébreu"], acc: ["latin"] },
  { id: "cath-p10", d: 4, t: "Quel saint espagnol a fondé la Compagnie de Jésus, les jésuites ?", a: "Ignace de Loyola", x: ["François d'Assise", "Benoît de Nursie", "Dominique de Guzmán"], acc: ["ignace de loyola", "loyola"] },
  { id: "cath-p11", d: 4, t: "Quel saint italien, ami des animaux, a fondé l'ordre des franciscains ?", a: "François d'Assise", x: ["Antoine de Padoue", "Benoît de Nursie", "Thomas d'Aquin"], acc: ["françois d'assise", "francois d'assise", "assise"] },
  { id: "cath-p12", d: 4, t: "Quel dogme de 1854 affirme que Marie fut conçue sans le péché originel ?", a: "L'Immaculée Conception", x: ["L'Assomption", "L'Annonciation", "La Visitation"], acc: ["immaculee conception", "immaculée conception"] },
  { id: "cath-p13", d: 4, t: "Quel dogme de 1950 affirme que Marie fut élevée au ciel corps et âme ?", a: "L'Assomption", x: ["L'Immaculée Conception", "L'Ascension", "L'Annonciation"], acc: ["assomption"] },
  { id: "cath-p14", d: 4, t: "Dans quelle ville française Bernadette Soubirous a-t-elle vu la Vierge en 1858 ?", a: "Lourdes", x: ["Fatima", "Lisieux", "La Salette"], acc: ["lourdes"] },
  { id: "cath-p15", d: 4, t: "Dans quelle ville portugaise trois enfants ont-ils rapporté des apparitions mariales en 1917 ?", a: "Fatima", x: ["Lourdes", "Guadalupe", "Knock"], acc: ["fatima"] },
  { id: "cath-p16", d: 4, t: "Quelle prière, enseignée par Jésus, commence par « Notre Père qui es aux cieux » ?", a: "Le Notre Père", x: ["Le Je vous salue Marie", "Le Credo", "Le Confiteor"], acc: ["notre père", "notre pere", "pater noster"] },
  { id: "cath-p17", d: 4, t: "Comment nomme-t-on la profession de foi récitée à la messe, résumant les croyances ?", a: "Le Credo", x: ["Le Gloria", "Le Sanctus", "L'Agnus Dei"], acc: ["credo"] },
  { id: "cath-p18", d: 4, t: "Quel pain sans levain, consacré à la messe, les fidèles reçoivent-ils à la communion ?", a: "L'hostie", x: ["Le calice", "La patène", "Le ciboire"], acc: ["hostie"] },
  { id: "cath-p19", d: 4, t: "Quelle religieuse de Calcutta, canonisée en 2016, a consacré sa vie aux plus pauvres ?", a: "Mère Teresa", x: ["Sainte Bernadette", "Sainte Rita", "Sainte Faustine"], acc: ["mere teresa", "mère teresa", "teresa de calcutta"] },
  { id: "cath-p20", d: 4, t: "En 1054, de quelle Église la catholique romaine s'est-elle définitivement séparée ?", a: "L'Église orthodoxe", x: ["L'Église protestante", "L'Église anglicane", "L'Église copte"], acc: ["orthodoxe", "eglise orthodoxe", "église orthodoxe"] },
]);
