import { universe } from "../_build";

export const chretiente = universe("religions", "Chrétienté", [
  // --- Faciles (5) ---
  { id: "chr-f1", d: 1, t: "Autour de quelle figure la religion chrétienne est-elle centrée ?", a: "Jésus-Christ", x: ["Mahomet", "Bouddha", "Abraham"], acc: ["jesus", "jésus", "jesus-christ", "christ"] },
  { id: "chr-f2", d: 1, t: "Quel est le livre saint des chrétiens ?", a: "La Bible", x: ["Le Coran", "La Torah", "Le Talmud"], acc: ["bible"] },
  { id: "chr-f3", d: 1, t: "Quelle fête chrétienne célèbre la naissance de Jésus le 25 décembre ?", a: "Noël", x: ["Pâques", "L'Aïd", "Hanoukka"], acc: ["noel", "noël"] },
  { id: "chr-f4", d: 1, t: "Quel symbole représente le sacrifice de Jésus pour les chrétiens ?", a: "La croix", x: ["Le croissant", "L'étoile de David", "La roue"], acc: ["croix", "la croix"] },
  { id: "chr-f5", d: 1, t: "Combien de dieux la religion chrétienne reconnaît-elle ?", a: "Un seul", x: ["Deux", "Trois cents", "Une multitude"], acc: ["un", "un seul"] },
  // --- Moyennes (10) ---
  { id: "chr-m1", d: 2, t: "En quelles deux grandes parties la Bible chrétienne se divise-t-elle ?", a: "L'Ancien et le Nouveau Testament", x: ["La Genèse et l'Apocalypse", "La Loi et les Prophètes", "Les Psaumes et les Évangiles"], acc: ["ancien et nouveau testament"] },
  { id: "chr-m2", d: 2, t: "Combien d'Évangiles racontent la vie de Jésus dans le Nouveau Testament ?", a: "Quatre", x: ["Deux", "Sept", "Douze"], acc: ["4", "quatre"] },
  { id: "chr-m3", d: 2, t: "Dans quelle ville Jésus est-il né selon les Évangiles ?", a: "Bethléem", x: ["Nazareth", "Jérusalem", "Rome"], acc: ["bethleem", "bethléem"] },
  { id: "chr-m4", d: 2, t: "Comment se prénomme la mère de Jésus ?", a: "Marie", x: ["Marthe", "Élisabeth", "Anne"], acc: ["marie"] },
  { id: "chr-m5", d: 2, t: "Combien d'apôtres Jésus a-t-il choisis pour le suivre ?", a: "Douze", x: ["Sept", "Dix", "Quarante"], acc: ["12", "douze"] },
  { id: "chr-m6", d: 2, t: "De quel supplice Jésus est-il mort selon les Évangiles ?", a: "La crucifixion", x: ["La lapidation", "La décapitation", "Le bûcher"], acc: ["crucifixion"] },
  { id: "chr-m7", d: 2, t: "Quel événement, fêté à Pâques, marque le retour à la vie de Jésus ?", a: "La résurrection", x: ["L'Ascension", "La Nativité", "La Cène"], acc: ["resurrection", "résurrection"] },
  { id: "chr-m8", d: 2, t: "Comment appelle-t-on le lieu de culte des chrétiens ?", a: "L'église", x: ["La mosquée", "La synagogue", "La pagode"], acc: ["eglise", "église"] },
  { id: "chr-m9", d: 2, t: "Quel titre porte le ministre du culte chez les protestants ?", a: "Le pasteur", x: ["Le prêtre", "L'imam", "Le rabbin"], acc: ["pasteur"] },
  { id: "chr-m10", d: 2, t: "Quel rite à l'eau marque l'entrée dans la vie chrétienne ?", a: "Le baptême", x: ["La circoncision", "Le ramadan", "La bar-mitsva"], acc: ["bapteme", "baptême"] },
  // --- Dures (15) ---
  { id: "chr-d1", d: 3, t: "Quelles sont les trois grandes branches du christianisme ?", a: "Catholiques, orthodoxes et protestants", x: ["Sunnites, chiites et soufis", "Ashkénazes, séfarades et karaïtes", "Theravada, mahayana et vajrayana"], acc: ["catholiques orthodoxes et protestants"] },
  { id: "chr-d2", d: 3, t: "Quel moine allemand a lancé la Réforme protestante en 1517 ?", a: "Martin Luther", x: ["Jean Calvin", "Henri VIII", "Thomas More"], acc: ["luther", "martin luther"] },
  { id: "chr-d3", d: 3, t: "Quel réformateur français a diffusé le protestantisme depuis Genève ?", a: "Jean Calvin", x: ["Martin Luther", "John Wesley", "John Knox"], acc: ["calvin", "jean calvin"] },
  { id: "chr-d4", d: 3, t: "Quel roi d'Angleterre a fondé l'Église anglicane au XVIe siècle ?", a: "Henri VIII", x: ["Henri IV", "Édouard VI", "Jacques Ier"], acc: ["henri viii"] },
  { id: "chr-d5", d: 3, t: "Quelle branche chrétienne, séparée de Rome en 1054, a son foyer à Constantinople ?", a: "L'orthodoxie", x: ["Le protestantisme", "L'anglicanisme", "Le catholicisme"], acc: ["orthodoxie", "orthodoxe"] },
  { id: "chr-d6", d: 3, t: "Quel est le premier livre de la Bible ?", a: "La Genèse", x: ["L'Exode", "Les Psaumes", "L'Apocalypse"], acc: ["genese", "genèse"] },
  { id: "chr-d7", d: 3, t: "Quel livre, évoquant la fin des temps, clôt le Nouveau Testament ?", a: "L'Apocalypse", x: ["La Genèse", "Les Actes des Apôtres", "L'Évangile de Jean"], acc: ["apocalypse"] },
  { id: "chr-d8", d: 3, t: "Matthieu, Marc, Luc et… : quel est le quatrième évangéliste ?", a: "Jean", x: ["Pierre", "Paul", "Thomas"], acc: ["jean"] },
  { id: "chr-d9", d: 3, t: "Quel apôtre a trahi Jésus pour trente pièces d'argent ?", a: "Judas", x: ["Pierre", "Thomas", "Barthélemy"], acc: ["judas", "judas iscariote"] },
  { id: "chr-d10", d: 3, t: "Quel apôtre a renié Jésus trois fois avant le chant du coq ?", a: "Pierre", x: ["Judas", "Jean", "André"], acc: ["pierre"] },
  { id: "chr-d11", d: 3, t: "Qui a baptisé Jésus dans le Jourdain ?", a: "Jean-Baptiste", x: ["Pierre", "Paul", "Joseph"], acc: ["jean-baptiste", "jean le baptiste"] },
  { id: "chr-d12", d: 3, t: "Dans quel fleuve Jésus a-t-il été baptisé ?", a: "Le Jourdain", x: ["Le Nil", "L'Euphrate", "Le Tibre"], acc: ["jourdain"] },
  { id: "chr-d13", d: 3, t: "Comment nomme-t-on le dernier repas de Jésus avec ses apôtres ?", a: "La Cène", x: ["Les Noces de Cana", "La Pentecôte", "La Transfiguration"], acc: ["cene", "cène", "la cene"] },
  { id: "chr-d14", d: 3, t: "Quelle fête, cinquante jours après Pâques, célèbre la venue du Saint-Esprit sur les apôtres ?", a: "La Pentecôte", x: ["L'Ascension", "L'Épiphanie", "L'Avent"], acc: ["pentecote", "pentecôte"] },
  { id: "chr-d15", d: 3, t: "Quel apôtre, d'abord persécuteur, s'est converti sur le chemin de Damas ?", a: "Paul", x: ["Pierre", "Jean", "Luc"], acc: ["paul", "saint paul", "paul de tarse"] },
  // --- Pro (20) ---
  { id: "chr-p1", d: 4, t: "Quelle place le christianisme occupe-t-il parmi les religions du monde par le nombre de fidèles ?", a: "La première", x: ["La deuxième", "La cinquième", "La dixième"], acc: ["1re", "première", "premiere"] },
  { id: "chr-p2", d: 4, t: "Quel empereur romain a autorisé le christianisme par l'édit de Milan en 313 ?", a: "Constantin", x: ["Néron", "Auguste", "Dioclétien"], acc: ["constantin"] },
  { id: "chr-p3", d: 4, t: "Quel concile de 325 a fixé les bases du Credo chrétien ?", a: "Le concile de Nicée", x: ["Le concile de Trente", "Vatican II", "Le concile de Constance"], acc: ["nicee", "nicée", "concile de nicée"] },
  { id: "chr-p4", d: 4, t: "Dans quelle langue les Évangiles ont-ils d'abord été écrits ?", a: "Le grec", x: ["Le latin", "L'hébreu", "L'araméen"], acc: ["grec"] },
  { id: "chr-p5", d: 4, t: "Quelle langue Jésus parlait-il au quotidien ?", a: "L'araméen", x: ["Le latin", "Le grec", "L'arabe"], acc: ["arameen", "araméen"] },
  { id: "chr-p6", d: 4, t: "Que signifie l'inscription « INRI » placée sur la croix de Jésus ?", a: "Jésus de Nazareth roi des Juifs", x: ["Au nom du Père et du Fils", "Ici repose notre roi", "Il est ressuscité"], acc: ["jesus de nazareth roi des juifs"] },
  { id: "chr-p7", d: 4, t: "Quel gouverneur romain a livré Jésus à la crucifixion ?", a: "Ponce Pilate", x: ["Hérode", "Néron", "César Auguste"], acc: ["ponce pilate", "pilate"] },
  { id: "chr-p8", d: 4, t: "Sur quelle colline de Jérusalem Jésus a-t-il été crucifié ?", a: "Le Golgotha", x: ["Le mont des Oliviers", "Le mont Sinaï", "Le mont Thabor"], acc: ["golgotha", "calvaire"] },
  { id: "chr-p9", d: 4, t: "Lors de quel événement Jésus a-t-il changé l'eau en vin, son premier miracle ?", a: "Les Noces de Cana", x: ["La Cène", "La multiplication des pains", "La Transfiguration"], acc: ["noces de cana", "cana"] },
  { id: "chr-p10", d: 4, t: "Quel miracle a permis à Jésus de nourrir une foule avec cinq pains et deux poissons ?", a: "La multiplication des pains", x: ["Les Noces de Cana", "La pêche miraculeuse", "La marche sur les eaux"], acc: ["multiplication des pains"] },
  { id: "chr-p11", d: 4, t: "Quel ami de Jésus a-t-il ramené à la vie quatre jours après sa mort ?", a: "Lazare", x: ["Judas", "Nicodème", "Zachée"], acc: ["lazare"] },
  { id: "chr-p12", d: 4, t: "Comment nomme-t-on le discours de Jésus commençant par « Heureux les pauvres en esprit » ?", a: "Les Béatitudes", x: ["Le Notre Père", "Le Cantique des cantiques", "Les Dix Commandements"], acc: ["beatitudes", "béatitudes", "sermon sur la montagne"] },
  { id: "chr-p13", d: 4, t: "Comment appelle-t-on la traduction latine de la Bible réalisée par saint Jérôme ?", a: "La Vulgate", x: ["La Septante", "La Peshitta", "La King James"], acc: ["vulgate"] },
  { id: "chr-p14", d: 4, t: "Quel nom porte l'antique traduction grecque de l'Ancien Testament ?", a: "La Septante", x: ["La Vulgate", "La Peshitta", "La Néovulgate"], acc: ["septante"] },
  { id: "chr-p15", d: 4, t: "Dans quelle ville allemande Luther aurait-il affiché ses 95 thèses ?", a: "Wittenberg", x: ["Genève", "Worms", "Augsbourg"], acc: ["wittenberg"] },
  { id: "chr-p16", d: 4, t: "Contrairement aux catholiques, à quelle seule autorité les protestants se réfèrent-ils avant tout ?", a: "La Bible seule", x: ["Le pape", "La Tradition", "Les conciles"], acc: ["la bible seule", "sola scriptura", "l'écriture seule"] },
  { id: "chr-p17", d: 4, t: "Quelles images saintes peintes sur bois sont vénérées dans les églises orthodoxes ?", a: "Les icônes", x: ["Les vitraux", "Les fresques", "Les statues"], acc: ["icones", "icônes"] },
  { id: "chr-p18", d: 4, t: "De quel roi d'Israël Jésus est-il présenté comme le descendant ?", a: "David", x: ["Salomon", "Saül", "Hérode"], acc: ["david"] },
  { id: "chr-p19", d: 4, t: "Combien de rois mages, selon la tradition, sont venus visiter Jésus enfant ?", a: "Trois", x: ["Deux", "Sept", "Douze"], acc: ["3", "trois"] },
  { id: "chr-p20", d: 4, t: "Quel animal servait de signe de reconnaissance secret aux premiers chrétiens ?", a: "Le poisson", x: ["L'agneau", "La colombe", "Le lion"], acc: ["poisson", "le poisson"] },
]);
