import { universe } from "../_build";

export const cinemajaponais = universe("japon", "Cinéma japonais", [
  // --- Faciles (5) ---
  { id: "jpcine-f1", d: 1, t: "Quel studio d'animation japonais a produit « Le Voyage de Chihiro » et « Totoro » ?", a: "Le Studio Ghibli", x: ["Le Studio Pixar", "La Toei", "Le Studio Ponoc"], acc: ["ghibli", "studio ghibli"] },
  { id: "jpcine-f2", d: 1, t: "Quel réalisateur, cofondateur de Ghibli, a signé « Princesse Mononoké » ?", a: "Hayao Miyazaki", x: ["Isao Takahata", "Makoto Shinkai", "Akira Kurosawa"] },
  { id: "jpcine-f3", d: 1, t: "Quel gros esprit gris de la forêt donne son nom à un film de Miyazaki ?", a: "Totoro", x: ["Ponyo", "Calcifer", "Jiji"], acc: ["totoro"] },
  { id: "jpcine-f4", d: 1, t: "Comment appelle-t-on les films japonais mettant en scène des monstres géants comme Godzilla ?", a: "Le kaiju", x: ["Le tokusatsu", "Le jidaigeki", "Le pinku"], acc: ["kaiju"] },
  { id: "jpcine-f5", d: 1, t: "Quel monstre géant sorti de l'océan détruit Tokyo dans un film de 1954 ?", a: "Godzilla", x: ["King Kong", "Mothra", "Gamera"], acc: ["godzilla", "gojira"] },
  // --- Moyennes (10) ---
  { id: "jpcine-m1", d: 2, t: "Quel réalisateur japonais est mondialement connu pour « Les Sept Samouraïs » ?", a: "Akira Kurosawa", x: ["Yasujirō Ozu", "Kenji Mizoguchi", "Takeshi Kitano"] },
  { id: "jpcine-m2", d: 2, t: "Quel film de Kurosawa de 1954 suit des paysans engageant des guerriers pour se défendre ?", a: "Les Sept Samouraïs", x: ["Ran", "Yojimbo", "Rashômon"] },
  { id: "jpcine-m3", d: 2, t: "Quel film de Miyazaki suit une jeune sorcière et son chat noir Jiji ?", a: "Kiki la petite sorcière", x: ["Ponyo", "Le Château ambulant", "Arrietty"] },
  { id: "jpcine-m4", d: 2, t: "Quel film de Miyazaki suit une petite fille poisson qui veut devenir humaine ?", a: "Ponyo sur la falaise", x: ["Kiki la petite sorcière", "Le Voyage de Chihiro", "Le Vent se lève"], acc: ["ponyo"] },
  { id: "jpcine-m5", d: 2, t: "Quel réalisateur japonais, aussi acteur comique, a signé « Hana-bi » ?", a: "Takeshi Kitano", x: ["Hirokazu Kore-eda", "Takashi Miike", "Akira Kurosawa"] },
  { id: "jpcine-m6", d: 2, t: "Quel film d'animation de Makoto Shinkai a été un carton mondial en 2016 ?", a: "Your Name", x: ["Les Enfants du temps", "Suzume", "5 centimètres par seconde"], acc: ["your name", "kimi no na wa"] },
  { id: "jpcine-m7", d: 2, t: "Quel réalisateur a écrit et réalisé le film d'animation « Akira » ?", a: "Katsuhiro Otomo", x: ["Hayao Miyazaki", "Mamoru Oshii", "Satoshi Kon"] },
  { id: "jpcine-m8", d: 2, t: "Quel film de Kurosawa de 1950 raconte un même crime selon plusieurs points de vue ?", a: "Rashômon", x: ["Les Sept Samouraïs", "Vivre", "Kagemusha"], acc: ["rashomon", "rashômon"] },
  { id: "jpcine-m9", d: 2, t: "Quel film d'horreur japonais de 1998 met en scène une cassette vidéo maudite ?", a: "Ring", x: ["Ju-on", "Dark Water", "Audition"], acc: ["ring", "ringu"] },
  { id: "jpcine-m10", d: 2, t: "Quel fantôme aux longs cheveux noirs hante le film « Ring » ?", a: "Sadako", x: ["Kayako", "Tomie", "Okiku"], acc: ["sadako"] },
  // --- Dures (15) ---
  { id: "jpcine-d1", d: 3, t: "Quel maître du cinéma japonais est connu pour ses plans fixes et « Voyage à Tokyo » ?", a: "Yasujirō Ozu", x: ["Akira Kurosawa", "Kenji Mizoguchi", "Mikio Naruse"] },
  { id: "jpcine-d2", d: 3, t: "Quel réalisateur palmé à Cannes est connu pour ses films de famille comme « Une affaire de famille » ?", a: "Hirokazu Kore-eda", x: ["Takeshi Kitano", "Takashi Miike", "Naomi Kawase"] },
  { id: "jpcine-d3", d: 3, t: "Quel film de Kore-eda a remporté la Palme d'or en 2018 ?", a: "Une affaire de famille", x: ["Tel père, tel fils", "Nobody Knows", "Still Walking"], acc: ["une affaire de famille", "shoplifters"] },
  { id: "jpcine-d4", d: 3, t: "Quel réalisateur prolifique et provocateur a signé « Audition » et « Ichi the Killer » ?", a: "Takashi Miike", x: ["Takeshi Kitano", "Sion Sono", "Kiyoshi Kurosawa"] },
  { id: "jpcine-d5", d: 3, t: "Quel film de 2000 met des collégiens forcés de s'entretuer sur une île ?", a: "Battle Royale", x: ["Real", "As the Gods Will", "Suicide Club"], acc: ["battle royale"] },
  { id: "jpcine-d6", d: 3, t: "Quel cofondateur de Ghibli a réalisé « Le Tombeau des lucioles » ?", a: "Isao Takahata", x: ["Hayao Miyazaki", "Yoshifumi Kondō", "Hiromasa Yonebayashi"] },
  { id: "jpcine-d7", d: 3, t: "Quel film de Ghibli de 1988 raconte deux enfants dans le Japon en guerre ?", a: "Le Tombeau des lucioles", x: ["Le Vent se lève", "Le Château dans le ciel", "Pompoko"] },
  { id: "jpcine-d8", d: 3, t: "Quel film de Miyazaki de 2001 a remporté l'Oscar du meilleur film d'animation ?", a: "Le Voyage de Chihiro", x: ["Princesse Mononoké", "Le Château ambulant", "Le Garçon et le Héron"] },
  { id: "jpcine-d9", d: 3, t: "Quel film d'animation de Miyazaki de 2023 a de nouveau remporté l'Oscar ?", a: "Le Garçon et le Héron", x: ["Le Vent se lève", "Ponyo", "Arrietty"], acc: ["le garçon et le héron"] },
  { id: "jpcine-d10", d: 3, t: "Quel réalisateur d'horreur a signé « Kaïro » et « Cure » ?", a: "Kiyoshi Kurosawa", x: ["Hideo Nakata", "Takashi Shimizu", "Takashi Miike"] },
  { id: "jpcine-d11", d: 3, t: "Quel réalisateur a lancé la saga d'horreur « Ju-on », adaptée en « The Grudge » ?", a: "Takashi Shimizu", x: ["Hideo Nakata", "Kiyoshi Kurosawa", "Sion Sono"] },
  { id: "jpcine-d12", d: 3, t: "Quel film de Kurosawa de 1985 transpose « Le Roi Lear » dans le Japon féodal ?", a: "Ran", x: ["Kagemusha", "Le Château de l'araignée", "Dersou Ouzala"] },
  { id: "jpcine-d13", d: 3, t: "Quel acteur fétiche de Kurosawa incarne le samouraï de « Yojimbo » ?", a: "Toshirō Mifune", x: ["Tatsuya Nakadai", "Takashi Shimura", "Ken Watanabe"] },
  { id: "jpcine-d14", d: 3, t: "Comment appelle-t-on le genre du film de sabre japonais en costumes d'époque ?", a: "Le jidaigeki", x: ["Le kaiju", "Le tokusatsu", "Le pinku"], acc: ["jidaigeki"] },
  { id: "jpcine-d15", d: 3, t: "Quel film d'animation de Mamoru Hosoda suit une famille dont le père se transforme en loup ?", a: "Les Enfants loups", x: ["Summer Wars", "Le Garçon et la Bête", "Belle"], acc: ["enfants loups"] },
  // --- Pro (20) ---
  { id: "jpcine-p1", d: 4, t: "En quelle année sort le tout premier film Godzilla ?", a: "1954", x: ["1947", "1962", "1971"] },
  { id: "jpcine-p2", d: 4, t: "Quel studio japonais a créé Godzilla ?", a: "La Tōhō", x: ["La Toei", "Le Studio Ghibli", "La Daiei"], acc: ["toho", "tōhō"] },
  { id: "jpcine-p3", d: 4, t: "Quel film de Kurosawa de 1952 suit un fonctionnaire mourant cherchant un sens à sa vie ?", a: "Vivre", x: ["Rashômon", "Barberousse", "L'Idiot"], acc: ["vivre", "ikiru"] },
  { id: "jpcine-p4", d: 4, t: "Quel western de Sergio Leone est un remake de « Yojimbo » de Kurosawa ?", a: "Pour une poignée de dollars", x: ["Le Bon, la Brute et le Truand", "Il était une fois dans l'Ouest", "Et pour quelques dollars de plus"] },
  { id: "jpcine-p5", d: 4, t: "Quel film d'animation de 1988 de Katsuhiro Otomo est un jalon du cyberpunk ?", a: "Akira", x: ["Ghost in the Shell", "Metropolis", "Steamboy"] },
  { id: "jpcine-p6", d: 4, t: "Quel réalisateur a signé « Ghost in the Shell » en 1995 ?", a: "Mamoru Oshii", x: ["Katsuhiro Otomo", "Satoshi Kon", "Hideaki Anno"] },
  { id: "jpcine-p7", d: 4, t: "Quel film de Satoshi Kon suit une idole pop harcelée, entre réalité et illusion ?", a: "Perfect Blue", x: ["Paprika", "Tokyo Godfathers", "Millennium Actress"] },
  { id: "jpcine-p8", d: 4, t: "Quel film d'horreur japonais de 1999 met en scène une audition qui vire au cauchemar ?", a: "Audition", x: ["Ring", "Ju-on", "Dark Water"] },
  { id: "jpcine-p9", d: 4, t: "Pour quel film Ken Watanabe a-t-il été nommé à l'Oscar face à Tom Cruise ?", a: "Le Dernier Samouraï", x: ["Lettres d'Iwo Jima", "Inception", "Memoirs of a Geisha"], acc: ["le dernier samouraï", "the last samurai"] },
  { id: "jpcine-p10", d: 4, t: "Quel film japonais a remporté l'Oscar du meilleur film international en 2022 ?", a: "Drive My Car", x: ["Une affaire de famille", "Shoplifters", "Departures"] },
  { id: "jpcine-p11", d: 4, t: "Quel film japonais a remporté l'Oscar du meilleur film en langue étrangère en 2009 ?", a: "Departures", x: ["Drive My Car", "Une affaire de famille", "Rashômon"], acc: ["departures", "okuribito"] },
  { id: "jpcine-p12", d: 4, t: "Quel réalisateur a signé « Drive My Car », d'après une nouvelle de Haruki Murakami ?", a: "Ryusuke Hamaguchi", x: ["Hirokazu Kore-eda", "Kiyoshi Kurosawa", "Naomi Kawase"] },
  { id: "jpcine-p13", d: 4, t: "Quel réalisateur japonais a reçu un Oscar d'honneur en 1990 pour l'ensemble de son œuvre ?", a: "Akira Kurosawa", x: ["Yasujirō Ozu", "Kenji Mizoguchi", "Nagisa Ōshima"] },
  { id: "jpcine-p14", d: 4, t: "Quel réalisateur a signé « L'Empire des sens », film sulfureux de 1976 ?", a: "Nagisa Ōshima", x: ["Shohei Imamura", "Kaneto Shindō", "Masaki Kobayashi"], acc: ["oshima", "nagisa oshima", "ōshima"] },
  { id: "jpcine-p15", d: 4, t: "Quel film d'horreur de 1964 de Kaneto Shindō met en scène un masque de démon dans les marais ?", a: "Onibaba", x: ["Kwaidan", "Kuroneko", "Ugetsu"], acc: ["onibaba"] },
  { id: "jpcine-p16", d: 4, t: "Quel film à sketches de 1964 de Masaki Kobayashi adapte des contes de fantômes ?", a: "Kwaidan", x: ["Onibaba", "Ugetsu", "Jigoku"], acc: ["kwaidan", "kaidan"] },
  { id: "jpcine-p17", d: 4, t: "Quel réalisateur de Ghibli a signé « Le Conte de la princesse Kaguya » ?", a: "Isao Takahata", x: ["Hayao Miyazaki", "Hiromasa Yonebayashi", "Gorō Miyazaki"] },
  { id: "jpcine-p18", d: 4, t: "Quel film de Ghibli suit une petite emprunteuse de quelques centimètres ?", a: "Arrietty", x: ["Ponyo", "Le Château ambulant", "Souvenirs goutte à goutte"], acc: ["arrietty"] },
  { id: "jpcine-p19", d: 4, t: "Quel film de Kore-eda suit quatre enfants abandonnés livrés à eux-mêmes à Tokyo ?", a: "Nobody Knows", x: ["Une affaire de famille", "Tel père, tel fils", "Still Walking"], acc: ["nobody knows"] },
  { id: "jpcine-p20", d: 4, t: "Quel film d'animation de Mamoru Hosoda réinvente la Belle et la Bête dans un monde virtuel ?", a: "Belle", x: ["Summer Wars", "Les Enfants loups", "Le Garçon et la Bête"], acc: ["belle"] },
]);
