import { universe } from "../_build";

export const culturejaponaise = universe("japon", "Culture japonaise", [
  // --- Faciles (5) ---
  { id: "jpcult-f1", d: 1, t: "Quelle est la capitale du Japon ?", a: "Tokyo", x: ["Kyoto", "Osaka", "Nagoya"] },
  { id: "jpcult-f2", d: 1, t: "Quel est le plus haut sommet du Japon, un volcan sacré ?", a: "Le mont Fuji", x: ["Le mont Aso", "Le mont Koya", "Le mont Hiei"], acc: ["mont fuji", "fuji", "fujisan"] },
  { id: "jpcult-f3", d: 1, t: "Quelle fleur rose, symbole du Japon, est célébrée au printemps ?", a: "La fleur de cerisier", x: ["La pivoine", "Le chrysanthème", "Le lotus"], acc: ["cerisier", "sakura", "fleur de cerisier"] },
  { id: "jpcult-f4", d: 1, t: "Quelle est la monnaie du Japon ?", a: "Le yen", x: ["Le won", "Le yuan", "Le baht"], acc: ["yen"] },
  { id: "jpcult-f5", d: 1, t: "Quel vêtement traditionnel japonais s'attache avec une large ceinture appelée obi ?", a: "Le kimono", x: ["Le hanbok", "Le sari", "Le qipao"], acc: ["kimono"] },
  // --- Moyennes (10) ---
  { id: "jpcult-m1", d: 2, t: "Comment appelle-t-on les guerriers de l'ancien Japon au code d'honneur strict ?", a: "Les samouraïs", x: ["Les ninjas", "Les shoguns", "Les ronins"], acc: ["samouraï", "samourai", "samouraïs"] },
  { id: "jpcult-m2", d: 2, t: "Comment appelle-t-on un samouraï sans maître ?", a: "Un ronin", x: ["Un ninja", "Un shogun", "Un daimyo"], acc: ["ronin"] },
  { id: "jpcult-m3", d: 2, t: "Quelle artiste et hôtesse traditionnelle se reconnaît à son maquillage blanc ?", a: "La geisha", x: ["La miko", "La maiko", "La kunoichi"], acc: ["geisha"] },
  { id: "jpcult-m4", d: 2, t: "Quelle religion animiste propre au Japon vénère les esprits appelés kami ?", a: "Le shintoisme", x: ["Le bouddhisme", "Le taoïsme", "Le confucianisme"], acc: ["shinto", "shintoïsme", "shintoisme"] },
  { id: "jpcult-m5", d: 2, t: "Comment appelle-t-on les portails rouges à l'entrée des sanctuaires shinto ?", a: "Le torii", x: ["La pagode", "Le tatami", "Le shoji"], acc: ["torii"] },
  { id: "jpcult-m6", d: 2, t: "Quel art japonais consiste à plier le papier ?", a: "L'origami", x: ["L'ikebana", "Le kirigami", "La calligraphie"], acc: ["origami"] },
  { id: "jpcult-m7", d: 2, t: "Quel art floral japonais compose des bouquets épurés ?", a: "L'ikebana", x: ["L'origami", "Le bonsaï", "Le kintsugi"], acc: ["ikebana"] },
  { id: "jpcult-m8", d: 2, t: "Comment appelle-t-on les petits arbres cultivés en pot et taillés ?", a: "Les bonsaïs", x: ["Les ikebanas", "Les origamis", "Les tatamis"], acc: ["bonsaï", "bonsai", "bonsaïs"] },
  { id: "jpcult-m9", d: 2, t: "Comment appelle-t-on la lutte traditionnelle japonaise entre colosses ?", a: "Le sumo", x: ["Le judo", "Le kendo", "L'aïkido"], acc: ["sumo"] },
  { id: "jpcult-m10", d: 2, t: "Quel train à grande vitesse japonais est surnommé le « train-balle » ?", a: "Le Shinkansen", x: ["Le Maglev", "Le TGV", "Le Nozomi"], acc: ["shinkansen"] },
  // --- Dures (15) ---
  { id: "jpcult-d1", d: 3, t: "Quel titre portait le chef militaire qui gouvernait le Japon au nom de l'empereur ?", a: "Le shogun", x: ["Le daimyo", "Le samouraï", "Le mikado"], acc: ["shogun", "shogoun"] },
  { id: "jpcult-d2", d: 3, t: "Comment appelle-t-on les seigneurs féodaux du Japon ?", a: "Les daimyos", x: ["Les shoguns", "Les ronins", "Les kami"], acc: ["daimyo", "daimyos"] },
  { id: "jpcult-d3", d: 3, t: "Quelle ère a marqué l'ouverture et la modernisation du Japon à partir de 1868 ?", a: "L'ère Meiji", x: ["L'ère Edo", "L'ère Showa", "L'ère Heisei"], acc: ["meiji", "ère meiji"] },
  { id: "jpcult-d4", d: 3, t: "Sous quel nom Tokyo était-elle connue avant 1868 ?", a: "Edo", x: ["Kyoto", "Nara", "Heian"], acc: ["edo"] },
  { id: "jpcult-d5", d: 3, t: "Comment appelle-t-on le suicide rituel par éventration des samouraïs ?", a: "Le seppuku", x: ["Le kamikaze", "Le bushido", "Le kabuki"], acc: ["seppuku", "hara-kiri", "harakiri"] },
  { id: "jpcult-d6", d: 3, t: "Comment appelle-t-on le code d'honneur des samouraïs ?", a: "Le bushido", x: ["Le seppuku", "Le shinto", "Le zen"], acc: ["bushido"] },
  { id: "jpcult-d7", d: 3, t: "Quelle cérémonie codifiée met à l'honneur le thé matcha ?", a: "La cérémonie du thé", x: ["L'ikebana", "Le kabuki", "Le hanami"], acc: ["cérémonie du thé", "chanoyu", "chado"] },
  { id: "jpcult-d8", d: 3, t: "Comment appelle-t-on la contemplation des cerisiers en fleurs au printemps ?", a: "Le hanami", x: ["Le matsuri", "Le hatsumode", "L'obon"], acc: ["hanami"] },
  { id: "jpcult-d9", d: 3, t: "Quel théâtre japonais traditionnel utilise des masques et des mouvements lents ?", a: "Le nô", x: ["Le kabuki", "Le bunraku", "Le rakugo"], acc: ["nô", "no", "noh"] },
  { id: "jpcult-d10", d: 3, t: "Quel théâtre japonais utilise de grandes marionnettes manipulées à vue ?", a: "Le bunraku", x: ["Le nô", "Le kabuki", "Le rakugo"], acc: ["bunraku"] },
  { id: "jpcult-d11", d: 3, t: "Quel art de réparer la céramique brisée avec de l'or en sublime les fêlures ?", a: "Le kintsugi", x: ["Le raku", "L'ikebana", "L'origami"], acc: ["kintsugi"] },
  { id: "jpcult-d12", d: 3, t: "Combien de syllabes compte un haïku, poème japonais traditionnel ?", a: "Dix-sept", x: ["Quatorze", "Trente et une", "Cinq"], acc: ["17", "dix-sept"] },
  { id: "jpcult-d13", d: 3, t: "Quels sont les deux syllabaires de l'écriture japonaise, avec les kanji ?", a: "Hiragana et katakana", x: ["Hangeul et hanja", "Pinyin et zhuyin", "Kana et romaji"], acc: ["hiragana et katakana"] },
  { id: "jpcult-d14", d: 3, t: "De quelle grande civilisation le Japon a-t-il emprunté les caractères kanji ?", a: "La Chine", x: ["La Corée", "L'Inde", "La Mongolie"], acc: ["chine", "chinoise"] },
  { id: "jpcult-d15", d: 3, t: "Comment appelle-t-on les fêtes populaires japonaises, avec stands et défilés ?", a: "Les matsuri", x: ["Les hanami", "Les obon", "Les onsen"], acc: ["matsuri"] },
  // --- Pro (20) ---
  { id: "jpcult-p1", d: 4, t: "Comment appelle-t-on les sources thermales japonaises ?", a: "Les onsen", x: ["Les sento", "Les ryokan", "Les matsuri"], acc: ["onsen"] },
  { id: "jpcult-p2", d: 4, t: "Comment appelle-t-on une auberge traditionnelle japonaise avec tatamis et futons ?", a: "Un ryokan", x: ["Un onsen", "Un minshuku", "Un konbini"], acc: ["ryokan"] },
  { id: "jpcult-p3", d: 4, t: "Quelle est la plus grande des îles principales du Japon ?", a: "Honshu", x: ["Hokkaido", "Kyushu", "Shikoku"], acc: ["honshu", "honshū"] },
  { id: "jpcult-p4", d: 4, t: "Quelle île du nord du Japon est réputée pour sa neige et ses paysages sauvages ?", a: "Hokkaido", x: ["Kyushu", "Shikoku", "Okinawa"], acc: ["hokkaido", "hokkaidō"] },
  { id: "jpcult-p5", d: 4, t: "Quel peuple autochtone vit historiquement dans le nord du Japon, à Hokkaido ?", a: "Les Aïnous", x: ["Les Ryukyu", "Les Yamato", "Les Han"], acc: ["aïnous", "ainu", "aïnou"] },
  { id: "jpcult-p6", d: 4, t: "Comment s'appelle l'empereur du Japon monté sur le trône en 2019 ?", a: "Naruhito", x: ["Akihito", "Hirohito", "Fumihito"], acc: ["naruhito"] },
  { id: "jpcult-p7", d: 4, t: "Quel nom porte l'ère du Japon depuis 2019 ?", a: "Reiwa", x: ["Heisei", "Showa", "Meiji"], acc: ["reiwa"] },
  { id: "jpcult-p8", d: 4, t: "Quel séisme et tsunami de 2011 a provoqué la catastrophe nucléaire de Fukushima ?", a: "Le séisme de Tōhoku", x: ["Le séisme de Kobe", "Le séisme du Kanto", "Le séisme de Nankai"], acc: ["tohoku", "tōhoku", "séisme de tohoku"] },
  { id: "jpcult-p9", d: 4, t: "Quel quartier de Tokyo est célèbre pour son carrefour parmi les plus fréquentés du monde ?", a: "Shibuya", x: ["Shinjuku", "Akihabara", "Ginza"], acc: ["shibuya"] },
  { id: "jpcult-p10", d: 4, t: "Quel quartier de Tokyo est le paradis de l'électronique et de la culture otaku ?", a: "Akihabara", x: ["Shibuya", "Harajuku", "Ginza"], acc: ["akihabara", "akiba"] },
  { id: "jpcult-p11", d: 4, t: "Quel quartier de Tokyo symbolise la mode excentrique des jeunes ?", a: "Harajuku", x: ["Ginza", "Roppongi", "Asakusa"], acc: ["harajuku"] },
  { id: "jpcult-p12", d: 4, t: "Quelle ancienne capitale impériale est célèbre pour ses temples et ses geishas ?", a: "Kyoto", x: ["Nara", "Osaka", "Kamakura"], acc: ["kyoto", "kyōto"] },
  { id: "jpcult-p13", d: 4, t: "Quelle ancienne capitale est célèbre pour ses daims en liberté et son grand Bouddha ?", a: "Nara", x: ["Kyoto", "Kamakura", "Nikko"], acc: ["nara"] },
  { id: "jpcult-p14", d: 4, t: "Quel jeu de plateau, dit « échecs japonais », se joue avec des pièces réutilisables ?", a: "Le shogi", x: ["Le go", "Le mah-jong", "Le xiangqi"], acc: ["shogi"] },
  { id: "jpcult-p15", d: 4, t: "Quel jeu de pions noirs et blancs, d'origine chinoise, est très pratiqué au Japon ?", a: "Le go", x: ["Le shogi", "Le mah-jong", "Le renju"], acc: ["go", "igo"] },
  { id: "jpcult-p16", d: 4, t: "Comment appelle-t-on le tapis de paille de riz qui couvre le sol des pièces traditionnelles ?", a: "Le tatami", x: ["Le futon", "Le shoji", "Le fusuma"], acc: ["tatami"] },
  { id: "jpcult-p17", d: 4, t: "Comment appelle-t-on les cloisons coulissantes en papier des maisons japonaises ?", a: "Les shoji", x: ["Les tatamis", "Les futons", "Les torii"], acc: ["shoji", "shōji"] },
  { id: "jpcult-p18", d: 4, t: "Quelle philosophie bouddhiste, prônant la méditation, a profondément marqué le Japon ?", a: "Le zen", x: ["Le taoïsme", "Le shinto", "Le confucianisme"], acc: ["zen"] },
  { id: "jpcult-p19", d: 4, t: "Comment appelle-t-on les pilotes japonais qui menaient des attaques-suicides en 1944-1945 ?", a: "Les kamikazes", x: ["Les samouraïs", "Les ronins", "Les ninjas"], acc: ["kamikaze", "kamikazes"] },
  { id: "jpcult-p20", d: 4, t: "Quelle déesse du soleil est la divinité la plus importante du shinto ?", a: "Amaterasu", x: ["Susanoo", "Tsukuyomi", "Izanami"], acc: ["amaterasu"] },
]);
