import { universe } from "../_build";

export const gastronomiejaponaise = universe("japon", "Gastronomie japonaise", [
  // --- Faciles (5) ---
  { id: "jpfood-f1", d: 1, t: "Quel plat japonais associe riz vinaigré et poisson cru ?", a: "Le sushi", x: ["Le ramen", "La tempura", "Le curry"], acc: ["sushi"] },
  { id: "jpfood-f2", d: 1, t: "Comment appelle-t-on de fines tranches de poisson cru servies sans riz ?", a: "Le sashimi", x: ["Le sushi", "Le maki", "Le nigiri"], acc: ["sashimi"] },
  { id: "jpfood-f3", d: 1, t: "Quelle soupe de nouilles est un plat japonais réconfortant très populaire ?", a: "Le ramen", x: ["Le pho", "Le pad thaï", "Le bibimbap"], acc: ["ramen"] },
  { id: "jpfood-f4", d: 1, t: "Avec quel ustensile mange-t-on traditionnellement au Japon ?", a: "Les baguettes", x: ["La fourchette", "La cuillère", "Le couteau"], acc: ["baguettes", "hashi"] },
  { id: "jpfood-f5", d: 1, t: "Quelle boisson alcoolisée japonaise est un alcool de riz ?", a: "Le saké", x: ["Le soju", "Le baijiu", "Le mirin"], acc: ["saké", "sake"] },
  // --- Moyennes (10) ---
  { id: "jpfood-m1", d: 2, t: "Comment appelle-t-on les beignets japonais de légumes ou crevettes en friture légère ?", a: "La tempura", x: ["Le gyoza", "Le katsu", "Le takoyaki"], acc: ["tempura"] },
  { id: "jpfood-m2", d: 2, t: "Quelles boulettes frites garnies de poulpe sont une spécialité d'Osaka ?", a: "Les takoyaki", x: ["Les gyoza", "Les onigiri", "Les dango"], acc: ["takoyaki"] },
  { id: "jpfood-m3", d: 2, t: "Comment appelle-t-on les raviolis japonais poêlés, souvent au porc ?", a: "Les gyoza", x: ["Les takoyaki", "Les nigiri", "Les mochi"], acc: ["gyoza"] },
  { id: "jpfood-m4", d: 2, t: "Comment appelle-t-on les boulettes de riz triangulaires, souvent enveloppées d'algue ?", a: "Les onigiri", x: ["Les mochi", "Les gyoza", "Les maki"], acc: ["onigiri"] },
  { id: "jpfood-m5", d: 2, t: "Quelle pâte de soja fermentée sert de base à une soupe japonaise ?", a: "Le miso", x: ["Le tofu", "Le natto", "Le dashi"], acc: ["miso"] },
  { id: "jpfood-m6", d: 2, t: "Quelle feuille d'algue séchée enveloppe les makis ?", a: "Le nori", x: ["Le wakame", "Le kombu", "Le konjac"], acc: ["nori"] },
  { id: "jpfood-m7", d: 2, t: "Quel condiment vert et très piquant accompagne les sushis ?", a: "Le wasabi", x: ["Le gingembre", "Le yuzu", "Le shiso"], acc: ["wasabi"] },
  { id: "jpfood-m8", d: 2, t: "Quelle pâte de riz gluant sucrée forme de petits gâteaux, parfois fourrés de glace ?", a: "Le mochi", x: ["Le dango", "Le dorayaki", "Le taiyaki"], acc: ["mochi"] },
  { id: "jpfood-m9", d: 2, t: "Quel plat de nouilles épaisses de blé se mange chaud ou froid ?", a: "L'udon", x: ["Le soba", "Le ramen", "Le somen"], acc: ["udon"] },
  { id: "jpfood-m10", d: 2, t: "Quelles nouilles fines de sarrasin sont un classique japonais ?", a: "Le soba", x: ["L'udon", "Le ramen", "Le somen"], acc: ["soba"] },
  // --- Dures (15) ---
  { id: "jpfood-d1", d: 3, t: "Quel thé vert en poudre est utilisé dans la cérémonie du thé ?", a: "Le matcha", x: ["Le sencha", "Le hojicha", "Le genmaicha"], acc: ["matcha"] },
  { id: "jpfood-d2", d: 3, t: "Comment appelle-t-on la fondue japonaise où l'on cuit de fines tranches de viande dans un bouillon ?", a: "Le shabu-shabu", x: ["Le sukiyaki", "Le nabe", "Le teppanyaki"], acc: ["shabu-shabu", "shabu shabu"] },
  { id: "jpfood-d3", d: 3, t: "Quel plat mijoté à table, à base de bœuf et de sauce sucrée-salée, existe au Japon ?", a: "Le sukiyaki", x: ["Le shabu-shabu", "Le yakitori", "Le donburi"], acc: ["sukiyaki"] },
  { id: "jpfood-d4", d: 3, t: "Comment appelle-t-on les brochettes de poulet grillées, spécialité des izakaya ?", a: "Les yakitori", x: ["Les takoyaki", "Les tempura", "Les gyoza"], acc: ["yakitori"] },
  { id: "jpfood-d5", d: 3, t: "Comment appelle-t-on les bars-restaurants conviviaux japonais où l'on boit et grignote ?", a: "Les izakaya", x: ["Les ryokan", "Les onsen", "Les konbini"], acc: ["izakaya"] },
  { id: "jpfood-d6", d: 3, t: "Comment appelle-t-on un bol de riz garni, par exemple d'une escalope panée ou de bœuf ?", a: "Le donburi", x: ["Le bento", "Le onigiri", "Le chirashi"], acc: ["donburi"] },
  { id: "jpfood-d7", d: 3, t: "Comment appelle-t-on le repas japonais présenté dans une boîte compartimentée ?", a: "Le bento", x: ["Le donburi", "Le teishoku", "Le kaiseki"], acc: ["bento"] },
  { id: "jpfood-d8", d: 3, t: "Quelle escalope de porc panée et frite est un classique japonais ?", a: "Le tonkatsu", x: ["Le karaage", "Le korokke", "Le menchi katsu"], acc: ["tonkatsu"] },
  { id: "jpfood-d9", d: 3, t: "Comment appelle-t-on le poulet frit japonais mariné, en petits morceaux ?", a: "Le karaage", x: ["Le tonkatsu", "Le korokke", "La tempura"], acc: ["karaage"] },
  { id: "jpfood-d10", d: 3, t: "Quelle galette garnie cuite sur plaque est une spécialité d'Osaka et Hiroshima ?", a: "L'okonomiyaki", x: ["Le takoyaki", "Le monjayaki", "Le yakisoba"], acc: ["okonomiyaki"] },
  { id: "jpfood-d11", d: 3, t: "Quel bouillon de base, à l'algue kombu et à la bonite séchée, parfume la cuisine japonaise ?", a: "Le dashi", x: ["Le miso", "Le ponzu", "Le mirin"], acc: ["dashi"] },
  { id: "jpfood-d12", d: 3, t: "Comment appelle-t-on la haute cuisine japonaise raffinée, en plusieurs petits plats ?", a: "Le kaiseki", x: ["Le teishoku", "Le donburi", "L'izakaya"], acc: ["kaiseki"] },
  { id: "jpfood-d13", d: 3, t: "Quel poisson potentiellement mortel, préparé par des chefs agréés, est un mets recherché ?", a: "Le fugu", x: ["Le thon", "L'anguille", "Le maquereau"], acc: ["fugu"] },
  { id: "jpfood-d14", d: 3, t: "Comment appelle-t-on l'anguille grillée et laquée, souvent servie sur du riz ?", a: "L'unagi", x: ["Le fugu", "Le saba", "L'ika"], acc: ["unagi"] },
  { id: "jpfood-d15", d: 3, t: "Quelle boisson alcoolisée japonaise distillée est plus forte que le saké ?", a: "Le shochu", x: ["Le mirin", "L'umeshu", "Le sencha"], acc: ["shochu", "shōchū"] },
  // --- Pro (20) ---
  { id: "jpfood-p1", d: 4, t: "Comment appelle-t-on les épiceries de proximité ouvertes en continu au Japon ?", a: "Les konbini", x: ["Les izakaya", "Les depachika", "Les yatai"], acc: ["konbini", "kombini"] },
  { id: "jpfood-p2", d: 4, t: "Comment appelle-t-on les stands de rue ambulants au Japon ?", a: "Les yatai", x: ["Les konbini", "Les izakaya", "Les depachika"], acc: ["yatai"] },
  { id: "jpfood-p3", d: 4, t: "Quel bouillon riche de ramen, à base d'os de porc, est typique de Kyushu ?", a: "Le tonkotsu", x: ["Le shoyu", "Le shio", "Le miso"], acc: ["tonkotsu"] },
  { id: "jpfood-p4", d: 4, t: "Quel style de ramen à la sauce soja est le plus classique à Tokyo ?", a: "Le shoyu ramen", x: ["Le tonkotsu ramen", "Le shio ramen", "Le miso ramen"], acc: ["shoyu", "shoyu ramen"] },
  { id: "jpfood-p5", d: 4, t: "Quel condiment liquide sucré, à base de riz, est un ingrédient clé de la cuisine japonaise ?", a: "Le mirin", x: ["Le dashi", "Le ponzu", "Le shochu"], acc: ["mirin"] },
  { id: "jpfood-p6", d: 4, t: "Quel plat de nouilles sautées, vendu dans les festivals, ressemble aux nouilles chinoises ?", a: "Le yakisoba", x: ["L'udon", "Le soba", "Le somen"], acc: ["yakisoba"] },
  { id: "jpfood-p7", d: 4, t: "Quel gâteau en forme de poisson, fourré de pâte de haricots rouges, se vend dans la rue ?", a: "Le taiyaki", x: ["Le dorayaki", "Le mochi", "Le dango"], acc: ["taiyaki"] },
  { id: "jpfood-p8", d: 4, t: "Quel dessert de deux pancakes fourrés de haricot rouge est adoré de Doraemon ?", a: "Le dorayaki", x: ["Le taiyaki", "Le mochi", "Le manju"], acc: ["dorayaki"] },
  { id: "jpfood-p9", d: 4, t: "Comment appelle-t-on la pâte sucrée de haricots rouges des pâtisseries japonaises ?", a: "L'anko", x: ["Le mochi", "Le matcha", "Le kinako"], acc: ["anko"] },
  { id: "jpfood-p10", d: 4, t: "Comment appelle-t-on les pâtisseries traditionnelles japonaises servies avec le thé ?", a: "Les wagashi", x: ["Les mochi", "Les dango", "Les taiyaki"], acc: ["wagashi"] },
  { id: "jpfood-p11", d: 4, t: "Quelles brochettes de boulettes de riz gluant, souvent tricolores, se mangent en dessert ?", a: "Les dango", x: ["Les mochi", "Les taiyaki", "Les manju"], acc: ["dango"] },
  { id: "jpfood-p12", d: 4, t: "Quel agrume japonais parfumé, jaune, est très prisé en cuisine ?", a: "Le yuzu", x: ["Le sudachi", "Le kabosu", "Le daidai"], acc: ["yuzu"] },
  { id: "jpfood-p13", d: 4, t: "Quelle sauce ponctuée d'agrume accompagne fondues et grillades ?", a: "Le ponzu", x: ["Le teriyaki", "Le tonkatsu", "Le dashi"], acc: ["ponzu"] },
  { id: "jpfood-p14", d: 4, t: "Comment appelle-t-on la sauce sucrée-salée laquée pour glacer viandes et poissons ?", a: "La sauce teriyaki", x: ["La sauce ponzu", "La sauce tonkatsu", "La sauce yakiniku"], acc: ["teriyaki"] },
  { id: "jpfood-p15", d: 4, t: "Quelle préparation de soja fermenté, gluante et odorante, divise même les Japonais ?", a: "Le natto", x: ["Le tofu", "Le miso", "L'edamame"], acc: ["natto", "nattō"] },
  { id: "jpfood-p16", d: 4, t: "Comment appelle-t-on les jeunes fèves de soja bouillies servies à l'apéritif ?", a: "Les edamame", x: ["Le natto", "Le tofu", "Le konjac"], acc: ["edamame"] },
  { id: "jpfood-p17", d: 4, t: "Quel plat de riz au curry, importé puis adapté, est un classique du quotidien japonais ?", a: "Le curry japonais", x: ["Le donburi", "Le chirashi", "Le gyudon"], acc: ["curry japonais", "kare raisu"] },
  { id: "jpfood-p18", d: 4, t: "Quel bol de riz garni de fines tranches de bœuf mijoté est un fast-food japonais ?", a: "Le gyudon", x: ["Le katsudon", "L'oyakodon", "Le tendon"], acc: ["gyudon"] },
  { id: "jpfood-p19", d: 4, t: "Quel bol associe poulet et œuf sur du riz, un nom signifiant « parent-enfant » ?", a: "L'oyakodon", x: ["Le gyudon", "Le katsudon", "Le tendon"], acc: ["oyakodon"] },
  { id: "jpfood-p20", d: 4, t: "Quelle glace pilée nappée de sirop coloré est un dessert d'été japonais ?", a: "Le kakigori", x: ["Le mochi glacé", "Le dango", "L'anmitsu"], acc: ["kakigori", "kakigōri"] },
]);
