import { universe } from "../_build";

export const musiquejaponaise = universe("japon", "Musique japonaise", [
  // --- Faciles (5) ---
  { id: "jpmus-f1", d: 1, t: "Comment appelle-t-on la musique pop japonaise ?", a: "La J-pop", x: ["La K-pop", "La C-pop", "La J-rock"], acc: ["j-pop", "jpop"] },
  { id: "jpmus-f2", d: 1, t: "Quel instrument à trois cordes se joue avec un grand plectre, le bachi ?", a: "Le shamisen", x: ["Le koto", "Le shakuhachi", "Le biwa"], acc: ["shamisen"] },
  { id: "jpmus-f3", d: 1, t: "Quelle flûte en bambou est un instrument traditionnel japonais ?", a: "Le shakuhachi", x: ["Le shamisen", "Le koto", "Le taiko"], acc: ["shakuhachi"] },
  { id: "jpmus-f4", d: 1, t: "Comment appelle-t-on les grands tambours japonais joués lors des festivals ?", a: "Les taiko", x: ["Les koto", "Les shamisen", "Les biwa"], acc: ["taiko"] },
  { id: "jpmus-f5", d: 1, t: "Quel loisir de chant sur bande, très populaire, est né au Japon ?", a: "Le karaoké", x: ["Le blind test", "Le playback", "Le a cappella"], acc: ["karaoké", "karaoke"] },
  // --- Moyennes (10) ---
  { id: "jpmus-m1", d: 2, t: "Quel groupe de rock japonais, pionnier du visual kei, a marqué les années 80-90 ?", a: "X Japan", x: ["B'z", "Glay", "L'Arc-en-Ciel"], acc: ["x japan"] },
  { id: "jpmus-m2", d: 2, t: "Quel duo est le groupe le plus vendeur de l'histoire de la musique japonaise ?", a: "B'z", x: ["X Japan", "Mr. Children", "Southern All Stars"], acc: ["b'z"] },
  { id: "jpmus-m3", d: 2, t: "Quelle chanteuse, surnommée l'impératrice de la pop japonaise, a régné sur les années 2000 ?", a: "Ayumi Hamasaki", x: ["Namie Amuro", "Hikaru Utada", "Kumi Koda"] },
  { id: "jpmus-m4", d: 2, t: "Quelle chanteuse née aux États-Unis a battu des records avec l'album « First Love » ?", a: "Hikaru Utada", x: ["Ayumi Hamasaki", "Namie Amuro", "Kyary Pamyu Pamyu"], acc: ["utada", "hikaru utada", "utada hikaru"] },
  { id: "jpmus-m5", d: 2, t: "Quel courant du rock japonais mise sur le maquillage et les costumes extravagants ?", a: "Le visual kei", x: ["Le city pop", "Le shibuya-kei", "L'enka"], acc: ["visual kei"] },
  { id: "jpmus-m6", d: 2, t: "Quel style de chanson japonaise sentimentale et traditionnelle rappelle un blues nippon ?", a: "L'enka", x: ["Le city pop", "La J-pop", "Le visual kei"], acc: ["enka"] },
  { id: "jpmus-m7", d: 2, t: "Quel groupe de rock japonais très populaire porte un nom français d'arc-en-ciel ?", a: "L'Arc-en-Ciel", x: ["Glay", "X Japan", "Luna Sea"], acc: ["l'arc-en-ciel", "larc en ciel"] },
  { id: "jpmus-m8", d: 2, t: "Quel groupe de garçons de l'agence Johnny's, à cinq membres, a dominé la J-pop des années 2000-2010 ?", a: "Arashi", x: ["SMAP", "KAT-TUN", "News"], acc: ["arashi"] },
  { id: "jpmus-m9", d: 2, t: "Quel boys band Johnny's, dissous en 2016, comptait Takuya Kimura ?", a: "SMAP", x: ["Arashi", "TOKIO", "V6"], acc: ["smap"] },
  { id: "jpmus-m10", d: 2, t: "Quel genre musical japonais des années 80, redevenu culte, évoque la ville et l'insouciance ?", a: "Le city pop", x: ["Le visual kei", "L'enka", "Le shibuya-kei"], acc: ["city pop"] },
  // --- Dures (15) ---
  { id: "jpmus-d1", d: 3, t: "Quelle chanson de 1963 de Kyu Sakamoto fut n°1 aux États-Unis sous le titre « Sukiyaki » ?", a: "Ue o Muite Arukō", x: ["Sakura Sakura", "Kojo no Tsuki", "Kawa no Nagare no Yō ni"], acc: ["sukiyaki", "ue o muite aruko"] },
  { id: "jpmus-d2", d: 3, t: "Quel morceau de city pop de Mariya Takeuchi est devenu viral des décennies plus tard ?", a: "Plastic Love", x: ["Stay With Me", "Ride on Time", "Mayonaka no Door"], acc: ["plastic love"] },
  { id: "jpmus-d3", d: 3, t: "Quelle chanteuse de city pop a chanté « Mayonaka no Door / Stay With Me » ?", a: "Miki Matsubara", x: ["Mariya Takeuchi", "Anri", "Taeko Ohnuki"], acc: ["miki matsubara"] },
  { id: "jpmus-d4", d: 3, t: "Quel compositeur japonais a signé les musiques des films Ghibli de Miyazaki ?", a: "Joe Hisaishi", x: ["Ryuichi Sakamoto", "Yoko Kanno", "Kenji Kawai"] },
  { id: "jpmus-d5", d: 3, t: "Quel musicien, membre du Yellow Magic Orchestra, a composé « Merry Christmas Mr. Lawrence » ?", a: "Ryuichi Sakamoto", x: ["Joe Hisaishi", "Haruomi Hosono", "Isao Tomita"] },
  { id: "jpmus-d6", d: 3, t: "Quel groupe électronique pionnier des années 70-80, avec Ryuichi Sakamoto, a influencé la techno ?", a: "Yellow Magic Orchestra", x: ["Kraftwerk", "Perfume", "Denki Groove"], acc: ["yellow magic orchestra", "ymo"] },
  { id: "jpmus-d7", d: 3, t: "Quelle compositrice a signé les musiques de « Cowboy Bebop » et de « Ghost in the Shell: SAC » ?", a: "Yoko Kanno", x: ["Joe Hisaishi", "Kenji Kawai", "Yuki Kajiura"] },
  { id: "jpmus-d8", d: 3, t: "Quel trio féminin de technopop, aux voix modifiées, est produit par Yasutaka Nakata ?", a: "Perfume", x: ["Babymetal", "AKB48", "Scandal"], acc: ["perfume"] },
  { id: "jpmus-d9", d: 3, t: "Quel groupe japonais mêle idols et heavy metal, avec « Gimme Chocolate!! » ?", a: "Babymetal", x: ["Perfume", "Band-Maid", "Scandal"], acc: ["babymetal"] },
  { id: "jpmus-d10", d: 3, t: "Quelle chanteuse pop kawaii à l'univers coloré a chanté « PonPonPon » ?", a: "Kyary Pamyu Pamyu", x: ["Perfume", "Kumi Koda", "Ayumi Hamasaki"], acc: ["kyary pamyu pamyu"] },
  { id: "jpmus-d11", d: 3, t: "Quel groupe de rock a chanté « GO!!! », générique de « Naruto » ?", a: "Flow", x: ["Asian Kung-Fu Generation", "Uverworld", "Ikimono-gakari"], acc: ["flow"] },
  { id: "jpmus-d12", d: 3, t: "Quel groupe de rock a signé « Rewrite », générique de « Fullmetal Alchemist » ?", a: "Asian Kung-Fu Generation", x: ["Flow", "L'Arc-en-Ciel", "Uverworld"], acc: ["asian kung-fu generation", "ajikan"] },
  { id: "jpmus-d13", d: 3, t: "Quel groupe pop-rock, énorme dans les années 2000, est surnommé « Misuchiru » ?", a: "Mr. Children", x: ["Bump of Chicken", "Spitz", "Glay"], acc: ["mr. children", "mr children", "misuchiru"] },
  { id: "jpmus-d14", d: 3, t: "Quel producteur est derrière Perfume, Kyary Pamyu Pamyu et le groupe Capsule ?", a: "Yasutaka Nakata", x: ["Tetsuya Komuro", "Ryuichi Sakamoto", "Joe Hisaishi"], acc: ["yasutaka nakata"] },
  { id: "jpmus-d15", d: 3, t: "Quel producteur star des années 90 a lancé Namie Amuro et TRF, dominant la J-pop ?", a: "Tetsuya Komuro", x: ["Yasutaka Nakata", "Johnny Kitagawa", "Ryuichi Sakamoto"], acc: ["tetsuya komuro"] },
  // --- Pro (20) ---
  { id: "jpmus-p1", d: 4, t: "Quel groupe de rock a été fondé par le batteur Yoshiki, figure du visual kei ?", a: "X Japan", x: ["Luna Sea", "Glay", "Dir en grey"], acc: ["x japan"] },
  { id: "jpmus-p2", d: 4, t: "Quelle chanteuse a interprété « First Love » et le thème de « Kingdom Hearts » ?", a: "Hikaru Utada", x: ["Ayumi Hamasaki", "Namie Amuro", "Kumi Koda"] },
  { id: "jpmus-p3", d: 4, t: "Quelle chanteuse, retirée en 2018, était la « reine de la J-pop » des années 90 ?", a: "Namie Amuro", x: ["Ayumi Hamasaki", "Hikaru Utada", "Seiko Matsuda"] },
  { id: "jpmus-p4", d: 4, t: "Quelle idole des années 80 est considérée comme l'archétype de l'idole japonaise ?", a: "Seiko Matsuda", x: ["Momoe Yamaguchi", "Akina Nakamori", "Kyoko Koizumi"] },
  { id: "jpmus-p5", d: 4, t: "Quelle chanteuse virtuelle, née d'un logiciel, remplit des salles avec ses hologrammes ?", a: "Hatsune Miku", x: ["Kizuna AI", "Gumi", "Kagamine Rin"], acc: ["hatsune miku", "miku"] },
  { id: "jpmus-p6", d: 4, t: "Quel logiciel de synthèse vocale est à l'origine de Hatsune Miku ?", a: "Vocaloid", x: ["UTAU", "Auto-Tune", "Synthesizer V"], acc: ["vocaloid"] },
  { id: "jpmus-p7", d: 4, t: "Quel duo pop des années 90, avec Tetsuya Komuro, a chanté « Departures » ?", a: "Globe", x: ["TRF", "Every Little Thing", "Do As Infinity"], acc: ["globe"] },
  { id: "jpmus-p8", d: 4, t: "Quel groupe pop-rock a explosé avec « Pretender » en 2019 ?", a: "Official Hige Dandism", x: ["King Gnu", "Vaundy", "Yoasobi"], acc: ["official hige dandism", "higedan"] },
  { id: "jpmus-p9", d: 4, t: "Quel duo, formé d'Ayase et de la chanteuse Ikura, a percé avec « Yoru ni Kakeru » ?", a: "Yoasobi", x: ["King Gnu", "Ado", "Eve"], acc: ["yoasobi"] },
  { id: "jpmus-p10", d: 4, t: "Quelle chanteuse masquée a interprété les chansons de « One Piece Film: Red » ?", a: "Ado", x: ["Yoasobi", "Aimer", "LiSA"], acc: ["ado"] },
  { id: "jpmus-p11", d: 4, t: "Quelle chanteuse a interprété « Gurenge », générique de « Demon Slayer » ?", a: "LiSA", x: ["Aimer", "Ado", "Eir Aoi"], acc: ["lisa"] },
  { id: "jpmus-p12", d: 4, t: "Quel groupe de rock a signé « Silhouette », générique de « Naruto Shippuden » ?", a: "Kana-Boon", x: ["Flow", "Asian Kung-Fu Generation", "Ikimono-gakari"], acc: ["kana-boon"] },
  { id: "jpmus-p13", d: 4, t: "Quel compositeur a signé la musique de la saga de jeux « Final Fantasy » ?", a: "Nobuo Uematsu", x: ["Koji Kondo", "Yoko Shimomura", "Yasunori Mitsuda"] },
  { id: "jpmus-p14", d: 4, t: "Quel compositeur a créé les thèmes musicaux de « Super Mario » et « Zelda » ?", a: "Koji Kondo", x: ["Nobuo Uematsu", "Yoko Shimomura", "Junichi Masuda"] },
  { id: "jpmus-p15", d: 4, t: "Quel guitariste de X Japan, star adulée du visual kei, est mort en 1998 ?", a: "hide", x: ["Yoshiki", "Toshi", "Taiji"], acc: ["hide"] },
  { id: "jpmus-p16", d: 4, t: "Quel festival de rock en plein air est le plus grand du Japon ?", a: "Le Fuji Rock Festival", x: ["Le Summer Sonic", "Le Rock in Japan", "Le Coachella"], acc: ["fuji rock"] },
  { id: "jpmus-p17", d: 4, t: "Quel concours de chant du Nouvel An oppose une équipe rouge et une équipe blanche à la NHK ?", a: "Le Kōhaku Uta Gassen", x: ["Le Music Station", "Le Count Down TV", "Le FNS Kayosai"], acc: ["kohaku", "kōhaku", "kohaku uta gassen"] },
  { id: "jpmus-p18", d: 4, t: "Quel puissant imprésario, fondateur de l'agence Johnny's, a façonné les boys bands japonais ?", a: "Johnny Kitagawa", x: ["Tetsuya Komuro", "Yasutaka Nakata", "Max Matsuura"], acc: ["johnny kitagawa"] },
  { id: "jpmus-p19", d: 4, t: "Quel groupe de pop-rock à voix féminine a chanté de nombreux génériques d'animes populaires ?", a: "Ikimono-gakari", x: ["Superfly", "Every Little Thing", "Scandal"], acc: ["ikimono-gakari"] },
  { id: "jpmus-p20", d: 4, t: "Comment appelle-t-on les internautes japonais qui reprennent des chansons sur Niconico ?", a: "Les utaite", x: ["Les seiyuu", "Les otaku", "Les vocaloid"], acc: ["utaite"] },
]);
