import { universe } from "../_build";

export const seriesjaponaises = universe("japon", "Séries japonaises", [
  // --- Faciles (5) ---
  { id: "jpserie-f1", d: 1, t: "De quelle série japonaise « tokusatsu » les Power Rangers américains sont-ils adaptés ?", a: "Super Sentai", x: ["Kamen Rider", "Ultraman", "Metal Heroes"], acc: ["super sentai"] },
  { id: "jpserie-f2", d: 1, t: "Quel héros géant de lumière combat des monstres kaiju dans une série japonaise culte ?", a: "Ultraman", x: ["Kamen Rider", "Godzilla", "Goldorak"], acc: ["ultraman"] },
  { id: "jpserie-f3", d: 1, t: "Quel justicier masqué à moto, sur le thème de l'insecte, est un héros tokusatsu ?", a: "Kamen Rider", x: ["Ultraman", "Super Sentai", "Metalder"], acc: ["kamen rider"] },
  { id: "jpserie-f4", d: 1, t: "Comment appelle-t-on les séries télévisées dramatiques japonaises ?", a: "Les dramas", x: ["Les telenovelas", "Les sitcoms", "Les soaps"], acc: ["drama", "dramas", "j-drama"] },
  { id: "jpserie-f5", d: 1, t: "Comment appelle-t-on les héros japonais en costumes colorés qui se transforment pour combattre le mal ?", a: "Les Sentai", x: ["Les Yokai", "Les Kaiju", "Les Kami"], acc: ["sentai", "super sentai"] },
  // --- Moyennes (10) ---
  { id: "jpserie-m1", d: 2, t: "Quel jeu télévisé japonais délirant, avec des épreuves physiques, était présenté par Takeshi Kitano ?", a: "Takeshi's Castle", x: ["Ninja Warrior", "Silent Library", "Gaki no Tsukai"], acc: ["takeshi's castle", "le château de takeshi"] },
  { id: "jpserie-m2", d: 2, t: "Quelle émission japonaise d'obstacles extrêmes est connue mondialement sous « Ninja Warrior » ?", a: "Sasuke", x: ["Takeshi's Castle", "Kunoichi", "Muscle Park"], acc: ["sasuke", "ninja warrior"] },
  { id: "jpserie-m3", d: 2, t: "En France, sous quel nom la série Super Sentai « Choudenshi Bioman » a-t-elle été diffusée ?", a: "Bioman", x: ["Bioforce", "X-Or", "Spielban"], acc: ["bioman"] },
  { id: "jpserie-m4", d: 2, t: "Quel héros, shérif de l'espace en armure, était diffusé en France sous « X-Or » ?", a: "Gavan", x: ["Sharivan", "Shaider", "Metalder"], acc: ["gavan", "x-or"] },
  { id: "jpserie-m5", d: 2, t: "Quel drama et film japonais suit un carnet de mort et le duel entre Light et L ?", a: "Death Note", x: ["Liar Game", "Alice in Borderland", "Gantz"], acc: ["death note"] },
  { id: "jpserie-m6", d: 2, t: "Quelle série Netflix japonaise met des joueurs face à des jeux mortels dans un Tokyo désert ?", a: "Alice in Borderland", x: ["Squid Game", "Liar Game", "Kaiji"], acc: ["alice in borderland"] },
  { id: "jpserie-m7", d: 2, t: "Quel drama japonais suit des joueurs piégés dans des jeux psychologiques truqués ?", a: "Liar Game", x: ["Alice in Borderland", "Kaiji", "Death Note"], acc: ["liar game"] },
  { id: "jpserie-m8", d: 2, t: "Quelle chaîne publique japonaise, l'équivalent de la BBC, produit des dramas historiques ?", a: "La NHK", x: ["Fuji TV", "TV Asahi", "TBS"], acc: ["nhk"] },
  { id: "jpserie-m9", d: 2, t: "Comment appelle-t-on les grands dramas historiques annuels de la NHK sur les samouraïs ?", a: "Les taiga dramas", x: ["Les asadora", "Les tokusatsu", "Les jidaigeki"], acc: ["taiga", "taiga drama"] },
  { id: "jpserie-m10", d: 2, t: "Comment appelle-t-on les dramas matinaux quotidiens de la NHK ?", a: "Les asadora", x: ["Les taiga", "Les dorama", "Les tokusatsu"], acc: ["asadora"] },
  // --- Dures (15) ---
  { id: "jpserie-d1", d: 3, t: "Quel drama de 2007 sur un pianiste et une cheffe d'orchestre, tiré d'un manga, a cartonné en Asie ?", a: "Nodame Cantabile", x: ["Hana Yori Dango", "Gokusen", "1 Litre de larmes"], acc: ["nodame cantabile"] },
  { id: "jpserie-d2", d: 3, t: "Quel drama tiré d'un manga suit une fille pauvre dans un lycée de riches, avec le groupe F4 ?", a: "Hana Yori Dango", x: ["Nodame Cantabile", "Itazura na Kiss", "Gokusen"], acc: ["hana yori dango"] },
  { id: "jpserie-d3", d: 3, t: "Quel drama émouvant de 2005 suit une adolescente atteinte d'une maladie dégénérative ?", a: "1 Litre de larmes", x: ["Hana Yori Dango", "Orange Days", "Beautiful Life"], acc: ["1 litre de larmes", "litre de larmes"] },
  { id: "jpserie-d4", d: 3, t: "Quelle prof au passé de yakuza enseigne à des élèves difficiles dans ce drama ?", a: "Gokusen", x: ["GTO", "Dragon Zakura", "Rookies"], acc: ["gokusen"] },
  { id: "jpserie-d5", d: 3, t: "Quel drama, adapté du manga « GTO », suit un ex-loubard devenu professeur ?", a: "GTO", x: ["Gokusen", "Dragon Zakura", "Rookies"], acc: ["gto", "great teacher onizuka"] },
  { id: "jpserie-d6", d: 3, t: "Quel super-héros géant, ennemi juré des kaiju, a débuté à la télé japonaise en 1966 ?", a: "Ultraman", x: ["Kamen Rider", "Godzilla", "Spectreman"] },
  { id: "jpserie-d7", d: 3, t: "Quel maître des effets spéciaux est le père d'Ultraman et de Godzilla à l'écran ?", a: "Eiji Tsuburaya", x: ["Ishirō Honda", "Shotaro Ishinomori", "Osamu Tezuka"], acc: ["tsuburaya"] },
  { id: "jpserie-d8", d: 3, t: "Quel mangaka est le créateur de Kamen Rider et de Super Sentai ?", a: "Shotaro Ishinomori", x: ["Osamu Tezuka", "Go Nagai", "Eiji Tsuburaya"], acc: ["ishinomori"] },
  { id: "jpserie-d9", d: 3, t: "Quelle sentai de 1975, première du genre, a lancé la longue lignée des Super Sentai ?", a: "Goranger", x: ["Bioman", "Zyuranger", "Goggle V"], acc: ["goranger", "gorenger"] },
  { id: "jpserie-d10", d: 3, t: "De quelle sentai japonaise « Zyuranger » les premiers « Power Rangers » sont-ils tirés ?", a: "Zyuranger", x: ["Goranger", "Bioman", "Dairanger"], acc: ["zyuranger"] },
  { id: "jpserie-d11", d: 3, t: "Quel drama de 2013 sur un banquier vengeur a lancé la réplique culte « je te rendrai au double » ?", a: "Hanzawa Naoki", x: ["Hero", "Doctor-X", "Galileo"], acc: ["hanzawa naoki"] },
  { id: "jpserie-d12", d: 3, t: "Quel drama policier suit un physicien génial surnommé « Galileo » aidant la police ?", a: "Galileo", x: ["Hero", "Doctor-X", "Unnatural"], acc: ["galileo"] },
  { id: "jpserie-d13", d: 3, t: "Quel drama suit une chirurgienne indépendante et surdouée qui n'échoue jamais ?", a: "Doctor-X", x: ["Code Blue", "Galileo", "Iryu"], acc: ["doctor-x", "doctor x"] },
  { id: "jpserie-d14", d: 3, t: "Quelle télé-réalité japonaise de Netflix sur la cohabitation de jeunes a connu un drame en 2020 ?", a: "Terrace House", x: ["Ainori", "Bachelor Japan", "Old Enough"], acc: ["terrace house"] },
  { id: "jpserie-d15", d: 3, t: "Quelle émission japonaise suit de très jeunes enfants faisant seuls leur première course ?", a: "Old Enough", x: ["Terrace House", "Takeshi's Castle", "Sasuke"], acc: ["old enough", "hajimete no otsukai"] },
  // --- Pro (20) ---
  { id: "jpserie-p1", d: 4, t: "Quel humoriste et cinéaste japonais présentait « Takeshi's Castle » ?", a: "Takeshi Kitano", x: ["Sonny Chiba", "George Tokoro", "Hitoshi Matsumoto"] },
  { id: "jpserie-p2", d: 4, t: "Quelle chaîne japonaise diffuse les Super Sentai et Kamen Rider le dimanche matin ?", a: "TV Asahi", x: ["NHK", "Fuji TV", "TBS"], acc: ["tv asahi"] },
  { id: "jpserie-p3", d: 4, t: "Quel bloc de programmes du dimanche matin regroupe Kamen Rider et Super Sentai ?", a: "Le Super Hero Time", x: ["Le Golden Time", "Le Noitamina", "Le Toonami"], acc: ["super hero time"] },
  { id: "jpserie-p4", d: 4, t: "Quel drama de 2016, phénomène social, a popularisé une danse de générique avec Yui Aragaki ?", a: "The Full-Time Wife Escapist", x: ["Hanzawa Naoki", "Hero", "Kahogo no Kahoko"], acc: ["nigehaji", "the full-time wife escapist"] },
  { id: "jpserie-p5", d: 4, t: "Quel acteur star, ex-membre de SMAP, tient le rôle-titre du drama policier « Hero » ?", a: "Takuya Kimura", x: ["Jun Matsumoto", "Kazunari Ninomiya", "Tomohisa Yamashita"] },
  { id: "jpserie-p6", d: 4, t: "De quelle agence de talents, immense au Japon, sont issus de nombreux acteurs de dramas ?", a: "Johnny's", x: ["Exile Tribe", "AKB48", "Amuse"], acc: ["johnny's", "johnnys"] },
  { id: "jpserie-p7", d: 4, t: "Quel drama Netflix retrace l'essor de l'industrie du film pour adultes au Japon ?", a: "The Naked Director", x: ["Sanctuary", "First Love", "Alice in Borderland"], acc: ["the naked director"] },
  { id: "jpserie-p8", d: 4, t: "Quel drama Netflix de 2023 plonge dans le monde brutal du sumo professionnel ?", a: "Sanctuary", x: ["The Naked Director", "First Love", "Tokyo Vice"], acc: ["sanctuary"] },
  { id: "jpserie-p9", d: 4, t: "Quelle série suit un journaliste étranger enquêtant sur les yakuzas à Tokyo ?", a: "Tokyo Vice", x: ["Giri/Haji", "Sanctuary", "Midnight Diner"], acc: ["tokyo vice"] },
  { id: "jpserie-p10", d: 4, t: "Quelle série douce suit un petit restaurant ouvert la nuit et les histoires de ses clients ?", a: "Midnight Diner", x: ["Samurai Gourmet", "Kantaro", "The Makanai"], acc: ["midnight diner", "shinya shokudo"] },
  { id: "jpserie-p11", d: 4, t: "Quel premier héros masqué de la télé japonaise, en 1958, précède Kamen Rider ?", a: "Moonlight Mask", x: ["Ultraman", "Gavan", "Spectreman"], acc: ["moonlight mask", "gekko kamen"] },
  { id: "jpserie-p12", d: 4, t: "Dans quelle émission française des années 80 passaient Bioman et San Ku Kaï ?", a: "Le Club Dorothée", x: ["Récré A2", "Croque-vacances", "Les Minikeums"], acc: ["club dorothée"] },
  { id: "jpserie-p13", d: 4, t: "Quelle série de SF japonaise de 1978 était connue en France sous « San Ku Kaï » ?", a: "San Ku Kaï", x: ["Spielban", "Metalder", "Jaspion"], acc: ["san ku kai", "san ku kaï"] },
  { id: "jpserie-p14", d: 4, t: "Quel Metal Hero, connu en France sous « Spielvan », combat en armure argentée ?", a: "Spielban", x: ["Gavan", "Sharivan", "Jiban"], acc: ["spielban", "spielvan"] },
  { id: "jpserie-p15", d: 4, t: "Quelle actrice, révélée par des dramas, a joué dans « Babel » et « Pacific Rim » ?", a: "Rinko Kikuchi", x: ["Yui Aragaki", "Satomi Ishihara", "Haruka Ayase"] },
  { id: "jpserie-p16", d: 4, t: "Quel drama romantique de Netflix de 2021 est inspiré d'une chanson d'Utada Hikaru ?", a: "First Love", x: ["Tokyo Vice", "Sanctuary", "The Makanai"], acc: ["first love", "hatsukoi"] },
  { id: "jpserie-p17", d: 4, t: "Quelle actrice a lancé la mode des dramas romantiques des années 90 avec « Tokyo Love Story » ?", a: "Honami Suzuki", x: ["Rie Miyazawa", "Yuki Amami", "Nanako Matsushima"], acc: ["honami suzuki"] },
  { id: "jpserie-p18", d: 4, t: "Quel groupe d'idols féminines géant, aux dizaines de membres, peuple les émissions japonaises ?", a: "AKB48", x: ["Morning Musume", "Nogizaka46", "Perfume"], acc: ["akb48"] },
  { id: "jpserie-p19", d: 4, t: "Quelle émission comique japonaise défie ses membres de ne pas rire sous peine de punition ?", a: "Gaki no Tsukai", x: ["Takeshi's Castle", "Sasuke", "Waratte Iitomo"], acc: ["gaki no tsukai", "batsu game"] },
  { id: "jpserie-p20", d: 4, t: "Quel duo comique anime « Gaki no Tsukai » et domine la télévision japonaise ?", a: "Downtown", x: ["Ninety-nine", "Tunnels", "Bakusho Mondai"], acc: ["downtown"] },
]);
