import type { Dilemma } from '../../core/tupreferesEngine';

/**
 * Banque de dilemmes « Tu préfères ? ». Deux options qui divisent, sans bonne
 * réponse. On évite le glauque et le clivant ; l'objectif est de lancer le débat
 * et de rire du camp minoritaire. Une option n'est jamais préfixée par « Tu
 * préfères » (ajouté à l'affichage).
 */
export const DILEMMAS: Dilemma[] = [
  { a: 'Voler comme un oiseau', b: 'Être invisible quand tu veux' },
  { a: 'Ne plus jamais manger de fromage', b: 'Ne plus jamais manger de chocolat' },
  { a: 'Vivre à la montagne', b: 'Vivre au bord de la mer' },
  { a: 'Avoir toujours trop chaud', b: 'Avoir toujours trop froid' },
  { a: 'Lire dans les pensées', b: 'Voir 10 minutes dans le futur' },
  { a: 'Être toujours en avance', b: 'Être toujours en retard' },
  { a: 'Ne plus jamais utiliser ton téléphone', b: 'Ne plus jamais regarder de séries' },
  { a: 'Gagner au loto mais perdre tes photos', b: 'Rester fauché mais garder tous tes souvenirs' },
  { a: 'Parler toutes les langues', b: 'Parler à tous les animaux' },
  { a: 'Avoir une mémoire parfaite', b: "Pouvoir oublier ce que tu veux" },
  { a: 'Un été sans fin', b: 'Un hiver sans fin' },
  { a: 'Être le plus drôle de la soirée', b: 'Être le plus beau/belle de la soirée' },
  { a: 'Danser comme une star', b: 'Chanter comme une star' },
  { a: 'Ne plus jamais faire la vaisselle', b: 'Ne plus jamais faire ton lit' },
  { a: 'Vivre sans musique', b: 'Vivre sans films' },
  { a: 'Toujours dire la vérité', b: 'Ne jamais pouvoir mentir… mais pouvoir te taire' },
  { a: 'Café le matin', b: 'Thé le matin' },
  { a: 'Pizza à vie', b: 'Burgers à vie' },
  { a: 'Passer une soirée en boîte', b: 'Passer une soirée jeux de société' },
  { a: 'Partir en vacances sans wifi', b: 'Partir en vacances sans valise (tout acheter sur place)' },
  { a: 'Avoir des bras de 3 mètres', b: 'Avoir des jambes de 3 mètres' },
  { a: 'Rire à chaque fois que tu mens', b: 'Éternuer à chaque fois que tu dis « oui »' },
  { a: 'Être coincé dans un ascenseur 2h avec ton ex', b: 'Avec ton pire prof' },
  { a: 'Refaire ta pire année', b: 'Sauter tes 5 prochaines années' },
  { a: 'Ne plus jamais te tromper', b: 'Ne plus jamais avoir peur' },
  { a: 'Manger uniquement salé', b: 'Manger uniquement sucré' },
  { a: 'Avoir un bouton pause sur la vie', b: 'Avoir un bouton retour en arrière (une fois par jour)' },
  { a: 'Être riche mais inconnu', b: 'Être célèbre mais fauché' },
  { a: 'Devoir chanter au lieu de parler', b: 'Devoir danser en marchant' },
  { a: 'Ne plus jamais retoucher tes photos', b: 'Ne plus jamais poster' },
  { a: 'Un super pouvoir nul (allumer les bougies)', b: 'Pas de pouvoir du tout' },
  { a: 'Vivre 100 ans en bonne santé', b: 'Vivre 150 ans mais fatigué' },
  { a: 'Toujours connaître la fin des films', b: 'Ne jamais retrouver la télécommande' },
  { a: 'Dormir 3h et être en forme', b: 'Dormir 12h obligatoires' },
  { a: 'Voyager dans le passé', b: 'Voyager dans le futur' },
  { a: 'Être champion du monde d\'un sport inconnu', b: 'Être moyen dans un sport ultra-populaire' },
  { a: 'Ne plus jamais attendre (files, feux, chargements)', b: 'Ne plus jamais être malade' },
  { a: 'Avoir un majordome robot', b: 'Avoir une voiture volante' },
  { a: 'Connaître le jour de ta mort', b: 'Connaître la cause, mais pas le jour' },
  { a: 'Manger le plat parfait tous les jours (le même)', b: 'Manger différent mais moyen' },
  { a: 'Être le héros mais souffrir', b: 'Être le side-kick peinard' },
  { a: 'Toujours avoir la chanson coincée dans la tête', b: 'Toujours avoir un caillou dans la chaussure' },
  { a: 'Perdre le goût', b: "Perdre l'odorat" },
  { a: 'Télétravailler à vie', b: 'Être au bureau tous les jours' },
  { a: 'Avoir des abonnés mais pas d\'amis', b: 'Avoir des amis mais 0 abonné' },
  { a: 'Dire tout haut ce que tu penses', b: 'Entendre ce que les autres pensent de toi' },
  { a: 'Un road-trip improvisé', b: 'Un voyage carré, tout réservé' },
  { a: 'Être toujours légèrement en sueur', b: 'Avoir toujours les mains froides' },
  { a: 'Gagner chaque dispute mais avoir tort', b: 'Perdre chaque dispute mais avoir raison' },
  { a: 'Ne plus jamais avoir mal aux jambes', b: 'Ne plus jamais avoir mal à la tête' },
  { a: 'Vivre dans une grande ville', b: 'Vivre à la campagne' },
  { a: 'Avoir une soirée mémorable mais tout oublier', b: 'Une soirée moyenne dont tu te souviens de tout' },
  { a: 'Recommencer cette soirée en boucle', b: 'Passer direct à demain' },
  { a: 'Être le meneur de jeu', b: 'Être celui qui subit les gages' },
  { a: 'Boire uniquement de l\'eau ce soir', b: 'Ne boire que ce que le groupe choisit' },
];
