import { filterHot } from '../../core/contentLevel';
import type { CancelLevel } from '../../core/models';
import type { Dilemma } from '../../core/tupreferesEngine';

/**
 * Banque de dilemmes « Tu préfères ? ». Deux options qui divisent, sans bonne
 * réponse. On évite le glauque et le clivant ; l'objectif est de lancer le débat
 * et de rire du camp minoritaire. Une option n'est jamais préfixée par « Tu
 * préfères » (ajouté à l'affichage).
 */
export const DILEMMAS: Dilemma[] = [
  { a: 'Voler comme un oiseau', b: 'Être invisible quand tu veux' },
  { a: 'Ne plus jamais manger de fromage', b: 'Ne plus jamais manger de chocolat' },
  { a: 'Vivre à la montagne', b: 'Vivre au bord de la mer' },
  { a: 'Avoir toujours trop chaud', b: 'Avoir toujours trop froid' },
  { a: 'Lire dans les pensées', b: 'Voir 10 minutes dans le futur' },
  { a: 'Être toujours en avance', b: 'Être toujours en retard' },
  { a: 'Ne plus jamais utiliser ton téléphone', b: 'Ne plus jamais regarder de séries' },
  { a: 'Gagner au loto mais perdre tes photos', b: 'Rester fauché mais garder tous tes souvenirs' },
  { a: 'Parler toutes les langues', b: 'Parler à tous les animaux' },
  { a: 'Avoir une mémoire parfaite', b: "Pouvoir oublier ce que tu veux" },
  { a: 'Un été sans fin', b: 'Un hiver sans fin' },
  { a: 'Être le plus drôle de la soirée', b: 'Être le plus beau/belle de la soirée' },
  { a: 'Danser comme une star', b: 'Chanter comme une star' },
  { a: 'Ne plus jamais faire la vaisselle', b: 'Ne plus jamais faire ton lit' },
  { a: 'Vivre sans musique', b: 'Vivre sans films' },
  { a: 'Toujours dire la vérité', b: 'Ne jamais pouvoir mentir… mais pouvoir te taire' },
  { a: 'Café le matin', b: 'Thé le matin' },
  { a: 'Pizza à vie', b: 'Burgers à vie' },
  { a: 'Passer une soirée en boîte', b: 'Passer une soirée jeux de société' },
  { a: 'Partir en vacances sans wifi', b: 'Partir en vacances sans valise (tout acheter sur place)' },
  { a: 'Avoir des bras de 3 mètres', b: 'Avoir des jambes de 3 mètres' },
  { a: 'Rire à chaque fois que tu mens', b: 'Éternuer à chaque fois que tu dis « oui »' },
  { a: 'Être coincé dans un ascenseur 2h avec ton ex', b: 'Avec ton pire prof' },
  { a: 'Refaire ta pire année', b: 'Sauter tes 5 prochaines années' },
  { a: 'Ne plus jamais te tromper', b: 'Ne plus jamais avoir peur' },
  { a: 'Manger uniquement salé', b: 'Manger uniquement sucré' },
  { a: 'Avoir un bouton pause sur la vie', b: 'Avoir un bouton retour en arrière (une fois par jour)' },
  { a: 'Être riche mais inconnu', b: 'Être célèbre mais fauché' },
  { a: 'Devoir chanter au lieu de parler', b: 'Devoir danser en marchant' },
  { a: 'Ne plus jamais retoucher tes photos', b: 'Ne plus jamais poster' },
  { a: 'Un super pouvoir nul (allumer les bougies)', b: 'Pas de pouvoir du tout' },
  { a: 'Vivre 100 ans en bonne santé', b: 'Vivre 150 ans mais fatigué' },
  { a: 'Toujours connaître la fin des films', b: 'Ne jamais retrouver la télécommande' },
  { a: 'Dormir 3h et être en forme', b: 'Dormir 12h obligatoires' },
  { a: 'Voyager dans le passé', b: 'Voyager dans le futur' },
  { a: 'Être champion du monde d\'un sport inconnu', b: 'Être moyen dans un sport ultra-populaire' },
  { a: 'Ne plus jamais attendre (files, feux, chargements)', b: 'Ne plus jamais être malade' },
  { a: 'Avoir un majordome robot', b: 'Avoir une voiture volante' },
  { a: 'Connaître le jour de ta mort', b: 'Connaître la cause, mais pas le jour' },
  { a: 'Manger le plat parfait tous les jours (le même)', b: 'Manger différent mais moyen' },
  { a: 'Être le héros mais souffrir', b: 'Être le side-kick peinard' },
  { a: 'Toujours avoir la chanson coincée dans la tête', b: 'Toujours avoir un caillou dans la chaussure' },
  { a: 'Perdre le goût', b: "Perdre l'odorat" },
  { a: 'Télétravailler à vie', b: 'Être au bureau tous les jours' },
  { a: 'Avoir des abonnés mais pas d\'amis', b: 'Avoir des amis mais 0 abonné' },
  { a: 'Dire tout haut ce que tu penses', b: 'Entendre ce que les autres pensent de toi' },
  { a: 'Un road-trip improvisé', b: 'Un voyage carré, tout réservé' },
  { a: 'Être toujours légèrement en sueur', b: 'Avoir toujours les mains froides' },
  { a: 'Gagner chaque dispute mais avoir tort', b: 'Perdre chaque dispute mais avoir raison' },
  { a: 'Ne plus jamais avoir mal aux jambes', b: 'Ne plus jamais avoir mal à la tête' },
  { a: 'Vivre dans une grande ville', b: 'Vivre à la campagne' },
  { a: 'Avoir une soirée mémorable mais tout oublier', b: 'Une soirée moyenne dont tu te souviens de tout' },
  { a: 'Recommencer cette soirée en boucle', b: 'Passer direct à demain' },
  { a: 'Être le meneur de jeu', b: 'Être celui qui subit les gages' },
  { a: 'Boire uniquement de l\'eau ce soir', b: 'Ne boire que ce que le groupe choisit' },
  // --- Quotidien & petits travers ---
  { a: "Ne plus jamais avoir de bouchons", b: "Ne plus jamais tomber sur un feu rouge" },
  { a: "Toujours retrouver tes clés du premier coup", b: "Toujours avoir ton téléphone chargé" },
  { a: "Ne plus jamais avoir de pub", b: "Ne plus jamais avoir de spam" },
  { a: "Avoir un frigo qui se remplit tout seul", b: "Avoir un linge qui se plie tout seul" },
  { a: "Ne plus jamais faire les courses", b: "Ne plus jamais cuisiner" },
  { a: "Un lit toujours parfaitement fait", b: "Une douche toujours à la bonne température" },
  { a: "Ne plus jamais avoir mal aux pieds en soirée", b: "Ne plus jamais avoir la gueule de bois" },
  { a: "Wifi ultra-rapide partout", b: "Batterie qui dure une semaine" },
  { a: "Ne plus jamais perdre une chaussette", b: "Ne plus jamais casser un verre" },
  { a: "Un placard toujours rangé", b: "Une boîte mail toujours vide" },
  { a: "Ne plus jamais attendre le bus", b: "Ne plus jamais chercher une place de parking" },
  { a: "Comprendre toutes les notices en 3 secondes", b: "Monter n'importe quel meuble sans réfléchir" },
  { a: "Ne plus jamais te brûler la langue", b: "Ne plus jamais te cogner le petit orteil" },
  { a: "Avoir toujours la bonne monnaie", b: "Ne jamais oublier un code ou un mot de passe" },
  { a: "Un café parfait chaque matin", b: "Un réveil toujours en pleine forme" },
  // --- Nourriture ---
  { a: "Ne manger que des plats épicés", b: "Ne manger que des plats fades" },
  { a: "Des frites illimitées mais froides", b: "Des frites chaudes mais rationnées" },
  { a: "Ne plus jamais manger de pain", b: "Ne plus jamais manger de pâtes" },
  { a: "Le petit-déjeuner à tous les repas", b: "Le dessert à tous les repas" },
  { a: "Un buffet à volonté chaque midi", b: "Le restaurant étoilé une fois par mois" },
  { a: "Manger avec les doigts toute ta vie", b: "Manger uniquement avec des baguettes" },
  { a: "Ne plus jamais boire que du chaud", b: "Ne plus jamais boire que du froid" },
  { a: "Tout goûter mais ne jamais te rappeler le goût", b: "Ne goûter que 10 aliments, à vie" },
  { a: "Des pizzas sans fromage", b: "Des burgers sans pain" },
  { a: "Cuisiner comme un chef mais salir toute la cuisine", b: "Cuisiner moyen mais tout reste propre" },
  // --- Super-pouvoirs & fantastique ---
  { a: "Te téléporter mais seulement là où tu es déjà allé", b: "Voler mais pas plus vite qu'à pied" },
  { a: "Arrêter le temps 10 minutes par jour", b: "Rembobiner de 10 minutes une fois par jour" },
  { a: "Respirer sous l'eau", b: "Ne jamais avoir besoin de dormir" },
  { a: "Parler à ton toi du passé", b: "Écouter ton toi du futur" },
  { a: "Devenir invisible mais tes vêtements restent visibles", b: "Voler mais seulement à 30 cm du sol" },
  { a: "Guérir n'importe quelle blessure", b: "Comprendre n'importe quel problème instantanément" },
  { a: "Invoquer n'importe quel objet à 5 €", b: "Rendre n'importe quel objet gratuit une fois par semaine" },
  { a: "Contrôler la météo au-dessus de toi", b: "Contrôler la musique partout où tu vas" },
  { a: "Avoir toujours de la chance aux petits jeux", b: "Ne jamais te blesser bêtement" },
  { a: "Comprendre les bébés", b: "Comprendre les chats" },
  // --- Voyage & aventure ---
  { a: "Visiter tous les pays mais 24h chacun", b: "Vivre 5 ans dans un seul pays de rêve" },
  { a: "Voyager gratuitement mais toujours seul", b: "Payer plein tarif mais toujours bien accompagné" },
  { a: "Un road-trip sans GPS", b: "Un voyage organisé minute par minute" },
  { a: "Dormir chez l'habitant partout", b: "Hôtels de luxe mais jamais de rencontres" },
  { a: "Ne visiter que des villes", b: "Ne visiter que la nature" },
  { a: "Parler la langue mais te perdre tout le temps", b: "T'orienter parfaitement mais ne rien comprendre" },
  { a: "Prendre l'avion sans jamais de retard", b: "Ne jamais payer les bagages" },
  { a: "Voir toutes les merveilles du monde en photo", b: "En visiter une seule, en vrai" },
  // --- Boulot & études ---
  { a: "La semaine de 4 jours mais journées longues", b: "5 jours mais tu finis tôt" },
  { a: "Un patron génial mais un salaire moyen", b: "Un salaire top mais un patron pénible" },
  { a: "Travailler avec tes meilleurs amis", b: "Travailler seul, tranquille" },
  { a: "Ne plus jamais avoir de réunion inutile", b: "Ne plus jamais avoir de mail le week-end" },
  { a: "Un métier passion mal payé", b: "Un métier alimentaire mais 3 mois de congés" },
  { a: "Être ton propre patron mais bosser tout le temps", b: "Être salarié mais déconnecter le soir" },
  { a: "Réussir sans effort mais sans reconnaissance", b: "Galérer mais être admiré" },
  { a: "Ne plus jamais réviser", b: "Ne plus jamais passer d'entretien" },
  // --- Techno & réseaux ---
  { a: "Ne plus jamais scroller", b: "Ne plus jamais binge-watcher" },
  { a: "Un jour sans écran par semaine", b: "Un écran illimité mais 2h par jour seulement" },
  { a: "Connaître tous tes mots de passe par cœur", b: "Ne plus jamais avoir de bug" },
  { a: "Répondre à tous tes messages tout de suite", b: "Ne jamais répondre mais qu'on ne t'en veuille pas" },
  { a: "Avoir un assistant IA parfait", b: "Avoir un ami qui sait vraiment tout" },
  { a: "Ne plus jamais avoir de pub avant une vidéo", b: "Ne plus jamais mettre à jour un logiciel" },
  { a: "Que ton historique soit public", b: "Que tes photos ratées soient publiques" },
  { a: "Vivre 100 % en réalité virtuelle 1h par jour", b: "Ne plus jamais jouer aux jeux vidéo" },
  // --- Corps & sensations ---
  { a: "Ne plus jamais transpirer", b: "Ne plus jamais avoir soif" },
  { a: "Dormir debout n'importe où", b: "Ne jamais avoir besoin de sieste" },
  { a: "Guérir en une nuit de n'importe quel rhume", b: "Ne plus jamais avoir de courbatures" },
  { a: "Voir dans le noir", b: "Entendre à travers les murs" },
  { a: "Avoir une voix magnifique", b: "Avoir un rire contagieux" },
  { a: "Ne plus jamais avoir faim", b: "Ne plus jamais être fatigué" },
  { a: "Changer la couleur de tes yeux quand tu veux", b: "Changer ta coiffure d'un claquement de doigts" },
  { a: "Marcher sans jamais te fatiguer", b: "Nager sans jamais couler" },
  // --- Soirée & jeu (méta) ---
  { a: "Distribuer tous les gages ce soir", b: "N'en recevoir aucun ce soir" },
  { a: "Connaître toutes les réponses du quiz", b: "Faire deviner n'importe quoi en 5 secondes" },
  { a: "Être toujours capitaine d'équipe", b: "Toujours choisir les règles" },
  { a: "Gagner ce soir mais perdre la prochaine fois", b: "Perdre ce soir mais gagner la prochaine" },
  { a: "Relancer une manche que tu as perdue", b: "Voler un point à l'équipe adverse" },
  { a: "Être imbattable aux jeux de mémoire", b: "Être imbattable aux jeux de rapidité" },
  { a: "Choisir la musique de la soirée", b: "Choisir le menu de la soirée" },
  { a: "Faire rire tout le monde une fois", b: "Faire réfléchir tout le monde longtemps" },
  // --- Choix cornéliens & hypothétiques ---
  { a: "Revivre ton plus beau souvenir sans t'en souvenir après", b: "Garder un souvenir moyen mais net à vie" },
  { a: "Savoir quand tout le monde ment", b: "Ne jamais te faire prendre en mentant" },
  { a: "Être le plus intelligent d'un groupe de bavards", b: "Le plus bavard d'un groupe de génies" },
  { a: "Avoir toujours raison mais que ça énerve", b: "Avoir souvent tort mais qu'on t'adore" },
  { a: "Recommencer ta vie en gardant tes souvenirs", b: "Continuer ta vie avec une chance en plus" },
  { a: "Être admiré de loin", b: "Être aimé de près" },
  { a: "Connaître un secret sur chacun", b: "Que personne ne connaisse rien sur toi" },
  { a: "Choisir ton talent mais un seul", b: "Être bon partout mais excellent nulle part" },
  { a: "Vivre une grande aventure risquée", b: "Une vie tranquille et douce" },
  { a: "Pouvoir tout recommencer une fois", b: "Pouvoir tout accélérer quand c'est pénible" },
  // --- Fun & absurde (bon enfant) ---
  { a: "Avoir en permanence une musique de film qui te suit", b: "Avoir un narrateur qui commente ta vie" },
  { a: "Parler en rimes toute la journée", b: "Chuchoter en permanence" },
  { a: "Que tout le monde t'applaudisse quand tu entres", b: "Que des confettis tombent quand tu réussis un truc" },
  { a: "Avoir une capuche qui apparaît quand il pleut", b: "Avoir des chaussures qui ne se salissent jamais" },
  { a: "Éternuer des paillettes", b: "Bâiller des bulles de savon" },
  { a: "Avoir un sosie qui fait les corvées", b: "Avoir un double qui va aux réunions" },
  { a: "Que ton animal préféré te suive partout", b: "Qu'un petit robot rigolo te suive partout" },
  { a: "Rétrécir à volonté", b: "Grandir à volonté" },
  { a: "Avoir des poches sans fond", b: "Avoir des mains qui ne se salissent jamais" },
  { a: "Parler comme un présentateur télé", b: "Bouger comme un danseur pro" },
  // --- Relations (léger) ---
  { a: "Te faire de nouveaux amis très facilement", b: "Garder tes amis actuels pour toujours" },
  { a: "Toujours savoir quoi offrir", b: "Toujours savoir quoi dire" },
  { a: "Ne jamais oublier un prénom", b: "Ne jamais oublier une date importante" },
  { a: "Être le confident du groupe", b: "Être l'organisateur du groupe" },
  { a: "Recevoir toujours chez toi", b: "Être toujours invité chez les autres" },
  { a: "Avoir un ami dans chaque pays", b: "Avoir un ami dans chaque métier" },
  { a: "Toujours faire le premier pas", b: "Qu'on vienne toujours vers toi" },
  { a: "Un grand groupe d'amis", b: "Deux ou trois amis inséparables" },
  // --- Saisons, maison, argent ---
  { a: "Vivre dans une tiny house nomade", b: "Vivre dans une grande maison immobile" },
  { a: "Gagner un petit peu tous les jours", b: "Gagner beaucoup une fois par an" },
  { a: "Une maison au bord d'un lac", b: "Un appart en plein centre-ville" },
  { a: "Être payé pour dormir", b: "Être payé pour voyager" },
  { a: "Ne plus jamais payer de loyer", b: "Ne plus jamais payer de transport" },
  { a: "Un jardin immense", b: "Une immense terrasse sur les toits" },
  { a: "Trouver 50 € par terre chaque semaine", b: "Ne jamais avoir à faire de vaisselle" },
  { a: "Automne toute l'année", b: "Printemps toute l'année" },
  // --- Culture & talents ---
  { a: "Jouer parfaitement d'un instrument", b: "Peindre comme un maître" },
  { a: "Écrire un roman à succès", b: "Réaliser un film culte" },
  { a: "Retenir tous les films que tu as vus", b: "Retenir tous les livres que tu as lus" },
  { a: "Improviser un discours parfait", b: "Improviser une chanson parfaite" },
  { a: "Comprendre l'art moderne", b: "Comprendre l'économie" },
  { a: "Connaître l'histoire de chaque lieu que tu visites", b: "Connaître l'avenir de chaque projet que tu lances" },
  { a: "Être imbattable aux mots croisés", b: "Être imbattable aux échecs" },
  { a: "Danser tous les styles", b: "Chanter dans toutes les langues" },
  // --- Encore du quotidien piquant ---
  { a: "Ne plus jamais avoir de faux numéro", b: "Ne plus jamais tomber sur un répondeur" },
  { a: "Que les sacs plastiques ne se déchirent jamais", b: "Que les écouteurs ne s'emmêlent jamais" },
  { a: "Un parapluie qui ne se retourne jamais", b: "Des lunettes qui ne s'embuent jamais" },
  { a: "Ne plus jamais avoir de fil de chargeur trop court", b: "Ne plus jamais avoir de prise trop loin" },
  { a: "Que le pain reste frais une semaine", b: "Que les bananes ne noircissent jamais" },
  { a: "Ne plus jamais rater une cuisson", b: "Ne plus jamais rater une photo" },
  { a: "Avoir toujours un stylo qui marche", b: "Avoir toujours une place assise" },
  { a: "Ne plus jamais avoir de pop-up « cookies »", b: "Ne plus jamais avoir de mise à jour forcée" },
  { a: "Que ta glace ne fonde jamais trop vite", b: "Que ton café ne refroidisse jamais trop vite" },
  { a: "Trouver toujours la bonne file en caisse", b: "Trouver toujours ta taille en magasin" },
  // --- Rab ---
  { a: "Avoir un talent caché que personne ne connaît", b: "Un défaut mineur que tout le monde connaît" },
  { a: "Ne plus jamais avoir le hoquet", b: "Ne plus jamais avoir de crampe" },
  { a: "Deviner la fin de chaque série", b: "Deviner qui va gagner chaque match" },
  { a: "Toujours trouver un cadeau au dernier moment", b: "Toujours l'avoir prévu des mois à l'avance" },
  { a: "Un chien qui parle mais qui dit n'importe quoi", b: "Un chat silencieux mais qui te comprend" },
  { a: "Ne plus jamais avoir froid aux mains", b: "Ne plus jamais avoir les pieds mouillés" },
  { a: "Pouvoir sauter très haut", b: "Pouvoir courir très longtemps" },
  { a: "Que ta chanson préférée passe partout où tu vas", b: "Que ton plat préféré soit toujours au menu" },
  { a: "Ne plus jamais avoir mal aux dents", b: "Ne plus jamais avoir mal au dos" },
  { a: "Un talent pour raconter des histoires", b: "Un talent pour écouter les autres" },
  { a: "Pouvoir dormir n'importe où", b: "Pouvoir te réveiller à l'heure sans réveil" },
  { a: "Avoir toujours une bonne excuse", b: "Ne jamais en avoir besoin" },
  { a: "Un super odorat pour la cuisine", b: "Une super ouïe pour la musique" },
  { a: "Ne plus jamais rater un bus de peu", b: "Ne plus jamais rater un ascenseur de peu" },
  { a: "Que tes plantes ne meurent jamais", b: "Que tes fleurs coupées durent un mois" },
  { a: "Deviner l'âge des gens à coup sûr", b: "Deviner leur métier à coup sûr" },
  { a: "Pouvoir refaire une sieste parfaite chaque jour", b: "Ne plus jamais avoir de coup de barre" },
  { a: "Un talent pour bricoler", b: "Un talent pour décorer" },
  { a: "Ne plus jamais oublier un rendez-vous", b: "Ne plus jamais être coincé dans une conversation" },
  { a: "Que le week-end dure trois jours", b: "Que les vacances arrivent deux fois plus souvent" },
];

/** Dilemme tagué du niveau minimum de « cancellabilité » requis pour le tirer. */
type HotDilemma = Dilemma & { lvl: CancelLevel };

/**
 * Contenu osé, du plus léger (2) au plus trash (4). Échantillon volontairement
 * démonstratif (à étoffer). On reste dans l'esprit « jeu de soirée adulte » —
 * coquin, tabou, humour noir — sans jamais viser ni rabaisser un groupe.
 */
export const DILEMMAS_HOT: HotDilemma[] = [
  // --- Niveau 2 · Épicé 🌶️ (coquin, gênant) --------------------------------
  { a: "Embrasser ton ex", b: "Embrasser le/la meilleur(e) ami(e) de ton ex", lvl: 2 },
  { a: "Que ton/ta partenaire lise tous tes messages", b: "Qu'il/elle voie tout ton historique de recherche", lvl: 2 },
  { a: "Un rencard parfait sans aucune alchimie", b: "Une alchimie de folie mais un rencard catastrophique", lvl: 2 },
  { a: "Matcher avec ton/ta boss sur une appli", b: "Matcher avec un(e) cousin(e) éloigné(e)", lvl: 2 },
  { a: "Que ta mère tombe sur tes textos coquins", b: "Que tes collègues tombent dessus", lvl: 2 },
  { a: "Te faire ghoster après un date de rêve", b: "Enchaîner dix dates tièdes", lvl: 2 },
  { a: "Draguer toute la nuit sans succès", b: "Être dragué(e) sans arrêt par la mauvaise personne", lvl: 2 },
  { a: "Ne plus jamais embrasser", b: "Ne plus jamais faire de câlins", lvl: 2 },
  { a: "Un(e) partenaire hyper jaloux(se)", b: "Un(e) partenaire trop convoité(e) par les autres", lvl: 2 },
  { a: "Liker par erreur une vieille photo de ton crush", b: "Envoyer un cœur à la mauvaise conversation", lvl: 2 },

  // --- Niveau 3 · +18 🔞 (torride, très adulte) ----------------------------
  { a: "Un plan à trois avec deux inconnus", b: "Un plan à trois avec deux ex", lvl: 3 },
  { a: "Que tout le monde ici connaisse ton nombre de partenaires", b: "Que tout le monde connaisse tes fantasmes", lvl: 3 },
  { a: "Le meilleur coup de ta vie, une seule fois", b: "Un niveau correct, mais garanti à vie", lvl: 3 },
  { a: "Ne faire l'amour qu'en silence total", b: "Qu'en réveillant tout l'immeuble", lvl: 3 },
  { a: "Te faire surprendre en plein acte par tes parents", b: "Par ton/ta boss", lvl: 3 },
  { a: "Un(e) amant(e) incroyable mais qui raconte tout", b: "Décevant(e) mais d'une discrétion totale", lvl: 3 },
  { a: "Recoucher une dernière fois avec ton ex", b: "Coucher avec quelqu'un présent ce soir", lvl: 3 },
  { a: "Révéler ton historique de sites pour adultes", b: "Révéler tous tes messages privés", lvl: 3 },
  { a: "Envoyer une photo osée à la mauvaise personne", b: "Recevoir celle que tu n'aurais jamais dû voir", lvl: 3 },
  { a: "Ne plus jamais coucher", b: "Ne plus jamais dormir plus de quatre heures", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (humour noir, tabou, provoc) --------------
  { a: "Hériter d'un million à la mort d'un proche que tu détestes", b: "Rester fauché, mais tout le monde en pleine santé", lvl: 4 },
  { a: "Savoir exactement quand tu vas mourir", b: "Savoir exactement comment", lvl: 4 },
  { a: "Balancer le pire secret de ton/ta meilleur(e) ami(e) pour 50 000 €", b: "Le garder et rester fauché", lvl: 4 },
  { a: "Dire tout haut ce que tout le monde pense tout bas", b: "Ne plus jamais pouvoir donner ton avis", lvl: 4 },
  { a: "Assister en fantôme à ton propre enterrement", b: "À celui de la personne que tu aimes le plus", lvl: 4 },
  { a: "Gagner à chaque fois en trichant, sans te faire prendre", b: "Perdre honnêtement toute ta vie", lvl: 4 },
  { a: "Coucher avec la seule personne interdite (l'ex d'un ami…)", b: "Ne plus toucher personne pendant deux ans", lvl: 4 },
  { a: "Qu'on projette ton historique internet à ton enterrement", b: "Qu'on lise tes messages privés à voix haute", lvl: 4 },
  { a: "Pleurer de rire à un enterrement", b: "Éclater de rire en pleine rupture", lvl: 4 },
  { a: "Effacer un souvenir traumatisant… et la leçon avec", b: "Le garder pour toujours, intact", lvl: 4 },

  // ===== Vague 2 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { a: "Que ton crush voie tous tes brouillons de messages", b: "Qu'il/elle entende toutes tes pensées pendant un date", lvl: 2 },
  { a: "Sortir avec quelqu'un de 15 ans de plus", b: "De 15 ans de moins (majeur !)", lvl: 2 },
  { a: "Embrasser trois inconnus ce soir", b: "N'embrasser personne pendant six mois", lvl: 2 },
  { a: "Un ex qui revient toutes les semaines", b: "Un ex qui ne répond plus jamais", lvl: 2 },
  { a: "Que ton/ta partenaire reste ami(e) avec tous ses ex", b: "Qu'il/elle coupe les ponts avec tout le monde", lvl: 2 },
  { a: "Un date parfait mais devant tes parents", b: "Un date catastrophique mais en tête-à-tête", lvl: 2 },
  { a: "Te déclarer et te prendre un râteau en public", b: "Ne jamais oser et le regretter à vie", lvl: 2 },
  { a: "Découvrir combien de gens t'ont friendzoné", b: "Combien t'ont trouvé(e) trop collant(e)", lvl: 2 },
  { a: "Ne draguer que par messages", b: "Ne draguer qu'en vrai", lvl: 2 },
  { a: "Que ton historique de likes devienne public", b: "Que tes captures d'écran deviennent publiques", lvl: 2 },
  { a: "Un rencard qui ne parle que de son ex", b: "Un rencard qui ne parle que de sa mère", lvl: 2 },
  { a: "Toujours dire « je t'aime » le premier", b: "Attendre indéfiniment que l'autre le dise", lvl: 2 },
  { a: "Sortir avec le/la meilleur(e) ami(e) de ton/ta pote", b: "Avec ton/ta voisin(e) de palier", lvl: 2 },
  { a: "Que tout le monde connaisse ton genre de crush", b: "Que personne ne devine jamais ce qui te plaît", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { a: "Coucher une fois avec ton/ta meilleur(e) ami(e)", b: "Ne plus jamais le/la revoir", lvl: 3 },
  { a: "Que ton/ta partenaire note tes performances sur 10", b: "Devoir noter les siennes à voix haute", lvl: 3 },
  { a: "Refaire ta toute première fois", b: "Effacer ton pire coup d'un soir", lvl: 3 },
  { a: "Une sextape qui fuite auprès de tes amis", b: "Auprès de tes collègues", lvl: 3 },
  { a: "Ne coucher qu'avec la même personne à vie", b: "Ne jamais deux fois avec la même", lvl: 3 },
  { a: "Dire tous tes fantasmes à ton/ta partenaire", b: "Qu'il/elle te révèle tous les siens", lvl: 3 },
  { a: "Un coup d'un soir incroyable avec un(e) inconnu(e)", b: "Un câlin médiocre avec quelqu'un que tu aimes", lvl: 3 },
  { a: "Être surpris(e) à mater du contenu +18", b: "Qu'on découvre tes recherches les plus bizarres", lvl: 3 },
  { a: "Coucher une fois avec la star qui te fait fantasmer", b: "Une vie sexuelle parfaite mais banale", lvl: 3 },
  { a: "Que ton nombre de partenaires s'affiche sur ton front", b: "Que tes notes de performance s'y affichent", lvl: 3 },
  { a: "Ne plus jamais de préliminaires", b: "Ne plus jamais d'after", lvl: 3 },
  { a: "Envoyer un nude à ton/ta boss par erreur", b: "À tout ton groupe d'amis", lvl: 3 },
  { a: "Coucher avec l'ex de ton/ta meilleur(e) ami(e)", b: "Avec un(e) ancien(ne) prof, entre adultes", lvl: 3 },
  { a: "Une dernière nuit torride puis célibat à vie", b: "Une vie de dates sans jamais conclure", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { a: "Coucher avec ton/ta ex le soir de son mariage", b: "Avec le/la marié(e) que tu ne connais même pas", lvl: 4 },
  { a: "Que le groupe apprenne qui tu as déjà trompé", b: "Combien de fois tu as menti pour coucher", lvl: 4 },
  { a: "Provoquer sans le vouloir le divorce de tes parents", b: "La rupture de ton/ta meilleur(e) ami(e)", lvl: 4 },
  { a: "Balancer un proche à la police pour 100 000 €", b: "Couvrir son délit et vivre avec", lvl: 4 },
  { a: "Coucher pour décrocher le job de tes rêves", b: "Rester médiocre mais intègre toute ta carrière", lvl: 4 },
  { a: "Qu'on lise tes messages les plus honteux à ton mariage", b: "À l'enterrement de ta grand-mère", lvl: 4 },
  { a: "Coucher avec quelqu'un que tu détestes pour sauver ta peau", b: "Tout perdre en gardant ta dignité", lvl: 4 },
  { a: "Mettre une nuit avec toi aux enchères", b: "Devoir enchérir sur celle de ton crush", lvl: 4 },
  { a: "Que ton pire secret d'alcôve devienne une story publique", b: "Que ton casier (même imaginaire) le devienne", lvl: 4 },
  { a: "Tromper et l'avouer dès le lendemain", b: "Tromper et l'emporter dans la tombe", lvl: 4 },
  { a: "Rire au nez de quelqu'un qui se fait larguer", b: "Filmer ta propre rupture pour les vues", lvl: 4 },
  { a: "Coucher avec deux ami(e)s d'un même groupe le même soir", b: "Avec deux ex le même week-end", lvl: 4 },
  { a: "Hériter en débranchant toi-même la prise", b: "Rester ruiné et veiller le/la malade dix ans", lvl: 4 },
  { a: "Simuler un deuil pour un congé payé", b: "Rater le vrai enterrement à cause du travail", lvl: 4 },
  { a: "Voler le/la partenaire de ton/ta meilleur(e) ami(e)", b: "Rester seul(e) mais loyal(e) à vie", lvl: 4 },

  // ===== Vague 3 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { a: "Que ton/ta crush voie ta playlist « du soir »", b: "Qu'il/elle lise tes notes de téléphone", lvl: 2 },
  { a: "Un premier rendez-vous au resto le plus chic", b: "Un premier rendez-vous à 4 h du mat en after", lvl: 2 },
  { a: "Rougir à chaque compliment", b: "Bégayer dès que quelqu'un te plaît", lvl: 2 },
  { a: "Sortir avec quelqu'un qui ronfle très fort", b: "Avec quelqu'un qui parle en dormant et balance tout", lvl: 2 },
  { a: "Avoir le béguin pour un(e) collègue", b: "Pour un(e) ami(e) de très longue date", lvl: 2 },
  { a: "Te faire larguer par SMS", b: "Te faire larguer devant tes amis", lvl: 2 },
  { a: "Embrasser quelqu'un qui embrasse divinement mais que tu n'aimes pas", b: "Aimer quelqu'un qui embrasse très mal", lvl: 2 },
  { a: "Un date qui checke son téléphone toute la soirée", b: "Un date qui ne parle que de lui", lvl: 2 },
  { a: "Que tout le monde sache pour qui tu as flashé ici", b: "Ne jamais l'avouer et le regretter", lvl: 2 },
  { a: "Un rencard parfait sous la pluie", b: "Un rencard raté par une journée magnifique", lvl: 2 },
  { a: "Devoir déclarer ta flamme en chanson", b: "En envoyant tes parents comme intermédiaires", lvl: 2 },
  { a: "Ne pouvoir draguer qu'avec des jeux de mots pourris", b: "Qu'en citant des répliques de films", lvl: 2 },
  { a: "Que ton/ta date arrive avec 1 h de retard", b: "Qu'il/elle arrive avec un(e) ami(e) non prévu(e)", lvl: 2 },
  { a: "Recevoir une lettre d'amour anonyme", b: "Découvrir un compte secret qui te suit partout", lvl: 2 },
  { a: "Sortir avec quelqu'un de trop parfait (intimidant)", b: "Avec quelqu'un d'attachant mais bordélique", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { a: "Que ton/ta partenaire garde toujours les yeux ouverts", b: "Qu'il/elle éteigne toujours la lumière", lvl: 3 },
  { a: "Faire l'amour dans un lieu insolite mais risqué", b: "Toujours au même endroit mais tranquille", lvl: 3 },
  { a: "Révéler ton chiffre à ton/ta partenaire actuel(le)", b: "Ne jamais connaître le sien", lvl: 3 },
  { a: "Un(e) partenaire infatigable mais très bruyant(e)", b: "Doux/douce mais qui s'endort avant la fin", lvl: 3 },
  { a: "Coucher avec ton plus grand fantasme et être déçu(e)", b: "Ne jamais tenter et fantasmer à vie", lvl: 3 },
  { a: "Que tes recherches privées s'affichent sur la TV du salon", b: "Que tes vocaux les plus gênants passent en boucle", lvl: 3 },
  { a: "Ne plus jamais de sexe mais des câlins parfaits", b: "Beaucoup de sexe mais zéro tendresse", lvl: 3 },
  { a: "Qu'un plan d'un soir tombe amoureux de toi", b: "Tomber amoureux(se) de ton plan d'un soir", lvl: 3 },
  { a: "Faire l'amour sur la musique de tes parents", b: "Sur le générique de ton dessin animé d'enfance", lvl: 3 },
  { a: "Que ton/ta boss découvre ta vie sexuelle", b: "Que ta belle-famille la découvre", lvl: 3 },
  { a: "Ne coucher qu'en vacances", b: "Ne coucher que les jours de pluie", lvl: 3 },
  { a: "Un tatouage au nom de ton ex", b: "Un tatouage raté à un endroit très intime", lvl: 3 },
  { a: "Que ton/ta partenaire lise ton journal intime coquin", b: "Qu'il/elle ouvre ton dossier « caché »", lvl: 3 },
  { a: "Assumer un fantasme jugé bizarre", b: "Cacher cette part de toi à vie", lvl: 3 },
  { a: "Coucher une dernière fois avec chaque ex pour tourner la page", b: "Ne jamais les revoir mais rester curieux(se)", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { a: "Coucher avec le/la meilleur(e) ami(e) de ton/ta ex", b: "Avec l'ex de ton/ta meilleur(e) ami(e)", lvl: 4 },
  { a: "Avouer publiquement ton pire mensonge", b: "Emporter ton pire secret dans la tombe", lvl: 4 },
  { a: "Gagner un million si un inconnu meurt (tu ne sauras jamais qui)", b: "Rester fauché toute ta vie", lvl: 4 },
  { a: "Que ta famille apprenne ton casier (même imaginaire)", b: "Ton nombre exact de partenaires", lvl: 4 },
  { a: "Trahir ton pays pour de l'argent", b: "Trahir ta famille pour la gloire", lvl: 4 },
  { a: "Rire pendant un discours d'enterrement", b: "T'endormir au mariage de ton/ta meilleur(e) ami(e)", lvl: 4 },
  { a: "Effacer la mémoire de ton pire ennemi", b: "Effacer la tienne des cinq dernières années", lvl: 4 },
  { a: "Vendre les secrets de ta bande d'amis à la presse", b: "Ceux de ta propre famille", lvl: 4 },
  { a: "Coucher avec quelqu'un juste pour un héritage", b: "Épouser sans amour pour l'argent", lvl: 4 },
  { a: "Connaître la date de mort de tes proches", b: "Qu'ils connaissent la tienne", lvl: 4 },
  { a: "Que ton pire moment soit rejoué sur écran géant", b: "Que ta pire pensée s'affiche au-dessus de ta tête", lvl: 4 },
  { a: "Piquer le/la fiancé(e) de quelqu'un le jour J", b: "Rater volontairement ton propre mariage", lvl: 4 },
  { a: "Balancer un(e) ami(e) infidèle à son/sa partenaire", b: "Garder le secret et culpabiliser", lvl: 4 },
  { a: "Un enterrement où personne ne pleure", b: "Un mariage où tout le monde parie sur le divorce", lvl: 4 },
  { a: "Simuler ta propre disparition pour repartir à zéro", b: "Rester coincé(e) dans ta vie actuelle à jamais", lvl: 4 },

  // ===== Vague 4 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { a: "Que ton/ta partenaire suive tous tes ex sur les réseaux", b: "Que tu suives tous les siens", lvl: 2 },
  { a: "Recevoir un compliment très gênant de ton/ta boss", b: "De ta belle-mère", lvl: 2 },
  { a: "Avoir un fou rire nerveux à ton premier bisou", b: "Éternuer juste avant", lvl: 2 },
  { a: "Un date qui commande pour toi sans demander", b: "Un date qui te laisse toute l'addition", lvl: 2 },
  { a: "Draguer quelqu'un qui ne rit à aucune de tes blagues", b: "Quelqu'un qui rit à TOUTES, même les nulles", lvl: 2 },
  { a: "Que ton téléphone lise tes messages à voix haute en soirée", b: "Qu'il affiche tes dernières photos likées", lvl: 2 },
  { a: "Tomber amoureux(se) de deux personnes en même temps", b: "De personne pendant deux ans", lvl: 2 },
  { a: "Rougir dès qu'on prononce un certain prénom", b: "Sourire bêtement à chaque notification", lvl: 2 },
  { a: "Un slow très gênant avec un(e) inconnu(e)", b: "Un blanc de 30 secondes en plein date", lvl: 2 },
  { a: "Que ta recherche « symptômes » devienne publique", b: "Ta recherche « comment dire à quelqu'un que… »", lvl: 2 },
  { a: "Refaire ta coiffure dix fois avant un rencard", b: "Changer de tenue jusqu'à être en retard", lvl: 2 },
  { a: "Mentir sur tes goûts pour plaire", b: "Assumer des goûts que personne ne partage", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { a: "Que ton/ta partenaire connaisse toutes tes anciennes conquêtes", b: "Que tu connaisses toutes les siennes", lvl: 3 },
  { a: "Un bruit très gênant au pire moment sous la couette", b: "Un fou rire incontrôlable", lvl: 3 },
  { a: "Devoir garder les chaussettes à chaque fois", b: "Ne jamais pouvoir éteindre la lumière", lvl: 3 },
  { a: "Que ton lit grince très fort", b: "Que les murs soient en papier", lvl: 3 },
  { a: "Un match parfait à 3 h de route", b: "Un match tiède juste en bas de chez toi", lvl: 3 },
  { a: "Recroiser un coup d'un soir chez le médecin", b: "À un entretien d'embauche", lvl: 3 },
  { a: "Que ton/ta crush découvre ta playlist très coquine", b: "Ta liste de fantasmes notée quelque part", lvl: 3 },
  { a: "Un(e) partenaire qui parle sans arrêt", b: "Un(e) partenaire totalement muet(te)", lvl: 3 },
  { a: "Que tes voisins connaissent ton rythme", b: "Que ta coloc te chambre chaque matin", lvl: 3 },
  { a: "Refaire une nuit parfaite sans jamais t'en souvenir", b: "T'en souvenir parfaitement sans qu'elle se répète", lvl: 3 },
  { a: "Que ton historique de rencontres soit tatoué", b: "Que tes notes de date le soient", lvl: 3 },
  { a: "N'avoir le droit qu'à un seul et unique fantasme à vie", b: "Devoir tous les réaliser sans exception", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { a: "Découvrir que ton/ta partenaire t'a toujours menti", b: "Qu'il/elle découvre que TOI, tu mens depuis le début", lvl: 4 },
  { a: "Assister au succès insolent de ton pire ennemi", b: "À ta propre humiliation publique", lvl: 4 },
  { a: "Que tout ce que tu dis en soirée soit enregistré et diffusé", b: "Que tes pensées de la journée soient publiées", lvl: 4 },
  { a: "Voler l'idée d'un(e) ami(e) et devenir riche", b: "Le/la soutenir et rester dans l'ombre", lvl: 4 },
  { a: "Ne plus jamais pouvoir mentir de ta vie", b: "Ne plus jamais pouvoir dire la vérité", lvl: 4 },
  { a: "Provoquer un scandale à un mariage", b: "Faire capoter un enterrement", lvl: 4 },
  { a: "Connaître le pire secret de chaque personne ici", b: "Qu'ils connaissent tous le tien", lvl: 4 },
  { a: "Hériter en épousant quelqu'un de mourant", b: "Rester pauvre mais libre", lvl: 4 },
  { a: "Que ta pire action passe aux infos", b: "Que ton pire message circule dans ta famille", lvl: 4 },
  { a: "Rire nerveusement à chaque mauvaise nouvelle", b: "Pleurer à chaque bonne nouvelle des autres", lvl: 4 },
  { a: "Effacer une personne de la mémoire de tous", b: "T'effacer toi-même de la leur", lvl: 4 },
  { a: "Trahir un(e) ami(e) sans qu'il/elle le sache jamais", b: "Être trahi(e) et le savoir à jamais", lvl: 4 },

  // ===== Vague 5 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { a: "Que ton patron voie le surnom que tu lui donnes", b: "Que ta belle-famille voie le sien", lvl: 2 },
  { a: "Avoir un rencard filmé pour une émission de télé", b: "Que ton pire date devienne viral malgré toi", lvl: 2 },
  { a: "Te faire poser un lapin en public", b: "Poser un lapin et te faire griller", lvl: 2 },
  { a: "Draguer en te faisant passer pour plus riche", b: "Pour beaucoup plus cultivé(e)", lvl: 2 },
  { a: "Que ton crush voie combien de fois tu as visité son profil", b: "Qu'il/elle lise tes brouillons de déclaration", lvl: 2 },
  { a: "Tomber sous le charme d'une simple voix au téléphone", b: "D'un sourire aperçu une seconde", lvl: 2 },
  { a: "Que ton téléphone sonne « chanson d'amour » en pleine réunion", b: "En plein moment solennel", lvl: 2 },
  { a: "Devoir complimenter ton ex très sincèrement", b: "Remercier la personne qui t'a largué(e)", lvl: 2 },
  { a: "Être surpris(e) à répéter ta déclaration devant le miroir", b: "À parler tout(e) seul(e) de ton crush", lvl: 2 },
  { a: "N'attirer que des gens déjà en couple", b: "N'attirer que des gens à l'autre bout du monde", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { a: "Que ton/ta partenaire te compare à voix haute à ses ex", b: "Devoir te comparer aux tiens", lvl: 3 },
  { a: "Ne jamais oser dire ce que tu aimes vraiment", b: "Devoir tout dire, sans aucun filtre", lvl: 3 },
  { a: "Un premier soir interrompu par un appel de tes parents", b: "Par ta coloc qui rentre plus tôt", lvl: 3 },
  { a: "Que ta liste de fantasmes soit imprimée", b: "Que tes anciens messages coquins soient reliés en livre", lvl: 3 },
  { a: "Coucher toujours avec une musique gênante", b: "Toujours dans le noir complet", lvl: 3 },
  { a: "Un(e) partenaire qui commente absolument tout", b: "Un(e) partenaire qui ne réagit jamais", lvl: 3 },
  { a: "Recroiser un coup d'un soir en salle d'attente médicale", b: "À la pharmacie, au pire rayon", lvl: 3 },
  { a: "Que tout le monde connaisse ta préférence", b: "Ton pire refus", lvl: 3 },
  { a: "Ne plus jamais te sentir désiré(e)", b: "Te sentir désiré(e) mais par les mauvaises personnes", lvl: 3 },
  { a: "Devoir raconter ta nuit sur un blog anonyme", b: "La raconter en détail à ton/ta meilleur(e) ami(e)", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { a: "Découvrir que toute ta famille te ment depuis toujours", b: "Apprendre que c'est TOI, le secret de la famille", lvl: 4 },
  { a: "Ressusciter une personne au prix de la vie d'une autre", b: "Ne jamais avoir ce pouvoir", lvl: 4 },
  { a: "Qu'un double maléfique prenne ta place un jour par an", b: "Que personne ne se souvienne de toi un jour par an", lvl: 4 },
  { a: "Trahir tout le monde pour sauver ta peau", b: "Te sacrifier pour un(e) parfait(e) inconnu(e)", lvl: 4 },
  { a: "Devoir choisir qui, dans la pièce, tu sauverais en dernier", b: "Qui tu laisserais tomber en premier", lvl: 4 },
  { a: "Qu'on révèle ta pire pensée sur chaque personne ici", b: "Ta pire action jamais avouée", lvl: 4 },
  { a: "Gagner en piétinant tous tes principes", b: "Rester intègre et tout perdre", lvl: 4 },
  { a: "Hanter après ta mort la personne que tu détestes", b: "Veiller sur celle que tu aimes sans jamais te montrer", lvl: 4 },
  { a: "Que ton procès imaginaire soit diffusé en direct", b: "Que ton journal intime soit publié à ta mort", lvl: 4 },
  { a: "Connaître la pire chose qu'on pense de toi", b: "La pire chose que TU penses des autres révélée à tous", lvl: 4 },

  // ===== Vague 6 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { a: "Que ton historique Netflix s'affiche à ton prochain date", b: "Ta playlist de chansons tristes", lvl: 2 },
  { a: "Un date qui t'a clairement stalké avant", b: "Un date qui te confond avec quelqu'un d'autre", lvl: 2 },
  { a: "Flirter sans savoir que c'est ton nouveau collègue", b: "Ton nouveau voisin de palier", lvl: 2 },
  { a: "Que ton crush voie ta tête au réveil", b: "T'entende chanter faux sous la douche", lvl: 2 },
  { a: "Un date parfait mais qui mâche très bruyamment", b: "Un date ennuyeux mais parfait sur la forme", lvl: 2 },
  { a: "Que ton ex devienne célèbre et raconte votre histoire", b: "Qu'il/elle t'oublie totalement", lvl: 2 },
  { a: "Rougir à chaque fois que tu mens", b: "Transpirer à chaque fois que tu dragues", lvl: 2 },
  { a: "Recevoir chaque matin un récap de tous tes ex", b: "Un rappel quotidien de tes pires vents", lvl: 2 },
  { a: "Ne pouvoir draguer qu'en parlant météo", b: "Qu'avec des questions de culture générale", lvl: 2 },
  { a: "Que ton clavier corrige « je t'aime » en « je t'aime pas »", b: "Qu'il envoie tes brouillons tout seul", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { a: "Que ton/ta partenaire tombe sur ton compte privé", b: "Sur ton pseudo secret en ligne", lvl: 3 },
  { a: "Ne faire l'amour qu'à des heures planifiées", b: "Uniquement de façon totalement imprévue", lvl: 3 },
  { a: "Un(e) partenaire qui prend des notes après", b: "Qui fait un débrief à voix haute", lvl: 3 },
  { a: "Coucher avec quelqu'un qui crie le mauvais prénom", b: "Qui reste totalement silencieux(se)", lvl: 3 },
  { a: "Devoir mimer ton fantasme devant tes amis", b: "Le confier au hasard à un(e) inconnu(e)", lvl: 3 },
  { a: "Qu'un coup d'un soir poste une story de chez toi", b: "Laisse une trace très embarrassante", lvl: 3 },
  { a: "Que ta recherche la plus honteuse s'autocomplète en public", b: "Que tes favoris s'affichent", lvl: 3 },
  { a: "Devoir garder les yeux bandés à chaque fois", b: "Ne jamais pouvoir enlever tes chaussettes", lvl: 3 },
  { a: "Coucher dans le lit de tes parents", b: "Dans le bureau de ton/ta boss", lvl: 3 },
  { a: "Devoir donner une note à chaque partenaire", b: "Recevoir la tienne à chaque fois", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { a: "Coucher avec un(e) inconnu(e) contre 10 000 €", b: "Rester fidèle et fauché(e)", lvl: 4 },
  { a: "Que ton nombre de partenaires soit annoncé au repas de Noël", b: "Ton salaire exact", lvl: 4 },
  { a: "Balancer l'infidélité de ton/ta meilleur(e) ami(e) à sa moitié", b: "Mentir pour le/la couvrir", lvl: 4 },
  { a: "Passer une nuit avec ton/ta patron(ne) pour un poste", b: "Le/la dénoncer et perdre ton job", lvl: 4 },
  { a: "Que ta sextape fuite mais tu deviens riche", b: "Que rien ne fuite mais tu restes fauché(e)", lvl: 4 },
  { a: "Draguer à un enterrement", b: "Éclater de rire à un mariage raté", lvl: 4 },
  { a: "Voler l'identité de quelqu'un pour repartir à zéro", b: "Rester coincé(e) dans ta réputation", lvl: 4 },
  { a: "Que tous tes mensonges de la semaine soient révélés", b: "Toutes tes pensées interdites", lvl: 4 },
  { a: "Devenir riche en ruinant discrètement un inconnu", b: "Rester modeste mais irréprochable", lvl: 4 },
  { a: "Hériter de la fortune d'un criminel", b: "Rester pauvre mais les mains propres", lvl: 4 },

  // ----- Vague (nouveaux dilemmes osés) ------------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Que ton crush voie toutes tes stories archivées", b: "Qu'il/elle écoute tes mémos vocaux ratés", lvl: 2 },
  { a: "Un date qui ne parle que de son ex", b: "Un date qui répond à ses mails pendant le dîner", lvl: 2 },
  { a: "Danser un slow gênant avec ton/ta boss", b: "Chanter un karaoké d'amour devant tes collègues", lvl: 2 },
  { a: "Que ton téléphone lise tes notifs au dîner de famille", b: "Que ton historique s'affiche sur la TV du salon", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Révéler ton pire coup d'un soir à la table", b: "Révéler ton meilleur, dans le détail", lvl: 3 },
  { a: "Ne séduire que par écran, jamais en vrai", b: "Ne séduire qu'en vrai, jamais par message", lvl: 3 },
  { a: "Que ton/ta partenaire note chaque nuit sur dix", b: "Devoir noter les siennes à voix haute", lvl: 3 },
  { a: "Un tête-à-tête brûlant avec une personne interdite", b: "Une soirée trop sage avec la personne parfaite", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Vendre les secrets de ton couple à un tabloïd", b: "Vendre ceux de ton/ta meilleur(e) ami(e)", lvl: 4 },
  { a: "Truquer un jeu télé pour rafler le jackpot", b: "Perdre honnêtement en direct", lvl: 4 },
  { a: "Que ton casier s'affiche sur ton profil de rencontre", b: "Que tes ex y laissent tous un avis public", lvl: 4 },
  { a: "Doubler un(e) ami(e) pour décrocher LE job", b: "Le/la laisser l'avoir et rester au placard", lvl: 4 },

  // ----- Vague 2 (nouveaux dilemmes osés) ----------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Que ton/ta crush voie tes brouillons de messages non envoyés", b: "Qu'il/elle connaisse toutes les personnes que tu as bloquées", lvl: 2 },
  { a: "Un rencard qui filme tout pour ses réseaux", b: "Un rencard qui note la soirée à voix haute", lvl: 2 },
  { a: "Devoir pimenter chaque anecdote pour séduire", b: "Ne raconter que la stricte vérité, même plate", lvl: 2 },
  { a: "Un date qui t'a clairement stalké(e) avant", b: "Un date qui confond ton prénom toute la soirée", lvl: 2 },
  { a: "Que ton ex commente toutes tes photos", b: "Que ta mère like tes posts en trois secondes", lvl: 2 },
  { a: "Avouer ton pire swipe de la semaine", b: "Montrer ton dernier match", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Faire le premier pas à chaque fois", b: "Ne jamais oser le faire", lvl: 3 },
  { a: "Un(e) partenaire qui garde tout en souvenir", b: "Un(e) partenaire qui raconte tout à ses potes", lvl: 3 },
  { a: "Révéler le lieu le plus improbable où tu l'as fait", b: "Révéler qui, dans la pièce, ne te laisserait pas indifférent(e)", lvl: 3 },
  { a: "Une nuit inoubliable avec quelqu'un d'inaccessible", b: "Dix nuits banales avec la personne parfaite", lvl: 3 },
  { a: "Dévoiler ton historique de navigation nocturne", b: "Dévoiler tes conversations privées les plus chaudes", lvl: 3 },
  { a: "N'avoir de succès qu'en vacances", b: "N'avoir de succès qu'au travail", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Truquer ton CV pour décrocher le job de tes rêves", b: "Rester honnête et sous-employé(e)", lvl: 4 },
  { a: "Que ton/ta partenaire découvre ton compte secret", b: "Que ton patron découvre ton job au noir", lvl: 4 },
  { a: "Empocher l'argent d'un portefeuille perdu", b: "Le rendre mais rater ton loyer", lvl: 4 },
  { a: "Trahir un secret d'ami pour devenir célèbre", b: "Rester anonyme et loyal(e)", lvl: 4 },
  { a: "Faire accuser un innocent à ta place", b: "Assumer une faute que tu n'as pas commise", lvl: 4 },
  { a: "Mentir sous serment pour sauver un proche", b: "Dire la vérité et l'envoyer en prison", lvl: 4 },

  // ----- Vague 3 (nouveaux dilemmes osés) ----------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Que tout le groupe voie ta dernière recherche Google", b: "Que ton patron voie ta galerie de mèmes", lvl: 2 },
  { a: "Rire nerveusement dans chaque moment sérieux", b: "Pleurer à chaque pub un peu triste", lvl: 2 },
  { a: "Envoyer un vocal de 5 minutes à ton crush", b: "Lui envoyer 30 messages d'affilée", lvl: 2 },
  { a: "Être surpris(e) à parler tout(e) seul(e)", b: "Être surpris(e) à te reluquer dans chaque vitrine", lvl: 2 },
  { a: "Oublier le prénom de ton date en pleine soirée", b: "L'appeler par le prénom de ton ex", lvl: 2 },
  { a: "Avoir un fou rire à un enterrement", b: "Décrocher le téléphone en plein mariage", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Que ton moteur de recherche s'affiche sur écran géant en boîte", b: "Que tes DM les plus chauds soient lus au micro", lvl: 3 },
  { a: "Avouer ton pire mensonge au lit", b: "Avouer ta plus grosse jalousie", lvl: 3 },
  { a: "Passer une nuit torride que tu regretteras", b: "Rater une occasion que tu regretteras toute ta vie", lvl: 3 },
  { a: "Ne plus jamais coucher mais tomber amoureux(se) souvent", b: "Coucher souvent sans jamais retomber amoureux(se)", lvl: 3 },
  { a: "Que ton/ta partenaire lise ton journal intime", b: "Qu'il/elle entende tes pensées pendant une dispute", lvl: 3 },
  { a: "Dire tout haut ce que tu penses des gens ici", b: "Que les gens disent tout haut ce qu'ils pensent de toi", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Balancer un(e) collègue pour sauver ta place", b: "Couvrir sa faute et risquer la tienne", lvl: 4 },
  { a: "Voler la vedette à ton/ta meilleur(e) ami(e) le jour de son mariage", b: "Rater complètement ton discours de témoin", lvl: 4 },
  { a: "Toucher un héritage en trahissant les dernières volontés", b: "Respecter le testament et rester fauché(e)", lvl: 4 },
  { a: "Que ta pire honte devienne un mème viral", b: "Que ton pire mensonge fasse la une", lvl: 4 },
  { a: "Effacer un souvenir gênant de la mémoire de tous", b: "Effacer une de tes plus grandes réussites", lvl: 4 },
  { a: "Dénoncer un proche qui a fraudé", b: "Te taire et devenir complice", lvl: 4 },

  // ----- Vague 4 (nouveaux dilemmes osés) ----------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Avoir le hoquet à chaque fois que tu mens", b: "Bâiller dès que quelqu'un t'ennuie", lvl: 2 },
  { a: "Ne draguer qu'avec des répliques de films", b: "Ne draguer qu'en chansons", lvl: 2 },
  { a: "Un date qui lit ton horoscope pour te juger", b: "Un date qui demande ton signe avant ton prénom", lvl: 2 },
  { a: "Rougir dès qu'on prononce un prénom qui te plaît", b: "Bégayer dès que tu essaies de séduire", lvl: 2 },
  { a: "Écrire à ton crush en pensant tout haut", b: "Liker toutes ses photos jusqu'en 2015", lvl: 2 },
  { a: "Un rencard parfait dans un lieu horrible", b: "Un lieu de rêve avec un rencard insupportable", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Coucher le premier soir à chaque relation", b: "Attendre six mois à chaque fois", lvl: 3 },
  { a: "Que ton/ta partenaire connaisse tes ex dans les moindres détails", b: "Ne jamais rien savoir de son passé", lvl: 3 },
  { a: "Un flirt endiablé qui ne mène à rien", b: "Une histoire sérieuse mais totalement plate", lvl: 3 },
  { a: "Assumer un tatouage au nom d'un(e) ex", b: "Effacer toute trace de tes relations passées", lvl: 3 },
  { a: "Dire à quelqu'un ici qu'il/elle te plaît", b: "Ne jamais oser et le regretter", lvl: 3 },
  { a: "Que ton pire date raconte la soirée en story", b: "Que ton meilleur coup en parle à tout le monde", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Piquer le/la partenaire de ton/ta meilleur(e) ami(e)", b: "Perdre cet(te) ami(e) pour toujours", lvl: 4 },
  { a: "Publier une fausse rumeur qui te rend célèbre", b: "Rester honnête et invisible", lvl: 4 },
  { a: "Encaisser une prime en dénonçant un innocent", b: "Refuser et te faire virer", lvl: 4 },
  { a: "Que ton employeur voie tout ce que tu dis de lui", b: "Que tes amis voient tout ce que tu dis d'eux", lvl: 4 },
  { a: "Accepter un énorme pot-de-vin et vivre avec", b: "Le refuser et rester fauché(e) à vie", lvl: 4 },
  { a: "Trahir ta patrie pour l'amour de ta vie", b: "Trahir ton amour pour ta patrie", lvl: 4 },

  // ----- Vague 5 (nouveaux dilemmes osés) ----------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Que ton correcteur automatique trahisse tes vraies pensées", b: "Que ta caméra s'allume au pire moment en visio", lvl: 2 },
  { a: "Un date qui parle la bouche pleine", b: "Un date qui te corrige sans arrêt", lvl: 2 },
  { a: "Chanter faux mais avec passion en soirée", b: "Danser sans aucun rythme toute la nuit", lvl: 2 },
  { a: "Que tout le monde voie ton temps d'écran quotidien", b: "Que tout le monde voie tes dépenses en livraisons", lvl: 2 },
  { a: "Être toujours celui/celle qui écrit en premier", b: "Attendre indéfiniment qu'on t'écrive", lvl: 2 },
  { a: "Recevoir un compliment gênant devant tout le monde", b: "Une critique juste mais publique", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Révéler ta position préférée à la table", b: "Révéler ton pire refus au lit", lvl: 3 },
  { a: "Un(e) partenaire bien plus expérimenté(e) que toi", b: "Bien moins expérimenté(e) que toi", lvl: 3 },
  { a: "Que ton crush entende tes pensées pendant un câlin", b: "Que ton ex les entende pendant une dispute", lvl: 3 },
  { a: "Vivre une passion intense mais interdite", b: "Un amour tranquille mais sans étincelle", lvl: 3 },
  { a: "Avouer un fantasme qui gênerait la table", b: "Écouter celui de la personne à ta gauche", lvl: 3 },
  { a: "Ne plus jamais mentir à qui tu dragues", b: "Ne plus jamais deviner quand on te ment", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Prendre le mérite du travail d'un(e) autre", b: "Voir quelqu'un rafler le crédit du tien", lvl: 4 },
  { a: "Que ta vie entière soit diffusée en télé-réalité", b: "Que tes secrets soient vendus au plus offrant", lvl: 4 },
  { a: "Séduire quelqu'un juste pour son argent", b: "Renoncer au grand confort par principe", lvl: 4 },
  { a: "Balancer un tricheur et briser une amitié", b: "Fermer les yeux et cautionner", lvl: 4 },
  { a: "Effacer toutes tes dettes en trahissant un secret", b: "Rembourser toute ta vie", lvl: 4 },
  { a: "Devenir influent(e) en manipulant l'opinion", b: "Rester intègre et ignoré(e)", lvl: 4 },

  // ----- Vague 6 (nouveaux dilemmes osés) ----------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Éternuer bruyamment à chaque baiser", b: "Avoir le fou rire à chaque câlin", lvl: 2 },
  { a: "Que ton ex soit invité à tous tes anniversaires", b: "Que ta belle-famille débarque sans prévenir", lvl: 2 },
  { a: "Ne plus pouvoir mentir sur tes sentiments", b: "Ne plus pouvoir cacher tes réactions physiques", lvl: 2 },
  { a: "Un date qui prend tout en photo", b: "Un date qui raconte la soirée en direct à sa mère", lvl: 2 },
  { a: "Draguer avec dix ans de retard sur les codes", b: "Draguer avec dix ans d'avance, incompris(e)", lvl: 2 },
  { a: "Que ton crush découvre ta playlist honteuse", b: "Qu'il/elle voie tes captures d'écran", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Coucher avec quelqu'un de bien plus âgé", b: "Avec quelqu'un que tout le monde juge", lvl: 3 },
  { a: "Avouer le plus grand nombre de la table", b: "Avouer le plus petit", lvl: 3 },
  { a: "Passer pour un(e) coincé(e)", b: "Passer pour un(e) obsédé(e)", lvl: 3 },
  { a: "Un(e) partenaire avec la règle « aucun tabou »", b: "Un(e) partenaire avec la règle « on ne parle de rien »", lvl: 3 },
  { a: "Séduire uniquement par les mots", b: "Séduire uniquement par le corps", lvl: 3 },
  { a: "Une aventure d'un soir mémorable", b: "Une amitié amoureuse ambiguë sans fin", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Vendre une vidéo intime pour rembourser tes dettes", b: "Garder ta dignité et couler", lvl: 4 },
  { a: "Trahir ton employeur pour un concurrent qui paie triple", b: "Rester loyal(e) et sous-payé(e)", lvl: 4 },
  { a: "Épouser par intérêt et jouer la comédie", b: "Rester célibataire mais sincère", lvl: 4 },
  { a: "Diffuser une info compromettante sur un rival", b: "Perdre face à lui loyalement", lvl: 4 },
  { a: "Que ton passé le plus honteux ressorte en pleine campagne", b: "Que ton pire mensonge soit prouvé", lvl: 4 },
  { a: "Sacrifier une amitié pour la gloire", b: "Rester dans l'ombre avec tes vrais amis", lvl: 4 },

  // ----- Vague 7 (nouveaux dilemmes osés) ----------------------------------
  // Niveau 2 · Épicé 🌶️
  { a: "Que ton profil de rencontre soit géré par tes amis", b: "Par tes parents", lvl: 2 },
  { a: "Matcher uniquement avec des gens trop bien pour toi", b: "Uniquement avec des gens qui te courent après", lvl: 2 },
  { a: "Avoir un rire communicatif mais ridicule", b: "Un regard charmeur mais involontairement flippant", lvl: 2 },
  { a: "Ne jamais retrouver tes mots face à qui te plaît", b: "En dire toujours beaucoup trop", lvl: 2 },
  { a: "Un date qui paie tout et le rappelle sans cesse", b: "Un date qui « oublie » toujours son portefeuille", lvl: 2 },
  { a: "Avoir une réputation de séducteur/séductrice imméritée", b: "Une réputation de coincé(e) imméritée", lvl: 2 },
  // Niveau 3 · +18 🔞
  { a: "Révéler ta recherche internet la plus honteuse", b: "Révéler ton dernier rêve très gênant", lvl: 3 },
  { a: "Un premier rendez-vous qui finit trop vite au lit", b: "Un premier rendez-vous qui ne mène jamais nulle part", lvl: 3 },
  { a: "Assumer une attirance pour quelqu'un d'interdit", b: "La nier toute ta vie", lvl: 3 },
  { a: "Que ton/ta partenaire découvre tes ex un par un", b: "Qu'il/elle découvre ton pire secret d'un coup", lvl: 3 },
  { a: "Tomber pour quelqu'un de totalement différent de toi", b: "Pour ton portrait craché", lvl: 3 },
  { a: "Vivre une romance secrète au travail", b: "Un célibat affiché mais frustrant", lvl: 3 },
  // Niveau 4 · Cancellable ☠️
  { a: "Séduire quelqu'un pour lui soutirer des infos", b: "Échouer dans ta mission par honnêteté", lvl: 4 },
  { a: "Trahir un secret de famille pour de l'argent", b: "Le garder et t'endetter", lvl: 4 },
  { a: "Devenir célèbre grâce à un scandale monté de toutes pièces", b: "Rester honnête et anonyme", lvl: 4 },
  { a: "Gagner un concours en soudoyant le jury", b: "Perdre honnêtement en finale", lvl: 4 },
  { a: "Faire chanter quelqu'un qui t'a humilié(e)", b: "Encaisser sans rien dire", lvl: 4 },
  { a: "Coucher avec l'ex de ton/ta meilleur(e) ami(e)", b: "Renoncer à un vrai coup de foudre", lvl: 4 },

  // ----- Vague 8 · Cancellable ++ (plus trash) -----------------------------
  { a: "Lâcher une caisse mémorable en plein premier rencard", b: "Roter à table devant ta belle-famille", lvl: 4 },
  { a: "Que ta recherche porno la plus bizarre s'affiche sur l'écran du salon", b: "Que ta liste de coups d'un soir soit lue au micro", lvl: 4 },
  { a: "Simuler au lit toute ta vie", b: "Apprendre que ton/ta partenaire a toujours simulé", lvl: 4 },
  { a: "Découvrir une sextape de tes parents", b: "Qu'ils tombent sur la tienne", lvl: 4 },
  { a: "Coucher une fois avec quelqu'un de repoussant mais génial", b: "Cent fois avec un canon insupportable", lvl: 4 },
  { a: "Envoyer un nude à ton groupe de famille par erreur", b: "L'envoyer à ton patron par erreur", lvl: 4 },
  { a: "Avoir un accident intestinal en public", b: "Un blanc total en pleine déclaration d'amour", lvl: 4 },
  { a: "Que ta libido s'affiche en temps réel au-dessus de ta tête", b: "Que tes pensées pendant un câlin soient sous-titrées", lvl: 4 },
  { a: "Être surpris(e) en train de te toucher par ton/ta coloc", b: "Surprendre ton/ta coloc en pleine action", lvl: 4 },
  { a: "Baver toute ta vie sur quelqu'un d'inaccessible", b: "N'être désiré(e) que par des gens que tu fuis", lvl: 4 },
  { a: "Avouer combien de fois par jour tu penses au sexe", b: "Avouer ta pratique la plus honteuse", lvl: 4 },
  { a: "Rester marqué(e) par un tatouage raté très visible", b: "Par un piercing intime qui a mal tourné", lvl: 4 },
  { a: "Draguer quelqu'un puis découvrir que c'est un(e) cousin(e) éloigné(e)", b: "Découvrir que c'est l'ex de ton parent", lvl: 4 },
  { a: "Que tout le monde connaisse ton pire fantasme", b: "Ta plus grosse insécurité au lit", lvl: 4 },
  { a: "Coucher avec un(e) inconnu(e) contre un CDI", b: "Rester au chômage mais intègre", lvl: 4 },

  // ----- Vague 9 · Cancellable ++ -----------------------------------------
  { a: "Coucher avec le/la partenaire de ton patron pour grimper", b: "Saboter un(e) collègue plus doué(e) que toi", lvl: 4 },
  { a: "Filmer tes ébats sans le dire à l'autre", b: "Découvrir que l'autre t'a filmé sans te le dire", lvl: 4 },
  { a: "Que ta famille apprenne ton métier le plus honteux", b: "Que ton patron apprenne ton passé sulfureux", lvl: 4 },
  { a: "Cracher dans le verre de quelqu'un que tu détestes", b: "Resservir une frite tombée par terre", lvl: 4 },
  { a: "Faire semblant d'être orphelin(e) pour un héritage", b: "Vendre un secret de famille aux tabloïds", lvl: 4 },
  { a: "Draguer ton médecin pendant la consultation", b: "Draguer ton avocat en plein procès", lvl: 4 },
  { a: "Coucher avec quelqu'un pour éviter de payer ton loyer", b: "Dormir dehors mais fier(e)", lvl: 4 },
  { a: "Que ton casier judiciaire soit tatoué sur ton front", b: "Ton nombre de partenaires tatoué sur ton bras", lvl: 4 },
  { a: "Avoir une aventure avec le prof de tes enfants", b: "Avec le/la meilleur(e) ami(e) de ton/ta partenaire", lvl: 4 },
  { a: "Piquer dans la caisse d'une association", b: "Voler le pourboire d'un serveur", lvl: 4 },
  { a: "Coucher le soir de l'enterrement de ton ex", b: "Éclater de rire pendant une minute de silence", lvl: 4 },
  { a: "Balancer ton meilleur pote pour une grosse récompense", b: "Prendre sa place en prison", lvl: 4 },
  { a: "Te faire prendre en flagrant délit d'adultère", b: "Avouer toi-même ta trahison", lvl: 4 },
  { a: "Séduire des jumeaux/jumelles sans qu'ils le sachent", b: "Te faire griller au pire moment", lvl: 4 },
  { a: "Avouer une infidélité en plein repas de famille", b: "La garder secrète toute ta vie", lvl: 4 },

  // ----- Vague 10 · Cancellable ++ ----------------------------------------
  { a: "Rester coincé(e) aux toilettes sans papier en pleine soirée", b: "Découvrir trop tard que ta braguette était ouverte toute la nuit", lvl: 4 },
  { a: "Que ton/ta partenaire trouve tes jouets cachés", b: "Que ta mère les trouve", lvl: 4 },
  { a: "Avoir le prénom de ton coup d'un soir tatoué", b: "Un dessin très cru bien visible", lvl: 4 },
  { a: "Coucher avec quelqu'un qui sent mauvais mais incroyable", b: "Avec quelqu'un de parfait mais nul au lit", lvl: 4 },
  { a: "Être filmé(e) en train de chanter nu(e) sous la douche", b: "Filmé(e) en train de parler à ton reflet", lvl: 4 },
  { a: "Tromper et te faire pardonner en mentant", b: "Avouer et tout perdre", lvl: 4 },
  { a: "Que ton employeur découvre ton compte OnlyFans", b: "Que tes parents s'y abonnent par erreur", lvl: 4 },
  { a: "Faire l'amour bruyamment dans des murs en papier", b: "Entendre tes voisins toute la nuit", lvl: 4 },
  { a: "Draguer quelqu'un qui se révèle marié", b: "Draguer le/la patron(ne) de ton/ta partenaire", lvl: 4 },
  { a: "Que ton dossier médical intime soit public", b: "Que ton relevé bancaire le soit", lvl: 4 },
  { a: "Assumer un tatouage « no regret » mal orthographié", b: "Un piercing qui fait sonner les portiques", lvl: 4 },
  { a: "Coucher avec ton/ta thérapeute", b: "Avec ton coach sportif", lvl: 4 },
  { a: "Envoyer un message d'insultes à ton boss par erreur", b: "Un message d'amour enflammé à ta belle-mère", lvl: 4 },
  { a: "Devoir rejouer ta nuit la plus honteuse en public", b: "L'oublier, mais aussi oublier ta meilleure nuit", lvl: 4 },

  // ----- Vague 11 · Cancellable ++ ----------------------------------------
  { a: "Que ton/ta crush lise tous tes messages le/la concernant", b: "Que le groupe vote ton pire trait au lit", lvl: 4 },
  { a: "Avoir un bruit très gênant à chaque orgasme", b: "Un tic incontrôlable dès que tu es excité(e)", lvl: 4 },
  { a: "Coucher avec un(e) inconnu(e) chaque mois pour rester riche", b: "Être fidèle mais fauché(e) à vie", lvl: 4 },
  { a: "Que ta pire photo devienne un mème mondial", b: "Qu'une vidéo intime fuite anonymement", lvl: 4 },
  { a: "Draguer trois personnes dans la même soirée et te faire griller", b: "Ne jamais oser aborder personne", lvl: 4 },
  { a: "Que ton ex devienne ton patron", b: "Que ton coup d'un soir devienne ton/ta colocataire", lvl: 4 },
  { a: "Confondre le prénom de ton/ta partenaire au lit", b: "Publier une story très compromettante bourré(e)", lvl: 4 },
  { a: "Assumer une sextape ratée devenue virale", b: "Un fou rire incontrôlable à chaque moment intime", lvl: 4 },
  { a: "Te faire larguer par SMS devant tout le monde", b: "Larguer quelqu'un le jour de son anniversaire", lvl: 4 },
  { a: "Un rendez-vous galant interrompu par la police", b: "Interrompu par tes parents en pyjama", lvl: 4 },
  { a: "Révéler ton plus gros mensonge amoureux", b: "Révéler le pire vent que tu aies mis", lvl: 4 },
  { a: "Que ton coach sportif connaisse tous tes fantasmes", b: "Que ton dentiste connaisse ton nombre de partenaires", lvl: 4 },

  // ----- Vague 12 · Cancellable ++ (sans filtre) --------------------------
  { a: "Devoir annoncer à la table « avaler ou recracher »", b: "Révéler ta position la moins avouable", lvl: 4 },
  { a: "Te faire surprendre en train de te masturber par ta coloc", b: "La surprendre avec un jouet en marche", lvl: 4 },
  { a: "Un ménage à trois avec deux ex", b: "Un ménage à trois avec deux inconnus rencontrés ce soir", lvl: 4 },
  { a: "Que ton nom soit sur une sextape virale", b: "Sur une liste publique de mauvais coups", lvl: 4 },
  { a: "Lécher le sol d'un bar pour 500 €", b: "Rouler une pelle à un inconnu aux dents pourries pour 500 €", lvl: 4 },
  { a: "Coucher avec le/la meilleur(e) ami(e) de ta mère", b: "Avec l'ex de ton père", lvl: 4 },
  { a: "Vomir dans le lit d'un(e) inconnu(e) en soirée", b: "Boucher ses toilettes de façon mémorable", lvl: 4 },
  { a: "Que tes parents tombent sur une de tes vidéos intimes", b: "Que tu tombes sur une des leurs", lvl: 4 },
  { a: "Simuler ta mort pour échapper à tes dettes", b: "Voler l'héritage de ta propre famille", lvl: 4 },
  { a: "Avoir une odeur intime insupportable", b: "Des bruits corporels incontrôlables au lit", lvl: 4 },
  { a: "Balancer le nom de ton meilleur coup à la table", b: "Balancer celui de ton pire", lvl: 4 },
  { a: "Que ton historique porno soit envoyé à tous tes contacts", b: "Que tes nudes soient affichés au bureau", lvl: 4 },
  { a: "Coucher une fois pour de l'argent, filmé(e)", b: "Rester fauché(e) mais tranquille", lvl: 4 },
  { a: "Manger un plat préparé par ton pire ennemi", b: "Coucher avec quelqu'un choisi par tes ex", lvl: 4 },
  { a: "Draguer en salle d'attente d'un hôpital", b: "Draguer à un enterrement pendant l'éloge", lvl: 4 },
];

/**
 * Pioche pour un ensemble de niveaux ACTIFS : le grand public (niveau 1) s'il est
 * actif + le contenu osé des niveaux actifs. Sélection indépendante (ex. 1 et 4).
 */
export function dilemmasForLevels(levels: CancelLevel[]): Dilemma[] {
  return [...(levels.includes(1) ? DILEMMAS : []), ...filterHot(DILEMMAS_HOT, levels)];
}
