import { universe } from "../_build";

export const acreed = universe("jeuxvideo", "Assassin's Creed", [
  // --- Faciles (5) ---
  { id: "acreed-f1", d: 1, t: "Quel éditeur français développe la série Assassin's Creed ?", a: "Ubisoft", x: ["Activision", "EA", "Capcom"], acc: ["ubisoft"] },
  { id: "acreed-f2", d: 1, t: "Quelles deux factions s'affrontent depuis toujours dans Assassin's Creed ?", a: "Les Assassins et les Templiers", x: ["Les Pirates et la Marine", "Les Elfes et les Orques", "Les Rebelles et l'Empire"], acc: ["assassins et templiers", "assassins et les templiers", "assassins templiers"] },
  { id: "acreed-f3", d: 1, t: "Quelle machine permet de revivre les souvenirs des ancêtres ?", a: "L'Animus", x: ["La Matrice", "Le Portail", "Le Simulateur"], acc: ["animus", "l'animus"] },
  { id: "acreed-f4", d: 1, t: "À quel genre appartient principalement Assassin's Creed ?", a: "L'action-aventure et l'infiltration", x: ["La course", "Le jeu de rythme", "La gestion"], acc: ["action-aventure", "infiltration", "action et infiltration"] },
  { id: "acreed-f5", d: 1, t: "Dans quels cadres se déroulent la plupart des jeux Assassin's Creed ?", a: "Des époques historiques", x: ["Le futur lointain", "Des mondes imaginaires", "La préhistoire uniquement"], acc: ["historiques", "epoques historiques", "le passe"] },
  // --- Moyennes (10) ---
  { id: "acreed-m1", d: 2, t: "En quelle année le premier Assassin's Creed est-il sorti ?", a: "2007", x: ["2001", "2012", "2015"], acc: ["2007"] },
  { id: "acreed-m2", d: 2, t: "Quelle arme dissimulée est l'outil emblématique des Assassins ?", a: "La lame secrète", x: ["Le pistolet", "Le fouet", "L'arc long"], acc: ["lame secrete", "la lame secrete", "hidden blade"] },
  { id: "acreed-m3", d: 2, t: "Comment appelle-t-on le saut spectaculaire des Assassins depuis les hauteurs ?", a: "Le saut de la foi", x: ["Le grand plongeon", "Le saut de l'ange", "La chute libre"], acc: ["saut de la foi", "leap of faith"] },
  { id: "acreed-m4", d: 2, t: "Comment s'appelle le célèbre assassin de la Renaissance italienne ?", a: "Ezio Auditore", x: ["Altaïr", "Connor", "Arno"], acc: ["ezio", "ezio auditore"] },
  { id: "acreed-m5", d: 2, t: "Quelle devise résume la philosophie des Assassins ?", a: "Rien n'est vrai, tout est permis", x: ["La fin justifie les moyens", "Un pour tous", "Vaincre ou mourir"], acc: ["rien n'est vrai tout est permis", "nothing is true everything is permitted"] },
  { id: "acreed-m6", d: 2, t: "Quel artefact convoité, la « Pomme », confère un grand pouvoir ?", a: "La Pomme d'Éden", x: ["Le Saint-Graal", "La Pierre philosophale", "Le Sceptre d'or"], acc: ["pomme d'eden", "pomme d'éden", "apple of eden"] },
  { id: "acreed-m7", d: 2, t: "Comment s'appelle le pouvoir qui met en évidence ennemis et objets importants ?", a: "La vision d'aigle", x: ["La vision nocturne", "Le sixième sens", "L'œil de faucon"], acc: ["vision d'aigle", "eagle vision"] },
  { id: "acreed-m8", d: 2, t: "Dans quel épisode incarne-t-on un pirate dans les Caraïbes ?", a: "Black Flag", x: ["Unity", "Origins", "Valhalla"], acc: ["black flag", "assassin's creed 4"] },
  { id: "acreed-m9", d: 2, t: "Dans quelle ville de la Renaissance débute l'aventure d'Ezio ?", a: "Florence", x: ["Rome", "Paris", "Le Caire"], acc: ["florence"] },
  { id: "acreed-m10", d: 2, t: "Comment s'appelle le héros moderne des premiers jeux, relié à l'Animus ?", a: "Desmond Miles", x: ["Ezio", "Altaïr", "Bayek"], acc: ["desmond", "desmond miles"] },
  // --- Dures (15) ---
  { id: "acreed-d1", d: 3, t: "Comment s'appelle le héros du tout premier Assassin's Creed, à l'époque des croisades ?", a: "Altaïr", x: ["Ezio", "Connor", "Arno"], acc: ["altair", "altaïr"] },
  { id: "acreed-d2", d: 3, t: "Dans quel pays se déroule Assassin's Creed Origins ?", a: "L'Égypte antique", x: ["La Grèce antique", "Le Japon féodal", "L'Angleterre viking"], acc: ["egypte", "egypte antique", "l'egypte"] },
  { id: "acreed-d3", d: 3, t: "Comment s'appelle le héros fondateur de la Confrérie dans Origins ?", a: "Bayek", x: ["Kassandra", "Eivor", "Arno"], acc: ["bayek"] },
  { id: "acreed-d4", d: 3, t: "Dans quel épisode incarne-t-on Kassandra ou Alexios, en Grèce antique ?", a: "Odyssey", x: ["Origins", "Valhalla", "Unity"], acc: ["odyssey", "assassin's creed odyssey"] },
  { id: "acreed-d5", d: 3, t: "Dans quel épisode joue-t-on un Viking nommé Eivor ?", a: "Valhalla", x: ["Odyssey", "Origins", "Black Flag"], acc: ["valhalla"] },
  { id: "acreed-d6", d: 3, t: "Dans quelle ville et quelle révolution se déroule Assassin's Creed Unity ?", a: "Paris, la Révolution française", x: ["Londres, la révolution industrielle", "La Rome antique", "Boston, la révolution américaine"], acc: ["paris revolution francaise", "revolution francaise", "paris"] },
  { id: "acreed-d7", d: 3, t: "Comment s'appelle le héros d'Assassin's Creed Unity ?", a: "Arno", x: ["Connor", "Edward", "Bayek"], acc: ["arno", "arno dorian"] },
  { id: "acreed-d8", d: 3, t: "Comment s'appelle le héros d'Assassin's Creed 3, durant la révolution américaine ?", a: "Connor", x: ["Ezio", "Arno", "Edward"], acc: ["connor"] },
  { id: "acreed-d9", d: 3, t: "Comment s'appelle le pirate héros de Black Flag ?", a: "Edward Kenway", x: ["Connor", "Arno", "Altaïr"], acc: ["edward kenway", "edward", "kenway"] },
  { id: "acreed-d10", d: 3, t: "Comment s'appelle l'entreprise moderne qui sert de façade aux Templiers ?", a: "Abstergo", x: ["Umbrella", "Vault-Tec", "Aperture"], acc: ["abstergo", "abstergo industries"] },
  { id: "acreed-d11", d: 3, t: "Quel studio d'Ubisoft a développé les premiers Assassin's Creed ?", a: "Ubisoft Montréal", x: ["Ubisoft Paris", "Ubisoft Toronto", "Ubisoft Milan"], acc: ["ubisoft montreal", "montreal"] },
  { id: "acreed-d12", d: 3, t: "Comment s'appelle le navire d'Edward Kenway dans Black Flag ?", a: "Le Jackdaw", x: ["L'Aquila", "Le Morrigan", "L'Adrestia"], acc: ["jackdaw", "le jackdaw"] },
  { id: "acreed-d13", d: 3, t: "Comment appelle-t-on la civilisation avancée qui a précédé l'humanité ?", a: "Les Isus", x: ["Les Atlantes", "Les Titans", "Les Anciens Dieux"], acc: ["isus", "les isus", "isu", "premiere civilisation"] },
  { id: "acreed-d14", d: 3, t: "Comment appelle-t-on la fidélité aux souvenirs à maintenir dans l'Animus ?", a: "La synchronisation", x: ["La calibration", "La résonance", "L'harmonie"], acc: ["synchronisation", "sync"] },
  { id: "acreed-d15", d: 3, t: "Comment s'appelle l'aigle qui accompagne et éclaire Bayek dans Origins ?", a: "Senu", x: ["Ikaros", "Sunna", "Ra"], acc: ["senu"] },
  // --- Pro (20) ---
  { id: "acreed-p1", d: 4, t: "Dans quel pays se déroule Assassin's Creed Shadows, sorti en 2025 ?", a: "Le Japon féodal", x: ["La Chine impériale", "La Corée", "L'Inde"], acc: ["japon", "japon feodal", "le japon"] },
  { id: "acreed-p2", d: 4, t: "Quels deux héros incarne-t-on dans Assassin's Creed Shadows ?", a: "Naoe et Yasuke", x: ["Kassandra et Alexios", "Altaïr et Ezio", "Connor et Haytham"], acc: ["naoe et yasuke", "naoe", "yasuke"] },
  { id: "acreed-p3", d: 4, t: "Quel personnage historique, samouraï d'origine africaine, est jouable dans Shadows ?", a: "Yasuke", x: ["Nobunaga", "Hattori", "Musashi"], acc: ["yasuke"] },
  { id: "acreed-p4", d: 4, t: "Comment s'appelle l'aigle qui accompagne Kassandra dans Odyssey ?", a: "Ikaros", x: ["Senu", "Sunna", "Pégase"], acc: ["ikaros"] },
  { id: "acreed-p5", d: 4, t: "Dans quel pays Eivor mène-t-il ses raids vikings dans Valhalla ?", a: "L'Angleterre", x: ["La Norvège uniquement", "La France", "L'Écosse"], acc: ["angleterre", "l'angleterre"] },
  { id: "acreed-p6", d: 4, t: "Quelle reine d'Égypte apparaît dans Assassin's Creed Origins ?", a: "Cléopâtre", x: ["Néfertiti", "Hatchepsout", "Isis"], acc: ["cleopatre", "cléopâtre"] },
  { id: "acreed-p7", d: 4, t: "Comment s'appelle le navire de Connor dans Assassin's Creed 3 ?", a: "L'Aquila", x: ["Le Jackdaw", "Le Morrigan", "L'Adrestia"], acc: ["aquila", "l'aquila"] },
  { id: "acreed-p8", d: 4, t: "Comment s'appelle le navire de Kassandra dans Odyssey ?", a: "L'Adrestia", x: ["Le Jackdaw", "L'Aquila", "Le Morrigan"], acc: ["adrestia", "l'adrestia"] },
  { id: "acreed-p9", d: 4, t: "Quel monument parisien, recréé dans Unity, a servi de référence après son incendie ?", a: "Notre-Dame de Paris", x: ["La tour Eiffel", "Le Louvre", "L'Arc de Triomphe"], acc: ["notre-dame", "notre dame", "notre-dame de paris"] },
  { id: "acreed-p10", d: 4, t: "Comment s'appelle le père templier de Connor dans Assassin's Creed 3 ?", a: "Haytham Kenway", x: ["Edward Kenway", "Achilles", "Charles Lee"], acc: ["haytham", "haytham kenway"] },
  { id: "acreed-p11", d: 4, t: "Quel épisode de 2010 introduit le recrutement d'assassins par Ezio à Rome ?", a: "Brotherhood", x: ["Revelations", "Unity", "Origins"], acc: ["brotherhood", "assassin's creed brotherhood"] },
  { id: "acreed-p12", d: 4, t: "Dans quel épisode Ezio, âgé, voyage-t-il jusqu'à Constantinople ?", a: "Revelations", x: ["Brotherhood", "Black Flag", "Unity"], acc: ["revelations", "assassin's creed revelations"] },
  { id: "acreed-p13", d: 4, t: "Comment s'appelle la déesse Isu qui met en garde Desmond ?", a: "Minerve", x: ["Junon", "Héra", "Athéna"], acc: ["minerve", "minerva"] },
  { id: "acreed-p14", d: 4, t: "Comment appelle-t-on les artefacts anciens et puissants disséminés dans la série ?", a: "Les Fragments d'Éden", x: ["Les Reliques sacrées", "Les Cristaux du temps", "Les Sceaux"], acc: ["fragments d'eden", "pieces of eden", "fragments d'éden"] },
  { id: "acreed-p15", d: 4, t: "Quel assassin turc guide Ezio dans Revelations ?", a: "Yusuf Tazim", x: ["Haytham", "Malik", "Achilles"], acc: ["yusuf", "yusuf tazim"] },
  { id: "acreed-p16", d: 4, t: "Quel génie de la Renaissance est l'ami inventeur d'Ezio ?", a: "Léonard de Vinci", x: ["Michel-Ange", "Machiavel", "Galilée"], acc: ["leonard de vinci", "vinci", "leonardo da vinci"] },
  { id: "acreed-p17", d: 4, t: "Contre quelle cité Athènes s'oppose-t-elle en toile de fond d'Odyssey ?", a: "Sparte", x: ["Rome", "Troie", "Thèbes"], acc: ["sparte"] },
  { id: "acreed-p18", d: 4, t: "Dans quel épisode de 2015 l'action se déroule à Londres durant la révolution industrielle ?", a: "Syndicate", x: ["Unity", "Rogue", "Origins"], acc: ["syndicate", "assassin's creed syndicate"] },
  { id: "acreed-p19", d: 4, t: "Comment s'appelle le mentor qui forme Connor dans Assassin's Creed 3 ?", a: "Achilles", x: ["Haytham", "Charles Lee", "Yusuf"], acc: ["achilles", "achilles davenport"] },
  { id: "acreed-p20", d: 4, t: "Quel événement historique sert de toile de fond au premier Assassin's Creed ?", a: "La troisième croisade", x: ["La guerre de Cent Ans", "La Renaissance", "La conquête de l'Amérique"], acc: ["troisieme croisade", "croisade", "3e croisade"] },
]);
