import { universe } from "../_build";

export const baldursgate = universe("jeuxvideo", "Baldur's Gate", [
  // --- Faciles (5) ---
  { id: "baldur-f1", d: 1, t: "Quel studio belge a développé Baldur's Gate 3 ?", a: "Larian Studios", x: ["BioWare", "Obsidian", "Bethesda"], acc: ["larian", "larian studios"] },
  { id: "baldur-f2", d: 1, t: "De quel célèbre jeu de rôle sur table Baldur's Gate s'inspire-t-il ?", a: "Donjons et Dragons", x: ["Warhammer", "L'Appel de Cthulhu", "Pathfinder"], acc: ["donjons et dragons", "dnd", "d&d"] },
  { id: "baldur-f3", d: 1, t: "À quel genre appartient Baldur's Gate 3 ?", a: "Le jeu de rôle", x: ["Le jeu de course", "Le jeu de tir", "Le jeu de rythme"], acc: ["jeu de role", "rpg"] },
  { id: "baldur-f4", d: 1, t: "De quoi Baldur's Gate tire-t-il son nom ?", a: "D'une grande cité", x: ["D'un océan", "D'un dragon", "D'une épée"], acc: ["cite", "cité", "ville"] },
  { id: "baldur-f5", d: 1, t: "Quel grand titre Baldur's Gate 3 a-t-il remporté aux Game Awards 2023 ?", a: "Le jeu de l'année", x: ["Le meilleur jeu de course", "Le meilleur jeu de sport", "Le meilleur jeu mobile"], acc: ["jeu de l'annee", "goty"] },
  // --- Moyennes (10) ---
  { id: "baldur-m1", d: 2, t: "Quel parasite les héros de BG3 ont-ils dans la tête au début, menaçant de les transformer ?", a: "Un têtard d'illithid", x: ["Un ver de sable", "Un symbiote", "Une puce électronique"], acc: ["tetard", "tetard d'illithid", "tadpole"] },
  { id: "baldur-m2", d: 2, t: "En quelle créature à tête de pieuvre le parasite risque-t-il de transformer les héros ?", a: "Un flagelleur mental", x: ["Un dragon", "Un gobelin", "Un vampire"], acc: ["flagelleur mental", "mind flayer", "illithid"] },
  { id: "baldur-m3", d: 2, t: "Quel compagnon élégant se révèle être un vampire ?", a: "Astarion", x: ["Gale", "Wyll", "Halsin"], acc: ["astarion"] },
  { id: "baldur-m4", d: 2, t: "Quelle compagne, clerc mystérieuse, cache une relique au début du jeu ?", a: "Shadowheart", x: ["Lae'zel", "Karlach", "Minthara"], acc: ["shadowheart"] },
  { id: "baldur-m5", d: 2, t: "Quel compagnon magicien adore les objets magiques et vit lié à la Dame de la magie ?", a: "Gale", x: ["Astarion", "Wyll", "Halsin"], acc: ["gale"] },
  { id: "baldur-m6", d: 2, t: "De quel peuple guerrier au teint verdâtre la compagne Lae'zel est-elle issue ?", a: "Les githyankis", x: ["Les elfes", "Les nains", "Les tieffelins"], acc: ["githyanki", "githyankis"] },
  { id: "baldur-m7", d: 2, t: "Quelle compagne barbare tieffeline a un cœur mécanique après un séjour aux Enfers ?", a: "Karlach", x: ["Shadowheart", "Lae'zel", "Minthara"], acc: ["karlach"] },
  { id: "baldur-m8", d: 2, t: "Comment se déroulent les combats de Baldur's Gate 3 ?", a: "Au tour par tour", x: ["En temps réel pur", "En rythme musical", "Au clic rapide"], acc: ["tour par tour"] },
  { id: "baldur-m9", d: 2, t: "Quel dé à vingt faces détermine la réussite des actions dans le jeu ?", a: "Le d20", x: ["Le dé à six faces", "La roue de la fortune", "Le dé à cent faces"], acc: ["d20"] },
  { id: "baldur-m10", d: 2, t: "Sur quelle côte du monde de Faerûn se déroule l'aventure ?", a: "La Côte des Épées", x: ["La Côte d'Azur", "La Côte Barbare", "La Côte de Jade"], acc: ["cote des epees", "côte des épées", "sword coast"] },
  // --- Dures (15) ---
  { id: "baldur-d1", d: 3, t: "Quel culte, mené par « l'Absolu », menace la région dans BG3 ?", a: "Le culte de l'Absolu", x: ["La Main Noire", "Les Zhentarims", "La Toison d'or"], acc: ["culte de l'absolu", "absolu"] },
  { id: "baldur-d2", d: 3, t: "Combien d'« Élus » servent l'Absolu, détenant chacun une pierre nétherienne ?", a: "Trois", x: ["Un", "Deux", "Cinq"], acc: ["3", "trois"] },
  { id: "baldur-d3", d: 3, t: "Quel compagnon sorcier est surnommé « la Lame des Frontières » ?", a: "Wyll", x: ["Gale", "Astarion", "Halsin"], acc: ["wyll"] },
  { id: "baldur-d4", d: 3, t: "Quel druide, capable de se transformer en ours, peut rejoindre l'équipe ?", a: "Halsin", x: ["Gale", "Wyll", "Minsc"], acc: ["halsin"] },
  { id: "baldur-d5", d: 3, t: "Quel guerrier culte voyage avec Boo, son hamster « miniature géant de l'espace » ?", a: "Minsc", x: ["Jaheira", "Halsin", "Wyll"], acc: ["minsc"] },
  { id: "baldur-d6", d: 3, t: "Quelle demi-elfe druidesse, déjà présente dans les anciens jeux, revient dans BG3 ?", a: "Jaheira", x: ["Shadowheart", "Karlach", "Minthara"], acc: ["jaheira"] },
  { id: "baldur-d7", d: 3, t: "Comment se nomme l'origine de personnage tourmentée par de sombres pulsions meurtrières ?", a: "La Pulsion noire", x: ["Le Sang maudit", "L'Âme brisée", "Le Pacte sombre"], acc: ["pulsion noire", "dark urge"] },
  { id: "baldur-d8", d: 3, t: "Quel squelette énigmatique peut ressusciter les personnages morts, au camp ?", a: "Withers", x: ["Volo", "Raphaël", "Halsin"], acc: ["withers"] },
  { id: "baldur-d9", d: 3, t: "Quel diable élégant propose des marchés tentants au fil de l'aventure ?", a: "Raphaël", x: ["Withers", "Gortash", "Astarion"], acc: ["raphael", "raphaël"] },
  { id: "baldur-d10", d: 3, t: "À quelle déesse des ténèbres Shadowheart voue-t-elle d'abord son culte ?", a: "Shar", x: ["Selûne", "Mystra", "Lolth"], acc: ["shar"] },
  { id: "baldur-d11", d: 3, t: "De quelle déesse de la magie Gale a-t-il été l'amant ?", a: "Mystra", x: ["Shar", "Selûne", "Tymora"], acc: ["mystra"] },
  { id: "baldur-d12", d: 3, t: "À bord de quel vaisseau volant des illithids l'aventure débute-t-elle ?", a: "Un nautiloïde", x: ["Un galion", "Un dirigeable", "Un drakkar"], acc: ["nautiloide", "nautiloïde"] },
  { id: "baldur-d13", d: 3, t: "Quel Élu, général immortel, se retranche aux Tours de l'Aube Lunaire ?", a: "Ketheric Thorm", x: ["Enver Gortash", "Orin la Rouge", "Sarevok"], acc: ["ketheric thorm", "ketheric"] },
  { id: "baldur-d14", d: 3, t: "Quelle Élue métamorphe, dévote de Bhaal, sème le chaos dans la cité ?", a: "Orin la Rouge", x: ["Ketheric Thorm", "Enver Gortash", "Minthara"], acc: ["orin", "orin la rouge"] },
  { id: "baldur-d15", d: 3, t: "Quel Élu ambitieux s'empare du pouvoir politique à Baldur's Gate ?", a: "Enver Gortash", x: ["Ketheric Thorm", "Orin la Rouge", "Raphaël"], acc: ["gortash", "enver gortash"] },
  // --- Pro (20) ---
  { id: "baldur-p1", d: 4, t: "En quelle année Baldur's Gate 3 est-il sorti en version complète ?", a: "2023", x: ["2019", "2021", "2025"], acc: ["2023"] },
  { id: "baldur-p2", d: 4, t: "Quel patron de Larian a présenté et dirigé Baldur's Gate 3 ?", a: "Swen Vincke", x: ["Todd Howard", "Hideo Kojima", "Sam Lake"], acc: ["swen vincke", "vincke"] },
  { id: "baldur-p3", d: 4, t: "Quelle autre grande série de Larian a précédé Baldur's Gate 3 ?", a: "Divinity Original Sin", x: ["Dragon Age", "Pillars of Eternity", "The Witcher"], acc: ["divinity", "divinity original sin"] },
  { id: "baldur-p4", d: 4, t: "Sur quelle édition des règles de Donjons et Dragons BG3 se base-t-il ?", a: "La cinquième", x: ["La deuxième", "La troisième", "La septième"], acc: ["5e", "cinquieme", "cinquième"] },
  { id: "baldur-p5", d: 4, t: "Quel studio avait créé les tout premiers Baldur's Gate à la fin des années 1990 ?", a: "BioWare", x: ["Larian", "Obsidian", "Rockstar"], acc: ["bioware"] },
  { id: "baldur-p6", d: 4, t: "Dans les premiers jeux, le héros est l'enfant de quel dieu du Meurtre ?", a: "Bhaal", x: ["Bane", "Myrkul", "Cyric"], acc: ["bhaal"] },
  { id: "baldur-p7", d: 4, t: "Quel demi-frère du héros est le grand méchant du premier Baldur's Gate ?", a: "Sarevok", x: ["Jon Irenicus", "Bodhi", "Enver Gortash"], acc: ["sarevok"] },
  { id: "baldur-p8", d: 4, t: "Quel mage elfe déchu est l'antagoniste de Baldur's Gate 2 ?", a: "Jon Irenicus", x: ["Sarevok", "Ketheric Thorm", "Raphaël"], acc: ["irenicus", "jon irenicus"] },
  { id: "baldur-p9", d: 4, t: "Combien de classes jouables Baldur's Gate 3 propose-t-il ?", a: "Douze", x: ["Six", "Neuf", "Vingt"], acc: ["12", "douze"] },
  { id: "baldur-p10", d: 4, t: "Quel mystérieux protecteur, apparaissant dans les rêves, se révèle être un illithid ?", a: "L'Empereur", x: ["Withers", "Raphaël", "Volo"], acc: ["empereur", "l'empereur"] },
  { id: "baldur-p11", d: 4, t: "Quel gigantesque cerveau illithid est la menace finale de BG3 ?", a: "Le Cerveau nether", x: ["L'Absolu originel", "Le Roi-Liche", "Le Dragon de bronze"], acc: ["cerveau nether", "netherbrain"] },
  { id: "baldur-p12", d: 4, t: "Quel chien errant peut-on adopter et ramener au camp ?", a: "Scratch", x: ["Boo", "Guapo", "Cerbère"], acc: ["scratch"] },
  { id: "baldur-p13", d: 4, t: "Quel petit animal hybride, mi-hibou mi-ours, peut aussi rejoindre le camp ?", a: "Le bébé hibours", x: ["Le louveteau", "Le dragonnet", "Le chaton-tigre"], acc: ["hibours", "bebe hibours", "owlbear"] },
  { id: "baldur-p14", d: 4, t: "Quel barde vantard et écrivain propose une opération de l'œil hasardeuse ?", a: "Volo", x: ["Withers", "Raphaël", "Minsc"], acc: ["volo"] },
  { id: "baldur-p15", d: 4, t: "En combien d'actes principaux l'histoire de BG3 se divise-t-elle ?", a: "Trois", x: ["Deux", "Cinq", "Sept"], acc: ["3", "trois"] },
  { id: "baldur-p16", d: 4, t: "Au premier acte, quel bosquet de druides abrite des réfugiés tieffelins ?", a: "Le Bosquet d'Émeraude", x: ["Les Tours de l'Aube Lunaire", "La Porte de Baldur", "Grymforge"], acc: ["bosquet d'emeraude", "bosquet d'émeraude", "emerald grove"] },
  { id: "baldur-p17", d: 4, t: "Quelle prêtresse drow, servante de l'Absolu, peut devenir compagne ?", a: "Minthara", x: ["Shadowheart", "Lae'zel", "Jaheira"], acc: ["minthara"] },
  { id: "baldur-p18", d: 4, t: "Quel métal des Enfers faut-il pour réparer le cœur de Karlach ?", a: "Le fer infernal", x: ["Le mithril", "L'adamantium", "L'orichalque"], acc: ["fer infernal"] },
  { id: "baldur-p19", d: 4, t: "Dans quel pays le studio Larian a-t-il son siège historique ?", a: "La Belgique", x: ["Les Pays-Bas", "La Pologne", "La France"], acc: ["belgique"] },
  { id: "baldur-p20", d: 4, t: "Combien de personnages peut-on emmener en même temps dans son groupe ?", a: "Quatre", x: ["Deux", "Six", "Huit"], acc: ["4", "quatre"] },
]);
