import { universe } from "../_build";

export const clairobscur = universe("jeuxvideo", "Clair Obscur Expédition 33", [
  // --- Faciles (5) ---
  { id: "co33-f1", d: 1, t: "Dans quel pays est basé Sandfall Interactive, le studio de Clair Obscur: Expédition 33 ?", a: "La France", x: ["Le Japon", "Les États-Unis", "Le Canada"], acc: ["france", "la france"] },
  { id: "co33-f2", d: 1, t: "À quel genre appartient Clair Obscur: Expédition 33 ?", a: "Le RPG au tour par tour", x: ["Le jeu de course", "Le jeu de tir à la première personne", "Le jeu de gestion"], acc: ["rpg", "tour par tour", "jeu de role"] },
  { id: "co33-f3", d: 1, t: "En quelle année Clair Obscur: Expédition 33 est-il sorti ?", a: "2025", x: ["2021", "2023", "2019"], acc: ["2025"] },
  { id: "co33-f4", d: 1, t: "Quel nombre donne son nom à l'expédition du jeu ?", a: "33", x: ["100", "7", "50"], acc: ["33", "trente-trois"] },
  { id: "co33-f5", d: 1, t: "Quelle entité colossale menace l'humanité en peignant un nombre chaque année ?", a: "La Peintresse", x: ["La Sorcière", "La Faucheuse", "La Reine"], acc: ["peintresse", "la peintresse", "paintress"] },
  // --- Moyennes (10) ---
  { id: "co33-m1", d: 2, t: "Comment se nomme le phénomène qui efface tous ceux ayant l'âge peint par la Peintresse ?", a: "Le Gommage", x: ["Le Déluge", "L'Oubli", "La Purge"], acc: ["gommage", "le gommage"] },
  { id: "co33-m2", d: 2, t: "Comment évolue le nombre peint par la Peintresse au fil des années ?", a: "Il diminue", x: ["Il augmente", "Il reste fixe", "Il double"], acc: ["il diminue", "diminue", "il baisse", "decroit"] },
  { id: "co33-m3", d: 2, t: "Quel ingénieur au bras mécanique est l'un des héros de l'expédition ?", a: "Gustave", x: ["Verso", "Monoco", "Renoir"], acc: ["gustave"] },
  { id: "co33-m4", d: 2, t: "Comment se nomme la jeune fille protégée par Gustave ?", a: "Maelle", x: ["Lune", "Sciel", "Alicia"], acc: ["maelle", "maëlle"] },
  { id: "co33-m5", d: 2, t: "Comment s'appelle la cité dont partent les expéditions ?", a: "Lumière", x: ["Clair-de-Lune", "Belleville", "Aurore"], acc: ["lumiere", "lumière"] },
  { id: "co33-m6", d: 2, t: "Quel éditeur a publié Clair Obscur: Expédition 33 ?", a: "Kepler Interactive", x: ["Electronic Arts", "Ubisoft", "Square Enix"], acc: ["kepler", "kepler interactive"] },
  { id: "co33-m7", d: 2, t: "Quelle époque française inspire l'univers visuel du jeu ?", a: "La Belle Époque", x: ["Le Moyen Âge", "La Renaissance", "Les années folles"], acc: ["belle epoque", "belle époque"] },
  { id: "co33-m8", d: 2, t: "Quel est le but de l'Expédition 33 ?", a: "Détruire la Peintresse", x: ["Coloniser une île", "Retrouver un trésor", "Fonder une cité"], acc: ["detruire la peintresse", "tuer la peintresse", "arreter la peintresse"] },
  { id: "co33-m9", d: 2, t: "Sur quel moteur graphique Clair Obscur: Expédition 33 a-t-il été développé ?", a: "L'Unreal Engine 5", x: ["Le Unity", "Le CryEngine", "Le Frostbite"], acc: ["unreal engine 5", "unreal", "ue5"] },
  { id: "co33-m10", d: 2, t: "En quoi les habitants effacés par le Gommage se dissipent-ils ?", a: "En pétales de fleurs", x: ["En cendres", "En statues de pierre", "En cristaux"], acc: ["petales", "pétales", "petales de fleurs"] },
  // --- Dures (15) ---
  { id: "co33-d1", d: 3, t: "Dans quelle ville française est installé le studio Sandfall Interactive ?", a: "Montpellier", x: ["Paris", "Lyon", "Bordeaux"], acc: ["montpellier"] },
  { id: "co33-d2", d: 3, t: "Qui est le directeur créatif à l'origine du jeu ?", a: "Guillaume Broche", x: ["David Cage", "Michel Ancel", "Éric Chahi"], acc: ["guillaume broche", "broche"] },
  { id: "co33-d3", d: 3, t: "Quelle érudite de l'équipe manie des pouvoirs élémentaires ?", a: "Lune", x: ["Maelle", "Sciel", "Alicia"], acc: ["lune"] },
  { id: "co33-d4", d: 3, t: "Quelle combattante de l'expédition manie une faux et des cartes ?", a: "Sciel", x: ["Lune", "Maelle", "Alicia"], acc: ["sciel"] },
  { id: "co33-d5", d: 3, t: "Comment se nomme l'expéditionnaire mystérieux que le groupe rencontre en chemin ?", a: "Verso", x: ["Monoco", "Renoir", "Gustave"], acc: ["verso"] },
  { id: "co33-d6", d: 3, t: "Comment appelle-t-on le petit peuple de créatures dont fait partie Monoco ?", a: "Les Gestrals", x: ["Les Nevrons", "Les Gnomes", "Les Lutins"], acc: ["gestrals", "gestraux", "gestral"] },
  { id: "co33-d7", d: 3, t: "Quelle grande créature volante aide le groupe à voyager sur la carte ?", a: "Esquie", x: ["Monoco", "Renoir", "Verso"], acc: ["esquie"] },
  { id: "co33-d8", d: 3, t: "Comment appelle-t-on les monstres qui peuplent le monde et que l'expédition affronte ?", a: "Les Nevrons", x: ["Les Gestrals", "Les Ombres", "Les Spectres"], acc: ["nevrons", "les nevrons"] },
  { id: "co33-d9", d: 3, t: "Quels objets, une fois équipés, confèrent des bonus et peuvent devenir des Lumina ?", a: "Les Pictos", x: ["Les Reliques", "Les Runes", "Les Gemmes"], acc: ["pictos", "les pictos", "picto"] },
  { id: "co33-d10", d: 3, t: "Comment se nomme l'homme en noir, figure inquiétante croisée par l'expédition ?", a: "Renoir", x: ["Verso", "Monoco", "Gustave"], acc: ["renoir"] },
  { id: "co33-d11", d: 3, t: "Quelle mécanique défensive, empruntée aux jeux d'action, permet d'éviter les attaques ennemies ?", a: "L'esquive et la parade", x: ["La couverture", "Le blocage passif", "La régénération"], acc: ["esquive", "parade", "esquive et parade"] },
  { id: "co33-d12", d: 3, t: "Sur quel support la Peintresse inscrit-elle son nombre fatidique ?", a: "Un monolithe", x: ["Un vitrail", "Une fresque", "Un parchemin"], acc: ["monolithe", "un monolithe"] },
  { id: "co33-d13", d: 3, t: "Quel compositeur a signé la bande originale du jeu ?", a: "Lorien Testard", x: ["Yoko Shimomura", "Nobuo Uematsu", "Austin Wintory"], acc: ["lorien testard", "testard"] },
  { id: "co33-d14", d: 3, t: "Combien de personnages peuvent composer l'équipe active en combat ?", a: "Trois", x: ["Deux", "Cinq", "Six"], acc: ["3", "trois"] },
  { id: "co33-d15", d: 3, t: "Quelle arme à distance les personnages peuvent-ils utiliser en visant librement en combat ?", a: "Une arme à feu", x: ["Un arc", "Une fronde", "Une arbalète"], acc: ["arme a feu", "arme à feu", "pistolet", "fusil"] },
  // --- Pro (20) ---
  { id: "co33-p1", d: 4, t: "Quelle chanteuse interprète les voix de la bande originale de Lorien Testard ?", a: "Alice Duport-Percier", x: ["Emma Peters", "Pomme", "Clara Luciani"], acc: ["alice duport-percier", "duport-percier"] },
  { id: "co33-p2", d: 4, t: "Quel acteur, connu pour Daredevil, prête sa voix à Gustave en version anglaise ?", a: "Charlie Cox", x: ["Ben Starr", "Andy Serkis", "Troy Baker"], acc: ["charlie cox", "cox"] },
  { id: "co33-p3", d: 4, t: "Quel acteur célèbre pour Gollum incarne Renoir en version anglaise ?", a: "Andy Serkis", x: ["Charlie Cox", "Ben Starr", "Doug Cockle"], acc: ["andy serkis", "serkis"] },
  { id: "co33-p4", d: 4, t: "Quel acteur, voix de Clive dans Final Fantasy XVI, incarne Verso ?", a: "Ben Starr", x: ["Charlie Cox", "Andy Serkis", "Troy Baker"], acc: ["ben starr", "starr"] },
  { id: "co33-p5", d: 4, t: "Quelle actrice prête sa voix à Maelle en version anglaise ?", a: "Jennifer English", x: ["Kirsty Rider", "Shala Nyx", "Jane Perry"], acc: ["jennifer english", "english"] },
  { id: "co33-p6", d: 4, t: "Quelle ressource, gagnée en attaquant, permet de lancer les compétences en combat ?", a: "Les points d'action", x: ["Les points de vie", "L'or", "L'expérience"], acc: ["points d'action", "pa", "action points"] },
  { id: "co33-p7", d: 4, t: "Quel vaste territoire l'expédition doit-elle traverser pour atteindre la Peintresse ?", a: "Le Continent", x: ["L'Archipel", "La Vallée", "Le Désert"], acc: ["continent", "le continent"] },
  { id: "co33-p8", d: 4, t: "Comment appelle-t-on les compétences passives obtenues en équipant assez de Pictos ?", a: "Les Lumina", x: ["Les Auras", "Les Sceaux", "Les Glyphes"], acc: ["lumina", "les lumina", "luminas"] },
  { id: "co33-p9", d: 4, t: "Quel Gestral rejoint l'équipe et se bat en imitant les capacités des monstres ?", a: "Monoco", x: ["Verso", "Esquie", "Renoir"], acc: ["monoco"] },
  { id: "co33-p10", d: 4, t: "Quelle est la particularité du bras droit de Gustave ?", a: "C'est une prothèse mécanique", x: ["Il est tatoué de runes", "Il est fait de cristal", "Il est immortel"], acc: ["prothese mecanique", "prothèse", "bras mecanique"] },
  { id: "co33-p11", d: 4, t: "Sur quelles plateformes Clair Obscur: Expédition 33 est-il sorti au lancement ?", a: "PC, PS5 et Xbox Series", x: ["Uniquement sur PC", "Uniquement sur Switch", "PS4 et Xbox One"], acc: ["pc ps5 xbox", "pc, ps5 et xbox series", "pc ps5 et xbox series"] },
  { id: "co33-p12", d: 4, t: "Dès son lancement, sur quel service par abonnement le jeu était-il disponible ?", a: "Le Xbox Game Pass", x: ["Le PlayStation Plus", "Le EA Play", "Le Ubisoft+"], acc: ["game pass", "xbox game pass"] },
  { id: "co33-p13", d: 4, t: "Quelle grande récompense annuelle du jeu vidéo Clair Obscur visait-il en 2025 ?", a: "Le titre de jeu de l'année", x: ["Le prix du meilleur jeu de sport", "Le prix du meilleur jeu mobile", "Le prix de la meilleure adaptation"], acc: ["jeu de l'annee", "goty", "game of the year"] },
  { id: "co33-p14", d: 4, t: "À quel rythme survient un nouveau Gommage dans le récit ?", a: "Chaque année", x: ["Chaque mois", "Tous les dix ans", "Chaque siècle"], acc: ["chaque annee", "un an", "annuel"] },
  { id: "co33-p15", d: 4, t: "Quel âge auront ceux qui disparaîtront lors du Gommage au début du jeu ?", a: "33 ans", x: ["18 ans", "50 ans", "7 ans"], acc: ["33", "33 ans", "trente-trois ans"] },
  { id: "co33-p16", d: 4, t: "Dans quelle langue sont majoritairement chantées les chansons de la bande originale ?", a: "En français", x: ["En anglais", "En latin", "En italien"], acc: ["francais", "français", "en francais"] },
  { id: "co33-p17", d: 4, t: "De quel pays est originaire la majorité de l'équipe de Sandfall Interactive ?", a: "La France", x: ["La Belgique", "Le Canada", "La Suisse"], acc: ["france", "la france"] },
  { id: "co33-p18", d: 4, t: "Quelle technique picturale de contraste entre ombre et lumière donne son nom au jeu ?", a: "Le clair-obscur", x: ["Le cubisme", "Le pointillisme", "Le fauvisme"], acc: ["clair-obscur", "clair obscur"] },
  { id: "co33-p19", d: 4, t: "Comment nomme-t-on chaque groupe qui part tenter de vaincre la Peintresse ?", a: "Une expédition", x: ["Une croisade", "Une légion", "Une caravane"], acc: ["expedition", "une expedition", "expédition"] },
  { id: "co33-p20", d: 4, t: "Clair Obscur: Expédition 33 est le tout premier jeu de quel studio ?", a: "Sandfall Interactive", x: ["Kepler Interactive", "Dontnod", "Asobo Studio"], acc: ["sandfall", "sandfall interactive"] },
]);
