import { universe } from "../_build";

export const cod = universe("jeuxvideo", "Call of Duty", [
  // --- Faciles (5) ---
  { id: "cod-f1", d: 1, t: "À quel genre appartient Call of Duty ?", a: "Le jeu de tir à la première personne", x: ["La course", "La gestion", "Le jeu de rôle"], acc: ["fps", "jeu de tir", "tir a la premiere personne", "shooter"] },
  { id: "cod-f2", d: 1, t: "Quel éditeur publie la série Call of Duty ?", a: "Activision", x: ["EA", "Ubisoft", "Sega"], acc: ["activision"] },
  { id: "cod-f3", d: 1, t: "Sur quel contexte reposent la plupart des jeux Call of Duty ?", a: "La guerre", x: ["Le sport", "La magie", "La cuisine"], acc: ["guerre", "la guerre"] },
  { id: "cod-f4", d: 1, t: "Quel mode coopératif oppose les joueurs à des vagues de morts-vivants ?", a: "Le mode Zombies", x: ["Le mode Ferme", "Le mode Course", "Le mode Danse"], acc: ["zombies", "mode zombies"] },
  { id: "cod-f5", d: 1, t: "Comment s'appelle le mode Battle Royale gratuit de Call of Duty ?", a: "Warzone", x: ["Blackout", "Fortnite", "Apex"], acc: ["warzone"] },
  // --- Moyennes (10) ---
  { id: "cod-m1", d: 2, t: "En quelle année le premier Call of Duty est-il sorti ?", a: "2003", x: ["1998", "2007", "2012"], acc: ["2003"] },
  { id: "cod-m2", d: 2, t: "Quel opus de 2007 a modernisé la série et l'a propulsée ?", a: "Modern Warfare", x: ["World at War", "Black Ops", "Ghosts"], acc: ["modern warfare", "call of duty 4"] },
  { id: "cod-m3", d: 2, t: "Comment s'appelle le capitaine à la moustache emblématique de Modern Warfare ?", a: "Le capitaine Price", x: ["Soap", "Ghost", "Makarov"], acc: ["price", "capitaine price", "captain price"] },
  { id: "cod-m4", d: 2, t: "Comment s'appelle le soldat masqué au crâne, personnage culte de la série ?", a: "Ghost", x: ["Price", "Soap", "Roach"], acc: ["ghost", "simon ghost riley"] },
  { id: "cod-m5", d: 2, t: "Quel studio a créé le premier Modern Warfare ?", a: "Infinity Ward", x: ["Treyarch", "Sledgehammer", "Rockstar"], acc: ["infinity ward"] },
  { id: "cod-m6", d: 2, t: "Comment s'appelle la sous-série de Treyarch, entre complots et guerre froide ?", a: "Black Ops", x: ["Modern Warfare", "Ghosts", "Vanguard"], acc: ["black ops"] },
  { id: "cod-m7", d: 2, t: "Comment appelle-t-on les récompenses obtenues en enchaînant les éliminations ?", a: "Les killstreaks", x: ["Les combos", "Les quêtes", "Les buffs"], acc: ["killstreaks", "killstreak", "series d'eliminations"] },
  { id: "cod-m8", d: 2, t: "À quelle fréquence un nouveau Call of Duty sort-il généralement ?", a: "Chaque année", x: ["Tous les 5 ans", "Tous les 10 ans", "Une seule fois"], acc: ["chaque annee", "tous les ans", "annuel"] },
  { id: "cod-m9", d: 2, t: "Comment s'appelle la petite carte culte de Black Ops, symétrique, aux mannequins ?", a: "Nuketown", x: ["Rust", "Shipment", "Dust"], acc: ["nuketown"] },
  { id: "cod-m10", d: 2, t: "En quelle année le Battle Royale Warzone est-il sorti ?", a: "2020", x: ["2015", "2018", "2023"], acc: ["2020"] },
  // --- Dures (15) ---
  { id: "cod-d1", d: 3, t: "Comment s'appelle le fidèle acolyte écossais de Price, à la crête ?", a: "Soap MacTavish", x: ["Ghost", "Roach", "Gaz"], acc: ["soap", "soap mactavish"] },
  { id: "cod-d2", d: 3, t: "Comment s'appelle le principal antagoniste russe de la série Modern Warfare ?", a: "Makarov", x: ["Zakhaev", "Shepherd", "Menendez"], acc: ["makarov"] },
  { id: "cod-d3", d: 3, t: "Comment s'appelle l'unité d'élite de Price et Soap ?", a: "La Task Force 141", x: ["Les Navy SEALs", "La Delta Force", "Le SAS"], acc: ["task force 141", "141"] },
  { id: "cod-d4", d: 3, t: "Quels trois studios développent la série en alternance ?", a: "Infinity Ward, Treyarch et Sledgehammer", x: ["Rockstar, Ubisoft et EA", "Valve, Bungie et id", "Capcom, Sega et Konami"], acc: ["infinity ward treyarch sledgehammer", "infinity ward treyarch et sledgehammer"] },
  { id: "cod-d5", d: 3, t: "Dans quel opus de 2008 le mode Zombies est-il apparu pour la première fois ?", a: "World at War", x: ["Modern Warfare", "Black Ops", "Ghosts"], acc: ["world at war"] },
  { id: "cod-d6", d: 3, t: "Comment s'appelle le mini-jeu de Warzone où l'on se bat en 1 contre 1 pour revenir ?", a: "Le Goulag", x: ["Le Ring", "L'Arène", "La Cage"], acc: ["goulag", "le goulag", "gulag"] },
  { id: "cod-d7", d: 3, t: "Comment s'appelle la machine des Zombies qui améliore les armes ?", a: "Le Pack-a-Punch", x: ["La Mystery Box", "Le Perk-a-Cola", "Le Wonder-Fizz"], acc: ["pack-a-punch", "pack a punch"] },
  { id: "cod-d8", d: 3, t: "Comment s'appelle la boîte mystère qui donne une arme au hasard en mode Zombies ?", a: "La Mystery Box", x: ["Le Pack-a-Punch", "Le coffre-fort", "La caisse d'armes"], acc: ["mystery box", "boite mysterieuse"] },
  { id: "cod-d9", d: 3, t: "Comment s'appelle la première grande carte de Warzone, une ville fictive ?", a: "Verdansk", x: ["Al Mazrah", "Caldera", "Rebirth Island"], acc: ["verdansk"] },
  { id: "cod-d10", d: 3, t: "Quel killstreak ultime met fin à la partie dans le multijoueur ?", a: "La bombe nucléaire tactique", x: ["Le drone espion", "Le colis de ravitaillement", "L'hélicoptère"], acc: ["bombe nucleaire", "nuke", "bombe nucleaire tactique"] },
  { id: "cod-d11", d: 3, t: "Comment s'appelle le système qui remet la progression à zéro contre un badge ?", a: "Le Prestige", x: ["Le Rang", "Le Season Pass", "Le Ladder"], acc: ["prestige", "le prestige"] },
  { id: "cod-d12", d: 3, t: "Quel killstreak léger révèle la position des ennemis sur la carte ?", a: "L'UAV", x: ["Le colis", "La tourelle", "Le chien"], acc: ["uav", "l'uav", "drone espion"] },
  { id: "cod-d13", d: 3, t: "Comment s'appelle le chien fidèle du jeu Call of Duty: Ghosts ?", a: "Riley", x: ["Rex", "Buddy", "Max"], acc: ["riley"] },
  { id: "cod-d14", d: 3, t: "Quel opus controversé de 2009 contient la mission « No Russian » dans un aéroport ?", a: "Modern Warfare 2", x: ["Black Ops", "World at War", "Ghosts"], acc: ["modern warfare 2", "mw2"] },
  { id: "cod-d15", d: 3, t: "Comment s'appelle le studio créé en 2009 qui a développé Advanced Warfare ?", a: "Sledgehammer Games", x: ["Infinity Ward", "Treyarch", "Raven"], acc: ["sledgehammer", "sledgehammer games"] },
  // --- Pro (20) ---
  { id: "cod-p1", d: 4, t: "Quel acteur oscarisé incarne le méchant de Call of Duty: Advanced Warfare ?", a: "Kevin Spacey", x: ["Kevin Costner", "Gary Oldman", "Idris Elba"], acc: ["kevin spacey", "spacey"] },
  { id: "cod-p2", d: 4, t: "Quelle réplique-mème provient d'une scène d'hommage d'Advanced Warfare ?", a: "Press F to pay respects", x: ["Get to the chopper", "Stay frosty", "Charlie Mike"], acc: ["press f to pay respects", "press f", "f to pay respects"] },
  { id: "cod-p3", d: 4, t: "Comment s'appelle le reboot de Modern Warfare sorti en 2019 ?", a: "Modern Warfare", x: ["Modern Warfare 2", "Warzone", "Black Ops"], acc: ["modern warfare 2019", "modern warfare", "mw 2019"] },
  { id: "cod-p4", d: 4, t: "Comment s'appelle l'opus Black Ops de 2020, sur fond de guerre froide ?", a: "Black Ops Cold War", x: ["Black Ops 4", "Black Ops 6", "Cold War Zombies"], acc: ["black ops cold war", "cold war"] },
  { id: "cod-p5", d: 4, t: "Quel opus Black Ops est sorti en 2024 ?", a: "Black Ops 6", x: ["Black Ops 4", "Black Ops 5", "Black Ops 7"], acc: ["black ops 6", "bo6"] },
  { id: "cod-p6", d: 4, t: "Comment s'appelle le méchant charismatique de Black Ops 2 ?", a: "Raul Menendez", x: ["Makarov", "Zakhaev", "Shepherd"], acc: ["menendez", "raul menendez"] },
  { id: "cod-p7", d: 4, t: "Comment s'appelle la deuxième grande carte de Warzone, en plein désert ?", a: "Al Mazrah", x: ["Verdansk", "Caldera", "Nuketown"], acc: ["al mazrah"] },
  { id: "cod-p8", d: 4, t: "Comment s'appelle la petite île à cadence rapide de Warzone ?", a: "Rebirth Island", x: ["Caldera", "Verdansk", "Fortune's Keep"], acc: ["rebirth island", "rebirth"] },
  { id: "cod-p9", d: 4, t: "Quel opus voit une partie de l'action se dérouler dans l'espace ?", a: "Infinite Warfare", x: ["Advanced Warfare", "Ghosts", "Vanguard"], acc: ["infinite warfare"] },
  { id: "cod-p10", d: 4, t: "Comment s'appelle le général traître de Modern Warfare 2 ?", a: "Shepherd", x: ["Makarov", "Menendez", "Zakhaev"], acc: ["shepherd", "general shepherd"] },
  { id: "cod-p11", d: 4, t: "Comment s'appelle l'ultranationaliste russe, cible du premier Modern Warfare ?", a: "Zakhaev", x: ["Makarov", "Menendez", "Shepherd"], acc: ["zakhaev"] },
  { id: "cod-p12", d: 4, t: "Comment appelle-t-on les boissons qui donnent des capacités en mode Zombies ?", a: "Les Perk-a-Cola", x: ["Les Wonder Weapons", "Les Pack-a-Punch", "Les Élixirs"], acc: ["perk-a-cola", "perk a cola", "perks"] },
  { id: "cod-p13", d: 4, t: "Comment appelle-t-on les armes surpuissantes et loufoques du mode Zombies ?", a: "Les Wonder Weapons", x: ["Les Perks", "Les Killstreaks", "Les Field Upgrades"], acc: ["wonder weapons", "wonder weapon"] },
  { id: "cod-p14", d: 4, t: "Quel opus de 2017 marque le retour de la série à la Seconde Guerre mondiale ?", a: "Call of Duty: WWII", x: ["Vanguard", "World at War", "Ghosts"], acc: ["wwii", "ww2", "call of duty wwii"] },
  { id: "cod-p15", d: 4, t: "Quel opus de 2021 se déroule aussi durant la Seconde Guerre mondiale ?", a: "Vanguard", x: ["WWII", "World at War", "Cold War"], acc: ["vanguard"] },
  { id: "cod-p16", d: 4, t: "Comment s'appelle la version mobile gratuite de Call of Duty ?", a: "Call of Duty: Mobile", x: ["Call of Duty: Pocket", "Warzone Go", "CoD Lite"], acc: ["cod mobile", "call of duty mobile"] },
  { id: "cod-p17", d: 4, t: "Comment s'appelle la petite carte ultra-rapide, un simple cargo, culte en multijoueur ?", a: "Shipment", x: ["Nuketown", "Rust", "Dust"], acc: ["shipment"] },
  { id: "cod-p18", d: 4, t: "Comment s'appelle la carte-arène de duel de Modern Warfare 2, en plein désert ?", a: "Rust", x: ["Shipment", "Nuketown", "Terminal"], acc: ["rust"] },
  { id: "cod-p19", d: 4, t: "Comment s'appelle le mode où deux équipes se disputent des points A, B et C ?", a: "Domination", x: ["Match à mort", "Recherche et destruction", "Capture du drapeau"], acc: ["domination"] },
  { id: "cod-p20", d: 4, t: "Comment s'appelle le mode tactique sans réapparition, avec pose de bombe ?", a: "Recherche et destruction", x: ["Domination", "Match à mort par équipe", "Point stratégique"], acc: ["recherche et destruction", "search and destroy", "s&d"] },
]);
