import { universe } from "../_build";

export const devilmaycry = universe("jeuxvideo", "Devil May Cry", [
  // --- Faciles (5) ---
  { id: "dmc-f1", d: 1, t: "Quel studio japonais a créé la série Devil May Cry ?", a: "Capcom", x: ["Konami", "Sega", "Square Enix"], acc: ["capcom"] },
  { id: "dmc-f2", d: 1, t: "Comment s'appelle le chasseur de démons aux cheveux blancs, héros de la série ?", a: "Dante", x: ["Nero", "Vergil", "Sparda"], acc: ["dante"] },
  { id: "dmc-f3", d: 1, t: "Que chasse principalement Dante dans Devil May Cry ?", a: "Des démons", x: ["Des zombies", "Des extraterrestres", "Des pirates"], acc: ["demons", "des demons"] },
  { id: "dmc-f4", d: 1, t: "À quel genre appartient Devil May Cry ?", a: "L'action-aventure", x: ["La course", "La gestion", "Le jeu de rythme"], acc: ["action", "action-aventure", "beat them all"] },
  { id: "dmc-f5", d: 1, t: "Quel type d'armes Dante utilise-t-il, en plus de son épée ?", a: "Deux pistolets", x: ["Un arc", "Une lance", "Un fouet"], acc: ["deux pistolets", "pistolets"] },
  // --- Moyennes (10) ---
  { id: "dmc-m1", d: 2, t: "Comment s'appelle le frère jumeau de Dante ?", a: "Vergil", x: ["Nero", "Sparda", "Mundus"], acc: ["vergil"] },
  { id: "dmc-m2", d: 2, t: "Comment s'appelle la boutique de chasse aux démons tenue par Dante ?", a: "Devil May Cry", x: ["Demon Hunter", "Sparda Shop", "Rebellion"], acc: ["devil may cry"] },
  { id: "dmc-m3", d: 2, t: "Comment se nomme le père démon légendaire de Dante et Vergil ?", a: "Sparda", x: ["Mundus", "Urizen", "Nero"], acc: ["sparda"] },
  { id: "dmc-m4", d: 2, t: "En quelle année est sorti le premier Devil May Cry ?", a: "2001", x: ["1997", "2005", "2010"], acc: ["2001"] },
  { id: "dmc-m5", d: 2, t: "Sur quelle console est d'abord sorti le premier Devil May Cry ?", a: "La PlayStation 2", x: ["La PlayStation 1", "La Xbox", "La GameCube"], acc: ["ps2", "playstation 2"] },
  { id: "dmc-m6", d: 2, t: "Comment s'appelle la grande épée emblématique de Dante ?", a: "Rebellion", x: ["Yamato", "Red Queen", "Force Edge"], acc: ["rebellion"] },
  { id: "dmc-m7", d: 2, t: "Comment s'appellent les deux pistolets fétiches de Dante ?", a: "Ebony et Ivory", x: ["Blue Rose", "Kalina Ann", "Coyote"], acc: ["ebony et ivory", "ebony and ivory"] },
  { id: "dmc-m8", d: 2, t: "Comment s'appelle le jeune chasseur au bras démoniaque, héros de Devil May Cry 4 ?", a: "Nero", x: ["Dante", "Vergil", "V"], acc: ["nero"] },
  { id: "dmc-m9", d: 2, t: "Quelle transformation rend les personnages plus puissants en démon ?", a: "Le Devil Trigger", x: ["Le Super Saiyan", "Le Bankai", "Le Berserk"], acc: ["devil trigger"] },
  { id: "dmc-m10", d: 2, t: "De quelle nature est Dante, mi-humain et mi-quoi ?", a: "Mi-démon", x: ["Mi-ange", "Mi-robot", "Mi-vampire"], acc: ["demon", "mi-demon", "demi-demon"] },
  // --- Dures (15) ---
  { id: "dmc-d1", d: 3, t: "Comment s'appelle le katana de Vergil ?", a: "Yamato", x: ["Rebellion", "Red Queen", "Ebony"], acc: ["yamato"] },
  { id: "dmc-d2", d: 3, t: "Quel réalisateur japonais a dirigé le tout premier Devil May Cry ?", a: "Hideki Kamiya", x: ["Hideo Kojima", "Shinji Mikami", "Hidetaka Miyazaki"], acc: ["hideki kamiya", "kamiya"] },
  { id: "dmc-d3", d: 3, t: "De quel autre jeu de Capcom Devil May Cry est-il issu à l'origine ?", a: "Resident Evil", x: ["Street Fighter", "Mega Man", "Monster Hunter"], acc: ["resident evil"] },
  { id: "dmc-d4", d: 3, t: "Comment s'appelle la chasseuse de démons humaine armée d'un lance-roquettes ?", a: "Lady", x: ["Trish", "Nico", "Kyrie"], acc: ["lady", "mary"] },
  { id: "dmc-d5", d: 3, t: "Comment s'appelle la démone qui ressemble à la mère de Dante et devient son alliée ?", a: "Trish", x: ["Lady", "Nico", "Eva"], acc: ["trish"] },
  { id: "dmc-d6", d: 3, t: "Comment s'appelle l'empereur démon, grand méchant du premier jeu ?", a: "Mundus", x: ["Sparda", "Urizen", "Vergil"], acc: ["mundus"] },
  { id: "dmc-d7", d: 3, t: "Quel épisode de 2005, préquelle, raconte la jeunesse de Dante ?", a: "Devil May Cry 3", x: ["Devil May Cry 2", "Devil May Cry 4", "DmC"], acc: ["devil may cry 3", "dmc3", "dante's awakening"] },
  { id: "dmc-d8", d: 3, t: "Comment s'appelle l'épée-tronçonneuse de Nero ?", a: "Red Queen", x: ["Rebellion", "Yamato", "Blue Rose"], acc: ["red queen"] },
  { id: "dmc-d9", d: 3, t: "Comment s'appelle le revolver de Nero ?", a: "Blue Rose", x: ["Ebony", "Ivory", "Coyote"], acc: ["blue rose"] },
  { id: "dmc-d10", d: 3, t: "Comment s'appelle la mère humaine de Dante et Vergil ?", a: "Eva", x: ["Trish", "Lady", "Kyrie"], acc: ["eva"] },
  { id: "dmc-d11", d: 3, t: "Quel studio britannique a développé le reboot DmC en 2013 ?", a: "Ninja Theory", x: ["Platinum Games", "FromSoftware", "Rocksteady"], acc: ["ninja theory"] },
  { id: "dmc-d12", d: 3, t: "Comment s'appelle la grande tour qui surgit dans Devil May Cry 3 ?", a: "Temen-ni-gru", x: ["Fortuna", "Redgrave", "Mallet Island"], acc: ["temen-ni-gru", "temen ni gru"] },
  { id: "dmc-d13", d: 3, t: "Comment s'appelle l'organisation religieuse qui vénère Sparda dans Devil May Cry 4 ?", a: "L'Ordre de l'Épée", x: ["La Main Rouge", "Le Cercle Noir", "La Garde Démoniaque"], acc: ["ordre de l'epee", "order of the sword", "ordre de l'épée"] },
  { id: "dmc-d14", d: 3, t: "Comment s'appelle la jeune femme aimée de Nero dans Devil May Cry 4 ?", a: "Kyrie", x: ["Lady", "Trish", "Nico"], acc: ["kyrie"] },
  { id: "dmc-d15", d: 3, t: "Quelle réplique culte Dante lance-t-il souvent en tirant ?", a: "Jackpot", x: ["Bingo", "Game over", "Gagné"], acc: ["jackpot"] },
  // --- Pro (20) ---
  { id: "dmc-p1", d: 4, t: "En quelle année est sorti Devil May Cry 5 ?", a: "2019", x: ["2013", "2015", "2021"], acc: ["2019"] },
  { id: "dmc-p2", d: 4, t: "Comment s'appelle la mécanicienne qui fabrique les bras de Nero dans Devil May Cry 5 ?", a: "Nico", x: ["Lady", "Trish", "Kyrie"], acc: ["nico"] },
  { id: "dmc-p3", d: 4, t: "Comment s'appelle le mystérieux personnage frêle désigné par une seule lettre dans Devil May Cry 5 ?", a: "V", x: ["J", "Z", "Nero"], acc: ["v"] },
  { id: "dmc-p4", d: 4, t: "De qui V est-il en réalité la moitié humaine dans Devil May Cry 5 ?", a: "Vergil", x: ["Dante", "Sparda", "Mundus"], acc: ["vergil"] },
  { id: "dmc-p5", d: 4, t: "Comment s'appelle le grand méchant de Devil May Cry 5, moitié démon de Vergil ?", a: "Urizen", x: ["Mundus", "Sparda", "Sanctus"], acc: ["urizen"] },
  { id: "dmc-p6", d: 4, t: "De qui Nero est-il révélé être le fils ?", a: "Vergil", x: ["Dante", "Sparda", "Mundus"], acc: ["vergil"] },
  { id: "dmc-p7", d: 4, t: "Comment s'appelle le lance-roquettes de Lady, nommé d'après sa mère ?", a: "Kalina Ann", x: ["Blue Rose", "Coyote-A", "Pandora"], acc: ["kalina ann"] },
  { id: "dmc-p8", d: 4, t: "Comment appelle-t-on les bras interchangeables de Nero dans Devil May Cry 5 ?", a: "Les Devil Breakers", x: ["Les Devil Arms", "Les Devil Bringers", "Les Devil Triggers"], acc: ["devil breakers", "devil breaker"] },
  { id: "dmc-p9", d: 4, t: "Quel système de notation récompense le style au combat, jusqu'au rang SSS ?", a: "Le rang de style", x: ["Le combo-mètre", "La barre de vie", "Le score de vitesse"], acc: ["rang de style", "style ranking", "style"] },
  { id: "dmc-p10", d: 4, t: "Que crie l'écran quand on atteint le meilleur rang de style ?", a: "Stylish", x: ["Perfect", "Combo", "Victory"], acc: ["stylish", "sss"] },
  { id: "dmc-p11", d: 4, t: "Dans quelle ville se déroule Devil May Cry 5 ?", a: "Redgrave City", x: ["Fortuna", "Raccoon City", "Mallet Island"], acc: ["redgrave city", "redgrave"] },
  { id: "dmc-p12", d: 4, t: "Comment s'appelle le chef de l'Ordre de l'Épée, méchant de Devil May Cry 4 ?", a: "Sanctus", x: ["Mundus", "Urizen", "Credo"], acc: ["sanctus"] },
  { id: "dmc-p13", d: 4, t: "Comment s'appelle le frère de Kyrie, chevalier de l'Ordre dans Devil May Cry 4 ?", a: "Credo", x: ["Sanctus", "Agnus", "Nero"], acc: ["credo"] },
  { id: "dmc-p14", d: 4, t: "Comment appelait-on le bras démoniaque de Nero avant qu'il ne soit arraché ?", a: "Le Devil Bringer", x: ["Le Devil Breaker", "Le Devil Trigger", "La Red Queen"], acc: ["devil bringer"] },
  { id: "dmc-p15", d: 4, t: "Comment s'appelle l'épée héritée de Sparda, aussi appelée Force Edge ?", a: "Sparda", x: ["Rebellion", "Yamato", "Red Queen"], acc: ["sparda", "force edge"] },
  { id: "dmc-p16", d: 4, t: "Quel chien démon géant devient une arme de glace dans Devil May Cry 3 ?", a: "Cerberus", x: ["Nevan", "Agni", "Beowulf"], acc: ["cerberus", "cerbère"] },
  { id: "dmc-p17", d: 4, t: "Comment s'appelle l'arme guitare-faux obtenue d'une démone dans Devil May Cry 3 ?", a: "Nevan", x: ["Cerberus", "Beowulf", "Nightmare"], acc: ["nevan"] },
  { id: "dmc-p18", d: 4, t: "Quelle plateforme a diffusé la série animée Devil May Cry en 2025 ?", a: "Netflix", x: ["Crunchyroll", "Disney+", "Hulu"], acc: ["netflix"] },
  { id: "dmc-p19", d: 4, t: "Quel producteur est à l'origine de la série animée Devil May Cry de 2025 ?", a: "Adi Shankar", x: ["Hideki Kamiya", "Hideo Kojima", "Shinji Mikami"], acc: ["adi shankar", "shankar"] },
  { id: "dmc-p20", d: 4, t: "Comment s'appelle l'artisane qui a forgé les pistolets Ebony et Ivory de Dante ?", a: "Nell Goldstein", x: ["Nico", "Lady", "Trish"], acc: ["nell goldstein", "goldstein"] },
]);
