import { universe } from "../_build";

export const eldenring = universe("jeuxvideo", "Elden Ring", [
  // --- Faciles (5) ---
  { id: "elden-f1", d: 1, t: "Quel studio a développé Elden Ring ?", a: "FromSoftware", x: ["Ubisoft", "Rockstar", "Capcom"], acc: ["fromsoftware", "from software"] },
  { id: "elden-f2", d: 1, t: "À quel genre appartient Elden Ring ?", a: "Le jeu de rôle action", x: ["La course", "Le jeu de rythme", "Le puzzle"], acc: ["rpg", "jeu de role action", "action rpg", "soulslike"] },
  { id: "elden-f3", d: 1, t: "En quelle année est sorti Elden Ring ?", a: "2022", x: ["2018", "2020", "2024"], acc: ["2022"] },
  { id: "elden-f4", d: 1, t: "Quel arbre gigantesque et lumineux domine le monde d'Elden Ring ?", a: "L'Arbre-Monde", x: ["Le Chêne noir", "L'Arbre de vie", "Le Grand Saule"], acc: ["arbre-monde", "arbre monde", "erdtree", "arbre d'or"] },
  { id: "elden-f5", d: 1, t: "Quel célèbre auteur de Game of Thrones a participé à l'univers d'Elden Ring ?", a: "George R. R. Martin", x: ["J. R. R. Tolkien", "Stephen King", "J. K. Rowling"], acc: ["george martin", "george r r martin", "grrm", "martin"] },
  // --- Moyennes (10) ---
  { id: "elden-m1", d: 2, t: "Comment appelle-t-on le personnage incarné par le joueur ?", a: "Le Sans-éclat", x: ["Le Chevalier noir", "L'Élu", "Le Cendreux"], acc: ["sans-eclat", "sans eclat", "tarnished"] },
  { id: "elden-m2", d: 2, t: "Quel titre le héros cherche-t-il à obtenir en réunissant l'Anneau ?", a: "Seigneur d'Elden", x: ["Roi des cendres", "Empereur", "Grand Sorcier"], acc: ["seigneur d'elden", "elden lord", "seigneur"] },
  { id: "elden-m3", d: 2, t: "Comment se nomme la vaste contrée où se déroule le jeu ?", a: "L'Entre-terre", x: ["Lordran", "Yharnam", "Boletaria"], acc: ["entre-terre", "lands between", "l'entre-terre"] },
  { id: "elden-m4", d: 2, t: "Qui a réalisé Elden Ring chez FromSoftware ?", a: "Hidetaka Miyazaki", x: ["Hideo Kojima", "Shigeru Miyamoto", "Fumito Ueda"], acc: ["miyazaki", "hidetaka miyazaki"] },
  { id: "elden-m5", d: 2, t: "Comment s'appelle la monture spectrale du héros ?", a: "Torrent", x: ["Épona", "Roach", "Agro"], acc: ["torrent"] },
  { id: "elden-m6", d: 2, t: "À quoi servent les runes récoltées sur les ennemis ?", a: "De monnaie et d'expérience", x: ["À ouvrir les portes", "À cuisiner", "À voler"], acc: ["monnaie et experience", "runes", "monnaie", "experience"] },
  { id: "elden-m7", d: 2, t: "Comment s'appellent les points de sauvegarde et de repos du jeu ?", a: "Les sites de grâce", x: ["Les feux de camp", "Les autels", "Les fontaines"], acc: ["sites de grace", "grace", "site de grace"] },
  { id: "elden-m8", d: 2, t: "Quelle guerrière redoutable est surnommée « la Lame de Miquella » ?", a: "Malenia", x: ["Ranni", "Rennala", "Marika"], acc: ["malenia"] },
  { id: "elden-m9", d: 2, t: "Quel éditeur a publié Elden Ring ?", a: "Bandai Namco", x: ["Sony", "Electronic Arts", "Activision"], acc: ["bandai namco", "bandai"] },
  { id: "elden-m10", d: 2, t: "Quel grand prix Elden Ring a-t-il remporté en 2022 ?", a: "Le jeu de l'année", x: ["Le meilleur jeu de sport", "Le meilleur jeu mobile", "Le meilleur jeu indépendant"], acc: ["jeu de l'annee", "goty", "game of the year"] },
  // --- Dures (15) ---
  { id: "elden-d1", d: 3, t: "Comment s'appelle la reine à l'origine de l'Anneau, l'Éternelle ?", a: "Marika", x: ["Ranni", "Rennala", "Malenia"], acc: ["marika", "marika l'eternelle"] },
  { id: "elden-d2", d: 3, t: "Comment nomme-t-on l'événement où l'Anneau fut brisé, déclenchant la guerre ?", a: "L'Éclatement", x: ["Le Cataclysme", "La Grande Nuit", "L'Effondrement"], acc: ["eclatement", "l'eclatement", "shattering"] },
  { id: "elden-d3", d: 3, t: "Comment s'appelle la compagne mystérieuse qui guide le héros au début ?", a: "Melina", x: ["Ranni", "Malenia", "Rennala"], acc: ["melina"] },
  { id: "elden-d4", d: 3, t: "Quel demi-dieu greffé de membres garde la première grande forteresse ?", a: "Godrick", x: ["Radahn", "Morgott", "Mohg"], acc: ["godrick", "godrick le greffe"] },
  { id: "elden-d5", d: 3, t: "Quel demi-dieu guerrier, fléau des astres, est affronté à Caelid ?", a: "Radahn", x: ["Godrick", "Morgott", "Mohg"], acc: ["radahn", "starscourge radahn"] },
  { id: "elden-d6", d: 3, t: "Comment s'appelle la sorcière qui propose une fin où elle emmène le héros ?", a: "Ranni", x: ["Melina", "Marika", "Malenia"], acc: ["ranni", "ranni la sorciere"] },
  { id: "elden-d7", d: 3, t: "Quelle région rouge, rongée par une pourriture écarlate, est très hostile ?", a: "Caelid", x: ["Necrolimbe", "Leyndell", "Liurnia"], acc: ["caelid"] },
  { id: "elden-d8", d: 3, t: "Comment s'appelle la région de départ, verdoyante, où commence l'aventure ?", a: "Necrolimbe", x: ["Caelid", "Liurnia", "Leyndell"], acc: ["necrolimbe", "limgrave"] },
  { id: "elden-d9", d: 3, t: "Comment s'appelle la capitale royale coiffée de l'Arbre-Monde ?", a: "Leyndell", x: ["Raya Lucaria", "Stormveil", "Caelid"], acc: ["leyndell"] },
  { id: "elden-d10", d: 3, t: "Comment s'appelle le lieu de rassemblement, sorte de QG entre les zones ?", a: "La Table Ronde", x: ["Le Sanctuaire du Lige", "Le Nexus", "Le Feu de Lige"], acc: ["table ronde", "roundtable", "la table ronde"] },
  { id: "elden-d11", d: 3, t: "Comment s'appelle la reine mage, mère de Ranni, à l'académie de Raya Lucaria ?", a: "Rennala", x: ["Marika", "Malenia", "Melina"], acc: ["rennala"] },
  { id: "elden-d12", d: 3, t: "Quelle fiole soigne le héros, remplie de « larmes carmin » ?", a: "La Fiole de Larmes carmin", x: ["La Gourde d'Estus", "Le Calice de sang", "La Potion verte"], acc: ["larmes carmin", "fiole de larmes carmin", "crimson tears"] },
  { id: "elden-d13", d: 3, t: "Comment s'appelle le roi maudit qui défend la capitale, alias Margit ?", a: "Morgott", x: ["Mohg", "Godrick", "Radahn"], acc: ["morgott", "margit"] },
  { id: "elden-d14", d: 3, t: "Comment s'appelle le seigneur du sang qui règne dans un palais souterrain ?", a: "Mohg", x: ["Morgott", "Godrick", "Radahn"], acc: ["mohg", "mohg seigneur du sang"] },
  { id: "elden-d15", d: 3, t: "Quelle réplique culte Malenia lance-t-elle en apparaissant ?", a: "Je suis Malenia, Lame de Miquella", x: ["Nulle pitié pour toi", "Que le combat commence", "Tu ne passeras pas"], acc: ["je suis malenia", "lame de miquella", "malenia lame de miquella"] },
  // --- Pro (20) ---
  { id: "elden-p1", d: 4, t: "Comment s'appelle le tout premier Seigneur d'Elden, époux de Marika ?", a: "Godfrey", x: ["Radagon", "Morgott", "Godrick"], acc: ["godfrey"] },
  { id: "elden-p2", d: 4, t: "Quelle entité, moitié de Marika, sert de gardien final de l'Anneau ?", a: "Radagon", x: ["Godfrey", "Mohg", "Morgott"], acc: ["radagon"] },
  { id: "elden-p3", d: 4, t: "Quel boss cosmique et doré affronte-t-on tout à la fin du jeu ?", a: "La Bête d'Elden", x: ["Le Dragon ancestral", "Le Nécro-roi", "Le Titan d'or"], acc: ["bete d'elden", "elden beast", "la bete d'elden"] },
  { id: "elden-p4", d: 4, t: "Comment s'appelle l'extension d'Elden Ring sortie en 2024 ?", a: "Shadow of the Erdtree", x: ["Ashes of Ariandel", "The Old Hunters", "Ringed City"], acc: ["shadow of the erdtree", "ombre de l'arbre monde", "erdtree"] },
  { id: "elden-p5", d: 4, t: "Comment s'appelle le principal antagoniste de l'extension de 2024 ?", a: "Messmer", x: ["Radahn", "Mohg", "Godwyn"], acc: ["messmer"] },
  { id: "elden-p6", d: 4, t: "Comment appelle-t-on les esprits que l'on invoque pour combattre à ses côtés ?", a: "Les Cendres d'esprit", x: ["Les Familiers", "Les Golems", "Les Invocations d'or"], acc: ["cendres d'esprit", "spirit ashes", "cendres"] },
  { id: "elden-p7", d: 4, t: "Comment nomme-t-on les techniques d'armes greffées via les Cendres de guerre ?", a: "Les Arts de guerre", x: ["Les Sorts", "Les Incantations", "Les Prières"], acc: ["arts de guerre", "ashes of war", "cendres de guerre"] },
  { id: "elden-p8", d: 4, t: "Quel enfant de Marika, endormi, est convoité par Mohg et Messmer ?", a: "Miquella", x: ["Godwyn", "Godrick", "Radahn"], acc: ["miquella"] },
  { id: "elden-p9", d: 4, t: "Quel demi-dieu, premier des morts, repose frappé par le Destin de la mort ?", a: "Godwyn", x: ["Godfrey", "Morgott", "Mohg"], acc: ["godwyn"] },
  { id: "elden-p10", d: 4, t: "Comment raille-t-on le héros qui n'a pas de « demoiselle » ?", a: "Sans-demoiselle", x: ["Sans-âme", "Sans-nom", "Sans-terre"], acc: ["sans-demoiselle", "maidenless", "sans demoiselle"] },
  { id: "elden-p11", d: 4, t: "Quelles grandes reliques faut-il rassembler pour restaurer l'Anneau ?", a: "Les Grandes Runes", x: ["Les Sceaux sacrés", "Les Gemmes d'or", "Les Clés d'Elden"], acc: ["grandes runes", "great runes", "runes majeures"] },
  { id: "elden-p12", d: 4, t: "Comment s'appelle l'académie de sorcellerie dirigée par Rennala ?", a: "Raya Lucaria", x: ["Leyndell", "Stormveil", "Sellia"], acc: ["raya lucaria"] },
  { id: "elden-p13", d: 4, t: "Comment s'appelle le château, premier grand donjon, gardé par Godrick ?", a: "Le château de Stormveil", x: ["Raya Lucaria", "Leyndell", "Farum Azula"], acc: ["stormveil", "chateau de stormveil"] },
  { id: "elden-p14", d: 4, t: "Quel joueur légendaire est devenu célèbre en aidant la communauté à vaincre Malenia ?", a: "Let Me Solo Her", x: ["Ninja", "The Happy Hob", "Distortion2"], acc: ["let me solo her", "solo her"] },
  { id: "elden-p15", d: 4, t: "Comment s'appelle le jeu dérivé coopératif d'Elden Ring sorti en 2025 ?", a: "Elden Ring Nightreign", x: ["Elden Ring 2", "Elden Ring Online", "Elden Ring Arena"], acc: ["nightreign", "elden ring nightreign"] },
  { id: "elden-p16", d: 4, t: "Dans quelle région lunaire et pluvieuse se trouve l'académie Raya Lucaria ?", a: "Liurnia", x: ["Caelid", "Necrolimbe", "Leyndell"], acc: ["liurnia"] },
  { id: "elden-p17", d: 4, t: "Comment s'appelle le seigneur-dragon ancestral affronté à Farum Azula ?", a: "Placidusax", x: ["Fortissax", "Gransax", "Smaug"], acc: ["placidusax"] },
  { id: "elden-p18", d: 4, t: "Comment s'appelle la cité en ruine flottante, décor d'un combat contre un dragon ancestral ?", a: "Farum Azula", x: ["Leyndell", "Nokron", "Stormveil"], acc: ["farum azula", "crumbling farum azula"] },
  { id: "elden-p19", d: 4, t: "Quel demi-dieu, boss majeur, revient en pleine puissance dans l'extension de 2024 ?", a: "Radahn", x: ["Godrick", "Rykard", "Morgott"], acc: ["radahn"] },
  { id: "elden-p20", d: 4, t: "Comment appelle-t-on la malédiction de mort qui frappe Godwyn et se répand ?", a: "Le Destin de la mort", x: ["La Peste écarlate", "La Flamme noire", "Le Fléau des runes"], acc: ["destin de la mort", "destined death", "rune de la mort"] },
]);
