import { universe } from "../_build";

export const farcry = universe("jeuxvideo", "Far Cry", [
  // --- Faciles (5) ---
  { id: "farcry-f1", d: 1, t: "Quel éditeur français publie la série Far Cry ?", a: "Ubisoft", x: ["Electronic Arts", "Activision", "Rockstar"], acc: ["ubisoft"] },
  { id: "farcry-f2", d: 1, t: "À quel genre appartient Far Cry ?", a: "Le jeu de tir à la première personne", x: ["Le jeu de course", "Le jeu de gestion", "Le jeu de rythme"], acc: ["fps", "tir a la premiere personne"] },
  { id: "farcry-f3", d: 1, t: "Les jeux Far Cry se déroulent le plus souvent dans quel type d'environnement ?", a: "Un monde ouvert", x: ["Un couloir linéaire", "Une seule pièce", "Un plateau en 2D"], acc: ["monde ouvert", "open world"] },
  { id: "farcry-f4", d: 1, t: "Quel danger, en plus des ennemis humains, guette souvent le joueur dans la nature de Far Cry ?", a: "Les animaux sauvages", x: ["Les fantômes", "Les extraterrestres", "Les zombies"], acc: ["animaux sauvages", "animaux"] },
  { id: "farcry-f5", d: 1, t: "Qu'est-ce qui distingue surtout chaque épisode de Far Cry ?", a: "Un grand méchant charismatique", x: ["Un chien parlant", "Une course de kart", "Un mode musical"], acc: ["mechant charismatique", "grand mechant"] },
  // --- Moyennes (10) ---
  { id: "farcry-m1", d: 2, t: "Quel antagoniste au crâne rasé est célèbre pour son monologue sur « la définition de la folie » ?", a: "Vaas", x: ["Pagan Min", "Joseph Seed", "Antón Castillo"], acc: ["vaas"] },
  { id: "farcry-m2", d: 2, t: "Quel roi tyrannique en costume rose dirige le Kyrat dans Far Cry 4 ?", a: "Pagan Min", x: ["Vaas", "Joseph Seed", "Antón Castillo"], acc: ["pagan min"] },
  { id: "farcry-m3", d: 2, t: "Quel gourou, « le Père », dirige la secte d'Eden's Gate dans Far Cry 5 ?", a: "Joseph Seed", x: ["Vaas", "Pagan Min", "Antón Castillo"], acc: ["joseph seed"] },
  { id: "farcry-m4", d: 2, t: "Dans quel comté fictif du Montana se déroule Far Cry 5 ?", a: "Hope County", x: ["Les îles Rook", "Le Kyrat", "Yara"], acc: ["hope county"] },
  { id: "farcry-m5", d: 2, t: "Sur quel archipel tropical Jason Brody est-il retenu dans Far Cry 3 ?", a: "Les îles Rook", x: ["Le Kyrat", "Yara", "Hope County"], acc: ["iles rook", "rook"] },
  { id: "farcry-m6", d: 2, t: "Dans quelle région himalayenne fictive se déroule Far Cry 4 ?", a: "Le Kyrat", x: ["Yara", "Les îles Rook", "Oros"], acc: ["kyrat"] },
  { id: "farcry-m7", d: 2, t: "Quel dictateur incarné par Giancarlo Esposito règne sur l'île de Yara dans Far Cry 6 ?", a: "Antón Castillo", x: ["Vaas", "Pagan Min", "Joseph Seed"], acc: ["anton castillo", "antón castillo", "castillo"] },
  { id: "farcry-m8", d: 2, t: "Comment se nomme le héros ou l'héroïne jouable de Far Cry 6 ?", a: "Dani Rojas", x: ["Jason Brody", "Ajay Ghale", "Jack Carver"], acc: ["dani rojas", "dani"] },
  { id: "farcry-m9", d: 2, t: "À quelle époque très reculée se déroule Far Cry Primal ?", a: "La préhistoire", x: ["Le Moyen Âge", "L'Antiquité romaine", "Le futur"], acc: ["prehistoire", "préhistoire", "age de pierre"] },
  { id: "farcry-m10", d: 2, t: "Quel studio allemand a créé le tout premier Far Cry en 2004 ?", a: "Crytek", x: ["Ubisoft Montréal", "Naughty Dog", "id Software"], acc: ["crytek"] },
  // --- Dures (15) ---
  { id: "farcry-d1", d: 3, t: "Comment se nomme le jeune touriste héros de Far Cry 3 ?", a: "Jason Brody", x: ["Ajay Ghale", "Dani Rojas", "Jack Carver"], acc: ["jason brody", "jason"] },
  { id: "farcry-d2", d: 3, t: "Quel héros revient au Kyrat disperser les cendres de sa mère dans Far Cry 4 ?", a: "Ajay Ghale", x: ["Jason Brody", "Dani Rojas", "Jack Carver"], acc: ["ajay ghale", "ajay"] },
  { id: "farcry-d3", d: 3, t: "Comment s'appelle le héros du tout premier Far Cry, sur des îles tropicales ?", a: "Jack Carver", x: ["Jason Brody", "Ajay Ghale", "Dani Rojas"], acc: ["jack carver", "jack"] },
  { id: "farcry-d4", d: 3, t: "Sur quel continent se déroule Far Cry 2, marqué par le paludisme et les diamants ?", a: "L'Afrique", x: ["L'Asie", "L'Amérique du Sud", "L'Océanie"], acc: ["afrique"] },
  { id: "farcry-d5", d: 3, t: "Comment surnomme-t-on les adeptes de la secte de Joseph Seed ?", a: "Les Peggies", x: ["Les Templiers", "Les Rakyat", "Les Highwaymen"], acc: ["peggies"] },
  { id: "farcry-d6", d: 3, t: "Quel peuple guerrier autochtone Jason rejoint-il pour libérer les îles Rook ?", a: "Les Rakyat", x: ["Les Peggies", "Les Highwaymen", "Les Wenja"], acc: ["rakyat"] },
  { id: "farcry-d7", d: 3, t: "Quelle tribu le héros Takkar cherche-t-il à réunir dans Far Cry Primal ?", a: "Les Wenja", x: ["Les Rakyat", "Les Peggies", "Les Udam"], acc: ["wenja"] },
  { id: "farcry-d8", d: 3, t: "Comment se nomme le chasseur héros de Far Cry Primal ?", a: "Takkar", x: ["Jason", "Ajay", "Dani"], acc: ["takkar"] },
  { id: "farcry-d9", d: 3, t: "Quelles jumelles dirigent les Highwaymen dans Far Cry New Dawn ?", a: "Mickey et Lou", x: ["Mary May et Grace", "Faith et Rachel", "Kim et Amita"], acc: ["mickey et lou"] },
  { id: "farcry-d10", d: 3, t: "De quel épisode Far Cry New Dawn est-il la suite directe, dans un Hope County dévasté ?", a: "Far Cry 5", x: ["Far Cry 3", "Far Cry 4", "Far Cry 6"], acc: ["far cry 5"] },
  { id: "farcry-d11", d: 3, t: "Quelle notion Vaas définit-il dans son célèbre monologue à Jason ?", a: "La folie", x: ["La liberté", "La vengeance", "La foi"], acc: ["folie", "la folie"] },
  { id: "farcry-d12", d: 3, t: "De quel pays réel l'île de Yara, dans Far Cry 6, s'inspire-t-elle largement ?", a: "Cuba", x: ["Le Mexique", "Le Venezuela", "Le Brésil"], acc: ["cuba"] },
  { id: "farcry-d13", d: 3, t: "Quel compagnon canin peut aider le joueur dans Far Cry 5 ?", a: "Boomer", x: ["Cheeseburger", "Peaches", "Guapo"], acc: ["boomer"] },
  { id: "farcry-d14", d: 3, t: "Combien de frères et sœurs « hérauts » secondent Joseph Seed dans Far Cry 5 ?", a: "Trois", x: ["Un", "Cinq", "Sept"], acc: ["3", "trois"] },
  { id: "farcry-d15", d: 3, t: "Quel acteur, aussi Gus Fring dans Breaking Bad, incarne Antón Castillo ?", a: "Giancarlo Esposito", x: ["Michael Mando", "Troy Baker", "Nolan North"], acc: ["giancarlo esposito", "esposito"] },
  // --- Pro (20) ---
  { id: "farcry-p1", d: 4, t: "En quelle année Far Cry 3, qui a lancé la popularité de la série, est-il sorti ?", a: "2012", x: ["2008", "2010", "2015"], acc: ["2012"] },
  { id: "farcry-p2", d: 4, t: "Quel acteur a prêté ses traits et sa voix à Vaas dans Far Cry 3 ?", a: "Michael Mando", x: ["Giancarlo Esposito", "Troy Baker", "Rahul Kohli"], acc: ["michael mando", "mando"] },
  { id: "farcry-p3", d: 4, t: "Quelle structure escalade-t-on souvent pour dévoiler la carte des environs ?", a: "Une tour radio", x: ["Un phare", "Une éolienne", "Un donjon"], acc: ["tour radio", "tour"] },
  { id: "farcry-p4", d: 4, t: "À partir de quoi fabrique-t-on sacs et étuis dans Far Cry 3 et 4 ?", a: "Des peaux d'animaux", x: ["Des pièces d'or", "Des plantes seules", "Du plastique"], acc: ["peaux d'animaux", "peaux"] },
  { id: "farcry-p5", d: 4, t: "De quelle couleur est le costume emblématique de Pagan Min sur la jaquette de Far Cry 4 ?", a: "Rose", x: ["Noir", "Blanc", "Rouge"], acc: ["rose"] },
  { id: "farcry-p6", d: 4, t: "Quelle maladie le héros de Far Cry 2 doit-il gérer, nécessitant des médicaments ?", a: "Le paludisme", x: ["La peste", "Le choléra", "La rage"], acc: ["paludisme", "malaria"] },
  { id: "farcry-p7", d: 4, t: "En quelle catastrophe imminente la secte d'Eden's Gate, dans Far Cry 5, croit-elle ?", a: "L'Effondrement", x: ["L'Invasion", "Le Déluge", "La Grande Peste"], acc: ["effondrement", "the collapse"] },
  { id: "farcry-p8", d: 4, t: "Quel mouvement de guérilla Dani Rojas rejoint-il dans Far Cry 6 ?", a: "Libertad", x: ["Les Rakyat", "Eden's Gate", "Les Highwaymen"], acc: ["libertad"] },
  { id: "farcry-p9", d: 4, t: "Quel crocodile est l'un des « Amigos » compagnons de Far Cry 6 ?", a: "Guapo", x: ["Chorizo", "Boomer", "Cheeseburger"], acc: ["guapo"] },
  { id: "farcry-p10", d: 4, t: "En quelle année est sorti Far Cry New Dawn ?", a: "2019", x: ["2016", "2021", "2014"], acc: ["2019"] },
  { id: "farcry-p11", d: 4, t: "En quelle année est sorti Far Cry 6 ?", a: "2021", x: ["2018", "2019", "2023"], acc: ["2021"] },
  { id: "farcry-p12", d: 4, t: "En quelle année est sorti Far Cry Primal ?", a: "2016", x: ["2012", "2014", "2019"], acc: ["2016"] },
  { id: "farcry-p13", d: 4, t: "Dans quelle langue s'expriment les personnages de Far Cry Primal ?", a: "Une langue préhistorique reconstituée", x: ["Le latin", "L'anglais moderne", "Le français"], acc: ["langue prehistorique", "langue reconstituee"] },
  { id: "farcry-p14", d: 4, t: "Quelle prêtresse des Rakyat, sœur de Vaas, envoûte Jason dans Far Cry 3 ?", a: "Citra", x: ["Faith", "Yuma", "Amita"], acc: ["citra"] },
  { id: "farcry-p15", d: 4, t: "Quel mouvement rebelle Ajay aide-t-il au Kyrat, tiraillé entre Amita et Sabal ?", a: "Le Sentier doré", x: ["Les Rakyat", "Libertad", "Eden's Gate"], acc: ["sentier dore", "sentier doré", "golden path"] },
  { id: "farcry-p16", d: 4, t: "Quelle drogue hallucinogène, la « Félicité », la secte de Far Cry 5 répand-elle ?", a: "Le Bliss", x: ["Le Surge", "La Rage", "Le Sérum"], acc: ["bliss", "felicite", "félicité"] },
  { id: "farcry-p17", d: 4, t: "Sur quel moteur maison d'Ubisoft tournent les Far Cry depuis le deuxième épisode ?", a: "Le Dunia", x: ["Le CryEngine", "L'Anvil", "Le Frostbite"], acc: ["dunia"] },
  { id: "farcry-p18", d: 4, t: "Comment se prénomme le jeune fils d'Antón Castillo, qu'il forme à lui succéder ?", a: "Diego", x: ["Dani", "Sabal", "Ajay"], acc: ["diego"] },
  { id: "farcry-p19", d: 4, t: "Quel trafiquant d'esclaves dirige l'île sud dans Far Cry 3, au-dessus de Vaas ?", a: "Hoyt Volker", x: ["Pagan Min", "Antón Castillo", "Joseph Seed"], acc: ["hoyt volker", "hoyt"] },
  { id: "farcry-p20", d: 4, t: "Comment nomme-t-on les armes bricolées et improvisées de Far Cry 6 ?", a: "Les armes Resolver", x: ["Les armes Nano", "Les armes reliques", "Les armes fantômes"], acc: ["resolver", "armes resolver"] },
]);
