import { universe } from "../_build";

export const farmingsimulator = universe("jeuxvideo", "Farming Simulator", [
  // --- Faciles (5) ---
  { id: "farmsim-f1", d: 1, t: "Quel type de jeu est Farming Simulator ?", a: "Un simulateur agricole", x: ["Un jeu de course", "Un jeu de tir", "Un jeu de combat"] },
  { id: "farmsim-f2", d: 1, t: "Quel animal N'élève-t-on PAS dans le jeu ?", a: "Le dragon", x: ["La vache", "Le mouton", "La poule"] },
  { id: "farmsim-f3", d: 1, t: "Quelle activité est au cœur du jeu ?", a: "Cultiver des champs", x: ["Piloter des avions", "Gérer un hôtel", "Explorer l'espace"] },
  { id: "farmsim-f4", d: 1, t: "Quel véhicule est emblématique du jeu ?", a: "Le tracteur", x: ["Le char", "La moto", "Le sous-marin"] },
  { id: "farmsim-f5", d: 1, t: "Que récolte-t-on principalement dans les champs ?", a: "Du blé", x: ["De l'or", "Du charbon", "Du pétrole"] },
  // --- Moyennes (10) ---
  { id: "farmsim-m1", d: 2, t: "Quel studio développe Farming Simulator ?", a: "Giants Software", x: ["Focus Entertainment", "Ubisoft", "Electronic Arts"] },
  { id: "farmsim-m2", d: 2, t: "Quelle grande marque de tracteurs verte et jaune est présente dans le jeu ?", a: "John Deere", x: ["Ferrari", "Bugatti", "Porsche"] },
  { id: "farmsim-m3", d: 2, t: "Laquelle de ces marques de tracteurs est allemande ?", a: "Fendt", x: ["Case IH", "New Holland", "Valtra"] },
  { id: "farmsim-m4", d: 2, t: "Quelles sont les trois grandes activités du jeu ?", a: "Agriculture, élevage et sylviculture", x: ["Agriculture, pêche et minage", "Élevage, chasse et cuisine", "Agriculture, transport et construction"] },
  { id: "farmsim-m5", d: 2, t: "Que peut-on faire pousser puis vendre ?", a: "Des céréales", x: ["Des voitures", "Des armes", "Des bijoux"] },
  { id: "farmsim-m6", d: 2, t: "Quelle machine sert à récolter les céréales ?", a: "La moissonneuse-batteuse", x: ["La bétonnière", "La pelleteuse", "La grue"] },
  { id: "farmsim-m7", d: 2, t: "Comment gagne-t-on de l'argent dans le jeu ?", a: "En vendant sa récolte", x: ["En gagnant des courses", "En combattant des ennemis", "En résolvant des énigmes"] },
  { id: "farmsim-m8", d: 2, t: "Que doit-on faire avant de semer dans un champ ?", a: "Labourer et préparer le sol", x: ["Construire une maison", "Recruter une armée", "Creuser une mine"] },
  { id: "farmsim-m9", d: 2, t: "Comment appelle-t-on la plateforme officielle de mods du jeu ?", a: "Le ModHub", x: ["Le Workshop", "Le Nexus", "Le Bazaar"] },
  { id: "farmsim-m10", d: 2, t: "Sur quel type de plateformes joue-t-on à Farming Simulator ?", a: "PC et consoles", x: ["Uniquement en arcade", "Uniquement en réalité virtuelle", "Uniquement sur borne"] },
  // --- Dures (15) ---
  { id: "farmsim-d1", d: 3, t: "De quel pays vient le studio Giants Software ?", a: "La Suisse", x: ["L'Allemagne", "Les États-Unis", "La France"] },
  { id: "farmsim-d2", d: 3, t: "Quelle marque de tracteurs italienne fabrique aussi des voitures de sport ?", a: "Lamborghini", x: ["Fendt", "Valtra", "Kubota"] },
  { id: "farmsim-d3", d: 3, t: "Quelle marque japonaise de matériel agricole est présente dans le jeu ?", a: "Kubota", x: ["Fendt", "Claas", "Deutz-Fahr"] },
  { id: "farmsim-d4", d: 3, t: "Quelle fonctionnalité guide automatiquement le tracteur en ligne droite ?", a: "L'aide au guidage GPS", x: ["Le pilote automatique aérien", "Le radar de recul", "Le régulateur de vitesse"] },
  { id: "farmsim-d5", d: 3, t: "Quelle activité forestière peut-on pratiquer ?", a: "Abattre et transporter des grumes", x: ["Chasser le gibier", "Pêcher en rivière", "Faire du rafting"] },
  { id: "farmsim-d6", d: 3, t: "Quelles chaînes transforment les matières premières en produits finis ?", a: "Les chaînes de production", x: ["Les quêtes secondaires", "Les combats de boss", "Les mini-jeux d'arcade"] },
  { id: "farmsim-d7", d: 3, t: "Quel mode permet de gérer une ferme à plusieurs joueurs ?", a: "Le multijoueur coopératif", x: ["Le battle royale", "Le mode versus", "Le mode histoire"] },
  { id: "farmsim-d8", d: 3, t: "Quelle marque de tracteurs finlandaise est présente dans le jeu ?", a: "Valtra", x: ["Fendt", "Claas", "John Deere"] },
  { id: "farmsim-d9", d: 3, t: "Combien de marques réelles environ le jeu propose-t-il ?", a: "Plus d'une centaine", x: ["Environ dix", "Environ trois", "Aucune, elles sont fictives"] },
  { id: "farmsim-d10", d: 3, t: "Quelle culture sert surtout à nourrir le bétail sous forme d'ensilage ?", a: "Le maïs", x: ["Le coton", "La pomme de terre", "Le tournesol"] },
  { id: "farmsim-d11", d: 3, t: "Quel équipement transporte la récolte jusqu'au point de vente ?", a: "La remorque", x: ["L'hélicoptère", "Le train à vapeur", "Le voilier"] },
  { id: "farmsim-d12", d: 3, t: "Quelle marque rouge de matériel agricole a « IH » dans son nom ?", a: "Case IH", x: ["New Holland", "Massey Ferguson", "Deutz-Fahr"] },
  { id: "farmsim-d13", d: 3, t: "Sur quel continent se déroule un des environnements de Farming Simulator 25 ?", a: "L'Asie de l'Est", x: ["L'Afrique", "L'Australie", "L'Amérique du Sud"] },
  { id: "farmsim-d14", d: 3, t: "Que peut-on produire à partir du lait dans les chaînes de production ?", a: "Du fromage", x: ["Du pain", "De l'essence", "Du tissu"] },
  { id: "farmsim-d15", d: 3, t: "Quel outil retourne la terre en profondeur avant les semis ?", a: "La charrue", x: ["L'épandeur", "La moissonneuse", "La remorque"] },
  // --- Pro (20) ---
  { id: "farmsim-p1", d: 4, t: "En quelle année est sorti Farming Simulator 22 ?", a: "2021", x: ["2019", "2023", "2017"] },
  { id: "farmsim-p2", d: 4, t: "En quelle année est sorti Farming Simulator 25 ?", a: "2024", x: ["2022", "2026", "2020"] },
  { id: "farmsim-p3", d: 4, t: "Quelle marque allemande a « Fahr » dans son nom ?", a: "Deutz-Fahr", x: ["Fendt", "Claas", "Krone"] },
  { id: "farmsim-p4", d: 4, t: "Quelle marque allemande de moissonneuses vertes est réputée pour la récolte ?", a: "Claas", x: ["Fendt", "Krone", "Amazone"] },
  { id: "farmsim-p5", d: 4, t: "Quelle culture nécessite une planteuse et une arracheuse spécifiques ?", a: "La pomme de terre", x: ["Le blé", "L'orge", "Le colza"] },
  { id: "farmsim-p6", d: 4, t: "Quel fourrage compacté et emballé de plastique blanc produit-on ?", a: "Les balles d'ensilage", x: ["Les bottes de foin", "Les sacs de grain", "Les palettes de bois"] },
  { id: "farmsim-p7", d: 4, t: "Quelle marque allemande de matériel de fenaison fait faucheuses et andaineuses ?", a: "Krone", x: ["Kubota", "Valtra", "Case IH"] },
  { id: "farmsim-p8", d: 4, t: "Quelle plante sucrière se récolte à l'automne avec une machine dédiée ?", a: "La betterave sucrière", x: ["Le maïs", "Le soja", "Le tournesol"] },
  { id: "farmsim-p9", d: 4, t: "Quel animal produit de la laine dans le jeu ?", a: "Le mouton", x: ["La vache", "Le cochon", "La poule"] },
  { id: "farmsim-p10", d: 4, t: "Quel animal produit du lait ?", a: "La vache", x: ["Le mouton", "Le cheval", "La poule"] },
  { id: "farmsim-p11", d: 4, t: "Quelle activité annexe consiste à monter et entraîner un animal ?", a: "L'équitation", x: ["La course automobile", "Le pilotage de drone", "La plongée"] },
  { id: "farmsim-p12", d: 4, t: "Quelle marque appartient au même groupe que Case IH ?", a: "New Holland", x: ["Fendt", "Claas", "Deutz-Fahr"] },
  { id: "farmsim-p13", d: 4, t: "Quel outil répand de l'engrais sur les cultures ?", a: "L'épandeur", x: ["La charrue", "La herse", "Le semoir"] },
  { id: "farmsim-p14", d: 4, t: "Comment s'appelle le tout premier jeu de la série, sorti en 2008 ?", a: "Farming Simulator 2008", x: ["Farming Simulator 2000", "Harvest Master", "Farm Life"] },
  { id: "farmsim-p15", d: 4, t: "Comment s'appelle la compétition e-sport officielle du jeu ?", a: "La Farming Simulator League", x: ["La Tractor Cup", "La Harvest Arena", "La Giants League"] },
  { id: "farmsim-p16", d: 4, t: "Quel liquide stocké en cuve sert à fertiliser les champs ?", a: "Le lisier", x: ["Le carburant d'avion", "La peinture", "L'eau de mer"] },
  { id: "farmsim-p17", d: 4, t: "Quelle culture textile blanche récolte-t-on dans les environnements américains ?", a: "Le coton", x: ["Le lin", "Le chanvre", "Le jute"] },
  { id: "farmsim-p18", d: 4, t: "Quelle machine ramasse le foin ou la paille pour former des balles ?", a: "La presse", x: ["La moissonneuse", "La charrue", "Le pulvérisateur"] },
  { id: "farmsim-p19", d: 4, t: "Quelle marque suédoise de matériel agricole a rejoint le jeu ?", a: "Väderstad", x: ["Kubota", "Lamborghini", "Deutz-Fahr"] },
  { id: "farmsim-p20", d: 4, t: "En quelle saison récolte-t-on principalement le blé si les saisons sont activées ?", a: "L'été", x: ["L'hiver", "Le printemps", "L'automne"] },
]);
