import { universe } from "../_build";

export const finalfantasy = universe("jeuxvideo", "Final Fantasy", [
  // --- Faciles (5) ---
  { id: "ff-f1", d: 1, t: "Quelle entreprise japonaise édite la série Final Fantasy ?", a: "Square Enix", x: ["Capcom", "Konami", "Bandai Namco"], acc: ["square enix", "square"] },
  { id: "ff-f2", d: 1, t: "À quel genre appartient Final Fantasy ?", a: "Le jeu de rôle", x: ["Le jeu de course", "Le jeu de tir", "Le jeu de foot"], acc: ["jeu de role", "rpg"] },
  { id: "ff-f3", d: 1, t: "Quel grand oiseau jaune sert souvent de monture dans Final Fantasy ?", a: "Le Chocobo", x: ["Le Moogle", "Le Tonberry", "Le Cactuar"], acc: ["chocobo"] },
  { id: "ff-f4", d: 1, t: "Sur quelle console le tout premier Final Fantasy est-il sorti en 1987 ?", a: "La NES", x: ["La PlayStation", "La Game Boy", "La Xbox"], acc: ["nes", "famicom"] },
  { id: "ff-f5", d: 1, t: "Quelle petite créature à pompon, disant souvent « kupo », revient dans la série ?", a: "Le Moogle", x: ["Le Chocobo", "Le Cactuar", "Le Tonberry"], acc: ["moogle", "mog"] },
  // --- Moyennes (10) ---
  { id: "ff-m1", d: 2, t: "Quel héros blond aux cheveux en pics et à l'épée géante mène Final Fantasy VII ?", a: "Cloud Strife", x: ["Squall Leonhart", "Tidus", "Zidane"], acc: ["cloud", "cloud strife"] },
  { id: "ff-m2", d: 2, t: "Quel antagoniste aux longs cheveux argentés et à l'épée immense hante Final Fantasy VII ?", a: "Sephiroth", x: ["Kefka", "Golbez", "Kuja"], acc: ["sephiroth"] },
  { id: "ff-m3", d: 2, t: "Quel roi dragon est l'invocation la plus emblématique de la série ?", a: "Bahamut", x: ["Ifrit", "Shiva", "Ramuh"], acc: ["bahamut"] },
  { id: "ff-m4", d: 2, t: "Quel compositeur a signé la musique de la plupart des Final Fantasy classiques ?", a: "Nobuo Uematsu", x: ["Koji Kondo", "Yasunori Mitsuda", "Yoko Shimomura"], acc: ["nobuo uematsu", "uematsu"] },
  { id: "ff-m5", d: 2, t: "Quelle est la monnaie utilisée dans la série ?", a: "Le gil", x: ["Le zenny", "La rupee", "Le crédit"], acc: ["gil"] },
  { id: "ff-m6", d: 2, t: "Quel objet, la « queue de Phénix », ranime un allié tombé au combat ?", a: "La queue de Phénix", x: ["La potion", "L'élixir", "L'éther"], acc: ["queue de phenix", "queue de phénix", "phoenix down"] },
  { id: "ff-m7", d: 2, t: "Quel personnage nommé Cid, souvent ingénieur ou pilote, revient à chaque épisode ?", a: "Cid", x: ["Biggs", "Wedge", "Gilgamesh"], acc: ["cid"] },
  { id: "ff-m8", d: 2, t: "Quelle mégalopole industrielle, dominée par la Shinra, ouvre Final Fantasy VII ?", a: "Midgar", x: ["Balamb", "Zanarkand", "Insomnia"], acc: ["midgar"] },
  { id: "ff-m9", d: 2, t: "Quel sport aquatique peut-on pratiquer dans Final Fantasy X ?", a: "Le Blitzball", x: ["Le Triple Triad", "La course de Chocobo", "Le Tetra Master"], acc: ["blitzball"] },
  { id: "ff-m10", d: 2, t: "Quel créateur japonais est le père de la série Final Fantasy ?", a: "Hironobu Sakaguchi", x: ["Shigeru Miyamoto", "Hideo Kojima", "Yuji Horii"], acc: ["sakaguchi", "hironobu sakaguchi"] },
  // --- Dures (15) ---
  { id: "ff-d1", d: 3, t: "Quelle héroïne fleuriste de Final Fantasy VII meurt tragiquement, tuée par Sephiroth ?", a: "Aerith", x: ["Tifa", "Yuffie", "Jessie"], acc: ["aerith", "aeris"] },
  { id: "ff-d2", d: 3, t: "Quelles sphères colorées confèrent magies et pouvoirs dans Final Fantasy VII ?", a: "Les Materias", x: ["Les Cristaux", "Les Espers", "Les Gambits"], acc: ["materia", "materias"] },
  { id: "ff-d3", d: 3, t: "Comment s'appelle l'épée géante de Cloud dans Final Fantasy VII ?", a: "L'épée Buster", x: ["La Masamune", "La gunblade", "L'Excalibur"], acc: ["buster", "epee buster", "buster sword"] },
  { id: "ff-d4", d: 3, t: "Quelle arme hybride, mi-épée mi-pistolet, Squall manie-t-il dans Final Fantasy VIII ?", a: "La gunblade", x: ["Le nunchaku", "L'arbalète", "Le trident"], acc: ["gunblade"] },
  { id: "ff-d5", d: 3, t: "Quel héros sportif venu de Zanarkand est le protagoniste de Final Fantasy X ?", a: "Tidus", x: ["Squall", "Zidane", "Noctis"], acc: ["tidus"] },
  { id: "ff-d6", d: 3, t: "Quel monstre colossal terrorise le monde de Spira dans Final Fantasy X ?", a: "Sin", x: ["Jenova", "Ultimecia", "Kefka"], acc: ["sin"] },
  { id: "ff-d7", d: 3, t: "Quel bouffon dément détruit le monde dans Final Fantasy VI ?", a: "Kefka", x: ["Sephiroth", "Kuja", "Golbez"], acc: ["kefka"] },
  { id: "ff-d8", d: 3, t: "Quel voleur à la queue de singe est le héros de Final Fantasy IX ?", a: "Zidane", x: ["Vivi", "Steiner", "Tidus"], acc: ["zidane"] },
  { id: "ff-d9", d: 3, t: "Quel petit mage noir au chapeau pointu et aux yeux jaunes est adoré des fans de Final Fantasy IX ?", a: "Vivi", x: ["Zidane", "Kuja", "Vaan"], acc: ["vivi"] },
  { id: "ff-d10", d: 3, t: "Quelle héroïne aux cheveux roses, surnommée « Lightning », mène Final Fantasy XIII ?", a: "Lightning", x: ["Yuna", "Terra", "Rinoa"], acc: ["lightning", "claire farron"] },
  { id: "ff-d11", d: 3, t: "Combien d'amis forment le groupe de Noctis lors du road trip de Final Fantasy XV ?", a: "Quatre", x: ["Trois", "Cinq", "Sept"], acc: ["4", "quatre"] },
  { id: "ff-d12", d: 3, t: "Sur quel monde le MMORPG Final Fantasy XIV se déroule-t-il ?", a: "Éorzéa", x: ["Spira", "Ivalice", "Cocoon"], acc: ["eorzea", "éorzéa"] },
  { id: "ff-d13", d: 3, t: "Avec quelle entreprise Square a-t-elle fusionné en 2003 pour former Square Enix ?", a: "Enix", x: ["Capcom", "Sega", "Namco"], acc: ["enix"] },
  { id: "ff-d14", d: 3, t: "Quel thème musical légendaire, porté par un chœur latin, accompagne Sephiroth ?", a: "One-Winged Angel", x: ["Aerith's Theme", "Prelude", "Victory Fanfare"], acc: ["one-winged angel", "one winged angel"] },
  { id: "ff-d15", d: 3, t: "Quel membre de l'équipe de Final Fantasy VII a un bras remplacé par une mitrailleuse ?", a: "Barret", x: ["Cloud", "Vincent", "Cait Sith"], acc: ["barret"] },
  // --- Pro (20) ---
  { id: "ff-p1", d: 4, t: "Pourquoi le premier jeu se serait-il appelé « Final » Fantasy, selon la légende ?", a: "Le studio était au bord de la faillite", x: ["Ce devait être le dernier RPG au monde", "Le héros meurt à la fin", "Le créateur partait à la retraite"], acc: ["faillite"] },
  { id: "ff-p2", d: 4, t: "En quelle année le remake de Final Fantasy VII est-il sorti ?", a: "2020", x: ["2015", "2017", "2023"], acc: ["2020"] },
  { id: "ff-p3", d: 4, t: "Comment s'intitule le deuxième volet du remake de Final Fantasy VII, sorti en 2024 ?", a: "Rebirth", x: ["Remake", "Reunion", "Reborn"], acc: ["rebirth"] },
  { id: "ff-p4", d: 4, t: "Quel héros, maître du feu, mène Final Fantasy XVI sorti en 2023 ?", a: "Clive Rosfield", x: ["Noctis Lucis", "Cloud Strife", "Squall Leonhart"], acc: ["clive", "clive rosfield"] },
  { id: "ff-p5", d: 4, t: "Comment nomme-t-on les invocations gigantesques de Final Fantasy XVI ?", a: "Les Primordiaux", x: ["Les Espers", "Les Materias", "Les Gardiens"], acc: ["primordiaux", "eikon", "eikons"] },
  { id: "ff-p6", d: 4, t: "Quel producteur, surnommé Yoshi-P, a sauvé Final Fantasy XIV avec « A Realm Reborn » ?", a: "Naoki Yoshida", x: ["Tetsuya Nomura", "Yoshinori Kitase", "Hironobu Sakaguchi"], acc: ["naoki yoshida", "yoshida", "yoshi-p"] },
  { id: "ff-p7", d: 4, t: "Quel artiste a conçu les personnages de Final Fantasy VII et VIII, et créé Kingdom Hearts ?", a: "Tetsuya Nomura", x: ["Yoshitaka Amano", "Akira Toriyama", "Kazuma Kaneko"], acc: ["nomura", "tetsuya nomura"] },
  { id: "ff-p8", d: 4, t: "Quel illustrateur signe les logos et aquarelles emblématiques de la série ?", a: "Yoshitaka Amano", x: ["Tetsuya Nomura", "Akira Toriyama", "Kazuma Kaneko"], acc: ["amano", "yoshitaka amano"] },
  { id: "ff-p9", d: 4, t: "Quel antagoniste androgyne, semeur de génomes, s'oppose à Zidane dans Final Fantasy IX ?", a: "Kuja", x: ["Kefka", "Sephiroth", "Golbez"], acc: ["kuja"] },
  { id: "ff-p10", d: 4, t: "Quelle académie militaire forme Squall et les SeeD dans Final Fantasy VIII ?", a: "Le Jardin de Balamb", x: ["L'académie de Midgar", "L'école de Zanarkand", "Le collège de Cocoon"], acc: ["balamb", "jardin de balamb"] },
  { id: "ff-p11", d: 4, t: "Quel guerrier bourru au long manteau rouge guide Tidus dans Final Fantasy X ?", a: "Auron", x: ["Wakka", "Kimahri", "Jecht"], acc: ["auron"] },
  { id: "ff-p12", d: 4, t: "Quel pirate du ciel élégant accompagne Vaan dans Final Fantasy XII ?", a: "Balthier", x: ["Basch", "Vayne", "Larsa"], acc: ["balthier"] },
  { id: "ff-p13", d: 4, t: "Sur quelle console 16 bits Final Fantasy VI est-il d'abord sorti ?", a: "La Super Nintendo", x: ["La PlayStation", "La NES", "La Game Boy"], acc: ["super nintendo", "snes"] },
  { id: "ff-p14", d: 4, t: "Sur quelle console Final Fantasy VII est-il sorti en 1997, marquant l'abandon de Nintendo ?", a: "La PlayStation", x: ["La Super Nintendo", "La Nintendo 64", "La Saturn"], acc: ["playstation", "ps1"] },
  { id: "ff-p15", d: 4, t: "Comment nomme-t-on les attaques spéciales déclenchées quand une jauge se remplit, comme la « Braver » de Cloud ?", a: "Les Limit Breaks", x: ["Les Materias", "Les Gambits", "Les Espers"], acc: ["limit break", "limit breaks", "transcendance"] },
  { id: "ff-p16", d: 4, t: "Quel épéiste récurrent à plusieurs bras collectionne les armes légendaires ?", a: "Gilgamesh", x: ["Cid", "Biggs", "Kefka"], acc: ["gilgamesh"] },
  { id: "ff-p17", d: 4, t: "Quel spin-off tactique au tour par tour se déroule aussi dans le monde d'Ivalice ?", a: "Final Fantasy Tactics", x: ["Final Fantasy Crystal Chronicles", "Dissidia", "Chocobo Racing"], acc: ["final fantasy tactics", "tactics"] },
  { id: "ff-p18", d: 4, t: "Quel petit air musical retentit à la fin de chaque combat gagné depuis 1987 ?", a: "La fanfare de la victoire", x: ["Le Prélude", "L'hymne des cristaux", "La berceuse d'Aerith"], acc: ["fanfare de la victoire", "victory fanfare"] },
  { id: "ff-p19", d: 4, t: "Quels objets incarnent souvent l'équilibre du monde et sont au cœur de nombreux épisodes ?", a: "Les cristaux", x: ["Les materias", "Les espers", "Les gils"], acc: ["cristaux", "les cristaux"] },
  { id: "ff-p20", d: 4, t: "De quel royaume Noctis est-il le prince héritier dans Final Fantasy XV ?", a: "Le Lucis", x: ["Le Niflheim", "Le Tenebrae", "L'Insomnia"], acc: ["lucis"] },
]);
