import { universe } from "../_build";

export const fortnite = universe("jeuxvideo", "Fortnite", [
  // --- Faciles (5) ---
  { id: "fortnite-f1", d: 1, t: "Quel studio a développé Fortnite ?", a: "Epic Games", x: ["Activision", "EA", "Ubisoft"], acc: ["epic games", "epic"] },
  { id: "fortnite-f2", d: 1, t: "Quel mode a rendu Fortnite mondialement célèbre ?", a: "Le Battle Royale", x: ["La course automobile", "Le jeu de gestion", "Le jeu de cartes"], acc: ["battle royale", "le battle royale"] },
  { id: "fortnite-f3", d: 1, t: "Combien de joueurs s'affrontent dans une partie de Battle Royale classique ?", a: "100", x: ["10", "50", "500"], acc: ["100", "cent"] },
  { id: "fortnite-f4", d: 1, t: "Quelle action, marque de fabrique de Fortnite, permet de se protéger en pleine partie ?", a: "Construire", x: ["Nager", "Creuser", "Voler des avions"], acc: ["construire", "construction", "build"] },
  { id: "fortnite-f5", d: 1, t: "Combien coûte Fortnite pour commencer à jouer ?", a: "Rien, il est gratuit", x: ["10 euros", "60 euros", "un abonnement mensuel"], acc: ["gratuit", "rien", "free"] },
  // --- Moyennes (10) ---
  { id: "fortnite-m1", d: 2, t: "Comment s'appelle la monnaie virtuelle de Fortnite ?", a: "Les V-Bucks", x: ["Les Robux", "Les Gil", "Les Zenis"], acc: ["v-bucks", "vbucks", "v bucks"] },
  { id: "fortnite-m2", d: 2, t: "Comment s'appelle le véhicule volant d'où les joueurs sautent en début de partie ?", a: "Le bus de combat", x: ["L'hélicoptère", "La montgolfière", "La fusée"], acc: ["bus de combat", "battle bus", "bus"] },
  { id: "fortnite-m3", d: 2, t: "Quel phénomène réduit peu à peu la zone jouable ?", a: "La tempête", x: ["Le brouillard", "La pluie acide", "La tornade"], acc: ["tempete", "la tempete", "storm"] },
  { id: "fortnite-m4", d: 2, t: "Quel outil de base sert à récolter des matériaux dans Fortnite ?", a: "La pioche", x: ["La pelle", "La hache de guerre", "Le marteau"], acc: ["pioche", "la pioche", "pickaxe"] },
  { id: "fortnite-m5", d: 2, t: "Comment appelle-t-on la victoire quand on est le dernier survivant ?", a: "La Victoire Royale", x: ["Le Game Over", "Le Chicken Dinner", "Le Fatality"], acc: ["victoire royale", "top 1", "victory royale"] },
  { id: "fortnite-m6", d: 2, t: "Comment appelle-t-on les tenues achetées pour personnaliser son personnage ?", a: "Des skins", x: ["Des armures", "Des uniformes", "Des costumes de guilde"], acc: ["skins", "des skins", "tenues"] },
  { id: "fortnite-m7", d: 2, t: "Comment s'appelle l'abonnement saisonnier qui offre des récompenses au fil des niveaux ?", a: "Le Passe de combat", x: ["Le Season Ticket", "L'Abo VIP", "Le Pass Or"], acc: ["passe de combat", "battle pass", "pass de combat"] },
  { id: "fortnite-m8", d: 2, t: "Que font les joueurs pour narguer leurs adversaires avec des danses ?", a: "Des emotes", x: ["Des sorts", "Des cris de guerre", "Des saluts militaires"], acc: ["emotes", "danses", "des emotes"] },
  { id: "fortnite-m9", d: 2, t: "Quel animal en peluche gonflable contient du butin quand on le casse ?", a: "Le lama", x: ["Le panda", "Le poney", "L'ours"], acc: ["lama", "le lama", "loot lama"] },
  { id: "fortnite-m10", d: 2, t: "En quelle année le mode Battle Royale de Fortnite est-il sorti ?", a: "2017", x: ["2013", "2020", "2015"], acc: ["2017"] },
  // --- Dures (15) ---
  { id: "fortnite-d1", d: 3, t: "Comment s'appelle le PDG et fondateur d'Epic Games ?", a: "Tim Sweeney", x: ["Gabe Newell", "Phil Spencer", "Bobby Kotick"], acc: ["tim sweeney", "sweeney"] },
  { id: "fortnite-d2", d: 3, t: "Quel lieu de la carte, une ville aux hautes tours, est devenu emblématique ?", a: "Tilted Towers", x: ["Pleasant Park", "Retail Row", "Salty Springs"], acc: ["tilted towers", "tilted"] },
  { id: "fortnite-d3", d: 3, t: "Quel moteur graphique maison Epic Games utilise-t-il pour Fortnite ?", a: "L'Unreal Engine", x: ["L'Unity", "Le Frostbite", "Le CryEngine"], acc: ["unreal engine", "unreal"] },
  { id: "fortnite-d4", d: 3, t: "Comment appelle-t-on le mode de jeu sans construction, ajouté en 2022 ?", a: "Le mode Zéro Construction", x: ["Le mode Créatif", "Le mode Hardcore", "Le mode Classique"], acc: ["zero construction", "zero build", "sans construction"] },
  { id: "fortnite-d5", d: 3, t: "Comment s'appelle le tout premier mode de Fortnite, coopératif contre des zombies ?", a: "Sauver le monde", x: ["Créatif", "Battle Royale", "Fêtes royales"], acc: ["sauver le monde", "save the world"] },
  { id: "fortnite-d6", d: 3, t: "Quel rappeur américain a donné un concert virtuel géant dans Fortnite en 2020 ?", a: "Travis Scott", x: ["Drake", "Kanye West", "Eminem"], acc: ["travis scott", "travis"] },
  { id: "fortnite-d7", d: 3, t: "Quel objet de soin, une grande gourde, restaure lentement vie et bouclier ?", a: "Le Chug Jug", x: ["La Mini-potion", "Le Médikit", "La Pomme"], acc: ["chug jug", "chug"] },
  { id: "fortnite-d8", d: 3, t: "Quels sont les trois matériaux de base pour construire ?", a: "Bois, pierre et métal", x: ["Or, argent et bronze", "Sable, verre et acier", "Terre, eau et feu"], acc: ["bois pierre et metal", "bois pierre metal", "bois brique metal"] },
  { id: "fortnite-d9", d: 3, t: "Quel personnage doré de Chapitre 2 transforme en or tout ce qu'il touche ?", a: "Midas", x: ["Meowscles", "Peely", "Jonesy"], acc: ["midas"] },
  { id: "fortnite-d10", d: 3, t: "Quel véhicule permet de faire réapparaître ses coéquipiers éliminés ?", a: "La camionnette de réanimation", x: ["Le bus de combat", "Le taxi", "L'ambulance"], acc: ["camionnette de reanimation", "reboot van", "reanimation"] },
  { id: "fortnite-d11", d: 3, t: "Comment s'appelle la banane humanoïde, skin culte de Fortnite ?", a: "Peely", x: ["Meowscles", "Fishstick", "Jonesy"], acc: ["peely"] },
  { id: "fortnite-d12", d: 3, t: "Quel gros cube violet, surnommé Kevin par les joueurs, a marqué la carte ?", a: "Le Cube", x: ["La Comète", "Le Volcan", "L'Iceberg"], acc: ["le cube", "cube", "kevin"] },
  { id: "fortnite-d13", d: 3, t: "En 2020, à la suite d'un litige, de quelle boutique Fortnite a-t-il été retiré ?", a: "L'App Store d'Apple", x: ["Le Play Store", "Steam", "L'Epic Store"], acc: ["app store", "apple", "app store d'apple"] },
  { id: "fortnite-d14", d: 3, t: "Comment nomme-t-on les grands rendez-vous scénarisés qui bouleversent la carte en direct ?", a: "Les événements en direct", x: ["Les mises à jour", "Les tournois", "Les soldes"], acc: ["evenements en direct", "live events", "evenements"] },
  { id: "fortnite-d15", d: 3, t: "Comment appelle-t-on les trois formats d'équipe : seul, à deux ou à quatre ?", a: "Solo, duo et escouade", x: ["Sprint, relais et marathon", "Bronze, argent et or", "Est, ouest et centre"], acc: ["solo duo escouade", "solo duo squad", "escouade"] },
  // --- Pro (20) ---
  { id: "fortnite-p1", d: 4, t: "En quel mois de 2017 le Battle Royale de Fortnite est-il précisément sorti ?", a: "En septembre", x: ["En janvier", "En juin", "En décembre"], acc: ["septembre", "en septembre"] },
  { id: "fortnite-p2", d: 4, t: "Quel événement noir a « aspiré » la carte pendant des jours en 2019 ?", a: "Le Trou Noir", x: ["La Grande Explosion", "L'Éclipse", "Le Tsunami"], acc: ["trou noir", "the black hole", "black hole"] },
  { id: "fortnite-p3", d: 4, t: "Comment s'appelle le retour du mode et de la carte d'origine, lancé fin 2023 ?", a: "Fortnite OG", x: ["Fortnite Classic", "Fortnite Remix", "Fortnite Reload"], acc: ["fortnite og", "og"] },
  { id: "fortnite-p4", d: 4, t: "Quel géant dévoreur de mondes de Marvel fut la vedette d'un événement en 2020 ?", a: "Galactus", x: ["Thanos", "Loki", "Ultron"], acc: ["galactus"] },
  { id: "fortnite-p5", d: 4, t: "Quel chat bodybuildé de Chapitre 2 est un personnage très populaire ?", a: "Meowscles", x: ["Peely", "Fishstick", "Midas"], acc: ["meowscles"] },
  { id: "fortnite-p6", d: 4, t: "Quel DJ a donné le tout premier grand concert virtuel de Fortnite en 2019 ?", a: "Marshmello", x: ["David Guetta", "Travis Scott", "Ariana Grande"], acc: ["marshmello"] },
  { id: "fortnite-p7", d: 4, t: "Quelle chanteuse pop a donné une tournée virtuelle dans Fortnite en 2021 ?", a: "Ariana Grande", x: ["Taylor Swift", "Billie Eilish", "Dua Lipa"], acc: ["ariana grande", "ariana"] },
  { id: "fortnite-p8", d: 4, t: "Quel personnage-poisson maladroit, skin humoristique, est adoré des joueurs ?", a: "Fishstick", x: ["Peely", "Meowscles", "Midas"], acc: ["fishstick"] },
  { id: "fortnite-p9", d: 4, t: "Comment appelle-t-on l'outil qui laisse les joueurs créer leurs propres mondes ?", a: "Le mode Créatif", x: ["Le mode Bac à sable", "Le mode Éditeur", "Le mode Atelier"], acc: ["mode creatif", "creatif", "creative"] },
  { id: "fortnite-p10", d: 4, t: "Quel ninja orange, héros d'un manga, a eu un skin Fortnite dès 2021 ?", a: "Naruto", x: ["Luffy", "Ichigo", "Goku"], acc: ["naruto"] },
  { id: "fortnite-p11", d: 4, t: "Comment appelle-t-on la structure de base construite pour se protéger d'un tir ?", a: "Un mur", x: ["Une tranchée", "Un bouclier magique", "Un dôme"], acc: ["un mur", "mur", "wall"] },
  { id: "fortnite-p12", d: 4, t: "Quel grand tournoi a offert des millions de dollars lors d'une compétition en 2019 ?", a: "La Fortnite World Cup", x: ["Les Jeux olympiques", "La Ligue des étoiles", "Le Grand Chelem"], acc: ["fortnite world cup", "world cup", "coupe du monde fortnite"] },
  { id: "fortnite-p13", d: 4, t: "Quel jeune joueur a remporté le titre en solo de la Coupe du monde 2019 ?", a: "Bugha", x: ["Ninja", "Tfue", "Mongraal"], acc: ["bugha"] },
  { id: "fortnite-p14", d: 4, t: "Comment appelle-t-on la grande division scénaristique qui relance l'univers avec une nouvelle carte ?", a: "Un chapitre", x: ["Un épisode", "Un acte", "Un tome"], acc: ["chapitre", "un chapitre", "chapter"] },
  { id: "fortnite-p15", d: 4, t: "Quel streamer, l'un des premiers visages de Fortnite, a joué en direct avec Drake en 2018 ?", a: "Ninja", x: ["Tfue", "Bugha", "Pokimane"], acc: ["ninja"] },
  { id: "fortnite-p16", d: 4, t: "Quelle danse-emote consiste à balancer les bras de part et d'autre de la taille ?", a: "Le Floss", x: ["Le Moonwalk", "Le Dab", "La Macarena"], acc: ["floss", "le floss"] },
  { id: "fortnite-p17", d: 4, t: "Quelle saga de science-fiction culte a eu droit à des sabres laser dans Fortnite ?", a: "Star Wars", x: ["Star Trek", "Dune", "Halo"], acc: ["star wars"] },
  { id: "fortnite-p18", d: 4, t: "Comment appelle-t-on le personnage de base sans skin, souvent moqué ?", a: "Le personnage par défaut", x: ["Le Bot", "Le Noob royal", "Le Fantôme"], acc: ["par defaut", "default", "personnage par defaut"] },
  { id: "fortnite-p19", d: 4, t: "Quel mode dérivé, façon jeu de rythme musical, a été ajouté fin 2023 ?", a: "Fortnite Festival", x: ["Fortnite Racing", "Fortnite Chess", "Fortnite Poker"], acc: ["fortnite festival", "festival"] },
  { id: "fortnite-p20", d: 4, t: "Contre quelle entreprise Epic Games a-t-il mené un grand procès sur les paiements ?", a: "Apple", x: ["Microsoft", "Sony", "Nintendo"], acc: ["apple"] },
]);
