import { universe } from "../_build";

export const genshin = universe("jeuxvideo", "Genshin Impact", [
  // --- Faciles (5) ---
  { id: "genshin-f1", d: 1, t: "Quel studio a développé Genshin Impact ?", a: "HoYoverse", x: ["Tencent", "Nintendo", "Riot Games"], acc: ["hoyoverse", "mihoyo", "hoyo"] },
  { id: "genshin-f2", d: 1, t: "Genshin Impact est un jeu de quel type, jouable gratuitement ?", a: "Un RPG en monde ouvert", x: ["Un jeu de course", "Un jeu de tir militaire", "Un jeu de foot"], acc: ["rpg", "monde ouvert", "rpg en monde ouvert", "action rpg"] },
  { id: "genshin-f3", d: 1, t: "En quelle année Genshin Impact est-il sorti ?", a: "2020", x: ["2015", "2018", "2023"], acc: ["2020"] },
  { id: "genshin-f4", d: 1, t: "Comment s'appelle le monde dans lequel se déroule Genshin Impact ?", a: "Teyvat", x: ["Hyrule", "Azeroth", "Tamriel"], acc: ["teyvat"] },
  { id: "genshin-f5", d: 1, t: "Comment s'appelle la petite créature volante qui guide le héros ?", a: "Paimon", x: ["Navi", "Fée Clochette", "Kirby"], acc: ["paimon"] },
  // --- Moyennes (10) ---
  { id: "genshin-m1", d: 2, t: "Combien y a-t-il d'éléments principaux dans Genshin Impact ?", a: "7", x: ["4", "5", "10"], acc: ["7", "sept"] },
  { id: "genshin-m2", d: 2, t: "Comment appelle-t-on le héros principal, venu d'un autre monde ?", a: "Le Voyageur", x: ["Le Chevalier", "L'Élu", "Le Nomade"], acc: ["voyageur", "le voyageur", "traveler"] },
  { id: "genshin-m3", d: 2, t: "Comment appelle-t-on le système payant de tirage de personnages au hasard ?", a: "Le gacha", x: ["Le crafting", "Le loot direct", "L'enchère"], acc: ["gacha", "le gacha", "voeux"] },
  { id: "genshin-m4", d: 2, t: "Comment s'appellent les pierres qui donnent leurs pouvoirs élémentaires aux personnages ?", a: "Les Visions", x: ["Les Gemmes", "Les Runes", "Les Cristaux"], acc: ["visions", "les visions", "vision"] },
  { id: "genshin-m5", d: 2, t: "Comment s'appelle la première région du jeu, aux moulins à vent ?", a: "Mondstadt", x: ["Liyue", "Inazuma", "Sumeru"], acc: ["mondstadt", "monstadt"] },
  { id: "genshin-m6", d: 2, t: "Quelle monnaie premium sert à faire des vœux pour obtenir des personnages ?", a: "Les Primogemmes", x: ["Les V-Bucks", "Les Zenys", "Les Mora"], acc: ["primogemmes", "primogems", "primo"] },
  { id: "genshin-m7", d: 2, t: "Comment nomme-t-on les dieux qui règnent sur chaque région ?", a: "Les Archons", x: ["Les Titans", "Les Sages", "Les Rois"], acc: ["archons", "les archons"] },
  { id: "genshin-m8", d: 2, t: "Comment nomme-t-on les combinaisons d'éléments qui créent des effets puissants ?", a: "Les réactions élémentaires", x: ["Les combos", "Les fusions", "Les sorts"], acc: ["reactions elementaires", "reactions", "reaction elementaire"] },
  { id: "genshin-m9", d: 2, t: "Sur quels supports peut-on jouer à Genshin Impact ?", a: "PC, mobile et PlayStation", x: ["Uniquement sur mobile", "Uniquement sur Switch", "Uniquement en arcade"], acc: ["pc mobile playstation", "pc mobile et playstation", "multiplateforme"] },
  { id: "genshin-m10", d: 2, t: "Comment s'appelle la région rocheuse d'inspiration chinoise ?", a: "Liyue", x: ["Mondstadt", "Inazuma", "Fontaine"], acc: ["liyue"] },
  // --- Dures (15) ---
  { id: "genshin-d1", d: 3, t: "Comment s'appellent les jumeaux dont l'un devient le Voyageur ?", a: "Aether et Lumine", x: ["Aether et Paimon", "Zhongli et Venti", "Kaeya et Diluc"], acc: ["aether et lumine", "aether", "lumine"] },
  { id: "genshin-d2", d: 3, t: "Quel élément est associé à la région de Mondstadt ?", a: "L'Anémo, le vent", x: ["Le Géo, la terre", "L'Électro, la foudre", "L'Hydro, l'eau"], acc: ["anemo", "vent", "l'anemo"] },
  { id: "genshin-d3", d: 3, t: "Quel élément est associé à la région de Liyue ?", a: "Le Géo, la terre", x: ["L'Anémo, le vent", "L'Électro", "Le Pyro, le feu"], acc: ["geo", "terre", "le geo"] },
  { id: "genshin-d4", d: 3, t: "Comment s'appelle la région japonisante frappée par la foudre ?", a: "Inazuma", x: ["Sumeru", "Fontaine", "Natlan"], acc: ["inazuma"] },
  { id: "genshin-d5", d: 3, t: "Comment s'appelle l'Archon Anémo, un barde, de Mondstadt ?", a: "Venti", x: ["Zhongli", "Raiden", "Nahida"], acc: ["venti"] },
  { id: "genshin-d6", d: 3, t: "Comment s'appelle l'Archon Géo, sous une élégante apparence humaine ?", a: "Zhongli", x: ["Venti", "Raiden", "Furina"], acc: ["zhongli", "morax"] },
  { id: "genshin-d7", d: 3, t: "Comment s'appelle l'organisation ennemie liée à la nation de Snezhnaya ?", a: "Les Fatui", x: ["L'Abîme", "Les Hilichurls", "La Fondation"], acc: ["fatui", "les fatui"] },
  { id: "genshin-d8", d: 3, t: "Comment s'appellent les ennemis de base, petites créatures masquées et hostiles ?", a: "Les Hilichurls", x: ["Les Slimes", "Les Aranaras", "Les Fatui"], acc: ["hilichurls", "hilichurl"] },
  { id: "genshin-d9", d: 3, t: "Comment appelle-t-on le donjon de fin de jeu par étages, un test de puissance ?", a: "L'Abîme en spirale", x: ["La Tour infinie", "Le Colisée", "Le Labyrinthe"], acc: ["abime en spirale", "spiral abyss", "abime"] },
  { id: "genshin-d10", d: 3, t: "Comment s'appelle la région forestière et désertique, dédiée au savoir ?", a: "Sumeru", x: ["Inazuma", "Fontaine", "Liyue"], acc: ["sumeru"] },
  { id: "genshin-d11", d: 3, t: "Quel élément, lié à la nature, a été ajouté avec la région de Sumeru ?", a: "Le Dendro", x: ["L'Hydro", "Le Cryo", "Le Pyro"], acc: ["dendro", "le dendro"] },
  { id: "genshin-d12", d: 3, t: "Comment s'appelle la région aquatique d'inspiration française ?", a: "Fontaine", x: ["Sumeru", "Natlan", "Inazuma"], acc: ["fontaine"] },
  { id: "genshin-d13", d: 3, t: "Comment s'appelle l'Archon Électro d'Inazuma, à l'allure de shogun ?", a: "Raiden Shogun", x: ["Venti", "Zhongli", "Nahida"], acc: ["raiden", "raiden shogun"] },
  { id: "genshin-d14", d: 3, t: "Comment appelle-t-on les donjons où l'on récupère du butin dans Teyvat ?", a: "Les Domaines", x: ["Les Cavernes", "Les Tours", "Les Failles"], acc: ["domaines", "les domaines", "domaine"] },
  { id: "genshin-d15", d: 3, t: "Que signifie approximativement le nom « Genshin » ?", a: "Dieu originel", x: ["Grand voyage", "Monde parfait", "Étoile filante"], acc: ["dieu originel", "dieu original", "original god"] },
  // --- Pro (20) ---
  { id: "genshin-p1", d: 4, t: "Comment s'appelle l'Archon Dendro de Sumeru, à l'apparence d'une enfant ?", a: "Nahida", x: ["Furina", "Raiden", "Venti"], acc: ["nahida"] },
  { id: "genshin-p2", d: 4, t: "Comment s'appelle l'Archon Hydro de Fontaine, théâtrale et populaire ?", a: "Furina", x: ["Nahida", "Raiden", "Mona"], acc: ["furina"] },
  { id: "genshin-p3", d: 4, t: "Comment appelle-t-on les puissants agents d'élite des Fatui ?", a: "Les Onze Fatui", x: ["Les Neuf Sages", "Les Douze Chevaliers", "Les Sept Rois"], acc: ["onze fatui", "harbingers", "fatui harbingers"] },
  { id: "genshin-p4", d: 4, t: "Quel Fatui, aussi appelé Childe, est un boss maniant l'Hydro ?", a: "Tartaglia", x: ["Scaramouche", "La Signora", "Dottore"], acc: ["tartaglia", "childe"] },
  { id: "genshin-p5", d: 4, t: "Comment s'appelle la petite pyromane espiègle de Mondstadt, adepte des explosions ?", a: "Klee", x: ["Amber", "Barbara", "Noelle"], acc: ["klee"] },
  { id: "genshin-p6", d: 4, t: "Comment s'appelle le riche héritier de Mondstadt, maître du Pyro et justicier de nuit ?", a: "Diluc", x: ["Kaeya", "Zhongli", "Childe"], acc: ["diluc"] },
  { id: "genshin-p7", d: 4, t: "Comment s'appelle la directrice espiègle des pompes funèbres de Liyue, une Pyro ?", a: "Hu Tao", x: ["Ganyu", "Keqing", "Xiangling"], acc: ["hu tao", "hutao"] },
  { id: "genshin-p8", d: 4, t: "Comment s'appelle l'astrologue Hydro qui se dit toujours fauchée ?", a: "Mona", x: ["Lisa", "Barbara", "Ningguang"], acc: ["mona"] },
  { id: "genshin-p9", d: 4, t: "Comment surnomme-t-on Paimon dans un mème, à cause de son nom ?", a: "De la nourriture d'urgence", x: ["Un porte-bonheur", "Un GPS vivant", "Un doudou"], acc: ["nourriture d'urgence", "emergency food"] },
  { id: "genshin-p10", d: 4, t: "Quel élément est associé à la nation de feu Natlan ?", a: "Le Pyro, le feu", x: ["Le Cryo", "L'Hydro", "L'Anémo"], acc: ["pyro", "feu", "le pyro"] },
  { id: "genshin-p11", d: 4, t: "Quel élément régira la nation encore attendue de Snezhnaya ?", a: "Le Cryo, la glace", x: ["Le Pyro", "Le Dendro", "Le Géo"], acc: ["cryo", "glace", "le cryo"] },
  { id: "genshin-p12", d: 4, t: "Comment s'appelle le royaume céleste des dieux, dans le ciel de Teyvat ?", a: "Céleste", x: ["Valhalla", "L'Olympe", "L'Abîme"], acc: ["celeste", "célestia", "celestia"] },
  { id: "genshin-p13", d: 4, t: "Quel autre grand jeu de miHoYo, spatial, est sorti après Genshin ?", a: "Honkai: Star Rail", x: ["Fate/Grand Order", "Arknights", "Azur Lane"], acc: ["honkai star rail", "star rail", "honkai"] },
  { id: "genshin-p14", d: 4, t: "Comment appelle-t-on la réaction qui explose en mêlant Électro et Pyro ?", a: "La Surcharge", x: ["La Vaporisation", "La Fonte", "Le Gel"], acc: ["surcharge", "overload"] },
  { id: "genshin-p15", d: 4, t: "Comment appelle-t-on la réaction Hydro et Pyro qui amplifie fortement les dégâts ?", a: "La Vaporisation", x: ["La Surcharge", "L'Électro-conduction", "La Cristallisation"], acc: ["vaporisation", "vaporize"] },
  { id: "genshin-p16", d: 4, t: "Comment s'appelle le samouraï errant à l'Anémo, allié du Voyageur à Inazuma ?", a: "Kazuha", x: ["Ayato", "Thoma", "Itto"], acc: ["kazuha"] },
  { id: "genshin-p17", d: 4, t: "Comment s'appelle l'archère Cryo de Liyue, mi-humaine mi-qilin, très prisée ?", a: "Ganyu", x: ["Keqing", "Xingqiu", "Ningguang"], acc: ["ganyu"] },
  { id: "genshin-p18", d: 4, t: "Comment appelle-t-on les statues qui offrent les pouvoirs élémentaires en explorant ?", a: "Les Statues des Sept", x: ["Les Autels", "Les Totems", "Les Bornes"], acc: ["statues des sept", "statue des sept"] },
  { id: "genshin-p19", d: 4, t: "Quel Fatui-marionnette, un temps privé de sa Vision, devient une figure marquante ?", a: "Scaramouche", x: ["Tartaglia", "Dottore", "Pantalone"], acc: ["scaramouche", "wanderer"] },
  { id: "genshin-p20", d: 4, t: "Genshin Impact est l'un des jeux les plus rentables de quelle catégorie ?", a: "Les jeux mobiles", x: ["Les jeux de plateau", "Les jeux de casino", "Les jeux VR"], acc: ["jeux mobiles", "mobile", "jeu mobile"] },
]);
