import { universe } from "../_build";

export const gta = universe("jeuxvideo", "GTA", [
  // --- Faciles (5) ---
  { id: "gta-f1", d: 1, t: "Quel studio développe la série Grand Theft Auto ?", a: "Rockstar Games", acc: ["rockstar", "rockstar games"], x: ["Ubisoft", "EA", "Activision"] },
  { id: "gta-f2", d: 1, t: "Que signifie littéralement « Grand Theft Auto » ?", a: "Vol de voiture", acc: ["vol de voiture", "vol de vehicule", "car theft"], x: ["Grande course", "Grand vol à main armée", "Auto-école"] },
  { id: "gta-f3", d: 1, t: "À quel type de jeu appartient GTA ?", a: "Action-aventure en monde ouvert", acc: ["monde ouvert", "open world", "action-aventure"], x: ["Jeu de tir spatial", "Jeu de gestion", "Jeu de plateforme"] },
  { id: "gta-f4", d: 1, t: "Que voit-on apparaître à l'écran quand on commet des crimes dans GTA ?", a: "Des étoiles de recherche", acc: ["etoiles", "étoiles", "niveau de recherche", "police"], x: ["Des cœurs", "Des pièces", "Des clés"] },
  { id: "gta-f5", d: 1, t: "Comment s'appelle la grande ville de GTA V et de GTA San Andreas ?", a: "Los Santos", acc: ["los santos"], x: ["Liberty City", "Vice City", "Las Venturas"] },

  // --- Moyennes (10) ---
  { id: "gta-m1", d: 2, t: "De quelle ville réelle Liberty City s'inspire-t-elle ?", a: "New York", acc: ["new york", "nyc"], x: ["Los Angeles", "Miami", "Chicago"] },
  { id: "gta-m2", d: 2, t: "De quelle ville réelle Vice City s'inspire-t-elle ?", a: "Miami", acc: ["miami"], x: ["New York", "Las Vegas", "Los Angeles"] },
  { id: "gta-m3", d: 2, t: "De quelle ville réelle Los Santos s'inspire-t-il ?", a: "Los Angeles", acc: ["los angeles", "la"], x: ["Miami", "New York", "Chicago"] },
  { id: "gta-m4", d: 2, t: "Combien de personnages jouables principaux compte GTA V ?", a: "3", acc: ["3", "trois"], x: ["1", "2", "5"] },
  { id: "gta-m5", d: 2, t: "Comment s'appelle le mode en ligne massivement joué de GTA V ?", a: "GTA Online", acc: ["gta online", "online"], x: ["GTA World", "GTA Multi", "San Andreas Online"] },
  { id: "gta-m6", d: 2, t: "En quelle année est sorti GTA V ?", a: "2013", x: ["2011", "2015", "2009"] },
  { id: "gta-m7", d: 2, t: "Dans quel État fictif se déroule GTA V ?", a: "San Andreas", acc: ["san andreas"], x: ["Liberty", "Vice", "Leonida"] },
  { id: "gta-m8", d: 2, t: "Quel jeu culte de western vient aussi du studio de GTA ?", a: "Red Dead Redemption", acc: ["red dead redemption", "red dead"], x: ["Mafia", "Sleeping Dogs", "Watch Dogs"] },
  { id: "gta-m9", d: 2, t: "Comment appelle-t-on les gros casses scénarisés, centraux dans GTA V ?", a: "Les braquages", acc: ["heists", "braquages", "braquage", "heist"], x: ["Les raids", "Les contrats", "Les livraisons"] },
  { id: "gta-m10", d: 2, t: "Quelle décennie sert de cadre à GTA Vice City ?", a: "Les années 1980", acc: ["annees 80", "années 80", "1980s", "eighties"], x: ["Les années 1970", "Les années 1990", "Les années 2000"] },

  // --- Dures (15) ---
  { id: "gta-d1", d: 3, t: "Comment s'appellent les trois héros de GTA V ?", a: "Michael, Franklin et Trevor", acc: ["michael franklin trevor", "michael", "franklin", "trevor"], x: ["Niko, Roman, Little Jacob", "Tommy, Lance, Ken", "CJ, Sweet, Ryder"] },
  { id: "gta-d2", d: 3, t: "Comment s'appelle le héros de GTA San Andreas ?", a: "Carl Johnson", acc: ["carl johnson", "cj", "carl"], x: ["Tommy Vercetti", "Niko Bellic", "Franklin"] },
  { id: "gta-d3", d: 3, t: "Comment s'appelle le héros de GTA Vice City ?", a: "Tommy Vercetti", acc: ["tommy vercetti", "tommy", "vercetti"], x: ["Carl Johnson", "Niko Bellic", "Claude"] },
  { id: "gta-d4", d: 3, t: "Comment s'appelle le héros immigré de GTA IV, venu d'Europe de l'Est ?", a: "Niko Bellic", acc: ["niko bellic", "niko", "bellic"], x: ["Roman", "Tommy", "CJ"] },
  { id: "gta-d5", d: 3, t: "En quelle année est sorti GTA III, premier de la série en 3D ?", a: "2001", x: ["1999", "2003", "2005"] },
  { id: "gta-d6", d: 3, t: "Comment s'appelle le gang de CJ dans San Andreas ?", a: "Grove Street", acc: ["grove street", "grove street families", "families"], x: ["Les Ballas", "Les Vagos", "Les Aztecas"] },
  { id: "gta-d7", d: 3, t: "Quel acteur célèbre a prêté sa voix à Tommy Vercetti dans Vice City ?", a: "Ray Liotta", acc: ["ray liotta", "liotta"], x: ["Al Pacino", "Robert De Niro", "Samuel L. Jackson"] },
  { id: "gta-d8", d: 3, t: "Quel ami corpulent trahit CJ dans San Andreas ?", a: "Big Smoke", acc: ["big smoke", "smoke"], x: ["Ryder", "Sweet", "Cesar"] },
  { id: "gta-d9", d: 3, t: "Comment s'appelle le studio qui a créé le premier GTA en 1997 ?", a: "DMA Design", acc: ["dma design", "dma"], x: ["Rockstar North", "Team Bondi", "Angel Studios"] },
  { id: "gta-d10", d: 3, t: "Comment s'appelle le chien de Franklin dans GTA V ?", a: "Chop", acc: ["chop"], x: ["Rex", "Bull", "Rocky"] },
  { id: "gta-d11", d: 3, t: "Quel héros de GTA V est un ex-braqueur placé sous protection des témoins ?", a: "Michael", acc: ["michael", "michael de santa"], x: ["Trevor", "Franklin", "Lester"] },
  { id: "gta-d12", d: 3, t: "Quel héros de GTA V est un trafiquant instable et violent ?", a: "Trevor", acc: ["trevor", "trevor philips"], x: ["Michael", "Franklin", "Lamar"] },
  { id: "gta-d13", d: 3, t: "Comment s'appelle le génie du piratage qui planifie les braquages dans GTA V ?", a: "Lester", acc: ["lester"], x: ["Lamar", "Ron", "Dave"] },
  { id: "gta-d14", d: 3, t: "Quel gang rival affronte les Grove Street dans San Andreas ?", a: "Les Ballas", acc: ["ballas"], x: ["Les Vagos", "Les Triades", "Les Aztecas"] },
  { id: "gta-d15", d: 3, t: "Quel acteur double le flic corrompu Tenpenny dans San Andreas ?", a: "Samuel L. Jackson", acc: ["samuel l jackson", "samuel jackson", "jackson"], x: ["Ray Liotta", "Denzel Washington", "Ice-T"] },

  // --- Pro (20) ---
  { id: "gta-p1", d: 4, t: "Comment s'appelle le cousin de Niko dans GTA IV, fan de bowling ?", a: "Roman", acc: ["roman", "roman bellic"], x: ["Little Jacob", "Brucie", "Packie"] },
  { id: "gta-p2", d: 4, t: "Comment s'appelle le héros de GTA III ?", a: "Claude", x: ["Niko", "Tommy", "Carl"] },
  { id: "gta-p3", d: 4, t: "Quel est le nom de famille de Michael dans GTA V ?", a: "De Santa", acc: ["de santa", "michael de santa"], x: ["Clinton", "Philips", "Bellic"] },
  { id: "gta-p4", d: 4, t: "Quel est le nom de famille de Franklin dans GTA V ?", a: "Clinton", acc: ["clinton", "franklin clinton"], x: ["De Santa", "Philips", "Johnson"] },
  { id: "gta-p5", d: 4, t: "Dans quel État fictif se déroulera GTA VI ?", a: "Leonida", acc: ["leonida"], x: ["San Andreas", "Liberty", "Alderney"] },
  { id: "gta-p6", d: 4, t: "Comment s'appelle l'héroïne principale de GTA VI, première femme protagoniste ?", a: "Lucia", x: ["Bonnie", "Catalina", "Michelle"] },
  { id: "gta-p7", d: 4, t: "Quelle ville est au cœur de GTA VI ?", a: "Vice City", acc: ["vice city"], x: ["Liberty City", "Los Santos", "Las Venturas"] },
  { id: "gta-p8", d: 4, t: "GTA V est l'un des produits de divertissement les plus rentables : combien d'exemplaires environ ?", a: "Plus de 190 millions", acc: ["190 millions", "plus de 190 millions", "200 millions"], x: ["10 millions", "50 millions", "1 milliard"] },
  { id: "gta-p9", d: 4, t: "Comment s'appelle la ville de San Andreas inspirée de Las Vegas ?", a: "Las Venturas", acc: ["las venturas"], x: ["San Fierro", "Los Santos", "Vice City"] },
  { id: "gta-p10", d: 4, t: "Comment s'appelle la ville de San Andreas inspirée de San Francisco ?", a: "San Fierro", acc: ["san fierro"], x: ["Las Venturas", "Los Santos", "Liberty City"] },
  { id: "gta-p11", d: 4, t: "Quel ami d'enfance exubérant accompagne Franklin dans GTA V ?", a: "Lamar", acc: ["lamar"], x: ["Lester", "Michael", "Trevor"] },
  { id: "gta-p12", d: 4, t: "Comment s'appelle la femme de Michael dans GTA V ?", a: "Amanda", x: ["Tracey", "Michelle", "Karen"] },
  { id: "gta-p13", d: 4, t: "Quel baron de la drogue Tommy renverse-t-il pour s'emparer de son manoir dans Vice City ?", a: "Ricardo Diaz", acc: ["ricardo diaz", "diaz"], x: ["Sonny Forelli", "Lance Vance", "Ken Rosenberg"] },
  { id: "gta-p14", d: 4, t: "Qui trahit Tommy vers la fin de Vice City ?", a: "Lance Vance", acc: ["lance vance", "lance"], x: ["Ricardo Diaz", "Ken Rosenberg", "Sonny Forelli"] },
  { id: "gta-p15", d: 4, t: "Quel grand frère de CJ dirige les Grove Street dans San Andreas ?", a: "Sweet", acc: ["sweet", "sean johnson"], x: ["Ryder", "Big Smoke", "Cesar"] },
  { id: "gta-p16", d: 4, t: "En quelle année la première bande-annonce de GTA VI est-elle sortie ?", a: "2023", acc: ["2023", "decembre 2023", "décembre 2023"], x: ["2021", "2022", "2024"] },
  { id: "gta-p17", d: 4, t: "Quelle réplique culte Roman répète-t-il pour inviter Niko à sortir dans GTA IV ?", a: "« Let's go bowling ! »", acc: ["bowling", "let's go bowling", "allons au bowling"], x: ["« Follow the train »", "« Ah shit, here we go again »", "« Wasted »"] },
  { id: "gta-p18", d: 4, t: "Quel message s'affiche à l'écran quand le personnage meurt dans GTA ?", a: "Wasted", acc: ["wasted"], x: ["Busted", "Game Over", "You Died"] },
  { id: "gta-p19", d: 4, t: "Quel message s'affiche quand la police vous attrape dans GTA ?", a: "Busted", acc: ["busted"], x: ["Wasted", "Arrested", "Game Over"] },
  { id: "gta-p20", d: 4, t: "Quel autre grand jeu Rockstar suit un cow-boy nommé Arthur Morgan ?", a: "Red Dead Redemption 2", acc: ["red dead redemption 2", "red dead 2", "rdr2"], x: ["GTA IV", "Bully", "Max Payne 3"] },
]);
