import { universe } from "../_build";

export const hades = universe("jeuxvideo", "Hades", [
  // --- Faciles (5) ---
  { id: "hades-f1", d: 1, t: "À quel genre appartient le jeu Hades ?", a: "Le rogue-like", x: ["La course", "Le jeu de rythme", "La gestion de ferme"], acc: ["rogue-like", "roguelike"] },
  { id: "hades-f2", d: 1, t: "Quel studio a développé Hades ?", a: "Supergiant Games", x: ["Team Cherry", "Motion Twin", "ConcernedApe"], acc: ["supergiant", "supergiant games"] },
  { id: "hades-f3", d: 1, t: "Comment se nomme le prince héros qui tente de fuir les Enfers ?", a: "Zagreus", x: ["Hadès", "Zeus", "Thanatos"], acc: ["zagreus", "zag"] },
  { id: "hades-f4", d: 1, t: "De quelle mythologie Hades s'inspire-t-il ?", a: "La mythologie grecque", x: ["La mythologie nordique", "La mythologie égyptienne", "La mythologie japonaise"], acc: ["grecque", "mythologie grecque"] },
  { id: "hades-f5", d: 1, t: "Quel est le but de Zagreus dans le jeu ?", a: "S'échapper des Enfers", x: ["Conquérir l'Olympe", "Sauver une princesse", "Bâtir une cité"], acc: ["s'echapper des enfers", "fuir les enfers"] },
  // --- Moyennes (10) ---
  { id: "hades-m1", d: 2, t: "De quel dieu Zagreus est-il le fils ?", a: "Hadès", x: ["Zeus", "Poséidon", "Arès"], acc: ["hades", "hadès"] },
  { id: "hades-m2", d: 2, t: "Que donnent les dieux de l'Olympe à Zagreus au fil de sa fuite ?", a: "Des faveurs", x: ["Des malédictions", "De l'argent réel", "Des cartes à collectionner"], acc: ["faveurs", "boons"] },
  { id: "hades-m3", d: 2, t: "Quelle est la première région traversée en quittant la maison d'Hadès ?", a: "Le Tartare", x: ["L'Élysée", "L'Asphodèle", "Le Styx"], acc: ["tartare"] },
  { id: "hades-m4", d: 2, t: "Quel chien à trois têtes garde les Enfers et peut être caressé ?", a: "Cerbère", x: ["Fluffy", "Garm", "Orthos"], acc: ["cerbere", "cerbère"] },
  { id: "hades-m5", d: 2, t: "Quel batelier des Enfers tient la boutique du jeu ?", a: "Charon", x: ["Hermès", "Thanatos", "Hypnos"], acc: ["charon"] },
  { id: "hades-m6", d: 2, t: "Comment appelle-t-on les six armes légendaires maniées par Zagreus ?", a: "Les Armes infernales", x: ["Les Lames d'Olympe", "Les Reliques du Styx", "Les Foudres divines"], acc: ["armes infernales"] },
  { id: "hades-m7", d: 2, t: "Que se passe-t-il à chaque mort de Zagreus ?", a: "Il revient à la maison d'Hadès", x: ["La partie est finie pour de bon", "Il perd toute sa progression", "Il change de personnage"], acc: ["revient a la maison"] },
  { id: "hades-m8", d: 2, t: "Quel musicien légendaire chante dans la maison d'Hadès ?", a: "Orphée", x: ["Achille", "Sisyphe", "Thésée"], acc: ["orphee", "orphée"] },
  { id: "hades-m9", d: 2, t: "Quel héros de la guerre de Troie sert de mentor à Zagreus ?", a: "Achille", x: ["Thésée", "Ulysse", "Hector"], acc: ["achille"] },
  { id: "hades-m10", d: 2, t: "En quelle année Hades est-il sorti en version complète ?", a: "2020", x: ["2016", "2018", "2022"], acc: ["2020"] },
  // --- Dures (15) ---
  { id: "hades-d1", d: 3, t: "Quelle déesse, sa mère disparue, Zagreus cherche-t-il à rejoindre en surface ?", a: "Perséphone", x: ["Nyx", "Déméter", "Aphrodite"], acc: ["persephone", "perséphone"] },
  { id: "hades-d2", d: 3, t: "Quelle déesse primordiale de la Nuit a élevé Zagreus ?", a: "Nyx", x: ["Perséphone", "Héra", "Gaïa"], acc: ["nyx"] },
  { id: "hades-d3", d: 3, t: "Quelle incarnation de la Mort, proche de Zagreus, compte ses ennemis vaincus ?", a: "Thanatos", x: ["Hypnos", "Charon", "Hermès"], acc: ["thanatos"] },
  { id: "hades-d4", d: 3, t: "Quel dieu du Sommeil accueille Zagreus à chaque retour à la maison ?", a: "Hypnos", x: ["Thanatos", "Charon", "Orphée"], acc: ["hypnos"] },
  { id: "hades-d5", d: 3, t: "Quelle Furie, ancienne compagne de Zagreus, est le premier boss du Tartare ?", a: "Mégère", x: ["Alecto", "Tisiphone", "Dusa"], acc: ["megere", "mégère", "megaera"] },
  { id: "hades-d6", d: 3, t: "Quelle région couverte de lave succède au Tartare ?", a: "L'Asphodèle", x: ["L'Élysée", "Le Temple du Styx", "L'Olympe"], acc: ["asphodele", "asphodèle"] },
  { id: "hades-d7", d: 3, t: "Quels deux champions, un roi et un Minotaure, gardent l'Élysée ?", a: "Thésée et Astérios", x: ["Achille et Patrocle", "Castor et Pollux", "Orphée et Eurydice"], acc: ["thesee et asterios", "thesee et asterion"] },
  { id: "hades-d8", d: 3, t: "Qui affronte-t-on comme boss final, gardant la sortie des Enfers ?", a: "Hadès", x: ["Zeus", "Thanatos", "Chronos"], acc: ["hades", "hadès"] },
  { id: "hades-d9", d: 3, t: "Comment se nomme l'épée de base, la lame Stygienne ?", a: "Stygius", x: ["Varatha", "Coronacht", "Aegis"], acc: ["stygius"] },
  { id: "hades-d10", d: 3, t: "Quelle arme infernale est un bouclier que l'on peut lancer ?", a: "Aegis", x: ["Stygius", "Coronacht", "Malphon"], acc: ["aegis"] },
  { id: "hades-d11", d: 3, t: "Quel objet de sa chambre permet à Zagreus d'acheter des améliorations permanentes ?", a: "Le Miroir de la Nuit", x: ["La Forge", "L'Autel", "La Fontaine"], acc: ["miroir de la nuit", "miroir"] },
  { id: "hades-d12", d: 3, t: "Quel breuvage offre-t-on aux personnages pour gagner leur affection ?", a: "Le nectar", x: ["L'ambroisie", "Le vin", "L'hydromel"], acc: ["nectar"] },
  { id: "hades-d13", d: 3, t: "Quelle tête de gorgone travaille comme servante dans la maison d'Hadès ?", a: "Dusa", x: ["Méduse", "Nyx", "Eurydice"], acc: ["dusa"] },
  { id: "hades-d14", d: 3, t: "Quel squelette sert de mannequin d'entraînement à Zagreus ?", a: "Skelly", x: ["Sisyphe", "Charon", "Hypnos"], acc: ["skelly"] },
  { id: "hades-d15", d: 3, t: "Quel condamné à rouler éternellement son rocher Zagreus croise-t-il ?", a: "Sisyphe", x: ["Tantale", "Prométhée", "Ixion"], acc: ["sisyphe"] },
  // --- Pro (20) ---
  { id: "hades-p1", d: 4, t: "Quel compositeur signe la bande-son de Hades, dont le thème « In the Blood » ?", a: "Darren Korb", x: ["Austin Wintory", "Toby Fox", "Lena Raine"], acc: ["darren korb", "korb"] },
  { id: "hades-p2", d: 4, t: "Hades est le premier jeu vidéo à remporter quel prix de science-fiction ?", a: "Le prix Hugo", x: ["Le prix Nebula", "Le prix Pulitzer", "Le prix Goncourt"], acc: ["prix hugo", "hugo"] },
  { id: "hades-p3", d: 4, t: "Comment se nomme l'arc de Zagreus ?", a: "Coronacht", x: ["Varatha", "Malphon", "Exagryph"], acc: ["coronacht"] },
  { id: "hades-p4", d: 4, t: "Quelle arme infernale est une lance nommée Varatha ?", a: "Varatha", x: ["Stygius", "Aegis", "Malphon"], acc: ["varatha"] },
  { id: "hades-p5", d: 4, t: "Comment se nomment les poings jumeaux, arme de corps à corps rapide ?", a: "Malphon", x: ["Coronacht", "Exagryph", "Varatha"], acc: ["malphon"] },
  { id: "hades-p6", d: 4, t: "Quelle arme à feu, le rail d'adamant, complète l'arsenal de Zagreus ?", a: "Exagryph", x: ["Coronacht", "Stygius", "Aegis"], acc: ["exagryph"] },
  { id: "hades-p7", d: 4, t: "Quelle ressource rouge sert à débloquer les aspects des armes ?", a: "Le sang de Titan", x: ["Le nectar", "Les diamants", "L'obole"], acc: ["sang de titan"] },
  { id: "hades-p8", d: 4, t: "Quel « pacte » permet d'augmenter la difficulté contre de meilleures récompenses ?", a: "Le Pacte de Châtiment", x: ["Le Pacte de Sang", "Le Pacte d'Olympe", "Le Serment du Styx"], acc: ["pacte de chatiment", "pacte de châtiment"] },
  { id: "hades-p9", d: 4, t: "Perséphone, la mère de Zagreus, est la fille de quelle déesse des moissons ?", a: "Déméter", x: ["Héra", "Nyx", "Aphrodite"], acc: ["demeter", "déméter"] },
  { id: "hades-p10", d: 4, t: "Quelle nymphe, épouse d'Orphée, tient une clairière en Asphodèle ?", a: "Eurydice", x: ["Dusa", "Mégère", "Perséphone"], acc: ["eurydice"] },
  { id: "hades-p11", d: 4, t: "Quel monstre à plusieurs têtes est le boss de l'Asphodèle ?", a: "L'Hydre", x: ["Le Minotaure", "Le Cyclope", "La Chimère"], acc: ["hydre", "l'hydre"] },
  { id: "hades-p12", d: 4, t: "Combien de Furies différentes peuvent garder le Tartare ?", a: "Trois", x: ["Une", "Deux", "Cinq"], acc: ["3", "trois"] },
  { id: "hades-p13", d: 4, t: "Quelle monnaie, l'obole, sert aux achats de Charon durant une tentative ?", a: "L'obole", x: ["Le nectar", "Le sang de Titan", "Le diamant"], acc: ["obole"] },
  { id: "hades-p14", d: 4, t: "Quelle chanteuse interprète la chanson-thème « In the Blood » ?", a: "Ashley Barrett", x: ["Lena Raine", "Björk", "Florence Welch"], acc: ["ashley barrett", "barrett"] },
  { id: "hades-p15", d: 4, t: "Quelle princesse, sœur de Zagreus, est l'héroïne de Hades II ?", a: "Mélinoé", x: ["Perséphone", "Nyx", "Dusa"], acc: ["melinoe", "mélinoé"] },
  { id: "hades-p16", d: 4, t: "Quel Titan du Temps est le grand ennemi de Hades II ?", a: "Chronos", x: ["Hadès", "Zeus", "Thanatos"], acc: ["chronos"] },
  { id: "hades-p17", d: 4, t: "Quel jeu, aussi de Supergiant, a précédé Hades avec un narrateur culte ?", a: "Bastion", x: ["Celeste", "Dead Cells", "Cuphead"], acc: ["bastion"] },
  { id: "hades-p18", d: 4, t: "Quel type de faveur, réservé à un seul dieu à la fois, est le plus rare et puissant ?", a: "La faveur Légendaire", x: ["La faveur Commune", "La faveur Rare", "La faveur Épique"], acc: ["legendaire", "légendaire"] },
  { id: "hades-p19", d: 4, t: "Comment appelle-t-on une faveur combinant les pouvoirs de deux dieux ?", a: "Une faveur Duo", x: ["Une faveur Solo", "Une faveur Trio", "Une faveur Chaos"], acc: ["duo", "faveur duo"] },
  { id: "hades-p20", d: 4, t: "Quelle divinité primordiale offre des faveurs puissantes après un malus temporaire ?", a: "Chaos", x: ["Nyx", "Érèbe", "Éther"], acc: ["chaos"] },
]);
