import { universe } from "../_build";

export const kingdomcome = universe("jeuxvideo", "Kingdom Come Deliverance", [
  // --- Faciles (5) ---
  { id: "kcd-f1", d: 1, t: "Quel studio tchèque a développé Kingdom Come Deliverance ?", a: "Warhorse Studios", x: ["CD Projekt Red", "Bethesda", "Ubisoft"], acc: ["warhorse"] },
  { id: "kcd-f2", d: 1, t: "Comment se prénomme le héros que l'on incarne dans le jeu ?", a: "Henri", x: ["Radzig", "Hans", "Godwin"], acc: ["henry", "henri"] },
  { id: "kcd-f3", d: 1, t: "Quel est le métier du père du héros au début de l'aventure ?", a: "Forgeron", x: ["Meunier", "Boulanger", "Charpentier"] },
  { id: "kcd-f4", d: 1, t: "Dans quelle région d'Europe centrale se déroule le jeu ?", a: "La Bohême", x: ["La Bavière", "La Saxe", "La Silésie"], acc: ["boheme", "bohême"] },
  { id: "kcd-f5", d: 1, t: "À quel genre de jeu appartient Kingdom Come Deliverance ?", a: "Un jeu de rôle", x: ["Un jeu de course", "Un jeu de tir", "Un jeu de plateforme"], acc: ["rpg", "jeu de role"] },
  // --- Moyennes (10) ---
  { id: "kcd-m1", d: 2, t: "Quelle ville natale d'Henri est mise à sac au début du jeu ?", a: "Skalitz", x: ["Rattay", "Sasau", "Talmberg"] },
  { id: "kcd-m2", d: 2, t: "Les troupes de quel roi ravagent Skalitz au début de l'histoire ?", a: "Sigismond", x: ["Venceslas", "Ottokar", "Vladislav"], acc: ["sigismond"] },
  { id: "kcd-m3", d: 2, t: "Quels guerriers nomades servent de mercenaires à l'armée d'invasion ?", a: "Les Coumans", x: ["Les Vikings", "Les Huns", "Les Mongols"], acc: ["coumans", "cumans"] },
  { id: "kcd-m4", d: 2, t: "Quel seigneur commande la garnison de Skalitz et prend Henri à son service ?", a: "Radzig Kobyla", x: ["Hanush de Leipa", "Divish de Talmberg", "Istvan Toth"], acc: ["radzig"] },
  { id: "kcd-m5", d: 2, t: "Quel jeune noble turbulent et vantard devient l'ami d'Henri ?", a: "Hans Capon", x: ["Divish de Talmberg", "Hanush de Leipa", "Markvart d'Aulitz"], acc: ["hans capon", "capon"] },
  { id: "kcd-m6", d: 2, t: "Quelle eau-de-vie permet à Henri de sauvegarder sa partie ?", a: "L'eau-de-vie du Sauveur", x: ["L'hydromel", "La cervoise", "Le vin de messe"], acc: ["eau-de-vie du sauveur", "saviour schnapps", "schnaps du sauveur"] },
  { id: "kcd-m7", d: 2, t: "Quelle jeune femme rescapée de Skalitz devient l'amour d'Henri ?", a: "Thérèse", x: ["Bianca", "Ludmila", "Stéphanie"], acc: ["therese", "thérèse", "theresa"] },
  { id: "kcd-m8", d: 2, t: "Dans quelle ville Henri sert-il les seigneurs Divish et Hanush ?", a: "Rattay", x: ["Skalitz", "Sasau", "Uzhitz"] },
  { id: "kcd-m9", d: 2, t: "Quel monastère Henri doit-il infiltrer en se faisant passer pour un novice ?", a: "Sasau", x: ["Talmberg", "Rattay", "Uzhitz"] },
  { id: "kcd-m10", d: 2, t: "En quelle année se déroule l'intrigue du jeu ?", a: "1403", x: ["1348", "1466", "1517"] },
  // --- Dures (15) ---
  { id: "kcd-d1", d: 3, t: "Quel roi de Bohême, capturé, est retenu prisonnier par Sigismond ?", a: "Venceslas IV", x: ["Charles IV", "Ottokar II", "Vladislav II"], acc: ["venceslas iv", "venceslas"] },
  { id: "kcd-d2", d: 3, t: "Quel lien de parenté unit Sigismond au roi Venceslas IV ?", a: "Son demi-frère", x: ["Son fils", "Son oncle", "Son cousin"] },
  { id: "kcd-d3", d: 3, t: "Comment se prénomme le père forgeron d'Henri ?", a: "Martin", x: ["Radzig", "Kunesh", "Théobald"] },
  { id: "kcd-d4", d: 3, t: "Quel seigneur accueille les rescapés de Skalitz dans son château fort ?", a: "Divish de Talmberg", x: ["Hanush de Leipa", "Radzig Kobyla", "Markvart d'Aulitz"], acc: ["divish", "divish de talmberg"] },
  { id: "kcd-d5", d: 3, t: "Quel chevalier hongrois est le cerveau du raid meurtrier sur Skalitz ?", a: "Istvan Toth", x: ["Markvart d'Aulitz", "Divish de Talmberg", "Hanush de Leipa"], acc: ["toth", "istvan toth"] },
  { id: "kcd-d6", d: 3, t: "Quel colosse bandit menait l'assaut en arborant l'épée du père d'Henri ?", a: "Runt", x: ["Toth", "Markvart", "Kunesh"] },
  { id: "kcd-d7", d: 3, t: "Quel camp fortifié caché dans les bois sert de repaire aux hommes de Toth ?", a: "Vranik", x: ["Pribyslavitz", "Ledetchko", "Merhojed"] },
  { id: "kcd-d8", d: 3, t: "Quelle compétence permet de préparer des potions à l'établi en suivant des recettes ?", a: "L'alchimie", x: ["La forge", "La vénerie", "Le crochetage"], acc: ["alchimie"] },
  { id: "kcd-d9", d: 3, t: "Quel capitaine d'armes entraîne Henri au combat à Rattay ?", a: "Le capitaine Bernard", x: ["Le sergent Matthias", "Le maître Feyfar", "Le capitaine Robard"], acc: ["bernard", "capitaine bernard"] },
  { id: "kcd-d10", d: 3, t: "Quel meunier de Rattay initie Henri au crochetage et au vol ?", a: "Peshek", x: ["Kunesh", "Feyfar", "Godwin"] },
  { id: "kcd-d11", d: 3, t: "Auprès de quel voisin ivrogne Henri recouvre-t-il une dette au tout début ?", a: "Kunesh", x: ["Peshek", "Zora", "Bianca"] },
  { id: "kcd-d12", d: 3, t: "Quel prêtre d'Uzhitz, porté sur la boisson, aide malgré tout Henri ?", a: "Le père Godwin", x: ["Le père Simon", "Le frère Nicodème", "L'abbé Thomas"], acc: ["godwin", "père godwin"] },
  { id: "kcd-d13", d: 3, t: "Quelle ressource précieuse extraite à Skalitz attise la convoitise de l'envahisseur ?", a: "L'argent", x: ["L'or", "Le fer", "Le sel"], acc: ["argent"] },
  { id: "kcd-d14", d: 3, t: "Quel village en ruines les bandits transforment-ils en repaire au fil de l'aventure ?", a: "Pribyslavitz", x: ["Ledetchko", "Neuhof", "Merhojed"] },
  { id: "kcd-d15", d: 3, t: "Quelle plante à fleur jaune sert de base à la décoction de soin la plus courante ?", a: "Le souci", x: ["La camomille", "L'ortie", "La belladone"], acc: ["souci"] },
  // --- Pro (20) ---
  { id: "kcd-p1", d: 4, t: "En quelle année Kingdom Come Deliverance est-il sorti ?", a: "2018", x: ["2015", "2016", "2020"] },
  { id: "kcd-p2", d: 4, t: "Quel game designer tchèque, déjà connu pour la série Mafia, a dirigé le jeu ?", a: "Daniel Vávra", x: ["Petr Vochozka", "Josef Fares", "Warren Spector"], acc: ["vavra", "daniel vavra", "vávra"] },
  { id: "kcd-p3", d: 4, t: "Dans quelle ville se situe le studio Warhorse ?", a: "Prague", x: ["Brno", "Varsovie", "Vienne"] },
  { id: "kcd-p4", d: 4, t: "Par quelle plateforme de financement participatif le projet a-t-il été lancé en 2014 ?", a: "Kickstarter", x: ["Indiegogo", "Patreon", "Ulule"] },
  { id: "kcd-p5", d: 4, t: "Quel titre impérial Sigismond finira-t-il par porter dans l'Histoire ?", a: "Empereur du Saint-Empire", x: ["Tsar de Russie", "Roi de France", "Sultan ottoman"] },
  { id: "kcd-p6", d: 4, t: "Quel DLC permet d'incarner Thérèse et d'adopter un chien fidèle ?", a: "A Woman's Lot", x: ["Band of Bastards", "From the Ashes", "The Amorous Adventures of Bold Sir Hans Capon"] },
  { id: "kcd-p7", d: 4, t: "Quel DLC suit les mésaventures amoureuses du jeune Hans Capon ?", a: "The Amorous Adventures of Bold Sir Hans Capon", x: ["Band of Bastards", "From the Ashes", "A Woman's Lot"] },
  { id: "kcd-p8", d: 4, t: "Quel DLC voit Henri rejoindre une compagnie de mercenaires menée par Sir Kuno ?", a: "Band of Bastards", x: ["From the Ashes", "A Woman's Lot", "The Amorous Adventures of Bold Sir Hans Capon"] },
  { id: "kcd-p9", d: 4, t: "Quel réformateur religieux tchèque, contemporain du jeu, sera brûlé comme hérétique en 1415 ?", a: "Jan Hus", x: ["Martin Luther", "Jean Calvin", "Jan Žižka"], acc: ["jan hus", "hus"] },
  { id: "kcd-p10", d: 4, t: "En quelle année la suite Kingdom Come Deliverance II est-elle sortie ?", a: "2025", x: ["2021", "2023", "2027"] },
  { id: "kcd-p11", d: 4, t: "Quelle riche ville minière d'argent est au cœur de Kingdom Come Deliverance II ?", a: "Kuttenberg", x: ["Prague", "Rattay", "Sasau"], acc: ["kuttenberg", "kutna hora"] },
  { id: "kcd-p12", d: 4, t: "Quelle aptitude Henri, illettré au départ, doit-il apprendre auprès d'un scribe ?", a: "Lire", x: ["Nager", "Monter à cheval", "Forger"] },
  { id: "kcd-p13", d: 4, t: "Quelle petite pièce d'argent sert de monnaie dans le jeu ?", a: "Le groschen", x: ["Le ducat", "Le florin", "Le thaler"], acc: ["groschen"] },
  { id: "kcd-p14", d: 4, t: "De quel défunt empereur Venceslas IV et Sigismond sont-ils les fils ?", a: "Charles IV", x: ["Ottokar II", "Venceslas II", "Rodolphe Ier"], acc: ["charles iv"] },
  { id: "kcd-p15", d: 4, t: "Quel mode ajouté après la sortie retire la carte et impose des malus réalistes ?", a: "Le mode hardcore", x: ["Le mode arcade", "Le mode histoire", "Le mode zen"], acc: ["hardcore", "mode hardcore"] },
  { id: "kcd-p16", d: 4, t: "Quel moteur graphique fait tourner le jeu ?", a: "Le CryEngine", x: ["L'Unreal Engine", "Le Frostbite", "L'Unity"], acc: ["cryengine"] },
  { id: "kcd-p17", d: 4, t: "Dans le DLC « From the Ashes », quelle fonction de gestion Henri occupe-t-il pour rebâtir un village ?", a: "Bailli", x: ["Forgeron", "Chevalier", "Évêque"], acc: ["bailli"] },
  { id: "kcd-p18", d: 4, t: "Dans quel établissement Henri peut-il se laver, se soigner et se reposer contre paiement ?", a: "Les bains publics", x: ["La taverne", "La chapelle", "L'écurie"], acc: ["bains publics", "bains", "bain"] },
  { id: "kcd-p19", d: 4, t: "Quel petit outil Henri emploie-t-il pour crocheter serrures et coffres ?", a: "Un crochet", x: ["Une clé squelette", "Un pic à glace", "Un poinçon"], acc: ["crochet"] },
  { id: "kcd-p20", d: 4, t: "De quelle origine était historiquement le peuple des Coumans, mercenaires du jeu ?", a: "Turque", x: ["Slave", "Germanique", "Latine"], acc: ["turque", "turc"] },
]);
