import { universe } from "../_build";

export const lessims = universe("jeuxvideo", "Les Sims", [
  // --- Faciles (5) ---
  { id: "sims-f1", d: 1, t: "Quel éditeur publie la série Les Sims ?", a: "Electronic Arts", x: ["Ubisoft", "Nintendo", "Activision"] },
  { id: "sims-f2", d: 1, t: "Que contrôle-t-on dans Les Sims ?", a: "Des personnages virtuels", x: ["Une armée", "Une équipe de foot", "Un vaisseau spatial"] },
  { id: "sims-f3", d: 1, t: "Comment appelle-t-on les personnages du jeu ?", a: "Des Sims", x: ["Des Avatars", "Des Mii", "Des Toons"] },
  { id: "sims-f4", d: 1, t: "Quelle langue inventée parlent les Sims ?", a: "Le simlish", x: ["L'elfique", "Le klingon", "Le dovahzul"] },
  { id: "sims-f5", d: 1, t: "Quel personnage vient chercher un Sim lorsqu'il meurt ?", a: "La Faucheuse", x: ["Le Père Noël", "Le facteur", "Un extraterrestre"] },
  // --- Moyennes (10) ---
  { id: "sims-m1", d: 2, t: "Quel studio développe Les Sims ?", a: "Maxis", x: ["BioWare", "DICE", "Respawn"] },
  { id: "sims-m2", d: 2, t: "Quel code de triche donne 50 000 simflouz dans Les Sims ?", a: "motherlode", x: ["rosebud", "kaching", "freerealestate"] },
  { id: "sims-m3", d: 2, t: "Comment appelle-t-on la monnaie du jeu en français ?", a: "Les simflouz", x: ["Les simdollars", "Les crédits", "Les florins"] },
  { id: "sims-m4", d: 2, t: "Quels besoins faut-il satisfaire pour garder un Sim heureux ?", a: "Faim, sommeil, hygiène et autres", x: ["Force, agilité et magie", "Or, bois et pierre", "Attaque, défense et vitesse"] },
  { id: "sims-m5", d: 2, t: "Que se passe-t-il si un Sim ne mange jamais ?", a: "Il meurt de faim", x: ["Il devient géant", "Il gagne un niveau", "Il se transforme en zombie"] },
  { id: "sims-m6", d: 2, t: "Combien d'opus principaux la série compte-t-elle à ce jour ?", a: "Quatre", x: ["Deux", "Sept", "Dix"] },
  { id: "sims-m7", d: 2, t: "Quel outil permet de bâtir et meubler la maison ?", a: "Le mode construction", x: ["L'éditeur de carte", "L'atelier", "Le mode combat"] },
  { id: "sims-m8", d: 2, t: "Que crée-t-on dans « Créer un Sim » ?", a: "L'apparence et la personnalité d'un Sim", x: ["Une ville entière", "Un véhicule", "Une arme"] },
  { id: "sims-m9", d: 2, t: "Comment un Sim gagne-t-il de l'argent ?", a: "En ayant un travail", x: ["En combattant des monstres", "En pillant des donjons", "En gagnant des courses"] },
  { id: "sims-m10", d: 2, t: "Quel événement heureux agrandit une famille de Sims ?", a: "L'arrivée d'un bébé", x: ["Une invasion", "Un tremblement de terre", "Une guerre"] },
  // --- Dures (15) ---
  { id: "sims-d1", d: 3, t: "En quelle année est sorti le tout premier Les Sims ?", a: "2000", x: ["1998", "2004", "1995"] },
  { id: "sims-d2", d: 3, t: "Qui a créé la série, également créateur de SimCity ?", a: "Will Wright", x: ["Sid Meier", "Peter Molyneux", "Hideo Kojima"] },
  { id: "sims-d3", d: 3, t: "Comment appelle-t-on un contenu qui ajoute tout un thème, comme les animaux ?", a: "Un pack d'extension", x: ["Un patch", "Un mod", "Une bêta"] },
  { id: "sims-d4", d: 3, t: "Quel code active les autres codes de triche dans Les Sims 4 ?", a: "testingcheats true", x: ["motherlode", "rosebud", "freerealestate"] },
  { id: "sims-d5", d: 3, t: "Quelle famille emblématique habite le quartier de départ ?", a: "La famille Goth", x: ["La famille Simpson", "La famille Adams", "La famille Dupont"] },
  { id: "sims-d6", d: 3, t: "Quelle matriarche disparaît mystérieusement de la famille Goth ?", a: "Bella Goth", x: ["Cassandra Goth", "Dina Caliente", "Agnès Crumplebottom"] },
  { id: "sims-d7", d: 3, t: "Que peut-on faire pousser dans un jardin pour gagner de l'argent ?", a: "Des fruits et légumes", x: ["Des diamants", "Des potions", "Des armes"] },
  { id: "sims-d8", d: 3, t: "Quel objet permet à un Sim de se laver ?", a: "La douche", x: ["Le four", "Le réfrigérateur", "La télévision"] },
  { id: "sims-d9", d: 3, t: "Comment un Sim améliore-t-il ses plats ?", a: "En développant sa compétence de cuisine", x: ["En achetant des vies", "En battant un boss", "En lisant la carte"] },
  { id: "sims-d10", d: 3, t: "Dans Les Sims 4, comment nomme-t-on ce qui définit la personnalité ?", a: "Les traits de caractère", x: ["Les classes", "Les races", "Les alignements"] },
  { id: "sims-d11", d: 3, t: "Que risque-t-il d'arriver si on laisse une cuisinière allumée sans surveillance ?", a: "Un incendie", x: ["Une inondation", "Un cambriolage", "Une invasion d'aliens"] },
  { id: "sims-d12", d: 3, t: "Comment appelle-t-on la manière cruelle et célèbre de tuer un Sim dans une piscine ?", a: "Retirer l'échelle", x: ["Couper le courant", "Fermer les portes", "Vider la piscine"] },
  { id: "sims-d13", d: 3, t: "Quel objet permet d'écrire des livres et de toucher des droits d'auteur ?", a: "L'ordinateur", x: ["Le téléphone", "Le télescope", "Le four"] },
  { id: "sims-d14", d: 3, t: "Quel meuble permet à un Sim de récupérer de l'énergie ?", a: "Le lit", x: ["Le bureau", "La cheminée", "L'aquarium"] },
  { id: "sims-d15", d: 3, t: "Combien de conjoints un Sim peut-il avoir en même temps ?", a: "Un seul", x: ["Deux", "Cinq", "Autant qu'on veut"] },
  // --- Pro (20) ---
  { id: "sims-p1", d: 4, t: "Quel est le nom anglais d'origine des « simflouz » ?", a: "Les simoleons", x: ["Les simbucks", "Les simcoins", "Les simdollars"] },
  { id: "sims-p2", d: 4, t: "Lequel de ces mondes est un monde de base des Sims 4 ?", a: "Willow Creek", x: ["Windenburg", "Del Sol Valley", "San Myshuno"] },
  { id: "sims-p3", d: 4, t: "Quel personnage récurrent vient voler la nuit chez les Sims ?", a: "Le cambrioleur", x: ["Le vampire", "Le clown tragique", "Le majordome"] },
  { id: "sims-p4", d: 4, t: "Quel personnage clownesque et déprimant apparaît quand un Sim est très malheureux ?", a: "Le clown tragique", x: ["Le cambrioleur", "La Faucheuse", "Le majordome"] },
  { id: "sims-p5", d: 4, t: "Quelle créature de la nuit peut mordre un Sim pour le transformer ?", a: "Le vampire", x: ["Le zombie", "La sirène", "Le fantôme"] },
  { id: "sims-p6", d: 4, t: "Comment un Sim devient-il un fantôme ?", a: "En mourant", x: ["En dormant", "En se mariant", "En vieillissant"] },
  { id: "sims-p7", d: 4, t: "Quelle compétence permet de réparer et d'améliorer les objets ?", a: "Le bricolage", x: ["La cuisine", "La pêche", "Le charisme"] },
  { id: "sims-p8", d: 4, t: "Quel meuble permet d'observer les étoiles et parfois de se faire enlever par des aliens ?", a: "Le télescope", x: ["Le microscope", "La longue-vue", "Le périscope"] },
  { id: "sims-p9", d: 4, t: "Quelle voisine séductrice de la famille Caliente est bien connue ?", a: "Dina Caliente", x: ["Bella Goth", "Cassandra Goth", "Agnès Crumplebottom"] },
  { id: "sims-p10", d: 4, t: "Quelle veuve acariâtre frappe de son sac les Sims qui s'embrassent en public ?", a: "Agnès Crumplebottom", x: ["Bella Goth", "Dina Caliente", "Cassandra Goth"] },
  { id: "sims-p11", d: 4, t: "Quel opus a introduit un vrai moteur 3D et la caméra libre ?", a: "Les Sims 2", x: ["Les Sims 1", "Les Sims 3", "Les Sims 4"] },
  { id: "sims-p12", d: 4, t: "Quelle aspiration pousse un Sim à amasser de l'argent ?", a: "Devenir riche", x: ["Devenir sportif", "Fonder une famille", "Faire le tour du monde"] },
  { id: "sims-p13", d: 4, t: "Comment appelle-t-on un contenu qui n'ajoute que des objets, sans gameplay majeur ?", a: "Un kit d'objets", x: ["Une extension", "Un patch correctif", "Une bêta"] },
  { id: "sims-p14", d: 4, t: "Quelle compétence améliore les relations et les discours d'un Sim ?", a: "Le charisme", x: ["La logique", "La forme physique", "La pêche"] },
  { id: "sims-p15", d: 4, t: "Que peuvent faire deux Sims très amoureux après le mariage ?", a: "Fonder une famille", x: ["Fusionner en un seul", "Disparaître", "Changer d'âge"] },
  { id: "sims-p16", d: 4, t: "Comment appelle-t-on la vue qui tourne autour de la maison en 3D ?", a: "La caméra libre", x: ["Le mode combat", "La mini-carte", "La vue de course"] },
  { id: "sims-p17", d: 4, t: "Quel personnage apparaît parfois avec le télescope pour enlever un Sim ?", a: "L'extraterrestre", x: ["Le cambrioleur", "Le clown tragique", "Le pompier"] },
  { id: "sims-p18", d: 4, t: "Quel service appelle-t-on quand un incendie se déclare ?", a: "Les pompiers", x: ["La police", "Le majordome", "Le facteur"] },
  { id: "sims-p19", d: 4, t: "Quel Sim de la famille Goth est le mari de Bella ?", a: "Mortimer Goth", x: ["Bella Goth", "Cassandra Goth", "Dina Caliente"] },
  { id: "sims-p20", d: 4, t: "Comment appelle-t-on une modification non officielle ajoutée par un joueur ?", a: "Un mod", x: ["Un kit", "Une extension", "Un patch"] },
]);
