import { universe } from "../_build";

export const minecraft = universe("jeuxvideo", "Minecraft", [
  // --- Faciles (5) ---
  { id: "mc-f1", d: 1, t: "Dans Minecraft, de quelle forme est presque tout dans le jeu ?", a: "Des cubes (blocs)", acc: ["cubes", "blocs", "cube", "bloc"], x: ["Des sphères", "Des pyramides", "Des cylindres"] },
  { id: "mc-f2", d: 1, t: "Comment s'appelle le monstre vert qui explose au contact du joueur ?", a: "Le Creeper", acc: ["creeper"], x: ["Le Zombie", "L'Enderman", "Le Squelette"] },
  { id: "mc-f3", d: 1, t: "Quel minerai précieux bleu-blanc tout le monde cherche à miner ?", a: "Le diamant", acc: ["diamant", "diamants"], x: ["L'or", "Le fer", "Le charbon"] },
  { id: "mc-f4", d: 1, t: "Comment s'appelle le personnage (skin) masculin par défaut du jeu ?", a: "Steve", x: ["Alex", "Notch", "Herobrine"] },
  { id: "mc-f5", d: 1, t: "Quel est le principe de base de Minecraft ?", a: "Casser et poser des blocs (construire)", acc: ["construire", "casser des blocs", "poser des blocs", "miner"], x: ["Faire la course", "Tirer sur des ennemis", "Gérer une ville"] },

  // --- Moyennes (10) ---
  { id: "mc-m1", d: 2, t: "Quel studio a créé Minecraft ?", a: "Mojang", acc: ["mojang"], x: ["Microsoft", "Valve", "Epic Games"] },
  { id: "mc-m2", d: 2, t: "Quel monstre nocturne tire des flèches sur le joueur ?", a: "Le Squelette", acc: ["squelette"], x: ["Le Creeper", "Le Zombie", "L'Enderman"] },
  { id: "mc-m3", d: 2, t: "Quelle grande créature noire se téléporte et déteste qu'on la regarde ?", a: "L'Enderman", acc: ["enderman"], x: ["Le Creeper", "Le Wither", "Le Ghast"] },
  { id: "mc-m4", d: 2, t: "Comment s'appelle le mode où l'on a des ressources infinies et où l'on vole ?", a: "Le mode Créatif", acc: ["creatif", "créatif", "creative"], x: ["Le mode Survie", "Le mode Aventure", "Le mode Hardcore"] },
  { id: "mc-m5", d: 2, t: "Comment s'appelle le mode où l'on doit gérer sa vie et sa faim ?", a: "Le mode Survie", acc: ["survie", "survival"], x: ["Le mode Créatif", "Le mode Spectateur", "Le mode Paisible"] },
  { id: "mc-m6", d: 2, t: "Quel bloc de fabrication 3×3 sert à créer la plupart des objets ?", a: "L'établi (table de craft)", acc: ["etabli", "établi", "table de craft", "crafting table"], x: ["Le four", "L'enclume", "Le coffre"] },
  { id: "mc-m7", d: 2, t: "Quel bloc sert à cuire les aliments et fondre les minerais ?", a: "Le four", acc: ["four", "furnace"], x: ["L'établi", "L'enclume", "L'alambic"] },
  { id: "mc-m8", d: 2, t: "Comment s'appelle le boss final ailé que l'on affronte dans l'End ?", a: "Le Dragon de l'Ender", acc: ["dragon de l'ender", "ender dragon", "dragon de l'end"], x: ["Le Wither", "Le Warden", "Le Ghast"] },
  { id: "mc-m9", d: 2, t: "Quelle dimension infernale, rouge et pleine de lave, peut-on visiter ?", a: "Le Nether", acc: ["nether"], x: ["L'End", "L'Overworld", "L'Aether"] },
  { id: "mc-m10", d: 2, t: "Quel objet permet de dormir pour passer la nuit ?", a: "Le lit", acc: ["lit", "le lit", "bed"], x: ["Le canapé", "La tente", "Le hamac"] },

  // --- Dures (15) ---
  { id: "mc-d1", d: 3, t: "Qui est le créateur original de Minecraft (surnommé « Notch ») ?", a: "Markus Persson", acc: ["markus persson", "notch", "persson"], x: ["Gabe Newell", "Hideo Kojima", "Jens Bergensten"] },
  { id: "mc-d2", d: 3, t: "Quelle entreprise a racheté Mojang en 2014 ?", a: "Microsoft", acc: ["microsoft"], x: ["Sony", "Google", "Amazon"] },
  { id: "mc-d3", d: 3, t: "Quel record Minecraft détient-il dans l'histoire du jeu vidéo ?", a: "Le jeu le plus vendu de tous les temps", acc: ["le plus vendu", "jeu le plus vendu"], x: ["Le plus cher", "Le plus ancien", "Le plus noté"] },
  { id: "mc-d4", d: 3, t: "Comment s'appelle le système de « circuits » rouge servant aux mécanismes ?", a: "La redstone", acc: ["redstone"], x: ["La glowstone", "Le quartz", "Le lapis"] },
  { id: "mc-d5", d: 3, t: "En quel bloc faut-il tailler le cadre d'un portail vers le Nether ?", a: "L'obsidienne", acc: ["obsidienne", "obsidian"], x: ["Le diamant", "La pierre", "Le fer"] },
  { id: "mc-d6", d: 3, t: "Comment s'appelle le boss à trois têtes que l'on doit fabriquer soi-même ?", a: "Le Wither", acc: ["wither"], x: ["Le Dragon de l'Ender", "Le Warden", "Le Ravageur"] },
  { id: "mc-d7", d: 3, t: "Quelle matière, plus solide que le diamant, se fabrique à partir de débris antiques ?", a: "La netherite", acc: ["netherite", "néthérite"], x: ["L'obsidienne", "L'émeraude", "Le quartz"] },
  { id: "mc-d8", d: 3, t: "Quelle monnaie d'échange utilise-t-on pour commercer avec les villageois ?", a: "Les émeraudes", acc: ["emeraude", "émeraudes", "emeraudes"], x: ["Les diamants", "L'or", "Les pièces"] },
  { id: "mc-d9", d: 3, t: "Comment s'appelle la couche de blocs indestructibles tout au fond du monde ?", a: "La bedrock (roche-mère)", acc: ["bedrock", "roche-mere", "roche-mère"], x: ["L'obsidienne", "La pierre", "Le netherrack"] },
  { id: "mc-d10", d: 3, t: "En quelle année Minecraft est-il officiellement sorti (version 1.0) ?", a: "2011", x: ["2009", "2013", "2015"] },
  { id: "mc-d11", d: 3, t: "Quel monstre volant du Nether crache des boules de feu et pleure ?", a: "Le Ghast", acc: ["ghast"], x: ["Le Blaze", "Le Piglin", "Le Wither"] },
  { id: "mc-d12", d: 3, t: "Quel objet trouvé dans les cités de l'End permet de planer comme des ailes ?", a: "L'Élytra", acc: ["elytra", "élytra"], x: ["La plume", "Le jetpack", "Le grappin"] },
  { id: "mc-d13", d: 3, t: "Quelle créature peut-on apprivoiser avec des os ?", a: "Le loup", acc: ["loup", "wolf"], x: ["Le chat", "Le cheval", "Le perroquet"] },
  { id: "mc-d14", d: 3, t: "Quel golem protège les villages et attaque les monstres ?", a: "Le Golem de fer", acc: ["golem de fer", "iron golem", "golem"], x: ["Le Golem de neige", "Le Warden", "Le Ravageur"] },
  { id: "mc-d15", d: 3, t: "Comment s'appelle l'édition historique (PC), développée en Java ?", a: "La Java Edition", acc: ["java", "java edition"], x: ["La Bedrock Edition", "La Pocket Edition", "La Console Edition"] },

  // --- Pro (20) ---
  { id: "mc-p1", d: 4, t: "Comment s'appelle le monstre aveugle et colossal du Deep Dark, sensible aux vibrations ?", a: "Le Warden", acc: ["warden"], x: ["Le Wither", "L'Enderman", "Le Ravageur"] },
  { id: "mc-p2", d: 4, t: "Comment s'appelle la structure souterraine où rôde le Warden ?", a: "La Cité antique (Ancient City)", acc: ["cite antique", "cité antique", "ancient city"], x: ["La Forteresse du Nether", "Le Manoir", "Le Temple"] },
  { id: "mc-p3", d: 4, t: "Quel objet rare permet de tromper la mort une fois (revenir à la vie) ?", a: "Le Totem d'immortalité", acc: ["totem d'immortalite", "totem d'immortalité", "totem of undying", "totem"], x: ["La Pomme d'or", "L'Élytra", "La Perle de l'Ender"] },
  { id: "mc-p4", d: 4, t: "De quel pillard obtient-on ce totem ?", a: "L'Évocateur (Evoker)", acc: ["evocateur", "évocateur", "evoker"], x: ["Le Pillard", "Le Vindicateur", "Le Ravageur"] },
  { id: "mc-p5", d: 4, t: "Comment s'appelle le compositeur de la musique culte de Minecraft ?", a: "C418 (Daniel Rosenfeld)", acc: ["c418", "daniel rosenfeld", "rosenfeld"], x: ["Toby Fox", "Lena Raine", "Koji Kondo"] },
  { id: "mc-p6", d: 4, t: "Quel monstre du Nether, fait de bâtons de feu, tire des boules de feu en rafale ?", a: "Le Blaze", acc: ["blaze"], x: ["Le Ghast", "Le Piglin", "Le Strider"] },
  { id: "mc-p7", d: 4, t: "Quelle créature humanoïde du Nether troque des objets contre de l'or ?", a: "Le Piglin", acc: ["piglin"], x: ["Le Villageois", "Le Ghast", "Le Hoglin"] },
  { id: "mc-p8", d: 4, t: "Comment obtient-on de l'obsidienne naturellement ?", a: "En versant de l'eau sur une source de lave", acc: ["eau sur lave", "eau et lave", "lave et eau"], x: ["En minant du charbon", "En cuisant de la pierre", "Dans le Nether"] },
  { id: "mc-p9", d: 4, t: "Vers quel niveau de profondeur (Y) trouve-t-on le plus de diamants depuis la 1.18 ?", a: "Vers Y -59 (tout en bas)", acc: ["-59", "-58", "tout en bas", "y -59"], x: ["Y 11", "Y 0", "Y 64"] },
  { id: "mc-p10", d: 4, t: "Comment s'appelle le mode survie sans réapparition (une seule vie) ?", a: "Le mode Hardcore", acc: ["hardcore"], x: ["Le mode Survie", "Le mode Extrême", "Le mode Aventure"] },
  { id: "mc-p11", d: 4, t: "Quel enchantement répare un objet grâce à l'expérience ?", a: "Raccommodage (Mending)", acc: ["raccommodage", "mending"], x: ["Solidité", "Réparation", "Infini"] },
  { id: "mc-p12", d: 4, t: "Quel petit être bleu volant (ajouté en 1.19) ramasse les objets qu'on lui confie ?", a: "L'Allay", acc: ["allay"], x: ["Le Vex", "Le Ghast", "Le Poisson-argent"] },
  { id: "mc-p13", d: 4, t: "Quelle créature amphibie rose (1.17) fait le mort pour tromper l'ennemi ?", a: "L'Axolotl", acc: ["axolotl"], x: ["Le Têtard", "La Grenouille", "Le Dauphin"] },
  { id: "mc-p14", d: 4, t: "Quel objet sert à fabriquer des potions ?", a: "L'alambic (brewing stand)", acc: ["alambic", "brewing stand"], x: ["Le chaudron", "L'enclume", "La table d'enchantement"] },
  { id: "mc-p15", d: 4, t: "Quel gros monstre-taureau charge lors des raids de pillards ?", a: "Le Ravageur", acc: ["ravageur", "ravager"], x: ["Le Wither", "Le Warden", "Le Hoglin"] },
  { id: "mc-p16", d: 4, t: "Quel objet, lancé, permet à l'Enderman (et au joueur) de se téléporter ?", a: "La Perle de l'Ender", acc: ["perle de l'ender", "ender pearl", "perle"], x: ["L'Œil de l'Ender", "La Poudre de Blaze", "La Fiole"] },
  { id: "mc-p17", d: 4, t: "Comment s'appelle le personnage-mythe (inexistant) qui hante la légende de Minecraft ?", a: "Herobrine", acc: ["herobrine"], x: ["Steve", "Notch", "Null"] },
  { id: "mc-p18", d: 4, t: "Quel acteur incarne Steve dans le film Minecraft (2025) ?", a: "Jack Black", acc: ["jack black"], x: ["Jason Momoa", "Chris Pratt", "Jables"] },
  { id: "mc-p19", d: 4, t: "Comment s'appelle la créature cubique verte qui rebondit et se divise en tombant ?", a: "Le Slime", acc: ["slime"], x: ["Le Cube de magma", "Le Creeper", "Le Ghast"] },
  { id: "mc-p20", d: 4, t: "De quel animal le Creeper a-t-il peur (il le fuit) ?", a: "Le chat (ocelot)", acc: ["chat", "ocelot", "chats"], x: ["Le loup", "Le golem", "Le cheval"] },
]);
