import { universe } from "../_build";

export const phasmophobia = universe("jeuxvideo", "Phasmophobia", [
  // --- Faciles (5) ---
  { id: "phas-f1", d: 1, t: "Que fait-on principalement dans Phasmophobia ?", a: "On chasse des fantômes", x: ["On élève des animaux", "On pilote des avions", "On cuisine"], acc: ["chasser des fantomes", "fantomes"] },
  { id: "phas-f2", d: 1, t: "Combien de joueurs peuvent enquêter ensemble en coopération ?", a: "Quatre", x: ["Deux", "Huit", "Seize"], acc: ["4", "quatre"] },
  { id: "phas-f3", d: 1, t: "Quel est le but principal d'une enquête ?", a: "Identifier le type de fantôme", x: ["Détruire la maison", "Trouver un trésor", "Sauver un otage"], acc: ["identifier le fantome"] },
  { id: "phas-f4", d: 1, t: "À quel genre de jeu vidéo Phasmophobia appartient-il ?", a: "L'horreur", x: ["La course", "Le sport", "La stratégie"], acc: ["horreur"] },
  { id: "phas-f5", d: 1, t: "On y incarne des enquêteurs spécialisés dans quel domaine ?", a: "Le paranormal", x: ["Le grand banditisme", "La finance", "Le marché de l'art"], acc: ["paranormal"] },
  // --- Moyennes (10) ---
  { id: "phas-m1", d: 2, t: "Quel appareil détecte les champs électromagnétiques, jusqu'au niveau 5 ?", a: "Le détecteur EMF", x: ["Le thermomètre", "La lampe UV", "L'appareil photo"], acc: ["emf", "detecteur emf"] },
  { id: "phas-m2", d: 2, t: "Quel appareil permet de poser des questions au fantôme et d'entendre ses réponses ?", a: "La spirit box", x: ["Le détecteur EMF", "Le thermomètre", "La croix"], acc: ["spirit box"] },
  { id: "phas-m3", d: 2, t: "Quelle preuve se repère avec un thermomètre qui descend sous zéro ?", a: "Les températures glaciales", x: ["Les empreintes", "Les orbes", "L'écriture"], acc: ["temperatures glaciales", "froid"] },
  { id: "phas-m4", d: 2, t: "Que révèle la lampe UV laissée par certains fantômes ?", a: "Des empreintes", x: ["Des orbes", "Des flammes", "Du sang"], acc: ["empreintes"] },
  { id: "phas-m5", d: 2, t: "Dans quel objet un fantôme peut-il laisser un message écrit ?", a: "Le carnet d'écriture", x: ["La spirit box", "La croix", "Le trépied"], acc: ["carnet d'ecriture", "livre d'ecriture"] },
  { id: "phas-m6", d: 2, t: "Quelle jauge des enquêteurs baisse dans le noir et rend le fantôme plus agressif ?", a: "La santé mentale", x: ["L'endurance", "La faim", "L'oxygène"], acc: ["sante mentale", "santé mentale", "sanity"] },
  { id: "phas-m7", d: 2, t: "Que doit faire un joueur quand le fantôme entame une « chasse » ?", a: "Se cacher", x: ["Attaquer", "Danser", "Négocier"], acc: ["se cacher", "cacher"] },
  { id: "phas-m8", d: 2, t: "Quel objet religieux empêche un fantôme de démarrer une chasse à proximité ?", a: "Le crucifix", x: ["La bougie", "Le sel", "La torche"], acc: ["crucifix", "croix"] },
  { id: "phas-m9", d: 2, t: "Combien de preuves faut-il réunir pour identifier un fantôme ?", a: "Trois", x: ["Une", "Cinq", "Sept"], acc: ["3", "trois"] },
  { id: "phas-m10", d: 2, t: "Quel studio a développé Phasmophobia ?", a: "Kinetic Games", x: ["Valve", "Innersloth", "Devolver"], acc: ["kinetic games", "kinetic"] },
  // --- Dures (15) ---
  { id: "phas-d1", d: 3, t: "À quoi sert le sel jeté au sol pendant l'enquête ?", a: "Révéler les pas du fantôme", x: ["Soigner les joueurs", "Recharger la lampe", "Ouvrir les portes"], acc: ["reveler les pas"] },
  { id: "phas-d2", d: 3, t: "Que font les bâtons de sauge, les « smudge sticks », brûlés près du fantôme ?", a: "Ils l'empêchent de chasser un temps", x: ["Ils le rendent visible", "Ils le détruisent", "Ils le dédoublent"], acc: ["empechent de chasser"] },
  { id: "phas-d3", d: 3, t: "Quel appareil projette une grille de points où l'on peut voir la silhouette du fantôme ?", a: "Le projecteur DOTS", x: ["La spirit box", "Le détecteur EMF", "La croix"], acc: ["dots", "projecteur dots"] },
  { id: "phas-d4", d: 3, t: "Sur quel appareil repère-t-on les « orbes » flottants comme preuve ?", a: "La caméra vidéo", x: ["Le thermomètre", "La lampe UV", "Le carnet"], acc: ["camera video", "caméra"] },
  { id: "phas-d5", d: 3, t: "Quel fantôme est célèbre pour lancer violemment plusieurs objets à la fois ?", a: "Le Poltergeist", x: ["La Banshee", "Le Wraith", "Le Mare"], acc: ["poltergeist"] },
  { id: "phas-d6", d: 3, t: "Quel fantôme s'acharne sur une seule cible à la fois ?", a: "La Banshee", x: ["Le Poltergeist", "Le Demon", "Le Yurei"], acc: ["banshee"] },
  { id: "phas-d7", d: 3, t: "Quel fantôme est réputé le plus agressif, chassant très tôt ?", a: "Le Demon", x: ["Le Spirit", "Le Phantom", "Le Wraith"], acc: ["demon"] },
  { id: "phas-d8", d: 3, t: "Quel fantôme peut se téléporter et ne laisse pas d'empreintes dans le sel ?", a: "Le Wraith", x: ["Le Mare", "Le Yurei", "Le Oni"], acc: ["wraith"] },
  { id: "phas-d9", d: 3, t: "Quel fantôme devient plus dangereux dans l'obscurité et déteste la lumière ?", a: "Le Mare", x: ["Le Hantu", "Le Goryo", "Le Myling"], acc: ["mare"] },
  { id: "phas-d10", d: 3, t: "Quel fantôme est plus rapide dans le froid et ne hante que les lieux glacés ?", a: "Le Hantu", x: ["Le Mare", "Le Yokai", "Le Oni"], acc: ["hantu"] },
  { id: "phas-d11", d: 3, t: "Quel fantôme est provoqué en chasse quand on parle près de lui ?", a: "Le Yokai", x: ["Le Goryo", "Le Myling", "Le Raiju"], acc: ["yokai"] },
  { id: "phas-d12", d: 3, t: "Quel fantôme est particulièrement discret, faisant peu de bruit en chasse ?", a: "Le Myling", x: ["Le Yokai", "Le Oni", "Le Hantu"], acc: ["myling"] },
  { id: "phas-d13", d: 3, t: "Quel fantôme se déplace très vite quand il vous a repéré, mais lentement sinon ?", a: "Le Revenant", x: ["Le Phantom", "Le Spirit", "Le Mare"], acc: ["revenant"] },
  { id: "phas-d14", d: 3, t: "Quel fantôme peut agir depuis deux endroits différents, comme s'ils étaient deux ?", a: "Les Jumeaux", x: ["Le Mimic", "Le Obake", "Le Deogen"], acc: ["jumeaux", "the twins", "twins"] },
  { id: "phas-d15", d: 3, t: "Comment s'appelle le vaste asile psychiatrique, l'une des plus grandes cartes du jeu ?", a: "Sunny Meadows", x: ["Tanglewood", "Ridgeview", "Edgefield"], acc: ["sunny meadows"] },
  // --- Pro (20) ---
  { id: "phas-p1", d: 4, t: "En quelle année Phasmophobia est-il sorti en accès anticipé ?", a: "2020", x: ["2016", "2018", "2022"], acc: ["2020"] },
  { id: "phas-p2", d: 4, t: "Quelle technologie d'immersion Phasmophobia prend-il en charge dès sa sortie ?", a: "La réalité virtuelle", x: ["La 3D relief", "Le retour de force du volant", "La reconnaissance faciale"], acc: ["realite virtuelle", "réalité virtuelle", "vr"] },
  { id: "phas-p3", d: 4, t: "Grâce à quel périphérique le fantôme peut-il « entendre » les joueurs prononcer son nom ?", a: "Le microphone", x: ["La manette", "Le clavier", "La webcam"], acc: ["microphone", "micro"] },
  { id: "phas-p4", d: 4, t: "Quel objet maudit permet de poser des questions mais fait chuter la santé mentale ?", a: "La planche Ouija", x: ["Le miroir hanté", "La boîte à musique", "La patte de singe"], acc: ["ouija", "planche ouija"] },
  { id: "phas-p5", d: 4, t: "Quel objet maudit exauce des vœux, souvent à un prix terrible ?", a: "La patte de singe", x: ["La planche Ouija", "Les cartes de tarot", "Le miroir hanté"], acc: ["patte de singe", "monkey paw"] },
  { id: "phas-p6", d: 4, t: "Quel objet maudit attire le fantôme en jouant une mélodie ?", a: "La boîte à musique", x: ["La patte de singe", "La poupée vaudou", "Le tarot"], acc: ["boite a musique", "boîte à musique"] },
  { id: "phas-p7", d: 4, t: "Quel objet maudit force le fantôme à réagir quand on lui plante des épingles ?", a: "La poupée vaudou", x: ["Le miroir hanté", "La boîte à musique", "La planche Ouija"], acc: ["poupee vaudou", "poupée vaudou"] },
  { id: "phas-p8", d: 4, t: "Quel jeu de cartes maudit déclenche des effets aléatoires, bons ou mauvais ?", a: "Les cartes de tarot", x: ["La patte de singe", "La boîte à musique", "La poupée vaudou"], acc: ["cartes de tarot", "tarot"] },
  { id: "phas-p9", d: 4, t: "Quel fantôme laisse parfois des empreintes à six doigts, trahissant sa nature ?", a: "Le Obake", x: ["Le Mimic", "Le Goryo", "Le Raiju"], acc: ["obake"] },
  { id: "phas-p10", d: 4, t: "Quel fantôme imite les autres et donne toujours des orbes comme fausse preuve ?", a: "Le Mimic", x: ["Le Obake", "Le Deogen", "Le Thaye"], acc: ["mimic"] },
  { id: "phas-p11", d: 4, t: "Quel fantôme sait toujours où sont les joueurs et se rue vers eux de loin ?", a: "Le Deogen", x: ["Le Thaye", "Le Raiju", "Le Moroi"], acc: ["deogen"] },
  { id: "phas-p12", d: 4, t: "Quel fantôme vieillit au fil du temps et devient de moins en moins actif ?", a: "Le Thaye", x: ["Le Deogen", "Le Moroi", "Le Obake"], acc: ["thaye"] },
  { id: "phas-p13", d: 4, t: "Quel fantôme se déplace plus vite à proximité des appareils électroniques ?", a: "Le Raiju", x: ["Le Hantu", "Le Yokai", "Le Onryo"], acc: ["raiju"] },
  { id: "phas-p14", d: 4, t: "Quel fantôme peut déclencher une chasse chaque fois qu'une flamme s'éteint ?", a: "Le Onryo", x: ["Le Raiju", "Le Moroi", "Le Goryo"], acc: ["onryo"] },
  { id: "phas-p15", d: 4, t: "Quel fantôme ne montre sa silhouette dans les points DOTS qu'à travers une caméra ?", a: "Le Goryo", x: ["Le Yurei", "Le Oni", "Le Myling"], acc: ["goryo"] },
  { id: "phas-p16", d: 4, t: "Quel fantôme fait chuter fortement la santé mentale et peut sceller une porte ?", a: "Le Yurei", x: ["Le Oni", "Le Goryo", "Le Hantu"], acc: ["yurei"] },
  { id: "phas-p17", d: 4, t: "Quel fantôme est plus actif quand plusieurs joueurs se trouvent près de lui ?", a: "Le Oni", x: ["Le Yurei", "Le Mare", "Le Phantom"], acc: ["oni"] },
  { id: "phas-p18", d: 4, t: "Prendre en photo quel fantôme le fait disparaître un instant ?", a: "Le Phantom", x: ["Le Spirit", "Le Wraith", "Le Poltergeist"], acc: ["phantom"] },
  { id: "phas-p19", d: 4, t: "Quel fantôme « de base », sans faiblesse notable, voit ses chasses longtemps retardées par la sauge ?", a: "Le Spirit", x: ["Le Wraith", "Le Phantom", "Le Demon"], acc: ["spirit"] },
  { id: "phas-p20", d: 4, t: "Quel fantôme peut « maudire » les joueurs via la spirit box, drainant leur santé mentale ?", a: "Le Moroi", x: ["Le Thaye", "Le Deogen", "Le Raiju"], acc: ["moroi"] },
]);
