import { universe } from "../_build";

export const residentevil = universe("jeuxvideo", "Resident Evil", [
  // --- Faciles (5) ---
  { id: "re-f1", d: 1, t: "Quel studio japonais développe la série Resident Evil ?", a: "Capcom", x: ["Konami", "Square Enix", "Sega"] },
  { id: "re-f2", d: 1, t: "De quel genre est Resident Evil ?", a: "Le survival horror", x: ["La course", "Le jeu de rythme", "La simulation de vie"] },
  { id: "re-f3", d: 1, t: "Quelle entreprise pharmaceutique est à l'origine des virus ?", a: "Umbrella", x: ["Aperture", "Abstergo", "Weyland"] },
  { id: "re-f4", d: 1, t: "Quelles créatures emblématiques attaquent le joueur dans les premiers jeux ?", a: "Les zombies", x: ["Les extraterrestres", "Les robots", "Les fantômes"] },
  { id: "re-f5", d: 1, t: "Sous quel nom la série est-elle connue au Japon ?", a: "Biohazard", x: ["Nemesis", "Outbreak", "Dead Space"] },
  // --- Moyennes (10) ---
  { id: "re-m1", d: 2, t: "Quel virus transforme les habitants en zombies dans les premiers jeux ?", a: "Le virus T", x: ["Le virus Z", "Le virus X", "Le solanum"], acc: ["virus t", "t-virus"] },
  { id: "re-m2", d: 2, t: "Dans quelle ville se déroule Resident Evil 2 ?", a: "Raccoon City", x: ["Silent Hill", "Los Perdidos", "Terragrigia"], acc: ["raccoon city"] },
  { id: "re-m3", d: 2, t: "Quel policier débutant est le héros de Resident Evil 2 ?", a: "Leon Kennedy", x: ["Chris Redfield", "Ethan Winters", "Carlos Oliveira"], acc: ["leon", "leon s. kennedy"] },
  { id: "re-m4", d: 2, t: "Quelle membre du S.T.A.R.S., experte en déminage, est l'héroïne de Resident Evil 3 ?", a: "Jill Valentine", x: ["Claire Redfield", "Ada Wong", "Rebecca Chambers"] },
  { id: "re-m5", d: 2, t: "Quelle créature poursuit sans relâche Jill dans Resident Evil 3 ?", a: "Nemesis", x: ["Le Licker", "Le Tyran", "Le Chasseur"] },
  { id: "re-m6", d: 2, t: "En quelle année le premier Resident Evil est-il sorti ?", a: "1996", x: ["1998", "2000", "1994"] },
  { id: "re-m7", d: 2, t: "Quel personnage aux lunettes noires est le grand traître de la série ?", a: "Albert Wesker", x: ["Chris Redfield", "Barry Burton", "Leon Kennedy"] },
  { id: "re-m8", d: 2, t: "Quel objet vert sert à se soigner dans la série ?", a: "Une herbe", x: ["Une potion", "Une seringue", "Un bandage"], acc: ["herbe", "herbe verte"] },
  { id: "re-m9", d: 2, t: "Comment s'appelle l'unité d'élite de la police à laquelle appartiennent Chris et Jill ?", a: "Le S.T.A.R.S.", x: ["La B.S.A.A.", "Le F.B.C.", "Le D.S.O."], acc: ["stars"] },
  { id: "re-m10", d: 2, t: "Quelle sœur de Chris Redfield est jouable dans Resident Evil 2 ?", a: "Claire Redfield", x: ["Ada Wong", "Jill Valentine", "Sheva Alomar"] },
  // --- Dures (15) ---
  { id: "re-d1", d: 3, t: "Dans quel manoir se déroule le tout premier Resident Evil ?", a: "Le manoir Spencer", x: ["Le manoir Baker", "Le château Dimitrescu", "Le manoir Trevor"], acc: ["spencer"] },
  { id: "re-d2", d: 3, t: "Quelle espionne en robe rouge apparaît dans plusieurs jeux aux côtés de Leon ?", a: "Ada Wong", x: ["Rebecca Chambers", "Sheva Alomar", "Mia Winters"] },
  { id: "re-d3", d: 3, t: "Quel virus, plus puissant que le T, William Birkin crée-t-il dans Resident Evil 2 ?", a: "Le virus G", x: ["Le virus C", "Le T-Véronica", "Las Plagas"], acc: ["virus g", "g-virus"] },
  { id: "re-d4", d: 3, t: "Dans quel pays se déroule principalement Resident Evil 4 ?", a: "L'Espagne", x: ["La Roumanie", "Le Japon", "Les États-Unis"] },
  { id: "re-d5", d: 3, t: "Quel parasite contrôle les villageois « Ganados » dans Resident Evil 4 ?", a: "Las Plagas", x: ["Le virus T", "Le Cordyceps", "La Moisissure"], acc: ["plagas", "las plagas"] },
  { id: "re-d6", d: 3, t: "Qui Leon doit-il escorter et protéger dans Resident Evil 4 ?", a: "Ashley Graham", x: ["Ada Wong", "Claire Redfield", "Sherry Birkin"] },
  { id: "re-d7", d: 3, t: "Sur quel continent se déroule Resident Evil 5 ?", a: "L'Afrique", x: ["L'Asie", "L'Amérique du Sud", "L'Europe"] },
  { id: "re-d8", d: 3, t: "Quelle partenaire accompagne Chris en Afrique dans Resident Evil 5 ?", a: "Sheva Alomar", x: ["Jill Valentine", "Ada Wong", "Rebecca Chambers"] },
  { id: "re-d9", d: 3, t: "Comment surnomme-t-on le Tyran en imperméable qui traque le joueur dans Resident Evil 2 ?", a: "Mr. X", x: ["Nemesis", "Ustanak", "Le Licker"], acc: ["mr x", "mr. x"] },
  { id: "re-d10", d: 3, t: "Quel scientifique crée le virus G et mute en monstre dans Resident Evil 2 ?", a: "William Birkin", x: ["Albert Wesker", "Ozwell Spencer", "James Marcus"] },
  { id: "re-d11", d: 3, t: "Quel Resident Evil principal est le premier entièrement à la première personne ?", a: "Resident Evil 7", x: ["Resident Evil 6", "Resident Evil 5", "Resident Evil 4"] },
  { id: "re-d12", d: 3, t: "Quelle famille terrifiante séquestre Ethan dans un manoir de Louisiane dans Resident Evil 7 ?", a: "La famille Baker", x: ["La famille Redfield", "La famille Winters", "La famille Graham"] },
  { id: "re-d13", d: 3, t: "Quel marchand mystérieux vend armes et objets dans Resident Evil 4 ?", a: "Le marchand", x: ["Le forgeron", "Le colporteur", "L'armurier"] },
  { id: "re-d14", d: 3, t: "Quelle organisation antiterroriste Chris rejoint-il après la chute d'Umbrella ?", a: "La B.S.A.A.", x: ["Le S.T.A.R.S.", "Umbrella", "Los Illuminados"], acc: ["bsaa"] },
  { id: "re-d15", d: 3, t: "Avec quel objet se sauvegarde-t-on via une machine à écrire dans les premiers jeux ?", a: "Un ruban encreur", x: ["Une disquette", "Une clé", "Une pièce"], acc: ["ruban encreur", "ruban"] },
  // --- Pro (20) ---
  { id: "re-p1", d: 4, t: "Comment s'appelle le héros de Resident Evil 7 et de Village ?", a: "Ethan Winters", x: ["Chris Redfield", "Leon Kennedy", "Carlos Oliveira"] },
  { id: "re-p2", d: 4, t: "Quelle grande dame vampire vit dans un château dans Resident Evil Village ?", a: "Lady Dimitrescu", x: ["Mère Miranda", "Donna Beneviento", "Mia Winters"] },
  { id: "re-p3", d: 4, t: "Combien de « seigneurs » servent Mère Miranda dans Resident Evil Village ?", a: "4", x: ["3", "5", "6"], acc: ["quatre"] },
  { id: "re-p4", d: 4, t: "Quel seigneur mi-homme mi-poisson vit près d'un réservoir dans Resident Evil Village ?", a: "Salvatore Moreau", x: ["Karl Heisenberg", "Osmund Saddler", "Ozwell Spencer"] },
  { id: "re-p5", d: 4, t: "Quel seigneur manipule le métal et une armée mécanique dans Resident Evil Village ?", a: "Karl Heisenberg", x: ["Salvatore Moreau", "Osmund Saddler", "Ramon Salazar"] },
  { id: "re-p6", d: 4, t: "Quelle poupée hante la maison de Donna Beneviento dans Resident Evil Village ?", a: "Angie", x: ["Eveline", "Lisa", "Rose"] },
  { id: "re-p7", d: 4, t: "Quel organisme fongique, « la Moisissure », infecte les Baker dans Resident Evil 7 ?", a: "La Moisissure", x: ["Las Plagas", "Le virus G", "Le Cordyceps"], acc: ["moisissure", "mold"] },
  { id: "re-p8", d: 4, t: "Quelle petite fille bio-arme, de type « E », est au cœur de Resident Evil 7 ?", a: "Eveline", x: ["Sherry", "Rose", "Angie"] },
  { id: "re-p9", d: 4, t: "Comment s'appelle la fille d'Ethan Winters, née avec des pouvoirs ?", a: "Rose", x: ["Eveline", "Sherry", "Mia"] },
  { id: "re-p10", d: 4, t: "Quel chef du culte « Los Illuminados » est le boss final de Resident Evil 4 ?", a: "Osmund Saddler", x: ["Ramon Salazar", "Jack Krauser", "Albert Wesker"] },
  { id: "re-p11", d: 4, t: "Quel petit châtelain arrogant commande une partie du château dans Resident Evil 4 ?", a: "Ramon Salazar", x: ["Osmund Saddler", "Jack Krauser", "Luis Sera"] },
  { id: "re-p12", d: 4, t: "Quel ancien allié devenu ennemi, expert au couteau, affronte Leon dans Resident Evil 4 ?", a: "Jack Krauser", x: ["Luis Sera", "Ramon Salazar", "Albert Wesker"] },
  { id: "re-p13", d: 4, t: "Quel virus, arme d'Albert Wesker, apparaît dans Resident Evil 5 ?", a: "Le virus Uroboros", x: ["Le virus C", "Le virus G", "Le T-Abyss"], acc: ["uroboros"] },
  { id: "re-p14", d: 4, t: "Où meurt Albert Wesker à la fin de Resident Evil 5 ?", a: "Dans un volcan", x: ["Dans l'océan", "Dans un manoir", "Dans un train"] },
  { id: "re-p15", d: 4, t: "Quelle actrice incarne Alice dans les films Resident Evil ?", a: "Milla Jovovich", x: ["Kate Beckinsale", "Michelle Rodriguez", "Sienna Guillory"] },
  { id: "re-p16", d: 4, t: "Comment s'appelle le domaine isolé de Louisiane où débute Resident Evil 7 ?", a: "Le domaine Baker", x: ["Le manoir Spencer", "Le château Dimitrescu", "Rockfort Island"], acc: ["baker"] },
  { id: "re-p17", d: 4, t: "Quel commando d'Umbrella increvable est surnommé « Mr. Death » dans les modes bonus ?", a: "HUNK", x: ["Nicholai", "Krauser", "Vector"] },
  { id: "re-p18", d: 4, t: "Quel virus de Resident Evil 6 transforme les infectés en « J'avo » ?", a: "Le virus C", x: ["Le virus G", "Le virus T", "Las Plagas"], acc: ["virus c", "c-virus"] },
  { id: "re-p19", d: 4, t: "Sur quelle île se déroule Resident Evil Code: Veronica ?", a: "Rockfort Island", x: ["L'île de Sheena", "Terragrigia", "Kijuju"], acc: ["rockfort"] },
  { id: "re-p20", d: 4, t: "En quelle année Resident Evil 4 est-il sorti à l'origine sur GameCube ?", a: "2005", x: ["2001", "2009", "2013"] },
]);
