import { universe } from "../_build";

export const stardewvalley = universe("jeuxvideo", "Stardew Valley", [
  // --- Faciles (5) ---
  { id: "stardew-f1", d: 1, t: "Quel type de jeu est Stardew Valley ?", a: "Un jeu de simulation agricole", x: ["Un jeu de tir", "Un jeu de course", "Un jeu de combat spatial"] },
  { id: "stardew-f2", d: 1, t: "Que reçoit-on de son grand-père au début du jeu ?", a: "Une ferme", x: ["Une épée", "Un château", "Un vaisseau"] },
  { id: "stardew-f3", d: 1, t: "De quelle grande entreprise le héros démissionne-t-il au début ?", a: "Joja", x: ["Nintendo", "Amazon", "Ubisoft"] },
  { id: "stardew-f4", d: 1, t: "Comment s'appelle la petite ville proche de la ferme ?", a: "Pelican Town", x: ["Stardew City", "Willow Creek", "Val Pélican"] },
  { id: "stardew-f5", d: 1, t: "Que peut-on faire pousser dans ses champs ?", a: "Des cultures", x: ["Des voitures", "Des immeubles", "Des armes"] },
  // --- Moyennes (10) ---
  { id: "stardew-m1", d: 2, t: "Qui a créé Stardew Valley presque entièrement seul ?", a: "ConcernedApe", x: ["Toby Fox", "Notch", "Edmund McMillen"] },
  { id: "stardew-m2", d: 2, t: "Quel magasin d'entreprise menace les commerces locaux ?", a: "Le JojaMart", x: ["Le bazar de Pierre", "La supérette de Gus", "Le marché du sorcier"] },
  { id: "stardew-m3", d: 2, t: "Quels petits esprits de la forêt aident à restaurer les lieux abandonnés ?", a: "Les Junimos", x: ["Les Lutins", "Les Pokémon", "Les Moogles"] },
  { id: "stardew-m4", d: 2, t: "Que peut-on faire à la mine sous la montagne ?", a: "Miner et combattre des monstres", x: ["Nager", "Piloter un avion", "Faire du ski"] },
  { id: "stardew-m5", d: 2, t: "Combien de saisons rythment l'année dans le jeu ?", a: "Quatre", x: ["Deux", "Trois", "Douze"] },
  { id: "stardew-m6", d: 2, t: "Que peut-on nouer avec certains habitants pour se marier ?", a: "Une relation amoureuse", x: ["Un contrat de travail", "Une alliance militaire", "Un duel"] },
  { id: "stardew-m7", d: 2, t: "Quel outil sert à arroser les cultures ?", a: "L'arrosoir", x: ["La pioche", "La hache", "L'épée"] },
  { id: "stardew-m8", d: 2, t: "Quelle activité permet d'attraper des poissons ?", a: "La pêche", x: ["La chasse", "L'escalade", "Le tir à l'arc"] },
  { id: "stardew-m9", d: 2, t: "Que se passe-t-il si le personnage veille trop tard ?", a: "Il s'évanouit de fatigue", x: ["Il gagne un niveau", "Il devient invincible", "Il se téléporte"] },
  { id: "stardew-m10", d: 2, t: "Quel outil sert à casser les rochers dans la mine ?", a: "La pioche", x: ["L'arrosoir", "La canne à pêche", "La faux"] },
  // --- Dures (15) ---
  { id: "stardew-d1", d: 3, t: "Quel est le vrai nom du créateur ConcernedApe ?", a: "Eric Barone", x: ["Aaron Barone", "Eric Barros", "Edmund McMillen"] },
  { id: "stardew-d2", d: 3, t: "Qui répare et améliore les outils du joueur ?", a: "Clint", x: ["Robin", "Pierre", "Lewis"] },
  { id: "stardew-d3", d: 3, t: "Qui construit et améliore les bâtiments de la ferme ?", a: "Robin", x: ["Clint", "Pierre", "Lewis"] },
  { id: "stardew-d4", d: 3, t: "Qui est le maire de Pelican Town ?", a: "Lewis", x: ["Clint", "Willy", "Gus"] },
  { id: "stardew-d5", d: 3, t: "Qui tient le magasin de graines et de produits frais ?", a: "Pierre", x: ["Clint", "Willy", "Gus"] },
  { id: "stardew-d6", d: 3, t: "Qui tient la boutique de pêche au bord de l'eau ?", a: "Willy", x: ["Pierre", "Clint", "Gus"] },
  { id: "stardew-d7", d: 3, t: "Qui tient le saloon de la ville ?", a: "Gus", x: ["Willy", "Pierre", "Lewis"] },
  { id: "stardew-d8", d: 3, t: "Quel personnage mystérieux vit dans une tour et pratique la magie ?", a: "Le sorcier", x: ["Le maire", "Le forgeron", "Le docteur"] },
  { id: "stardew-d9", d: 3, t: "Quel fruit rare augmente définitivement l'énergie maximale quand on le mange ?", a: "La Stardrop", x: ["La pomme de vie", "La baie magique", "Le fruit d'or"] },
  { id: "stardew-d10", d: 3, t: "Quel animal de la ferme produit du lait ?", a: "La vache", x: ["La poule", "Le mouton", "Le cochon"] },
  { id: "stardew-d11", d: 3, t: "Que produit une poule dans le poulailler ?", a: "Des œufs", x: ["Du lait", "De la laine", "Du miel"] },
  { id: "stardew-d12", d: 3, t: "Que produit un mouton ?", a: "De la laine", x: ["Des œufs", "Du lait", "Du miel"] },
  { id: "stardew-d13", d: 3, t: "Que peut-on offrir aux habitants pour améliorer l'amitié ?", a: "Des cadeaux", x: ["Des armes", "Des potions", "Des sortilèges"] },
  { id: "stardew-d14", d: 3, t: "Combien d'habitants peut-on épouser en même temps ?", a: "Un seul", x: ["Deux", "Cinq", "Autant qu'on veut"] },
  { id: "stardew-d15", d: 3, t: "Combien de niveaux compte la mine principale ?", a: "120", x: ["50", "200", "1000"] },
  // --- Pro (20) ---
  { id: "stardew-p1", d: 4, t: "En quelle année Stardew Valley est-il sorti ?", a: "2016", x: ["2013", "2018", "2020"] },
  { id: "stardew-p2", d: 4, t: "Quel lieu dangereux du désert se débloque après la mine ?", a: "La Caverne du crâne", x: ["Le donjon de glace", "Les catacombes", "Le volcan gelé"] },
  { id: "stardew-p3", d: 4, t: "Quelle grosse culture orange d'automne peut devenir géante ?", a: "La citrouille", x: ["La pastèque", "Le chou", "La courge musquée"] },
  { id: "stardew-p4", d: 4, t: "Laquelle de ces cultures peut devenir « géante » ?", a: "Le melon", x: ["La fraise", "Le maïs", "La tomate"] },
  { id: "stardew-p5", d: 4, t: "Quelle machine transforme un fruit en vin ?", a: "Le fût", x: ["Le pressoir à huile", "La ruche", "Le four à fromage"] },
  { id: "stardew-p6", d: 4, t: "Quel célibataire renfermé adore le violet et la musique ?", a: "Sebastian", x: ["Sam", "Alex", "Harvey"] },
  { id: "stardew-p7", d: 4, t: "Quel médecin de la ville fait partie des célibataires ?", a: "Harvey", x: ["Sam", "Sebastian", "Elliott"] },
  { id: "stardew-p8", d: 4, t: "Quel écrivain vit dans une cabane sur la plage ?", a: "Elliott", x: ["Harvey", "Sam", "Alex"] },
  { id: "stardew-p9", d: 4, t: "Quelle célibataire aux cheveux violets aime l'aventure et mange des gemmes ?", a: "Abigail", x: ["Penny", "Leah", "Maru"] },
  { id: "stardew-p10", d: 4, t: "Quelle célibataire artiste vit dans une cabane en forêt ?", a: "Leah", x: ["Abigail", "Penny", "Maru"] },
  { id: "stardew-p11", d: 4, t: "Quelle célibataire, fille de Robin, adore la science et la robotique ?", a: "Maru", x: ["Abigail", "Penny", "Leah"] },
  { id: "stardew-p12", d: 4, t: "Quel métal doit-on affiner pour améliorer ses outils juste après le cuivre ?", a: "Le fer", x: ["L'or", "L'iridium", "Le charbon"] },
  { id: "stardew-p13", d: 4, t: "Quel métal violet, le plus précieux du jeu, améliore les outils au maximum ?", a: "L'iridium", x: ["L'or", "Le fer", "Le cuivre"] },
  { id: "stardew-p14", d: 4, t: "Comment appelle-t-on la monnaie du jeu ?", a: "L'or", x: ["Le simflouz", "Le kama", "Le rubis"] },
  { id: "stardew-p15", d: 4, t: "Quelle grande fête d'automne propose un marché et une soupe géante à préparer ensemble ?", a: "La Foire de Stardew Valley", x: ["Le Festival des œufs", "La Danse des fleurs", "Le Bal de la Lune de miel"] },
  { id: "stardew-p16", d: 4, t: "Quelle fête du printemps propose une chasse aux œufs ?", a: "Le Festival des œufs", x: ["La Foire de Stardew Valley", "La Danse des fleurs", "Le Festival de l'écume"] },
  { id: "stardew-p17", d: 4, t: "Que peut-on rejoindre au lieu de restaurer le centre communautaire ?", a: "L'entrepôt Joja", x: ["La guilde des aventuriers", "Le clan des sorciers", "La marine"] },
  { id: "stardew-p18", d: 4, t: "Quel animal de compagnie peut-on choisir au début du jeu ?", a: "Un chat ou un chien", x: ["Un dragon", "Un cheval de course", "Un robot"] },
  { id: "stardew-p19", d: 4, t: "Quel jour de la semaine le magasin de Pierre est-il souvent fermé ?", a: "Le mercredi", x: ["Le dimanche", "Le samedi", "Le lundi"] },
  { id: "stardew-p20", d: 4, t: "Quel bâtiment doit-on remplir de « lots » d'objets pour le restaurer ?", a: "Le centre communautaire", x: ["La mairie", "L'hôpital", "L'école"] },
]);
