import { universe } from "../_build";

export const thewitcher = universe("jeuxvideo", "The Witcher", [
  // --- Faciles (5) ---
  { id: "witcher-f1", d: 1, t: "Comment s'appelle le sorceleur héros de la saga The Witcher ?", a: "Geralt de Riv", x: ["Ciri", "Vesemir", "Jaskier"], acc: ["geralt"] },
  { id: "witcher-f2", d: 1, t: "Quel studio polonais a développé les jeux The Witcher ?", a: "CD Projekt Red", x: ["Ubisoft", "Bethesda", "Rockstar"] },
  { id: "witcher-f3", d: 1, t: "Que sont les sorceleurs comme Geralt ?", a: "Des chasseurs de monstres", x: ["Des chevaliers du roi", "Des marchands", "Des prêtres"] },
  { id: "witcher-f4", d: 1, t: "De quelle couleur sont les cheveux de Geralt ?", a: "Blancs", x: ["Noirs", "Roux", "Bruns"] },
  { id: "witcher-f5", d: 1, t: "Quel troisième opus est sous-titré « Wild Hunt » ?", a: "The Witcher 3", x: ["The Witcher 2", "The Witcher 1", "The Witcher 4"] },
  // --- Moyennes (10) ---
  { id: "witcher-m1", d: 2, t: "De quel écrivain polonais la saga est-elle tirée ?", a: "Andrzej Sapkowski", x: ["Stanisław Lem", "J.R.R. Tolkien", "George R.R. Martin"] },
  { id: "witcher-m2", d: 2, t: "Comment s'appelle la jument fidèle de Geralt ?", a: "Ablette", x: ["Épona", "Agro", "Tornado"], acc: ["roach", "ablette"] },
  { id: "witcher-m3", d: 2, t: "Quelle jeune fille aux pouvoirs de l'Aîné Sang Geralt considère-t-il comme sa fille ?", a: "Ciri", x: ["Yennefer", "Triss", "Shani"] },
  { id: "witcher-m4", d: 2, t: "Comment appelle-t-on les sortilèges que lance Geralt d'un geste de la main ?", a: "Les signes", x: ["Les runes", "Les glyphes", "Les incantations"] },
  { id: "witcher-m5", d: 2, t: "Quel barde ami de Geralt chante « Toss a Coin to Your Witcher » ?", a: "Jaskier", x: ["Zoltan", "Régis", "Lambert"], acc: ["jaskier", "dandelion", "rossignol"] },
  { id: "witcher-m6", d: 2, t: "Quelle magicienne aux cheveux noirs est le grand amour de Geralt ?", a: "Yennefer", x: ["Triss Merigold", "Shani", "Fringilla"], acc: ["yennefer de vengerberg"] },
  { id: "witcher-m7", d: 2, t: "Quel jeu de cartes peut-on jouer dans The Witcher 3 ?", a: "Le Gwent", x: ["Le Triple Triad", "Le Caravan", "Le Pazaak"], acc: ["gwent"] },
  { id: "witcher-m8", d: 2, t: "Quel signe de Geralt crée une barrière de protection ?", a: "Le Quen", x: ["L'Igni", "L'Aard", "L'Yrden"], acc: ["quen"] },
  { id: "witcher-m9", d: 2, t: "Quel signe de Geralt projette une vague de flammes ?", a: "L'Igni", x: ["Le Quen", "L'Aard", "L'Axii"], acc: ["igni"] },
  { id: "witcher-m10", d: 2, t: "Comment appelle-t-on la chasse spectrale qui poursuit Ciri ?", a: "La Chasse sauvage", x: ["La Traque", "Le Cortège noir", "La Meute d'ombre"], acc: ["wild hunt", "chasse sauvage"] },
  // --- Dures (15) ---
  { id: "witcher-d1", d: 3, t: "Comment s'appelle l'école de sorceleurs où Geralt a été formé ?", a: "L'école du Loup", x: ["L'école du Chat", "L'école du Griffon", "L'école de la Vipère"] },
  { id: "witcher-d2", d: 3, t: "Dans quelle forteresse en ruines les sorceleurs de l'école du Loup étaient-ils formés ?", a: "Kaer Morhen", x: ["Kaer Trolde", "Vizima", "Novigrad"] },
  { id: "witcher-d3", d: 3, t: "Quel vieux sorceleur, mentor de Geralt, vit à Kaer Morhen ?", a: "Vesemir", x: ["Lambert", "Eskel", "Régis"] },
  { id: "witcher-d4", d: 3, t: "Quel signe de Geralt repousse violemment les ennemis par une onde de choc ?", a: "L'Aard", x: ["L'Igni", "Le Quen", "L'Axii"], acc: ["aard"] },
  { id: "witcher-d5", d: 3, t: "Quel signe de Geralt permet de contrôler l'esprit d'autrui ?", a: "L'Axii", x: ["L'Yrden", "Le Quen", "L'Aard"], acc: ["axii"] },
  { id: "witcher-d6", d: 3, t: "Comment appelle-t-on la mutation qui a rendu Ciri capable de voyager entre les mondes ?", a: "L'Aîné Sang", x: ["Le Don du Loup", "La Marque du Dragon", "Le Sang de Feu"], acc: ["elder blood", "aîné sang"] },
  { id: "witcher-d7", d: 3, t: "Quelle grande cité portuaire et marchande visite-t-on dans The Witcher 3 ?", a: "Novigrad", x: ["Vizima", "Beauclair", "Oxenfurt"] },
  { id: "witcher-d8", d: 3, t: "Comment s'appelle l'archipel nordique inspiré des Vikings dans The Witcher 3 ?", a: "Skellige", x: ["Velen", "Toussaint", "Kaedwen"] },
  { id: "witcher-d9", d: 3, t: "Quelle magicienne rousse, amie de Geralt, apparaît dès le premier jeu ?", a: "Triss Merigold", x: ["Yennefer", "Fringilla", "Philippa"] },
  { id: "witcher-d10", d: 3, t: "Quel chef de la Chasse sauvage traque Ciri dans The Witcher 3 ?", a: "Eredin", x: ["Imlerith", "Caranthir", "Emhyr"] },
  { id: "witcher-d11", d: 3, t: "Quelle potion sorceleur noircit les yeux et améliore la vision nocturne ?", a: "La Chouette", x: ["Le Chat", "L'Hirondelle", "Le Blaireau"], acc: ["cat", "le chat"] },
  { id: "witcher-d12", d: 3, t: "Quelle région marécageuse et ravagée par la guerre explore-t-on au début de The Witcher 3 ?", a: "Velen", x: ["Skellige", "Toussaint", "Novigrad"] },
  { id: "witcher-d13", d: 3, t: "Quel empereur de Nilfgaard engage Geralt pour retrouver Ciri ?", a: "Emhyr var Emreis", x: ["Radovid", "Foltest", "Eredin"], acc: ["emhyr"] },
  { id: "witcher-d14", d: 3, t: "Quel nain bagarreur et ami de Geralt l'accompagne à Novigrad ?", a: "Zoltan", x: ["Yarpen", "Régis", "Lambert"] },
  { id: "witcher-d15", d: 3, t: "Quel signe de Geralt pose un piège magique au sol ?", a: "L'Yrden", x: ["L'Aard", "L'Igni", "Le Quen"], acc: ["yrden"] },
  // --- Pro (20) ---
  { id: "witcher-p1", d: 4, t: "En quelle année est sorti The Witcher 3 : Wild Hunt ?", a: "2015", x: ["2011", "2013", "2017"] },
  { id: "witcher-p2", d: 4, t: "Quelle extension de The Witcher 3 emmène Geralt dans le duché viticole de Toussaint ?", a: "Blood and Wine", x: ["Hearts of Stone", "The Frozen Heart", "The Price of Neutrality"] },
  { id: "witcher-p3", d: 4, t: "Quelle extension introduit le personnage d'Olgierd von Everec et son pacte ?", a: "Hearts of Stone", x: ["Blood and Wine", "Assassins of Kings", "The Wild Hunt"] },
  { id: "witcher-p4", d: 4, t: "Quel vampire supérieur et médecin est un vieil ami de Geralt ?", a: "Régis", x: ["Detlaff", "Dettlaff", "Olgierd"], acc: ["regis"] },
  { id: "witcher-p5", d: 4, t: "Quel vampire semant la terreur à Beauclair est l'antagoniste de Blood and Wine ?", a: "Dettlaff", x: ["Régis", "Olgierd", "Eredin"] },
  { id: "witcher-p6", d: 4, t: "Quelle capitale du royaume de Temeria sert de cadre au premier jeu ?", a: "Vizima", x: ["Novigrad", "Beauclair", "Wyzima"], acc: ["wyzima"] },
  { id: "witcher-p7", d: 4, t: "Comment s'appellent les mutations et l'épreuve qui transforment un enfant en sorceleur ?", a: "L'Épreuve des Herbes", x: ["Le Rituel du Loup", "La Marque du Chat", "Le Baptême du Sang"], acc: ["trial of the grasses", "épreuve des herbes"] },
  { id: "witcher-p8", d: 4, t: "Quel roi fou de Rédanie chasse les mages dans The Witcher 3 ?", a: "Radovid V", x: ["Foltest", "Emhyr", "Henselt"], acc: ["radovid"] },
  { id: "witcher-p9", d: 4, t: "Comment appelle-t-on la conjonction cosmique qui a mêlé monstres et humains sur le Continent ?", a: "La Conjonction des Sphères", x: ["Le Grand Cataclysme", "La Fracture", "L'Éveil"], acc: ["conjunction of the spheres", "conjonction des sphères"] },
  { id: "witcher-p10", d: 4, t: "Quel général balafré de la Chasse sauvage Geralt affronte-t-il sur Skellige ?", a: "Imlerith", x: ["Eredin", "Caranthir", "Dettlaff"] },
  { id: "witcher-p11", d: 4, t: "Comment se nomme le peuple elfique dont fait partie la Chasse sauvage ?", a: "Les Aen Elle", x: ["Les Aen Seidhe", "Les Nilfgaardiens", "Les Skelligers"] },
  { id: "witcher-p12", d: 4, t: "Quel monstre de la mythologie slave, un esprit des marais, apparaît souvent dans le bestiaire ?", a: "Le noyeur", x: ["Le kraken", "Le minotaure", "Le basilic"], acc: ["drowner", "noyeur"] },
  { id: "witcher-p13", d: 4, t: "Quelle épée un sorceleur réserve-t-il aux monstres ?", a: "L'épée d'argent", x: ["L'épée d'acier", "L'épée de bronze", "L'épée d'or"] },
  { id: "witcher-p14", d: 4, t: "Quel banni loup-garou maudit affronte-t-on dans la quête de la « Dame du Bois » ?", a: "La Dame du Bois", x: ["Le Baron sanglant", "Gaunter O'Dimm", "Le Roi Bran"], acc: ["crones", "les mégères"] },
  { id: "witcher-p15", d: 4, t: "Quel marchand énigmatique, aussi appelé « le Maître Miroir », accorde des vœux à un prix terrible ?", a: "Gaunter O'Dimm", x: ["Olgierd von Everec", "Emhyr var Emreis", "Régis"], acc: ["gaunter", "master mirror"] },
  { id: "witcher-p16", d: 4, t: "Quel roi de Temeria, hanté par une malédiction familiale, apparaît dans les premiers jeux ?", a: "Foltest", x: ["Radovid", "Henselt", "Demavend"] },
  { id: "witcher-p17", d: 4, t: "Comment s'appelle la loge secrète de magiciennes qui complote sur le Continent ?", a: "La Loge des magiciennes", x: ["Le Chapitre", "Le Conseil des Sages", "L'Ordre de la Rose ardente"], acc: ["lodge of sorceresses"] },
  { id: "witcher-p18", d: 4, t: "Quel autre sorceleur de l'école du Loup, cynique et râleur, vit à Kaer Morhen ?", a: "Lambert", x: ["Eskel", "Vesemir", "Berengar"] },
  { id: "witcher-p19", d: 4, t: "Dans quelle cité universitaire proche de Novigrad Geralt retrouve-t-il de vieux amis ?", a: "Oxenfurt", x: ["Beauclair", "Vizima", "Gors Velen"] },
  { id: "witcher-p20", d: 4, t: "Quel personnage jouable incarne-t-on lors de certaines séquences aux côtés de Geralt ?", a: "Ciri", x: ["Yennefer", "Triss", "Jaskier"] },
]);
