import { universe } from "../_build";

export const tlou = universe("jeuxvideo", "The Last of Us", [
  // --- Faciles (5) ---
  { id: "tlou-f1", d: 1, t: "Quel studio a développé The Last of Us ?", a: "Naughty Dog", x: ["Rockstar", "Ubisoft", "Capcom"], acc: ["naughty dog"] },
  { id: "tlou-f2", d: 1, t: "Sur les consoles de quelle marque The Last of Us est-il d'abord sorti ?", a: "PlayStation", x: ["Xbox", "Nintendo", "Sega"], acc: ["playstation", "sony", "ps3"] },
  { id: "tlou-f3", d: 1, t: "Quel duo de personnages forme le cœur de The Last of Us ?", a: "Joel et Ellie", x: ["Nathan et Elena", "Leon et Ada", "Max et Chloé"], acc: ["joel et ellie", "joel", "ellie"] },
  { id: "tlou-f4", d: 1, t: "Dans quel type de monde se déroule The Last of Us ?", a: "Un monde post-apocalyptique", x: ["Un monde médiéval", "L'espace", "Un monde sous-marin"], acc: ["post-apocalyptique", "apocalypse", "post apo"] },
  { id: "tlou-f5", d: 1, t: "Qu'est-ce qui a transformé une partie de l'humanité en créatures dans le jeu ?", a: "Un champignon", x: ["Un virus zombie classique", "Une invasion alien", "Une bombe nucléaire"], acc: ["champignon", "cordyceps", "fongus"] },
  // --- Moyennes (10) ---
  { id: "tlou-m1", d: 2, t: "Quelle particularité fait d'Ellie l'espoir de l'humanité ?", a: "Elle est immunisée", x: ["Elle est invincible", "Elle est médecin", "Elle vole"], acc: ["immunisee", "immunité", "immunisée"] },
  { id: "tlou-m2", d: 2, t: "Quel champignon réel inspire l'infection du jeu ?", a: "Le cordyceps", x: ["La pénicilline", "L'amanite", "La truffe"], acc: ["cordyceps"] },
  { id: "tlou-m3", d: 2, t: "En quelle année est sorti le premier The Last of Us ?", a: "2013", x: ["2007", "2016", "2020"], acc: ["2013"] },
  { id: "tlou-m4", d: 2, t: "Comment appelle-t-on les infectés aveugles qui se repèrent au son, les plus emblématiques ?", a: "Les Claqueurs", x: ["Les Rôdeurs", "Les Coureurs", "Les Colosses"], acc: ["claqueurs", "clickers", "les claqueurs"] },
  { id: "tlou-m5", d: 2, t: "Quel métier exerce Joel au début de l'histoire ?", a: "Contrebandier", x: ["Médecin", "Soldat", "Policier"], acc: ["contrebandier", "passeur", "smuggler"] },
  { id: "tlou-m6", d: 2, t: "Comment s'appelle le groupe rebelle qui cherche un vaccin ?", a: "Les Lucioles", x: ["Les Loups", "Les Corbeaux", "Les Renards"], acc: ["lucioles", "les lucioles", "fireflies"] },
  { id: "tlou-m7", d: 2, t: "En quelle année est sorti The Last of Us Part II ?", a: "2020", x: ["2015", "2018", "2023"], acc: ["2020"] },
  { id: "tlou-m8", d: 2, t: "Quelle chaîne a adapté The Last of Us en série télévisée en 2023 ?", a: "HBO", x: ["Netflix", "Disney+", "Amazon"], acc: ["hbo"] },
  { id: "tlou-m9", d: 2, t: "Quel acteur incarne Joel dans la série HBO ?", a: "Pedro Pascal", x: ["Pedro Alonso", "Oscar Isaac", "Javier Bardem"], acc: ["pedro pascal", "pascal"] },
  { id: "tlou-m10", d: 2, t: "Combien de temps après le début de l'épidémie se déroule l'aventure de Joel et Ellie ?", a: "Environ 20 ans", x: ["Quelques jours", "1 an", "100 ans"], acc: ["20 ans", "environ 20 ans", "vingt ans"] },
  // --- Dures (15) ---
  { id: "tlou-d1", d: 3, t: "Comment s'appelle la fille de Joel, qui meurt la nuit de l'épidémie ?", a: "Sarah", x: ["Ellie", "Tess", "Dina"], acc: ["sarah"] },
  { id: "tlou-d2", d: 3, t: "Comment s'appelle la partenaire de Joel qui l'accompagne au début du premier jeu ?", a: "Tess", x: ["Marlene", "Dina", "Abby"], acc: ["tess"] },
  { id: "tlou-d3", d: 3, t: "Comment s'appelle le frère de Joel ?", a: "Tommy", x: ["Sam", "Bill", "Henry"], acc: ["tommy"] },
  { id: "tlou-d4", d: 3, t: "Comment s'appelle la cheffe des Lucioles ?", a: "Marlene", x: ["Tess", "Dina", "Abby"], acc: ["marlene"] },
  { id: "tlou-d5", d: 3, t: "Qui a dirigé la création de The Last of Us chez Naughty Dog ?", a: "Neil Druckmann", x: ["Hideo Kojima", "Cory Barlog", "Amy Hennig"], acc: ["neil druckmann", "druckmann"] },
  { id: "tlou-d6", d: 3, t: "Quelle actrice incarne Ellie dans la série HBO ?", a: "Bella Ramsey", x: ["Millie Bobby Brown", "Maisie Williams", "Florence Pugh"], acc: ["bella ramsey", "ramsey"] },
  { id: "tlou-d7", d: 3, t: "Comment s'appelle la ville-refuge du Wyoming où vit Tommy dans Part II ?", a: "Jackson", x: ["Boston", "Seattle", "Salt Lake City"], acc: ["jackson"] },
  { id: "tlou-d8", d: 3, t: "Comment s'appelle la nouvelle héroïne, musclée, qui bouleverse Part II ?", a: "Abby", x: ["Dina", "Marlene", "Riley"], acc: ["abby"] },
  { id: "tlou-d9", d: 3, t: "Comment s'appelle la petite amie d'Ellie dans Part II ?", a: "Dina", x: ["Riley", "Tess", "Abby"], acc: ["dina"] },
  { id: "tlou-d10", d: 3, t: "Dans quelle ville se déroule en grande partie The Last of Us Part II ?", a: "Seattle", x: ["Boston", "Jackson", "Pittsburgh"], acc: ["seattle"] },
  { id: "tlou-d11", d: 3, t: "Quel sentiment guide Ellie tout au long de Part II ?", a: "La vengeance", x: ["La curiosité", "L'ambition", "La jalousie"], acc: ["vengeance", "la vengeance", "revanche"] },
  { id: "tlou-d12", d: 3, t: "Comment s'appelle le gros infecté couvert de plaques fongiques, très résistant ?", a: "Le Colosse", x: ["Le Claqueur", "Le Rôdeur", "Le Coureur"], acc: ["colosse", "bloater", "le colosse"] },
  { id: "tlou-d13", d: 3, t: "Comment s'appelle le DLC du premier jeu centré sur Ellie et son amie Riley ?", a: "Left Behind", x: ["Ground Zeroes", "The Old Hunters", "Blood and Wine"], acc: ["left behind"] },
  { id: "tlou-d14", d: 3, t: "Quelle scène culte, avec un grand animal en liberté, offre une pause poétique ?", a: "La scène de la girafe", x: ["La scène du lion", "La scène de l'éléphant", "La scène du cerf"], acc: ["girafe", "scene de la girafe"] },
  { id: "tlou-d15", d: 3, t: "Comment s'appelle le remake du premier jeu, sorti sur PS5 en 2022 ?", a: "The Last of Us Part I", x: ["The Last of Us Remastered", "The Last of Us Reborn", "The Last of Us Origins"], acc: ["part i", "the last of us part i", "part 1"] },
  // --- Pro (20) ---
  { id: "tlou-p1", d: 4, t: "Comment appelle-t-on les infectés du premier stade, rapides et encore humains d'apparence ?", a: "Les Coureurs", x: ["Les Claqueurs", "Les Colosses", "Les Rôdeurs"], acc: ["coureurs", "runners", "les coureurs"] },
  { id: "tlou-p2", d: 4, t: "Comment appelle-t-on le stade intermédiaire d'infecté, qui se cache et surgit ?", a: "Les Rôdeurs", x: ["Les Coureurs", "Les Claqueurs", "Les Colosses"], acc: ["rodeurs", "stalkers", "les rodeurs"] },
  { id: "tlou-p3", d: 4, t: "Comment s'appelle la milice armée qui contrôle Seattle dans Part II ?", a: "Le WLF", x: ["Les Lucioles", "La FEDRA", "Les Séraphites"], acc: ["wlf", "les loups", "washington liberation front"] },
  { id: "tlou-p4", d: 4, t: "Comment surnomme-t-on la secte religieuse ennemie du WLF à Seattle ?", a: "Les Séraphites", x: ["Les Lucioles", "Le WLF", "La FEDRA"], acc: ["seraphites", "scars", "les seraphites"] },
  { id: "tlou-p5", d: 4, t: "Comment s'appelle l'organisation militaire autoritaire qui gère les zones de quarantaine ?", a: "La FEDRA", x: ["Le WLF", "Les Lucioles", "L'OTAN"], acc: ["fedra"] },
  { id: "tlou-p6", d: 4, t: "Pour quelle raison Abby en veut-elle mortellement à Joel ?", a: "Joel a tué son père", x: ["Joel a volé ses vivres", "Joel a détruit sa ville", "Joel l'a trahie"], acc: ["a tue son pere", "son pere", "il a tue son pere"] },
  { id: "tlou-p7", d: 4, t: "Quel métier exerçait le père d'Abby chez les Lucioles ?", a: "Chirurgien", x: ["Soldat", "Pilote", "Cuisinier"], acc: ["chirurgien", "medecin", "docteur"] },
  { id: "tlou-p8", d: 4, t: "Comment s'appelle le jeune Séraphite qu'Abby prend sous son aile ?", a: "Lev", x: ["Yara", "Sam", "Riley"], acc: ["lev"] },
  { id: "tlou-p9", d: 4, t: "Quel showrunner de Chernobyl a co-créé la série HBO avec Neil Druckmann ?", a: "Craig Mazin", x: ["Vince Gilligan", "David Benioff", "Jon Favreau"], acc: ["craig mazin", "mazin"] },
  { id: "tlou-p10", d: 4, t: "De quelle ville part le périple de Joel et Ellie au début du premier jeu ?", a: "Boston", x: ["Seattle", "New York", "Chicago"], acc: ["boston"] },
  { id: "tlou-p11", d: 4, t: "Quel instrument de musique Ellie apprend-elle à jouer, hérité de Joel ?", a: "La guitare", x: ["Le piano", "Le violon", "La batterie"], acc: ["guitare", "la guitare"] },
  { id: "tlou-p12", d: 4, t: "Comment s'appelle le mode multijoueur du premier The Last of Us ?", a: "Factions", x: ["Warzone", "Survivors", "Onslaught"], acc: ["factions"] },
  { id: "tlou-p13", d: 4, t: "Comment s'appelle le survivaliste bricoleur que Joel et Ellie croisent dans une petite ville ?", a: "Bill", x: ["Tommy", "Henry", "David"], acc: ["bill"] },
  { id: "tlou-p14", d: 4, t: "Comment s'appelle le petit frère d'Henry, rencontré à Pittsburgh ?", a: "Sam", x: ["Frank", "Lev", "James"], acc: ["sam"] },
  { id: "tlou-p15", d: 4, t: "Quelle devise, tirée de la BD préférée d'Ellie, revient comme un leitmotiv ?", a: "Endure and survive", x: ["Fear the living", "Stay together", "No hope left"], acc: ["endure and survive", "endurer et survivre"] },
  { id: "tlou-p16", d: 4, t: "Comment s'appelle le chef de groupe cannibale affronté à la fin du premier jeu ?", a: "David", x: ["Bill", "Henry", "Tommy"], acc: ["david"] },
  { id: "tlou-p17", d: 4, t: "Quel grand prix The Last of Us a-t-il massivement remporté en 2013 ?", a: "Le jeu de l'année", x: ["Le meilleur jeu de sport", "Le meilleur jeu mobile", "Le meilleur party game"], acc: ["jeu de l'annee", "goty", "game of the year"] },
  { id: "tlou-p18", d: 4, t: "En quelle année la saison 2 de la série HBO a-t-elle été diffusée ?", a: "2025", x: ["2023", "2024", "2026"], acc: ["2025"] },
  { id: "tlou-p19", d: 4, t: "Comment s'appelle la meilleure amie d'Ellie dans le DLC Left Behind ?", a: "Riley", x: ["Dina", "Abby", "Sarah"], acc: ["riley"] },
  { id: "tlou-p20", d: 4, t: "Dans quelle ville se trouve l'hôpital des Lucioles où l'on emmène Ellie ?", a: "Salt Lake City", x: ["Boston", "Seattle", "Jackson"], acc: ["salt lake city", "salt lake"] },
]);
