import { universe } from "../_build";

/**
 * World of Warcraft : univers particulièrement fourni.
 * Répartition : 5 faciles, 10 moyennes, 15 dures, puis 70 pro (= 20 de base
 * + 50 pro supplémentaires) pour couvrir la profondeur du lore.
 */
export const worldofwarcraft = universe("jeuxvideo", "World of Warcraft", [
  // --- Faciles (5) ---
  { id: "wow-f1", d: 1, t: "Quel studio développe World of Warcraft ?", a: "Blizzard Entertainment", x: ["Electronic Arts", "Ubisoft", "Riot Games"] },
  { id: "wow-f2", d: 1, t: "Quelles sont les deux grandes factions du jeu ?", a: "L'Alliance et la Horde", x: ["Les Rouges et les Bleus", "Le Nord et le Sud", "Les Anges et les Démons"] },
  { id: "wow-f3", d: 1, t: "Sur quel monde se déroule principalement le jeu ?", a: "Azeroth", x: ["Tatooine", "Hyrule", "Termina"] },
  { id: "wow-f4", d: 1, t: "Quel type de jeu est World of Warcraft ?", a: "Un jeu de rôle en ligne massivement multijoueur", x: ["Un jeu de course", "Un jeu de tir", "Un jeu de gestion"] },
  { id: "wow-f5", d: 1, t: "Quelle race verte et musclée est emblématique de la Horde ?", a: "L'orc", x: ["L'elfe", "Le nain", "Le gnome"] },
  // --- Moyennes (10) ---
  { id: "wow-m1", d: 2, t: "Quel continent est le berceau des orcs et des taurens sur Azeroth ?", a: "Kalimdor", x: ["Norfendre", "Outreterre", "Pandarie"] },
  { id: "wow-m2", d: 2, t: "Quelle est la capitale de la Horde, à Durotar ?", a: "Orgrimmar", x: ["Hurlevent", "Forgefer", "Darnassus"] },
  { id: "wow-m3", d: 2, t: "Quel héros orc fut chef de guerre de la Horde et grand chaman ?", a: "Thrall", x: ["Arthas", "Illidan", "Kael'thas"] },
  { id: "wow-m4", d: 2, t: "Quelle est la capitale principale de l'Alliance ?", a: "Hurlevent", x: ["Orgrimmar", "Fossoyeuse", "Lune-d'argent"] },
  { id: "wow-m5", d: 2, t: "Quelle classe manie la magie arcanique et lance des boules de feu ?", a: "Le mage", x: ["Le guerrier", "Le voleur", "Le chasseur"] },
  { id: "wow-m6", d: 2, t: "En quelle année World of Warcraft est-il sorti ?", a: "2004", x: ["2000", "2008", "2011"] },
  { id: "wow-m7", d: 2, t: "Quel roi-liche gèle ses ennemis depuis son trône de glace ?", a: "Arthas", x: ["Thrall", "Varian", "Malfurion"] },
  { id: "wow-m8", d: 2, t: "Quelle race bovine peuple les plaines de Mulgore ?", a: "Les taurens", x: ["Les orcs", "Les gnomes", "Les worgens"] },
  { id: "wow-m9", d: 2, t: "Quel continent gelé abrite le royaume du Roi-liche ?", a: "Norfendre", x: ["Kalimdor", "Outreterre", "Pandarie"] },
  { id: "wow-m10", d: 2, t: "Comment s'appelle l'armée démoniaque qui menace sans cesse Azeroth ?", a: "La Légion ardente", x: ["La Horde de fer", "Le Fléau", "Le Cercle cénarien"] },
  // --- Dures (15) ---
  { id: "wow-d1", d: 3, t: "Quel est le nom de famille du prince Arthas ?", a: "Menethil", x: ["Wrynn", "Portvaillant", "Fordring"] },
  { id: "wow-d2", d: 3, t: "Quelle race a pour capitale Les Pitons du Tonnerre ?", a: "Les taurens", x: ["Les orcs", "Les trolls", "Les Réprouvés"] },
  { id: "wow-d3", d: 3, t: "Quel monde brisé est le berceau des orcs et des draeneï ?", a: "Draenor", x: ["Azeroth", "Norfendre", "Pandarie"] },
  { id: "wow-d4", d: 3, t: "Comment appelle-t-on le passage reliant Azeroth à Outreterre ?", a: "La Porte des ténèbres", x: ["Le portail de Dalaran", "La Porte de l'Effroi", "Le Maelström"] },
  { id: "wow-d5", d: 3, t: "Quel eredar surnommé le Trompeur seconde Sargeras à la tête de la Légion ?", a: "Kil'jaeden", x: ["Mannoroth", "Archimonde", "Ner'zhul"] },
  { id: "wow-d6", d: 3, t: "Quel dragon noir se faisait passer pour la conseillère Katrana Prestor à Hurlevent ?", a: "Onyxia", x: ["Nefarian", "Alexstrasza", "Ysera"] },
  { id: "wow-d7", d: 3, t: "Quelle classe en plaques manie la Lumière pour combattre et soigner ?", a: "Le paladin", x: ["Le prêtre", "Le mage", "Le voleur"] },
  { id: "wow-d8", d: 3, t: "Quel elfe de la nuit est le tout premier druide, frère jumeau d'Illidan ?", a: "Malfurion", x: ["Cénarius", "Thrall", "Medivh"] },
  { id: "wow-d9", d: 3, t: "Quelle haute-prêtresse d'Elune dirige les elfes de la nuit ?", a: "Tyrande", x: ["Jaina", "Sylvanas", "Alexstrasza"] },
  { id: "wow-d10", d: 3, t: "Quel chef de guerre orc est renversé lors du Siège d'Orgrimmar ?", a: "Garrosh", x: ["Vol'jin", "Saurfang", "Thrall"] },
  { id: "wow-d11", d: 3, t: "Quel dragon jadis nommé Neltharion déclenche le Cataclysme ?", a: "Aile de mort", x: ["Malygos", "Nefarian", "Onyxia"], acc: ["Deathwing"] },
  { id: "wow-d12", d: 3, t: "Quelle cité-forteresse sous la montagne est la capitale des nains ?", a: "Forgefer", x: ["Hurlevent", "Gnomeregan", "Darnassus"] },
  { id: "wow-d13", d: 3, t: "Quel cercle druidique porte le nom du demi-dieu qui enseigna la nature ?", a: "Le Cercle cénarien", x: ["Le Kirin Tor", "La Poigne d'argent", "Les Illidari"] },
  { id: "wow-d14", d: 3, t: "Quelle organisation de mages gouverne la cité de Dalaran ?", a: "Le Kirin Tor", x: ["Le Cercle cénarien", "La Main d'argent", "Le Marteau du Crépuscule"] },
  { id: "wow-d15", d: 3, t: "Quel dragon de bronze permet de revivre d'anciens donjons via le voyage temporel ?", a: "Chromie", x: ["Nozdormu", "Ysera", "Alexstrasza"] },
  // --- Pro (70) ---
  { id: "wow-p1", d: 4, t: "Quelle est la première extension de WoW, sortie en 2007 ?", a: "The Burning Crusade", x: ["Wrath of the Lich King", "Cataclysm", "Legion"] },
  { id: "wow-p2", d: 4, t: "Quelle extension de 2008 introduit Norfendre et le Roi-liche ?", a: "Wrath of the Lich King", x: ["The Burning Crusade", "Cataclysm", "Mists of Pandaria"] },
  { id: "wow-p3", d: 4, t: "Quelle extension de 2010 voit Aile de mort dévaster Azeroth ?", a: "Cataclysm", x: ["Legion", "Warlords of Draenor", "Dragonflight"] },
  { id: "wow-p4", d: 4, t: "Quelle extension de 2012 rend les pandarens jouables ?", a: "Mists of Pandaria", x: ["Warlords of Draenor", "Legion", "Shadowlands"] },
  { id: "wow-p5", d: 4, t: "Quelle extension de 2014 se déroule sur un Draenor du passé ?", a: "Warlords of Draenor", x: ["Mists of Pandaria", "Legion", "Battle for Azeroth"] },
  { id: "wow-p6", d: 4, t: "Quelle extension de 2016 introduit les Îles Brisées et les armes prodigieuses ?", a: "Legion", x: ["Warlords of Draenor", "Battle for Azeroth", "Shadowlands"] },
  { id: "wow-p7", d: 4, t: "Quelle extension de 2018 emmène les joueurs à Zandalar et Kul Tiras ?", a: "Battle for Azeroth", x: ["Legion", "Shadowlands", "Dragonflight"] },
  { id: "wow-p8", d: 4, t: "Quelle extension de 2020 explore l'au-delà ?", a: "Shadowlands", x: ["Legion", "Battle for Azeroth", "Dragonflight"] },
  { id: "wow-p9", d: 4, t: "Quelle extension de 2022 se déroule sur les Îles aux Dragons ?", a: "Dragonflight", x: ["Shadowlands", "The War Within", "Legion"] },
  { id: "wow-p10", d: 4, t: "Quelle extension de 2024 ouvre la saga de l'Âme-monde à Khaz Algar ?", a: "The War Within", x: ["Dragonflight", "Shadowlands", "Battle for Azeroth"] },
  { id: "wow-p11", d: 4, t: "Quel prince humain sombre dans les ténèbres et devient le Roi-liche ?", a: "Arthas", x: ["Anduin", "Varian", "Bolvar"] },
  { id: "wow-p12", d: 4, t: "Qui devient le nouveau Roi-liche après la chute d'Arthas ?", a: "Bolvar", x: ["Tirion", "Anduin", "Thrall"] },
  { id: "wow-p13", d: 4, t: "Quelle reine-banshee fut aussi chef de guerre de la Horde ?", a: "Sylvanas", x: ["Jaina", "Tyrande", "Alexstrasza"] },
  { id: "wow-p14", d: 4, t: "Quel « Traître » dirige le Temple noir en Outreterre ?", a: "Illidan", x: ["Kael'thas", "Gul'dan", "Vol'jin"] },
  { id: "wow-p15", d: 4, t: "Quelle magicienne dirige Kul Tiras et fut la protectrice de Theramore ?", a: "Jaina", x: ["Sylvanas", "Tyrande", "Alexstrasza"] },
  { id: "wow-p16", d: 4, t: "Quel guerrier orc tue le pit-lord Mannoroth ?", a: "Grommash", x: ["Thrall", "Orgrim", "Durotan"] },
  { id: "wow-p17", d: 4, t: "Quel sorcier orc a scellé le premier pacte avec la Légion ardente ?", a: "Gul'dan", x: ["Ner'zhul", "Thrall", "Grommash"] },
  { id: "wow-p18", d: 4, t: "Quel archimage, dernier Gardien, ouvre la Porte des ténèbres ?", a: "Medivh", x: ["Khadgar", "Antonidas", "Rhonin"] },
  { id: "wow-p19", d: 4, t: "Qui est le fils de Varian et roi de Hurlevent ?", a: "Anduin", x: ["Arthas", "Bolvar", "Genn"] },
  { id: "wow-p20", d: 4, t: "Quel chef tauren est tué en mak'gora par Garrosh ?", a: "Cairne", x: ["Baine", "Thrall", "Vol'jin"] },
  { id: "wow-p21", d: 4, t: "Quel Aspect draconique rouge incarne la vie ?", a: "Alexstrasza", x: ["Ysera", "Nozdormu", "Malygos"] },
  { id: "wow-p22", d: 4, t: "Quel Aspect vert veille sur le Rêve d'émeraude ?", a: "Ysera", x: ["Alexstrasza", "Malygos", "Nozdormu"] },
  { id: "wow-p23", d: 4, t: "Quel Aspect bronze est le maître du temps ?", a: "Nozdormu", x: ["Malygos", "Ysera", "Alexstrasza"] },
  { id: "wow-p24", d: 4, t: "Quel Aspect bleu règne sur la magie ?", a: "Malygos", x: ["Nozdormu", "Neltharion", "Ysera"] },
  { id: "wow-p25", d: 4, t: "Quel Aspect noir sombre dans la folie et devient Aile de mort ?", a: "Neltharion", x: ["Malygos", "Nozdormu", "Alexstrasza"] },
  { id: "wow-p26", d: 4, t: "Quel Dieu très ancien est vaincu au Temple d'Ahn'Qiraj ?", a: "C'Thun", x: ["Yogg-Saron", "N'Zoth", "Y'Shaarj"] },
  { id: "wow-p27", d: 4, t: "Quel Dieu très ancien est emprisonné sous Ulduar ?", a: "Yogg-Saron", x: ["C'Thun", "N'Zoth", "Y'Shaarj"] },
  { id: "wow-p28", d: 4, t: "Quel Dieu très ancien est libéré à la fin de Battle for Azeroth ?", a: "N'Zoth", x: ["C'Thun", "Yogg-Saron", "Y'Shaarj"] },
  { id: "wow-p29", d: 4, t: "Quel seigneur du feu affronte-t-on dans le Cœur du Magma ?", a: "Ragnaros", x: ["Nefarian", "Onyxia", "Kel'Thuzad"] },
  { id: "wow-p30", d: 4, t: "Quelle liche dirige le Fléau depuis Naxxramas ?", a: "Kel'Thuzad", x: ["Ragnaros", "Nefarian", "Arthas"] },
  { id: "wow-p31", d: 4, t: "Quel dragon noir, frère d'Onyxia, règne sur le Repaire de l'Aile noire ?", a: "Nefarian", x: ["Sartharion", "Malygos", "Ragnaros"] },
  { id: "wow-p32", d: 4, t: "Dans quel raid affronte-t-on enfin le Roi-liche Arthas ?", a: "La Citadelle de la Couronne de glace", x: ["Ulduar", "Naxxramas", "Le Bastion du Crépuscule"] },
  { id: "wow-p33", d: 4, t: "Quel chef de guerre orc est le boss final de « Siège d'Orgrimmar » ?", a: "Garrosh", x: ["Thrall", "Vol'jin", "Sylvanas"] },
  { id: "wow-p34", d: 4, t: "Quel eredar de la Légion est vaincu dans la Citadelle du Feu infernal en 2015 ?", a: "Archimonde", x: ["Kil'jaeden", "Sargeras", "Mannoroth"] },
  { id: "wow-p35", d: 4, t: "Quel Titan déchu dirige la Légion ardente ?", a: "Sargeras", x: ["Kil'jaeden", "Archimonde", "Aman'Thul"] },
  { id: "wow-p36", d: 4, t: "Quelle cité flottante des mages surplombe Norfendre puis les Îles Brisées ?", a: "Dalaran", x: ["Shattrath", "Suramar", "Hurlevent"] },
  { id: "wow-p37", d: 4, t: "Quelle cité des elfes de sang abrite le Puits solaire ?", a: "Lune-d'argent", x: ["Darnassus", "Forgefer", "L'Exodar"] },
  { id: "wow-p38", d: 4, t: "Quelle capitale des Réprouvés se trouve sous les ruines de Lordaeron ?", a: "Fossoyeuse", x: ["Orgrimmar", "Lune-d'argent", "Les Pitons du Tonnerre"] },
  { id: "wow-p39", d: 4, t: "Quel Arbre-monde Sylvanas incendie-t-elle au début de Battle for Azeroth ?", a: "Teldrassil", x: ["Nordrassil", "Vordrassil", "Shaladrassil"] },
  { id: "wow-p40", d: 4, t: "Quelle cité des elfes noctes est au cœur de l'extension Legion ?", a: "Suramar", x: ["Dalaran", "Shattrath", "Darnassus"] },
  { id: "wow-p41", d: 4, t: "Quelle classe-héros est introduite par Wrath of the Lich King ?", a: "Le chevalier de la mort", x: ["Le chasseur de démons", "Le moine", "L'évocateur"] },
  { id: "wow-p42", d: 4, t: "Quelle classe-héros est introduite par Legion ?", a: "Le chasseur de démons", x: ["Le chevalier de la mort", "Le moine", "L'évocateur"] },
  { id: "wow-p43", d: 4, t: "Quelle classe fait ses débuts avec Mists of Pandaria ?", a: "Le moine", x: ["Le chasseur de démons", "L'évocateur", "Le chevalier de la mort"] },
  { id: "wow-p44", d: 4, t: "Quelle classe, jouée par les dracthyr, arrive avec Dragonflight ?", a: "L'évocateur", x: ["Le moine", "Le chasseur de démons", "Le chevalier de la mort"] },
  { id: "wow-p45", d: 4, t: "Quel était le niveau maximum de personnage dans WoW à sa sortie en 2004 ?", a: "60", x: ["50", "70", "80"] },
  { id: "wow-p46", d: 4, t: "Quelle race jouable rejoint l'Alliance avec The Burning Crusade ?", a: "Les draeneï", x: ["Les worgens", "Les Pandarens", "Les gnomes"] },
  { id: "wow-p47", d: 4, t: "Quelle race jouable rejoint la Horde avec The Burning Crusade ?", a: "Les elfes de sang", x: ["Les gobelins", "Les Pandarens", "Les taurens"] },
  { id: "wow-p48", d: 4, t: "Quelle race d'humains transformés en loups rejoint l'Alliance dans Cataclysm ?", a: "Les worgens", x: ["Les gobelins", "Les draeneï", "Les Pandarens"] },
  { id: "wow-p49", d: 4, t: "Quelle race gobeline rejoint la Horde dans Cataclysm ?", a: "Les gobelins", x: ["Les worgens", "Les Pandarens", "Les gnomes"] },
  { id: "wow-p50", d: 4, t: "Quel empereur mogu ressuscité est le maître du Trône du Tonnerre ?", a: "Lei Shen", x: ["Shaohao", "Xuen", "Yu'lon"] },
  { id: "wow-p51", d: 4, t: "Quelle énergie négative, née du dernier Dieu très ancien, corrompt la Pandarie ?", a: "Le Sha", x: ["Le Vide", "Le Fléau", "La Peste"] },
  { id: "wow-p52", d: 4, t: "Quel roi d'Azeroth périt à la Rive brisée au début de Legion ?", a: "Varian", x: ["Anduin", "Genn", "Bolvar"] },
  { id: "wow-p53", d: 4, t: "Quel chef troll, chef de guerre de la Horde, meurt aussi à la Rive brisée ?", a: "Vol'jin", x: ["Thrall", "Garrosh", "Baine"] },
  { id: "wow-p54", d: 4, t: "Quelle grande magistrix dirige les elfes noctes de Suramar ?", a: "Elisande", x: ["Azshara", "Sylvanas", "Tyrande"] },
  { id: "wow-p55", d: 4, t: "Quel sire vampirique de Revendreth est le boss de « Château Nathria » ?", a: "Denathrius", x: ["Zovaal", "Kel'Thuzad", "Arthas"] },
  { id: "wow-p56", d: 4, t: "Comment appelle-t-on le geôlier, grand méchant de Shadowlands ?", a: "Zovaal", x: ["Denathrius", "Sargeras", "Kil'jaeden"] },
  { id: "wow-p57", d: 4, t: "Quelle reine des naga fut jadis la reine des elfes de la nuit ?", a: "Azshara", x: ["Tyrande", "Sylvanas", "Alexstrasza"] },
  { id: "wow-p58", d: 4, t: "Il y a environ combien de milliers d'années eut lieu la Grande Fracture d'Azeroth ?", a: "10 000", x: ["1 000", "500", "50 000"] },
  { id: "wow-p59", d: 4, t: "Quel dragon noir, fils d'Aile de mort, est surnommé le Prince noir ?", a: "Wrathion", x: ["Nefarian", "Onyxia", "Sartharion"] },
  { id: "wow-p60", d: 4, t: "Quel objet planté dans Silithus fait saigner Azeroth et libère l'Azérite ?", a: "L'épée de Sargeras", x: ["Frostmourne", "Ashbringer", "Gorehowl"] },
  { id: "wow-p61", d: 4, t: "Quel puits arcanique des hauts-elfes est au cœur de The Burning Crusade ?", a: "Le Puits solaire", x: ["Le Puits d'éternité", "La Fontaine de jouvence", "Le Bassin des larmes"] },
  { id: "wow-p62", d: 4, t: "Quel demi-dieu au corps de cerf enseigne la voie druidique à Malfurion ?", a: "Cénarius", x: ["Elune", "Aggramar", "Nozdormu"] },
  { id: "wow-p63", d: 4, t: "Quelle déesse de la lune vénèrent les elfes de la nuit ?", a: "Elune", x: ["Cénarius", "Alexstrasza", "Ysera"] },
  { id: "wow-p64", d: 4, t: "Quel roi de Lordaeron est assassiné par son propre fils Arthas ?", a: "Terenas", x: ["Varian", "Anduin", "Magni"] },
  { id: "wow-p65", d: 4, t: "Quel marteau légendaire est transmis d'Orgrim à Thrall ?", a: "Doomhammer", x: ["Frostmourne", "Ashbringer", "Gorehowl"], acc: ["Marteau du Destin"] },
  { id: "wow-p66", d: 4, t: "Quelle lame sacrée, fléau des morts-vivants, est portée par Tirion Fordring ?", a: "Ashbringer", x: ["Frostmourne", "Doomhammer", "Gorehowl"], acc: ["Porte-Cendres"] },
  { id: "wow-p67", d: 4, t: "Quelle hache emblématique passe de Grommash à son fils Garrosh ?", a: "Gorehowl", x: ["Frostmourne", "Ashbringer", "Doomhammer"] },
  { id: "wow-p68", d: 4, t: "Quel gnoll, boss de la Forêt d'Élwynn, est la terreur des débutants ?", a: "Hogger", x: ["Mankrik", "Murky", "Chromie"] },
  { id: "wow-p69", d: 4, t: "Quel royaume elfique du nord des Royaumes de l'Est abrite le Puits solaire ?", a: "Quel'Thalas", x: ["Khaz Modan", "Gilnéas", "Kul Tiras"] },
  { id: "wow-p70", d: 4, t: "Quel guerrier orc défie Sylvanas en mak'gora à la fin de Battle for Azeroth ?", a: "Saurfang", x: ["Thrall", "Garrosh", "Durotan"] },
]);
