import { universe } from "../_build";

export const yakuza = universe("jeuxvideo", "Yakuza", [
  // --- Faciles (5) ---
  { id: "yakuza-f1", d: 1, t: "Quel éditeur japonais publie la série Yakuza ?", a: "Sega", x: ["Capcom", "Konami", "Bandai Namco"], acc: ["sega"] },
  { id: "yakuza-f2", d: 1, t: "Comment se nomme le héros emblématique des premiers jeux Yakuza ?", a: "Kazuma Kiryu", x: ["Goro Majima", "Ichiban Kasuga", "Taiga Saejima"], acc: ["kiryu", "kazuma kiryu"] },
  { id: "yakuza-f3", d: 1, t: "Dans quel pays se déroule principalement la série Yakuza ?", a: "Le Japon", x: ["La Corée du Sud", "La Chine", "Les États-Unis"], acc: ["japon", "le japon"] },
  { id: "yakuza-f4", d: 1, t: "À quelle organisation criminelle le titre Yakuza fait-il référence ?", a: "La mafia japonaise", x: ["La mafia italienne", "Les triades chinoises", "Le cartel mexicain"], acc: ["mafia japonaise", "yakuza"] },
  { id: "yakuza-f5", d: 1, t: "Quel animal légendaire est tatoué dans le dos de Kazuma Kiryu ?", a: "Un dragon", x: ["Un tigre", "Un serpent", "Un phénix"], acc: ["dragon", "un dragon"] },
  // --- Moyennes (10) ---
  { id: "yakuza-m1", d: 2, t: "Quel quartier fictif de Tokyo sert de décor principal à la série ?", a: "Kamurocho", x: ["Sotenbori", "Ijincho", "Onomichi"], acc: ["kamurocho"] },
  { id: "yakuza-m2", d: 2, t: "Quel surnom désigne Kazuma Kiryu ?", a: "Le Dragon de Dojima", x: ["Le Chien fou de Shimano", "Le Tigre d'Osaka", "Le Loup solitaire"], acc: ["dragon de dojima"] },
  { id: "yakuza-m3", d: 2, t: "Quel personnage borgne est surnommé le Chien fou de Shimano ?", a: "Goro Majima", x: ["Kazuma Kiryu", "Akira Nishikiyama", "Taiga Saejima"], acc: ["majima", "goro majima"] },
  { id: "yakuza-m4", d: 2, t: "Quelle petite fille Kiryu élève-t-il comme sa propre enfant ?", a: "Haruka", x: ["Yuki", "Sayama", "Rina"], acc: ["haruka"] },
  { id: "yakuza-m5", d: 2, t: "Quel mini-jeu de chant très populaire retrouve-t-on dans la série ?", a: "Le karaoké", x: ["Le bowling", "La pêche", "Le golf"], acc: ["karaoke", "karaoké"] },
  { id: "yakuza-m6", d: 2, t: "Sous quel titre la série Yakuza est-elle désormais connue en Occident ?", a: "Like a Dragon", x: ["Sleeping Dogs", "Way of the Samurai", "Shenmue"], acc: ["like a dragon"] },
  { id: "yakuza-m7", d: 2, t: "En quelle année est sorti le tout premier jeu Yakuza ?", a: "2005", x: ["2000", "2010", "1998"], acc: ["2005"] },
  { id: "yakuza-m8", d: 2, t: "Sur quelle console est d'abord sorti le premier Yakuza ?", a: "La PlayStation 2", x: ["La PlayStation 3", "La Xbox", "La GameCube"], acc: ["ps2", "playstation 2"] },
  { id: "yakuza-m9", d: 2, t: "Comment se nomme le clan de yakuzas auquel appartient Kiryu ?", a: "Le clan Tojo", x: ["Le clan Omi", "Le clan Doku", "Le clan Saio"], acc: ["tojo", "clan tojo"] },
  { id: "yakuza-m10", d: 2, t: "Quel quartier inspiré d'Osaka apparaît souvent dans la série ?", a: "Sotenbori", x: ["Kamurocho", "Ijincho", "Onomichi"], acc: ["sotenbori"] },
  // --- Dures (15) ---
  { id: "yakuza-d1", d: 3, t: "Quel nouveau héros amateur de Dragon Quest devient le protagoniste de Yakuza: Like a Dragon ?", a: "Ichiban Kasuga", x: ["Kazuma Kiryu", "Goro Majima", "Takayuki Yagami"], acc: ["ichiban", "ichiban kasuga"] },
  { id: "yakuza-d2", d: 3, t: "Quel changement majeur de gameplay Yakuza: Like a Dragon introduit-il en 2020 ?", a: "Le combat au tour par tour", x: ["La vue à la première personne", "Le monde ouvert intégral", "Le multijoueur en ligne"], acc: ["tour par tour"] },
  { id: "yakuza-d3", d: 3, t: "Comment se nomme le frère de sang de Kiryu qui le trahit dans le premier jeu ?", a: "Akira Nishikiyama", x: ["Goro Majima", "Taiga Saejima", "Ryuji Goda"], acc: ["nishikiyama", "nishiki"] },
  { id: "yakuza-d4", d: 3, t: "À quelle époque se déroule Yakuza 0, préquelle de la saga ?", a: "Les années 1980", x: ["Les années 1960", "Les années 2000", "Les années 1940"], acc: ["1980", "années 1980", "1988"] },
  { id: "yakuza-d5", d: 3, t: "Quel studio de Sega développe la série depuis ses débuts ?", a: "Ryu Ga Gotoku Studio", x: ["Atlus", "Platinum Games", "From Software"], acc: ["ryu ga gotoku studio", "ryu ga gotoku"] },
  { id: "yakuza-d6", d: 3, t: "Quel clan rival, basé dans le Kansai, s'oppose au clan Tojo ?", a: "L'Alliance Omi", x: ["Le clan Doku", "La famille Nishiki", "Le clan Saio"], acc: ["omi", "alliance omi"] },
  { id: "yakuza-d7", d: 3, t: "Dans le premier jeu, pour quelle raison Kiryu passe-t-il dix ans en prison ?", a: "Il endosse un meurtre", x: ["Il braque une banque", "Il trahit son clan", "Il s'évade d'un tribunal"], acc: ["endosse un meurtre", "il endosse un meurtre"] },
  { id: "yakuza-d8", d: 3, t: "Quel personnage prêteur sur gages devient jouable dans Yakuza 4 ?", a: "Shun Akiyama", x: ["Taiga Saejima", "Masayoshi Tanimura", "Goro Majima"], acc: ["akiyama", "shun akiyama"] },
  { id: "yakuza-d9", d: 3, t: "Quelle tour emblématique domine le quartier de Kamurocho ?", a: "La Millennium Tower", x: ["La Tokyo Tower", "La Sky Tree", "La Tour Tojo"], acc: ["millennium tower"] },
  { id: "yakuza-d10", d: 3, t: "Comment se nomme le détective ami de longue date de Kiryu ?", a: "Makoto Date", x: ["Shun Akiyama", "Masayoshi Tanimura", "Goro Majima"], acc: ["date", "makoto date"] },
  { id: "yakuza-d11", d: 3, t: "Dans Yakuza 0, quel type d'établissement Kiryu gère-t-il dans un mini-jeu de management ?", a: "Un club d'hôtesses", x: ["Un restaurant", "Un casino", "Un garage"], acc: ["club d'hotesses", "cabaret", "club d'hôtesses"] },
  { id: "yakuza-d12", d: 3, t: "Quelle ville portuaire sert de second décor dans Yakuza 6 ?", a: "Onomichi", x: ["Sotenbori", "Ijincho", "Kamurocho"], acc: ["onomichi"] },
  { id: "yakuza-d13", d: 3, t: "Quel quartier de Yokohama sert de décor à Yakuza: Like a Dragon ?", a: "Ijincho", x: ["Kamurocho", "Sotenbori", "Onomichi"], acc: ["ijincho", "isezaki ijincho"] },
  { id: "yakuza-d14", d: 3, t: "Quel est le style de combat signature de Kiryu, qui reprend son surnom ?", a: "Le style du Dragon", x: ["Le style de la Bête", "Le style du Voyou", "Le style du Boxeur"], acc: ["style du dragon", "dragon"] },
  { id: "yakuza-d15", d: 3, t: "Quelle série dérivée met en scène le détective Takayuki Yagami ?", a: "Judgment", x: ["Shenmue", "Binary Domain", "Sleeping Dogs"], acc: ["judgment", "judge eyes"] },
  // --- Pro (20) ---
  { id: "yakuza-p1", d: 4, t: "Quel créateur est le père fondateur de la série Yakuza ?", a: "Toshihiro Nagoshi", x: ["Hideo Kojima", "Yoko Taro", "Goichi Suda"], acc: ["nagoshi", "toshihiro nagoshi"] },
  { id: "yakuza-p2", d: 4, t: "Quel rival surnommé le Dragon du Kansai affronte Kiryu dans Yakuza 2 ?", a: "Ryuji Goda", x: ["Akira Nishikiyama", "Taiga Saejima", "Daigo Dojima"], acc: ["ryuji goda", "goda"] },
  { id: "yakuza-p3", d: 4, t: "Dans Yakuza 0, quel mini-jeu de course met en scène de petites voitures télécommandées ?", a: "Le Pocket Circuit", x: ["Le Mach Bowl", "Le Kart Battle", "Le Mini Grand Prix"], acc: ["pocket circuit"] },
  { id: "yakuza-p4", d: 4, t: "Quel patron du clan Tojo, protégé par Kiryu, en devient le président ?", a: "Daigo Dojima", x: ["Ryuji Goda", "Akira Nishikiyama", "Goro Majima"], acc: ["daigo dojima", "daigo"] },
  { id: "yakuza-p5", d: 4, t: "Quelle entreprise de construction Goro Majima dirige-t-il dans plusieurs jeux ?", a: "Majima Construction", x: ["Kiryu Corporation", "Tojo Holdings", "Omi Trading"], acc: ["majima construction"] },
  { id: "yakuza-p6", d: 4, t: "Sous quel faux nom Kiryu opère-t-il dans Like a Dragon Gaiden ?", a: "Joryu", x: ["Suzuki", "Kazama", "Shinada"], acc: ["joryu"] },
  { id: "yakuza-p7", d: 4, t: "Dans quel archipel américain se déroule en partie Like a Dragon: Infinite Wealth ?", a: "Hawaï", x: ["La Floride", "La Californie", "Porto Rico"], acc: ["hawai", "hawaï", "honolulu"] },
  { id: "yakuza-p8", d: 4, t: "Quel jeu dérivé situé à l'ère des samouraïs met en scène un sosie de Kiryu nommé Sakamoto Ryoma ?", a: "Like a Dragon: Ishin", x: ["Like a Dragon: Kenzan", "Fist of the North Star", "Judgment"], acc: ["ishin", "like a dragon ishin"] },
  { id: "yakuza-p9", d: 4, t: "Comment se nomme le système de métiers façon RPG dans Yakuza: Like a Dragon ?", a: "Le système de jobs", x: ["Le système de gangs", "L'arbre du dragon", "Le rang de clan"], acc: ["jobs", "systeme de jobs", "métiers"] },
  { id: "yakuza-p10", d: 4, t: "Quel colosse, frère de sang de Majima, devient jouable dans Yakuza 4 et 5 ?", a: "Taiga Saejima", x: ["Shun Akiyama", "Masayoshi Tanimura", "Tatsuo Shinada"], acc: ["saejima", "taiga saejima"] },
  { id: "yakuza-p11", d: 4, t: "Dans Yakuza 5, quel ancien joueur de baseball déchu est l'un des héros jouables ?", a: "Tatsuo Shinada", x: ["Shun Akiyama", "Taiga Saejima", "Masayoshi Tanimura"], acc: ["shinada", "tatsuo shinada"] },
  { id: "yakuza-p12", d: 4, t: "Comment s'appelle le bar tenu par Date et fréquenté par Kiryu dans le premier jeu ?", a: "Le Serena", x: ["Le Survive", "Le Shellac", "Le Vincent"], acc: ["serena"] },
  { id: "yakuza-p13", d: 4, t: "Quel quartier réel de Tokyo a inspiré Kamurocho ?", a: "Kabukicho", x: ["Shibuya", "Akihabara", "Ginza"], acc: ["kabukicho"] },
  { id: "yakuza-p14", d: 4, t: "Quel quartier réel d'Osaka a inspiré Sotenbori ?", a: "Dotonbori", x: ["Namba", "Umeda", "Shinsekai"], acc: ["dotonbori"] },
  { id: "yakuza-p15", d: 4, t: "Quel remake de 2016 réinvente le tout premier Yakuza ?", a: "Yakuza Kiwami", x: ["Yakuza Zero", "Yakuza Ishin", "Yakuza Gaiden"], acc: ["kiwami", "yakuza kiwami"] },
  { id: "yakuza-p16", d: 4, t: "Quelle célèbre licence de manga d'arts martiaux a eu droit à un jeu du studio en 2018 ?", a: "Ken le Survivant", x: ["Dragon Ball", "Berserk", "One Piece"], acc: ["ken le survivant", "hokuto no ken", "fist of the north star"] },
  { id: "yakuza-p17", d: 4, t: "Dans Infinite Wealth, quel héros historique accompagne Ichiban comme second personnage jouable ?", a: "Kazuma Kiryu", x: ["Goro Majima", "Taiga Saejima", "Takayuki Yagami"], acc: ["kiryu", "kazuma kiryu"] },
  { id: "yakuza-p18", d: 4, t: "Quelle maladie Kiryu affronte-t-il dans Infinite Wealth ?", a: "Un cancer", x: ["Une amnésie", "La cécité", "Une paralysie"], acc: ["cancer", "un cancer"] },
  { id: "yakuza-p19", d: 4, t: "Comment se nomme la suite du spin-off policier, sortie en 2021 ?", a: "Lost Judgment", x: ["Judgment Kiwami", "Judge Eyes 2", "Yakuza Gaiden"], acc: ["lost judgment"] },
  { id: "yakuza-p20", d: 4, t: "Quel acteur japonais prête son visage et sa voix à Kazuma Kiryu ?", a: "Takaya Kuroda", x: ["Hidenari Ugaki", "Toshiki Masuda", "Kazuhiro Nakaya"], acc: ["takaya kuroda", "kuroda"] },
]);
