import { universe } from "../_build";

export const bandedessinee = universe("litterature", "Bande dessinée", [
  // --- Faciles (5) ---
  { id: "bd-f1", d: 1, t: "Quel jeune reporter à la houppette, accompagné de son chien, est le héros d'Hergé ?", a: "Tintin", x: ["Spirou", "Astérix", "Boule"] },
  { id: "bd-f2", d: 1, t: "Quel petit Gaulois d'Uderzo et Goscinny boit une potion magique ?", a: "Astérix", x: ["Obélix", "Tintin", "Iznogoud"] },
  { id: "bd-f3", d: 1, t: "Comment s'appelle le petit chien blanc de Tintin ?", a: "Milou", x: ["Idéfix", "Rantanplan", "Bill"] },
  { id: "bd-f4", d: 1, t: "Quel gros Gaulois, ami d'Astérix, transporte des menhirs ?", a: "Obélix", x: ["Abraracourcix", "Assurancetourix", "Panoramix"] },
  { id: "bd-f5", d: 1, t: "Quels petits personnages bleus vivant dans un village ont été créés par Peyo ?", a: "Les Schtroumpfs", x: ["Les Barbapapa", "Les Snorky", "Les Minions"] },
  // --- Moyennes (10) ---
  { id: "bd-m1", d: 2, t: "Quel dessinateur belge a créé Tintin ?", a: "Hergé", x: ["Peyo", "Franquin", "Morris"] },
  { id: "bd-m2", d: 2, t: "Quel cow-boy solitaire « tire plus vite que son ombre », créé par Morris ?", a: "Lucky Luke", x: ["Jerry Spring", "Tex Willer", "Buddy Longway"] },
  { id: "bd-m3", d: 2, t: "Quel druide prépare la potion magique dans Astérix ?", a: "Panoramix", x: ["Abraracourcix", "Assurancetourix", "Ordralfabétix"] },
  { id: "bd-m4", d: 2, t: "Quel groom héros de BD a été créé par Rob-Vel puis repris par Franquin ?", a: "Spirou", x: ["Gaston", "Boule", "Tintin"] },
  { id: "bd-m5", d: 2, t: "Quel employé de bureau paresseux et gaffeur a été créé par Franquin ?", a: "Gaston", x: ["Spirou", "Cubitus", "Cédric"] },
  { id: "bd-m6", d: 2, t: "Quel grand vizir de Goscinny veut « être calife à la place du calife » ?", a: "Iznogoud", x: ["Astérix", "Obélix", "Cubitus"] },
  { id: "bd-m7", d: 2, t: "Quel sorcier maléfique, aidé de son chat, veut capturer les Schtroumpfs ?", a: "Gargamel", x: ["Azraël", "Iznogoud", "Cauchemar"] },
  { id: "bd-m8", d: 2, t: "Quel cocker est le compagnon du petit Boule dans la BD de Roba ?", a: "Bill", x: ["Milou", "Idéfix", "Cubitus"] },
  { id: "bd-m9", d: 2, t: "Quel journal de BD belge a publié les aventures de Spirou ?", a: "Le Journal de Spirou", x: ["Pilote", "Métal hurlant", "Fluide glacial"] },
  { id: "bd-m10", d: 2, t: "Quel super-héros de comics américain vient de la planète Krypton ?", a: "Superman", x: ["Batman", "Spider-Man", "Iron Man"] },
  // --- Dures (15) ---
  { id: "bd-d1", d: 3, t: "Quel scénariste a créé Astérix avec Uderzo et Lucky Luke avec Morris ?", a: "René Goscinny", x: ["Albert Uderzo", "Jean Van Hamme", "Pierre Christin"] },
  { id: "bd-d2", d: 3, t: "Quel animal fantastique à longue queue préhensile Franquin a-t-il créé ?", a: "Le Marsupilami", x: ["Le Concombre masqué", "Le Chat", "Le Génie des alpages"] },
  { id: "bd-d3", d: 3, t: "Quel pilote de l'aéronavale américaine est un héros d'aviation de Charlier et Hubinon ?", a: "Buck Danny", x: ["Dan Cooper", "Michel Tanguy", "Steve Canyon"] },
  { id: "bd-d4", d: 3, t: "Quel lieutenant de cavalerie au visage buriné a été créé par Charlier et Giraud ?", a: "Blueberry", x: ["Comanche", "Durango", "Ramiro"] },
  { id: "bd-d5", d: 3, t: "Sous quel pseudonyme le dessinateur Jean Giraud signait-il ses œuvres de science-fiction ?", a: "Mœbius", x: ["Bilal", "Druillet", "Caza"] },
  { id: "bd-d6", d: 3, t: "Quel auteur de « La Foire aux immortels » et « Nikopol » est un maître de la BD de SF ?", a: "Enki Bilal", x: ["Philippe Druillet", "Jean-Claude Mézières", "Alejandro Jodorowsky"] },
  { id: "bd-d7", d: 3, t: "Quel auteur a créé « Le Chat du rabbin » et « Petit Vampire » ?", a: "Joann Sfar", x: ["Lewis Trondheim", "Christophe Blain", "Marjane Satrapi"] },
  { id: "bd-d8", d: 3, t: "Quelle autrice a raconté son enfance en Iran dans la BD « Persepolis » ?", a: "Marjane Satrapi", x: ["Julie Doucet", "Pénélope Bagieu", "Claire Bretécher"] },
  { id: "bd-d9", d: 3, t: "Quel roman graphique d'Art Spiegelman raconte la Shoah avec des souris et des chats ?", a: "Maus", x: ["Persepolis", "Fun Home", "Blankets"] },
  { id: "bd-d10", d: 3, t: "Quel amnésique tatoué d'un chiffre romain est un héros de Van Hamme et Vance ?", a: "XIII", x: ["Thorgal", "Blueberry", "Ramiro"] },
  { id: "bd-d11", d: 3, t: "Quel héros viking et fantastique a été créé par Van Hamme et Rosinski ?", a: "Thorgal", x: ["Ramiro", "Comanche", "Blueberry"] },
  { id: "bd-d12", d: 3, t: "Quels deux gentlemen britanniques d'Edgar P. Jacobs vivent des aventures fantastiques ?", a: "Blake et Mortimer", x: ["Spirou et Fantasio", "Johan et Pirlouit", "Boule et Bill"] },
  { id: "bd-d13", d: 3, t: "Quelle série humoristique de Gotlib est parue dans « Pilote » puis « Fluide glacial » ?", a: "La Rubrique-à-brac", x: ["Achille Talon", "Le Génie des alpages", "Les Bidochon"] },
  { id: "bd-d14", d: 3, t: "Quel couple de Français moyens a été croqué par Christian Binet ?", a: "Les Bidochon", x: ["Les Frustrés", "Le Génie des alpages", "Le Chat"] },
  { id: "bd-d15", d: 3, t: "Quel gamin à la houppette pose des questions naïves sur la vie dans la BD de Zep ?", a: "Titeuf", x: ["Cédric", "Boule", "Cubitus"] },
  // --- Pro (20) ---
  { id: "bd-p1", d: 4, t: "En quelle année Tintin apparaît-il pour la première fois, dans « Tintin au pays des Soviets » ?", a: "1929", x: ["1919", "1939", "1946"] },
  { id: "bd-p2", d: 4, t: "Quel personnage barbu, ami de Tintin et amateur de whisky, jure « mille sabords » ?", a: "Le capitaine Haddock", x: ["Le professeur Tournesol", "Le général Alcazar", "Le docteur Müller"] },
  { id: "bd-p3", d: 4, t: "Comment s'appelle le savant distrait et dur d'oreille des aventures de Tintin ?", a: "Le professeur Tournesol", x: ["Le capitaine Haddock", "Le docteur Müller", "Le colonel Sponsz"] },
  { id: "bd-p4", d: 4, t: "De quel « art » la bande dessinée est-elle surnommée, selon l'expression consacrée ?", a: "Le neuvième art", x: ["Le septième art", "Le huitième art", "Le dixième art"] },
  { id: "bd-p5", d: 4, t: "Quel festival français, créé en 1974, est la plus grande manifestation européenne de BD ?", a: "Le Festival d'Angoulême", x: ["Le Festival de Cannes", "Le Salon du Bourget", "Le Festival de Lucca"] },
  { id: "bd-p6", d: 4, t: "Quel barde des albums d'Astérix est régulièrement bâillonné pendant les banquets ?", a: "Assurancetourix", x: ["Abraracourcix", "Ordralfabétix", "Agecanonix"] },
  { id: "bd-p7", d: 4, t: "Comment s'appelle le chef du village gaulois, porté sur un bouclier, dans Astérix ?", a: "Abraracourcix", x: ["Assurancetourix", "Panoramix", "Ordralfabétix"] },
  { id: "bd-p8", d: 4, t: "Quel dessinateur italien a donné vie au personnage de western Tex Willer ?", a: "Aurelio Galleppini", x: ["Hugo Pratt", "Milo Manara", "Sergio Bonelli"] },
  { id: "bd-p9", d: 4, t: "Quel marin aventurier romantique a été créé par Hugo Pratt ?", a: "Corto Maltese", x: ["Tex Willer", "Bernard Prince", "Bruno Brazil"] },
  { id: "bd-p10", d: 4, t: "Quel auteur britannique a créé la série de comics « Sandman » ?", a: "Neil Gaiman", x: ["Alan Moore", "Frank Miller", "Grant Morrison"] },
  { id: "bd-p11", d: 4, t: "Quel scénariste a écrit « Watchmen » et « V pour Vendetta » ?", a: "Alan Moore", x: ["Neil Gaiman", "Frank Miller", "Warren Ellis"] },
  { id: "bd-p12", d: 4, t: "Quel auteur a redéfini Batman avec « The Dark Knight Returns » et créé « Sin City » ?", a: "Frank Miller", x: ["Alan Moore", "Jim Lee", "Todd McFarlane"] },
  { id: "bd-p13", d: 4, t: "Quel scénariste a cocréé Spider-Man avec le dessinateur Steve Ditko ?", a: "Stan Lee", x: ["Jack Kirby", "Bob Kane", "Bill Finger"] },
  { id: "bd-p14", d: 4, t: "Quel dessinateur a cocréé les X-Men, les Quatre Fantastiques et Hulk avec Stan Lee ?", a: "Jack Kirby", x: ["Steve Ditko", "Bob Kane", "John Romita"] },
  { id: "bd-p15", d: 4, t: "Quelle autrice française pionnière a croqué « Les Frustrés » et « Agrippine » ?", a: "Claire Bretécher", x: ["Pénélope Bagieu", "Florence Cestac", "Marjane Satrapi"] },
  { id: "bd-p16", d: 4, t: "Quelle BD de Pénélope Bagieu portraiture des femmes qui ont marqué l'Histoire ?", a: "Culottées", x: ["Persepolis", "Aya de Yopougon", "Le Bleu est une couleur chaude"] },
  { id: "bd-p17", d: 4, t: "Quelle série d'Uderzo et Goscinny se déroule « en 50 avant Jésus-Christ » ?", a: "Astérix", x: ["Alix", "Iznogoud", "Oumpah-pah"] },
  { id: "bd-p18", d: 4, t: "Quelle longue série de Cauvin met en scène deux soldats pendant la guerre de Sécession ?", a: "Les Tuniques bleues", x: ["Boule et Bill", "Les Petits Hommes", "Cédric"] },
  { id: "bd-p19", d: 4, t: "Quel super-héros aveugle de Marvel est aussi un avocat justicier ?", a: "Daredevil", x: ["Punisher", "Hawkeye", "Elektra"] },
  { id: "bd-p20", d: 4, t: "Quel dessinateur belge a créé Gaston Lagaffe et donné vie au Marsupilami ?", a: "Franquin", x: ["Peyo", "Morris", "Roba"] },
]);
