import { universe } from "../_build";

export const policier = universe("litterature", "Policier", [
  // --- Faciles (5) ---
  { id: "pol-f1", d: 1, t: "Quel détective belge à moustache est le héros de nombreux romans d'Agatha Christie ?", a: "Hercule Poirot", x: ["Sherlock Holmes", "Arsène Lupin", "Nestor Burma"] },
  { id: "pol-f2", d: 1, t: "Quel détective anglais vit au 221B Baker Street avec le docteur Watson ?", a: "Sherlock Holmes", x: ["Hercule Poirot", "Nestor Burma", "Philip Marlowe"] },
  { id: "pol-f3", d: 1, t: "Quel écrivain français a créé le gentleman cambrioleur Arsène Lupin ?", a: "Maurice Leblanc", x: ["Gaston Leroux", "Georges Simenon", "Maurice Renard"] },
  { id: "pol-f4", d: 1, t: "Quelle romancière britannique est surnommée la « reine du crime » ?", a: "Agatha Christie", x: ["P.D. James", "Ruth Rendell", "Patricia Cornwell"] },
  { id: "pol-f5", d: 1, t: "Quel commissaire parisien, amateur de pipe, est le héros de Georges Simenon ?", a: "Maigret", x: ["Poirot", "Lupin", "Burma"] },
  // --- Moyennes (10) ---
  { id: "pol-m1", d: 2, t: "Quel écrivain écossais a créé le personnage de Sherlock Holmes ?", a: "Arthur Conan Doyle", x: ["Agatha Christie", "Edgar Allan Poe", "Wilkie Collins"] },
  { id: "pol-m2", d: 2, t: "Quel roman d'Agatha Christie met en scène dix invités piégés sur une île ?", a: "Ils étaient dix", x: ["Le Crime de l'Orient-Express", "Mort sur le Nil", "Le Meurtre de Roger Ackroyd"], acc: ["dix petits nègres"] },
  { id: "pol-m3", d: 2, t: "Dans quel roman d'Agatha Christie un meurtre a lieu à bord d'un train bloqué par la neige ?", a: "Le Crime de l'Orient-Express", x: ["Mort sur le Nil", "Ils étaient dix", "ABC contre Poirot"] },
  { id: "pol-m4", d: 2, t: "Quel auteur américain a créé le détective privé cynique Philip Marlowe ?", a: "Raymond Chandler", x: ["Dashiell Hammett", "James Ellroy", "Mickey Spillane"] },
  { id: "pol-m5", d: 2, t: "Quel écrivain a créé Jack Reacher, ancien de la police militaire ?", a: "Lee Child", x: ["Michael Connelly", "Harlan Coben", "David Baldacci"] },
  { id: "pol-m6", d: 2, t: "Quel personnage de Thomas Harris est un psychiatre cannibale ?", a: "Hannibal Lecter", x: ["Norman Bates", "Dexter Morgan", "Tom Ripley"] },
  { id: "pol-m7", d: 2, t: "Quel roman de Thomas Harris oppose Clarice Starling à Hannibal Lecter ?", a: "Le Silence des agneaux", x: ["Dragon rouge", "Hannibal", "American Psycho"] },
  { id: "pol-m8", d: 2, t: "Quel auteur suédois a écrit la trilogie « Millénium » ?", a: "Stieg Larsson", x: ["Henning Mankell", "Jo Nesbø", "Camilla Läckberg"] },
  { id: "pol-m9", d: 2, t: "Comment s'appelle la hackeuse héroïne de la trilogie Millénium ?", a: "Lisbeth Salander", x: ["Mikael Blomkvist", "Kurt Wallander", "Harry Hole"] },
  { id: "pol-m10", d: 2, t: "Quel écrivain américain a créé l'inspecteur Harry Bosch de la police de Los Angeles ?", a: "Michael Connelly", x: ["Lee Child", "James Patterson", "Robert Crais"] },
  // --- Dures (15) ---
  { id: "pol-d1", d: 3, t: "Quel écrivain américain a écrit « Le Faucon maltais » avec le détective Sam Spade ?", a: "Dashiell Hammett", x: ["Raymond Chandler", "James M. Cain", "Chester Himes"] },
  { id: "pol-d2", d: 3, t: "Quel personnage de Patricia Highsmith est un imposteur et meurtrier séduisant ?", a: "Tom Ripley", x: ["Hannibal Lecter", "Dexter Morgan", "Norman Bates"] },
  { id: "pol-d3", d: 3, t: "Quel commissaire suédois de Henning Mankell exerce à Ystad ?", a: "Kurt Wallander", x: ["Harry Hole", "Martin Beck", "Erlendur Sveinsson"] },
  { id: "pol-d4", d: 3, t: "Quel détective alcoolique d'Oslo est le héros des romans de Jo Nesbø ?", a: "Harry Hole", x: ["Kurt Wallander", "Carl Mørck", "Harry Bosch"] },
  { id: "pol-d5", d: 3, t: "Quel auteur américain met en scène l'avocat Mickey Haller, le « Lincoln Lawyer » ?", a: "Michael Connelly", x: ["John Grisham", "Scott Turow", "David Baldacci"] },
  { id: "pol-d6", d: 3, t: "Quel écrivain américain a écrit « L'Affaire Pélican » et « La Firme », des thrillers judiciaires ?", a: "John Grisham", x: ["Michael Connelly", "David Baldacci", "Scott Turow"] },
  { id: "pol-d7", d: 3, t: "Quelle écrivaine française a créé le commissaire Adamsberg ?", a: "Fred Vargas", x: ["Jean-Christophe Grangé", "Pierre Lemaitre", "Franck Thilliez"] },
  { id: "pol-d8", d: 3, t: "Quel roman de Jean-Christophe Grangé met en scène des crimes rituels dans une ville de montagne ?", a: "Les Rivières pourpres", x: ["Le Vol des cigognes", "L'Empire des loups", "Le Concile de pierre"] },
  { id: "pol-d9", d: 3, t: "Quel écrivain a signé « Au revoir là-haut », prix Goncourt, ainsi que le polar « Alex » ?", a: "Pierre Lemaitre", x: ["Fred Vargas", "Franck Thilliez", "Bernard Minier"] },
  { id: "pol-d10", d: 3, t: "Quel duo d'auteurs suédois a créé le policier Martin Beck dans les années 60 ?", a: "Sjöwall et Wahlöö", x: ["Boileau et Narcejac", "Dupont et Durand", "Larsson et Mankell"] },
  { id: "pol-d11", d: 3, t: "Quel duo français a écrit « Celle qui n'était plus », adapté au cinéma en « Les Diaboliques » ?", a: "Boileau et Narcejac", x: ["Sjöwall et Wahlöö", "Barjavel et Bordage", "Erckmann et Chatrian"] },
  { id: "pol-d12", d: 3, t: "Quel roman policier d'Umberto Eco se déroule dans une abbaye médiévale ?", a: "Le Nom de la rose", x: ["Le Pendule de Foucault", "Da Vinci Code", "Les Piliers de la Terre"] },
  { id: "pol-d13", d: 3, t: "Quel écrivain japonais a écrit « Le Dévouement du suspect X » ?", a: "Keigo Higashino", x: ["Natsuo Kirino", "Seishi Yokomizo", "Fuminori Nakamura"] },
  { id: "pol-d14", d: 3, t: "Quel enquêteur islandais d'Arnaldur Indriðason est mélancolique et solitaire ?", a: "Erlendur", x: ["Wallander", "Rebus", "Adamsberg"] },
  { id: "pol-d15", d: 3, t: "Quel écrivain écossais a créé l'inspecteur John Rebus, à Édimbourg ?", a: "Ian Rankin", x: ["Peter May", "Val McDermid", "Denise Mina"] },
  // --- Pro (20) ---
  { id: "pol-p1", d: 4, t: "Quelle nouvelle d'Edgar Allan Poe de 1841 est considérée comme le premier récit de détective ?", a: "Double assassinat dans la rue Morgue", x: ["Le Scarabée d'or", "La Lettre volée", "Le Chat noir"] },
  { id: "pol-p2", d: 4, t: "Quel détective imaginé par Edgar Allan Poe précède Sherlock Holmes ?", a: "Auguste Dupin", x: ["Hercule Poirot", "Nestor Burma", "Sam Spade"] },
  { id: "pol-p3", d: 4, t: "Quel roman de Wilkie Collins de 1868 est un des premiers romans policiers anglais ?", a: "Pierre de lune", x: ["La Dame en blanc", "Le Mystère d'Edwin Drood", "Bleak House"] },
  { id: "pol-p4", d: 4, t: "Quel écrivain belge a créé le commissaire Maigret ?", a: "Georges Simenon", x: ["Maurice Leblanc", "Gaston Leroux", "Stanislas-André Steeman"] },
  { id: "pol-p5", d: 4, t: "Quel roman de Gaston Leroux met en scène le jeune journaliste détective Rouletabille ?", a: "Le Mystère de la chambre jaune", x: ["Le Fantôme de l'Opéra", "Chéri-Bibi", "Le Parfum de la dame en noir"] },
  { id: "pol-p6", d: 4, t: "Quel auteur américain a écrit « Le Dahlia noir » et « L.A. Confidential » ?", a: "James Ellroy", x: ["Raymond Chandler", "Dashiell Hammett", "Elmore Leonard"] },
  { id: "pol-p7", d: 4, t: "Quel écrivain a créé les détectives de Harlem Ed Cercueil et Fossoyeur Jones ?", a: "Chester Himes", x: ["Walter Mosley", "James Baldwin", "Donald Goines"] },
  { id: "pol-p8", d: 4, t: "Quel roman de James M. Cain a pour intrigue un meurtre commis pour une assurance-vie ?", a: "Assurance sur la mort", x: ["Le facteur sonne toujours deux fois", "Mildred Pierce", "Le Bluffeur"] },
  { id: "pol-p9", d: 4, t: "Quel écrivain italien a créé le commissaire sicilien Salvo Montalbano ?", a: "Andrea Camilleri", x: ["Umberto Eco", "Gianrico Carofiglio", "Massimo Carlotto"] },
  { id: "pol-p10", d: 4, t: "Quel auteur américain de romans noirs a écrit « Pop. 1280 » et « L'Assassin qui est en moi » ?", a: "Jim Thompson", x: ["David Goodis", "Cornell Woolrich", "Horace McCoy"] },
  { id: "pol-p11", d: 4, t: "Quel écrivain français a créé le détective parisien Nestor Burma ?", a: "Léo Malet", x: ["Georges Simenon", "Frédéric Dard", "Sébastien Japrisot"] },
  { id: "pol-p12", d: 4, t: "Sous quel pseudonyme Frédéric Dard a-t-il écrit une célèbre série policière argotique ?", a: "San-Antonio", x: ["Le Poulpe", "OSS 117", "Le Gorille"] },
  { id: "pol-p13", d: 4, t: "Quel écrivain danois a écrit la série « Département V » avec l'inspecteur Carl Mørck ?", a: "Jussi Adler-Olsen", x: ["Jo Nesbø", "Karin Fossum", "Anne Holt"] },
  { id: "pol-p14", d: 4, t: "Quel roman de Donna Tartt suit un meurtre dans un cercle d'étudiants en lettres classiques ?", a: "Le Maître des illusions", x: ["Le Chardonneret", "La Vérité sur l'affaire Harry Quebert", "Les Apparences"] },
  { id: "pol-p15", d: 4, t: "Quel écrivain suisse a écrit « La Vérité sur l'affaire Harry Quebert » ?", a: "Joël Dicker", x: ["Bernard Minier", "Franck Thilliez", "Maxime Chattam"] },
  { id: "pol-p16", d: 4, t: "Quel auteur français a écrit la Trilogie du Mal, ouverte par « L'Âme du mal » ?", a: "Maxime Chattam", x: ["Franck Thilliez", "Bernard Minier", "Jean-Christophe Grangé"] },
  { id: "pol-p17", d: 4, t: "Quel commissaire au lourd passé est un personnage récurrent des thrillers de Franck Thilliez ?", a: "Franck Sharko", x: ["Pierre Niémans", "Martin Servaz", "Camille Verhœven"] },
  { id: "pol-p18", d: 4, t: "Quelle romancière a créé l'anthropologue judiciaire Temperance Brennan, qui inspire la série Bones ?", a: "Kathy Reichs", x: ["Patricia Cornwell", "Tess Gerritsen", "Karin Slaughter"] },
  { id: "pol-p19", d: 4, t: "Quel médecin légiste, héroïne de Patricia Cornwell, enquête à Richmond ?", a: "Kay Scarpetta", x: ["Temperance Brennan", "Clarice Starling", "Lisbeth Salander"] },
  { id: "pol-p20", d: 4, t: "Quel prix littéraire français, tirant son nom de la police judiciaire parisienne, récompense un roman policier ?", a: "Le prix du Quai des Orfèvres", x: ["Le prix Goncourt", "Le prix Femina", "Le prix Renaudot"] },
]);
