import { universe } from "../_build";

export const sciencefiction = universe("litterature", "Science-fiction", [
  // --- Faciles (5) ---
  { id: "sf-f1", d: 1, t: "Quel auteur français du XIXe siècle a écrit « Vingt mille lieues sous les mers » ?", a: "Jules Verne", x: ["Victor Hugo", "Émile Zola", "Alexandre Dumas"] },
  { id: "sf-f2", d: 1, t: "Dans quel roman de Mary Shelley un savant crée une créature à partir de cadavres ?", a: "Frankenstein", x: ["Dracula", "L'Île du docteur Moreau", "Le Golem"] },
  { id: "sf-f3", d: 1, t: "Quel auteur a imaginé une société surveillée par « Big Brother » dans « 1984 » ?", a: "George Orwell", x: ["Aldous Huxley", "Ray Bradbury", "H.G. Wells"] },
  { id: "sf-f4", d: 1, t: "Quelles créatures venues de l'espace envahissent la Terre dans « La Guerre des mondes » ?", a: "Les Martiens", x: ["Les Vénusiens", "Les robots", "Les zombies"] },
  { id: "sf-f5", d: 1, t: "Quel écrivain britannique a écrit « La Machine à explorer le temps » ?", a: "H.G. Wells", x: ["Jules Verne", "George Orwell", "Arthur C. Clarke"] },
  // --- Moyennes (10) ---
  { id: "sf-m1", d: 2, t: "Quel auteur américain a écrit le cycle « Fondation » ?", a: "Isaac Asimov", x: ["Arthur C. Clarke", "Philip K. Dick", "Robert Heinlein"] },
  { id: "sf-m2", d: 2, t: "Quel roman de Frank Herbert se déroule sur la planète désertique Arrakis ?", a: "Dune", x: ["Hypérion", "Fondation", "Ubik"] },
  { id: "sf-m3", d: 2, t: "Quel écrivain a formulé les trois lois de la robotique ?", a: "Isaac Asimov", x: ["Philip K. Dick", "Arthur C. Clarke", "Ray Bradbury"] },
  { id: "sf-m4", d: 2, t: "Dans « Fahrenheit 451 » de Ray Bradbury, que brûlent les pompiers ?", a: "Les livres", x: ["Les maisons", "Les drapeaux", "Les forêts"] },
  { id: "sf-m5", d: 2, t: "Quel roman d'Aldous Huxley décrit une société où les humains sont fabriqués en usine ?", a: "Le Meilleur des mondes", x: ["1984", "Nous", "Un bonheur insoutenable"] },
  { id: "sf-m6", d: 2, t: "Quel auteur a écrit « Ubik » et « Les androïdes rêvent-ils de moutons électriques ? » ?", a: "Philip K. Dick", x: ["Isaac Asimov", "William Gibson", "Frank Herbert"] },
  { id: "sf-m7", d: 2, t: "Quel classique de 1818 est considéré comme l'un des premiers romans de science-fiction ?", a: "Frankenstein", x: ["Dracula", "Le Château d'Otrante", "Les Voyages de Gulliver"] },
  { id: "sf-m8", d: 2, t: "Quel écrivain britannique a coécrit « 2001 : l'Odyssée de l'espace » avec Stanley Kubrick ?", a: "Arthur C. Clarke", x: ["Isaac Asimov", "H.G. Wells", "Ray Bradbury"] },
  { id: "sf-m9", d: 2, t: "Quel roman de William Gibson de 1984 a fondé le mouvement cyberpunk ?", a: "Neuromancien", x: ["Snow Crash", "Schismatrice", "Câblé"] },
  { id: "sf-m10", d: 2, t: "Quelle romancière a écrit « La Main gauche de la nuit » et le cycle de Hain ?", a: "Ursula K. Le Guin", x: ["Margaret Atwood", "Mary Shelley", "Octavia Butler"] },
  // --- Dures (15) ---
  { id: "sf-d1", d: 3, t: "Quel roman de Dan Simmons met en scène des pèlerins voyageant vers les Tombeaux du Temps ?", a: "Hypérion", x: ["Dune", "Fondation", "La Stratégie Ender"] },
  { id: "sf-d2", d: 3, t: "Quel auteur polonais a écrit « Solaris », adapté au cinéma par Tarkovski ?", a: "Stanislas Lem", x: ["Isaac Asimov", "Arkadi Strougatski", "Ievgueni Zamiatine"] },
  { id: "sf-d3", d: 3, t: "Quel roman de Margaret Atwood décrit la république théocratique de Galaad ?", a: "La Servante écarlate", x: ["1984", "Le Meilleur des mondes", "Bienvenue à Gattaca"] },
  { id: "sf-d4", d: 3, t: "Quel cycle d'Isaac Asimov raconte le déclin d'un empire galactique et la « psychohistoire » ?", a: "Fondation", x: ["Dune", "Les Robots", "Hypérion"] },
  { id: "sf-d5", d: 3, t: "Quel roman d'Orson Scott Card suit un enfant prodige entraîné pour la guerre ?", a: "La Stratégie Ender", x: ["Starship Troopers", "La Guerre éternelle", "Berserker"] },
  { id: "sf-d6", d: 3, t: "Quel roman de Robert Heinlein de 1959 met en scène une infanterie en armure contre des insectes ?", a: "Étoiles, garde-à-vous", x: ["La Guerre éternelle", "Berserker", "Le Vieil Homme et la Guerre"], acc: ["starship troopers"] },
  { id: "sf-d7", d: 3, t: "Quel auteur français a écrit « La Planète des singes » ?", a: "Pierre Boulle", x: ["René Barjavel", "Jules Verne", "Bernard Werber"] },
  { id: "sf-d8", d: 3, t: "Quel roman de René Barjavel évoque une civilisation engloutie et un amour éternel ?", a: "La Nuit des temps", x: ["Ravage", "Le Voyageur imprudent", "La Faim du tigre"] },
  { id: "sf-d9", d: 3, t: "Quel roman dystopique russe de Zamiatine a inspiré « 1984 » ?", a: "Nous", x: ["Le Meilleur des mondes", "Fahrenheit 451", "La Kallocaïne"], acc: ["nous autres"] },
  { id: "sf-d10", d: 3, t: "Quel humoriste britannique a écrit « Le Guide du voyageur galactique » ?", a: "Douglas Adams", x: ["Terry Pratchett", "Neil Gaiman", "Iain Banks"] },
  { id: "sf-d11", d: 3, t: "Quelle réponse un super-ordinateur donne-t-il à la « grande question sur la vie » dans Le Guide du voyageur galactique ?", a: "42", x: ["7", "0", "101"] },
  { id: "sf-d12", d: 3, t: "Quel écrivain écossais a imaginé une utopie galactique nommée « la Culture » ?", a: "Iain Banks", x: ["Alastair Reynolds", "Peter Hamilton", "Dan Simmons"] },
  { id: "sf-d13", d: 3, t: "Quel roman de H.G. Wells met en scène un homme devenu transparent ?", a: "L'Homme invisible", x: ["La Machine à explorer le temps", "L'Île du docteur Moreau", "Les Premiers Hommes dans la Lune"] },
  { id: "sf-d14", d: 3, t: "Quel écrivain français contemporain a écrit la trilogie « Les Fourmis » ?", a: "Bernard Werber", x: ["Pierre Bordage", "René Barjavel", "Michel Houellebecq"] },
  { id: "sf-d15", d: 3, t: "Quel roman de Liu Cixin débute une trilogie sur un contact extraterrestre ?", a: "Le Problème à trois corps", x: ["La Stratégie Ender", "Contact", "Rendez-vous avec Rama"] },
  // --- Pro (20) ---
  { id: "sf-p1", d: 4, t: "Quel prix récompense chaque année les meilleures œuvres de science-fiction, du nom d'un éditeur pionnier ?", a: "Le prix Hugo", x: ["Le prix Nebula", "Le prix Locus", "Le prix Goncourt"] },
  { id: "sf-p2", d: 4, t: "Quel éditeur américain a donné son nom au prix Hugo et popularisé le terme « science fiction » ?", a: "Hugo Gernsback", x: ["John W. Campbell", "Isaac Asimov", "Forrest Ackerman"] },
  { id: "sf-p3", d: 4, t: "Quel roman de Walter M. Miller suit des moines préservant le savoir après un cataclysme nucléaire ?", a: "Un cantique pour Leibowitz", x: ["La Route", "Malevil", "Le Fléau"] },
  { id: "sf-p4", d: 4, t: "Quel roman de Dan Simmons fait directement suite à Hypérion ?", a: "La Chute d'Hypérion", x: ["Endymion", "Ilium", "Olympos"] },
  { id: "sf-p5", d: 4, t: "Quel auteur a écrit « La Guerre éternelle », inspiré de son expérience au Vietnam ?", a: "Joe Haldeman", x: ["Robert Heinlein", "Orson Scott Card", "Jerry Pournelle"] },
  { id: "sf-p6", d: 4, t: "Quel roman de Philip K. Dick imagine une Amérique où l'Axe a gagné la guerre ?", a: "Le Maître du Haut Château", x: ["Ubik", "Substance mort", "Loterie solaire"] },
  { id: "sf-p7", d: 4, t: "Quel écrivain français, pionnier du genre, a écrit « Le Vingtième siècle » et des récits d'anticipation illustrés ?", a: "Albert Robida", x: ["Jules Verne", "J.-H. Rosny aîné", "Camille Flammarion"] },
  { id: "sf-p8", d: 4, t: "Quel auteur a écrit « La Mort de la Terre » et forgé le mot « astronautique » ?", a: "J.-H. Rosny aîné", x: ["Jules Verne", "Albert Robida", "Maurice Renard"] },
  { id: "sf-p9", d: 4, t: "Quel recueil de Ray Bradbury rassemble des récits sur la colonisation de Mars ?", a: "Chroniques martiennes", x: ["Fahrenheit 451", "L'Homme illustré", "La Foire des ténèbres"] },
  { id: "sf-p10", d: 4, t: "Quel roman de Daniel Keyes suit Charlie, un homme dont l'intelligence est décuplée ?", a: "Des fleurs pour Algernon", x: ["L'Homme démoli", "Terminus les étoiles", "Les Plus qu'humains"] },
  { id: "sf-p11", d: 4, t: "Quel prix, décerné par les auteurs américains, complète souvent le prix Hugo ?", a: "Le prix Nebula", x: ["Le prix Hugo", "Le prix Locus", "Le prix Philip K. Dick"] },
  { id: "sf-p12", d: 4, t: "Quels deux auteurs cyberpunk ont coécrit « La Machine à différences », roman steampunk fondateur ?", a: "Gibson et Sterling", x: ["Asimov et Clarke", "Niven et Pournelle", "Strougatski et Lem"] },
  { id: "sf-p13", d: 4, t: "Quel roman des frères Strougatski a inspiré le film « Stalker » de Tarkovski ?", a: "Pique-nique au bord du chemin", x: ["Solaris", "Il est difficile d'être un dieu", "Le Lundi commence le samedi"] },
  { id: "sf-p14", d: 4, t: "Quel roman d'Arthur C. Clarke suit l'exploration d'un vaisseau extraterrestre cylindrique ?", a: "Rendez-vous avec Rama", x: ["2001 : l'Odyssée de l'espace", "Les Fontaines du paradis", "La Cité et les Astres"] },
  { id: "sf-p15", d: 4, t: "Quel auteur britannique de space opera a écrit la trilogie « L'Aube de la nuit » ?", a: "Peter F. Hamilton", x: ["Alastair Reynolds", "Iain Banks", "Stephen Baxter"] },
  { id: "sf-p16", d: 4, t: "Quel roman de 1953 d'Alfred Bester met en scène une société de télépathes et un meurtre ?", a: "L'Homme démoli", x: ["Terminus les étoiles", "Les Plus qu'humains", "Demain les chiens"] },
  { id: "sf-p17", d: 4, t: "Quel recueil de Clifford Simak imagine des chiens héritant de la Terre après les humains ?", a: "Demain les chiens", x: ["Chroniques martiennes", "Le Grand Livre", "La Patrouille du temps"] },
  { id: "sf-p18", d: 4, t: "Quelle autrice afro-américaine a écrit « La Parabole du semeur » et le cycle Xénogenèse ?", a: "Octavia Butler", x: ["Ursula K. Le Guin", "Margaret Atwood", "Nnedi Okorafor"] },
  { id: "sf-p19", d: 4, t: "Quel roman de Connie Willis envoie une historienne dans l'Angleterre médiévale de la peste ?", a: "Le Grand Livre", x: ["La Patrouille du temps", "Blackout", "Les Portes d'Anubis"] },
  { id: "sf-p20", d: 4, t: "Quel auteur français a écrit le space opera « Les Guerriers du silence » ?", a: "Pierre Bordage", x: ["Bernard Werber", "René Barjavel", "Alain Damasio"] },
]);
