import type { Question } from '../../core/models';

/**
 * Banque de questions du quiz.
 *
 * Pour AJOUTER des questions : copiez un objet ci-dessous, donnez-lui un `id`
 * unique, choisissez un `theme` existant (voir THEMES dans core/models.ts),
 * une `difficulty` (1 facile, 2 moyen, 3 difficile), au moins 3 `distractors`
 * (mauvaises réponses pour le mode QCM) et, si vous voulez, des `hints`
 * (indices progressifs qui coûtent des points) et des `acceptable` (autres
 * orthographes acceptées en mode réponse libre).
 *
 * Pour AJOUTER un thème : ajoutez-le à THEMES + THEME_META dans core/models.ts,
 * puis taguez de nouvelles questions avec.
 */
export const QUESTIONS: Question[] = [
  // ----- Manga / Anime ------------------------------------------------------
  {
    id: 'manga-1',
    theme: 'manga',
    difficulty: 1,
    text: 'Dans Naruto, quel est le grand rêve de Naruto Uzumaki ?',
    answer: 'Devenir Hokage',
    distractors: ['Devenir capitaine', 'Trouver le One Piece', 'Devenir Roi des Pirates'],
    hints: ['Le Hokage est le chef du village de Konoha.'],
  },
  {
    id: 'manga-2',
    theme: 'manga',
    difficulty: 1,
    text: 'Dans One Piece, quel type de fruit du démon a mangé Luffy ?',
    answer: 'Le fruit du caoutchouc (Gomu Gomu)',
    acceptable: ['caoutchouc', 'gomu gomu', 'gum gum'],
    distractors: ['Le fruit du feu', 'Le fruit des ténèbres', 'Le fruit de la glace'],
  },
  {
    id: 'manga-3',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans Dragon Ball, comment s\'appelle la première transformation aux cheveux dorés ?',
    answer: 'Super Saiyan',
    acceptable: ['super saiyen', 'ssj'],
    distractors: ['Ultra Instinct', 'Kaio-ken', 'Super Namek'],
    hints: ['Goku l\'atteint pour la première fois face à Freezer.'],
  },
  {
    id: 'manga-4',
    theme: 'manga',
    difficulty: 2,
    text: 'Qui est le mangaka (auteur) de One Piece ?',
    answer: 'Eiichirō Oda',
    acceptable: ['oda'],
    distractors: ['Masashi Kishimoto', 'Akira Toriyama', 'Tite Kubo'],
  },
  {
    id: 'manga-5',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans L\'Attaque des Titans, comment s\'appelle le héros principal ?',
    answer: 'Eren Jäger',
    acceptable: ['eren', 'eren yeager', 'eren jaeger'],
    distractors: ['Levi', 'Armin', 'Mikasa'],
  },
  {
    id: 'manga-6',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Death Note, quel est le vrai nom du détective « L » ?',
    answer: 'L Lawliet',
    acceptable: ['lawliet'],
    distractors: ['Light Yagami', 'Near', 'Mello'],
    hints: ['Son prénom est aussi la lettre L.', 'Nom de famille : Lawliet.'],
  },
  {
    id: 'manga-7',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans Naruto, quel démon-renard est scellé en lui ?',
    answer: 'Kurama (le démon à neuf queues)',
    acceptable: ['kurama', 'kyubi', 'kyūbi', 'neuf queues'],
    distractors: ['Shukaku', 'Gyuki', 'Son Goku le singe'],
  },
  {
    id: 'manga-8',
    theme: 'manga',
    difficulty: 1,
    text: 'Quel est le nom du chat-robot venu du futur dans le manga éponyme ?',
    answer: 'Doraemon',
    distractors: ['Doremi', 'Totoro', 'Luna'],
  },
  {
    id: 'manga-9',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Hunter x Hunter, qui est le meilleur ami de Gon ?',
    answer: 'Killua Zoldyck',
    acceptable: ['killua', 'kirua'],
    distractors: ['Kurapika', 'Leorio', 'Hisoka'],
  },
  {
    id: 'manga-10',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans Demon Slayer, comment s\'appelle le héros dont la sœur est devenue un démon ?',
    answer: 'Tanjiro Kamado',
    acceptable: ['tanjiro'],
    distractors: ['Zenitsu', 'Inosuke', 'Giyu'],
    hints: ['Sa sœur s\'appelle Nezuko.'],
  },

  // ----- Jeux vidéo ---------------------------------------------------------
  {
    id: 'jv-1',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quel plombier moustachu est la mascotte de Nintendo ?',
    answer: 'Mario',
    distractors: ['Luigi', 'Sonic', 'Link'],
  },
  {
    id: 'jv-2',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Dans quel jeu construit-on un monde avec des blocs cubiques ?',
    answer: 'Minecraft',
    distractors: ['Roblox', 'Terraria', 'Fortnite'],
  },
  {
    id: 'jv-3',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Quelle entreprise a créé la console PlayStation ?',
    answer: 'Sony',
    distractors: ['Microsoft', 'Nintendo', 'Sega'],
  },
  {
    id: 'jv-4',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quel est le Pokémon numéro 25 du Pokédex national ?',
    answer: 'Pikachu',
    distractors: ['Évoli', 'Bulbizarre', 'Carapuce'],
    hints: ['C\'est un Pokémon électrique tout jaune.'],
  },
  {
    id: 'jv-5',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Dans The Legend of Zelda, quel est le nom du héros que l\'on incarne ?',
    answer: 'Link',
    distractors: ['Zelda', 'Ganon', 'Epona'],
    hints: ['La princesse, elle, s\'appelle Zelda.'],
  },
  {
    id: 'jv-6',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'En quelle année est sorti le premier Super Mario Bros. ?',
    answer: '1985',
    distractors: ['1983', '1990', '1987'],
    hints: ['Milieu des années 80, sur la NES.'],
  },
  {
    id: 'jv-7',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Quel jeu de tir héroïque 6 contre 6 de Blizzard est sorti en 2016 ?',
    answer: 'Overwatch',
    distractors: ['Valorant', 'Apex Legends', 'Team Fortress 2'],
  },
  {
    id: 'jv-8',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quel jeu mobile de 2016 fait attraper des créatures en réalité augmentée ?',
    answer: 'Pokémon GO',
    acceptable: ['pokemon go'],
    distractors: ['Ingress', 'Harry Potter Wizards Unite', 'Jurassic World Alive'],
  },
  {
    id: 'jv-9',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Qui est le créateur de la série Metal Gear ?',
    answer: 'Hideo Kojima',
    acceptable: ['kojima'],
    distractors: ['Shigeru Miyamoto', 'Hironobu Sakaguchi', 'Yoko Taro'],
  },
  {
    id: 'jv-10',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Dans Fortnite, comment s\'appelle le mode où 100 joueurs s\'affrontent ?',
    answer: 'Battle Royale',
    distractors: ['Sauver le monde', 'Créatif', 'Arène'],
  },

  // ----- Séries -------------------------------------------------------------
  {
    id: 'serie-1',
    theme: 'series',
    difficulty: 1,
    text: 'Dans Game of Thrones, quelle maison a pour devise « Winter is coming » ?',
    answer: 'Stark',
    distractors: ['Lannister', 'Targaryen', 'Baratheon'],
  },
  {
    id: 'serie-2',
    theme: 'series',
    difficulty: 2,
    text: 'Quelle série espagnole suit un braquage avec masques de Dalí et combinaisons rouges ?',
    answer: 'La Casa de Papel',
    acceptable: ['casa de papel', 'money heist'],
    distractors: ['Vis a vis', 'Élite', 'Toy Boy'],
  },
  {
    id: 'serie-3',
    theme: 'series',
    difficulty: 1,
    text: 'Dans Breaking Bad, quel est le métier initial de Walter White ?',
    answer: 'Professeur de chimie',
    acceptable: ['prof de chimie', 'chimie'],
    distractors: ['Médecin', 'Avocat', 'Policier'],
    hints: ['Il enseigne dans un lycée.'],
  },
  {
    id: 'serie-4',
    theme: 'series',
    difficulty: 2,
    text: 'Dans Stranger Things, comment surnomme-t-on la jeune fille aux pouvoirs ?',
    answer: 'Eleven (Onze)',
    acceptable: ['eleven', 'onze', 'el'],
    distractors: ['Max', 'Nancy', 'Robin'],
  },
  {
    id: 'serie-5',
    theme: 'series',
    difficulty: 3,
    text: 'Dans Friends, quel est le nom de famille de Chandler ?',
    answer: 'Bing',
    distractors: ['Geller', 'Tribbiani', 'Green'],
    hints: ['Chandler ___ .'],
  },
  {
    id: 'serie-6',
    theme: 'series',
    difficulty: 1,
    text: 'Quelle série animée suit une famille jaune vivant à Springfield ?',
    answer: 'Les Simpson',
    acceptable: ['simpsons', 'the simpsons'],
    distractors: ['Family Guy', 'Futurama', 'South Park'],
  },
  {
    id: 'serie-7',
    theme: 'series',
    difficulty: 2,
    text: 'Dans The Office (US), qui est le patron de la succursale de Scranton ?',
    answer: 'Michael Scott',
    acceptable: ['michael'],
    distractors: ['Jim Halpert', 'Dwight Schrute', 'Andy Bernard'],
  },
  {
    id: 'serie-8',
    theme: 'series',
    difficulty: 3,
    text: 'En quelle année a débuté la série britannique Doctor Who (série classique) ?',
    answer: '1963',
    distractors: ['1970', '1955', '1980'],
  },
  {
    id: 'serie-9',
    theme: 'series',
    difficulty: 2,
    text: 'Dans Peaky Blinders, quelle famille règne sur Birmingham ?',
    answer: 'Les Shelby',
    acceptable: ['shelby'],
    distractors: ['Les Solomons', 'Les Gray', 'Les Changretta'],
  },
  {
    id: 'serie-10',
    theme: 'series',
    difficulty: 1,
    text: 'Quelle série met en scène des chirurgiens au Seattle Grace Hospital ?',
    answer: "Grey's Anatomy",
    acceptable: ['greys anatomy'],
    distractors: ['Dr House', 'Urgences', 'New Amsterdam'],
  },

  // ----- Films --------------------------------------------------------------
  {
    id: 'film-1',
    theme: 'films',
    difficulty: 1,
    text: 'Qui a réalisé Titanic (1997) ?',
    answer: 'James Cameron',
    acceptable: ['cameron'],
    distractors: ['Steven Spielberg', 'Christopher Nolan', 'Ridley Scott'],
  },
  {
    id: 'film-2',
    theme: 'films',
    difficulty: 2,
    text: 'Dans Le Seigneur des Anneaux, quel hobbit doit détruire l\'Anneau Unique ?',
    answer: 'Frodon',
    acceptable: ['frodo', 'frodon sacquet'],
    distractors: ['Gandalf', 'Aragorn', 'Sam'],
  },
  {
    id: 'film-3',
    theme: 'films',
    difficulty: 1,
    text: 'Dans Star Wars, qui est le père de Luke Skywalker ?',
    answer: 'Dark Vador (Anakin Skywalker)',
    acceptable: ['dark vador', 'anakin', 'darth vader', 'vador'],
    distractors: ['Obi-Wan', 'Yoda', 'Palpatine'],
  },
  {
    id: 'film-4',
    theme: 'films',
    difficulty: 2,
    text: 'Quel acteur incarne Jack Sparrow dans Pirates des Caraïbes ?',
    answer: 'Johnny Depp',
    acceptable: ['depp'],
    distractors: ['Orlando Bloom', 'Brad Pitt', 'Javier Bardem'],
  },
  {
    id: 'film-5',
    theme: 'films',
    difficulty: 3,
    text: 'Quel film coréen a remporté l\'Oscar du meilleur film en 2020 ?',
    answer: 'Parasite',
    distractors: ['1917', 'Joker', 'Once Upon a Time in Hollywood'],
    hints: ['Réalisé par Bong Joon-ho.'],
  },
  {
    id: 'film-6',
    theme: 'films',
    difficulty: 1,
    text: 'Dans Le Roi Lion, comment s\'appelle le père de Simba ?',
    answer: 'Mufasa',
    distractors: ['Scar', 'Rafiki', 'Zazu'],
  },
  {
    id: 'film-7',
    theme: 'films',
    difficulty: 2,
    text: 'Quel réalisateur est connu pour Inception et Interstellar ?',
    answer: 'Christopher Nolan',
    acceptable: ['nolan'],
    distractors: ['Denis Villeneuve', 'James Cameron', 'Quentin Tarantino'],
  },
  {
    id: 'film-8',
    theme: 'films',
    difficulty: 3,
    text: 'En quelle année est sorti le premier film Matrix ?',
    answer: '1999',
    distractors: ['1997', '2001', '2003'],
  },
  {
    id: 'film-9',
    theme: 'films',
    difficulty: 1,
    text: 'Dans Toy Story, quel est le jouet cow-boy ?',
    answer: 'Woody',
    distractors: ["Buzz l'Éclair", 'Rex', 'Jessie'],
  },
  {
    id: 'film-10',
    theme: 'films',
    difficulty: 2,
    text: 'Quel super-héros Marvel est interprété par Robert Downey Jr. ?',
    answer: 'Iron Man',
    distractors: ['Captain America', 'Thor', 'Hulk'],
  },

  // ----- Musique ------------------------------------------------------------
  {
    id: 'musique-1',
    theme: 'musique',
    difficulty: 1,
    text: 'Quel groupe a chanté « Bohemian Rhapsody » ?',
    answer: 'Queen',
    distractors: ['The Beatles', 'The Rolling Stones', 'Led Zeppelin'],
  },
  {
    id: 'musique-2',
    theme: 'musique',
    difficulty: 2,
    text: 'Quelle chanteuse est surnommée « Queen B » ?',
    answer: 'Beyoncé',
    acceptable: ['beyonce'],
    distractors: ['Rihanna', 'Lady Gaga', 'Adele'],
  },
  {
    id: 'musique-3',
    theme: 'musique',
    difficulty: 1,
    text: 'Combien de cordes possède une guitare classique standard ?',
    answer: '6',
    acceptable: ['six'],
    distractors: ['4', '5', '12'],
    hints: ['Une basse en a quatre.'],
  },
  {
    id: 'musique-4',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel artiste a sorti l\'album « Thriller » ?',
    answer: 'Michael Jackson',
    acceptable: ['jackson'],
    distractors: ['Prince', 'Stevie Wonder', 'Lionel Richie'],
  },
  {
    id: 'musique-5',
    theme: 'musique',
    difficulty: 3,
    text: 'De quelle ville anglaise est originaire le groupe The Beatles ?',
    answer: 'Liverpool',
    distractors: ['Londres', 'Manchester', 'Birmingham'],
  },
  {
    id: 'musique-6',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel duo français masqué a composé « Get Lucky » et « One More Time » ?',
    answer: 'Daft Punk',
    distractors: ['Justice', 'Modjo', 'Cassius'],
  },
  {
    id: 'musique-7',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel rappeur américain est surnommé « Slim Shady » ?',
    answer: 'Eminem',
    distractors: ['Jay-Z', '50 Cent', 'Dr. Dre'],
  },
  {
    id: 'musique-8',
    theme: 'musique',
    difficulty: 3,
    text: 'Quel compositeur, devenu sourd, a écrit la 9e symphonie (« Ode à la joie ») ?',
    answer: 'Beethoven',
    distractors: ['Mozart', 'Bach', 'Chopin'],
  },
  {
    id: 'musique-9',
    theme: 'musique',
    difficulty: 1,
    text: 'Quelle chanteuse a sorti « Shake It Off » et l\'album « 1989 » ?',
    answer: 'Taylor Swift',
    acceptable: ['swift'],
    distractors: ['Katy Perry', 'Ariana Grande', 'Selena Gomez'],
  },
  {
    id: 'musique-10',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel groupe suédois a chanté « Dancing Queen » ?',
    answer: 'ABBA',
    distractors: ['Ace of Base', 'Roxette', 'A-ha'],
  },

  // ----- Culture générale ---------------------------------------------------
  {
    id: 'culture-1',
    theme: 'culture',
    difficulty: 1,
    text: 'Quelle est la capitale de la France ?',
    answer: 'Paris',
    distractors: ['Lyon', 'Marseille', 'Bordeaux'],
  },
  {
    id: 'culture-2',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de continents compte-t-on sur Terre ?',
    answer: '7',
    acceptable: ['sept'],
    distractors: ['5', '6', '8'],
  },
  {
    id: 'culture-3',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la planète la plus proche du Soleil ?',
    answer: 'Mercure',
    distractors: ['Vénus', 'Mars', 'La Terre'],
  },
  {
    id: 'culture-4',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel élément chimique a pour symbole « O » ?',
    answer: 'Oxygène',
    distractors: ['Or', 'Osmium', 'Hydrogène'],
  },
  {
    id: 'culture-5',
    theme: 'culture',
    difficulty: 3,
    text: 'En quelle année est tombé le mur de Berlin ?',
    answer: '1989',
    distractors: ['1991', '1987', '1985'],
  },
  {
    id: 'culture-6',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de côtés possède un hexagone ?',
    answer: '6',
    acceptable: ['six'],
    distractors: ['5', '7', '8'],
  },
  {
    id: 'culture-7',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand océan du monde ?',
    answer: 'L\'océan Pacifique',
    acceptable: ['pacifique'],
    distractors: ['Atlantique', 'Indien', 'Arctique'],
  },
  {
    id: 'culture-8',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a peint La Joconde ?',
    answer: 'Léonard de Vinci',
    acceptable: ['de vinci', 'vinci', 'leonard de vinci'],
    distractors: ['Michel-Ange', 'Raphaël', 'Botticelli'],
  },
  {
    id: 'culture-9',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel est le plus petit État indépendant du monde ?',
    answer: 'Le Vatican',
    acceptable: ['vatican'],
    distractors: ['Monaco', 'Saint-Marin', 'Nauru'],
  },
  {
    id: 'culture-10',
    theme: 'culture',
    difficulty: 1,
    text: 'Quel pays a la forme d\'une botte ?',
    answer: "L'Italie",
    acceptable: ['italie'],
    distractors: ["L'Espagne", 'La Grèce', 'Le Portugal'],
  },
];
