import type { Question } from '../../../core/models';
import { universe } from './_build';

// Les questions « drapeau » utilisent flagcdn.com (PNG, fiable). Elles
// nécessitent une connexion ; hors-ligne, l'image ne s'affiche pas.
const flag = (code: string): { type: 'image'; uri: string } => ({
  type: 'image',
  uri: `https://flagcdn.com/w320/${code}.png`,
});

export const cultureQuestions: Question[] = [
  ...universe('culture', 'Géographie', [
    // --- Faciles (5) ---
    { id: "geo-f1", d: 1, t: "Quelle est la capitale de la France ?", a: "Paris", x: ["Lyon", "Marseille", "Bordeaux"] },
    { id: "geo-f2", d: 1, t: "Quel pays a la forme d'une botte ?", a: "L'Italie", x: ["L'Espagne", "La Grèce", "Le Portugal"], acc: ["italie"] },
    { id: "geo-f3", d: 1, t: "À quel pays appartient ce drapeau ?", a: "Japon", x: ["Chine", "Corée du Sud", "Bangladesh"], acc: ["le japon"], m: flag("jp") },
    { id: "geo-f4", d: 1, t: "Quel est le plus long fleuve du monde ?", a: "Le Nil", x: ["L'Amazone", "Le Mississippi", "Le Yangtsé"], acc: ["nil", "le nil"] },
    { id: "geo-f5", d: 1, t: "Quelle est la capitale de l'Espagne ?", a: "Madrid", x: ["Barcelone", "Séville", "Valence"] },
    // --- Moyennes (10) ---
    { id: "geo-m1", d: 2, t: "Quel est le plus grand océan du monde ?", a: "L'océan Pacifique", x: ["L'Atlantique", "L'Indien", "L'Arctique"], acc: ["pacifique"] },
    { id: "geo-m2", d: 2, t: "Quelle est la plus haute montagne du monde ?", a: "L'Everest", x: ["Le K2", "Le Mont Blanc", "Le Kilimandjaro"], acc: ["everest", "mont everest"] },
    { id: "geo-m3", d: 2, t: "À quel pays appartient ce drapeau ?", a: "Brésil", x: ["Argentine", "Portugal", "Cameroun"], acc: ["le brésil", "bresil"], m: flag("br") },
    { id: "geo-m4", d: 2, t: "Quelle est la monnaie du Japon ?", a: "Le yen", x: ["Le won", "Le yuan", "Le baht"], acc: ["yen"] },
    { id: "geo-m5", d: 2, t: "Quel est le plus grand désert chaud du monde ?", a: "Le Sahara", x: ["Le Gobi", "Le Kalahari", "L'Atacama"], acc: ["sahara", "le sahara"] },
    { id: "geo-m6", d: 2, t: "Quel est le plus grand pays du monde par sa superficie ?", a: "La Russie", x: ["Le Canada", "La Chine", "Les États-Unis"], acc: ["russie", "la russie"] },
    { id: "geo-m7", d: 2, t: "Combien de continents compte-t-on sur Terre ?", a: "7", x: ["5", "6", "8"], acc: ["sept"] },
    { id: "geo-m8", d: 2, t: "À quel pays appartient ce drapeau ?", a: "Canada", x: ["États-Unis", "Royaume-Uni", "Suisse"], acc: ["le canada"], m: flag("ca") },
    { id: "geo-m9", d: 2, t: "Sur quel continent se situe majoritairement l'Égypte ?", a: "L'Afrique", x: ["L'Asie", "L'Europe", "L'Amérique"], acc: ["afrique"] },
    { id: "geo-m10", d: 2, t: "Quelle est la capitale de l'Allemagne ?", a: "Berlin", x: ["Munich", "Francfort", "Hambourg"] },
    // --- Dures (15) ---
    { id: "geo-d1", d: 3, t: "Quel est le plus petit État indépendant du monde ?", a: "Le Vatican", x: ["Monaco", "Saint-Marin", "Nauru"], acc: ["vatican"] },
    { id: "geo-d2", d: 3, t: "À quel pays appartient ce drapeau ?", a: "Corée du Sud", x: ["Japon", "Chine", "Mongolie"], acc: ["coree du sud", "corée"], m: flag("kr") },
    { id: "geo-d3", d: 3, t: "À quel pays appartient ce drapeau ?", a: "Inde", x: ["Niger", "Irlande", "Côte d'Ivoire"], acc: ["l'inde"], m: flag("in") },
    { id: "geo-d4", d: 3, t: "À quel pays appartient ce drapeau ?", a: "Australie", x: ["Nouvelle-Zélande", "Royaume-Uni", "Fidji"], acc: ["l'australie"], m: flag("au") },
    { id: "geo-d5", d: 3, t: "Quelle langue compte le plus de locuteurs natifs au monde ?", a: "Le chinois", x: ["L'anglais", "L'espagnol", "L'hindi"], acc: ["chinois", "mandarin"] },
    { id: "geo-d6", d: 3, t: "Quelle est la capitale de l'Australie ?", a: "Canberra", x: ["Sydney", "Melbourne", "Perth"] },
    { id: "geo-d7", d: 3, t: "Quel fleuve traverse la ville de Londres ?", a: "La Tamise", x: ["La Seine", "Le Rhin", "Le Danube"], acc: ["tamise", "la tamise"] },
    { id: "geo-d8", d: 3, t: "Quelle est la langue officielle du Brésil ?", a: "Le portugais", x: ["L'espagnol", "Le brésilien", "Le français"], acc: ["portugais", "le portugais"] },
    { id: "geo-d9", d: 3, t: "Quelle est la capitale du Canada ?", a: "Ottawa", x: ["Toronto", "Montréal", "Vancouver"] },
    { id: "geo-d10", d: 3, t: "Quelle chaîne de montagnes sépare traditionnellement l'Europe de l'Asie ?", a: "L'Oural", x: ["Les Alpes", "Les Carpates", "Le Caucase"] },
    { id: "geo-d11", d: 3, t: "Quel détroit sépare l'Europe de l'Afrique ?", a: "Le détroit de Gibraltar", x: ["Le Bosphore", "La Manche", "Le détroit de Malacca"] },
    { id: "geo-d12", d: 3, t: "Quel est le plus grand État des États-Unis par sa superficie ?", a: "L'Alaska", x: ["Le Texas", "La Californie", "Le Montana"] },
    { id: "geo-d13", d: 3, t: "Dans quel pays se trouve la ville de Marrakech ?", a: "Le Maroc", x: ["L'Algérie", "La Tunisie", "L'Égypte"] },
    { id: "geo-d14", d: 3, t: "Quelle mer borde à la fois l'Italie, la Grèce et l'Égypte ?", a: "La mer Méditerranée", x: ["La mer Rouge", "La mer Noire", "La mer Caspienne"] },
    { id: "geo-d15", d: 3, t: "Quelle est la capitale de la Russie ?", a: "Moscou", x: ["Saint-Pétersbourg", "Kiev", "Minsk"] },
    // --- Pro (20) ---
    { id: "geo-p1", d: 4, t: "À quel pays appartient ce drapeau ?", a: "Roumanie", x: ["Tchad", "Andorre", "Moldavie"], acc: ["la roumanie"], m: flag("ro") },
    { id: "geo-p2", d: 4, t: "À quel pays appartient ce drapeau ?", a: "Grèce", x: ["Israël", "Uruguay", "Finlande"], acc: ["la grèce", "grece"], m: flag("gr") },
    { id: "geo-p3", d: 4, t: "Quel est le pays le plus peuplé d'Afrique ?", a: "Le Nigéria", x: ["L'Égypte", "L'Éthiopie", "L'Afrique du Sud"], acc: ["nigeria", "nigéria", "le nigéria"] },
    { id: "geo-p4", d: 4, t: "Quelle est la capitale de la Turquie ?", a: "Ankara", x: ["Istanbul", "Izmir", "Bursa"] },
    { id: "geo-p5", d: 4, t: "Quelle est la capitale du Brésil ?", a: "Brasília", x: ["Rio de Janeiro", "São Paulo", "Salvador"] },
    { id: "geo-p6", d: 4, t: "Quel est le pays le plus vaste d'Amérique du Sud ?", a: "Le Brésil", x: ["L'Argentine", "Le Pérou", "La Colombie"] },
    { id: "geo-p7", d: 4, t: "Quel désert froid s'étend sur la Mongolie et la Chine ?", a: "Le désert de Gobi", x: ["Le Sahara", "L'Atacama", "Le Kalahari"] },
    { id: "geo-p8", d: 4, t: "Quel lac est le plus profond du monde ?", a: "Le lac Baïkal", x: ["Le lac Tanganyika", "Le lac Supérieur", "La mer Caspienne"] },
    { id: "geo-p9", d: 4, t: "Quelle est la plus longue chaîne de montagnes émergée du monde ?", a: "La cordillère des Andes", x: ["L'Himalaya", "Les Rocheuses", "Les Alpes"] },
    { id: "geo-p10", d: 4, t: "Quelle est la capitale de l'Argentine ?", a: "Buenos Aires", x: ["Montevideo", "Santiago", "Lima"] },
    { id: "geo-p11", d: 4, t: "Quel royaume est entièrement enclavé dans l'Afrique du Sud ?", a: "Le Lesotho", x: ["L'Eswatini", "Le Botswana", "La Namibie"] },
    { id: "geo-p12", d: 4, t: "Quelle est la capitale de l'Égypte ?", a: "Le Caire", x: ["Alexandrie", "Louxor", "Assouan"] },
    { id: "geo-p13", d: 4, t: "Quel pays possède le plus long littoral du monde ?", a: "Le Canada", x: ["La Russie", "L'Australie", "L'Indonésie"] },
    { id: "geo-p14", d: 4, t: "Quelle est la capitale de la Norvège ?", a: "Oslo", x: ["Bergen", "Stockholm", "Helsinki"] },
    { id: "geo-p15", d: 4, t: "Quel est le plus petit pays d'Amérique du Sud ?", a: "Le Suriname", x: ["L'Uruguay", "L'Équateur", "Le Guyana"] },
    { id: "geo-p16", d: 4, t: "Dans quelle ville se trouve le Colisée ?", a: "Rome", x: ["Athènes", "Naples", "Vérone"] },
    { id: "geo-p17", d: 4, t: "Quel pays a pour capitale Wellington ?", a: "La Nouvelle-Zélande", x: ["L'Australie", "Les Fidji", "Le Canada"] },
    { id: "geo-p18", d: 4, t: "Quelle étendue d'eau salée fermée est la plus grande du monde ?", a: "La mer Caspienne", x: ["La mer Morte", "La mer d'Aral", "Le lac Baïkal"] },
    { id: "geo-p19", d: 4, t: "Quel pays arbore le plus ancien drapeau national encore en usage ?", a: "Le Danemark", x: ["La Suède", "Les Pays-Bas", "L'Autriche"] },
    { id: "geo-p20", d: 4, t: "Quelle est la capitale du Portugal ?", a: "Lisbonne", x: ["Porto", "Madrid", "Séville"] },
  ]),

  ...universe('culture', 'Histoire', [
    // --- Faciles (5) ---
    { id: "hist-f1", d: 1, t: "Quel mur séparait la ville de Berlin jusqu'en 1989 ?", a: "Le mur de Berlin", x: ["La Grande Muraille", "Le mur d'Hadrien", "Le Mur des lamentations"] },
    { id: "hist-f2", d: 1, t: "En quelle matière étaient les premiers outils de la Préhistoire ?", a: "La pierre", x: ["Le fer", "Le bronze", "Le plastique"] },
    { id: "hist-f3", d: 1, t: "Comment appelle-t-on les rois de l'Égypte antique ?", a: "Les pharaons", x: ["Les césars", "Les sultans", "Les tsars"] },
    { id: "hist-f4", d: 1, t: "Quel peuple antique a inventé la démocratie à Athènes ?", a: "Les Grecs", x: ["Les Romains", "Les Égyptiens", "Les Perses"] },
    { id: "hist-f5", d: 1, t: "Comment appelle-t-on l'écriture à base de dessins des anciens Égyptiens ?", a: "Les hiéroglyphes", x: ["Le cunéiforme", "L'alphabet latin", "Les runes"] },
    // --- Moyennes (10) ---
    { id: "hist-m1", d: 2, t: "Qui fut le premier président des États-Unis ?", a: "George Washington", x: ["Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], acc: ["washington", "george washington"] },
    { id: "hist-m2", d: 2, t: "Quel empereur français a été vaincu à la bataille de Waterloo ?", a: "Napoléon Bonaparte", x: ["Louis XVI", "Charles de Gaulle", "Jules César"], acc: ["napoleon", "napoléon", "bonaparte"] },
    { id: "hist-m3", d: 2, t: "Quelle civilisation antique a construit les pyramides de Gizeh ?", a: "Les Égyptiens", x: ["Les Romains", "Les Mayas", "Les Grecs"], acc: ["egyptiens", "égyptiens", "egypte ancienne"] },
    { id: "hist-m4", d: 2, t: "Quel célèbre paquebot a coulé en 1912 lors de son voyage inaugural ?", a: "Le Titanic", x: ["Le Lusitania", "Le Britannic", "Le Bismarck"], acc: ["titanic", "le titanic"] },
    { id: "hist-m5", d: 2, t: "En quelle année Christophe Colomb a-t-il atteint l'Amérique ?", a: "1492", x: ["1453", "1519", "1607"] },
    { id: "hist-m6", d: 2, t: "Quel général carthaginois a traversé les Alpes avec des éléphants ?", a: "Hannibal", x: ["Jules César", "Alexandre le Grand", "Spartacus"] },
    { id: "hist-m7", d: 2, t: "Quelle reine d'Égypte a séduit César puis Marc Antoine ?", a: "Cléopâtre", x: ["Néfertiti", "Hatchepsout", "Théodora"] },
    { id: "hist-m8", d: 2, t: "Quel roi de France a été guillotiné pendant la Révolution ?", a: "Louis XVI", x: ["Louis XIV", "Henri IV", "François Ier"] },
    { id: "hist-m9", d: 2, t: "Qui a mené les Français à la victoire lors du siège d'Orléans en 1429 ?", a: "Jeanne d'Arc", x: ["Aliénor d'Aquitaine", "Catherine de Médicis", "Marie-Antoinette"] },
    { id: "hist-m10", d: 2, t: "Quel président américain a aboli l'esclavage pendant la guerre de Sécession ?", a: "Abraham Lincoln", x: ["George Washington", "Thomas Jefferson", "Theodore Roosevelt"] },
    // --- Dures (15) ---
    { id: "hist-d1", d: 3, t: "En quelle année est tombé le mur de Berlin ?", a: "1989", x: ["1991", "1987", "1985"] },
    { id: "hist-d2", d: 3, t: "En quelle année s'est terminée la Seconde Guerre mondiale ?", a: "1945", x: ["1944", "1939", "1918"] },
    { id: "hist-d3", d: 3, t: "Quel roi de France est surnommé le « Roi-Soleil » ?", a: "Louis XIV", x: ["Louis XVI", "François Ier", "Henri IV"], acc: ["louis 14", "louis xiv"] },
    { id: "hist-d4", d: 3, t: "Quel traité de 1919 a officiellement mis fin à la Première Guerre mondiale ?", a: "Le traité de Versailles", x: ["Le traité de Rome", "Le congrès de Vienne", "Le traité de Tordesillas"] },
    { id: "hist-d5", d: 3, t: "Quel empereur romain a été assassiné aux ides de mars 44 av. J.-C. ?", a: "Jules César", x: ["Auguste", "Néron", "Caligula"] },
    { id: "hist-d6", d: 3, t: "Quelle dynastie chinoise a bâti la Grande Muraille telle qu'on la voit aujourd'hui ?", a: "Les Ming", x: ["Les Han", "Les Tang", "Les Qing"] },
    { id: "hist-d7", d: 3, t: "Quel roi anglais a fondé l'Église anglicane pour pouvoir divorcer ?", a: "Henri VIII", x: ["Richard Cœur de Lion", "Guillaume le Conquérant", "Jean sans Terre"] },
    { id: "hist-d8", d: 3, t: "En quelle année les États-Unis ont-ils déclaré leur indépendance ?", a: "1776", x: ["1789", "1804", "1812"] },
    { id: "hist-d9", d: 3, t: "Quel homme a mené l'Inde à l'indépendance par la non-violence ?", a: "Gandhi", x: ["Nehru", "Bose", "Ambedkar"] },
    { id: "hist-d10", d: 3, t: "Quel mur de pierre protégeait le nord de la Bretagne romaine ?", a: "Le mur d'Hadrien", x: ["La Grande Muraille", "Le mur de Berlin", "Le limes du Rhin"] },
    { id: "hist-d11", d: 3, t: "Quelle civilisation précolombienne régnait sur Tenochtitlan au Mexique ?", a: "Les Aztèques", x: ["Les Incas", "Les Mayas", "Les Olmèques"] },
    { id: "hist-d12", d: 3, t: "Quelle cité andine du Pérou fut construite par les Incas au XVe siècle ?", a: "Le Machu Picchu", x: ["Chichén Itzá", "Tikal", "Nazca"] },
    { id: "hist-d13", d: 3, t: "Quel conquérant macédonien a bâti un immense empire au IVe siècle av. J.-C. ?", a: "Alexandre le Grand", x: ["Jules César", "Hannibal", "Darius"] },
    { id: "hist-d14", d: 3, t: "Quelle guerre a opposé le Nord et le Sud des États-Unis de 1861 à 1865 ?", a: "La guerre de Sécession", x: ["La guerre d'Indépendance", "La guerre de 1812", "La guerre du Vietnam"] },
    { id: "hist-d15", d: 3, t: "Quelle épidémie a ravagé l'Europe au XIVe siècle en tuant des millions de personnes ?", a: "La peste noire", x: ["La grippe espagnole", "Le choléra", "La variole"] },
    // --- Pro (20) ---
    { id: "hist-p1", d: 4, t: "En quelle année a eu lieu la prise de la Bastille ?", a: "1789", x: ["1799", "1769", "1804"] },
    { id: "hist-p2", d: 4, t: "En quelle année l'Homme a-t-il marché sur la Lune pour la première fois ?", a: "1969", x: ["1972", "1965", "1959"] },
    { id: "hist-p3", d: 4, t: "En quelle année a commencé la Première Guerre mondiale ?", a: "1914", x: ["1918", "1912", "1939"] },
    { id: "hist-p4", d: 4, t: "En quelle année Jules César a-t-il été assassiné ?", a: "44 av. J.-C.", x: ["27 av. J.-C.", "476 apr. J.-C.", "79 apr. J.-C."] },
    { id: "hist-p5", d: 4, t: "Quel empereur romain a légalisé le christianisme par l'édit de Milan en 313 ?", a: "Constantin", x: ["Néron", "Dioclétien", "Trajan"] },
    { id: "hist-p6", d: 4, t: "En quelle année l'Empire romain d'Occident est-il tombé ?", a: "476", x: ["410", "800", "1453"] },
    { id: "hist-p7", d: 4, t: "En quelle année Constantinople est-elle tombée aux mains des Ottomans ?", a: "1453", x: ["1492", "1204", "1071"] },
    { id: "hist-p8", d: 4, t: "Quel roi franc a été couronné empereur en l'an 800 ?", a: "Charlemagne", x: ["Clovis", "Hugues Capet", "Louis le Pieux"] },
    { id: "hist-p9", d: 4, t: "Quelle reine d'Angleterre a régné de 1558 à 1603, donnant son nom à une époque ?", a: "Élisabeth Ire", x: ["Victoria", "Marie Ire", "Anne"] },
    { id: "hist-p10", d: 4, t: "Quel roi de France a révoqué l'édit de Nantes en 1685 ?", a: "Louis XIV", x: ["Louis XIII", "Henri IV", "Louis XV"] },
    { id: "hist-p11", d: 4, t: "Quelle bataille navale de 1805 opposa Nelson à la flotte franco-espagnole ?", a: "Trafalgar", x: ["Aboukir", "Lépante", "Actium"] },
    { id: "hist-p12", d: 4, t: "En quelle année a eu lieu la révolution bolchevique en Russie ?", a: "1917", x: ["1905", "1922", "1789"] },
    { id: "hist-p13", d: 4, t: "Quel dirigeant soviétique était à la tête de l'URSS pendant la Seconde Guerre mondiale ?", a: "Staline", x: ["Lénine", "Khrouchtchev", "Trotski"] },
    { id: "hist-p14", d: 4, t: "Quels traités de 1648 ont mis fin à la guerre de Trente Ans ?", a: "Les traités de Westphalie", x: ["Le traité de Versailles", "Le congrès de Vienne", "Le traité d'Utrecht"] },
    { id: "hist-p15", d: 4, t: "Quel explorateur portugais a mené la première expédition à faire le tour du monde ?", a: "Magellan", x: ["Vasco de Gama", "Christophe Colomb", "Amerigo Vespucci"] },
    { id: "hist-p16", d: 4, t: "Quelle dynastie régnait sur la France juste avant la Révolution de 1789 ?", a: "Les Bourbons", x: ["Les Valois", "Les Carolingiens", "Les Mérovingiens"] },
    { id: "hist-p17", d: 4, t: "En quelle année a eu lieu la bataille de Hastings, qui livra l'Angleterre aux Normands ?", a: "1066", x: ["1215", "911", "1099"] },
    { id: "hist-p18", d: 4, t: "Quel pharaon est célèbre pour son tombeau presque intact découvert en 1922 ?", a: "Toutânkhamon", x: ["Ramsès II", "Khéops", "Akhenaton"] },
    { id: "hist-p19", d: 4, t: "Quel chef mongol a fondé le plus grand empire terrestre d'un seul tenant de l'Histoire ?", a: "Gengis Khan", x: ["Kubilai Khan", "Tamerlan", "Attila"] },
    { id: "hist-p20", d: 4, t: "En quelle année la Grande Charte, la « Magna Carta », a-t-elle été signée en Angleterre ?", a: "1215", x: ["1066", "1348", "1492"] },
  ]),

  ...universe('culture', 'Sciences', [
    // --- Faciles (5) ---
    { id: "sci-f1", d: 1, t: "Combien de côtés possède un hexagone ?", a: "6", x: ["5", "7", "8"], acc: ["six"] },
    { id: "sci-f2", d: 1, t: "Quelle planète est surnommée la planète rouge ?", a: "Mars", x: ["Vénus", "Jupiter", "Saturne"] },
    { id: "sci-f3", d: 1, t: "Quel est l'animal le plus haut du monde ?", a: "La girafe", x: ["L'éléphant", "L'autruche", "Le chameau"], acc: ["girafe", "la girafe"] },
    { id: "sci-f4", d: 1, t: "Combien de pattes possède une araignée ?", a: "8", x: ["6", "10", "4"], acc: ["huit"] },
    { id: "sci-f5", d: 1, t: "Quel organe pompe le sang dans tout le corps ?", a: "Le cœur", x: ["Le foie", "Les poumons", "Le cerveau"], acc: ["coeur", "cœur", "le cœur"] },
    // --- Moyennes (10) ---
    { id: "sci-m1", d: 2, t: "Quelle est la planète la plus proche du Soleil ?", a: "Mercure", x: ["Vénus", "Mars", "La Terre"] },
    { id: "sci-m2", d: 2, t: "Quel élément chimique a pour symbole « O » ?", a: "Oxygène", x: ["Or", "Osmium", "Hydrogène"] },
    { id: "sci-m3", d: 2, t: "Quel est le plus grand organe du corps humain ?", a: "La peau", x: ["Le foie", "Les poumons", "L'intestin"], acc: ["peau"] },
    { id: "sci-m4", d: 2, t: "Qui a développé la théorie de la relativité ?", a: "Albert Einstein", x: ["Isaac Newton", "Niels Bohr", "Galilée"], acc: ["einstein"] },
    { id: "sci-m5", d: 2, t: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", a: "Le dioxyde de carbone", x: ["L'oxygène", "L'azote", "L'hydrogène"], acc: ["co2", "dioxyde de carbone", "gaz carbonique"] },
    { id: "sci-m6", d: 2, t: "Quelle est la plus grande planète du système solaire ?", a: "Jupiter", x: ["Saturne", "Neptune", "La Terre"] },
    { id: "sci-m7", d: 2, t: "Quel est le plus grand animal ayant jamais existé, vivant dans les océans ?", a: "La baleine bleue", x: ["Le cachalot", "Le requin-baleine", "Le mégalodon"], acc: ["baleine bleue", "baleine", "la baleine bleue"] },
    { id: "sci-m8", d: 2, t: "Quelle est la formule chimique de l'eau ?", a: "H2O", x: ["CO2", "O2", "H2O2"], acc: ["h2o"] },
    { id: "sci-m9", d: 2, t: "Autour de quel astre la Terre tourne-t-elle en environ 365 jours ?", a: "Le Soleil", x: ["La Lune", "Mars", "Jupiter"], acc: ["soleil", "le soleil"] },
    { id: "sci-m10", d: 2, t: "Quelle planète possède les anneaux les plus visibles du système solaire ?", a: "Saturne", x: ["Jupiter", "Uranus", "Neptune"] },
    // --- Dures (15) ---
    { id: "sci-d1", d: 3, t: "Quelle est approximativement la vitesse de la lumière ?", a: "300 000 km/s", x: ["150 000 km/s", "1 000 000 km/s", "30 000 km/s"], acc: ["300000", "300 000"] },
    { id: "sci-d2", d: 3, t: "Quel est le symbole chimique de l'or ?", a: "Au", x: ["Or", "Ag", "Gd"] },
    { id: "sci-d3", d: 3, t: "Combien de cœurs possède une pieuvre ?", a: "3", x: ["1", "2", "5"], acc: ["trois"] },
    { id: "sci-d4", d: 3, t: "Quel métal est liquide à température ambiante ?", a: "Le mercure", x: ["Le plomb", "L'étain", "Le zinc"], acc: ["mercure"] },
    { id: "sci-d5", d: 3, t: "Quel scientifique a énoncé les trois lois du mouvement ?", a: "Isaac Newton", x: ["Galilée", "Albert Einstein", "Johannes Kepler"], acc: ["newton"] },
    { id: "sci-d6", d: 3, t: "Quel est l'os le plus long du corps humain ?", a: "Le fémur", x: ["Le tibia", "L'humérus", "Le péroné"], acc: ["femur", "fémur", "le fémur"] },
    { id: "sci-d7", d: 3, t: "Quel scientifique a formulé la théorie de l'évolution par sélection naturelle ?", a: "Charles Darwin", x: ["Gregor Mendel", "Louis Pasteur", "Carl von Linné"], acc: ["darwin"] },
    { id: "sci-d8", d: 3, t: "Quel gaz représente environ 21 % de l'air que nous respirons ?", a: "L'oxygène", x: ["L'azote", "Le dioxyde de carbone", "L'hydrogène"], acc: ["oxygene", "oxygène", "o2"] },
    { id: "sci-d9", d: 3, t: "Quel scientifique a découvert la pénicilline ?", a: "Alexander Fleming", x: ["Louis Pasteur", "Marie Curie", "Robert Koch"] },
    { id: "sci-d10", d: 3, t: "Quelle est l'unité de mesure de la force dans le système international ?", a: "Le newton", x: ["Le joule", "Le watt", "Le pascal"] },
    { id: "sci-d11", d: 3, t: "Combien de dents possède un adulte humain en bonne santé ?", a: "32", x: ["28", "30", "36"] },
    { id: "sci-d12", d: 3, t: "Quel organe produit l'insuline dans le corps humain ?", a: "Le pancréas", x: ["Le foie", "Les reins", "La rate"] },
    { id: "sci-d13", d: 3, t: "Quelle particule de l'atome porte une charge négative ?", a: "L'électron", x: ["Le proton", "Le neutron", "Le photon"] },
    { id: "sci-d14", d: 3, t: "Quel gaz noble est utilisé dans les enseignes lumineuses rouges ?", a: "Le néon", x: ["L'hélium", "L'argon", "Le krypton"] },
    { id: "sci-d15", d: 3, t: "Quelle planète est la plus éloignée du Soleil dans le système solaire ?", a: "Neptune", x: ["Uranus", "Saturne", "Pluton"] },
    // --- Pro (20) ---
    { id: "sci-p1", d: 4, t: "Combien d'os compte le squelette humain adulte ?", a: "206", x: ["256", "198", "212"] },
    { id: "sci-p2", d: 4, t: "Combien de chromosomes possède une cellule humaine ?", a: "46", x: ["23", "48", "64"], acc: ["quarante-six"] },
    { id: "sci-p3", d: 4, t: "Quelle est approximativement la vitesse du son dans l'air ?", a: "340 m/s", x: ["3 000 m/s", "100 m/s", "300 000 km/s"], acc: ["340", "340 m/s", "1235 km/h"] },
    { id: "sci-p4", d: 4, t: "Quel est l'élément chimique le plus abondant dans l'univers ?", a: "L'hydrogène", x: ["L'oxygène", "L'hélium", "Le carbone"], acc: ["hydrogene", "hydrogène", "h"] },
    { id: "sci-p5", d: 4, t: "Quelle scientifique a reçu deux prix Nobel, en physique et en chimie ?", a: "Marie Curie", x: ["Rosalind Franklin", "Lise Meitner", "Dorothy Hodgkin"] },
    { id: "sci-p6", d: 4, t: "Quel est l'élément chimique de symbole « Fe » ?", a: "Le fer", x: ["Le fluor", "Le francium", "Le phosphore"] },
    { id: "sci-p7", d: 4, t: "Quelle est approximativement la vitesse de libération pour quitter l'attraction terrestre ?", a: "Environ 11 km/s", x: ["Environ 3 km/s", "Environ 40 km/s", "Environ 300 km/s"] },
    { id: "sci-p8", d: 4, t: "Quelle molécule porte l'information génétique dans nos cellules ?", a: "L'ADN", x: ["L'ARN messager", "Le glucose", "L'ATP"] },
    { id: "sci-p9", d: 4, t: "Qui a proposé le modèle héliocentrique plaçant le Soleil au centre ?", a: "Copernic", x: ["Ptolémée", "Aristote", "Galilée"] },
    { id: "sci-p10", d: 4, t: "Quelle est l'étoile la plus proche de la Terre après le Soleil ?", a: "Proxima du Centaure", x: ["Sirius", "Bételgeuse", "Véga"] },
    { id: "sci-p11", d: 4, t: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", a: "Environ 8 minutes", x: ["Environ 8 secondes", "Environ 1 heure", "Environ 1 jour"] },
    { id: "sci-p12", d: 4, t: "Quel savant grec aurait crié « Eurêka » en découvrant la poussée dans son bain ?", a: "Archimède", x: ["Pythagore", "Euclide", "Thalès"] },
    { id: "sci-p13", d: 4, t: "Quelle échelle mesure la magnitude des séismes ?", a: "L'échelle de Richter", x: ["L'échelle de Beaufort", "L'échelle de Mohs", "L'échelle Celsius"] },
    { id: "sci-p14", d: 4, t: "Quel métal est le plus abondant dans la croûte terrestre ?", a: "L'aluminium", x: ["Le fer", "Le cuivre", "Le magnésium"] },
    { id: "sci-p15", d: 4, t: "Quelle est la température d'ébullition de l'eau au niveau de la mer ?", a: "100 °C", x: ["90 °C", "120 °C", "80 °C"] },
    { id: "sci-p16", d: 4, t: "Dans quel organe du corps humain se trouvent les alvéoles ?", a: "Les poumons", x: ["Le cœur", "Le foie", "L'estomac"] },
    { id: "sci-p17", d: 4, t: "Quelle grandeur physique se mesure en ampères ?", a: "L'intensité électrique", x: ["La tension", "La résistance", "La puissance"] },
    { id: "sci-p18", d: 4, t: "Combien de paires de côtes possède la cage thoracique humaine ?", a: "12", x: ["10", "14", "8"] },
    { id: "sci-p19", d: 4, t: "À quelle grande famille de roches appartient le granite ?", a: "Les roches magmatiques", x: ["Les roches sédimentaires", "Les roches métamorphiques", "Les roches organiques"] },
    { id: "sci-p20", d: 4, t: "Quel physicien danois a modélisé l'atome avec des électrons sur des orbites ?", a: "Niels Bohr", x: ["Ernest Rutherford", "Max Planck", "Werner Heisenberg"] },
  ]),

  ...universe('culture', 'Culture générale', [
    // --- Faciles (5) ---
    { id: "cult-f1", d: 1, t: "Combien de joueurs composent une équipe de football sur le terrain ?", a: "11", x: ["10", "12", "9"] },
    { id: "cult-f2", d: 1, t: "Combien de joueurs compte une équipe de basket sur le terrain ?", a: "5", x: ["6", "7", "11"], acc: ["cinq"] },
    { id: "cult-f3", d: 1, t: "Combien de minutes y a-t-il dans une heure ?", a: "60", x: ["100", "24", "12"], acc: ["soixante"] },
    { id: "cult-f4", d: 1, t: "Combien de faces possède un dé classique ?", a: "6", x: ["4", "8", "12"], acc: ["six"] },
    { id: "cult-f5", d: 1, t: "Combien de joueurs composent une équipe de volley-ball sur le terrain ?", a: "6", x: ["5", "7", "11"], acc: ["six"] },
    // --- Moyennes (10) ---
    { id: "cult-m1", d: 2, t: "Qui a écrit la pièce « Roméo et Juliette » ?", a: "William Shakespeare", x: ["Molière", "Victor Hugo", "Voltaire"], acc: ["shakespeare"] },
    { id: "cult-m2", d: 2, t: "Qui a écrit « Les Misérables » ?", a: "Victor Hugo", x: ["Émile Zola", "Gustave Flaubert", "Honoré de Balzac"], acc: ["hugo"] },
    { id: "cult-m3", d: 2, t: "Qui a écrit « Le Petit Prince » ?", a: "Antoine de Saint-Exupéry", x: ["Jules Verne", "Charles Perrault", "Marcel Pagnol"], acc: ["saint-exupery", "saint exupéry", "saint-exupéry"] },
    { id: "cult-m4", d: 2, t: "Quel écrivain a créé le détective Sherlock Holmes ?", a: "Arthur Conan Doyle", x: ["Agatha Christie", "Edgar Allan Poe", "Maurice Leblanc"], acc: ["conan doyle", "doyle"] },
    { id: "cult-m5", d: 2, t: "Dans quel sport parle-t-on d'un « ace » et d'un « let » ?", a: "Le tennis", x: ["Le golf", "Le volley", "Le rugby"], acc: ["tennis", "le tennis"] },
    { id: "cult-m6", d: 2, t: "Combien de couleurs distingue-t-on traditionnellement dans un arc-en-ciel ?", a: "7", x: ["5", "6", "9"], acc: ["sept"] },
    { id: "cult-m7", d: 2, t: "Quel instrument de musique possède 88 touches ?", a: "Le piano", x: ["L'orgue", "L'accordéon", "La harpe"], acc: ["piano", "le piano"] },
    { id: "cult-m8", d: 2, t: "Qui a écrit les fables « Le Corbeau et le Renard » et « Le Lièvre et la Tortue » ?", a: "Jean de La Fontaine", x: ["Charles Perrault", "Victor Hugo", "Molière"] },
    { id: "cult-m9", d: 2, t: "Dans quel sport marque-t-on un « strike » et un « spare » ?", a: "Le bowling", x: ["Le baseball", "Le cricket", "Le curling"] },
    { id: "cult-m10", d: 2, t: "Quelle discipline sportive se déroule sur un tatami avec des ceintures de couleur ?", a: "Le judo", x: ["L'escrime", "La lutte", "La boxe"] },
    // --- Dures (15) ---
    { id: "cult-d1", d: 3, t: "Quel peintre néerlandais s'est tristement coupé une partie de l'oreille ?", a: "Vincent van Gogh", x: ["Rembrandt", "Vermeer", "Claude Monet"], acc: ["van gogh", "vincent van gogh"] },
    { id: "cult-d2", d: 3, t: "Tous les combien d'années ont lieu les Jeux olympiques d'été ?", a: "4 ans", x: ["2 ans", "5 ans", "3 ans"], acc: ["4", "quatre", "4 ans", "tous les 4 ans"] },
    { id: "cult-d3", d: 3, t: "Qui a écrit « Don Quichotte » ?", a: "Miguel de Cervantès", x: ["Dante Alighieri", "Lope de Vega", "Gabriel García Márquez"] },
    { id: "cult-d4", d: 3, t: "Quel dramaturge français a écrit « Le Malade imaginaire » ?", a: "Molière", x: ["Racine", "Corneille", "Beaumarchais"] },
    { id: "cult-d5", d: 3, t: "Combien de joueurs compose une équipe de rugby à XV sur le terrain ?", a: "15", x: ["13", "11", "7"] },
    { id: "cult-d6", d: 3, t: "Quel tournoi de tennis se joue sur le gazon de Wimbledon ?", a: "Le tournoi de Wimbledon", x: ["Roland-Garros", "L'US Open", "L'Open d'Australie"] },
    { id: "cult-d7", d: 3, t: "Quelle épreuve d'athlétisme couvre une distance de 42,195 km ?", a: "Le marathon", x: ["Le décathlon", "Le steeple", "Le semi-marathon"] },
    { id: "cult-d8", d: 3, t: "Qui a écrit « Cent Ans de solitude » ?", a: "Gabriel García Márquez", x: ["Jorge Luis Borges", "Pablo Neruda", "Mario Vargas Llosa"] },
    { id: "cult-d9", d: 3, t: "Quel philosophe grec fut le précepteur d'Alexandre le Grand ?", a: "Aristote", x: ["Platon", "Socrate", "Épicure"] },
    { id: "cult-d10", d: 3, t: "Quel écrivain russe a écrit « Guerre et Paix » ?", a: "Léon Tolstoï", x: ["Fiodor Dostoïevski", "Anton Tchekhov", "Nicolas Gogol"] },
    { id: "cult-d11", d: 3, t: "Quel poète italien a écrit « La Divine Comédie » ?", a: "Dante", x: ["Pétrarque", "Boccace", "Machiavel"] },
    { id: "cult-d12", d: 3, t: "Quel sport olympique d'hiver combine tir et ski de fond ?", a: "Le biathlon", x: ["Le pentathlon", "Le combiné nordique", "Le skeleton"] },
    { id: "cult-d13", d: 3, t: "Quel compositeur autrichien a écrit « La Marche turque » ?", a: "Mozart", x: ["Beethoven", "Strauss", "Haydn"] },
    { id: "cult-d14", d: 3, t: "Combien de trous compte un parcours de golf classique ?", a: "18", x: ["9", "12", "24"] },
    { id: "cult-d15", d: 3, t: "Quel écrivain a imaginé « Vingt Mille Lieues sous les mers » ?", a: "Jules Verne", x: ["H.G. Wells", "Isaac Asimov", "Arthur C. Clarke"] },
    // --- Pro (20) ---
    { id: "cult-p1", d: 4, t: "Quel pays a remporté la première Coupe du monde de football, en 1930 ?", a: "L'Uruguay", x: ["Le Brésil", "L'Argentine", "L'Italie"], acc: ["uruguay"] },
    { id: "cult-p2", d: 4, t: "Quel monumental roman de Marcel Proust commence par « Du côté de chez Swann » ?", a: "À la recherche du temps perdu", x: ["Les Misérables", "La Comédie humaine", "Les Rougon-Macquart"] },
    { id: "cult-p3", d: 4, t: "Quel dramaturge anglais a écrit « Hamlet » et « Macbeth » ?", a: "William Shakespeare", x: ["Christopher Marlowe", "Ben Jonson", "Oscar Wilde"] },
    { id: "cult-p4", d: 4, t: "Quel nageur américain a remporté 23 médailles d'or olympiques ?", a: "Michael Phelps", x: ["Mark Spitz", "Ian Thorpe", "Ryan Lochte"] },
    { id: "cult-p5", d: 4, t: "Quel coureur jamaïcain détient les records du monde du 100 m et du 200 m ?", a: "Usain Bolt", x: ["Carl Lewis", "Yohan Blake", "Tyson Gay"] },
    { id: "cult-p6", d: 4, t: "Quel philosophe allemand a écrit « Ainsi parlait Zarathoustra » ?", a: "Friedrich Nietzsche", x: ["Emmanuel Kant", "Georg Hegel", "Arthur Schopenhauer"] },
    { id: "cult-p7", d: 4, t: "Quel écrivain irlandais a écrit le roman « Ulysse » ?", a: "James Joyce", x: ["Samuel Beckett", "Oscar Wilde", "William Butler Yeats"] },
    { id: "cult-p8", d: 4, t: "En quelle année se sont tenus les premiers Jeux olympiques modernes, à Athènes ?", a: "1896", x: ["1900", "1924", "1888"] },
    { id: "cult-p9", d: 4, t: "Quel pilote allemand détient sept titres de champion du monde de Formule 1 ?", a: "Michael Schumacher", x: ["Ayrton Senna", "Alain Prost", "Sebastian Vettel"] },
    { id: "cult-p10", d: 4, t: "Quel écrivain russe a écrit « Crime et Châtiment » ?", a: "Fiodor Dostoïevski", x: ["Léon Tolstoï", "Ivan Tourgueniev", "Alexandre Pouchkine"] },
    { id: "cult-p11", d: 4, t: "Quel jeu oppose des pièces blanches et noires sur 64 cases, avec un roi à protéger ?", a: "Les échecs", x: ["Les dames", "Le go", "Le backgammon"] },
    { id: "cult-p12", d: 4, t: "Quel écrivain américain a écrit « Le Vieil Homme et la Mer » ?", a: "Ernest Hemingway", x: ["John Steinbeck", "William Faulkner", "Francis Scott Fitzgerald"] },
    { id: "cult-p13", d: 4, t: "Quel boxeur américain se surnommait « The Greatest » ?", a: "Mohamed Ali", x: ["Mike Tyson", "Joe Frazier", "George Foreman"] },
    { id: "cult-p14", d: 4, t: "Quelle course cycliste française a lieu chaque été depuis 1903 ?", a: "Le Tour de France", x: ["Le Tour d'Italie", "Le Tour d'Espagne", "Paris-Roubaix"] },
    { id: "cult-p15", d: 4, t: "Quel écrivain français a écrit « Madame Bovary » ?", a: "Gustave Flaubert", x: ["Émile Zola", "Honoré de Balzac", "Guy de Maupassant"] },
    { id: "cult-p16", d: 4, t: "Quel philosophe grec a été condamné à boire la ciguë à Athènes ?", a: "Socrate", x: ["Platon", "Aristote", "Diogène"] },
    { id: "cult-p17", d: 4, t: "Quel dramaturge norvégien a écrit « Une maison de poupée » ?", a: "Henrik Ibsen", x: ["August Strindberg", "Anton Tchekhov", "Bertolt Brecht"] },
    { id: "cult-p18", d: 4, t: "Quelle compétition annuelle oppose les meilleurs clubs de football d'Europe ?", a: "La Ligue des champions", x: ["La Coupe du monde", "L'Euro", "La Copa America"] },
    { id: "cult-p19", d: 4, t: "Quel écrivain français a créé le gentleman-cambrioleur Arsène Lupin ?", a: "Maurice Leblanc", x: ["Gaston Leroux", "Georges Simenon", "Pierre Souvestre"] },
    { id: "cult-p20", d: 4, t: "Quel jeu de stratégie japonais se joue avec des pierres noires et blanches sur un quadrillage ?", a: "Le go", x: ["Le shôgi", "Le mah-jong", "Les dames"] },
  ]),

  ...universe('culture', 'Expressions', [
    // Faciles (5)
    { id: 'expr-f1', d: 1, t: 'Complète : « Qui vole un œuf… »', a: 'vole un bœuf', x: ['vole une poule', 'finit en prison', 'est un voleur'] },
    { id: 'expr-f2', d: 1, t: "Complète : « Petit à petit, l'oiseau fait… »", a: 'son nid', x: ['son trou', 'son chemin', 'sa vie'] },
    { id: 'expr-f3', d: 1, t: 'Complète : « Mieux vaut tard… »', a: 'que jamais', x: ['que rien', "qu'hier", 'que trop tôt'] },
    { id: 'expr-f4', d: 1, t: "Complète : « L'habit ne fait pas… »", a: 'le moine', x: ["l'homme", 'le roi', 'la personne'] },
    { id: 'expr-f5', d: 1, t: 'Que veut dire « poser un lapin » ?', a: 'Ne pas venir à un rendez-vous', x: ['Faire une farce', 'Offrir un cadeau', 'Mentir'] },
    // Moyennes (10)
    { id: 'expr-m1', d: 2, t: "Complète : « Il ne faut pas vendre la peau de l'ours… »", a: "avant de l'avoir tué", x: ["avant l'hiver", 'sans permis', 'à un inconnu'] },
    { id: 'expr-m2', d: 2, t: 'Complète : « Chat échaudé craint… »', a: "l'eau froide", x: ['le feu', 'les chiens', 'la pluie'] },
    { id: 'expr-m3', d: 2, t: 'Complète : « Après la pluie… »', a: 'le beau temps', x: ['les nuages', "l'orage", 'le froid'] },
    { id: 'expr-m4', d: 2, t: 'Que veut dire « avoir le cafard » ?', a: 'Être déprimé', x: ['Avoir peur', 'Être malade', 'Avoir faim'] },
    { id: 'expr-m5', d: 2, t: 'Que veut dire « tomber dans les pommes » ?', a: "S'évanouir", x: ['Se tromper', 'Tomber amoureux', 'Avoir de la chance'] },
    { id: 'expr-m6', d: 2, t: 'Complète : « Loin des yeux… »', a: 'loin du cœur', x: ['loin du corps', 'près du cœur', 'loin de tout'] },
    { id: 'expr-m7', d: 2, t: 'Complète : « Qui sème le vent… »', a: 'récolte la tempête', x: ['récolte le blé', 'perd son temps', "moissonne l'orage"] },
    { id: 'expr-m8', d: 2, t: 'Que veut dire « donner sa langue au chat » ?', a: 'Renoncer à deviner', x: ['Se taire', 'Trop parler', 'Mentir'] },
    { id: 'expr-m9', d: 2, t: 'Complète : « Un tiens vaut mieux… »', a: "que deux tu l'auras", x: ['que rien du tout', 'que deux promesses', "qu'un long discours"] },
    { id: 'expr-m10', d: 2, t: 'Que veut dire « avoir la main verte » ?', a: 'Être doué pour le jardinage', x: ['Être jaloux', 'Être maladroit', 'Être riche'] },
    // Dures (15)
    { id: 'expr-d1', d: 3, t: 'Complète : « La nuit, tous les chats… »', a: 'sont gris', x: ['dorment', 'sortent', 'sont noirs'] },
    { id: 'expr-d2', d: 3, t: "Complète : « On ne fait pas d'omelette sans… »", a: 'casser des œufs', x: ['farine', 'beurre', 'effort'] },
    { id: 'expr-d3', d: 3, t: 'Que veut dire « être au bout du rouleau » ?', a: 'Être épuisé', x: ['Avoir fini un travail', 'Être en retard', 'Être perdu'] },
    { id: 'expr-d4', d: 3, t: "Complète : « Il n'y a pas de fumée sans… »", a: 'feu', x: ['vent', 'cause', 'cheminée'] },
    { id: 'expr-d5', d: 3, t: 'Que veut dire « découvrir le pot aux roses » ?', a: 'Découvrir un secret caché', x: ['Trouver un trésor', 'Faire un cadeau', 'Tomber amoureux'] },
    { id: 'expr-d6', d: 3, t: 'Complète : « Chassez le naturel, il revient… »', a: 'au galop', x: ['au trot', 'toujours', 'en courant'] },
    { id: 'expr-d7', d: 3, t: "Que veut dire « filer à l'anglaise » ?", a: 'Partir discrètement', x: ['Voyager à Londres', 'Parler anglais', 'Se dépêcher'] },
    { id: 'expr-d8', d: 3, t: 'Complète : « Les cordonniers sont les plus mal… »', a: 'chaussés', x: ['payés', 'habillés', 'logés'] },
    { id: 'expr-d9', d: 3, t: 'Que veut dire « avoir un chat dans la gorge » ?', a: 'Être enroué', x: ['Avoir faim', 'Mentir', 'Avoir peur'] },
    { id: 'expr-d10', d: 3, t: "Complète : « Pierre qui roule n'amasse pas… »", a: 'mousse', x: ['poussière', 'rien', "d'argent"] },
    { id: 'expr-d11', d: 3, t: 'Que veut dire « mettre la charrue avant les bœufs » ?', a: 'Faire les choses dans le désordre', x: ['Travailler dur', 'Aller trop vite', 'Se tromper de route'] },
    { id: 'expr-d12', d: 3, t: 'Complète : « Bien mal acquis ne… »', a: 'profite jamais', x: ['dure jamais', 'rapporte rien', 'se garde pas'] },
    { id: 'expr-d13', d: 3, t: 'Que veut dire « prendre ses jambes à son cou » ?', a: "S'enfuir en courant", x: ['Se blesser', 'Faire du sport', 'Être fatigué'] },
    { id: 'expr-d14', d: 3, t: 'Complète : « À bon chat… »', a: 'bon rat', x: ['bonne souris', 'bon chien', 'bon maître'] },
    { id: 'expr-d15', d: 3, t: "Que veut dire « jeter l'éponge » ?", a: 'Abandonner', x: ['Nettoyer', 'Se laver', 'Recommencer'] },
    // Pro (20)
    { id: 'expr-p1', d: 4, t: 'Complète : « Qui trop embrasse… »', a: 'mal étreint', x: ['mal aime', 'perd tout', 'se lasse'] },
    { id: 'expr-p2', d: 4, t: 'Que veut dire « battre la campagne » ?', a: 'Divaguer, déraisonner', x: ['Se promener', 'Gagner une bataille', 'Travailler la terre'] },
    { id: 'expr-p3', d: 4, t: "Complète : « L'occasion fait… »", a: 'le larron', x: ['le maître', 'la fortune', 'le bonheur'] },
    { id: 'expr-p4', d: 4, t: 'Que veut dire « faire chou blanc » ?', a: 'Échouer complètement', x: ['Réussir de justesse', 'Cuisiner', 'Devenir pâle'] },
    { id: 'expr-p5', d: 4, t: "Complète : « Ventre affamé n'a point… »", a: "d'oreilles", x: ['de raison', 'de pitié', 'de patience'] },
    { id: 'expr-p6', d: 4, t: 'Que veut dire « tenir le haut du pavé » ?', a: 'Occuper une position dominante', x: ['Marcher fièrement', 'Être riche', 'Construire une route'] },
    { id: 'expr-p7', d: 4, t: 'Complète : « Tel est pris qui croyait… »', a: 'prendre', x: ['gagner', 'fuir', 'tromper'] },
    { id: 'expr-p8', d: 4, t: "Que veut dire « avoir maille à partir avec quelqu'un » ?", a: 'Avoir un différend avec lui', x: ['Lui devoir de l\'argent', 'Le connaître à peine', 'Partager un repas'] },
    { id: 'expr-p9', d: 4, t: 'Complète : « La fortune sourit… »', a: 'aux audacieux', x: ['aux riches', 'aux patients', 'aux sages'] },
    { id: 'expr-p10', d: 4, t: 'Que veut dire « rester lettre morte » ?', a: "Ne pas être suivi d'effet", x: ['Être oublié', 'Être secret', 'Être illisible'] },
    { id: 'expr-p11', d: 4, t: "Complète : « Nul n'est prophète… »", a: 'en son pays', x: ['en son temps', 'sans honneur', 'chez les rois'] },
    { id: 'expr-p12', d: 4, t: "Que veut dire « damer le pion à quelqu'un » ?", a: "L'emporter sur lui", x: ['Le trahir', 'Jouer avec lui', 'Le vexer'] },
    { id: 'expr-p13', d: 4, t: 'Complète : « Charbonnier est maître… »', a: 'chez soi', x: ['de son feu', 'du village', 'de son art'] },
    { id: 'expr-p14', d: 4, t: 'Que veut dire « prêcher pour sa paroisse » ?', a: 'Défendre son propre intérêt', x: ['Convaincre une foule', "Aller à l'église", 'Dire la vérité'] },
    { id: 'expr-p15', d: 4, t: 'Complète : « Qui va à la chasse… »', a: 'perd sa place', x: ['perd son temps', 'revient bredouille', 'trouve gibier'] },
    { id: 'expr-p16', d: 4, t: "Que veut dire « se faire l'avocat du diable » ?", a: 'Défendre une thèse contraire pour la discussion', x: ['Mentir au tribunal', 'Accuser à tort', "Refuser d'aider"] },
    { id: 'expr-p17', d: 4, t: 'Complète : « Un homme averti… »', a: 'en vaut deux', x: ['ne craint rien', 'vaut mieux', 'reste prudent'] },
    { id: 'expr-p18', d: 4, t: 'Que veut dire « avoir voix au chapitre » ?', a: 'Avoir le droit de donner son avis', x: ['Savoir chanter', 'Lire à voix haute', 'Diriger une réunion'] },
    { id: 'expr-p19', d: 4, t: 'Complète : « À vaincre sans péril, on triomphe… »', a: 'sans gloire', x: ['sans effort', 'sans honneur', 'facilement'] },
    { id: 'expr-p20', d: 4, t: 'Que veut dire « renvoyer aux calendes grecques » ?', a: "Remettre à une date qui n'arrivera jamais", x: ["Reporter d'un jour", 'Annuler définitivement', 'Fêter en Grèce'] },
  ]),
  ...universe('culture', 'Anglais', [
    // Faciles (5)
    { id: 'angl-f1', d: 1, t: 'Comment dit-on « chien » en anglais ?', a: 'Dog', x: ['Cat', 'Bird', 'Fish'] },
    { id: 'angl-f2', d: 1, t: 'Comment dit-on « rouge » en anglais ?', a: 'Red', x: ['Blue', 'Green', 'Yellow'] },
    { id: 'angl-f3', d: 1, t: 'Que signifie le mot anglais « house » ?', a: 'Maison', x: ['Voiture', 'Arbre', 'Route'] },
    { id: 'angl-f4', d: 1, t: 'Comment dit-on « merci » en anglais ?', a: 'Thank you', x: ['Please', 'Sorry', 'Hello'] },
    { id: 'angl-f5', d: 1, t: 'Que signifie « Monday » ?', a: 'Lundi', x: ['Mardi', 'Dimanche', 'Vendredi'] },
    // Moyennes (10)
    { id: 'angl-m1', d: 2, t: 'Comment dit-on « papillon » en anglais ?', a: 'Butterfly', x: ['Ladybug', 'Dragonfly', 'Bee'] },
    { id: 'angl-m2', d: 2, t: 'Que signifie le faux-ami « library » ?', a: 'Bibliothèque', x: ['Librairie', 'Laboratoire', 'Mairie'] },
    { id: 'angl-m3', d: 2, t: 'Comment dit-on « clé » en anglais ?', a: 'Key', x: ['Lock', 'Door', 'Ring'] },
    { id: 'angl-m4', d: 2, t: 'Que signifie le faux-ami « actually » ?', a: 'En fait, en réalité', x: ['Actuellement', 'Activement', 'Bientôt'] },
    { id: 'angl-m5', d: 2, t: 'Comment dit-on « grenouille » en anglais ?', a: 'Frog', x: ['Toad', 'Snake', 'Lizard'] },
    { id: 'angl-m6', d: 2, t: 'Que signifie le verbe « to read » ?', a: 'Lire', x: ['Écrire', 'Compter', 'Parler'] },
    { id: 'angl-m7', d: 2, t: 'Comment dit-on « nuage » en anglais ?', a: 'Cloud', x: ['Rain', 'Storm', 'Sky'] },
    { id: 'angl-m8', d: 2, t: 'Que signifie le faux-ami « to attend » ?', a: 'Assister à', x: ['Attendre', 'Atteindre', 'Tenter'] },
    { id: 'angl-m9', d: 2, t: 'Comment dit-on « ceinture » en anglais ?', a: 'Belt', x: ['Button', 'Sleeve', 'Collar'] },
    { id: 'angl-m10', d: 2, t: "Que signifie l'expression « It's raining cats and dogs » ?", a: 'Il pleut très fort', x: ['Il fait beau', 'Il neige', 'Il vente'] },
    // Dures (15)
    { id: 'angl-d1', d: 3, t: "Que signifie l'expression « to break a leg » ?", a: 'Bonne chance', x: ['Se blesser', 'Partir vite', 'Abandonner'] },
    { id: 'angl-d2', d: 3, t: 'Que signifie le faux-ami « eventually » ?', a: 'Finalement, à la fin', x: ['Éventuellement', 'Peut-être', 'Rarement'] },
    { id: 'angl-d3', d: 3, t: 'Comment dit-on « enclume » en anglais ?', a: 'Anvil', x: ['Hammer', 'Nail', 'Forge'] },
    { id: 'angl-d4', d: 3, t: 'Que signifie le mot « chest » ?', a: 'Poitrine ou coffre', x: ['Chaise', 'Joue', 'Menton'] },
    { id: 'angl-d5', d: 3, t: "Que signifie l'expression « once in a blue moon » ?", a: 'Très rarement', x: ['Une fois par mois', 'La nuit', 'Sans raison'] },
    { id: 'angl-d6', d: 3, t: 'Que signifie le faux-ami « to demand » ?', a: 'Exiger', x: ['Demander poliment', 'Répondre', 'Proposer'] },
    { id: 'angl-d7', d: 3, t: 'Comment dit-on « écureuil » en anglais ?', a: 'Squirrel', x: ['Hedgehog', 'Beaver', 'Otter'] },
    { id: 'angl-d8', d: 3, t: "Que signifie l'expression « to spill the beans » ?", a: 'Vendre la mèche, révéler un secret', x: ['Renverser un plat', 'Perdre patience', 'Gaspiller'] },
    { id: 'angl-d9', d: 3, t: 'Que signifie le verbe « to figure out » ?', a: 'Comprendre, résoudre', x: ['Dessiner', 'Compter', 'Imaginer'] },
    { id: 'angl-d10', d: 3, t: 'Comment dit-on « aiguille » en anglais ?', a: 'Needle', x: ['Thread', 'Pin', 'Hook'] },
    { id: 'angl-d11', d: 3, t: "Que signifie l'expression « a piece of cake » ?", a: "C'est très facile", x: ['Une part de gâteau', 'Une bonne surprise', 'Une part d\'héritage'] },
    { id: 'angl-d12', d: 3, t: 'Que signifie le faux-ami « sensible » ?', a: 'Raisonnable, sensé', x: ['Sensible', 'Fragile', 'Émotif'] },
    { id: 'angl-d13', d: 3, t: 'Comment dit-on « brouillard » en anglais ?', a: 'Fog', x: ['Frost', 'Dew', 'Hail'] },
    { id: 'angl-d14', d: 3, t: "Que signifie l'expression « to cost an arm and a leg » ?", a: 'Coûter très cher', x: ['Être dangereux', 'Faire mal', 'Être fatigant'] },
    { id: 'angl-d15', d: 3, t: 'Que signifie le verbe « to borrow » ?', a: 'Emprunter', x: ['Prêter', 'Voler', 'Rendre'] },
    // Pro (20)
    { id: 'angl-p1', d: 4, t: "Que signifie l'expression « the ball is in your court » ?", a: "C'est à toi de décider", x: ["C'est perdu", "C'est trop tard", "C'est injuste"] },
    { id: 'angl-p2', d: 4, t: 'Que signifie le faux-ami « to pretend » ?', a: 'Faire semblant', x: ['Prétendre à', 'Attendre', 'Comprendre'] },
    { id: 'angl-p3', d: 4, t: 'Comment dit-on « taupe » en anglais ?', a: 'Mole', x: ['Shrew', 'Rat', 'Bat'] },
    { id: 'angl-p4', d: 4, t: "Que signifie l'expression « to bite the bullet » ?", a: 'Affronter une épreuve inévitable', x: ['Trahir quelqu\'un', 'Manger vite', 'Se venger'] },
    { id: 'angl-p5', d: 4, t: 'Que signifie le mot « eventual » ?', a: 'Final, qui finit par arriver', x: ['Éventuel', 'Rare', 'Immédiat'] },
    { id: 'angl-p6', d: 4, t: 'Comment dit-on « moisissure » en anglais ?', a: 'Mould', x: ['Rust', 'Dust', 'Mud'] },
    { id: 'angl-p7', d: 4, t: "Que signifie l'expression « to let the cat out of the bag » ?", a: 'Vendre la mèche', x: ['Libérer quelqu\'un', 'Faire une bêtise', 'Prendre un risque'] },
    { id: 'angl-p8', d: 4, t: 'Que signifie le faux-ami « to achieve » ?', a: 'Accomplir, réussir', x: ['Achever', 'Acheter', 'Essayer'] },
    { id: 'angl-p9', d: 4, t: 'Comment dit-on « verrou » en anglais ?', a: 'Bolt', x: ['Hinge', 'Handle', 'Knob'] },
    { id: 'angl-p10', d: 4, t: "Que signifie l'expression « to be under the weather » ?", a: 'Être un peu malade', x: ['Être mouillé', 'Être triste', 'Être en retard'] },
    { id: 'angl-p11', d: 4, t: 'Que signifie le mot « rope » ?', a: 'Corde', x: ['Ruban', 'Fil', 'Chaîne'] },
    { id: 'angl-p12', d: 4, t: "Que signifie l'expression « to hit the sack » ?", a: 'Aller se coucher', x: ['Se battre', 'Faire les courses', 'Faire du sport'] },
    { id: 'angl-p13', d: 4, t: 'Comment dit-on « hibou » en anglais ?', a: 'Owl', x: ['Hawk', 'Crow', 'Dove'] },
    { id: 'angl-p14', d: 4, t: "Que signifie l'expression « to be on cloud nine » ?", a: 'Être aux anges', x: ['Être perdu', 'Rêver', 'Avoir la tête en l\'air'] },
    { id: 'angl-p15', d: 4, t: 'Que signifie le verbe « to spare » ?', a: 'Épargner, se passer de', x: ['Dépenser', 'Partager', 'Réparer'] },
    { id: 'angl-p16', d: 4, t: 'Comment dit-on « fourmi » en anglais ?', a: 'Ant', x: ['Bee', 'Wasp', 'Fly'] },
    { id: 'angl-p17', d: 4, t: "Que signifie l'expression « to jump on the bandwagon » ?", a: 'Suivre le mouvement', x: ['Sauter de joie', "Changer d'avis", 'Partir en voyage'] },
    { id: 'angl-p18', d: 4, t: 'Que signifie le mot « leaf » ?', a: 'Feuille', x: ['Branche', 'Racine', 'Fleur'] },
    { id: 'angl-p19', d: 4, t: "Que signifie l'expression « to burn the midnight oil » ?", a: 'Travailler tard dans la nuit', x: ["Gaspiller de l'argent", 'Se disputer', 'Faire la fête'] },
    { id: 'angl-p20', d: 4, t: 'Comment dit-on « escargot » en anglais ?', a: 'Snail', x: ['Slug', 'Worm', 'Snake'] },
  ]),

  ...universe('culture', 'Art', [
    // --- Faciles (5) ---
    { id: 'art-f1', d: 1, t: 'Qui a peint la Joconde ?', a: 'Léonard de Vinci', x: ['Pablo Picasso', 'Vincent van Gogh', 'Claude Monet'] },
    { id: 'art-f2', d: 1, t: 'Dans quel musée parisien peut-on voir la Joconde ?', a: 'Le Louvre', x: ["Le musée d'Orsay", 'Le Centre Pompidou', 'Le château de Versailles'] },
    { id: 'art-f3', d: 1, t: 'Avec quel accessoire un peintre mélange-t-il ses couleurs ?', a: 'La palette', x: ['Le pinceau', 'Le chevalet', 'Le cadre'] },
    { id: 'art-f4', d: 1, t: 'Comment appelle-t-on une œuvre sculptée représentant une personne debout ?', a: 'Une statue', x: ['Une fresque', 'Une nature morte', 'Un portrait'] },
    { id: 'art-f5', d: 1, t: 'Quelle couleur obtient-on en mélangeant du bleu et du jaune ?', a: 'Le vert', x: ["L'orange", 'Le violet', 'Le marron'] },
    // --- Moyennes (10) ---
    { id: 'art-m1', d: 2, t: 'Qui a peint « La Nuit étoilée » ?', a: 'Vincent van Gogh', x: ['Claude Monet', 'Pablo Picasso', 'Salvador Dalí'] },
    { id: 'art-m2', d: 2, t: 'Quel mouvement tire son nom du tableau « Impression, soleil levant » de Monet ?', a: "L'impressionnisme", x: ['Le cubisme', 'Le surréalisme', 'Le romantisme'] },
    { id: 'art-m3', d: 2, t: 'Qui a peint le plafond de la chapelle Sixtine ?', a: 'Michel-Ange', x: ['Raphaël', 'Titien', 'Botticelli'] },
    { id: 'art-m4', d: 2, t: 'Quel peintre espagnol a cofondé le cubisme ?', a: 'Pablo Picasso', x: ['Salvador Dalí', 'Joan Miró', 'Francisco de Goya'] },
    { id: 'art-m5', d: 2, t: 'Quelle sculpture de Rodin représente un homme assis, le menton sur la main ?', a: 'Le Penseur', x: ['Le Baiser', 'David', 'La Vénus de Milo'] },
    { id: 'art-m6', d: 2, t: 'Qui a peint « Guernica » ?', a: 'Pablo Picasso', x: ['Salvador Dalí', 'Joan Miró', 'Diego Vélasquez'] },
    { id: 'art-m7', d: 2, t: 'Quel artiste de la Renaissance a sculpté le « David » de marbre à Florence ?', a: 'Michel-Ange', x: ['Donatello', 'Raphaël', 'Botticelli'] },
    { id: 'art-m8', d: 2, t: 'Comment appelle-t-on une peinture réalisée sur un enduit mural encore frais ?', a: 'Une fresque', x: ['Une aquarelle', 'Un pastel', 'Une gravure'] },
    { id: 'art-m9', d: 2, t: "Quel mouvement du XXe siècle, illustré par Dalí, explore le rêve et l'inconscient ?", a: 'Le surréalisme', x: ["L'impressionnisme", 'Le cubisme', 'Le réalisme'] },
    { id: 'art-m10', d: 2, t: 'Quelle technique juxtapose de petits points de couleur ?', a: 'Le pointillisme', x: ['Le fusain', 'La gouache', 'Le collage'] },
    // --- Dures (15) ---
    { id: 'art-d1', d: 3, t: 'Qui a peint « La Jeune Fille à la perle » ?', a: 'Johannes Vermeer', x: ['Rembrandt van Rijn', 'Pierre Paul Rubens', 'Jan van Eyck'] },
    { id: 'art-d2', d: 3, t: 'Quel peintre néerlandais a réalisé « La Ronde de nuit » ?', a: 'Rembrandt van Rijn', x: ['Johannes Vermeer', 'Pierre Paul Rubens', 'Jan van Eyck'] },
    { id: 'art-d3', d: 3, t: 'Quel sculpteur français a créé « Le Penseur » et « Le Baiser » ?', a: 'Auguste Rodin', x: ['Camille Claudel', 'Aristide Maillol', 'Antoine Bourdelle'] },
    { id: 'art-d4', d: 3, t: 'Quel mouvement du début du XXe siècle Picasso et Braque ont-ils fondé ?', a: 'Le cubisme', x: ['Le fauvisme', 'Le futurisme', 'Le dadaïsme'] },
    { id: 'art-d5', d: 3, t: 'Qui a peint « Le Cri » ?', a: 'Edvard Munch', x: ['Gustav Klimt', 'Egon Schiele', 'Emil Nolde'] },
    { id: 'art-d6', d: 3, t: "Quel peintre autrichien a couvert « Le Baiser » de feuilles d'or ?", a: 'Gustav Klimt', x: ['Egon Schiele', 'Edvard Munch', 'Oskar Kokoschka'] },
    { id: 'art-d7', d: 3, t: 'Quelle artiste mexicaine est célèbre pour ses autoportraits ?', a: 'Frida Kahlo', x: ["Georgia O'Keeffe", 'Tamara de Lempicka', 'Remedios Varo'] },
    { id: 'art-d8', d: 3, t: 'Quel peintre néerlandais post-impressionniste a peint « Les Tournesols » ?', a: 'Vincent van Gogh', x: ['Paul Gauguin', 'Paul Cézanne', 'Georges Seurat'] },
    { id: 'art-d9', d: 3, t: 'Quelle fresque de Léonard de Vinci orne un réfectoire de Milan ?', a: 'La Cène', x: ["L'École d'Athènes", 'Le Jugement dernier', "La Création d'Adam"] },
    { id: 'art-d10', d: 3, t: 'Quel peintre baroque italien maîtrisait un clair-obscur intense ?', a: 'Le Caravage', x: ['Le Titien', 'Le Tintoret', 'Le Corrège'] },
    { id: 'art-d11', d: 3, t: 'Quel mouvement, mené par Matisse, choque par ses couleurs violentes ?', a: 'Le fauvisme', x: ['Le cubisme', 'Le pointillisme', 'Le réalisme'] },
    { id: 'art-d12', d: 3, t: 'Quel artiste américain peint en versant la peinture, le « dripping » ?', a: 'Jackson Pollock', x: ['Mark Rothko', 'Andy Warhol', 'Willem de Kooning'] },
    { id: 'art-d13', d: 3, t: 'Quel artiste du pop art a peint des boîtes de soupe Campbell ?', a: 'Andy Warhol', x: ['Roy Lichtenstein', 'Jasper Johns', 'Robert Rauschenberg'] },
    { id: 'art-d14', d: 3, t: 'Comment nomme-t-on le mouvement contestataire de Marcel Duchamp et de son urinoir « Fontaine » ?', a: 'Le dadaïsme', x: ['Le surréalisme', 'Le cubisme', "L'expressionnisme"] },
    { id: 'art-d15', d: 3, t: "Qui a peint « Les Ménines » à la cour d'Espagne ?", a: 'Diego Vélasquez', x: ['Francisco de Goya', 'El Greco', 'Bartolomé Murillo'] },
    // --- Pro (20) ---
    { id: 'art-p1', d: 4, t: 'Vers quelle année Léonard de Vinci a-t-il commencé la Joconde ?', a: 'Vers 1503', x: ['Vers 1450', 'Vers 1650', 'Vers 1800'] },
    { id: 'art-p2', d: 4, t: 'Qui a peint « Le Trois Mai 1808 » ?', a: 'Francisco de Goya', x: ['Diego Vélasquez', 'El Greco', 'Joan Miró'] },
    { id: 'art-p3', d: 4, t: "Quel peintre est un pionnier de l'art abstrait avec ses « Compositions » ?", a: 'Vassily Kandinsky', x: ['Kazimir Malevitch', 'Piet Mondrian', 'Paul Klee'] },
    { id: 'art-p4', d: 4, t: 'Quel artiste a peint « Carré noir sur fond blanc », icône du suprématisme ?', a: 'Kazimir Malevitch', x: ['Vassily Kandinsky', 'Piet Mondrian', 'El Lissitzky'] },
    { id: 'art-p5', d: 4, t: 'Quel peintre néerlandais est connu pour ses grilles de lignes noires et de rectangles de couleurs primaires ?', a: 'Piet Mondrian', x: ['Theo van Doesburg', 'Kazimir Malevitch', 'Paul Klee'] },
    { id: 'art-p6', d: 4, t: "Quelle technique à base de pigments liés au jaune d'œuf précède la peinture à l'huile ?", a: 'La tempera', x: ["L'aquarelle", 'Le pastel', 'La gouache'] },
    { id: 'art-p7', d: 4, t: 'Quel terme désigne le dégradé vaporeux popularisé par Léonard de Vinci ?', a: 'Le sfumato', x: ['Le clair-obscur', "Le trompe-l'œil", 'Le camaïeu'] },
    { id: 'art-p8', d: 4, t: "Quel sculpteur baroque italien a réalisé « L'Extase de sainte Thérèse » ?", a: 'Le Bernin', x: ['Michel-Ange', 'Donatello', 'Verrocchio'] },
    { id: 'art-p9', d: 4, t: 'Quel peintre a réalisé la série des « Nymphéas » dans son jardin de Giverny ?', a: 'Claude Monet', x: ['Édouard Manet', 'Camille Pissarro', 'Alfred Sisley'] },
    { id: 'art-p10', d: 4, t: 'Quel peintre post-impressionniste a peint de nombreuses scènes de Tahiti ?', a: 'Paul Gauguin', x: ['Paul Cézanne', 'Georges Seurat', 'Henri Rousseau'] },
    { id: 'art-p11', d: 4, t: "Quel peintre, père de l'art moderne, a multiplié les vues de la montagne Sainte-Victoire ?", a: 'Paul Cézanne', x: ['Paul Gauguin', 'Édouard Manet', 'Camille Pissarro'] },
    { id: 'art-p12', d: 4, t: "Quel pointilliste a peint « Un dimanche après-midi à l'île de la Grande Jatte » ?", a: 'Georges Seurat', x: ['Paul Signac', 'Camille Pissarro', 'Henri-Edmond Cross'] },
    { id: 'art-p13', d: 4, t: 'Quel peintre romantique a réalisé « La Liberté guidant le peuple » ?', a: 'Eugène Delacroix', x: ['Théodore Géricault', 'Jean-Auguste-Dominique Ingres', 'Gustave Courbet'] },
    { id: 'art-p14', d: 4, t: 'Quel tableau de Géricault montre des naufragés sur une embarcation de fortune ?', a: 'Le Radeau de la Méduse', x: ['La Liberté guidant le peuple', 'Le Sacre de Napoléon', 'Les Glaneuses'] },
    { id: 'art-p15', d: 4, t: 'Quel chef de file du réalisme a peint « Un enterrement à Ornans » ?', a: 'Gustave Courbet', x: ['Jean-François Millet', 'Honoré Daumier', 'Camille Corot'] },
    { id: 'art-p16', d: 4, t: "Quelle peintre impressionniste, belle-sœur d'Édouard Manet, a réalisé « Le Berceau » ?", a: 'Berthe Morisot', x: ['Mary Cassatt', 'Rosa Bonheur', 'Marie Bracquemond'] },
    { id: 'art-p17', d: 4, t: "Quelle fresque de Raphaël au Vatican réunit les philosophes de l'Antiquité ?", a: "L'École d'Athènes", x: ["La Création d'Adam", 'La Cène', 'Le Jugement dernier'] },
    { id: 'art-p18', d: 4, t: "Quel mouvement d'arts décoratifs, tout en courbes végétales, fleurit vers 1900 ?", a: "L'Art nouveau", x: ["L'Art déco", 'Le Bauhaus', 'Le brutalisme'] },
    { id: 'art-p19', d: 4, t: 'Quelle école allemande de design, fondée par Walter Gropius en 1919, marque le modernisme ?', a: 'Le Bauhaus', x: ["L'Art nouveau", 'Le Werkbund', 'Le constructivisme'] },
    { id: 'art-p20', d: 4, t: 'Quel graveur japonais a créé « La Grande Vague de Kanagawa » ?', a: 'Hokusai', x: ['Hiroshige', 'Utamaro', 'Sesshū'] },
  ]),

  ...universe('culture', 'Gastronomie', [
    // --- Faciles (5) ---
    { id: "gastro-f1", d: 1, t: "De quel pays la pizza est-elle originaire ?", a: "L'Italie", x: ["La France", "La Grèce", "L'Espagne"] },
    { id: "gastro-f2", d: 1, t: "Quel ingrédient principal sert à faire le pain ?", a: "La farine", x: ["Le riz", "Le maïs", "Le sucre"] },
    { id: "gastro-f3", d: 1, t: "Quelle boisson chaude obtient-on à partir de grains torréfiés ?", a: "Le café", x: ["Le thé", "Le chocolat", "Le lait"] },
    { id: "gastro-f4", d: 1, t: "De quel pays le sushi est-il originaire ?", a: "Le Japon", x: ["La Chine", "La Corée", "La Thaïlande"] },
    { id: "gastro-f5", d: 1, t: "Quel fruit jaune et courbé les singes adorent-ils ?", a: "La banane", x: ["La pomme", "La fraise", "Le raisin"] },
    // --- Moyennes (10) ---
    { id: "gastro-m1", d: 2, t: "Quel plat italien est fait de longues pâtes fines ?", a: "Les spaghettis", x: ["Le risotto", "La polenta", "Les lasagnes"] },
    { id: "gastro-m2", d: 2, t: "Quel fromage bleu français est affiné dans les caves de l'Aveyron ?", a: "Le roquefort", x: ["Le camembert", "Le comté", "Le brie"] },
    { id: "gastro-m3", d: 2, t: "Quelle épice rouge et précieuse provient des pistils d'une fleur de crocus ?", a: "Le safran", x: ["Le curcuma", "Le paprika", "La cannelle"] },
    { id: "gastro-m4", d: 2, t: "Quel plat espagnol au riz safrané contient souvent fruits de mer et poulet ?", a: "La paella", x: ["La tortilla", "Le gaspacho", "Les tapas"] },
    { id: "gastro-m5", d: 2, t: "De quel pays le taco et le guacamole sont-ils originaires ?", a: "Le Mexique", x: ["L'Espagne", "Le Pérou", "Le Brésil"] },
    { id: "gastro-m6", d: 2, t: "Quel plat japonais consiste en du poisson cru sur du riz vinaigré ?", a: "Le sushi", x: ["Le ramen", "Le tempura", "Le yakitori"] },
    { id: "gastro-m7", d: 2, t: "Quelle viennoiserie française en forme de croissant est un classique du petit-déjeuner ?", a: "Le croissant", x: ["L'éclair", "Le macaron", "La brioche"] },
    { id: "gastro-m8", d: 2, t: "Quel légume fait pleurer quand on le coupe ?", a: "L'oignon", x: ["La carotte", "Le poireau", "La tomate"] },
    { id: "gastro-m9", d: 2, t: "Quelle boisson pétillante prestigieuse vient d'une région française du même nom ?", a: "Le champagne", x: ["Le cidre", "La bière", "Le porto"] },
    { id: "gastro-m10", d: 2, t: "Quel plat vietnamien est une soupe de nouilles au bœuf ou au poulet ?", a: "Le pho", x: ["Le pad thaï", "Le curry", "Le nem"] },
    // --- Dures (15) ---
    { id: "gastro-d1", d: 3, t: "Quel guide gastronomique décerne des « étoiles » aux restaurants ?", a: "Le guide Michelin", x: ["Le Gault et Millau", "Le Routard", "Le Fooding"], acc: ["michelin"] },
    { id: "gastro-d2", d: 3, t: "Quel chef français est l'un des plus étoilés de l'histoire ?", a: "Alain Ducasse", x: ["Cyril Lignac", "Thierry Marx", "Philippe Etchebest"] },
    { id: "gastro-d3", d: 3, t: "Quel chef lyonnais légendaire était surnommé « Monsieur Paul » ?", a: "Paul Bocuse", x: ["Alain Ducasse", "Joël Robuchon", "Guy Savoy"] },
    { id: "gastro-d4", d: 3, t: "De quel pays le kimchi, chou fermenté et pimenté, est-il un incontournable ?", a: "La Corée du Sud", x: ["Le Japon", "La Chine", "Le Vietnam"] },
    { id: "gastro-d5", d: 3, t: "Quel fruit est la base du guacamole ?", a: "L'avocat", x: ["La tomate", "Le poivron", "Le concombre"] },
    { id: "gastro-d6", d: 3, t: "Quel dessert italien contient du mascarpone et du café ?", a: "Le tiramisu", x: ["La panna cotta", "Le cannolo", "Le zabaglione"], acc: ["tiramisu"] },
    { id: "gastro-d7", d: 3, t: "Quel plat suisse consiste à tremper du pain dans du fromage fondu ?", a: "La fondue", x: ["La raclette", "Le gratin", "La tartiflette"] },
    { id: "gastro-d8", d: 3, t: "Quelle viande n'est traditionnellement pas consommée dans les religions musulmane et juive ?", a: "Le porc", x: ["Le bœuf", "Le poulet", "L'agneau"] },
    { id: "gastro-d9", d: 3, t: "Quel condiment japonais vert et très piquant accompagne les sushis ?", a: "Le wasabi", x: ["Le gingembre", "Le soja", "Le miso"], acc: ["wasabi"] },
    { id: "gastro-d10", d: 3, t: "Quelle céréale est la base de l'alimentation d'une grande partie de l'Asie ?", a: "Le riz", x: ["Le blé", "Le maïs", "L'orge"] },
    { id: "gastro-d11", d: 3, t: "Quel alcool anisé du sud de la France se boit allongé d'eau ?", a: "Le pastis", x: ["Le calvados", "Le cognac", "L'armagnac"] },
    { id: "gastro-d12", d: 3, t: "Quel plat indien mijoté et épicé se décline au poulet ou aux légumes ?", a: "Le curry", x: ["Le couscous", "Le tajine", "Le chili"] },
    { id: "gastro-d13", d: 3, t: "Quelle pâtisserie ronde à la coque colorée et à la ganache est une spécialité française ?", a: "Le macaron", x: ["Le canelé", "La madeleine", "Le financier"] },
    { id: "gastro-d14", d: 3, t: "Quel fruit de mer bivalve peut parfois contenir une perle ?", a: "L'huître", x: ["La moule", "La coquille Saint-Jacques", "La palourde"] },
    { id: "gastro-d15", d: 3, t: "De quelle région le couscous est-il un plat traditionnel ?", a: "Le Maghreb", x: ["Les Balkans", "La Scandinavie", "Les Caraïbes"] },
    // --- Pro (20) ---
    { id: "gastro-p1", d: 4, t: "Quel chef français a codifié la haute cuisine et créé la « pêche Melba » ?", a: "Auguste Escoffier", x: ["Paul Bocuse", "Antonin Carême", "Alain Ducasse"] },
    { id: "gastro-p2", d: 4, t: "Quelle sauce française au beurre et aux jaunes d'œufs accompagne les asperges ?", a: "La sauce hollandaise", x: ["La béchamel", "La mayonnaise", "La sauce tomate"] },
    { id: "gastro-p3", d: 4, t: "Quel plat à base d'escargots est une spécialité de Bourgogne ?", a: "Les escargots de Bourgogne", x: ["La quiche lorraine", "La bouillabaisse", "Le cassoulet"] },
    { id: "gastro-p4", d: 4, t: "De quelle ville la bouillabaisse, soupe de poissons, est-elle la spécialité ?", a: "Marseille", x: ["Lyon", "Nice", "Bordeaux"] },
    { id: "gastro-p5", d: 4, t: "Quel cépage rouge est emblématique des grands vins de Bourgogne ?", a: "Le pinot noir", x: ["Le merlot", "Le cabernet sauvignon", "La syrah"] },
    { id: "gastro-p6", d: 4, t: "Quelle région française est la plus célèbre pour ses grands vins rouges classés ?", a: "Le Bordelais", x: ["L'Alsace", "La Champagne", "La Provence"] },
    { id: "gastro-p7", d: 4, t: "Quel plat japonais consiste en des nouilles servies dans un bouillon fumant ?", a: "Le ramen", x: ["Le sushi", "Le sashimi", "Le tempura"] },
    { id: "gastro-p8", d: 4, t: "Quel alcool japonais est fabriqué à partir de riz fermenté ?", a: "Le saké", x: ["Le soju", "Le baijiu", "Le mirin"] },
    { id: "gastro-p9", d: 4, t: "Quel piment mexicain fumé et séché parfume de nombreux plats ?", a: "Le chipotle", x: ["Le jalapeño", "Le habanero", "Le poblano"] },
    { id: "gastro-p10", d: 4, t: "Quel plat coréen est un bol de riz garni de légumes, de viande et d'un œuf ?", a: "Le bibimbap", x: ["Le bulgogi", "Le japchae", "Le tteokbokki"], acc: ["bibimbap"] },
    { id: "gastro-p11", d: 4, t: "Quelle est la principale matière première du chocolat ?", a: "La fève de cacao", x: ["La noisette", "La vanille", "Le café"] },
    { id: "gastro-p12", d: 4, t: "Quel fromage italien à pâte dure se râpe sur les pâtes ?", a: "Le parmesan", x: ["La mozzarella", "Le gorgonzola", "La ricotta"] },
    { id: "gastro-p13", d: 4, t: "Quel plat mijoté du Sud-Ouest associe haricots blancs, saucisse et confit ?", a: "Le cassoulet", x: ["La choucroute", "Le pot-au-feu", "La blanquette"] },
    { id: "gastro-p14", d: 4, t: "Quelle herbe aromatique est la base du pesto italien ?", a: "Le basilic", x: ["Le persil", "La coriandre", "L'estragon"] },
    { id: "gastro-p15", d: 4, t: "Quel dessert français a une fine couche de sucre caramélisé et craquant sur le dessus ?", a: "La crème brûlée", x: ["La crème caramel", "Le pudding", "La panna cotta"] },
    { id: "gastro-p16", d: 4, t: "De quel pays le goulash, ragoût au paprika, est-il originaire ?", a: "La Hongrie", x: ["La Pologne", "L'Autriche", "La Roumanie"] },
    { id: "gastro-p17", d: 4, t: "Comment appelle-t-on la cuisine qui use de la science pour transformer les textures ?", a: "La gastronomie moléculaire", x: ["La cuisine fusion", "La cuisine crue", "La street food"] },
    { id: "gastro-p18", d: 4, t: "Quel restaurant espagnol de Ferran Adrià fut élu meilleur du monde plusieurs fois ?", a: "elBulli", x: ["Noma", "El Celler de Can Roca", "Mugaritz"], acc: ["el bulli", "elbulli"] },
    { id: "gastro-p19", d: 4, t: "Quel restaurant danois de René Redzepi a révolutionné la cuisine nordique ?", a: "Noma", x: ["elBulli", "Osteria Francescana", "The Fat Duck"] },
    { id: "gastro-p20", d: 4, t: "Quelle épice, tirée d'une orchidée, parfume glaces et pâtisseries ?", a: "La vanille", x: ["La cannelle", "La muscade", "Le clou de girofle"] },
  ]),
  ...universe('culture', 'Mode', [
    // --- Faciles (5) ---
    { id: "mode-f1", d: 1, t: "Quelle maison française de luxe a pour logo deux « C » entrelacés ?", a: "Chanel", x: ["Dior", "Gucci", "Prada"] },
    { id: "mode-f2", d: 1, t: "Quelle ville est considérée comme la capitale mondiale de la mode ?", a: "Paris", x: ["Milan", "New York", "Londres"] },
    { id: "mode-f3", d: 1, t: "Comment appelle-t-on l'événement où des mannequins présentent une collection ?", a: "Un défilé de mode", x: ["Un vernissage", "Un showroom", "Une braderie"], acc: ["défilé", "fashion show"] },
    { id: "mode-f4", d: 1, t: "Quelle maison française est célèbre pour ses sacs et son monogramme « LV » ?", a: "Louis Vuitton", x: ["Hermès", "Chanel", "Dior"] },
    { id: "mode-f5", d: 1, t: "Comment appelle-t-on la mode sur mesure et d'exception, par opposition au prêt-à-porter ?", a: "La haute couture", x: ["Le vintage", "La fast fashion", "Le streetwear"], acc: ["haute couture"] },
    // --- Moyennes (10) ---
    { id: "mode-m1", d: 2, t: "Quel couturier a créé le « New Look » en 1947 ?", a: "Christian Dior", x: ["Coco Chanel", "Yves Saint Laurent", "Hubert de Givenchy"] },
    { id: "mode-m2", d: 2, t: "Quelle couturière a libéré la femme du corset et créé la petite robe noire ?", a: "Coco Chanel", x: ["Jeanne Lanvin", "Elsa Schiaparelli", "Madeleine Vionnet"] },
    { id: "mode-m3", d: 2, t: "Quel couturier a imposé le smoking pour femme dans les années 60 ?", a: "Yves Saint Laurent", x: ["Christian Dior", "Karl Lagerfeld", "Pierre Cardin"] },
    { id: "mode-m4", d: 2, t: "Quel styliste allemand au catogan blanc a longtemps dirigé Chanel ?", a: "Karl Lagerfeld", x: ["Jean-Paul Gaultier", "Christian Lacroix", "Thierry Mugler"] },
    { id: "mode-m5", d: 2, t: "Quelle maison italienne a pour emblème une tête de Méduse ?", a: "Versace", x: ["Gucci", "Prada", "Armani"] },
    { id: "mode-m6", d: 2, t: "Quel magazine de mode américain est surnommé « la bible de la mode » ?", a: "Vogue", x: ["Elle", "Harper's Bazaar", "Marie Claire"] },
    { id: "mode-m7", d: 2, t: "Comment appelle-t-on une personne qui défile pour présenter des vêtements ?", a: "Un mannequin", x: ["Un styliste", "Un couturier", "Un modéliste"] },
    { id: "mode-m8", d: 2, t: "Quel couturier français, surnommé « l'enfant terrible de la mode », adore la marinière ?", a: "Jean-Paul Gaultier", x: ["Christian Lacroix", "Thierry Mugler", "Yves Saint Laurent"] },
    { id: "mode-m9", d: 2, t: "Quelle chaîne suédoise est un géant de la « fast fashion » ?", a: "H&M", x: ["Zara", "Uniqlo", "Primark"] },
    { id: "mode-m10", d: 2, t: "Quelle marque espagnole du groupe Inditex est une reine de la fast fashion ?", a: "Zara", x: ["H&M", "Mango", "Bershka"] },
    // --- Dures (15) ---
    { id: "mode-d1", d: 3, t: "Quelle rédactrice en chef a longtemps régné sur le Vogue américain ?", a: "Anna Wintour", x: ["Carine Roitfeld", "Grace Coddington", "Diana Vreeland"] },
    { id: "mode-d2", d: 3, t: "Quel styliste britannique provocateur, ancien de Givenchy, est mort en 2010 ?", a: "Alexander McQueen", x: ["John Galliano", "Vivienne Westwood", "Stella McCartney"] },
    { id: "mode-d3", d: 3, t: "Quelle créatrice britannique est surnommée la « reine du punk » ?", a: "Vivienne Westwood", x: ["Stella McCartney", "Mary Quant", "Phoebe Philo"] },
    { id: "mode-d4", d: 3, t: "À quelle créatrice attribue-t-on la popularisation de la minijupe dans les années 60 ?", a: "Mary Quant", x: ["Vivienne Westwood", "Coco Chanel", "Jean Shrimpton"] },
    { id: "mode-d5", d: 3, t: "Quel couturier a dirigé Dior avant d'être renvoyé après un scandale en 2011 ?", a: "John Galliano", x: ["Raf Simons", "Hedi Slimane", "Alexander McQueen"] },
    { id: "mode-d6", d: 3, t: "Quel directeur artistique a réinventé Gucci vers 2015 avec un style maximaliste ?", a: "Alessandro Michele", x: ["Tom Ford", "Frida Giannini", "Sabato De Sarno"] },
    { id: "mode-d7", d: 3, t: "Quel créateur américain a relancé Gucci dans les années 1990 avant de fonder sa marque ?", a: "Tom Ford", x: ["Marc Jacobs", "Michael Kors", "Ralph Lauren"] },
    { id: "mode-d8", d: 3, t: "Quel créateur a fait entrer Louis Vuitton dans le streetwear de luxe avant sa mort en 2021 ?", a: "Virgil Abloh", x: ["Kim Jones", "Marc Jacobs", "Kanye West"] },
    { id: "mode-d9", d: 3, t: "Quelle marque de streetwear de luxe fondée par Virgil Abloh détourne guillemets et flèches ?", a: "Off-White", x: ["Supreme", "A Bathing Ape", "Fear of God"] },
    { id: "mode-d10", d: 3, t: "Quelle marque new-yorkaise de skate au logo rouge et blanc est culte dans le streetwear ?", a: "Supreme", x: ["Off-White", "Palace", "Stüssy"] },
    { id: "mode-d11", d: 3, t: "Quel groupe de luxe français, dirigé par Bernard Arnault, possède Louis Vuitton et Dior ?", a: "LVMH", x: ["Kering", "Richemont", "Chanel"], acc: ["lvmh"] },
    { id: "mode-d12", d: 3, t: "Quel groupe de luxe, rival de LVMH, possède Gucci et Saint Laurent ?", a: "Kering", x: ["LVMH", "Richemont", "Prada"] },
    { id: "mode-d13", d: 3, t: "Quelle maison italienne est connue pour ses tricots en zigzag multicolores ?", a: "Missoni", x: ["Fendi", "Etro", "Marni"] },
    { id: "mode-d14", d: 3, t: "Comment appelle-t-on les mannequins vedettes des années 90 comme Naomi Campbell et Cindy Crawford ?", a: "Les top models", x: ["Les égéries", "Les it-girls", "Les cover-girls"], acc: ["top models", "supermodels", "top model"] },
    { id: "mode-d15", d: 3, t: "Quelle maison française au logo de cavalier est célèbre pour son sac « Birkin » ?", a: "Hermès", x: ["Louis Vuitton", "Chanel", "Céline"] },
    // --- Pro (20) ---
    { id: "mode-p1", d: 4, t: "Quel est le vrai prénom de Coco Chanel ?", a: "Gabrielle", x: ["Gaby", "Jeanne", "Colette"], acc: ["gabrielle"] },
    { id: "mode-p2", d: 4, t: "En quelle année Yves Saint Laurent présente-t-il son smoking pour femme ?", a: "1966", x: ["1947", "1954", "1983"] },
    { id: "mode-p3", d: 4, t: "Quel homme d'affaires a cofondé la maison Yves Saint Laurent ?", a: "Pierre Bergé", x: ["François Pinault", "Bernard Arnault", "Marcel Boussac"] },
    { id: "mode-p4", d: 4, t: "Quelle maison Yves Saint Laurent dirigeait-il avant de fonder la sienne ?", a: "Dior", x: ["Chanel", "Givenchy", "Balenciaga"] },
    { id: "mode-p5", d: 4, t: "Quel couturier espagnol était surnommé « le maître » par ses pairs, dont Dior ?", a: "Cristóbal Balenciaga", x: ["Paco Rabanne", "Manuel Pertegaz", "Mariano Fortuny"] },
    { id: "mode-p6", d: 4, t: "Quelle actrice a inspiré le sac « Kelly » d'Hermès ?", a: "Grace Kelly", x: ["Audrey Hepburn", "Jane Birkin", "Brigitte Bardot"] },
    { id: "mode-p7", d: 4, t: "Quelle chanteuse et actrice a donné son nom au sac le plus convoité d'Hermès ?", a: "Jane Birkin", x: ["Grace Kelly", "Françoise Hardy", "Marianne Faithfull"] },
    { id: "mode-p8", d: 4, t: "Quel styliste italien a été assassiné devant sa villa de Miami en 1997 ?", a: "Gianni Versace", x: ["Valentino Garavani", "Giorgio Armani", "Ottavio Missoni"] },
    { id: "mode-p9", d: 4, t: "Quel couturier italien est associé à une nuance de rouge qui porte son nom ?", a: "Valentino", x: ["Versace", "Armani", "Gucci"] },
    { id: "mode-p10", d: 4, t: "Quel duo de créateurs signe une maison sicilienne et baroque ?", a: "Dolce & Gabbana", x: ["Ermenegildo Zegna", "Fendi", "Missoni"] },
    { id: "mode-p11", d: 4, t: "Quelle créatrice, fille d'un Beatle, est connue pour sa mode sans cuir ni fourrure ?", a: "Stella McCartney", x: ["Phoebe Philo", "Clare Waight Keller", "Victoria Beckham"] },
    { id: "mode-p12", d: 4, t: "Quel créateur a poussé Balenciaga vers un style extrême dans les années 2020 ?", a: "Demna Gvasalia", x: ["Nicolas Ghesquière", "Alexander Wang", "Josephus Thimister"], acc: ["demna"] },
    { id: "mode-p13", d: 4, t: "Quelle marque, cofondée par Demna, s'est fait connaître en détournant le logo DHL ?", a: "Vetements", x: ["Off-White", "Y/Project", "Ambush"], acc: ["vetements", "vêtements"] },
    { id: "mode-p14", d: 4, t: "Quel couturier tunisien, star des années 80-90, moulait le corps de ses modèles ?", a: "Azzedine Alaïa", x: ["Thierry Mugler", "Claude Montana", "Jean-Paul Gaultier"] },
    { id: "mode-p15", d: 4, t: "Quel couturier des années 80 est connu pour ses robes-sculptures et le parfum « Angel » ?", a: "Thierry Mugler", x: ["Claude Montana", "Jean-Paul Gaultier", "Christian Lacroix"] },
    { id: "mode-p16", d: 4, t: "Quelle maison japonaise d'avant-garde a été fondée par Rei Kawakubo ?", a: "Comme des Garçons", x: ["Issey Miyake", "Yohji Yamamoto", "Kenzo"] },
    { id: "mode-p17", d: 4, t: "Quel créateur japonais est connu pour ses plissés techniques et un parfum en flacon conique ?", a: "Issey Miyake", x: ["Yohji Yamamoto", "Rei Kawakubo", "Kenzo Takada"] },
    { id: "mode-p18", d: 4, t: "Quelle mannequin britannique, muse de Calvin Klein, incarne le « heroin chic » des années 90 ?", a: "Kate Moss", x: ["Naomi Campbell", "Linda Evangelista", "Claudia Schiffer"] },
    { id: "mode-p19", d: 4, t: "Quel styliste américain incarne le rêve américain avec son poloclub et son cavalier ?", a: "Ralph Lauren", x: ["Tommy Hilfiger", "Calvin Klein", "Michael Kors"] },
    { id: "mode-p20", d: 4, t: "Quelle ville, avec Paris, Milan et Londres, complète le quatuor des capitales de la mode ?", a: "New York", x: ["Tokyo", "Berlin", "Madrid"] },
  ]),
];
