import type { Question } from '../../../core/models';
import { universe } from './_build';

// Les questions « drapeau » utilisent flagcdn.com (PNG, fiable). Elles
// nécessitent une connexion ; hors-ligne, l'image ne s'affiche pas.
const flag = (code: string): { type: 'image'; uri: string } => ({
  type: 'image',
  uri: `https://flagcdn.com/w320/${code}.png`,
});

export const cultureQuestions: Question[] = [
  {
    id: 'culture-1',
    theme: 'culture',
    difficulty: 1,
    text: 'Quelle est la capitale de la France ?',
    answer: 'Paris',
    distractors: ['Lyon', 'Marseille', 'Bordeaux'],
  },
  {
    id: 'culture-2',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de continents compte-t-on sur Terre ?',
    answer: '7',
    acceptable: ['sept'],
    distractors: ['5', '6', '8'],
  },
  {
    id: 'culture-3',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la planète la plus proche du Soleil ?',
    answer: 'Mercure',
    distractors: ['Vénus', 'Mars', 'La Terre'],
  },
  {
    id: 'culture-4',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel élément chimique a pour symbole « O » ?',
    answer: 'Oxygène',
    distractors: ['Or', 'Osmium', 'Hydrogène'],
  },
  {
    id: 'culture-5',
    theme: 'culture',
    difficulty: 3,
    text: 'En quelle année est tombé le mur de Berlin ?',
    answer: '1989',
    distractors: ['1991', '1987', '1985'],
  },
  {
    id: 'culture-6',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de côtés possède un hexagone ?',
    answer: '6',
    acceptable: ['six'],
    distractors: ['5', '7', '8'],
  },
  {
    id: 'culture-7',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand océan du monde ?',
    answer: "L'océan Pacifique",
    acceptable: ['pacifique'],
    distractors: ['Atlantique', 'Indien', 'Arctique'],
  },
  {
    id: 'culture-8',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a peint La Joconde ?',
    answer: 'Léonard de Vinci',
    acceptable: ['de vinci', 'vinci', 'leonard de vinci'],
    distractors: ['Michel-Ange', 'Raphaël', 'Botticelli'],
  },
  {
    id: 'culture-9',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel est le plus petit État indépendant du monde ?',
    answer: 'Le Vatican',
    acceptable: ['vatican'],
    distractors: ['Monaco', 'Saint-Marin', 'Nauru'],
  },
  {
    id: 'culture-10',
    theme: 'culture',
    difficulty: 1,
    text: 'Quel pays a la forme d\'une botte ?',
    answer: "L'Italie",
    acceptable: ['italie'],
    distractors: ["L'Espagne", 'La Grèce', 'Le Portugal'],
  },
  {
    id: 'culture-11',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand organe du corps humain ?',
    answer: 'La peau',
    acceptable: ['peau'],
    distractors: ['Le foie', 'Les poumons', "L'intestin"],
  },
  {
    id: 'culture-12',
    theme: 'culture',
    difficulty: 3,
    text: 'Quelle est approximativement la vitesse de la lumière ?',
    answer: '300 000 km/s',
    acceptable: ['300000', '300 000'],
    distractors: ['150 000 km/s', '1 000 000 km/s', '30 000 km/s'],
  },
  {
    id: 'culture-13',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de joueurs composent une équipe de football sur le terrain ?',
    answer: '11',
    distractors: ['10', '12', '9'],
  },
  {
    id: 'culture-14',
    theme: 'culture',
    difficulty: 4,
    text: 'En quelle année a eu lieu la prise de la Bastille ?',
    answer: '1789',
    distractors: ['1799', '1769', '1804'],
  },
  {
    id: 'culture-15',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la plus haute montagne du monde ?',
    answer: "L'Everest",
    acceptable: ['everest', 'mont everest'],
    distractors: ['Le K2', 'Le Mont Blanc', 'Le Kilimandjaro'],
  },
  {
    id: 'culture-16',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a développé la théorie de la relativité ?',
    answer: 'Albert Einstein',
    acceptable: ['einstein'],
    distractors: ['Isaac Newton', 'Niels Bohr', 'Galilée'],
  },
  {
    id: 'culture-17',
    theme: 'culture',
    difficulty: 3,
    text: "Quel est le symbole chimique de l'or ?",
    answer: 'Au',
    distractors: ['Or', 'Ag', 'Gd'],
  },
  {
    id: 'culture-18',
    theme: 'culture',
    difficulty: 4,
    text: 'Combien d\'os compte le squelette humain adulte ?',
    answer: '206',
    distractors: ['256', '198', '212'],
  },
  {
    id: 'culture-19',
    theme: 'culture',
    difficulty: 1,
    text: 'Quelle planète est surnommée la planète rouge ?',
    answer: 'Mars',
    distractors: ['Vénus', 'Jupiter', 'Saturne'],
  },
  {
    id: 'culture-20',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a écrit la pièce « Roméo et Juliette » ?',
    answer: 'William Shakespeare',
    acceptable: ['shakespeare'],
    distractors: ['Molière', 'Victor Hugo', 'Voltaire'],
  },

  // ----- Questions « devine le drapeau » (image) -----
  {
    id: 'culture-flag-jp',
    theme: 'culture',
    difficulty: 1,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Japon',
    acceptable: ['le japon'],
    distractors: ['Chine', 'Corée du Sud', 'Bangladesh'],
    media: flag('jp'),
  },
  {
    id: 'culture-flag-br',
    theme: 'culture',
    difficulty: 2,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Brésil',
    acceptable: ['le brésil', 'bresil'],
    distractors: ['Argentine', 'Portugal', 'Cameroun'],
    media: flag('br'),
  },
  {
    id: 'culture-flag-ca',
    theme: 'culture',
    difficulty: 1,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Canada',
    acceptable: ['le canada'],
    distractors: ['États-Unis', 'Royaume-Uni', 'Suisse'],
    media: flag('ca'),
  },
  {
    id: 'culture-flag-kr',
    theme: 'culture',
    difficulty: 3,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Corée du Sud',
    acceptable: ['coree du sud', 'corée'],
    distractors: ['Japon', 'Chine', 'Mongolie'],
    media: flag('kr'),
  },
  {
    id: 'culture-flag-in',
    theme: 'culture',
    difficulty: 3,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Inde',
    acceptable: ["l'inde"],
    distractors: ['Niger', 'Irlande', "Côte d'Ivoire"],
    media: flag('in'),
  },
  {
    id: 'culture-flag-au',
    theme: 'culture',
    difficulty: 3,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Australie',
    acceptable: ["l'australie"],
    distractors: ['Nouvelle-Zélande', 'Royaume-Uni', 'Fidji'],
    media: flag('au'),
  },
  {
    id: 'culture-flag-ro',
    theme: 'culture',
    difficulty: 4,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Roumanie',
    acceptable: ['la roumanie'],
    distractors: ['Tchad', 'Andorre', 'Moldavie'],
    media: flag('ro'),
    hints: ['Très proche du drapeau du Tchad…'],
  },
  {
    id: 'culture-flag-gr',
    theme: 'culture',
    difficulty: 4,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Grèce',
    acceptable: ['la grèce', 'grece'],
    distractors: ['Israël', 'Uruguay', 'Finlande'],
    media: flag('gr'),
  },

  // ----- Culture générale (suite) -----
  {
    id: 'culture-21',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?',
    answer: 'Le dioxyde de carbone',
    acceptable: ['co2', 'dioxyde de carbone', 'gaz carbonique'],
    distractors: ["L'oxygène", "L'azote", "L'hydrogène"],
  },
  {
    id: 'culture-22',
    theme: 'culture',
    difficulty: 3,
    text: 'Combien de cœurs possède une pieuvre ?',
    answer: '3',
    acceptable: ['trois'],
    distractors: ['1', '2', '5'],
  },
  {
    id: 'culture-23',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la monnaie du Japon ?',
    answer: 'Le yen',
    acceptable: ['yen'],
    distractors: ['Le won', 'Le yuan', 'Le baht'],
  },
  {
    id: 'culture-24',
    theme: 'culture',
    difficulty: 4,
    text: "En quelle année l'Homme a-t-il marché sur la Lune pour la première fois ?",
    answer: '1969',
    distractors: ['1972', '1965', '1959'],
  },
  {
    id: 'culture-25',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la plus grande planète du système solaire ?',
    answer: 'Jupiter',
    distractors: ['Saturne', 'Neptune', 'La Terre'],
  },
  {
    id: 'culture-26',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel métal est liquide à température ambiante ?',
    answer: 'Le mercure',
    acceptable: ['mercure'],
    distractors: ['Le plomb', "L'étain", 'Le zinc'],
  },
  {
    id: 'culture-27',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a écrit « Les Misérables » ?',
    answer: 'Victor Hugo',
    acceptable: ['hugo'],
    distractors: ['Émile Zola', 'Gustave Flaubert', 'Honoré de Balzac'],
  },
  {
    id: 'culture-28',
    theme: 'culture',
    difficulty: 3,
    text: 'Quelle langue compte le plus de locuteurs natifs au monde ?',
    answer: 'Le chinois',
    acceptable: ['chinois', 'mandarin'],
    distractors: ["L'anglais", "L'espagnol", "L'hindi"],
  },
  {
    id: 'culture-29',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel scientifique a énoncé les trois lois du mouvement ?',
    answer: 'Isaac Newton',
    acceptable: ['newton'],
    distractors: ['Galilée', 'Albert Einstein', 'Johannes Kepler'],
  },
  {
    id: 'culture-30',
    theme: 'culture',
    difficulty: 4,
    text: 'En quelle année a commencé la Première Guerre mondiale ?',
    answer: '1914',
    distractors: ['1918', '1912', '1939'],
  },

  // ----- Culture générale (lot supplémentaire) -----
  {
    id: 'culture-31',
    theme: 'culture',
    difficulty: 1,
    text: 'Quel est le plus long fleuve du monde ?',
    answer: 'Le Nil',
    acceptable: ['nil', 'le nil'],
    distractors: ["L'Amazone", 'Le Mississippi', 'Le Yangtsé'],
  },
  {
    id: 'culture-32',
    theme: 'culture',
    difficulty: 3,
    text: "Quelle est la capitale de l'Australie ?",
    answer: 'Canberra',
    distractors: ['Sydney', 'Melbourne', 'Perth'],
    hints: ['Ce n\'est pas la plus grande ville du pays.'],
  },
  {
    id: 'culture-33',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand désert chaud du monde ?',
    answer: 'Le Sahara',
    acceptable: ['sahara', 'le sahara'],
    distractors: ['Le Gobi', 'Le Kalahari', "L'Atacama"],
  },
  {
    id: 'culture-34',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand pays du monde par sa superficie ?',
    answer: 'La Russie',
    acceptable: ['russie', 'la russie'],
    distractors: ['Le Canada', 'La Chine', 'Les États-Unis'],
  },
  {
    id: 'culture-35',
    theme: 'culture',
    difficulty: 1,
    text: "Quelle est la capitale de l'Espagne ?",
    answer: 'Madrid',
    distractors: ['Barcelone', 'Séville', 'Valence'],
  },
  {
    id: 'culture-36',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel fleuve traverse la ville de Londres ?',
    answer: 'La Tamise',
    acceptable: ['tamise', 'la tamise'],
    distractors: ['La Seine', 'Le Rhin', 'Le Danube'],
  },
  {
    id: 'culture-37',
    theme: 'culture',
    difficulty: 4,
    text: "Quel est le pays le plus peuplé d'Afrique ?",
    answer: 'Le Nigéria',
    acceptable: ['nigeria', 'nigéria', 'le nigéria'],
    distractors: ["L'Égypte", "L'Éthiopie", "L'Afrique du Sud"],
  },
  {
    id: 'culture-38',
    theme: 'culture',
    difficulty: 1,
    text: "Sur quel continent se situe majoritairement l'Égypte ?",
    answer: "L'Afrique",
    acceptable: ['afrique'],
    distractors: ["L'Asie", "L'Europe", "L'Amérique"],
  },
  {
    id: 'culture-39',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui fut le premier président des États-Unis ?',
    answer: 'George Washington',
    acceptable: ['washington', 'george washington'],
    distractors: ['Abraham Lincoln', 'Thomas Jefferson', 'Benjamin Franklin'],
  },
  {
    id: 'culture-40',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel empereur français a été vaincu à la bataille de Waterloo ?',
    answer: 'Napoléon Bonaparte',
    acceptable: ['napoleon', 'napoléon', 'bonaparte'],
    distractors: ['Louis XVI', 'Charles de Gaulle', 'Jules César'],
  },
  {
    id: 'culture-41',
    theme: 'culture',
    difficulty: 3,
    text: "En quelle année s'est terminée la Seconde Guerre mondiale ?",
    answer: '1945',
    distractors: ['1944', '1939', '1918'],
  },
  {
    id: 'culture-42',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle civilisation antique a construit les pyramides de Gizeh ?',
    answer: 'Les Égyptiens',
    acceptable: ['egyptiens', 'égyptiens', 'egypte ancienne'],
    distractors: ['Les Romains', 'Les Mayas', 'Les Grecs'],
  },
  {
    id: 'culture-43',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel roi de France est surnommé le « Roi-Soleil » ?',
    answer: 'Louis XIV',
    acceptable: ['louis 14', 'louis xiv'],
    distractors: ['Louis XVI', 'François Ier', 'Henri IV'],
  },
  {
    id: 'culture-44',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel célèbre paquebot a coulé en 1912 lors de son voyage inaugural ?',
    answer: 'Le Titanic',
    acceptable: ['titanic', 'le titanic'],
    distractors: ['Le Lusitania', 'Le Britannic', 'Le Bismarck'],
  },
  {
    id: 'culture-45',
    theme: 'culture',
    difficulty: 1,
    text: 'Quel est l\'animal le plus haut du monde ?',
    answer: 'La girafe',
    acceptable: ['girafe', 'la girafe'],
    distractors: ["L'éléphant", "L'autruche", 'Le chameau'],
  },
  {
    id: 'culture-46',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand animal ayant jamais existé, vivant dans les océans ?',
    answer: 'La baleine bleue',
    acceptable: ['baleine bleue', 'baleine', 'la baleine bleue'],
    distractors: ['Le cachalot', 'Le requin-baleine', 'Le mégalodon'],
  },
  {
    id: 'culture-47',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de pattes possède une araignée ?',
    answer: '8',
    acceptable: ['huit'],
    distractors: ['6', '10', '4'],
  },
  {
    id: 'culture-48',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel est l\'os le plus long du corps humain ?',
    answer: 'Le fémur',
    acceptable: ['femur', 'fémur', 'le fémur'],
    distractors: ['Le tibia', "L'humérus", 'Le péroné'],
  },
  {
    id: 'culture-49',
    theme: 'culture',
    difficulty: 1,
    text: 'Quel organe pompe le sang dans tout le corps ?',
    answer: 'Le cœur',
    acceptable: ['coeur', 'cœur', 'le cœur'],
    distractors: ['Le foie', 'Les poumons', 'Le cerveau'],
  },
  {
    id: 'culture-50',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la formule chimique de l\'eau ?',
    answer: 'H2O',
    acceptable: ['h2o'],
    distractors: ['CO2', 'O2', 'H2O2'],
  },
  {
    id: 'culture-51',
    theme: 'culture',
    difficulty: 4,
    text: 'Combien de chromosomes possède une cellule humaine ?',
    answer: '46',
    acceptable: ['46', 'quarante-six'],
    distractors: ['23', '48', '64'],
  },
  {
    id: 'culture-52',
    theme: 'culture',
    difficulty: 2,
    text: 'Autour de quel astre la Terre tourne-t-elle en environ 365 jours ?',
    answer: 'Le Soleil',
    acceptable: ['soleil', 'le soleil'],
    distractors: ['La Lune', 'Mars', 'Jupiter'],
  },
  {
    id: 'culture-53',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle planète possède les anneaux les plus visibles du système solaire ?',
    answer: 'Saturne',
    distractors: ['Jupiter', 'Uranus', 'Neptune'],
  },
  {
    id: 'culture-54',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel scientifique a formulé la théorie de l\'évolution par sélection naturelle ?',
    answer: 'Charles Darwin',
    acceptable: ['darwin'],
    distractors: ['Gregor Mendel', 'Louis Pasteur', 'Carl von Linné'],
  },
  {
    id: 'culture-55',
    theme: 'culture',
    difficulty: 3,
    text: "Quel gaz représente environ 21 % de l'air que nous respirons ?",
    answer: "L'oxygène",
    acceptable: ['oxygene', 'oxygène', 'o2'],
    distractors: ["L'azote", 'Le CO2', "L'hydrogène"],
  },
  {
    id: 'culture-56',
    theme: 'culture',
    difficulty: 4,
    text: 'Quelle est approximativement la vitesse du son dans l\'air ?',
    answer: '340 m/s',
    acceptable: ['340', '340 m/s', '1235 km/h'],
    distractors: ['3 000 m/s', '100 m/s', '300 000 km/s'],
  },
  {
    id: 'culture-57',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a composé la « 9e Symphonie » et son célèbre « Hymne à la joie » ?',
    answer: 'Beethoven',
    acceptable: ['beethoven', 'ludwig van beethoven'],
    distractors: ['Mozart', 'Bach', 'Chopin'],
  },
  {
    id: 'culture-58',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel peintre néerlandais s\'est tristement coupé une partie de l\'oreille ?',
    answer: 'Vincent van Gogh',
    acceptable: ['van gogh', 'vincent van gogh'],
    distractors: ['Rembrandt', 'Vermeer', 'Claude Monet'],
  },
  {
    id: 'culture-59',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a écrit « Le Petit Prince » ?',
    answer: 'Antoine de Saint-Exupéry',
    acceptable: ['saint-exupery', 'saint exupéry', 'saint-exupéry'],
    distractors: ['Jules Verne', 'Charles Perrault', 'Marcel Pagnol'],
  },
  {
    id: 'culture-60',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel mouvement artistique Pablo Picasso a-t-il cofondé avec Georges Braque ?',
    answer: 'Le cubisme',
    acceptable: ['cubisme', 'le cubisme'],
    distractors: ["L'impressionnisme", 'Le surréalisme', 'Le fauvisme'],
  },
  {
    id: 'culture-61',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel écrivain a créé le détective Sherlock Holmes ?',
    answer: 'Arthur Conan Doyle',
    acceptable: ['conan doyle', 'doyle'],
    distractors: ['Agatha Christie', 'Edgar Allan Poe', 'Maurice Leblanc'],
  },
  {
    id: 'culture-62',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de joueurs compte une équipe de basket sur le terrain ?',
    answer: '5',
    acceptable: ['cinq'],
    distractors: ['6', '7', '11'],
  },
  {
    id: 'culture-63',
    theme: 'culture',
    difficulty: 3,
    text: "Tous les combien d'années ont lieu les Jeux olympiques d'été ?",
    answer: '4 ans',
    acceptable: ['4', 'quatre', '4 ans', 'tous les 4 ans'],
    distractors: ['2 ans', '5 ans', '3 ans'],
  },
  {
    id: 'culture-64',
    theme: 'culture',
    difficulty: 2,
    text: 'Dans quel sport parle-t-on d\'un « ace » et d\'un « let » ?',
    answer: 'Le tennis',
    acceptable: ['tennis', 'le tennis'],
    distractors: ['Le golf', 'Le volley', 'Le rugby'],
  },
  {
    id: 'culture-65',
    theme: 'culture',
    difficulty: 4,
    text: 'Quel pays a remporté la première Coupe du monde de football, en 1930 ?',
    answer: "L'Uruguay",
    acceptable: ['uruguay'],
    distractors: ['Le Brésil', "L'Argentine", "L'Italie"],
  },
  {
    id: 'culture-66',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de minutes y a-t-il dans une heure ?',
    answer: '60',
    acceptable: ['soixante'],
    distractors: ['100', '24', '12'],
  },
  {
    id: 'culture-67',
    theme: 'culture',
    difficulty: 2,
    text: 'Combien de couleurs distingue-t-on traditionnellement dans un arc-en-ciel ?',
    answer: '7',
    acceptable: ['sept'],
    distractors: ['5', '6', '9'],
  },
  {
    id: 'culture-68',
    theme: 'culture',
    difficulty: 3,
    text: 'Quelle est la langue officielle du Brésil ?',
    answer: 'Le portugais',
    acceptable: ['portugais', 'le portugais'],
    distractors: ["L'espagnol", 'Le brésilien', 'Le français'],
  },
  {
    id: 'culture-69',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel instrument de musique possède 88 touches ?',
    answer: 'Le piano',
    acceptable: ['piano', 'le piano'],
    distractors: ["L'orgue", "L'accordéon", 'La harpe'],
  },
  {
    id: 'culture-70',
    theme: 'culture',
    difficulty: 4,
    text: "Quel est l'élément chimique le plus abondant dans l'univers ?",
    answer: "L'hydrogène",
    acceptable: ['hydrogene', 'hydrogène', 'h'],
    distractors: ["L'oxygène", "L'hélium", 'Le carbone'],
  },
  ...universe('culture', 'Expressions', [
    // Faciles (5)
    { id: 'expr-f1', d: 1, t: 'Complète : « Qui vole un œuf… »', a: 'vole un bœuf', x: ['vole une poule', 'finit en prison', 'est un voleur'] },
    { id: 'expr-f2', d: 1, t: "Complète : « Petit à petit, l'oiseau fait… »", a: 'son nid', x: ['son trou', 'son chemin', 'sa vie'] },
    { id: 'expr-f3', d: 1, t: 'Complète : « Mieux vaut tard… »', a: 'que jamais', x: ['que rien', "qu'hier", 'que trop tôt'] },
    { id: 'expr-f4', d: 1, t: "Complète : « L'habit ne fait pas… »", a: 'le moine', x: ["l'homme", 'le roi', 'la personne'] },
    { id: 'expr-f5', d: 1, t: 'Que veut dire « poser un lapin » ?', a: 'Ne pas venir à un rendez-vous', x: ['Faire une farce', 'Offrir un cadeau', 'Mentir'] },
    // Moyennes (10)
    { id: 'expr-m1', d: 2, t: "Complète : « Il ne faut pas vendre la peau de l'ours… »", a: "avant de l'avoir tué", x: ["avant l'hiver", 'sans permis', 'à un inconnu'] },
    { id: 'expr-m2', d: 2, t: 'Complète : « Chat échaudé craint… »', a: "l'eau froide", x: ['le feu', 'les chiens', 'la pluie'] },
    { id: 'expr-m3', d: 2, t: 'Complète : « Après la pluie… »', a: 'le beau temps', x: ['les nuages', "l'orage", 'le froid'] },
    { id: 'expr-m4', d: 2, t: 'Que veut dire « avoir le cafard » ?', a: 'Être déprimé', x: ['Avoir peur', 'Être malade', 'Avoir faim'] },
    { id: 'expr-m5', d: 2, t: 'Que veut dire « tomber dans les pommes » ?', a: "S'évanouir", x: ['Se tromper', 'Tomber amoureux', 'Avoir de la chance'] },
    { id: 'expr-m6', d: 2, t: 'Complète : « Loin des yeux… »', a: 'loin du cœur', x: ['loin du corps', 'près du cœur', 'loin de tout'] },
    { id: 'expr-m7', d: 2, t: 'Complète : « Qui sème le vent… »', a: 'récolte la tempête', x: ['récolte le blé', 'perd son temps', "moissonne l'orage"] },
    { id: 'expr-m8', d: 2, t: 'Que veut dire « donner sa langue au chat » ?', a: 'Renoncer à deviner', x: ['Se taire', 'Trop parler', 'Mentir'] },
    { id: 'expr-m9', d: 2, t: 'Complète : « Un tiens vaut mieux… »', a: "que deux tu l'auras", x: ['que rien du tout', 'que deux promesses', "qu'un long discours"] },
    { id: 'expr-m10', d: 2, t: 'Que veut dire « avoir la main verte » ?', a: 'Être doué pour le jardinage', x: ['Être jaloux', 'Être maladroit', 'Être riche'] },
    // Dures (15)
    { id: 'expr-d1', d: 3, t: 'Complète : « La nuit, tous les chats… »', a: 'sont gris', x: ['dorment', 'sortent', 'sont noirs'] },
    { id: 'expr-d2', d: 3, t: "Complète : « On ne fait pas d'omelette sans… »", a: 'casser des œufs', x: ['farine', 'beurre', 'effort'] },
    { id: 'expr-d3', d: 3, t: 'Que veut dire « être au bout du rouleau » ?', a: 'Être épuisé', x: ['Avoir fini un travail', 'Être en retard', 'Être perdu'] },
    { id: 'expr-d4', d: 3, t: "Complète : « Il n'y a pas de fumée sans… »", a: 'feu', x: ['vent', 'cause', 'cheminée'] },
    { id: 'expr-d5', d: 3, t: 'Que veut dire « découvrir le pot aux roses » ?', a: 'Découvrir un secret caché', x: ['Trouver un trésor', 'Faire un cadeau', 'Tomber amoureux'] },
    { id: 'expr-d6', d: 3, t: 'Complète : « Chassez le naturel, il revient… »', a: 'au galop', x: ['au trot', 'toujours', 'en courant'] },
    { id: 'expr-d7', d: 3, t: "Que veut dire « filer à l'anglaise » ?", a: 'Partir discrètement', x: ['Voyager à Londres', 'Parler anglais', 'Se dépêcher'] },
    { id: 'expr-d8', d: 3, t: 'Complète : « Les cordonniers sont les plus mal… »', a: 'chaussés', x: ['payés', 'habillés', 'logés'] },
    { id: 'expr-d9', d: 3, t: 'Que veut dire « avoir un chat dans la gorge » ?', a: 'Être enroué', x: ['Avoir faim', 'Mentir', 'Avoir peur'] },
    { id: 'expr-d10', d: 3, t: "Complète : « Pierre qui roule n'amasse pas… »", a: 'mousse', x: ['poussière', 'rien', "d'argent"] },
    { id: 'expr-d11', d: 3, t: 'Que veut dire « mettre la charrue avant les bœufs » ?', a: 'Faire les choses dans le désordre', x: ['Travailler dur', 'Aller trop vite', 'Se tromper de route'] },
    { id: 'expr-d12', d: 3, t: 'Complète : « Bien mal acquis ne… »', a: 'profite jamais', x: ['dure jamais', 'rapporte rien', 'se garde pas'] },
    { id: 'expr-d13', d: 3, t: 'Que veut dire « prendre ses jambes à son cou » ?', a: "S'enfuir en courant", x: ['Se blesser', 'Faire du sport', 'Être fatigué'] },
    { id: 'expr-d14', d: 3, t: 'Complète : « À bon chat… »', a: 'bon rat', x: ['bonne souris', 'bon chien', 'bon maître'] },
    { id: 'expr-d15', d: 3, t: "Que veut dire « jeter l'éponge » ?", a: 'Abandonner', x: ['Nettoyer', 'Se laver', 'Recommencer'] },
    // Pro (20)
    { id: 'expr-p1', d: 4, t: 'Complète : « Qui trop embrasse… »', a: 'mal étreint', x: ['mal aime', 'perd tout', 'se lasse'] },
    { id: 'expr-p2', d: 4, t: 'Que veut dire « battre la campagne » ?', a: 'Divaguer, déraisonner', x: ['Se promener', 'Gagner une bataille', 'Travailler la terre'] },
    { id: 'expr-p3', d: 4, t: "Complète : « L'occasion fait… »", a: 'le larron', x: ['le maître', 'la fortune', 'le bonheur'] },
    { id: 'expr-p4', d: 4, t: 'Que veut dire « faire chou blanc » ?', a: 'Échouer complètement', x: ['Réussir de justesse', 'Cuisiner', 'Devenir pâle'] },
    { id: 'expr-p5', d: 4, t: "Complète : « Ventre affamé n'a point… »", a: "d'oreilles", x: ['de raison', 'de pitié', 'de patience'] },
    { id: 'expr-p6', d: 4, t: 'Que veut dire « tenir le haut du pavé » ?', a: 'Occuper une position dominante', x: ['Marcher fièrement', 'Être riche', 'Construire une route'] },
    { id: 'expr-p7', d: 4, t: 'Complète : « Tel est pris qui croyait… »', a: 'prendre', x: ['gagner', 'fuir', 'tromper'] },
    { id: 'expr-p8', d: 4, t: "Que veut dire « avoir maille à partir avec quelqu'un » ?", a: 'Avoir un différend avec lui', x: ['Lui devoir de l\'argent', 'Le connaître à peine', 'Partager un repas'] },
    { id: 'expr-p9', d: 4, t: 'Complète : « La fortune sourit… »', a: 'aux audacieux', x: ['aux riches', 'aux patients', 'aux sages'] },
    { id: 'expr-p10', d: 4, t: 'Que veut dire « rester lettre morte » ?', a: "Ne pas être suivi d'effet", x: ['Être oublié', 'Être secret', 'Être illisible'] },
    { id: 'expr-p11', d: 4, t: "Complète : « Nul n'est prophète… »", a: 'en son pays', x: ['en son temps', 'sans honneur', 'chez les rois'] },
    { id: 'expr-p12', d: 4, t: "Que veut dire « damer le pion à quelqu'un » ?", a: "L'emporter sur lui", x: ['Le trahir', 'Jouer avec lui', 'Le vexer'] },
    { id: 'expr-p13', d: 4, t: 'Complète : « Charbonnier est maître… »', a: 'chez soi', x: ['de son feu', 'du village', 'de son art'] },
    { id: 'expr-p14', d: 4, t: 'Que veut dire « prêcher pour sa paroisse » ?', a: 'Défendre son propre intérêt', x: ['Convaincre une foule', "Aller à l'église", 'Dire la vérité'] },
    { id: 'expr-p15', d: 4, t: 'Complète : « Qui va à la chasse… »', a: 'perd sa place', x: ['perd son temps', 'revient bredouille', 'trouve gibier'] },
    { id: 'expr-p16', d: 4, t: "Que veut dire « se faire l'avocat du diable » ?", a: 'Défendre une thèse contraire pour la discussion', x: ['Mentir au tribunal', 'Accuser à tort', "Refuser d'aider"] },
    { id: 'expr-p17', d: 4, t: 'Complète : « Un homme averti… »', a: 'en vaut deux', x: ['ne craint rien', 'vaut mieux', 'reste prudent'] },
    { id: 'expr-p18', d: 4, t: 'Que veut dire « avoir voix au chapitre » ?', a: 'Avoir le droit de donner son avis', x: ['Savoir chanter', 'Lire à voix haute', 'Diriger une réunion'] },
    { id: 'expr-p19', d: 4, t: 'Complète : « À vaincre sans péril, on triomphe… »', a: 'sans gloire', x: ['sans effort', 'sans honneur', 'facilement'] },
    { id: 'expr-p20', d: 4, t: 'Que veut dire « renvoyer aux calendes grecques » ?', a: "Remettre à une date qui n'arrivera jamais", x: ["Reporter d'un jour", 'Annuler définitivement', 'Fêter en Grèce'] },
  ]),
  ...universe('culture', 'Anglais', [
    // Faciles (5)
    { id: 'angl-f1', d: 1, t: 'Comment dit-on « chien » en anglais ?', a: 'Dog', x: ['Cat', 'Bird', 'Fish'] },
    { id: 'angl-f2', d: 1, t: 'Comment dit-on « rouge » en anglais ?', a: 'Red', x: ['Blue', 'Green', 'Yellow'] },
    { id: 'angl-f3', d: 1, t: 'Que signifie le mot anglais « house » ?', a: 'Maison', x: ['Voiture', 'Arbre', 'Route'] },
    { id: 'angl-f4', d: 1, t: 'Comment dit-on « merci » en anglais ?', a: 'Thank you', x: ['Please', 'Sorry', 'Hello'] },
    { id: 'angl-f5', d: 1, t: 'Que signifie « Monday » ?', a: 'Lundi', x: ['Mardi', 'Dimanche', 'Vendredi'] },
    // Moyennes (10)
    { id: 'angl-m1', d: 2, t: 'Comment dit-on « papillon » en anglais ?', a: 'Butterfly', x: ['Ladybug', 'Dragonfly', 'Bee'] },
    { id: 'angl-m2', d: 2, t: 'Que signifie le faux-ami « library » ?', a: 'Bibliothèque', x: ['Librairie', 'Laboratoire', 'Mairie'] },
    { id: 'angl-m3', d: 2, t: 'Comment dit-on « clé » en anglais ?', a: 'Key', x: ['Lock', 'Door', 'Ring'] },
    { id: 'angl-m4', d: 2, t: 'Que signifie le faux-ami « actually » ?', a: 'En fait, en réalité', x: ['Actuellement', 'Activement', 'Bientôt'] },
    { id: 'angl-m5', d: 2, t: 'Comment dit-on « grenouille » en anglais ?', a: 'Frog', x: ['Toad', 'Snake', 'Lizard'] },
    { id: 'angl-m6', d: 2, t: 'Que signifie le verbe « to read » ?', a: 'Lire', x: ['Écrire', 'Compter', 'Parler'] },
    { id: 'angl-m7', d: 2, t: 'Comment dit-on « nuage » en anglais ?', a: 'Cloud', x: ['Rain', 'Storm', 'Sky'] },
    { id: 'angl-m8', d: 2, t: 'Que signifie le faux-ami « to attend » ?', a: 'Assister à', x: ['Attendre', 'Atteindre', 'Tenter'] },
    { id: 'angl-m9', d: 2, t: 'Comment dit-on « ceinture » en anglais ?', a: 'Belt', x: ['Button', 'Sleeve', 'Collar'] },
    { id: 'angl-m10', d: 2, t: "Que signifie l'expression « It's raining cats and dogs » ?", a: 'Il pleut très fort', x: ['Il fait beau', 'Il neige', 'Il vente'] },
    // Dures (15)
    { id: 'angl-d1', d: 3, t: "Que signifie l'expression « to break a leg » ?", a: 'Bonne chance', x: ['Se blesser', 'Partir vite', 'Abandonner'] },
    { id: 'angl-d2', d: 3, t: 'Que signifie le faux-ami « eventually » ?', a: 'Finalement, à la fin', x: ['Éventuellement', 'Peut-être', 'Rarement'] },
    { id: 'angl-d3', d: 3, t: 'Comment dit-on « enclume » en anglais ?', a: 'Anvil', x: ['Hammer', 'Nail', 'Forge'] },
    { id: 'angl-d4', d: 3, t: 'Que signifie le mot « chest » ?', a: 'Poitrine ou coffre', x: ['Chaise', 'Joue', 'Menton'] },
    { id: 'angl-d5', d: 3, t: "Que signifie l'expression « once in a blue moon » ?", a: 'Très rarement', x: ['Une fois par mois', 'La nuit', 'Sans raison'] },
    { id: 'angl-d6', d: 3, t: 'Que signifie le faux-ami « to demand » ?', a: 'Exiger', x: ['Demander poliment', 'Répondre', 'Proposer'] },
    { id: 'angl-d7', d: 3, t: 'Comment dit-on « écureuil » en anglais ?', a: 'Squirrel', x: ['Hedgehog', 'Beaver', 'Otter'] },
    { id: 'angl-d8', d: 3, t: "Que signifie l'expression « to spill the beans » ?", a: 'Vendre la mèche, révéler un secret', x: ['Renverser un plat', 'Perdre patience', 'Gaspiller'] },
    { id: 'angl-d9', d: 3, t: 'Que signifie le verbe « to figure out » ?', a: 'Comprendre, résoudre', x: ['Dessiner', 'Compter', 'Imaginer'] },
    { id: 'angl-d10', d: 3, t: 'Comment dit-on « aiguille » en anglais ?', a: 'Needle', x: ['Thread', 'Pin', 'Hook'] },
    { id: 'angl-d11', d: 3, t: "Que signifie l'expression « a piece of cake » ?", a: "C'est très facile", x: ['Une part de gâteau', 'Une bonne surprise', 'Une part d\'héritage'] },
    { id: 'angl-d12', d: 3, t: 'Que signifie le faux-ami « sensible » ?', a: 'Raisonnable, sensé', x: ['Sensible', 'Fragile', 'Émotif'] },
    { id: 'angl-d13', d: 3, t: 'Comment dit-on « brouillard » en anglais ?', a: 'Fog', x: ['Frost', 'Dew', 'Hail'] },
    { id: 'angl-d14', d: 3, t: "Que signifie l'expression « to cost an arm and a leg » ?", a: 'Coûter très cher', x: ['Être dangereux', 'Faire mal', 'Être fatigant'] },
    { id: 'angl-d15', d: 3, t: 'Que signifie le verbe « to borrow » ?', a: 'Emprunter', x: ['Prêter', 'Voler', 'Rendre'] },
    // Pro (20)
    { id: 'angl-p1', d: 4, t: "Que signifie l'expression « the ball is in your court » ?", a: "C'est à toi de décider", x: ["C'est perdu", "C'est trop tard", "C'est injuste"] },
    { id: 'angl-p2', d: 4, t: 'Que signifie le faux-ami « to pretend » ?', a: 'Faire semblant', x: ['Prétendre à', 'Attendre', 'Comprendre'] },
    { id: 'angl-p3', d: 4, t: 'Comment dit-on « taupe » en anglais ?', a: 'Mole', x: ['Shrew', 'Rat', 'Bat'] },
    { id: 'angl-p4', d: 4, t: "Que signifie l'expression « to bite the bullet » ?", a: 'Affronter une épreuve inévitable', x: ['Trahir quelqu\'un', 'Manger vite', 'Se venger'] },
    { id: 'angl-p5', d: 4, t: 'Que signifie le mot « eventual » ?', a: 'Final, qui finit par arriver', x: ['Éventuel', 'Rare', 'Immédiat'] },
    { id: 'angl-p6', d: 4, t: 'Comment dit-on « moisissure » en anglais ?', a: 'Mould', x: ['Rust', 'Dust', 'Mud'] },
    { id: 'angl-p7', d: 4, t: "Que signifie l'expression « to let the cat out of the bag » ?", a: 'Vendre la mèche', x: ['Libérer quelqu\'un', 'Faire une bêtise', 'Prendre un risque'] },
    { id: 'angl-p8', d: 4, t: 'Que signifie le faux-ami « to achieve » ?', a: 'Accomplir, réussir', x: ['Achever', 'Acheter', 'Essayer'] },
    { id: 'angl-p9', d: 4, t: 'Comment dit-on « verrou » en anglais ?', a: 'Bolt', x: ['Hinge', 'Handle', 'Knob'] },
    { id: 'angl-p10', d: 4, t: "Que signifie l'expression « to be under the weather » ?", a: 'Être un peu malade', x: ['Être mouillé', 'Être triste', 'Être en retard'] },
    { id: 'angl-p11', d: 4, t: 'Que signifie le mot « rope » ?', a: 'Corde', x: ['Ruban', 'Fil', 'Chaîne'] },
    { id: 'angl-p12', d: 4, t: "Que signifie l'expression « to hit the sack » ?", a: 'Aller se coucher', x: ['Se battre', 'Faire les courses', 'Faire du sport'] },
    { id: 'angl-p13', d: 4, t: 'Comment dit-on « hibou » en anglais ?', a: 'Owl', x: ['Hawk', 'Crow', 'Dove'] },
    { id: 'angl-p14', d: 4, t: "Que signifie l'expression « to be on cloud nine » ?", a: 'Être aux anges', x: ['Être perdu', 'Rêver', 'Avoir la tête en l\'air'] },
    { id: 'angl-p15', d: 4, t: 'Que signifie le verbe « to spare » ?', a: 'Épargner, se passer de', x: ['Dépenser', 'Partager', 'Réparer'] },
    { id: 'angl-p16', d: 4, t: 'Comment dit-on « fourmi » en anglais ?', a: 'Ant', x: ['Bee', 'Wasp', 'Fly'] },
    { id: 'angl-p17', d: 4, t: "Que signifie l'expression « to jump on the bandwagon » ?", a: 'Suivre le mouvement', x: ['Sauter de joie', "Changer d'avis", 'Partir en voyage'] },
    { id: 'angl-p18', d: 4, t: 'Que signifie le mot « leaf » ?', a: 'Feuille', x: ['Branche', 'Racine', 'Fleur'] },
    { id: 'angl-p19', d: 4, t: "Que signifie l'expression « to burn the midnight oil » ?", a: 'Travailler tard dans la nuit', x: ["Gaspiller de l'argent", 'Se disputer', 'Faire la fête'] },
    { id: 'angl-p20', d: 4, t: 'Comment dit-on « escargot » en anglais ?', a: 'Snail', x: ['Slug', 'Worm', 'Snake'] },
  ]),
];
