import type { Question } from '../../../core/models';

// Les questions « drapeau » utilisent flagcdn.com (PNG, fiable). Elles
// nécessitent une connexion ; hors-ligne, l'image ne s'affiche pas.
const flag = (code: string): { type: 'image'; uri: string } => ({
  type: 'image',
  uri: `https://flagcdn.com/w320/${code}.png`,
});

export const cultureQuestions: Question[] = [
  {
    id: 'culture-1',
    theme: 'culture',
    difficulty: 1,
    text: 'Quelle est la capitale de la France ?',
    answer: 'Paris',
    distractors: ['Lyon', 'Marseille', 'Bordeaux'],
  },
  {
    id: 'culture-2',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de continents compte-t-on sur Terre ?',
    answer: '7',
    acceptable: ['sept'],
    distractors: ['5', '6', '8'],
  },
  {
    id: 'culture-3',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la planète la plus proche du Soleil ?',
    answer: 'Mercure',
    distractors: ['Vénus', 'Mars', 'La Terre'],
  },
  {
    id: 'culture-4',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel élément chimique a pour symbole « O » ?',
    answer: 'Oxygène',
    distractors: ['Or', 'Osmium', 'Hydrogène'],
  },
  {
    id: 'culture-5',
    theme: 'culture',
    difficulty: 3,
    text: 'En quelle année est tombé le mur de Berlin ?',
    answer: '1989',
    distractors: ['1991', '1987', '1985'],
  },
  {
    id: 'culture-6',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de côtés possède un hexagone ?',
    answer: '6',
    acceptable: ['six'],
    distractors: ['5', '7', '8'],
  },
  {
    id: 'culture-7',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand océan du monde ?',
    answer: "L'océan Pacifique",
    acceptable: ['pacifique'],
    distractors: ['Atlantique', 'Indien', 'Arctique'],
  },
  {
    id: 'culture-8',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a peint La Joconde ?',
    answer: 'Léonard de Vinci',
    acceptable: ['de vinci', 'vinci', 'leonard de vinci'],
    distractors: ['Michel-Ange', 'Raphaël', 'Botticelli'],
  },
  {
    id: 'culture-9',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel est le plus petit État indépendant du monde ?',
    answer: 'Le Vatican',
    acceptable: ['vatican'],
    distractors: ['Monaco', 'Saint-Marin', 'Nauru'],
  },
  {
    id: 'culture-10',
    theme: 'culture',
    difficulty: 1,
    text: 'Quel pays a la forme d\'une botte ?',
    answer: "L'Italie",
    acceptable: ['italie'],
    distractors: ["L'Espagne", 'La Grèce', 'Le Portugal'],
  },
  {
    id: 'culture-11',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel est le plus grand organe du corps humain ?',
    answer: 'La peau',
    acceptable: ['peau'],
    distractors: ['Le foie', 'Les poumons', "L'intestin"],
  },
  {
    id: 'culture-12',
    theme: 'culture',
    difficulty: 3,
    text: 'Quelle est approximativement la vitesse de la lumière ?',
    answer: '300 000 km/s',
    acceptable: ['300000', '300 000'],
    distractors: ['150 000 km/s', '1 000 000 km/s', '30 000 km/s'],
  },
  {
    id: 'culture-13',
    theme: 'culture',
    difficulty: 1,
    text: 'Combien de joueurs composent une équipe de football sur le terrain ?',
    answer: '11',
    distractors: ['10', '12', '9'],
  },
  {
    id: 'culture-14',
    theme: 'culture',
    difficulty: 4,
    text: 'En quelle année a eu lieu la prise de la Bastille ?',
    answer: '1789',
    distractors: ['1799', '1769', '1804'],
  },
  {
    id: 'culture-15',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la plus haute montagne du monde ?',
    answer: "L'Everest",
    acceptable: ['everest', 'mont everest'],
    distractors: ['Le K2', 'Le Mont Blanc', 'Le Kilimandjaro'],
  },
  {
    id: 'culture-16',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a développé la théorie de la relativité ?',
    answer: 'Albert Einstein',
    acceptable: ['einstein'],
    distractors: ['Isaac Newton', 'Niels Bohr', 'Galilée'],
  },
  {
    id: 'culture-17',
    theme: 'culture',
    difficulty: 3,
    text: "Quel est le symbole chimique de l'or ?",
    answer: 'Au',
    distractors: ['Or', 'Ag', 'Gd'],
  },
  {
    id: 'culture-18',
    theme: 'culture',
    difficulty: 4,
    text: 'Combien d\'os compte le squelette humain adulte ?',
    answer: '206',
    distractors: ['256', '198', '212'],
  },
  {
    id: 'culture-19',
    theme: 'culture',
    difficulty: 1,
    text: 'Quelle planète est surnommée la planète rouge ?',
    answer: 'Mars',
    distractors: ['Vénus', 'Jupiter', 'Saturne'],
  },
  {
    id: 'culture-20',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a écrit la pièce « Roméo et Juliette » ?',
    answer: 'William Shakespeare',
    acceptable: ['shakespeare'],
    distractors: ['Molière', 'Victor Hugo', 'Voltaire'],
  },

  // ----- Questions « devine le drapeau » (image) -----
  {
    id: 'culture-flag-jp',
    theme: 'culture',
    difficulty: 1,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Japon',
    acceptable: ['le japon'],
    distractors: ['Chine', 'Corée du Sud', 'Bangladesh'],
    media: flag('jp'),
  },
  {
    id: 'culture-flag-br',
    theme: 'culture',
    difficulty: 2,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Brésil',
    acceptable: ['le brésil', 'bresil'],
    distractors: ['Argentine', 'Portugal', 'Cameroun'],
    media: flag('br'),
  },
  {
    id: 'culture-flag-ca',
    theme: 'culture',
    difficulty: 1,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Canada',
    acceptable: ['le canada'],
    distractors: ['États-Unis', 'Royaume-Uni', 'Suisse'],
    media: flag('ca'),
  },
  {
    id: 'culture-flag-kr',
    theme: 'culture',
    difficulty: 3,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Corée du Sud',
    acceptable: ['coree du sud', 'corée'],
    distractors: ['Japon', 'Chine', 'Mongolie'],
    media: flag('kr'),
  },
  {
    id: 'culture-flag-in',
    theme: 'culture',
    difficulty: 3,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Inde',
    acceptable: ["l'inde"],
    distractors: ['Niger', 'Irlande', "Côte d'Ivoire"],
    media: flag('in'),
  },
  {
    id: 'culture-flag-au',
    theme: 'culture',
    difficulty: 3,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Australie',
    acceptable: ["l'australie"],
    distractors: ['Nouvelle-Zélande', 'Royaume-Uni', 'Fidji'],
    media: flag('au'),
  },
  {
    id: 'culture-flag-ro',
    theme: 'culture',
    difficulty: 4,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Roumanie',
    acceptable: ['la roumanie'],
    distractors: ['Tchad', 'Andorre', 'Moldavie'],
    media: flag('ro'),
    hints: ['Très proche du drapeau du Tchad…'],
  },
  {
    id: 'culture-flag-gr',
    theme: 'culture',
    difficulty: 4,
    text: 'À quel pays appartient ce drapeau ?',
    answer: 'Grèce',
    acceptable: ['la grèce', 'grece'],
    distractors: ['Israël', 'Uruguay', 'Finlande'],
    media: flag('gr'),
  },

  // ----- Culture générale (suite) -----
  {
    id: 'culture-21',
    theme: 'culture',
    difficulty: 2,
    text: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?',
    answer: 'Le dioxyde de carbone (CO2)',
    acceptable: ['co2', 'dioxyde de carbone', 'gaz carbonique'],
    distractors: ["L'oxygène", "L'azote", "L'hydrogène"],
  },
  {
    id: 'culture-22',
    theme: 'culture',
    difficulty: 3,
    text: 'Combien de cœurs possède une pieuvre ?',
    answer: '3',
    acceptable: ['trois'],
    distractors: ['1', '2', '5'],
  },
  {
    id: 'culture-23',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la monnaie du Japon ?',
    answer: 'Le yen',
    acceptable: ['yen'],
    distractors: ['Le won', 'Le yuan', 'Le baht'],
  },
  {
    id: 'culture-24',
    theme: 'culture',
    difficulty: 4,
    text: "En quelle année l'Homme a-t-il marché sur la Lune pour la première fois ?",
    answer: '1969',
    distractors: ['1972', '1965', '1959'],
  },
  {
    id: 'culture-25',
    theme: 'culture',
    difficulty: 2,
    text: 'Quelle est la plus grande planète du système solaire ?',
    answer: 'Jupiter',
    distractors: ['Saturne', 'Neptune', 'La Terre'],
  },
  {
    id: 'culture-26',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel métal est liquide à température ambiante ?',
    answer: 'Le mercure',
    acceptable: ['mercure'],
    distractors: ['Le plomb', "L'étain", 'Le zinc'],
  },
  {
    id: 'culture-27',
    theme: 'culture',
    difficulty: 2,
    text: 'Qui a écrit « Les Misérables » ?',
    answer: 'Victor Hugo',
    acceptable: ['hugo'],
    distractors: ['Émile Zola', 'Gustave Flaubert', 'Honoré de Balzac'],
  },
  {
    id: 'culture-28',
    theme: 'culture',
    difficulty: 3,
    text: 'Quelle langue compte le plus de locuteurs natifs au monde ?',
    answer: 'Le chinois (mandarin)',
    acceptable: ['chinois', 'mandarin'],
    distractors: ["L'anglais", "L'espagnol", "L'hindi"],
  },
  {
    id: 'culture-29',
    theme: 'culture',
    difficulty: 3,
    text: 'Quel scientifique a énoncé les trois lois du mouvement ?',
    answer: 'Isaac Newton',
    acceptable: ['newton'],
    distractors: ['Galilée', 'Albert Einstein', 'Johannes Kepler'],
  },
  {
    id: 'culture-30',
    theme: 'culture',
    difficulty: 4,
    text: 'En quelle année a commencé la Première Guerre mondiale ?',
    answer: '1914',
    distractors: ['1918', '1912', '1939'],
  },
];
