import type { Question } from '../../../core/models';

// Énigmes : se jouent très bien en mode « réponse libre » (on dit la réponse à
// voix haute, l'animateur valide), mais marchent aussi en QCM.
export const enigmesQuestions: Question[] = [
  {
    id: 'enig-1',
    theme: 'enigmes',
    difficulty: 2,
    text: "Je peux voler sans ailes et pleurer sans yeux. Partout où je vais, l'obscurité me suit. Qui suis-je ?",
    answer: 'Le nuage',
    acceptable: ['nuage', 'les nuages'],
    distractors: ['Le vent', "L'ombre", 'La fumée'],
    hints: ['Je flotte dans le ciel.'],
  },
  {
    id: 'enig-2',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Plus on en enlève, plus il devient grand. Quʼest-ce que cʼest ?',
    answer: 'Un trou',
    acceptable: ['trou', 'le trou'],
    distractors: ['Un tas', 'Une montagne', 'Un puits'],
  },
  {
    id: 'enig-3',
    theme: 'enigmes',
    difficulty: 3,
    text: "Jʼai des villes mais pas de maisons, des forêts mais pas dʼarbres, et de lʼeau mais pas de poissons. Qui suis-je ?",
    answer: 'Une carte',
    acceptable: ['carte', 'une carte géographique', 'la carte'],
    distractors: ['Un rêve', 'Un livre', 'Un globe'],
  },
  {
    id: 'enig-4',
    theme: 'enigmes',
    difficulty: 2,
    text: "Je parle sans bouche et jʼentends sans oreilles. Je nʼai pas de corps mais je prends vie avec le vent. Qui suis-je ?",
    answer: "L'écho",
    acceptable: ['echo', 'un écho'],
    distractors: ['Le fantôme', 'La radio', 'La pensée'],
  },
  {
    id: 'enig-5',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Quʼest-ce qui devient de plus en plus mouillé au fur et à mesure quʼil sèche ?',
    answer: 'La serviette',
    acceptable: ['serviette', 'une serviette', 'la serviette de bain'],
    distractors: ['Le savon', "L'éponge", 'Le soleil'],
  },
  {
    id: 'enig-6',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Le matin il marche sur 4 pattes, le midi sur 2, le soir sur 3. Qui est-ce ?',
    answer: "L'être humain",
    acceptable: ['homme', "l'homme", 'humain', 'être humain'],
    distractors: ['Le temps', 'Le chien', 'Le soleil'],
    hints: ['Cʼest la célèbre énigme du Sphinx.'],
  },
  {
    id: 'enig-7',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Jʼai des dents mais je ne mords pas. Qui suis-je ?',
    answer: 'Le peigne',
    acceptable: ['peigne', 'un peigne', 'la fermeture éclair'],
    distractors: ['La scie', 'Le requin', 'La fourchette'],
  },
  {
    id: 'enig-8',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Quʼest-ce qui monte mais ne redescend jamais ?',
    answer: "L'âge",
    acceptable: ['age', "l'âge", 'votre âge'],
    distractors: ['La fumée', 'Le ballon', 'La température'],
  },
  {
    id: 'enig-9',
    theme: 'enigmes',
    difficulty: 2,
    text: 'On me casse toujours avant de mʼutiliser. Qui suis-je ?',
    answer: "L'œuf",
    acceptable: ['oeuf', 'un œuf', "l'œuf"],
    distractors: ['Le verre', 'La promesse', 'La glace'],
  },
  {
    id: 'enig-10',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Quʼest-ce qui est à toi mais que les autres utilisent bien plus que toi ?',
    answer: 'Ton prénom',
    acceptable: ['prenom', 'ton prénom', 'mon nom', 'le nom', 'ton nom'],
    distractors: ['Ton ombre', 'Ton argent', 'Ton téléphone'],
  },
  {
    id: 'enig-11',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Plus il y en a, moins on voit. Quʼest-ce que cʼest ?',
    answer: "L'obscurité",
    acceptable: ['obscurite', 'le noir', 'les ténèbres'],
    distractors: ['Le brouillard', 'La foule', 'La lumière'],
  },
  {
    id: 'enig-12',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Jʼai un cou mais pas de tête. Qui suis-je ?',
    answer: 'La bouteille',
    acceptable: ['bouteille', 'une bouteille', 'la chemise'],
    distractors: ['La girafe', 'La guitare', 'Le vase'],
  },
  {
    id: 'enig-13',
    theme: 'enigmes',
    difficulty: 3,
    text: 'On me prend avant de me donner. Qui suis-je ?',
    answer: 'La photo',
    acceptable: ['photo', 'une photo', 'un cliché'],
    distractors: ['Le cadeau', 'Le train', 'Le médicament'],
    hints: ['« Prendre » une ___.'],
  },
  {
    id: 'enig-14',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Deux pères et deux fils vont à la pêche et attrapent 3 poissons, un chacun. Comment est-ce possible ?',
    answer: 'Ils sont 3 : grand-père, père et fils',
    acceptable: ['grand-père père fils', '3 personnes', 'ils sont 3', 'trois personnes'],
    distractors: ['Ils en relâchent un', 'Un poisson coupé en deux', 'Ils trichent'],
    hints: ['Le père est aussi le fils de quelquʼun.'],
  },
  {
    id: 'enig-15',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Je suis présent une fois dans une minute, deux fois dans un moment, mais jamais dans cent ans. Qui suis-je ?',
    answer: 'La lettre M',
    acceptable: ['m', 'la lettre m', 'lettre m'],
    distractors: ['La lettre N', 'Le temps', "L'instant"],
  },
  {
    id: 'enig-16',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Quʼest-ce qui te suit partout en pleine journée et disparaît la nuit ?',
    answer: "L'ombre",
    acceptable: ['ombre', 'ton ombre'],
    distractors: ['Le soleil', 'Le vent', 'Le reflet'],
  },
];
