import type { Question } from '../../../core/models';

// Énigmes : se jouent très bien en mode « réponse libre » (on dit la réponse à
// voix haute, l'animateur valide), mais marchent aussi en QCM.
export const enigmesQuestions: Question[] = [
  {
    id: 'enig-1',
    theme: 'enigmes',
    difficulty: 2,
    text: "Je peux voler sans ailes et pleurer sans yeux. Partout où je vais, l'obscurité me suit. Qui suis-je ?",
    answer: 'Le nuage',
    acceptable: ['nuage', 'les nuages'],
    distractors: ['Le vent', "L'ombre", 'La fumée'],
    hints: ['Je flotte dans le ciel.'],
  },
  {
    id: 'enig-2',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Plus on en enlève, plus il devient grand. Quʼest-ce que cʼest ?',
    answer: 'Un trou',
    acceptable: ['trou', 'le trou'],
    distractors: ['Un tas', 'Une montagne', 'Un puits'],
  },
  {
    id: 'enig-3',
    theme: 'enigmes',
    difficulty: 3,
    text: "Jʼai des villes mais pas de maisons, des forêts mais pas dʼarbres, et de lʼeau mais pas de poissons. Qui suis-je ?",
    answer: 'Une carte',
    acceptable: ['carte', 'une carte géographique', 'la carte'],
    distractors: ['Un rêve', 'Un livre', 'Un globe'],
  },
  {
    id: 'enig-4',
    theme: 'enigmes',
    difficulty: 2,
    text: "Je parle sans bouche et jʼentends sans oreilles. Je nʼai pas de corps mais je prends vie avec le vent. Qui suis-je ?",
    answer: "L'écho",
    acceptable: ['echo', 'un écho'],
    distractors: ['Le fantôme', 'La radio', 'La pensée'],
  },
  {
    id: 'enig-5',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Quʼest-ce qui devient de plus en plus mouillé au fur et à mesure quʼil sèche ?',
    answer: 'La serviette',
    acceptable: ['serviette', 'une serviette', 'la serviette de bain'],
    distractors: ['Le savon', "L'éponge", 'Le soleil'],
  },
  {
    id: 'enig-6',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Le matin il marche sur 4 pattes, le midi sur 2, le soir sur 3. Qui est-ce ?',
    answer: "L'être humain",
    acceptable: ['homme', "l'homme", 'humain', 'être humain'],
    distractors: ['Le temps', 'Le chien', 'Le soleil'],
    hints: ['Cʼest la célèbre énigme du Sphinx.'],
  },
  {
    id: 'enig-7',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Jʼai des dents mais je ne mords pas. Qui suis-je ?',
    answer: 'Le peigne',
    acceptable: ['peigne', 'un peigne', 'la fermeture éclair'],
    distractors: ['La scie', 'Le requin', 'La fourchette'],
  },
  {
    id: 'enig-8',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Quʼest-ce qui monte mais ne redescend jamais ?',
    answer: "L'âge",
    acceptable: ['age', "l'âge", 'votre âge'],
    distractors: ['La fumée', 'Le ballon', 'La température'],
  },
  {
    id: 'enig-9',
    theme: 'enigmes',
    difficulty: 2,
    text: 'On me casse toujours avant de mʼutiliser. Qui suis-je ?',
    answer: "L'œuf",
    acceptable: ['oeuf', 'un œuf', "l'œuf"],
    distractors: ['Le verre', 'La promesse', 'La glace'],
  },
  {
    id: 'enig-10',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Quʼest-ce qui est à toi mais que les autres utilisent bien plus que toi ?',
    answer: 'Ton prénom',
    acceptable: ['prenom', 'ton prénom', 'mon nom', 'le nom', 'ton nom'],
    distractors: ['Ton ombre', 'Ton argent', 'Ton téléphone'],
  },
  {
    id: 'enig-11',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Plus il y en a, moins on voit. Quʼest-ce que cʼest ?',
    answer: "L'obscurité",
    acceptable: ['obscurite', 'le noir', 'les ténèbres'],
    distractors: ['Le brouillard', 'La foule', 'La lumière'],
  },
  {
    id: 'enig-12',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Jʼai un cou mais pas de tête. Qui suis-je ?',
    answer: 'La bouteille',
    acceptable: ['bouteille', 'une bouteille', 'la chemise'],
    distractors: ['La girafe', 'La guitare', 'Le vase'],
  },
  {
    id: 'enig-13',
    theme: 'enigmes',
    difficulty: 3,
    text: 'On me prend avant de me donner. Qui suis-je ?',
    answer: 'La photo',
    acceptable: ['photo', 'une photo', 'un cliché'],
    distractors: ['Le cadeau', 'Le train', 'Le médicament'],
    hints: ['« Prendre » une ___.'],
  },
  {
    id: 'enig-14',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Deux pères et deux fils vont à la pêche et attrapent 3 poissons, un chacun. Comment est-ce possible ?',
    answer: 'Ils sont 3 : grand-père, père et fils',
    acceptable: ['grand-père père fils', '3 personnes', 'ils sont 3', 'trois personnes'],
    distractors: ['Ils en relâchent un', 'Un poisson coupé en deux', 'Ils trichent'],
    hints: ['Le père est aussi le fils de quelquʼun.'],
  },
  {
    id: 'enig-15',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Je suis présent une fois dans une minute, deux fois dans un moment, mais jamais dans cent ans. Qui suis-je ?',
    answer: 'La lettre M',
    acceptable: ['m', 'la lettre m', 'lettre m'],
    distractors: ['La lettre N', 'Le temps', "L'instant"],
  },
  {
    id: 'enig-16',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Quʼest-ce qui te suit partout en pleine journée et disparaît la nuit ?',
    answer: "L'ombre",
    acceptable: ['ombre', 'ton ombre'],
    distractors: ['Le soleil', 'Le vent', 'Le reflet'],
  },
  {
    id: 'enig-17',
    theme: 'enigmes',
    difficulty: 3,
    text: "J'ai une tête et une queue mais pas de corps. Qui suis-je ?",
    answer: 'Une pièce de monnaie',
    acceptable: ['pièce', 'une pièce', 'pièce de monnaie', 'piece'],
    distractors: ['Un serpent', 'Une comète', 'Une allumette'],
  },
  {
    id: 'enig-18',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Je suis toujours devant toi mais tu ne peux jamais me voir. Qui suis-je ?',
    answer: 'Le futur',
    acceptable: ['futur', "l'avenir", 'avenir'],
    distractors: ['Le vent', "L'horizon", 'Ton nez'],
  },
  {
    id: 'enig-19',
    theme: 'enigmes',
    difficulty: 4,
    text: "Un homme regarde un portrait : « Je n'ai ni frère ni sœur, mais le père de cet homme est le fils de mon père. » Qui est sur le portrait ?",
    answer: 'Son fils',
    acceptable: ['son fils', 'le fils'],
    distractors: ['Lui-même', 'Son père', 'Son neveu'],
  },
  {
    id: 'enig-20',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Plus tu en prends, plus tu en laisses derrière toi. Que sont-ils ?',
    answer: 'Des pas (empreintes)',
    acceptable: ['des pas', 'pas', 'empreintes', 'les pas'],
    distractors: ['Du temps', 'Des cheveux', 'Des miettes'],
  },
  {
    id: 'enig-21',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Quelle est la chose que tu brises rien quʼen prononçant son nom ?',
    answer: 'Le silence',
    acceptable: ['silence', 'le silence'],
    distractors: ['Le verre', 'La glace', 'Un record'],
  },
  {
    id: 'enig-22',
    theme: 'enigmes',
    difficulty: 4,
    text: "Je n'ai pas de vie mais je peux mourir ; je n'ai pas de poumons mais l'eau me tue. Qui suis-je ?",
    answer: 'Le feu',
    acceptable: ['feu', 'le feu'],
    distractors: ['La bougie', 'La plante', 'La pile'],
  },
  {
    id: 'enig-23',
    theme: 'enigmes',
    difficulty: 3,
    text: "Léger comme une plume, mais l'homme le plus fort ne peut me retenir plus de quelques minutes. Qui suis-je ?",
    answer: 'Le souffle (la respiration)',
    acceptable: ['le souffle', 'souffle', 'la respiration', 'sa respiration'],
    distractors: ['Une plume', 'La fumée', 'Une bulle'],
  },
  {
    id: 'enig-24',
    theme: 'enigmes',
    difficulty: 2,
    text: "J'ai des aiguilles mais je ne pique pas. Qui suis-je ?",
    answer: "L'horloge",
    acceptable: ['horloge', 'la montre', 'montre', 'une pendule', 'pendule'],
    distractors: ['Le sapin', 'La boussole', 'La seringue'],
  },
];
