import type { Question } from '../../../core/models';

// Énigmes : se jouent très bien en mode « réponse libre » (on dit la réponse à
// voix haute, l'animateur valide), mais marchent aussi en QCM.
export const enigmesQuestions: Question[] = [
  {
    id: 'enig-1',
    theme: 'enigmes',
    difficulty: 2,
    text: "Je peux voler sans ailes et pleurer sans yeux. Partout où je vais, l'obscurité me suit. Qui suis-je ?",
    answer: 'Le nuage',
    acceptable: ['nuage', 'les nuages'],
    distractors: ['Le vent', "L'ombre", 'La fumée'],
    hints: ['Je flotte dans le ciel.'],
  },
  {
    id: 'enig-2',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Plus on en enlève, plus il devient grand. Quʼest-ce que cʼest ?',
    answer: 'Un trou',
    acceptable: ['trou', 'le trou'],
    distractors: ['Un tas', 'Une montagne', 'Un puits'],
  },
  {
    id: 'enig-3',
    theme: 'enigmes',
    difficulty: 3,
    text: "Jʼai des villes mais pas de maisons, des forêts mais pas dʼarbres, et de lʼeau mais pas de poissons. Qui suis-je ?",
    answer: 'Une carte',
    acceptable: ['carte', 'une carte géographique', 'la carte'],
    distractors: ['Un rêve', 'Un livre', 'Un globe'],
  },
  {
    id: 'enig-4',
    theme: 'enigmes',
    difficulty: 2,
    text: "Je parle sans bouche et jʼentends sans oreilles. Je nʼai pas de corps mais je prends vie avec le vent. Qui suis-je ?",
    answer: "L'écho",
    acceptable: ['echo', 'un écho'],
    distractors: ['Le fantôme', 'La radio', 'La pensée'],
  },
  {
    id: 'enig-5',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Quʼest-ce qui devient de plus en plus mouillé au fur et à mesure quʼil sèche ?',
    answer: 'La serviette',
    acceptable: ['serviette', 'une serviette', 'la serviette de bain'],
    distractors: ['Le savon', "L'éponge", 'Le soleil'],
  },
  {
    id: 'enig-6',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Le matin il marche sur 4 pattes, le midi sur 2, le soir sur 3. Qui est-ce ?',
    answer: "L'être humain",
    acceptable: ['homme', "l'homme", 'humain', 'être humain'],
    distractors: ['Le temps', 'Le chien', 'Le soleil'],
    hints: ['Cʼest la célèbre énigme du Sphinx.'],
  },
  {
    id: 'enig-7',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Jʼai des dents mais je ne mords pas. Qui suis-je ?',
    answer: 'Le peigne',
    acceptable: ['peigne', 'un peigne', 'la fermeture éclair'],
    distractors: ['La scie', 'Le requin', 'La fourchette'],
  },
  {
    id: 'enig-8',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Quʼest-ce qui monte mais ne redescend jamais ?',
    answer: "L'âge",
    acceptable: ['age', "l'âge", 'votre âge'],
    distractors: ['La fumée', 'Le ballon', 'La température'],
  },
  {
    id: 'enig-9',
    theme: 'enigmes',
    difficulty: 2,
    text: 'On me casse toujours avant de mʼutiliser. Qui suis-je ?',
    answer: "L'œuf",
    acceptable: ['oeuf', 'un œuf', "l'œuf"],
    distractors: ['Le verre', 'La promesse', 'La glace'],
  },
  {
    id: 'enig-10',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Quʼest-ce qui est à toi mais que les autres utilisent bien plus que toi ?',
    answer: 'Ton prénom',
    acceptable: ['prenom', 'ton prénom', 'mon nom', 'le nom', 'ton nom'],
    distractors: ['Ton ombre', 'Ton argent', 'Ton téléphone'],
  },
  {
    id: 'enig-11',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Plus il y en a, moins on voit. Quʼest-ce que cʼest ?',
    answer: "L'obscurité",
    acceptable: ['obscurite', 'le noir', 'les ténèbres'],
    distractors: ['Le brouillard', 'La foule', 'La lumière'],
  },
  {
    id: 'enig-12',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Jʼai un cou mais pas de tête. Qui suis-je ?',
    answer: 'La bouteille',
    acceptable: ['bouteille', 'une bouteille', 'la chemise'],
    distractors: ['La girafe', 'La guitare', 'Le vase'],
  },
  {
    id: 'enig-13',
    theme: 'enigmes',
    difficulty: 3,
    text: 'On me prend avant de me donner. Qui suis-je ?',
    answer: 'La photo',
    acceptable: ['photo', 'une photo', 'un cliché'],
    distractors: ['Le cadeau', 'Le train', 'Le médicament'],
    hints: ['« Prendre » une ___.'],
  },
  {
    id: 'enig-14',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Deux pères et deux fils vont à la pêche et attrapent 3 poissons, un chacun. Comment est-ce possible ?',
    answer: 'Ils sont 3 : grand-père, père et fils',
    acceptable: ['grand-père père fils', '3 personnes', 'ils sont 3', 'trois personnes'],
    distractors: ['Ils en relâchent un', 'Un poisson coupé en deux', 'Ils trichent'],
    hints: ['Le père est aussi le fils de quelquʼun.'],
  },
  {
    id: 'enig-15',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Je suis présent une fois dans une minute, deux fois dans un moment, mais jamais dans cent ans. Qui suis-je ?',
    answer: 'La lettre M',
    acceptable: ['m', 'la lettre m', 'lettre m'],
    distractors: ['La lettre N', 'Le temps', "L'instant"],
  },
  {
    id: 'enig-16',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Quʼest-ce qui te suit partout en pleine journée et disparaît la nuit ?',
    answer: "L'ombre",
    acceptable: ['ombre', 'ton ombre'],
    distractors: ['Le soleil', 'Le vent', 'Le reflet'],
  },
  {
    id: 'enig-17',
    theme: 'enigmes',
    difficulty: 3,
    text: "J'ai une tête et une queue mais pas de corps. Qui suis-je ?",
    answer: 'Une pièce de monnaie',
    acceptable: ['pièce', 'une pièce', 'pièce de monnaie', 'piece'],
    distractors: ['Un serpent', 'Une comète', 'Une allumette'],
  },
  {
    id: 'enig-18',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Je suis toujours devant toi mais tu ne peux jamais me voir. Qui suis-je ?',
    answer: 'Le futur',
    acceptable: ['futur', "l'avenir", 'avenir'],
    distractors: ['Le vent', "L'horizon", 'Ton nez'],
  },
  {
    id: 'enig-19',
    theme: 'enigmes',
    difficulty: 4,
    text: "Un homme regarde un portrait : « Je n'ai ni frère ni sœur, mais le père de cet homme est le fils de mon père. » Qui est sur le portrait ?",
    answer: 'Son fils',
    acceptable: ['son fils', 'le fils'],
    distractors: ['Lui-même', 'Son père', 'Son neveu'],
  },
  {
    id: 'enig-20',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Plus tu en prends, plus tu en laisses derrière toi. Que sont-ils ?',
    answer: 'Des pas',
    acceptable: ['des pas', 'pas', 'empreintes', 'les pas'],
    distractors: ['Du temps', 'Des cheveux', 'Des miettes'],
  },
  {
    id: 'enig-21',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Quelle est la chose que tu brises rien quʼen prononçant son nom ?',
    answer: 'Le silence',
    acceptable: ['silence', 'le silence'],
    distractors: ['Le verre', 'La glace', 'Un record'],
  },
  {
    id: 'enig-22',
    theme: 'enigmes',
    difficulty: 4,
    text: "Je n'ai pas de vie mais je peux mourir ; je n'ai pas de poumons mais l'eau me tue. Qui suis-je ?",
    answer: 'Le feu',
    acceptable: ['feu', 'le feu'],
    distractors: ['La bougie', 'La plante', 'La pile'],
  },
  {
    id: 'enig-23',
    theme: 'enigmes',
    difficulty: 3,
    text: "Léger comme une plume, mais l'homme le plus fort ne peut me retenir plus de quelques minutes. Qui suis-je ?",
    answer: 'Le souffle',
    acceptable: ['le souffle', 'souffle', 'la respiration', 'sa respiration'],
    distractors: ['Une plume', 'La fumée', 'Une bulle'],
  },
  {
    id: 'enig-24',
    theme: 'enigmes',
    difficulty: 2,
    text: "J'ai des aiguilles mais je ne pique pas. Qui suis-je ?",
    answer: "L'horloge",
    acceptable: ['horloge', 'la montre', 'montre', 'une pendule', 'pendule'],
    distractors: ['Le sapin', 'La boussole', 'La seringue'],
  },
  {
    id: 'enig-25',
    theme: 'enigmes',
    difficulty: 2,
    text: "J'ai une langue mais je ne parle jamais. Qui suis-je ?",
    answer: 'La chaussure',
    acceptable: ['chaussure', 'la chaussure', 'une chaussure'],
    distractors: ['Le serpent', 'La cloche', 'Le livre'],
  },
  {
    id: 'enig-26',
    theme: 'enigmes',
    difficulty: 3,
    text: "J'ai un lit mais je ne dors jamais, et une bouche mais je ne mange jamais. Qui suis-je ?",
    answer: 'La rivière',
    acceptable: ['riviere', 'la rivière', 'le fleuve', 'fleuve'],
    distractors: ['Le lac', 'La mer', 'La montagne'],
  },
  {
    id: 'enig-27',
    theme: 'enigmes',
    difficulty: 2,
    text: "J'ai un œil mais je ne vois rien. Qui suis-je ?",
    answer: "L'aiguille",
    acceptable: ['aiguille', 'une aiguille', "l'aiguille"],
    distractors: ['La caméra', 'Le cyclope', 'Le télescope'],
  },
  {
    id: 'enig-28',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Je voyage à travers le monde tout en restant sagement dans un coin. Qui suis-je ?',
    answer: 'Le timbre',
    acceptable: ['timbre', 'le timbre', 'un timbre'],
    distractors: ['La lettre', 'Le satellite', "L'avion"],
  },
  {
    id: 'enig-29',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Plus on me remplit, plus je deviens léger. Qui suis-je ?',
    answer: 'Le ballon',
    acceptable: ['ballon', 'le ballon', 'la montgolfière', 'montgolfiere'],
    distractors: ['Le verre', 'Le sac', "L'éponge"],
  },
  {
    id: 'enig-30',
    theme: 'enigmes',
    difficulty: 3,
    text: "Je commence par un « e », je ne contiens qu'une seule lettre, et pourtant je ne suis pas la lettre « e ». Qui suis-je ?",
    answer: 'Une enveloppe',
    acceptable: ['enveloppe', 'une enveloppe', "l'enveloppe"],
    distractors: ['Un escargot', 'Un écran', 'Un éclair'],
  },
  {
    id: 'enig-31',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Un fermier a 17 moutons. Tous meurent sauf 9. Combien lui en reste-t-il ?',
    answer: '9',
    acceptable: ['9', 'neuf', '9 moutons'],
    distractors: ['8', '17', '0'],
    hints: ['Relis bien : « tous sauf 9 ».'],
  },
  {
    id: 'enig-32',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Je suis blanc quand je suis sale et noir quand je suis propre. Qui suis-je ?',
    answer: 'Le tableau',
    acceptable: ['tableau', 'le tableau', 'tableau noir', 'ardoise', "l'ardoise"],
    distractors: ['Le linge', 'La craie', 'Le charbon'],
  },
  {
    id: 'enig-33',
    theme: 'enigmes',
    difficulty: 3,
    text: "J'ai un pied mais pas de jambe. Qui suis-je ?",
    answer: 'Le champignon',
    acceptable: ['champignon', 'un champignon', 'le champignon'],
    distractors: ['Le lit', 'La table', 'La chaussette'],
  },
  {
    id: 'enig-34',
    theme: 'enigmes',
    difficulty: 2,
    text: "J'ai des feuilles mais je ne suis pas un arbre. Qui suis-je ?",
    answer: 'Le livre',
    acceptable: ['livre', 'le livre', 'un livre', 'le cahier'],
    distractors: ['La fleur', 'La table', 'La lampe'],
  },
  {
    id: 'enig-35',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Je cours sans jambes et je murmure sans bouche. Qui suis-je ?',
    answer: 'Le vent',
    acceptable: ['vent', 'le vent'],
    distractors: ['La rivière', 'Le fantôme', 'La radio'],
  },
  {
    id: 'enig-36',
    theme: 'enigmes',
    difficulty: 4,
    text: "J'ai des touches mais pas de serrure, de l'espace mais pas de pièce. On peut entrer mais pas sortir. Qui suis-je ?",
    answer: 'Le clavier',
    acceptable: ['clavier', 'le clavier', 'un clavier'],
    distractors: ['La maison', 'Le piano', 'La voiture'],
    hints: ['Pense à une « touche entrée » et une « barre espace ».'],
  },
  {
    id: 'enig-37',
    theme: 'enigmes',
    difficulty: 3,
    text: "J'ai un pouce et quatre doigts, mais je ne suis pas vivant. Qui suis-je ?",
    answer: 'Le gant',
    acceptable: ['gant', 'le gant', 'un gant', 'la moufle'],
    distractors: ['La main', 'Le râteau', 'La fourchette'],
  },
  {
    id: 'enig-38',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Qu\'est-ce qui monte quand la pluie descend ?',
    answer: 'Le parapluie',
    acceptable: ['parapluie', 'le parapluie', 'un parapluie'],
    distractors: ["Le niveau de l'eau", 'Le baromètre', 'La température'],
  },
  {
    id: 'enig-39',
    theme: 'enigmes',
    difficulty: 3,
    text: 'On me perd dès l\'instant où on me partage. Qui suis-je ?',
    answer: 'Le secret',
    acceptable: ['secret', 'un secret', 'le secret'],
    distractors: ["L'argent", 'Le temps', 'La clé'],
  },
  {
    id: 'enig-40',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Je suis plein de trous mais je retiens pourtant l\'eau. Qui suis-je ?',
    answer: "L'éponge",
    acceptable: ['eponge', "l'éponge", 'une éponge'],
    distractors: ['Le filet', 'La passoire', 'Le seau'],
  },
  {
    id: 'enig-41',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Je cours tout autour de la maison sans jamais bouger d\'un pas. Qui suis-je ?',
    answer: 'Le mur',
    acceptable: ['mur', 'le mur', 'les murs', 'cloture', 'clôture', 'la clôture'],
    distractors: ['Le chien', 'Le vent', 'Le toit'],
  },
  {
    id: 'enig-42',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Un coq pond un œuf au sommet d\'un toit parfaitement pointu. De quel côté l\'œuf roule-t-il ?',
    answer: "Aucun : un coq ne pond pas d'œufs",
    acceptable: ['aucun', 'le coq ne pond pas', 'il ne pond pas', 'aucun cote'],
    distractors: ['À gauche', 'À droite', 'Des deux côtés'],
  },
  {
    id: 'enig-43',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Je grandis vers le bas au lieu de grandir vers le haut. Qui suis-je ?',
    answer: 'La stalactite',
    acceptable: ['stalactite', 'une stalactite', 'le glaçon', 'glacon'],
    distractors: ['La stalagmite', 'Le bambou', "L'arbre"],
  },
  {
    id: 'enig-44',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Combien de fois peut-on soustraire 5 du nombre 25 ?',
    answer: 'Une seule fois',
    acceptable: ['une fois', 'une seule fois', '1', '1 fois'],
    distractors: ['5 fois', '25 fois', 'Une infinité'],
    hints: ['Après la première soustraction, le nombre a changé.'],
  },
  {
    id: 'enig-45',
    theme: 'enigmes',
    difficulty: 2,
    text: "J'ai un bec sans être un oiseau et je contiens de l'eau sans être une rivière. Qui suis-je ?",
    answer: 'La bouilloire',
    acceptable: ['bouilloire', 'la bouilloire', 'theiere', 'théière', 'la théière'],
    distractors: ['Le canard', 'Le robinet', 'Le vase'],
  },
  {
    id: 'enig-46',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Un train électrique file plein nord à vive allure. Dans quel sens souffle la fumée ?',
    answer: "Il n'y a pas de fumée",
    acceptable: ['pas de fumee', 'aucune fumee', "il n'y a pas de fumee", 'pas de fumée'],
    distractors: ['Vers le sud', 'Vers le nord', 'Vers le haut'],
  },
  {
    id: 'enig-47',
    theme: 'enigmes',
    difficulty: 2,
    text: 'Quel véhicule a quatre roues et des mouches ?',
    answer: 'Le camion poubelle',
    acceptable: ['camion poubelle', 'poubelle', 'camion-poubelle', 'un camion poubelle'],
    distractors: ['La voiture', 'Le corbillard', 'Le vélo'],
  },
  {
    id: 'enig-48',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Si 2 poules pondent 2 œufs en 2 jours, combien faut-il de poules pour avoir 6 œufs en 6 jours ?',
    answer: '2 poules',
    acceptable: ['2', 'deux', '2 poules', 'deux poules'],
    distractors: ['6 poules', '3 poules', '4 poules'],
    hints: ['Une poule pond un œuf tous les deux jours.'],
  },
  {
    id: 'enig-49',
    theme: 'enigmes',
    difficulty: 4,
    text: 'Pierre a 5 sœurs, et chacune de ses sœurs a un frère. Combien Pierre a-t-il de frères et sœurs ?',
    answer: '5 sœurs et aucun frère',
    acceptable: ['5 soeurs et aucun frere', '5 soeurs', 'cinq soeurs', 'aucun frere'],
    distractors: ['10', '6 frères et sœurs', '5 frères'],
    hints: ['Le frère de chaque sœur, c\'est Pierre.'],
  },
  {
    id: 'enig-50',
    theme: 'enigmes',
    difficulty: 3,
    text: 'Je peux remplir une pièce entière sans jamais prendre de place. Qui suis-je ?',
    answer: 'La lumière',
    acceptable: ['lumiere', 'la lumière', 'le jour'],
    distractors: ["L'air", 'Le son', 'Le parfum'],
  },
];
