import type { Question } from '../../../core/models';
import { universe } from './_build';

export const filmsQuestions: Question[] = [
  ...universe('films', 'Grands classiques', [
    // --- Faciles (5) ---
    { id: "clas-f1", d: 1, t: "Qui a réalisé Titanic ?", a: "James Cameron", x: ["Steven Spielberg", "Christopher Nolan", "Ridley Scott"], acc: ["cameron"] },
    { id: "clas-f2", d: 1, t: "Dans Star Wars, qui est le père de Luke Skywalker ?", a: "Dark Vador", x: ["Obi-Wan", "Yoda", "Palpatine"], acc: ["dark vador", "anakin", "darth vader", "vador"] },
    { id: "clas-f3", d: 1, t: "Dans Le Roi Lion, comment s'appelle le père de Simba ?", a: "Mufasa", x: ["Scar", "Rafiki", "Zazu"] },
    { id: "clas-f4", d: 1, t: "Quels animaux sont recréés dans Jurassic Park ?", a: "Les dinosaures", x: ["Les mammouths", "Les dragons", "Les loups"], acc: ["dinosaures"] },
    { id: "clas-f5", d: 1, t: "Comment s'appelle l'école de sorcellerie dans Harry Potter ?", a: "Poudlard", x: ["Beauxbâtons", "Durmstrang", "Salem"], acc: ["hogwarts"] },
    // --- Moyennes (10) ---
    { id: "clas-m1", d: 2, t: "Dans Toy Story, quel est le jouet cow-boy ?", a: "Woody", x: ["Buzz l'Éclair", "Rex", "Jessie"] },
    { id: "clas-m2", d: 2, t: "Dans Le Seigneur des Anneaux, quel hobbit doit détruire l'Anneau Unique ?", a: "Frodon", x: ["Gandalf", "Aragorn", "Sam"], acc: ["frodo", "frodon sacquet"] },
    { id: "clas-m3", d: 2, t: "Quel acteur incarne Jack Sparrow dans Pirates des Caraïbes ?", a: "Johnny Depp", x: ["Orlando Bloom", "Brad Pitt", "Javier Bardem"], acc: ["depp"] },
    { id: "clas-m4", d: 2, t: "Quel réalisateur est connu pour Inception et Interstellar ?", a: "Christopher Nolan", x: ["Denis Villeneuve", "James Cameron", "Quentin Tarantino"], acc: ["nolan"] },
    { id: "clas-m5", d: 2, t: "Quel super-héros Marvel est interprété par Robert Downey Jr. ?", a: "Iron Man", x: ["Captain America", "Thor", "Hulk"] },
    { id: "clas-m6", d: 2, t: "Qui a réalisé la trilogie Le Seigneur des Anneaux ?", a: "Peter Jackson", x: ["Guillermo del Toro", "Ridley Scott", "Steven Spielberg"] },
    { id: "clas-m7", d: 2, t: "Dans Le Parrain, quel est le nom de la famille mafieuse principale ?", a: "Corleone", x: ["Soprano", "Montana", "Gambino"] },
    { id: "clas-m8", d: 2, t: "Quel studio d'animation a créé Toy Story ?", a: "Pixar", x: ["DreamWorks", "Disney", "Illumination"] },
    { id: "clas-m9", d: 2, t: "Quel acteur incarne Don Vito Corleone dans Le Parrain ?", a: "Marlon Brando", x: ["Al Pacino", "Robert De Niro", "James Caan"] },
    { id: "clas-m10", d: 2, t: "Quel film Pixar met en scène les émotions dans la tête d'une fillette ?", a: "Vice-versa", x: ["Là-haut", "Coco", "Soul"], acc: ["vice-versa", "inside out"] },
    // --- Dures (15) ---
    { id: "clas-d1", d: 3, t: "Quel film coréen a remporté l'Oscar du meilleur film en 2020 ?", a: "Parasite", x: ["1917", "Joker", "Once Upon a Time in Hollywood"] },
    { id: "clas-d2", d: 3, t: "En quelle année est sorti le premier film Matrix ?", a: "1999", x: ["1997", "2001", "2003"] },
    { id: "clas-d3", d: 3, t: "Qui a réalisé Pulp Fiction ?", a: "Quentin Tarantino", x: ["Martin Scorsese", "Les frères Coen", "David Fincher"], acc: ["tarantino"] },
    { id: "clas-d4", d: 3, t: "Quel acteur joue le rôle-titre dans Forrest Gump ?", a: "Tom Hanks", x: ["Kevin Costner", "Tom Cruise", "Robin Williams"] },
    { id: "clas-d5", d: 3, t: "Quel film de James Cameron est longtemps resté le plus rentable de tous les temps ?", a: "Avatar", x: ["Avengers: Endgame", "Titanic", "Star Wars VII"] },
    { id: "clas-d6", d: 3, t: "Dans Retour vers le futur, de quelle année part Marty au début ?", a: "1985", x: ["1955", "1989", "1980"] },
    { id: "clas-d7", d: 3, t: "Quel film de 1994 suit Andy Dufresne dans la prison de Shawshank ?", a: "Les Évadés", x: ["La Ligne verte", "Le Pénitencier", "Évasion"], acc: ["les évadés", "shawshank", "the shawshank redemption"] },
    { id: "clas-d8", d: 3, t: "Quel acteur joue Korben Dallas dans Le Cinquième Élément ?", a: "Bruce Willis", x: ["Mel Gibson", "Kurt Russell", "Harrison Ford"] },
    { id: "clas-d9", d: 3, t: "Quel acteur incarne le Joker dans le film Joker ?", a: "Joaquin Phoenix", x: ["Heath Ledger", "Jared Leto", "Jack Nicholson"] },
    { id: "clas-d10", d: 3, t: "Quel réalisateur a signé « 2001, l'Odyssée de l'espace » et « Orange mécanique » ?", a: "Stanley Kubrick", x: ["Steven Spielberg", "Ridley Scott", "David Lynch"] },
    { id: "clas-d11", d: 3, t: "Quel acteur incarne Neo dans Matrix ?", a: "Keanu Reeves", x: ["Laurence Fishburne", "Hugo Weaving", "Brad Pitt"] },
    { id: "clas-d12", d: 3, t: "Quel film d'animation de Miyazaki a remporté l'Oscar en 2003 ?", a: "Le Voyage de Chihiro", x: ["Princesse Mononoké", "Le Château ambulant", "Mon voisin Totoro"] },
    { id: "clas-d13", d: 3, t: "Quel aventurier armé d'un fouet est incarné par Harrison Ford ?", a: "Indiana Jones", x: ["Han Solo", "James Bond", "Lara Croft"] },
    { id: "clas-d14", d: 3, t: "Dans Rocky, quel sport pratique le héros ?", a: "La boxe", x: ["La lutte", "Le catch", "Les arts martiaux"] },
    { id: "clas-d15", d: 3, t: "Quel extraterrestre veut « téléphoner maison » dans le film de Spielberg de 1982 ?", a: "E.T.", x: ["Alf", "Yoda", "Paul"] },
    // --- Pro (20) ---
    { id: "clas-p1", d: 4, t: "Quel film a remporté le tout premier Oscar du meilleur film ?", a: "Les Ailes", x: ["Autant en emporte le vent", "Ben-Hur", "Casablanca"], acc: ["wings", "les ailes"] },
    { id: "clas-p2", d: 4, t: "Dans Avengers, quelle Pierre d'Infinité se trouve sur le front de Vision ?", a: "La Pierre de l'Esprit", x: ["La Pierre du Temps", "La Pierre du Pouvoir", "La Pierre de l'Espace"], acc: ["esprit", "mind stone"] },
    { id: "clas-p3", d: 4, t: "Qui a composé la musique de Star Wars, Indiana Jones et Jurassic Park ?", a: "John Williams", x: ["Hans Zimmer", "Ennio Morricone", "Danny Elfman"] },
    { id: "clas-p4", d: 4, t: "Qui a réalisé Psychose ?", a: "Alfred Hitchcock", x: ["Stanley Kubrick", "Orson Welles", "Billy Wilder"], acc: ["hitchcock"] },
    { id: "clas-p5", d: 4, t: "En quelle année est sorti le tout premier Star Wars ?", a: "1977", x: ["1979", "1975", "1980"] },
    { id: "clas-p6", d: 4, t: "Quel film partage le record de 11 Oscars avec Ben-Hur et Titanic ?", a: "Le Seigneur des Anneaux : Le Retour du Roi", x: ["Avatar", "La La Land", "Gladiator"], acc: ["le retour du roi", "return of the king"] },
    { id: "clas-p7", d: 4, t: "Quel film de 1941 d'Orson Welles est souvent cité comme le meilleur de tous les temps ?", a: "Citizen Kane", x: ["Casablanca", "Sueurs froides", "Le Parrain"] },
    { id: "clas-p8", d: 4, t: "Quel acteur incarne Rick dans Casablanca ?", a: "Humphrey Bogart", x: ["Cary Grant", "James Stewart", "Clark Gable"] },
    { id: "clas-p9", d: 4, t: "Quel film musical de 1939 suit Dorothy et son chien Toto au pays d'Oz ?", a: "Le Magicien d'Oz", x: ["Mary Poppins", "Chantons sous la pluie", "Blanche-Neige"] },
    { id: "clas-p10", d: 4, t: "Quel film de 1939 avec Clark Gable est adapté d'un roman sur la guerre de Sécession ?", a: "Autant en emporte le vent", x: ["Ben-Hur", "Cléopâtre", "Spartacus"] },
    { id: "clas-p11", d: 4, t: "Quel robot assassin est incarné par Arnold Schwarzenegger en 1984 ?", a: "Le Terminator", x: ["RoboCop", "Bumblebee", "Ultron"] },
    { id: "clas-p12", d: 4, t: "Quel film de Ridley Scott de 1979 se déroule à bord du vaisseau Nostromo ?", a: "Alien", x: ["Blade Runner", "Outland", "Event Horizon"] },
    { id: "clas-p13", d: 4, t: "Quel film de Ridley Scott de 2000 suit le général romain Maximus ?", a: "Gladiator", x: ["Spartacus", "Ben-Hur", "Troie"] },
    { id: "clas-p14", d: 4, t: "Dans « 2001, l'Odyssée de l'espace », comment s'appelle l'ordinateur de bord ?", a: "HAL 9000", x: ["Skynet", "GLaDOS", "Deep Thought"] },
    { id: "clas-p15", d: 4, t: "Quel acteur incarne Vito Corleone jeune dans Le Parrain, 2e partie ?", a: "Robert De Niro", x: ["Al Pacino", "James Caan", "Marlon Brando"] },
    { id: "clas-p16", d: 4, t: "Quel film de science-fiction de Ridley Scott de 1982 met en scène des « réplicants » ?", a: "Blade Runner", x: ["Total Recall", "Minority Report", "Tron"] },
    { id: "clas-p17", d: 4, t: "Quel film de Coppola de 1979 sur la guerre du Vietnam s'inspire de « Au cœur des ténèbres » ?", a: "Apocalypse Now", x: ["Voyage au bout de l'enfer", "Platoon", "Full Metal Jacket"] },
    { id: "clas-p18", d: 4, t: "Quel réalisateur italien a signé « Le Bon, la Brute et le Truand » ?", a: "Sergio Leone", x: ["Federico Fellini", "Dario Argento", "Vittorio De Sica"] },
    { id: "clas-p19", d: 4, t: "Qui a composé la musique du « Bon, la Brute et le Truand » et de nombreux westerns ?", a: "Ennio Morricone", x: ["John Williams", "Hans Zimmer", "Nino Rota"] },
    { id: "clas-p20", d: 4, t: "Quel film musical de 1952 voit Gene Kelly danser sous la pluie ?", a: "Chantons sous la pluie", x: ["Un Américain à Paris", "West Side Story", "Cabaret"] },
  ]),

  ...universe('films', 'Drames', [
    // --- Faciles (5) ---
    { id: "drame-f1", d: 1, t: "Quel drame retrace la vie de Freddie Mercury, chanteur de Queen ?", a: "Bohemian Rhapsody", x: ["Rocketman", "Elvis", "Amadeus"] },
    { id: "drame-f2", d: 1, t: "Quel drame de Spielberg suit un industriel qui sauve des Juifs pendant la Seconde Guerre mondiale ?", a: "La Liste de Schindler", x: ["Le Pianiste", "La Vie est belle", "Il faut sauver le soldat Ryan"] },
    { id: "drame-f3", d: 1, t: "Quel drame italien de Benigni voit un père transformer un camp en jeu pour son fils ?", a: "La Vie est belle", x: ["Le Pianiste", "La Rafle", "Au revoir les enfants"] },
    { id: "drame-f4", d: 1, t: "Quel drame de 1999 avec Tom Hanks se déroule dans le couloir de la mort ?", a: "La Ligne verte", x: ["Les Évadés", "La Dernière Marche", "Dead Man Walking"] },
    { id: "drame-f5", d: 1, t: "Quel drame musical réunit Lady Gaga et Bradley Cooper en 2018 ?", a: "A Star Is Born", x: ["La La Land", "Whiplash", "Rocketman"] },
    // --- Moyennes (10) ---
    { id: "drame-m1", d: 2, t: "Quel drame de Scorsese de 1990 suit l'ascension de gangsters, avec Ray Liotta ?", a: "Les Affranchis", x: ["Le Parrain", "Casino", "Les Infiltrés"] },
    { id: "drame-m2", d: 2, t: "Quel drame de 1993 voit un avocat séropositif, avec Tom Hanks oscarisé ?", a: "Philadelphia", x: ["Dallas Buyers Club", "Milk", "Rain Man"] },
    { id: "drame-m3", d: 2, t: "Quel drame de Danny Boyle suit un jeune des bidonvilles indiens à un jeu télévisé ?", a: "Slumdog Millionaire", x: ["Lion", "La Cité de Dieu", "Gandhi"] },
    { id: "drame-m4", d: 2, t: "Quel drame de Ron Howard retrace la vie du mathématicien John Nash ?", a: "Un homme d'exception", x: ["Rain Man", "Le Discours d'un roi", "Will Hunting"] },
    { id: "drame-m5", d: 2, t: "Quel drame de Gus Van Sant voit Matt Damon en génie des maths employé comme concierge ?", a: "Will Hunting", x: ["Un homme d'exception", "Le Cercle des poètes disparus", "Whiplash"] },
    { id: "drame-m6", d: 2, t: "Quel drame de Peter Weir voit Robin Williams inspirer ses élèves par la poésie ?", a: "Le Cercle des poètes disparus", x: ["Will Hunting", "Écrire pour exister", "Le Maître de musique"] },
    { id: "drame-m7", d: 2, t: "Quel drame de 2010 voit le roi George VI vaincre son bégaiement ?", a: "Le Discours d'un roi", x: ["The Queen", "Lincoln", "Le Jeune Karl Marx"] },
    { id: "drame-m8", d: 2, t: "Quel drame de 2013 de Steve McQueen suit un homme noir libre réduit en esclavage ?", a: "12 Years a Slave", x: ["Django Unchained", "La Couleur des sentiments", "Selma"] },
    { id: "drame-m9", d: 2, t: "Quel drame de Clint Eastwood voit une boxeuse entraînée par un vieil entraîneur ?", a: "Million Dollar Baby", x: ["Rocky", "Raging Bull", "The Fighter"] },
    { id: "drame-m10", d: 2, t: "Quel drame de Darren Aronofsky voit Mickey Rourke en catcheur sur le retour ?", a: "The Wrestler", x: ["Rocky", "Raging Bull", "Foxcatcher"] },
    // --- Dures (15) ---
    { id: "drame-d1", d: 3, t: "Quel drame de 1975 avec Jack Nicholson se déroule dans un hôpital psychiatrique ?", a: "Vol au-dessus d'un nid de coucou", x: ["Shutter Island", "Rain Man", "Un homme d'exception"] },
    { id: "drame-d2", d: 3, t: "Quel drame de 2002 de Polanski suit un pianiste juif dans le ghetto de Varsovie ?", a: "Le Pianiste", x: ["La Liste de Schindler", "La Vie est belle", "Le Fils de Saul"] },
    { id: "drame-d3", d: 3, t: "Quel drame de 1988 voit Dustin Hoffman en autiste savant, frère de Tom Cruise ?", a: "Rain Man", x: ["Forrest Gump", "Un homme d'exception", "I Am Sam"] },
    { id: "drame-d4", d: 3, t: "Quel drame de Scorsese de 1980 suit le boxeur Jake LaMotta, avec Robert De Niro ?", a: "Raging Bull", x: ["Rocky", "The Fighter", "Ali"] },
    { id: "drame-d5", d: 3, t: "Quel drame de 1979 sur un divorce oppose Dustin Hoffman et Meryl Streep ?", a: "Kramer contre Kramer", x: ["Marriage Story", "La Guerre des Rose", "Blue Valentine"] },
    { id: "drame-d6", d: 3, t: "Quel drame français de 2011 lie un aristocrate tétraplégique et son aide à domicile ?", a: "Intouchables", x: ["Le Goût des autres", "La Famille Bélier", "Hors normes"] },
    { id: "drame-d7", d: 3, t: "Quel drame de 2014 oppose un jeune batteur à un professeur tyrannique ?", a: "Whiplash", x: ["La La Land", "Black Swan", "Le Concert"] },
    { id: "drame-d8", d: 3, t: "Quel drame de 1957 de Sidney Lumet enferme douze jurés dans une salle ?", a: "Douze hommes en colère", x: ["Le Verdict", "Témoin à charge", "Anatomie d'un meurtre"] },
    { id: "drame-d9", d: 3, t: "Quel drame de 1985 de Sydney Pollack voit Meryl Streep et Robert Redford au Kenya ?", a: "Out of Africa", x: ["Le Patient anglais", "Nulle part en Afrique", "Congo"] },
    { id: "drame-d10", d: 3, t: "Quel drame de 1996 d'Anthony Minghella suit un grand brûlé et ses souvenirs ?", a: "Le Patient anglais", x: ["Out of Africa", "La Déchirure", "Retour à Cold Mountain"] },
    { id: "drame-d11", d: 3, t: "Quel drame de 2006 sur la surveillance en RDA a gagné l'Oscar du film étranger ?", a: "La Vie des autres", x: ["Good Bye Lenin!", "Le Tambour", "Barbara"] },
    { id: "drame-d12", d: 3, t: "Quel drame de 2016 voit Casey Affleck oscarisé, endeuillé, dans le Massachusetts ?", a: "Manchester by the Sea", x: ["Moonlight", "Room", "Nebraska"] },
    { id: "drame-d13", d: 3, t: "Quel drame de 2016 de Barry Jenkins, Oscar du meilleur film, suit un jeune Noir de Miami ?", a: "Moonlight", x: ["Manchester by the Sea", "Green Book", "Boyhood"] },
    { id: "drame-d14", d: 3, t: "Quel drame de 2019 suit un couple en plein divorce, avec Adam Driver et Scarlett Johansson ?", a: "Marriage Story", x: ["Kramer contre Kramer", "Blue Valentine", "Revolutionary Road"] },
    { id: "drame-d15", d: 3, t: "Quel drame de Ken Loach, Palme d'or 2016, suit un menuisier face à l'administration ?", a: "Moi, Daniel Blake", x: ["La Loi du marché", "Deux jours, une nuit", "Sorry We Missed You"] },
    // --- Pro (20) ---
    { id: "drame-p1", d: 4, t: "Quel drame de 1954 de Kazan voit Marlon Brando en docker révolté ?", a: "Sur les quais", x: ["Un tramway nommé Désir", "L'Équipée sauvage", "Reflets dans un œil d'or"] },
    { id: "drame-p2", d: 4, t: "Quel drame de 1951 adapte Tennessee Williams avec Brando en Stanley Kowalski ?", a: "Un tramway nommé Désir", x: ["Sur les quais", "La Chatte sur un toit brûlant", "Soudain l'été dernier"] },
    { id: "drame-p3", d: 4, t: "Quel drame de 2011 de Terrence Malick, Palme d'or, mêle l'enfance et le cosmos ?", a: "The Tree of Life", x: ["Melancholia", "The Fountain", "Boyhood"] },
    { id: "drame-p4", d: 4, t: "Quel drame de Richard Linklater a été tourné sur douze ans avec les mêmes acteurs ?", a: "Boyhood", x: ["The Tree of Life", "Moonlight", "Roma"] },
    { id: "drame-p5", d: 4, t: "Quel drame mexicain de 2018 d'Alfonso Cuarón, en noir et blanc, a gagné l'Oscar du film étranger ?", a: "Roma", x: ["Amours chiennes", "Y tu mamá también", "La Zona"] },
    { id: "drame-p6", d: 4, t: "Quel drame de 1993 de Jane Campion, Palme d'or, suit une muette et son piano ?", a: "La Leçon de piano", x: ["Les Hauts de Hurlevent", "Orgueil et Préjugés", "Bright Star"] },
    { id: "drame-p7", d: 4, t: "Quel drame de 1962 de David Lean suit un officier britannique dans le désert d'Arabie ?", a: "Lawrence d'Arabie", x: ["Le Pont de la rivière Kwaï", "Docteur Jivago", "Gandhi"] },
    { id: "drame-p8", d: 4, t: "Quel drame de 1982 d'Attenborough retrace la vie du leader indien de la non-violence ?", a: "Gandhi", x: ["Lawrence d'Arabie", "Le Dernier Empereur", "Mississippi Burning"] },
    { id: "drame-p9", d: 4, t: "Quel drame de 1987 de Bertolucci suit le dernier empereur de Chine ?", a: "Le Dernier Empereur", x: ["Gandhi", "La Cité interdite", "Adieu ma concubine"] },
    { id: "drame-p10", d: 4, t: "Quel drame de 1993 de Chen Kaige, Palme d'or, suit deux acteurs d'opéra de Pékin ?", a: "Adieu ma concubine", x: ["Le Dernier Empereur", "Épouses et concubines", "Hero"] },
    { id: "drame-p11", d: 4, t: "Quel drame de 1959 de Truffaut, clé de la Nouvelle Vague, suit le jeune Antoine Doinel ?", a: "Les Quatre Cents Coups", x: ["À bout de souffle", "Jules et Jim", "Le Mépris"] },
    { id: "drame-p12", d: 4, t: "Quel drame de 1948 de De Sica, chef-d'œuvre néoréaliste, suit un père et son vélo ?", a: "Le Voleur de bicyclette", x: ["Rome, ville ouverte", "La Strada", "Umberto D."] },
    { id: "drame-p13", d: 4, t: "Quel drame de 1957 de Bergman voit un chevalier jouer aux échecs avec la Mort ?", a: "Le Septième Sceau", x: ["Les Fraises sauvages", "Persona", "Cris et chuchotements"] },
    { id: "drame-p14", d: 4, t: "Quel drame japonais de 1952 de Kurosawa suit un fonctionnaire mourant cherchant un sens ?", a: "Vivre", x: ["Rashômon", "Les Sept Samouraïs", "Dersou Ouzala"] },
    { id: "drame-p15", d: 4, t: "Quel drame de 2012 de Haneke, Palme d'or, suit un couple âgé face à la maladie ?", a: "Amour", x: ["Le Ruban blanc", "Caché", "La Pianiste"] },
    { id: "drame-p16", d: 4, t: "Quel drame de 2017 de Guillermo del Toro, Oscar du meilleur film, lie une muette et une créature ?", a: "La Forme de l'eau", x: ["Le Labyrinthe de Pan", "Hellboy", "Crimson Peak"] },
    { id: "drame-p17", d: 4, t: "Quel drame de 2015 voit une mère et son fils captifs dans une seule pièce ?", a: "Room", x: ["Split", "10 Cloverfield Lane", "Prisoners"] },
    { id: "drame-p18", d: 4, t: "Quel drame de 2020 de Chloé Zhao, Oscar du meilleur film, suit une nomade avec Frances McDormand ?", a: "Nomadland", x: ["Roma", "Minari", "Three Billboards"] },
    { id: "drame-p19", d: 4, t: "Quel drame de 2003 de Sofia Coppola réunit Bill Murray et Scarlett Johansson à Tokyo ?", a: "Lost in Translation", x: ["Her", "Broken Flowers", "Somewhere"] },
    { id: "drame-p20", d: 4, t: "Quel drame britannique de 1996 de Mike Leigh, Palme d'or, réunit une femme noire et sa mère biologique ?", a: "Secrets et Mensonges", x: ["Le Goût des autres", "Another Year", "Vera Drake"] },
  ]),

  ...universe('films', 'Horreur', [
    // --- Faciles (5) ---
    { id: 'hor-f1', d: 1, t: 'Dans quelle saga un tueur masqué nommé Jason hante le camp Crystal Lake ?', a: 'Vendredi 13', acc: ['vendredi 13', 'friday the 13th'], x: ['Halloween', 'Scream', 'Saw'] },
    { id: 'hor-f2', d: 1, t: 'Quel masque le tueur de la saga Scream porte-t-il ?', a: 'Le masque Ghostface', acc: ['ghostface', 'masque ghostface'], x: ['Un masque de hockey', 'Un masque en cuir', 'Une cagoule noire'] },
    { id: 'hor-f3', d: 1, t: 'Quelle poupée rousse est possédée par l\'âme d\'un tueur ?', a: 'Chucky', x: ['Annabelle', 'Billy', 'Slappy'] },
    { id: 'hor-f4', d: 1, t: 'Dans Les Dents de la mer, quel animal terrorise les baigneurs ?', a: 'Un requin', x: ['Un crocodile', 'Une pieuvre', 'Un orque'] },
    { id: 'hor-f5', d: 1, t: 'De quelle couleur est le sang qui gicle typiquement dans les films gore ?', a: 'Rouge', x: ['Vert', 'Bleu', 'Noir'] },

    // --- Moyennes (10) ---
    { id: 'hor-m1', d: 2, t: 'Quel tueur au pull rayé rouge et vert hante les rêves dans Les Griffes de la nuit ?', a: 'Freddy Krueger', x: ['Jason Voorhees', 'Michael Myers', 'Norman Bates'] },
    { id: 'hor-m2', d: 2, t: 'Dans Halloween, comment s\'appelle le tueur masqué ?', a: 'Michael Myers', x: ['Jason Voorhees', 'Freddy Krueger', 'Leatherface'] },
    { id: 'hor-m3', d: 2, t: 'Quel film de 1973 met en scène l\'exorcisme de la jeune Regan ?', a: 'L\'Exorciste', x: ['Rosemary\'s Baby', 'La Malédiction', 'Amityville'] },
    { id: 'hor-m4', d: 2, t: 'Quelle saga de pièges mortels tourne autour d\'un tueur appelé Jigsaw ?', a: 'Saw', x: ['Hostel', 'Scream', 'Insidious'] },
    { id: 'hor-m5', d: 2, t: 'Quel film de zombies de 1968 de George Romero a lancé le genre ?', a: 'La Nuit des morts-vivants', acc: ['nuit des morts-vivants', 'night of the living dead'], x: ['28 jours plus tard', 'Zombie', 'L\'Armée des morts'] },
    { id: 'hor-m6', d: 2, t: 'Dans Shining, quel hôtel isolé rend fou Jack Torrance ?', a: 'L\'hôtel Overlook', acc: ['overlook'], x: ['L\'hôtel Bates', 'L\'hôtel Cecil', 'Le manoir Hill'] },
    { id: 'hor-m7', d: 2, t: 'Quel écrivain américain a écrit Ça, Shining et Carrie ?', a: 'Stephen King', x: ['Dean Koontz', 'Clive Barker', 'Bram Stoker'] },
    { id: 'hor-m8', d: 2, t: 'Quel clown maléfique hante la ville de Derry dans Ça ?', a: 'Grippe-Sou', acc: ['grippe-sou', 'pennywise'], x: ['Chucky', 'Ghostface', 'Jigsaw'] },
    { id: 'hor-m9', d: 2, t: 'Quel tueur défiguré manie une tronçonneuse au fin fond du Texas ?', a: 'Leatherface', x: ['Ghostface', 'Chucky', 'Jigsaw'] },
    { id: 'hor-m10', d: 2, t: 'Quelle franchise met en scène des poupées, des nonnes démoniaques et les époux Warren ?', a: 'Conjuring', acc: ['conjuring', 'the conjuring'], x: ['Insidious', 'Sinister', 'Paranormal Activity'] },

    // --- Dures (15) ---
    { id: 'hor-d1', d: 3, t: 'Qui a réalisé Halloween en 1978 et en a composé la musique ?', a: 'John Carpenter', x: ['Wes Craven', 'Tobe Hooper', 'Sean Cunningham'] },
    { id: 'hor-d2', d: 3, t: 'Qui a réalisé Les Griffes de la nuit et le premier Scream ?', a: 'Wes Craven', x: ['John Carpenter', 'Sam Raimi', 'George Romero'] },
    { id: 'hor-d3', d: 3, t: 'Dans Psychose, comment s\'appelle le motel tenu par Norman Bates ?', a: 'Le motel Bates', acc: ['bates', 'motel bates'], x: ['Le motel Overlook', 'Le motel Cecil', 'Le motel Sunset'] },
    { id: 'hor-d4', d: 3, t: 'Quel film de 1999 en found footage suit trois étudiants perdus dans une forêt ?', a: 'Le Projet Blair Witch', acc: ['blair witch', 'projet blair witch'], x: ['Paranormal Activity', 'REC', 'Cloverfield'] },
    { id: 'hor-d5', d: 3, t: 'Quelle poupée possédée a son propre film dérivé de l\'univers Conjuring ?', a: 'Annabelle', x: ['Chucky', 'Slappy', 'Brahms'] },
    { id: 'hor-d6', d: 3, t: 'Quel réalisateur japonais a lancé la J-horror avec Ring ?', a: 'Hideo Nakata', x: ['Takashi Miike', 'Takashi Shimizu', 'Kiyoshi Kurosawa'] },
    { id: 'hor-d7', d: 3, t: 'Dans Ring, combien de jours reste-t-il à vivre après avoir vu la cassette maudite ?', a: '7 jours', x: ['3 jours', '13 jours', '1 jour'] },
    { id: 'hor-d8', d: 3, t: 'Quel film de Jordan Peele de 2017 mêle horreur et satire raciale ?', a: 'Get Out', x: ['Us', 'Nope', 'Midsommar'] },
    { id: 'hor-d9', d: 3, t: 'Qui a réalisé Hérédité et Midsommar ?', a: 'Ari Aster', x: ['Robert Eggers', 'Jordan Peele', 'David Robert Mitchell'] },
    { id: 'hor-d10', d: 3, t: 'Quel film de 1979 dans l\'espace a pour slogan « personne ne vous entendra crier » ?', a: 'Alien', x: ['The Thing', 'Event Horizon', 'Life'] },
    { id: 'hor-d11', d: 3, t: 'Dans The Thing de John Carpenter, qu\'est-ce qui imite parfaitement ses victimes ?', a: 'Un extraterrestre', acc: ['extraterrestre', 'alien', 'la chose'], x: ['Un fantôme', 'Un virus', 'Un robot'] },
    { id: 'hor-d12', d: 3, t: 'Quel film de 1974 de Tobe Hooper a choqué par son ambiance texane malsaine ?', a: 'Massacre à la tronçonneuse', acc: ['massacre a la tronconneuse'], x: ['La Colline a des yeux', 'Délivrance', 'Wrong Turn'] },
    { id: 'hor-d13', d: 3, t: 'Quelle saga espagnole en found footage se déroule dans un immeuble en quarantaine ?', a: 'REC', x: ['Paranormal Activity', 'Blair Witch', 'Cloverfield'] },
    { id: 'hor-d14', d: 3, t: 'Dans le tout premier Vendredi 13, qui est en réalité le tueur ?', a: 'Pamela Voorhees', acc: ['pamela voorhees', 'la mere de jason'], x: ['Jason Voorhees', 'Michael Myers', 'Alice Hardy'] },
    { id: 'hor-d15', d: 3, t: 'Quel film de 2018 impose le silence face à des créatures sensibles au moindre bruit ?', a: 'Sans un bruit', acc: ['sans un bruit', 'a quiet place'], x: ['Bird Box', 'The Silence', 'Don\'t Breathe'] },

    // --- Pro (20) ---
    { id: 'hor-p1', d: 4, t: 'En quelle année est sorti le premier Halloween de John Carpenter ?', a: '1978', x: ['1980', '1974', '1982'] },
    { id: 'hor-p2', d: 4, t: 'Quelle actrice incarne Laurie Strode dans la saga Halloween ?', a: 'Jamie Lee Curtis', x: ['Sigourney Weaver', 'Neve Campbell', 'Heather Langenkamp'] },
    { id: 'hor-p3', d: 4, t: 'Quel acteur incarne Freddy Krueger dans la saga originale ?', a: 'Robert Englund', x: ['Kane Hodder', 'Doug Bradley', 'Tony Todd'] },
    { id: 'hor-p4', d: 4, t: 'Quel démon aux épingles plantées dans la tête dirige les Cénobites dans Hellraiser ?', a: 'Pinhead', x: ['Pyramid Head', 'Samara', 'Valak'] },
    { id: 'hor-p5', d: 4, t: 'Quelle actrice incarne Sidney Prescott dans la saga Scream ?', a: 'Neve Campbell', x: ['Courteney Cox', 'Drew Barrymore', 'Jamie Lee Curtis'] },
    { id: 'hor-p6', d: 4, t: 'Qui a réalisé la saga culte Evil Dead ?', a: 'Sam Raimi', x: ['Peter Jackson', 'Wes Craven', 'Stuart Gordon'] },
    { id: 'hor-p7', d: 4, t: 'Quel héros à la tronçonneuse et au fusil combat les morts dans Evil Dead ?', a: 'Ash Williams', x: ['Tommy Jarvis', 'Nancy Thompson', 'Chris Washington'] },
    { id: 'hor-p8', d: 4, t: 'Quel film muet de 1922 de Murnau est une adaptation non autorisée de Dracula ?', a: 'Nosferatu', x: ['Dracula', 'Vampyr', 'Le Golem'] },
    { id: 'hor-p9', d: 4, t: 'Quel réalisateur mexicain a fait Le Labyrinthe de Pan et La Forme de l\'eau ?', a: 'Guillermo del Toro', x: ['Alfonso Cuarón', 'Alejandro González Iñárritu', 'Robert Rodriguez'] },
    { id: 'hor-p10', d: 4, t: 'Comment s\'appelle le croque-mitaine du film d\'horreur australien de 2014 ?', a: 'Le Babadook', acc: ['babadook'], x: ['Le Slender Man', 'Le Bonhomme Sept Heures', 'Le Croque-mitaine'] },
    { id: 'hor-p11', d: 4, t: 'Quel film de 1976 de Brian De Palma adapte un roman de Stephen King sur une lycéenne télékinésiste ?', a: 'Carrie', x: ['Christine', 'Cujo', 'Firestarter'] },
    { id: 'hor-p12', d: 4, t: 'Quelle saga de found footage a débuté en 2007 avec une caméra dans une chambre ?', a: 'Paranormal Activity', x: ['REC', 'Blair Witch', 'Cloverfield'] },
    { id: 'hor-p13', d: 4, t: 'Quel acteur incarne Hannibal Lecter dans Le Silence des agneaux ?', a: 'Anthony Hopkins', x: ['Christopher Lee', 'Vincent Price', 'Robert Englund'] },
    { id: 'hor-p14', d: 4, t: 'Quel film de 1968 de Roman Polanski met en scène une grossesse démoniaque ?', a: 'Rosemary\'s Baby', x: ['La Malédiction', 'L\'Exorciste', 'L\'Antéchrist'] },
    { id: 'hor-p15', d: 4, t: 'Quel film de 1980 de Stanley Kubrick adapte le roman Shining de Stephen King ?', a: 'Shining', x: ['Ça', 'Christine', 'Simetierre'] },
    { id: 'hor-p16', d: 4, t: 'Quelle saga imagine une nuit annuelle où tous les crimes deviennent légaux ?', a: 'American Nightmare', acc: ['american nightmare', 'the purge', 'purge'], x: ['Battle Royale', 'Hunger Games', 'Hostel'] },
    { id: 'hor-p17', d: 4, t: 'Quel réalisateur néo-zélandais a fait le film gore Braindead avant Le Seigneur des Anneaux ?', a: 'Peter Jackson', x: ['Sam Raimi', 'Guillermo del Toro', 'George Romero'] },
    { id: 'hor-p18', d: 4, t: 'Quel vampire créé par Bram Stoker en 1897 est le plus adapté au cinéma ?', a: 'Dracula', x: ['Nosferatu', 'Carmilla', 'Lestat'] },
    { id: 'hor-p19', d: 4, t: 'Quel film japonais de 2000 fait s\'entretuer des lycéens sur une île déserte ?', a: 'Battle Royale', x: ['Ring', 'Ju-on', 'Audition'] },
    { id: 'hor-p20', d: 4, t: 'Quel spectre au crochet revient si l\'on prononce son nom cinq fois devant un miroir ?', a: 'Candyman', x: ['Bloody Mary', 'Pinhead', 'Samara'] },
  ]),

  ...universe('films', 'Comédies romantiques', [
    // --- Faciles (5) ---
    { id: 'romcom-f1', d: 1, t: 'Dans quelle comédie romantique Julia Roberts joue-t-elle une prostituée séduite par un homme d\'affaires ?', a: 'Pretty Woman', x: ['Coup de foudre à Notting Hill', 'Le Journal de Bridget Jones', 'Love Actually'] },
    { id: 'romcom-f2', d: 1, t: 'Quel film réunit Hugh Grant et Julia Roberts autour d\'une librairie de Londres ?', a: 'Coup de foudre à Notting Hill', x: ['Pretty Woman', 'Quatre mariages et un enterrement', 'Love Actually'] },
    { id: 'romcom-f3', d: 1, t: 'Quelle comédie romantique de Noël entremêle plusieurs histoires d\'amour à Londres ?', a: 'Love Actually', x: ['Pretty Woman', 'Le Journal de Bridget Jones', 'Nuits blanches à Seattle'] },
    { id: 'romcom-f4', d: 1, t: 'Quelle actrice incarne Bridget Jones ?', a: 'Renée Zellweger', x: ['Cameron Diaz', 'Kate Hudson', 'Reese Witherspoon'] },
    { id: 'romcom-f5', d: 1, t: 'Dans « Grease », quel couple d\'adolescents chante et danse ?', a: 'Danny et Sandy', x: ['Jack et Rose', 'Noah et Allie', 'Baby et Johnny'] },
    // --- Moyennes (10) ---
    { id: 'romcom-m1', d: 2, t: 'Quel film culte réunit Meg Ryan et Billy Crystal autour de l\'amitié homme-femme ?', a: 'Quand Harry rencontre Sally', x: ['Nuits blanches à Seattle', 'Vous avez un message', 'Coup de foudre à Notting Hill'] },
    { id: 'romcom-m2', d: 2, t: 'Quel film réunit Meg Ryan et Tom Hanks qui tombent amoureux par messagerie électronique ?', a: 'Vous avez un message', x: ['Nuits blanches à Seattle', 'Quand Harry rencontre Sally', 'Pretty Woman'] },
    { id: 'romcom-m3', d: 2, t: 'Quel film suit une avocate blonde à Harvard, incarnée par Reese Witherspoon ?', a: 'La Revanche d\'une blonde', x: ['Mean Girls', 'Clueless', 'Sexe Intentions'] },
    { id: 'romcom-m4', d: 2, t: 'Dans « Dirty Dancing », qui apprend à danser à Bébé ?', a: 'Johnny', x: ['Danny', 'Jack', 'Noah'] },
    { id: 'romcom-m5', d: 2, t: 'Quel film de 2004 avec Jim Carrey imagine un amour effacé de la mémoire ?', a: 'Eternal Sunshine of the Spotless Mind', x: ['500 jours ensemble', 'Her', 'Lost in Translation'] },
    { id: 'romcom-m6', d: 2, t: 'Dans « Le Journal de Bridget Jones », entre quels deux hommes hésite-t-elle ?', a: 'Mark et Daniel', x: ['Noah et Allie', 'Jack et Will', 'Ross et Chandler'] },
    { id: 'romcom-m7', d: 2, t: 'Quel film suit une journaliste qui doit faire fuir un homme en dix jours ?', a: 'Comment se faire larguer en 10 leçons', x: ['Hitch', 'Le Journal de Bridget Jones', 'La Proposition'] },
    { id: 'romcom-m8', d: 2, t: 'Quel « coach en séduction » incarné par Will Smith aide des hommes timides ?', a: 'Hitch', x: ['Crazy Stupid Love', 'La Proposition', 'Just Married ou presque'] },
    { id: 'romcom-m9', d: 2, t: 'Quelle comédie romantique musicale réunit Emma Stone et Ryan Gosling à Los Angeles ?', a: 'La La Land', x: ['Whiplash', 'Crazy Stupid Love', 'Nuits blanches à Seattle'] },
    { id: 'romcom-m10', d: 2, t: 'Quel film adapte Jane Austen avec Keira Knightley en Elizabeth Bennet ?', a: 'Orgueil et Préjugés', x: ['Raison et Sentiments', 'Emma', 'Jane Eyre'] },
    // --- Dures (15) ---
    { id: 'romcom-d1', d: 3, t: 'Quelle réalisatrice est une reine de la comédie romantique avec « Nuits blanches à Seattle » ?', a: 'Nora Ephron', x: ['Nancy Meyers', 'Nia Vardalos', 'Elaine May'] },
    { id: 'romcom-d2', d: 3, t: 'Quel scénariste a écrit « Love Actually », « Coup de foudre à Notting Hill » et « Quatre mariages » ?', a: 'Richard Curtis', x: ['Woody Allen', 'James L. Brooks', 'Cameron Crowe'] },
    { id: 'romcom-d3', d: 3, t: 'Dans « 500 jours ensemble », quel acteur joue Tom, amoureux de Summer ?', a: 'Joseph Gordon-Levitt', x: ['Michael Cera', 'Andrew Garfield', 'Paul Rudd'] },
    { id: 'romcom-d4', d: 3, t: 'Quel film réunit Ryan Gosling et Rachel McAdams dans une romance sur plusieurs décennies ?', a: 'N\'oublie jamais', x: ['La La Land', 'Coup de foudre à Notting Hill', 'Blue Valentine'] },
    { id: 'romcom-d5', d: 3, t: 'Quelle comédie romantique voit un homme revivre sans fin le même jour à Punxsutawney ?', a: 'Un jour sans fin', x: ['Retour vers le futur', 'Edge of Tomorrow', 'Sur la route de Madison'] },
    { id: 'romcom-d6', d: 3, t: 'Dans quel quartier de Paris se déroule « Le Fabuleux Destin d\'Amélie Poulain » ?', a: 'Montmartre', x: ['le Marais', 'Montparnasse', 'Belleville'] },
    { id: 'romcom-d7', d: 3, t: 'Quel film de Woody Allen, romance new-yorkaise, a gagné l\'Oscar du meilleur film en 1978 ?', a: 'Annie Hall', x: ['Manhattan', 'Harry dans tous ses états', 'Minuit à Paris'] },
    { id: 'romcom-d8', d: 3, t: 'Quel duo forme le jeune couple de « Crazy Stupid Love » ?', a: 'Emma Stone et Ryan Gosling', x: ['Rachel McAdams et Ryan Gosling', 'Emma Stone et Andrew Garfield', 'Cameron Diaz et Justin Timberlake'] },
    { id: 'romcom-d9', d: 3, t: 'Quel film de Cédric Klapisch suit des étudiants Erasmus à Barcelone avec Romain Duris ?', a: 'L\'Auberge espagnole', x: ['Les Poupées russes', 'Paris', 'Le Péril jeune'] },
    { id: 'romcom-d10', d: 3, t: 'Dans quelle ville se déroule « Pretty Woman » ?', a: 'Los Angeles', x: ['New York', 'San Francisco', 'Las Vegas'] },
    { id: 'romcom-d11', d: 3, t: 'Quel acteur britannique bafouillant est le roi de la comédie romantique des années 1990 ?', a: 'Hugh Grant', x: ['Colin Firth', 'Jude Law', 'Ewan McGregor'] },
    { id: 'romcom-d12', d: 3, t: 'Quelle actrice joue Andie dans « Comment se faire larguer en 10 leçons » ?', a: 'Kate Hudson', x: ['Kate Beckinsale', 'Cameron Diaz', 'Reese Witherspoon'] },
    { id: 'romcom-d13', d: 3, t: 'Quel film adoucit un écrivain misanthrope grâce à une serveuse, avec Jack Nicholson ?', a: 'Pour le pire et pour le meilleur', x: ['Sur la route de Madison', 'Une équipe hors du commun', 'Nuits blanches à Seattle'] },
    { id: 'romcom-d14', d: 3, t: 'Quelle comédie romantique de 2018 met en scène une distribution asiatique et un mariage à Singapour ?', a: 'Crazy Rich Asians', x: ['The Big Sick', 'Toujours l\'amour', 'Coup de foudre à Bollywood'] },
    { id: 'romcom-d15', d: 3, t: 'Quel film de 1999 modernise Shakespeare dans un lycée et révèle Heath Ledger ?', a: '10 bonnes raisons de te larguer', x: ['American Pie', 'Sexe Intentions', 'Clueless'] },
    // --- Pro (20) ---
    { id: 'romcom-p1', d: 4, t: 'Quel film de 1953 voit Audrey Hepburn en princesse en escapade à Rome avec Gregory Peck ?', a: 'Vacances romaines', x: ['Sabrina', 'Diamants sur canapé', 'Drôle de frimousse'] },
    { id: 'romcom-p2', d: 4, t: 'Dans « Diamants sur canapé », quelle actrice incarne Holly Golightly ?', a: 'Audrey Hepburn', x: ['Grace Kelly', 'Marilyn Monroe', 'Elizabeth Taylor'] },
    { id: 'romcom-p3', d: 4, t: 'Quelle actrice joue Vivian dans « Pretty Woman » ?', a: 'Julia Roberts', x: ['Meg Ryan', 'Sandra Bullock', 'Cameron Diaz'] },
    { id: 'romcom-p4', d: 4, t: 'Quel réalisateur a signé « Manhattan » et de nombreuses romances new-yorkaises ?', a: 'Woody Allen', x: ['Rob Reiner', 'James L. Brooks', 'Nora Ephron'] },
    { id: 'romcom-p5', d: 4, t: 'Quel film réunit à nouveau Jim Carrey et Kate Winslet dans une romance mélancolique ?', a: 'Eternal Sunshine of the Spotless Mind', x: ['The Truman Show', 'Little Children', 'Lost in Translation'] },
    { id: 'romcom-p6', d: 4, t: 'Dans « Love Actually », quel acteur joue le Premier ministre britannique ?', a: 'Hugh Grant', x: ['Colin Firth', 'Liam Neeson', 'Alan Rickman'] },
    { id: 'romcom-p7', d: 4, t: 'Quelle comédie romantique voit Sandra Bullock feindre des fiançailles avec un homme dans le coma ?', a: 'L\'Amour à tout prix', x: ['La Proposition', 'Miss Détective', 'Nuits blanches à Seattle'] },
    { id: 'romcom-p8', d: 4, t: 'Quel film de 2009 voit Sandra Bullock forcer son assistant à l\'épouser pour un visa ?', a: 'La Proposition', x: ['L\'Amour à tout prix', '27 robes', 'Crazy Rich Asians'] },
    { id: 'romcom-p9', d: 4, t: 'Quel film de 1999 réunit Julia Roberts et Richard Gere après « Pretty Woman » ?', a: 'Just Married ou presque', x: ['Le Mariage de mon meilleur ami', 'Coup de foudre à Notting Hill', 'Erin Brockovich'] },
    { id: 'romcom-p10', d: 4, t: 'Dans « Le Mariage de mon meilleur ami », quelle actrice tente de séparer un couple ?', a: 'Julia Roberts', x: ['Cameron Diaz', 'Meg Ryan', 'Sandra Bullock'] },
    { id: 'romcom-p11', d: 4, t: 'Quelle comédie romantique adolescente de 2018 montre un garçon écrivant des lettres d\'amour secrètes ?', a: 'À tous les garçons que j\'ai aimés', x: ['The Kissing Booth', 'Sierra Burgess', 'Toujours l\'amour'] },
    { id: 'romcom-p12', d: 4, t: 'Quel film indépendant de 2009, raconté dans le désordre, montre l\'amour de Tom pour Summer ?', a: '500 jours ensemble', x: ['Her', 'Blue Valentine', 'Garden State'] },
    { id: 'romcom-p13', d: 4, t: 'Quel acteur incarne le coach en séduction Hitch ?', a: 'Will Smith', x: ['Kevin Hart', 'Eddie Murphy', 'Chris Rock'] },
    { id: 'romcom-p14', d: 4, t: 'Quel réalisateur de Jean-Pierre Jeunet a révélé Audrey Tautou en 2001 ?', a: 'Le Fabuleux Destin d\'Amélie Poulain', x: ['Ensemble, c\'est tout', 'Hors de prix', 'Coco avant Chanel'] },
    { id: 'romcom-p15', d: 4, t: 'Quelle réalisatrice a signé « Tout peut arriver » et « Pas si simple » ?', a: 'Nancy Meyers', x: ['Nora Ephron', 'Nia Vardalos', 'Elaine May'] },
    { id: 'romcom-p16', d: 4, t: 'Quelle comédie romantique gréco-américaine de 2002 fut un immense succès indépendant ?', a: 'Mariage à la grecque', x: ['Le Mariage de mon meilleur ami', '27 robes', 'Crazy Rich Asians'] },
    { id: 'romcom-p17', d: 4, t: 'Quel film de 1993 de Nora Ephron voit un veuf et son fils chercher l\'amour à la radio ?', a: 'Nuits blanches à Seattle', x: ['Vous avez un message', 'Quand Harry rencontre Sally', 'Un jour sans fin'] },
    { id: 'romcom-p18', d: 4, t: 'Dans « Quatre mariages et un enterrement », qui joue Charles ?', a: 'Hugh Grant', x: ['Colin Firth', 'Rowan Atkinson', 'Simon Callow'] },
    { id: 'romcom-p19', d: 4, t: 'Quel film musical réunit un couple d\'adolescents Sandy et Danny dans les années 1950 ?', a: 'Grease', x: ['Hairspray', 'Dirty Dancing', 'Footloose'] },
    { id: 'romcom-p20', d: 4, t: 'Quelle comédie romantique de 2011 réunit Justin Timberlake et Mila Kunis « amis sans le sexe » ?', a: 'Sexe entre amis', x: ['Sexe entre potes', 'Crazy Stupid Love', 'Comment savoir'] },
  ]),

  ...universe('films', 'Thriller', [
    // --- Faciles (5) ---
    { id: 'thril-f1', d: 1, t: 'Quel thriller de 1991 met en scène Hannibal Lecter et Clarice Starling ?', a: 'Le Silence des agneaux', x: ['Seven', 'Zodiac', 'Shutter Island'] },
    { id: 'thril-f2', d: 1, t: 'Quel réalisateur est surnommé « le maître du suspense » ?', a: 'Alfred Hitchcock', x: ['Steven Spielberg', 'David Fincher', 'Christopher Nolan'] },
    { id: 'thril-f3', d: 1, t: 'Dans « Les Dents de la mer », quel animal terrorise une station balnéaire ?', a: 'Un requin', x: ['Un crocodile', 'Une baleine', 'Une pieuvre'] },
    { id: 'thril-f4', d: 1, t: 'Quel thriller de Spielberg oppose un automobiliste à un camion menaçant ?', a: 'Duel', x: ['Les Dents de la mer', 'Munich', 'Minority Report'] },
    { id: 'thril-f5', d: 1, t: 'Quel thriller suit deux détectives traquant un tueur inspiré des sept péchés capitaux ?', a: 'Seven', x: ['Zodiac', 'Le Silence des agneaux', 'Prisoners'] },
    // --- Moyennes (10) ---
    { id: 'thril-m1', d: 2, t: 'Quel réalisateur a signé « Seven », « Zodiac » et « Gone Girl » ?', a: 'David Fincher', x: ['Christopher Nolan', 'Denis Villeneuve', 'Martin Scorsese'] },
    { id: 'thril-m2', d: 2, t: 'Dans « Psychose », dans quel motel a lieu le célèbre meurtre sous la douche ?', a: 'le motel Bates', x: ['l\'hôtel Overlook', 'le motel Blue', 'l\'hôtel California'] },
    { id: 'thril-m3', d: 2, t: 'Quel thriller de Nolan raconte l\'histoire à l\'envers, avec un homme sans mémoire courte ?', a: 'Memento', x: ['Inception', 'Insomnia', 'Le Prestige'] },
    { id: 'thril-m4', d: 2, t: 'Quel thriller de 1999 révèle qu\'un enfant « voit des gens morts » ?', a: 'Sixième Sens', x: ['Les Autres', 'Shutter Island', 'Identity'] },
    { id: 'thril-m5', d: 2, t: 'Quel thriller de Scorsese envoie DiCaprio enquêter dans un asile sur une île ?', a: 'Shutter Island', x: ['Inception', 'Zodiac', 'Seven'] },
    { id: 'thril-m6', d: 2, t: 'Quel thriller met en scène un tueur nommé Norman Bates ?', a: 'Psychose', x: ['Halloween', 'Le Silence des agneaux', 'Seven'] },
    { id: 'thril-m7', d: 2, t: 'Dans « Le Silence des agneaux », quel acteur incarne Hannibal Lecter ?', a: 'Anthony Hopkins', x: ['Jack Nicholson', 'Al Pacino', 'Robert De Niro'] },
    { id: 'thril-m8', d: 2, t: 'Quel thriller de Nolan de 2010 explore les rêves à plusieurs niveaux ?', a: 'Inception', x: ['Interstellar', 'Memento', 'Shutter Island'] },
    { id: 'thril-m9', d: 2, t: 'Quel thriller de Hitchcock voit un homme accusé à tort poursuivi à travers le pays ?', a: 'La Mort aux trousses', x: ['Fenêtre sur cour', 'Les Oiseaux', 'Sueurs froides'] },
    { id: 'thril-m10', d: 2, t: 'Quel thriller de Hitchcock voit des oiseaux attaquer une petite ville ?', a: 'Les Oiseaux', x: ['Psychose', 'Sueurs froides', 'Fenêtre sur cour'] },
    // --- Dures (15) ---
    { id: 'thril-d1', d: 3, t: 'Quel thriller de 1974 avec Jack Nicholson se déroule dans le Los Angeles des années 1930 ?', a: 'Chinatown', x: ['L.A. Confidential', 'Le Dahlia noir', 'Heat'] },
    { id: 'thril-d2', d: 3, t: 'Quel réalisateur coréen a signé « Old Boy », thriller culte de vengeance ?', a: 'Park Chan-wook', x: ['Bong Joon-ho', 'Kim Jee-woon', 'Na Hong-jin'] },
    { id: 'thril-d3', d: 3, t: 'Quel thriller de Bong Joon-ho, Palme d\'or 2019, oppose deux familles ?', a: 'Parasite', x: ['Memories of Murder', 'The Host', 'Snowpiercer'] },
    { id: 'thril-d4', d: 3, t: 'Quel thriller de 1995 dévoile l\'identité de « Keyser Söze » ?', a: 'Usual Suspects', x: ['Seven', 'Fight Club', 'Heat'] },
    { id: 'thril-d5', d: 3, t: 'Quel thriller de Fincher révèle un narrateur créant un club de combat clandestin ?', a: 'Fight Club', x: ['Seven', 'Gone Girl', 'Zodiac'] },
    { id: 'thril-d6', d: 3, t: 'Quel thriller de 1960 tue son héroïne dès le premier tiers, choquant le public ?', a: 'Psychose', x: ['Sueurs froides', 'Les Oiseaux', 'Fenêtre sur cour'] },
    { id: 'thril-d7', d: 3, t: 'Quel thriller de Hitchcock suit un photographe immobilisé qui espionne ses voisins ?', a: 'Fenêtre sur cour', x: ['Sueurs froides', 'La Corde', 'La Mort aux trousses'] },
    { id: 'thril-d8', d: 3, t: 'Quel thriller de 1991 voit Jodie Foster affronter un tueur qui dépèce ses victimes ?', a: 'Le Silence des agneaux', x: ['Copycat', 'Seven', 'Zodiac'] },
    { id: 'thril-d9', d: 3, t: 'Quel thriller de 2007 de Fincher enquête sur un tueur en série de San Francisco ?', a: 'Zodiac', x: ['Seven', 'Memories of Murder', 'Prisoners'] },
    { id: 'thril-d10', d: 3, t: 'Quel thriller de Denis Villeneuve voit Hugh Jackman chercher sa fille enlevée ?', a: 'Prisoners', x: ['Zodiac', 'Gone Girl', 'Wind River'] },
    { id: 'thril-d11', d: 3, t: 'Quel thriller de 1992 avec Sharon Stone et un pic à glace fit scandale ?', a: 'Basic Instinct', x: ['Liaison fatale', 'Body Heat', 'Jade'] },
    { id: 'thril-d12', d: 3, t: 'Quel thriller de 1987 voit une liaison tourner au cauchemar avec Glenn Close ?', a: 'Liaison fatale', x: ['Basic Instinct', 'Proposition indécente', 'Harcèlement'] },
    { id: 'thril-d13', d: 3, t: 'Quel thriller de 1949 se déroule dans la Vienne d\'après-guerre avec Orson Welles ?', a: 'Le Troisième Homme', x: ['La Dame de Shanghai', 'Le Faucon maltais', 'Assurance sur la mort'] },
    { id: 'thril-d14', d: 3, t: 'Quel thriller de Roman Polanski voit une femme enceinte cernée par des voisins inquiétants ?', a: 'Rosemary\'s Baby', x: ['Le Locataire', 'Répulsion', 'Shutter Island'] },
    { id: 'thril-d15', d: 3, t: 'Quel thriller de 1976 voit Robert De Niro en chauffeur de taxi de plus en plus instable ?', a: 'Taxi Driver', x: ['Les Affranchis', 'Casino', 'Mean Streets'] },
    // --- Pro (20) ---
    { id: 'thril-p1', d: 4, t: 'Quel thriller de Hitchcock, avec James Stewart, traite du vertige et d\'une obsession ?', a: 'Sueurs froides', x: ['Fenêtre sur cour', 'La Corde', 'Psychose'] },
    { id: 'thril-p2', d: 4, t: 'Quel thriller coréen de 2003 de Bong Joon-ho suit une enquête sur un tueur en série ?', a: 'Memories of Murder', x: ['Parasite', 'The Chaser', 'I Saw the Devil'] },
    { id: 'thril-p3', d: 4, t: 'Quel thriller de 1995 de Michael Mann oppose De Niro à Al Pacino autour d\'un braquage ?', a: 'Heat', x: ['Le Solitaire', 'Collateral', 'Casino'] },
    { id: 'thril-p4', d: 4, t: 'Quel thriller de 1997 se déroule dans le Los Angeles corrompu des années 1950 ?', a: 'L.A. Confidential', x: ['Chinatown', 'Mulholland Drive', 'The Nice Guys'] },
    { id: 'thril-p5', d: 4, t: 'Quel thriller de 2014 de Fincher voit un mari suspecté de la disparition de sa femme ?', a: 'Gone Girl', x: ['Prisoners', 'Zodiac', 'The Girl on the Train'] },
    { id: 'thril-p6', d: 4, t: 'Quel thriller de 2006 de Scorsese oppose un flic infiltré et une taupe dans la police ?', a: 'Les Infiltrés', x: ['Heat', 'L.A. Confidential', 'Training Day'] },
    { id: 'thril-p7', d: 4, t: 'Quel thriller psychologique de 2010 voit une ballerine sombrer dans la folie ?', a: 'Black Swan', x: ['Shutter Island', 'Perfect Blue', 'Répulsion'] },
    { id: 'thril-p8', d: 4, t: 'Quel thriller français de 1955 de Clouzot terrorise avec une baignoire et un mort ?', a: 'Les Diaboliques', x: ['Le Salaire de la peur', 'Le Corbeau', 'Garde à vue'] },
    { id: 'thril-p9', d: 4, t: 'Quel thriller de 1971 lance l\'inspecteur « Dirty Harry » avec Clint Eastwood ?', a: 'L\'Inspecteur Harry', x: ['French Connection', 'Bullitt', 'Serpico'] },
    { id: 'thril-p10', d: 4, t: 'Quel thriller de 1971 propose une course-poursuite culte sous le métro de New York ?', a: 'French Connection', x: ['Bullitt', 'L\'Inspecteur Harry', 'Serpico'] },
    { id: 'thril-p11', d: 4, t: 'Quel thriller de David Lynch de 2001 plonge dans un Hollywood onirique et énigmatique ?', a: 'Mulholland Drive', x: ['Lost Highway', 'Blue Velvet', 'Shutter Island'] },
    { id: 'thril-p12', d: 4, t: 'Quel thriller de 1999 voit Matt Damon incarner un imposteur charmeur en Italie ?', a: 'Le Talentueux Mr Ripley', x: ['Gattaca', 'The Game', 'Le Mystère von Bülow'] },
    { id: 'thril-p13', d: 4, t: 'Quel thriller de 1997 de Fincher piège Michael Douglas dans un jeu grandeur nature ?', a: 'The Game', x: ['Panic Room', 'Seven', 'Fight Club'] },
    { id: 'thril-p14', d: 4, t: 'Quel thriller de 2002 de Spielberg imagine une police arrêtant les criminels avant le crime ?', a: 'Minority Report', x: ['Bienvenue à Gattaca', 'Total Recall', 'A.I.'] },
    { id: 'thril-p15', d: 4, t: 'Quel thriller coréen de 2010 de Kim Jee-woon oppose un agent à un tueur, très violent ?', a: 'J\'ai rencontré le diable', x: ['The Chaser', 'Old Boy', 'Memories of Murder'] },
    { id: 'thril-p16', d: 4, t: 'Quel thriller de 1944 de Billy Wilder est un pilier du film noir autour d\'une assurance-vie ?', a: 'Assurance sur la mort', x: ['Le Grand Sommeil', 'Laura', 'La Griffe du passé'] },
    { id: 'thril-p17', d: 4, t: 'Quel thriller de 1958 d\'Orson Welles s\'ouvre sur un plan-séquence à la frontière mexicaine ?', a: 'La Soif du mal', x: ['Le Troisième Homme', 'La Dame de Shanghai', 'Le Faucon maltais'] },
    { id: 'thril-p18', d: 4, t: 'Quel thriller de 2013 de Denis Villeneuve met en scène deux sosies inquiétants avec Jake Gyllenhaal ?', a: 'Enemy', x: ['Prisoners', 'Nightcrawler', 'Zodiac'] },
    { id: 'thril-p19', d: 4, t: 'Quel thriller de 2014 voit Jake Gyllenhaal filmer des scènes de crime la nuit ?', a: 'Night Call', x: ['Enemy', 'Prisoners', 'End of Watch'] },
    { id: 'thril-p20', d: 4, t: 'Quel thriller de Bong Joon-ho a remporté l\'Oscar du meilleur film pour 2019 ?', a: 'Parasite', x: ['Roma', '1917', 'Joker'] },
  ]),
];
