import type { Question } from '../../../core/models';

export const filmsQuestions: Question[] = [
  {
    id: 'film-1',
    theme: 'films',
    difficulty: 1,
    text: 'Qui a réalisé Titanic ?',
    answer: 'James Cameron',
    acceptable: ['cameron'],
    distractors: ['Steven Spielberg', 'Christopher Nolan', 'Ridley Scott'],
  },
  {
    id: 'film-2',
    theme: 'films',
    difficulty: 2,
    text: "Dans Le Seigneur des Anneaux, quel hobbit doit détruire l'Anneau Unique ?",
    answer: 'Frodon',
    acceptable: ['frodo', 'frodon sacquet'],
    distractors: ['Gandalf', 'Aragorn', 'Sam'],
  },
  {
    id: 'film-3',
    theme: 'films',
    difficulty: 1,
    text: 'Dans Star Wars, qui est le père de Luke Skywalker ?',
    answer: 'Dark Vador',
    acceptable: ['dark vador', 'anakin', 'darth vader', 'vador'],
    distractors: ['Obi-Wan', 'Yoda', 'Palpatine'],
  },
  {
    id: 'film-4',
    theme: 'films',
    difficulty: 2,
    text: 'Quel acteur incarne Jack Sparrow dans Pirates des Caraïbes ?',
    answer: 'Johnny Depp',
    acceptable: ['depp'],
    distractors: ['Orlando Bloom', 'Brad Pitt', 'Javier Bardem'],
  },
  {
    id: 'film-5',
    theme: 'films',
    difficulty: 3,
    text: "Quel film coréen a remporté l'Oscar du meilleur film en 2020 ?",
    answer: 'Parasite',
    distractors: ['1917', 'Joker', 'Once Upon a Time in Hollywood'],
    hints: ['Réalisé par Bong Joon-ho.'],
  },
  {
    id: 'film-6',
    theme: 'films',
    difficulty: 1,
    text: 'Dans Le Roi Lion, comment s\'appelle le père de Simba ?',
    answer: 'Mufasa',
    distractors: ['Scar', 'Rafiki', 'Zazu'],
  },
  {
    id: 'film-7',
    theme: 'films',
    difficulty: 2,
    text: 'Quel réalisateur est connu pour Inception et Interstellar ?',
    answer: 'Christopher Nolan',
    acceptable: ['nolan'],
    distractors: ['Denis Villeneuve', 'James Cameron', 'Quentin Tarantino'],
  },
  {
    id: 'film-8',
    theme: 'films',
    difficulty: 3,
    text: 'En quelle année est sorti le premier film Matrix ?',
    answer: '1999',
    distractors: ['1997', '2001', '2003'],
  },
  {
    id: 'film-9',
    theme: 'films',
    difficulty: 1,
    text: 'Dans Toy Story, quel est le jouet cow-boy ?',
    answer: 'Woody',
    distractors: ["Buzz l'Éclair", 'Rex', 'Jessie'],
  },
  {
    id: 'film-10',
    theme: 'films',
    difficulty: 2,
    text: 'Quel super-héros Marvel est interprété par Robert Downey Jr. ?',
    answer: 'Iron Man',
    distractors: ['Captain America', 'Thor', 'Hulk'],
  },
  {
    id: 'film-11',
    theme: 'films',
    difficulty: 2,
    text: 'Qui a réalisé la trilogie Le Seigneur des Anneaux ?',
    answer: 'Peter Jackson',
    distractors: ['Guillermo del Toro', 'Ridley Scott', 'Steven Spielberg'],
  },
  {
    id: 'film-12',
    theme: 'films',
    difficulty: 3,
    text: 'Qui a réalisé Pulp Fiction ?',
    answer: 'Quentin Tarantino',
    acceptable: ['tarantino'],
    distractors: ['Martin Scorsese', 'Les frères Coen', 'David Fincher'],
  },
  {
    id: 'film-13',
    theme: 'films',
    difficulty: 2,
    text: 'Dans Le Parrain, quel est le nom de la famille mafieuse principale ?',
    answer: 'Corleone',
    distractors: ['Soprano', 'Montana', 'Gambino'],
  },
  {
    id: 'film-14',
    theme: 'films',
    difficulty: 4,
    text: "Quel film a remporté le tout premier Oscar du meilleur film ?",
    answer: 'Les Ailes',
    acceptable: ['wings', 'les ailes'],
    distractors: ['Autant en emporte le vent', 'Ben-Hur', 'Casablanca'],
  },
  {
    id: 'film-15',
    theme: 'films',
    difficulty: 3,
    text: 'Quel acteur joue le rôle-titre dans Forrest Gump ?',
    answer: 'Tom Hanks',
    distractors: ['Kevin Costner', 'Tom Cruise', 'Robin Williams'],
  },
  {
    id: 'film-16',
    theme: 'films',
    difficulty: 4,
    text: 'Dans Avengers, quelle Pierre d\'Infinité se trouve sur le front de Vision ?',
    answer: "La Pierre de l'Esprit",
    acceptable: ['esprit', 'mind stone'],
    distractors: ['Pierre du Temps', 'Pierre du Pouvoir', "Pierre de l'Espace"],
  },
  {
    id: 'film-17',
    theme: 'films',
    difficulty: 3,
    text: 'Quel film de James Cameron est longtemps resté le plus rentable de tous les temps ?',
    answer: 'Avatar',
    distractors: ['Avengers: Endgame', 'Titanic', 'Star Wars VII'],
  },
  {
    id: 'film-18',
    theme: 'films',
    difficulty: 3,
    text: 'Dans Retour vers le futur, de quelle année part Marty au début ?',
    answer: '1985',
    distractors: ['1955', '1989', '1980'],
  },
  {
    id: 'film-19',
    theme: 'films',
    difficulty: 2,
    text: 'Quel studio d\'animation a créé Toy Story ?',
    answer: 'Pixar',
    distractors: ['DreamWorks', 'Disney', 'Illumination'],
  },
  {
    id: 'film-20',
    theme: 'films',
    difficulty: 4,
    text: 'Qui a composé la musique de Star Wars, Indiana Jones et Jurassic Park ?',
    answer: 'John Williams',
    distractors: ['Hans Zimmer', 'Ennio Morricone', 'Danny Elfman'],
  },
  {
    id: 'film-21',
    theme: 'films',
    difficulty: 2,
    text: 'Quel acteur incarne Don Vito Corleone dans Le Parrain ?',
    answer: 'Marlon Brando',
    distractors: ['Al Pacino', 'Robert De Niro', 'James Caan'],
  },
  {
    id: 'film-22',
    theme: 'films',
    difficulty: 3,
    text: 'Quel film de 1994 suit Andy Dufresne dans la prison de Shawshank ?',
    answer: 'Les Évadés',
    acceptable: ['les évadés', 'shawshank', 'the shawshank redemption'],
    distractors: ['La Ligne verte', 'Le Pénitencier', 'Évasion'],
  },
  {
    id: 'film-23',
    theme: 'films',
    difficulty: 1,
    text: 'Quels animaux sont recréés dans Jurassic Park ?',
    answer: 'Les dinosaures',
    acceptable: ['dinosaures'],
    distractors: ['Les mammouths', 'Les dragons', 'Les loups'],
  },
  {
    id: 'film-24',
    theme: 'films',
    difficulty: 4,
    text: 'Qui a réalisé Psychose ?',
    answer: 'Alfred Hitchcock',
    acceptable: ['hitchcock'],
    distractors: ['Stanley Kubrick', 'Orson Welles', 'Billy Wilder'],
  },
  {
    id: 'film-25',
    theme: 'films',
    difficulty: 3,
    text: 'Quel acteur joue Korben Dallas dans Le Cinquième Élément ?',
    answer: 'Bruce Willis',
    distractors: ['Mel Gibson', 'Kurt Russell', 'Harrison Ford'],
  },
  {
    id: 'film-26',
    theme: 'films',
    difficulty: 2,
    text: "Quel film Pixar met en scène les émotions dans la tête d'une fillette ?",
    answer: 'Vice-versa',
    acceptable: ['vice-versa', 'inside out'],
    distractors: ['Là-haut', 'Coco', 'Soul'],
  },
  {
    id: 'film-27',
    theme: 'films',
    difficulty: 4,
    text: 'En quelle année est sorti le tout premier Star Wars ?',
    answer: '1977',
    distractors: ['1979', '1975', '1980'],
  },
  {
    id: 'film-28',
    theme: 'films',
    difficulty: 3,
    text: 'Quel acteur incarne le Joker dans le film Joker ?',
    answer: 'Joaquin Phoenix',
    distractors: ['Heath Ledger', 'Jared Leto', 'Jack Nicholson'],
  },
  {
    id: 'film-29',
    theme: 'films',
    difficulty: 1,
    text: "Comment s'appelle l'école de sorcellerie dans Harry Potter ?",
    answer: 'Poudlard',
    acceptable: ['hogwarts'],
    distractors: ['Beauxbâtons', 'Durmstrang', 'Salem'],
  },
  {
    id: 'film-30',
    theme: 'films',
    difficulty: 4,
    text: "Quel film partage le record de 11 Oscars avec Ben-Hur et Titanic ?",
    answer: 'Le Seigneur des Anneaux : Le Retour du Roi',
    acceptable: ['le retour du roi', 'return of the king'],
    distractors: ['Avatar', 'La La Land', 'Gladiator'],
  },
];
