import type { Question, QuestionMedia } from '../../../core/models';

/**
 * Thème « Image mystère » — 100 % questions à base d'images tirées d'internet,
 * niveau difficile / pro, pensées pour des connaisseurs.
 *
 * ⚠️ Ces questions ont besoin d'une connexion : l'image est chargée à la volée.
 * C'est pourquoi ce thème est DÉSACTIVÉ par défaut (comme le blind test) et se
 * choisit explicitement sur l'écran de configuration.
 *
 * Source d'images : l'artwork officiel des Pokémon hébergé par le projet
 * PokeAPI sur GitHub — fiable et vérifié sur l'appareil. Les photos de
 * personnalités issues de Wikimedia ont été retirées : elles ne se chargeaient
 * pas dans l'application.
 *
 * Si une image ne se charge malgré tout pas (fichier renommé, hors-ligne…),
 * deux filets de sécurité : en jeu, la question est automatiquement remplacée
 * (même joueur, +1 au total) ; et l'écran « Vérifier les images » (Réglages)
 * liste d'un coup d'œil celles qui ne s'affichent pas.
 *
 * Règles maison respectées : aucune parenthèse dans les intitulés / réponses ;
 * les propositions d'une même question sont homogènes (ici : soit des noms de
 * créatures, soit des pseudos, soit des noms complets de personnes).
 */

/** Artwork officiel d'un Pokémon par numéro national (PokeAPI, hébergé GitHub). */
const poke = (n: number): QuestionMedia => ({
  type: 'image',
  uri: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${n}.png`,
});

const POKE = 'Quel est ce Pokémon ?';

export const imagesQuestions: Question[] = [
  // ---------------------------------------------------------------------------
  // Pokémon — artwork officiel (source fiable). 40 questions.
  // ---------------------------------------------------------------------------
  { id: 'img-1', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Absol', distractors: ['Mangriff', 'Séviper', 'Démolosse'], media: poke(359), text_en: 'Which Pokemon is this?', answer_en: 'Absol', distractors_en: ['Zangoose','Seviper','Houndoom'] },
  { id: 'img-2', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Spiritomb', distractors: ['Sinistrail', 'Tutétékri', 'Magirêve'], media: poke(442), text_en: 'Which Pokemon is this?', answer_en: 'Spiritomb', distractors_en: ['Dhelmise','Runerigus','Mismagius'] },
  { id: 'img-3', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Mimiqui', distractors: ['Bekaglaçon', 'Morpeko', 'Trousselin'], media: poke(778), text_en: 'Which Pokemon is this?', answer_en: 'Mimikyu', distractors_en: ['Eiscue','Morpeko','Klefki'] },
  { id: 'img-4', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Zorua', distractors: ['Zoroark', 'Noctali', 'Magirêve'], media: poke(570), text_en: 'Which Pokemon is this?', answer_en: 'Zorua', distractors_en: ['Zoroark','Umbreon','Mismagius'] },
  { id: 'img-5', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Nymphali', distractors: ['Noctali', 'Charmilly', 'Mysdibule'], media: poke(700), text_en: 'Which Pokemon is this?', answer_en: 'Sylveon', distractors_en: ['Umbreon','Slurpuff','Mawile'] },
  { id: 'img-6', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Métalosse', distractors: ['Drattak', 'Trioxhydre', 'Carchacrok'], media: poke(376), text_en: 'Which Pokemon is this?', answer_en: 'Metagross', distractors_en: ['Salamence','Hydreigon','Garchomp'] },
  { id: 'img-7', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Carchacrok', distractors: ['Drattak', 'Hydragon', 'Tyranocif'], media: poke(445), text_en: 'Which Pokemon is this?', answer_en: 'Garchomp', distractors_en: ['Salamence','Dracovish','Tyranitar'] },
  { id: 'img-8', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Tyranocif', distractors: ['Démolosse', 'Métalosse', 'Golemastoc'], media: poke(248), text_en: 'Which Pokemon is this?', answer_en: 'Tyranitar', distractors_en: ['Houndoom','Metagross','Golurk'] },
  { id: 'img-9', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Noctali', distractors: ['Nymphali', 'Zorua', 'Dimoret'], media: poke(197), text_en: 'Which Pokemon is this?', answer_en: 'Umbreon', distractors_en: ['Sylveon','Zorua','Weavile'] },
  { id: 'img-10', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Ectoplasma', distractors: ['Sinistrail', 'Noctunoir', 'Magirêve'], media: poke(94), text_en: 'Which Pokemon is this?', answer_en: 'Gengar', distractors_en: ['Dhelmise','Dusknoir','Mismagius'] },
  { id: 'img-11', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Lucario', distractors: ['Cizayox', 'Scalpereur', 'Berserkatt'], media: poke(448), text_en: 'Which Pokemon is this?', answer_en: 'Lucario', distractors_en: ['Scizor','Kingambit','Perrserker'] },
  { id: 'img-12', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Dimoret', distractors: ['Noctali', 'Berserkatt', 'Mangriff'], media: poke(461), text_en: 'Which Pokemon is this?', answer_en: 'Weavile', distractors_en: ['Umbreon','Perrserker','Zangoose'] },
  { id: 'img-13', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Girafarig', distractors: ['Farigiraf', 'Cerfrousse', 'Cadoizo'], media: poke(203), text_en: 'Which Pokemon is this?', answer_en: 'Girafarig', distractors_en: ['Farigiraf','Stantler','Delibird'] },
  { id: 'img-14', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Caratroc', distractors: ['Corayon', 'Relicanth', 'Tropius'], media: poke(213), text_en: 'Which Pokemon is this?', answer_en: 'Shuckle', distractors_en: ['Corsola','Relicanth','Tropius'] },
  { id: 'img-15', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Corayon', distractors: ['Caratroc', 'Relicanth', 'Cadoizo'], media: poke(222), text_en: 'Which Pokemon is this?', answer_en: 'Corsola', distractors_en: ['Shuckle','Relicanth','Delibird'] },
  { id: 'img-16', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Cadoizo', distractors: ['Pijako', 'Corayon', 'Cerfrousse'], media: poke(225), text_en: 'Which Pokemon is this?', answer_en: 'Delibird', distractors_en: ['Chatot','Corsola','Stantler'] },
  { id: 'img-17', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Cerfrousse', distractors: ['Girafarig', 'Tropius', 'Mangriff'], media: poke(234), text_en: 'Which Pokemon is this?', answer_en: 'Stantler', distractors_en: ['Girafarig','Tropius','Zangoose'] },
  { id: 'img-18', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Queulorior', distractors: ['Pijako', 'Vortente', 'Relicanth'], media: poke(235), text_en: 'Which Pokemon is this?', answer_en: 'Smeargle', distractors_en: ['Chatot','Carnivine','Relicanth'] },
  { id: 'img-19', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Ténéfix', distractors: ['Mysdibule', 'Magirêve', 'Berserkatt'], media: poke(302), text_en: 'Which Pokemon is this?', answer_en: 'Sableye', distractors_en: ['Mawile','Mismagius','Perrserker'] },
  { id: 'img-20', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Mysdibule', distractors: ['Ténéfix', 'Mangriff', 'Charmilly'], media: poke(303), text_en: 'Which Pokemon is this?', answer_en: 'Mawile', distractors_en: ['Sableye','Zangoose','Slurpuff'] },
  { id: 'img-21', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Mangriff', distractors: ['Séviper', 'Ténéfix', 'Cerfrousse'], media: poke(335), text_en: 'Which Pokemon is this?', answer_en: 'Zangoose', distractors_en: ['Seviper','Sableye','Stantler'] },
  { id: 'img-22', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Séviper', distractors: ['Mangriff', 'Venalgue', 'Kravarech'], media: poke(336), text_en: 'Which Pokemon is this?', answer_en: 'Seviper', distractors_en: ['Zangoose','Skrelp','Dragalge'] },
  { id: 'img-23', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Tropius', distractors: ['Caratroc', 'Relicanth', 'Corayon'], media: poke(357), text_en: 'Which Pokemon is this?', answer_en: 'Tropius', distractors_en: ['Shuckle','Relicanth','Corsola'] },
  { id: 'img-24', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Relicanth', distractors: ['Caratroc', 'Corayon', 'Tropius'], media: poke(369), text_en: 'Which Pokemon is this?', answer_en: 'Relicanth', distractors_en: ['Shuckle','Corsola','Tropius'] },
  { id: 'img-25', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Magirêve', distractors: ['Sinistrail', 'Tutétékri', 'Noctunoir'], media: poke(429), text_en: 'Which Pokemon is this?', answer_en: 'Mismagius', distractors_en: ['Dhelmise','Runerigus','Dusknoir'] },
  { id: 'img-26', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Pijako', distractors: ['Cadoizo', 'Queulorior', 'Vortente'], media: poke(441), text_en: 'Which Pokemon is this?', answer_en: 'Chatot', distractors_en: ['Delibird','Smeargle','Carnivine'] },
  { id: 'img-27', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Vortente', distractors: ['Venalgue', 'Kravarech', 'Queulorior'], media: poke(455), text_en: 'Which Pokemon is this?', answer_en: 'Carnivine', distractors_en: ['Skrelp','Dragalge','Smeargle'] },
  { id: 'img-28', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Fragilady', distractors: ['Charmilly', 'Mysdibule', 'Nymphali'], media: poke(549), text_en: 'Which Pokemon is this?', answer_en: 'Lilligant', distractors_en: ['Slurpuff','Mawile','Sylveon'] },
  { id: 'img-29', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Golemastoc', distractors: ['Ferdeter', 'Tomberro', 'Scalpereur'], media: poke(623), text_en: 'Which Pokemon is this?', answer_en: 'Golurk', distractors_en: ['Ferdeter','Houndstone','Kingambit'] },
  { id: 'img-30', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Golgopathe', distractors: ['Corvaillus', 'Kravarech', 'Venalgue'], media: poke(689), text_en: 'Which Pokemon is this?', answer_en: 'Barbaracle', distractors_en: ['Corviknight','Dragalge','Skrelp'] },
  { id: 'img-31', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Kravarech', distractors: ['Venalgue', 'Hydragon', 'Séviper'], media: poke(691), text_en: 'Which Pokemon is this?', answer_en: 'Dragalge', distractors_en: ['Skrelp','Dracovish','Seviper'] },
  { id: 'img-32', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Trousselin', distractors: ['Charmilly', 'Mimiqui', 'Morpeko'], media: poke(707), text_en: 'Which Pokemon is this?', answer_en: 'Klefki', distractors_en: ['Slurpuff','Mimikyu','Morpeko'] },
  { id: 'img-33', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Sinistrail', distractors: ['Magirêve', 'Tutétékri', 'Noctunoir'], media: poke(781), text_en: 'Which Pokemon is this?', answer_en: 'Dhelmise', distractors_en: ['Mismagius','Runerigus','Dusknoir'] },
  { id: 'img-34', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Berserkatt', distractors: ['Dimoret', 'Mangriff', 'Scalpereur'], media: poke(863), text_en: 'Which Pokemon is this?', answer_en: 'Perrserker', distractors_en: ['Weavile','Zangoose','Kingambit'] },
  { id: 'img-35', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Tutétékri', distractors: ['Sinistrail', 'Magirêve', 'Spiritomb'], media: poke(867), text_en: 'Which Pokemon is this?', answer_en: 'Runerigus', distractors_en: ['Dhelmise','Mismagius','Spiritomb'] },
  { id: 'img-36', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Bekaglaçon', distractors: ['Morpeko', 'Mimiqui', 'Bargantua'], media: poke(875), text_en: 'Which Pokemon is this?', answer_en: 'Eiscue', distractors_en: ['Morpeko','Mimikyu','Dondozo'] },
  { id: 'img-37', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Morpeko', distractors: ['Bekaglaçon', 'Trousselin', 'Mimiqui'], media: poke(877), text_en: 'Which Pokemon is this?', answer_en: 'Morpeko', distractors_en: ['Eiscue','Klefki','Mimikyu'] },
  { id: 'img-38', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Galvagon', distractors: ['Hydragon', 'Gigansel', 'Nigirigon'], media: poke(880), text_en: 'Which Pokemon is this?', answer_en: 'Dracozolt', distractors_en: ['Dracovish','Garganacl','Nigirigon'] },
  { id: 'img-39', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Gigansel', distractors: ['Forgelina', 'Ferdeter', 'Golemastoc'], media: poke(934), text_en: 'Which Pokemon is this?', answer_en: 'Garganacl', distractors_en: ['Forgelina','Ferdeter','Golurk'] },
  { id: 'img-40', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Farigiraf', distractors: ['Girafarig', 'Cerfrousse', 'Deusolourdo'], media: poke(981), text_en: 'Which Pokemon is this?', answer_en: 'Farigiraf', distractors_en: ['Girafarig','Stantler','Dudunsparce'] },

  // ---------------------------------------------------------------------------
  // Pokémon (suite) — artwork officiel PokeAPI, fiable. 66 questions.
  // ---------------------------------------------------------------------------
  { id: 'img-41', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Florizarre', distractors: ['Tutétékri', 'Pingoléon', 'Giratina'], media: poke(3), text_en: 'Which Pokemon is this?', answer_en: 'Venusaur', distractors_en: ['Runerigus','Empoleon','Giratina'] },
  { id: 'img-42', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Dracaufeu', distractors: ['Gardevoir', 'Trioxhydre', 'Spiritomb'], media: poke(6), text_en: 'Which Pokemon is this?', answer_en: 'Charizard', distractors_en: ['Gardevoir','Hydreigon','Spiritomb'] },
  { id: 'img-43', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Tortank', distractors: ['Nostenfer', 'Galvagon', 'Galeking'], media: poke(9), text_en: 'Which Pokemon is this?', answer_en: 'Blastoise', distractors_en: ['Crobat','Dracozolt','Aggron'] },
  { id: 'img-44', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Pikachu', distractors: ['Latios', 'Scarhino', 'Deoxys'], media: poke(25), text_en: 'Which Pokemon is this?', answer_en: 'Pikachu', distractors_en: ['Latios','Heracross','Deoxys'] },
  { id: 'img-45', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Raichu', distractors: ['Ténéfix', 'Aquali', 'Braségali'], media: poke(26), text_en: 'Which Pokemon is this?', answer_en: 'Raichu', distractors_en: ['Sableye','Vaporeon','Blaziken'] },
  { id: 'img-46', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Arcanin', distractors: ['Absol', 'Libégon', 'Mew'], media: poke(59), text_en: 'Which Pokemon is this?', answer_en: 'Arcanine', distractors_en: ['Absol','Flygon','Mew'] },
  { id: 'img-47', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Alakazam', distractors: ['Arcanin', 'Aquali', 'Élekable'], media: poke(65), text_en: 'Which Pokemon is this?', answer_en: 'Alakazam', distractors_en: ['Arcanine','Vaporeon','Electivire'] },
  { id: 'img-48', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Mackogneur', distractors: ['Mimiqui', 'Zorua', 'Aquali'], media: poke(68), text_en: 'Which Pokemon is this?', answer_en: 'Machamp', distractors_en: ['Mimikyu','Zorua','Vaporeon'] },
  { id: 'img-49', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Rhinoféros', distractors: ['Bekaglaçon', 'Simiabraz', 'Kravarech'], media: poke(112), text_en: 'Which Pokemon is this?', answer_en: 'Rhydon', distractors_en: ['Eiscue','Infernape','Dragalge'] },
  { id: 'img-50', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Kangourex', distractors: ['Relicanth', 'Magirêve', 'Morpeko'], media: poke(115), text_en: 'Which Pokemon is this?', answer_en: 'Kangaskhan', distractors_en: ['Relicanth','Mismagius','Morpeko'] },
  { id: 'img-51', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Insécateur', distractors: ['Lugia', 'Queulorior', 'Tropius'], media: poke(123), text_en: 'Which Pokemon is this?', answer_en: 'Scyther', distractors_en: ['Lugia','Smeargle','Tropius'] },
  { id: 'img-52', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Scarabrute', distractors: ['Méganium', 'Insécateur', 'Corayon'], media: poke(127), text_en: 'Which Pokemon is this?', answer_en: 'Pinsir', distractors_en: ['Meganium','Scyther','Corsola'] },
  { id: 'img-53', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Léviator', distractors: ['Drattak', 'Noarfang', 'Trousselin'], media: poke(130), text_en: 'Which Pokemon is this?', answer_en: 'Gyarados', distractors_en: ['Salamence','Noctowl','Klefki'] },
  { id: 'img-54', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Lokhlass', distractors: ['Kangourex', 'Caratroc', 'Braségali'], media: poke(131), text_en: 'Which Pokemon is this?', answer_en: 'Lapras', distractors_en: ['Kangaskhan','Shuckle','Blaziken'] },
  { id: 'img-55', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Évoli', distractors: ['Celebi', 'Arceus', 'Galeking'], media: poke(133), text_en: 'Which Pokemon is this?', answer_en: 'Eevee', distractors_en: ['Celebi','Arceus','Aggron'] },
  { id: 'img-56', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Aquali', distractors: ['Spiritomb', 'Gardevoir', 'Évoli'], media: poke(134), text_en: 'Which Pokemon is this?', answer_en: 'Vaporeon', distractors_en: ['Spiritomb','Gardevoir','Eevee'] },
  { id: 'img-57', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Voltali', distractors: ['Scarabrute', 'Cerfrousse', 'Drattak'], media: poke(135), text_en: 'Which Pokemon is this?', answer_en: 'Jolteon', distractors_en: ['Pinsir','Stantler','Salamence'] },
  { id: 'img-58', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Pyroli', distractors: ['Trousselin', 'Reshiram', 'Corayon'], media: poke(136), text_en: 'Which Pokemon is this?', answer_en: 'Flareon', distractors_en: ['Klefki','Reshiram','Corsola'] },
  { id: 'img-59', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Ptéra', distractors: ['Zekrom', 'Girafarig', 'Démolosse'], media: poke(142), text_en: 'Which Pokemon is this?', answer_en: 'Aerodactyl', distractors_en: ['Zekrom','Girafarig','Houndoom'] },
  { id: 'img-60', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Ronflex', distractors: ['Pijako', 'Florizarre', 'Kangourex'], media: poke(143), text_en: 'Which Pokemon is this?', answer_en: 'Snorlax', distractors_en: ['Chatot','Venusaur','Kangaskhan'] },
  { id: 'img-61', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Dracolosse', distractors: ['Latias', 'Magirêve', 'Rhinoféros'], media: poke(149), text_en: 'Which Pokemon is this?', answer_en: 'Dragonite', distractors_en: ['Latias','Mismagius','Rhydon'] },
  { id: 'img-62', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Mewtwo', distractors: ['Sinistrail', 'Nostenfer', 'Mysdibule'], media: poke(150), text_en: 'Which Pokemon is this?', answer_en: 'Mewtwo', distractors_en: ['Dhelmise','Crobat','Mawile'] },
  { id: 'img-63', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Mew', distractors: ['Mangriff', 'Reshiram', 'Kravarech'], media: poke(151), text_en: 'Which Pokemon is this?', answer_en: 'Mew', distractors_en: ['Zangoose','Reshiram','Dragalge'] },
  { id: 'img-64', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Méganium', distractors: ['Scarabrute', 'Reshiram', 'Tropius'], media: poke(154), text_en: 'Which Pokemon is this?', answer_en: 'Meganium', distractors_en: ['Pinsir','Reshiram','Tropius'] },
  { id: 'img-65', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Héricendre', distractors: ['Kangourex', 'Gigansel', 'Victini'], media: poke(155), text_en: 'Which Pokemon is this?', answer_en: 'Cyndaquil', distractors_en: ['Kangaskhan','Garganacl','Victini'] },
  { id: 'img-66', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Typhlosion', distractors: ['Torterra', 'Arcanin', 'Scarhino'], media: poke(157), text_en: 'Which Pokemon is this?', answer_en: 'Typhlosion', distractors_en: ['Torterra','Arcanine','Heracross'] },
  { id: 'img-67', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Aligatueur', distractors: ['Dimoret', 'Mew', 'Arceus'], media: poke(160), text_en: 'Which Pokemon is this?', answer_en: 'Feraligatr', distractors_en: ['Weavile','Mew','Arceus'] },
  { id: 'img-68', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Noarfang', distractors: ['Bekaglaçon', 'Gigansel', 'Simiabraz'], media: poke(164), text_en: 'Which Pokemon is this?', answer_en: 'Noctowl', distractors_en: ['Eiscue','Garganacl','Infernape'] },
  { id: 'img-69', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Nostenfer', distractors: ['Mysdibule', 'Bekaglaçon', 'Dracolosse'], media: poke(169), text_en: 'Which Pokemon is this?', answer_en: 'Crobat', distractors_en: ['Mawile','Eiscue','Dragonite'] },
  { id: 'img-70', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Pharamp', distractors: ['Reshiram', 'Ho-Oh', 'Absol'], media: poke(181), text_en: 'Which Pokemon is this?', answer_en: 'Ampharos', distractors_en: ['Reshiram','Ho-Oh','Absol'] },
  { id: 'img-71', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Mentali', distractors: ['Typhlosion', 'Tutétékri', 'Gigansel'], media: poke(196), text_en: 'Which Pokemon is this?', answer_en: 'Espeon', distractors_en: ['Typhlosion','Runerigus','Garganacl'] },
  { id: 'img-72', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Cizayox', distractors: ['Celebi', 'Laggron', 'Aligatueur'], media: poke(212), text_en: 'Which Pokemon is this?', answer_en: 'Scizor', distractors_en: ['Celebi','Swampert','Feraligatr'] },
  { id: 'img-73', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Scarhino', distractors: ['Laggron', 'Golemastoc', 'Fragilady'], media: poke(214), text_en: 'Which Pokemon is this?', answer_en: 'Heracross', distractors_en: ['Swampert','Golurk','Lilligant'] },
  { id: 'img-74', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Démolosse', distractors: ['Métalosse', 'Absol', 'Aligatueur'], media: poke(229), text_en: 'Which Pokemon is this?', answer_en: 'Houndoom', distractors_en: ['Metagross','Absol','Feraligatr'] },
  { id: 'img-75', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Lugia', distractors: ['Scarabrute', 'Braségali', 'Spiritomb'], media: poke(249), text_en: 'Which Pokemon is this?', answer_en: 'Lugia', distractors_en: ['Pinsir','Blaziken','Spiritomb'] },
  { id: 'img-76', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Ho-Oh', distractors: ['Tyranocif', 'Golemastoc', 'Corayon'], media: poke(250), text_en: 'Which Pokemon is this?', answer_en: 'Ho-Oh', distractors_en: ['Tyranitar','Golurk','Corsola'] },
  { id: 'img-77', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Celebi', distractors: ['Simiabraz', 'Mew', 'Lugia'], media: poke(251), text_en: 'Which Pokemon is this?', answer_en: 'Celebi', distractors_en: ['Infernape','Mew','Lugia'] },
  { id: 'img-78', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Jungko', distractors: ['Ronflex', 'Élekable', 'Cizayox'], media: poke(254), text_en: 'Which Pokemon is this?', answer_en: 'Sceptile', distractors_en: ['Snorlax','Electivire','Scizor'] },
  { id: 'img-79', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Braségali', distractors: ['Mewtwo', 'Ronflex', 'Métalosse'], media: poke(257), text_en: 'Which Pokemon is this?', answer_en: 'Blaziken', distractors_en: ['Mewtwo','Snorlax','Metagross'] },
  { id: 'img-80', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Laggron', distractors: ['Ectoplasma', 'Mew', 'Kravarech'], media: poke(260), text_en: 'Which Pokemon is this?', answer_en: 'Swampert', distractors_en: ['Gengar','Mew','Dragalge'] },
  { id: 'img-81', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Gardevoir', distractors: ['Mysdibule', 'Pijako', 'Caratroc'], media: poke(282), text_en: 'Which Pokemon is this?', answer_en: 'Gardevoir', distractors_en: ['Mawile','Chatot','Shuckle'] },
  { id: 'img-82', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Monaflèmit', distractors: ['Nymphali', 'Scarhino', 'Aquali'], media: poke(289), text_en: 'Which Pokemon is this?', answer_en: 'Slaking', distractors_en: ['Sylveon','Heracross','Vaporeon'] },
  { id: 'img-83', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Galeking', distractors: ['Démolosse', 'Monaflèmit', 'Libégon'], media: poke(306), text_en: 'Which Pokemon is this?', answer_en: 'Aggron', distractors_en: ['Houndoom','Slaking','Flygon'] },
  { id: 'img-84', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Sharpedo', distractors: ['Séviper', 'Laggron', 'Gigansel'], media: poke(319), text_en: 'Which Pokemon is this?', answer_en: 'Sharpedo', distractors_en: ['Seviper','Swampert','Garganacl'] },
  { id: 'img-85', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Libégon', distractors: ['Aligatueur', 'Ptéra', 'Drattak'], media: poke(330), text_en: 'Which Pokemon is this?', answer_en: 'Flygon', distractors_en: ['Feraligatr','Aerodactyl','Salamence'] },
  { id: 'img-86', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Drattak', distractors: ['Gigansel', 'Pijako', 'Élekable'], media: poke(373), text_en: 'Which Pokemon is this?', answer_en: 'Salamence', distractors_en: ['Garganacl','Chatot','Electivire'] },
  { id: 'img-87', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Latias', distractors: ['Kravarech', 'Zorua', 'Tortank'], media: poke(380), text_en: 'Which Pokemon is this?', answer_en: 'Latias', distractors_en: ['Dragalge','Zorua','Blastoise'] },
  { id: 'img-88', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Latios', distractors: ['Tyranocif', 'Scarhino', 'Mysdibule'], media: poke(381), text_en: 'Which Pokemon is this?', answer_en: 'Latios', distractors_en: ['Tyranitar','Heracross','Mawile'] },
  { id: 'img-89', theme: 'images', universe: 'Pokémon en images', difficulty: 2, text: POKE, answer: 'Rayquaza', distractors: ['Dracolosse', 'Simiabraz', 'Mew'], media: poke(384), text_en: 'Which Pokemon is this?', answer_en: 'Rayquaza', distractors_en: ['Dragonite','Infernape','Mew'] },
  { id: 'img-90', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Jirachi', distractors: ['Golgopathe', 'Ho-Oh', 'Pharamp'], media: poke(385), text_en: 'Which Pokemon is this?', answer_en: 'Jirachi', distractors_en: ['Barbaracle','Ho-Oh','Ampharos'] },
  { id: 'img-91', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Deoxys', distractors: ['Phyllali', 'Vortente', 'Démolosse'], media: poke(386), text_en: 'Which Pokemon is this?', answer_en: 'Deoxys', distractors_en: ['Leafeon','Carnivine','Houndoom'] },
  { id: 'img-92', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Torterra', distractors: ['Girafarig', 'Victini', 'Arceus'], media: poke(389), text_en: 'Which Pokemon is this?', answer_en: 'Torterra', distractors_en: ['Girafarig','Victini','Arceus'] },
  { id: 'img-93', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Simiabraz', distractors: ['Vortente', 'Ténéfix', 'Braségali'], media: poke(392), text_en: 'Which Pokemon is this?', answer_en: 'Infernape', distractors_en: ['Carnivine','Sableye','Blaziken'] },
  { id: 'img-94', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Pingoléon', distractors: ['Zekrom', 'Carchacrok', 'Jungko'], media: poke(395), text_en: 'Which Pokemon is this?', answer_en: 'Empoleon', distractors_en: ['Zekrom','Garchomp','Sceptile'] },
  { id: 'img-95', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Élekable', distractors: ['Sinistrail', 'Deoxys', 'Arcanin'], media: poke(466), text_en: 'Which Pokemon is this?', answer_en: 'Electivire', distractors_en: ['Dhelmise','Deoxys','Arcanine'] },
  { id: 'img-96', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Phyllali', distractors: ['Dimoret', 'Pyroli', 'Libégon'], media: poke(470), text_en: 'Which Pokemon is this?', answer_en: 'Leafeon', distractors_en: ['Weavile','Flareon','Flygon'] },
  { id: 'img-97', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Givrali', distractors: ['Élekable', 'Zoroark', 'Sinistrail'], media: poke(471), text_en: 'Which Pokemon is this?', answer_en: 'Glaceon', distractors_en: ['Electivire','Zoroark','Dhelmise'] },
  { id: 'img-98', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Dialga', distractors: ['Pijako', 'Vortente', 'Pyroli'], media: poke(483), text_en: 'Which Pokemon is this?', answer_en: 'Dialga', distractors_en: ['Chatot','Carnivine','Flareon'] },
  { id: 'img-99', theme: 'images', universe: 'Pokémon en images', difficulty: 3, text: POKE, answer: 'Palkia', distractors: ['Zorua', 'Vortente', 'Lokhlass'], media: poke(484), text_en: 'Which Pokemon is this?', answer_en: 'Palkia', distractors_en: ['Zorua','Carnivine','Lapras'] },
  { id: 'img-100', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Giratina', distractors: ['Florizarre', 'Alakazam', 'Golgopathe'], media: poke(487), text_en: 'Which Pokemon is this?', answer_en: 'Giratina', distractors_en: ['Venusaur','Alakazam','Barbaracle'] },
  { id: 'img-101', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Arceus', distractors: ['Jirachi', 'Mysdibule', 'Aligatueur'], media: poke(493), text_en: 'Which Pokemon is this?', answer_en: 'Arceus', distractors_en: ['Jirachi','Mawile','Feraligatr'] },
  { id: 'img-102', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Victini', distractors: ['Voltali', 'Héricendre', 'Palkia'], media: poke(494), text_en: 'Which Pokemon is this?', answer_en: 'Victini', distractors_en: ['Jolteon','Cyndaquil','Palkia'] },
  { id: 'img-103', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Zoroark', distractors: ['Farigiraf', 'Mimiqui', 'Celebi'], media: poke(571), text_en: 'Which Pokemon is this?', answer_en: 'Zoroark', distractors_en: ['Farigiraf','Mimikyu','Celebi'] },
  { id: 'img-104', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Trioxhydre', distractors: ['Arceus', 'Héricendre', 'Fragilady'], media: poke(635), text_en: 'Which Pokemon is this?', answer_en: 'Hydreigon', distractors_en: ['Arceus','Cyndaquil','Lilligant'] },
  { id: 'img-105', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Reshiram', distractors: ['Élekable', 'Pingoléon', 'Caratroc'], media: poke(643), text_en: 'Which Pokemon is this?', answer_en: 'Reshiram', distractors_en: ['Electivire','Empoleon','Shuckle'] },
  { id: 'img-106', theme: 'images', universe: 'Pokémon en images', difficulty: 4, text: POKE, answer: 'Zekrom', distractors: ['Mangriff', 'Évoli', 'Caratroc'], media: poke(644), text_en: 'Which Pokemon is this?', answer_en: 'Zekrom', distractors_en: ['Zangoose','Eevee','Shuckle'] },
];
