import { universe } from './_build';

// Nouveau thème « Références Internet » : mèmes, virales, plateformes et
// culture web. Attention, ça vieillit vite — on privilégie les références
// déjà bien installées.
export const internetQuestions = [
  ...universe('internet', 'Mèmes & viral', [
  // --- Faciles (5) ---
  { id: 'net-f1', d: 1, t: 'Quel réseau social est connu pour ses vidéos courtes et son fil « Pour toi » ?', a: 'TikTok', x: ['LinkedIn', 'Pinterest', 'Reddit'] },
  { id: 'net-f2', d: 1, t: 'Comment appelle-t-on une image humoristique qui se propage massivement sur internet ?', a: 'Un mème', acc: ['meme', 'mème'], x: ['Un spam', 'Un cookie', 'Un pixel'] },
  { id: 'net-f3', d: 1, t: 'Sur YouTube, quel bouton clique-t-on pour soutenir une vidéo qu\'on aime ?', a: 'J\'aime', acc: ["j'aime", 'like', 'pouce bleu'], x: ['Partager', 'S\'abonner', 'Signaler'] },
  { id: 'net-f4', d: 1, t: 'Quelle plateforme de diffusion en direct de jeux vidéo appartient à Amazon ?', a: 'Twitch', x: ['YouTube Gaming', 'Kick', 'Discord'] },
  { id: 'net-f5', d: 1, t: 'Que dit-on d\'une vidéo qui rencontre un énorme succès soudain sur internet ?', a: 'Elle devient virale', acc: ['virale', 'buzz', 'viral'], x: ['Elle devient payante', 'Elle devient privée', 'Elle est supprimée'] },

  // --- Moyennes (10) ---
  { id: 'net-m1', d: 2, t: 'Quel chanteur sud-coréen a explosé en 2012 avec « Gangnam Style » ?', a: 'PSY', x: ['Rain', 'G-Dragon', 'Taeyang'] },
  { id: 'net-m2', d: 2, t: 'Quel site de discussion s\'organise en « subreddits » et fonctionne aux votes ?', a: 'Reddit', x: ['Digg', 'Quora', '4chan'] },
  { id: 'net-m3', d: 2, t: 'Comment s\'appelle la grenouille verte devenue un célèbre mème ?', a: 'Pepe the Frog', acc: ['pepe', 'pepe the frog'], x: ['Kermit', 'Crazy Frog', 'Keroppi'] },
  { id: 'net-m4', d: 2, t: 'Quel défi viral de 2014 consistait à se verser un seau d\'eau glacée pour une cause ?', a: 'L\'Ice Bucket Challenge', acc: ['ice bucket challenge', 'ice bucket'], x: ['Le Mannequin Challenge', 'Le Harlem Shake', 'Le Kiki Challenge'] },
  { id: 'net-m5', d: 2, t: 'Quelle mode virale demandait de rester totalement figé pendant qu\'une caméra circule ?', a: 'Le Mannequin Challenge', acc: ['mannequin challenge'], x: ['Le Harlem Shake', 'La Macarena', 'Le Floss'] },
  { id: 'net-m6', d: 2, t: 'Quel format d\'image animée sans son est partout dans les commentaires ?', a: 'Le GIF', acc: ['gif'], x: ['Le PNG', 'Le MP3', 'Le PDF'] },
  { id: 'net-m7', d: 2, t: 'Comment appelle-t-on quelqu\'un qui provoque exprès pour semer la discorde en ligne ?', a: 'Un troll', x: ['Un noob', 'Un lurker', 'Un admin'] },
  { id: 'net-m8', d: 2, t: 'Quel chat grincheux est devenu une star des mèmes sous le nom de « Grumpy Cat » ?', a: 'Grumpy Cat', acc: ['grumpy cat'], x: ['Nyan Cat', 'Keyboard Cat', 'Lil Bub'] },
  { id: 'net-m9', d: 2, t: 'Quel site de tchat vidéo mettait en relation deux inconnus totalement au hasard ?', a: 'Chatroulette', x: ['Omegle', 'Skype', 'FaceTime'] },
  { id: 'net-m10', d: 2, t: 'Comment appelle-t-on les créateurs qui vivent de leur audience sur les réseaux sociaux ?', a: 'Des influenceurs', acc: ['influenceurs', 'influenceur'], x: ['Des modérateurs', 'Des développeurs', 'Des annonceurs'] },

  // --- Dures (15) ---
  { id: 'net-d1', d: 3, t: 'De quel jeu vidéo vient la phrase-mème « the cake is a lie » ?', a: 'Portal', x: ['Half-Life', 'Doom', 'BioShock'] },
  { id: 'net-d2', d: 3, t: 'Quelle réplique de Dragon Ball Z est devenue un mème sur la puissance ?', a: 'It\'s over 9000', acc: ['over 9000', '9000', 'plus de 9000'], x: ['Kamehameha', 'This is Sparta', 'Hasta la vista'] },
  { id: 'net-d3', d: 3, t: 'De quel film vient le mème « This is Sparta » ?', a: '300', x: ['Gladiator', 'Troie', 'Le Choc des Titans'] },
  { id: 'net-d4', d: 3, t: 'Quel site de partage de vidéos a été racheté par Google en 2006 ?', a: 'YouTube', x: ['Dailymotion', 'Vimeo', 'Twitch'] },
  { id: 'net-d5', d: 3, t: 'Quel format vertical éphémère, lancé par Snapchat, a été copié par Instagram ?', a: 'Les stories', acc: ['stories', 'story'], x: ['Les reels', 'Les shorts', 'Les lives'] },
  { id: 'net-d6', d: 3, t: 'De quel dessin animé vient le mème du texte en « MaJuScUlEs alternées » ?', a: 'Bob l\'éponge', acc: ['bob l\'eponge', 'spongebob'], x: ['Les Simpson', 'South Park', 'Rick et Morty'] },
  { id: 'net-d7', d: 3, t: 'Quel forum anonyme est à l\'origine de nombreux mèmes et du collectif Anonymous ?', a: '4chan', x: ['Reddit', 'Tumblr', 'Something Awful'] },
  { id: 'net-d8', d: 3, t: 'Comment appelle-t-on le fait de divulguer les informations privées de quelqu\'un en ligne ?', a: 'Le doxxing', acc: ['doxxing', 'dox', 'doxing'], x: ['Le phishing', 'Le catfishing', 'Le ghosting'] },
  { id: 'net-d9', d: 3, t: 'Comment appelle-t-on le fait de séduire quelqu\'un en ligne avec une fausse identité ?', a: 'Le catfishing', acc: ['catfishing', 'catfish'], x: ['Le doxxing', 'Le phishing', 'Le trolling'] },
  { id: 'net-d10', d: 3, t: 'Quelle vidéo de bébé mordeur est l\'une des toutes premières virales de YouTube ?', a: 'Charlie Bit My Finger', acc: ['charlie bit my finger', 'charlie'], x: ['David After Dentist', 'Chocolate Rain', 'Keyboard Cat'] },
  { id: 'net-d11', d: 3, t: 'Quel piège viral redirige l\'internaute vers une chanson de Rick Astley ?', a: 'Le Rickroll', acc: ['rickroll', 'rick roll', 'never gonna give you up'], x: ['Le Nyan Cat', 'Le Harlem Shake', 'Le Screamer'] },
  { id: 'net-d12', d: 3, t: 'Quel jeu mobile de 2016 en réalité augmentée a fait sortir tout le monde chasser des créatures ?', a: 'Pokémon GO', acc: ['pokemon go'], x: ['Ingress', 'Harry Potter Wizards Unite', 'Jurassic World Alive'] },
  { id: 'net-d13', d: 3, t: 'Comment appelle-t-on une fausse information largement partagée sur internet ?', a: 'Une fake news', acc: ['fake news', 'infox'], x: ['Un spoiler', 'Un thread', 'Un tag'] },
  { id: 'net-d14', d: 3, t: 'Quel mème montre un vieil homme souriant qui cache visiblement une douleur ?', a: 'Hide the Pain Harold', acc: ['hide the pain harold', 'harold'], x: ['Bad Luck Brian', 'Success Kid', 'Overly Attached Girlfriend'] },
  { id: 'net-d15', d: 3, t: 'Quel mème montre un homme se retournant sur une passante devant sa copine outrée ?', a: 'Distracted Boyfriend', acc: ['distracted boyfriend', 'petit ami distrait'], x: ['Two Buttons', 'Woman Yelling at a Cat', 'Expanding Brain'] },

  // --- Pro (20) ---
  { id: 'net-p1', d: 4, t: 'En quelle année YouTube a-t-il été créé ?', a: '2005', x: ['2003', '2007', '2009'] },
  { id: 'net-p2', d: 4, t: 'Quelle a été la toute première vidéo mise en ligne sur YouTube ?', a: 'Me at the zoo', acc: ['me at the zoo'], x: ['Charlie Bit My Finger', 'Gangnam Style', 'Nyan Cat'] },
  { id: 'net-p3', d: 4, t: 'Quel Suédois est resté des années le YouTubeur le plus suivi au monde ?', a: 'PewDiePie', x: ['Ninja', 'Markiplier', 'Jacksepticeye'] },
  { id: 'net-p4', d: 4, t: 'Quel YouTubeur américain est connu pour ses défis à gros budget et ses dons ?', a: 'MrBeast', x: ['PewDiePie', 'Ninja', 'Markiplier'] },
  { id: 'net-p5', d: 4, t: 'Quelle chanson est devenue en 2017 la vidéo la plus vue de YouTube ?', a: 'Despacito', x: ['Gangnam Style', 'Baby Shark', 'Shape of You'] },
  { id: 'net-p6', d: 4, t: 'Quelle comptine pour enfants figure parmi les vidéos les plus vues de tous les temps ?', a: 'Baby Shark', x: ['Despacito', 'Gangnam Style', 'La Reine des Neiges'] },
  { id: 'net-p7', d: 4, t: 'Quel réseau social a été fondé par Mark Zuckerberg en 2004 ?', a: 'Facebook', x: ['Myspace', 'Twitter', 'Instagram'] },
  { id: 'net-p8', d: 4, t: 'En quelle lettre Elon Musk a-t-il renommé Twitter en 2023 ?', a: 'X', x: ['Z', 'T', 'W'] },
  { id: 'net-p9', d: 4, t: 'Quel mème montre un homme transpirant devant deux boutons à choisir ?', a: 'Two Buttons', acc: ['two buttons', 'daily struggle'], x: ['Distracted Boyfriend', 'Drake Hotline Bling', 'Expanding Brain'] },
  { id: 'net-p10', d: 4, t: 'Quel mème utilise le rappeur Drake qui refuse puis approuve quelque chose ?', a: 'Drake Hotline Bling', acc: ['drake hotline bling', 'drakeposting'], x: ['Two Buttons', 'Distracted Boyfriend', 'Change My Mind'] },
  { id: 'net-p11', d: 4, t: 'Quelle plateforme de discussion par serveurs vocaux est très prisée des gamers ?', a: 'Discord', x: ['Slack', 'TeamSpeak', 'Skype'] },
  { id: 'net-p12', d: 4, t: 'Quel mème d\'un cerveau qui grossit illustre des idées prétendument géniales ?', a: 'Expanding Brain', acc: ['expanding brain', 'galaxy brain'], x: ['Two Buttons', 'Drakeposting', 'Stonks'] },
  { id: 'net-p13', d: 4, t: 'Quel mème d\'un homme d\'affaires devant un graphique illustre le « profit » absurde ?', a: 'Stonks', x: ['Gains', 'Bull', 'Cash'] },
  { id: 'net-p14', d: 4, t: 'Quel mème montre un chat blanc à table, pointé par une femme en colère ?', a: 'Woman Yelling at a Cat', acc: ['woman yelling at a cat', 'smudge'], x: ['Grumpy Cat', 'Nyan Cat', 'Cheems'] },
  { id: 'net-p15', d: 4, t: 'Quelle race de chien japonais est la mascotte du mème « Doge » et du Dogecoin ?', a: 'Le Shiba Inu', acc: ['shiba inu', 'shiba', 'doge'], x: ['Le Akita', 'Le Corgi', 'Le Husky'] },
  { id: 'net-p16', d: 4, t: 'Quel événement Facebook « pour rigoler » de 2019 proposait de prendre d\'assaut la Zone 51 ?', a: 'Storm Area 51', acc: ['storm area 51', 'area 51', 'zone 51'], x: ['Occupy Wall Street', 'Project Chanology', 'Rickroll'] },
  { id: 'net-p17', d: 4, t: 'Quel site d\'encyclopédie collaborative existe depuis 2001 ?', a: 'Wikipédia', x: ['Encarta', 'Quora', 'Reddit'] },
  { id: 'net-p18', d: 4, t: 'Quel mot d\'argot internet signifie « rire » et vient de l\'anglais ?', a: 'LOL', acc: ['lol', 'mdr'], x: ['BRB', 'AFK', 'FYI'] },
  { id: 'net-p19', d: 4, t: 'Quel YouTubeur et boxeur britannique forme un duo célèbre avec Logan Paul ?', a: 'KSI', x: ['MrBeast', 'PewDiePie', 'Ninja'] },
  { id: 'net-p20', d: 4, t: 'Comment appelle-t-on une tendance vidéo que tout le monde reproduit à l\'identique ?', a: 'Un challenge', acc: ['challenge', 'trend', 'tendance'], x: ['Un thread', 'Un raid', 'Un combo'] },
  ]),
  ...universe('internet', 'Réseaux sociaux', [
    // --- Faciles (5) ---
    { id: "reso-f1", d: 1, t: "Quel réseau social à l'oiseau bleu s'appelle désormais « X » ?", a: "Twitter", x: ["Facebook", "Instagram", "LinkedIn"], acc: ["twitter", "x"] },
    { id: "reso-f2", d: 1, t: "Quelle application de vidéos courtes et de danses est très populaire chez les jeunes ?", a: "TikTok", x: ["LinkedIn", "Pinterest", "Reddit"] },
    { id: "reso-f3", d: 1, t: "Sur quel réseau partage-t-on surtout des photos avec des filtres ?", a: "Instagram", x: ["Twitter", "LinkedIn", "Reddit"] },
    { id: "reso-f4", d: 1, t: "Comment appelle-t-on un petit symbole exprimant une émotion, comme 😂 ?", a: "Un emoji", x: ["Un pixel", "Un avatar", "Un hashtag"], acc: ["emoji", "émoji"] },
    { id: "reso-f5", d: 1, t: "Quel mot-clé précédé d'un « # » regroupe les publications sur un thème ?", a: "Un hashtag", x: ["Un tag", "Un lien", "Un pseudo"], acc: ["hashtag"] },
    // --- Moyennes (10) ---
    { id: "reso-m1", d: 2, t: "Qui a cofondé Facebook en 2004 ?", a: "Mark Zuckerberg", x: ["Bill Gates", "Steve Jobs", "Elon Musk"] },
    { id: "reso-m2", d: 2, t: "Quel milliardaire a racheté Twitter en 2022 ?", a: "Elon Musk", x: ["Jeff Bezos", "Mark Zuckerberg", "Bill Gates"] },
    { id: "reso-m3", d: 2, t: "Quelle entreprise possède Instagram et WhatsApp ?", a: "Meta", x: ["Google", "Apple", "Amazon"], acc: ["meta", "facebook"] },
    { id: "reso-m4", d: 2, t: "Comment appelle-t-on une photo de soi prise à bout de bras ?", a: "Un selfie", x: ["Un portrait", "Un snap", "Un reel"], acc: ["selfie"] },
    { id: "reso-m5", d: 2, t: "Quelle application affiche des photos qui s'effacent après quelques secondes ?", a: "Snapchat", x: ["WhatsApp", "Telegram", "Signal"] },
    { id: "reso-m6", d: 2, t: "Comment appelle-t-on une personne rémunérée pour promouvoir des produits sur les réseaux ?", a: "Un influenceur", x: ["Un modérateur", "Un abonné", "Un troll"], acc: ["influenceur"] },
    { id: "reso-m7", d: 2, t: "Quel bouton permet d'exprimer qu'on aime une publication ?", a: "Le « j'aime »", x: ["Le partage", "L'abonnement", "Le signalement"], acc: ["like", "j'aime"] },
    { id: "reso-m8", d: 2, t: "Quel réseau social professionnel sert à chercher un emploi et à réseauter ?", a: "LinkedIn", x: ["TikTok", "Snapchat", "Twitch"] },
    { id: "reso-m9", d: 2, t: "Comment appelle-t-on le fait de suivre le compte de quelqu'un ?", a: "S'abonner", x: ["Bloquer", "Signaler", "Épingler"], acc: ["suivre", "follow"] },
    { id: "reso-m10", d: 2, t: "Quelle plateforme de vidéos en direct est surtout dédiée au jeu vidéo ?", a: "Twitch", x: ["TikTok", "Vimeo", "Dailymotion"] },
    // --- Dures (15) ---
    { id: "reso-d1", d: 3, t: "En quelle année Facebook a-t-il été lancé ?", a: "2004", x: ["2000", "2008", "2010"] },
    { id: "reso-d2", d: 3, t: "En quelle année Instagram a-t-il été lancé ?", a: "2010", x: ["2004", "2013", "2016"] },
    { id: "reso-d3", d: 3, t: "Quelle entreprise chinoise détient TikTok ?", a: "ByteDance", x: ["Tencent", "Alibaba", "Huawei"], acc: ["bytedance"] },
    { id: "reso-d4", d: 3, t: "Quel réseau américain se présente comme la « page d'accueil de l'internet », avec ses forums ?", a: "Reddit", x: ["Tumblr", "Discord", "Pinterest"] },
    { id: "reso-d5", d: 3, t: "Comment appelle-t-on une personne qui provoque et sème la discorde en ligne ?", a: "Un troll", x: ["Un modérateur", "Un influenceur", "Un abonné"], acc: ["troll"] },
    { id: "reso-d6", d: 3, t: "Quelle messagerie, très utilisée par les gamers, s'organise en « serveurs » ?", a: "Discord", x: ["Slack", "Zoom", "Skype"] },
    { id: "reso-d7", d: 3, t: "Quelle plateforme d'épinglage d'images sert d'inspiration déco et mode ?", a: "Pinterest", x: ["Reddit", "Tumblr", "Flickr"] },
    { id: "reso-d8", d: 3, t: "Comment appelle-t-on l'ensemble des personnes qui suivent un compte ?", a: "Les abonnés", x: ["Les vues", "Les likes", "Les partages"], acc: ["abonnés", "followers"] },
    { id: "reso-d9", d: 3, t: "Quel format de vidéo courte et verticale Instagram a-t-il lancé pour concurrencer TikTok ?", a: "Les Reels", x: ["Les Stories", "Les Lives", "Les Threads"], acc: ["reels"] },
    { id: "reso-d10", d: 3, t: "Comment appelle-t-on le fait de devenir extrêmement populaire très vite sur internet ?", a: "Devenir viral", x: ["Devenir modéré", "Être banni", "Être vérifié"], acc: ["viral"] },
    { id: "reso-d11", d: 3, t: "Quel petit badge indique qu'un compte est authentifié ?", a: "La coche de vérification", x: ["L'étoile", "Le cadenas", "La couronne"], acc: ["badge", "coche bleue", "certifié"] },
    { id: "reso-d12", d: 3, t: "Quelle messagerie chiffrée est réputée pour la protection de la vie privée ?", a: "Signal", x: ["Messenger", "Snapchat", "WeChat"] },
    { id: "reso-d13", d: 3, t: "Quelle « super-application » chinoise combine messagerie, paiement et réseau social ?", a: "WeChat", x: ["WhatsApp", "Telegram", "Line"] },
    { id: "reso-d14", d: 3, t: "Comment appelle-t-on un contenu sponsorisé qui ressemble à une publication normale ?", a: "Un placement de produit", x: ["Un hashtag", "Un reel", "Un thread"], acc: ["placement de produit", "sponso"] },
    { id: "reso-d15", d: 3, t: "Quelle plateforme, rachetée par Elon Musk, a lancé un abonnement payant « Blue » ?", a: "Twitter", x: ["Instagram", "TikTok", "LinkedIn"], acc: ["twitter", "x"] },
    // --- Pro (20) ---
    { id: "reso-p1", d: 4, t: "Comment s'appelle la version chinoise d'origine de TikTok ?", a: "Douyin", x: ["Weibo", "Kuaishou", "Xiaohongshu"], acc: ["douyin"] },
    { id: "reso-p2", d: 4, t: "Quel réseau social des années 2000, très populaire avant Facebook, classait ses « amis » ?", a: "MySpace", x: ["Friendster", "Bebo", "Hi5"] },
    { id: "reso-p3", d: 4, t: "Quelle plateforme de blogs française était très populaire chez les ados dans les années 2000 ?", a: "Skyblog", x: ["MySpace", "Copains d'avant", "Caramail"], acc: ["skyblog", "skyrock"] },
    { id: "reso-p4", d: 4, t: "Quel PDG de Meta a témoigné plusieurs fois devant le Congrès américain ?", a: "Mark Zuckerberg", x: ["Elon Musk", "Sundar Pichai", "Tim Cook"] },
    { id: "reso-p5", d: 4, t: "Comment appelle-t-on le fil personnalisé de TikTok qui propose des vidéos ?", a: "Le « Pour toi »", x: ["Le « Mur »", "Le « Feed pro »", "La « Story »"], acc: ["pour toi", "for you"] },
    { id: "reso-p6", d: 4, t: "Quel réseau social a été fondé par Kevin Systrom et Mike Krieger ?", a: "Instagram", x: ["Twitter", "Snapchat", "Pinterest"] },
    { id: "reso-p7", d: 4, t: "Qui a cofondé et dirigé Snapchat ?", a: "Evan Spiegel", x: ["Kevin Systrom", "Jack Dorsey", "Jan Koum"] },
    { id: "reso-p8", d: 4, t: "Qui était le cofondateur et PDG historique de Twitter ?", a: "Jack Dorsey", x: ["Evan Spiegel", "Kevin Systrom", "Reid Hoffman"] },
    { id: "reso-p9", d: 4, t: "Quelle application de rencontres a popularisé le « swipe » à droite ou à gauche ?", a: "Tinder", x: ["Bumble", "Hinge", "Meetic"] },
    { id: "reso-p10", d: 4, t: "Comment appelle-t-on une image ou une idée qui se propage et se décline en masse sur internet ?", a: "Un mème", x: ["Un thread", "Un cookie", "Un flux"], acc: ["mème", "meme"] },
    { id: "reso-p11", d: 4, t: "Quel réseau professionnel a été racheté par Microsoft en 2016 ?", a: "LinkedIn", x: ["Slack", "Zoom", "Yammer"] },
    { id: "reso-p12", d: 4, t: "Quel concurrent de Twitter Meta a-t-il lancé en 2023 ?", a: "Threads", x: ["Mastodon", "Bluesky", "Truth Social"] },
    { id: "reso-p13", d: 4, t: "Comment appelle-t-on le fait de faire défiler sans fin son fil d'actualité ?", a: "Le scroll", x: ["Le buzz", "Le spam", "Le hack"], acc: ["scroll", "scroller", "doomscrolling"] },
    { id: "reso-p14", d: 4, t: "Quelle application de visioconférence est devenue incontournable pendant le confinement ?", a: "Zoom", x: ["Discord", "Twitch", "Reddit"] },
    { id: "reso-p15", d: 4, t: "Comment appelle-t-on un effet qui déforme ou décore le visage en direct ?", a: "Un filtre", x: ["Un emoji", "Un hashtag", "Un avatar"], acc: ["filtre"] },
    { id: "reso-p16", d: 4, t: "À quelle entreprise appartient YouTube ?", a: "Google", x: ["Meta", "Microsoft", "Amazon"] },
    { id: "reso-p17", d: 4, t: "Comment appelle-t-on la pratique de dévoiler publiquement les données privées de quelqu'un ?", a: "Le doxxing", x: ["Le phishing", "Le spamming", "Le streaming"], acc: ["doxxing", "doxing"] },
    { id: "reso-p18", d: 4, t: "Quel réseau de microblogging décentralisé, alternative à Twitter, fonctionne par « instances » ?", a: "Mastodon", x: ["Threads", "Bluesky", "Reddit"] },
    { id: "reso-p19", d: 4, t: "Comment appelle-t-on le harcèlement en ligne visant à intimider une personne ?", a: "Le cyberharcèlement", x: ["Le clickbait", "Le référencement", "Le community management"], acc: ["cyberharcèlement"] },
    { id: "reso-p20", d: 4, t: "Comment appelle-t-on un titre ou une image aguicheuse conçue pour pousser au clic ?", a: "Le clickbait", x: ["Le doxxing", "Le sample", "Le hashtag"], acc: ["clickbait", "piège à clics"] },
  ]),
];
