import type { Question } from '../../../core/models';

export const jeuxvideoQuestions: Question[] = [
  {
    id: 'jv-1',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quel plombier moustachu est la mascotte de Nintendo ?',
    answer: 'Mario',
    distractors: ['Luigi', 'Sonic', 'Link'],
  },
  {
    id: 'jv-2',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Dans quel jeu construit-on un monde avec des blocs cubiques ?',
    answer: 'Minecraft',
    distractors: ['Roblox', 'Terraria', 'Fortnite'],
  },
  {
    id: 'jv-3',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Quelle entreprise a créé la console PlayStation ?',
    answer: 'Sony',
    distractors: ['Microsoft', 'Nintendo', 'Sega'],
  },
  {
    id: 'jv-4',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quel est le Pokémon numéro 25 du Pokédex national ?',
    answer: 'Pikachu',
    distractors: ['Évoli', 'Bulbizarre', 'Carapuce'],
    hints: ['C\'est un Pokémon électrique tout jaune.'],
  },
  {
    id: 'jv-5',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: "Dans The Legend of Zelda, quel est le nom du héros que l'on incarne ?",
    answer: 'Link',
    distractors: ['Zelda', 'Ganon', 'Epona'],
    hints: ['La princesse, elle, s\'appelle Zelda.'],
  },
  {
    id: 'jv-6',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'En quelle année est sorti le premier Super Mario Bros. ?',
    answer: '1985',
    distractors: ['1983', '1990', '1987'],
    hints: ['Milieu des années 80, sur la NES.'],
  },
  {
    id: 'jv-7',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Quel jeu de tir héroïque 6 contre 6 de Blizzard est sorti en 2016 ?',
    answer: 'Overwatch',
    distractors: ['Valorant', 'Apex Legends', 'Team Fortress 2'],
  },
  {
    id: 'jv-8',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quel jeu mobile de 2016 fait attraper des créatures en réalité augmentée ?',
    answer: 'Pokémon GO',
    acceptable: ['pokemon go'],
    distractors: ['Ingress', 'Harry Potter Wizards Unite', 'Jurassic World Alive'],
  },
  {
    id: 'jv-9',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Qui est le créateur de la série Metal Gear ?',
    answer: 'Hideo Kojima',
    acceptable: ['kojima'],
    distractors: ['Shigeru Miyamoto', 'Hironobu Sakaguchi', 'Yoko Taro'],
  },
  {
    id: 'jv-10',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: "Dans Fortnite, comment s'appelle le mode où 100 joueurs s'affrontent ?",
    answer: 'Battle Royale',
    distractors: ['Sauver le monde', 'Créatif', 'Arène'],
  },
  {
    id: 'jv-11',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Dans quel jeu incarne-t-on un soldat nommé Master Chief ?',
    answer: 'Halo',
    distractors: ['Gears of War', 'Doom', 'Destiny'],
  },
  {
    id: 'jv-12',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Quel studio polonais a développé The Witcher 3 ?',
    answer: 'CD Projekt Red',
    acceptable: ['cd projekt'],
    distractors: ['Bethesda', 'BioWare', 'Ubisoft'],
  },
  {
    id: 'jv-13',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: "Dans Animal Crossing, comment s'appelle le tanuki qui prête de l'argent ?",
    answer: 'Tom Nook',
    acceptable: ['nook'],
    distractors: ['Marie', 'Rounard', 'Serena'],
  },
  {
    id: 'jv-14',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'En quelle année est sorti le premier jeu Tomb Raider ?',
    answer: '1996',
    distractors: ['1998', '1994', '2000'],
  },
  {
    id: 'jv-15',
    theme: 'jeuxvideo',
    difficulty: 4,
    text: 'Quel est le nom du protagoniste muet de la série Half-Life ?',
    answer: 'Gordon Freeman',
    acceptable: ['freeman'],
    distractors: ['Adrian Shephard', 'Alyx Vance', 'Isaac Clarke'],
  },
  {
    id: 'jv-16',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Dans Mario Kart, quel objet rend invincible quelques secondes ?',
    answer: "L'étoile",
    acceptable: ['etoile', 'etoile invincibilite'],
    distractors: ['Le champignon', 'La carapace bleue', 'La banane'],
  },
  {
    id: 'jv-17',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Quel RPG en monde ouvert de 2011 se déroule dans la contrée de Bordeciel (Skyrim) ?',
    answer: 'The Elder Scrolls V: Skyrim',
    acceptable: ['skyrim'],
    distractors: ['Oblivion', 'Dragon Age', 'Fallout 3'],
  },
  {
    id: 'jv-18',
    theme: 'jeuxvideo',
    difficulty: 4,
    text: 'Dans la série Dark Souls, comment appelle-t-on la « monnaie » récupérée sur les ennemis ?',
    answer: 'Les âmes',
    acceptable: ['ames', 'souls'],
    distractors: ['Les Runes', 'Les Éclats', 'Le Sang'],
  },
  {
    id: 'jv-19',
    theme: 'jeuxvideo',
    difficulty: 1,
    text: 'Quelle princesse Mario doit-il le plus souvent secourir ?',
    answer: 'Peach',
    acceptable: ['princesse peach'],
    distractors: ['Daisy', 'Zelda', 'Rosalina'],
  },
  {
    id: 'jv-20',
    theme: 'jeuxvideo',
    difficulty: 4,
    text: 'Quel est le jeu vidéo le plus vendu de tous les temps (toutes plateformes) ?',
    answer: 'Minecraft',
    distractors: ['Tetris', 'GTA V', 'Wii Sports'],
  },
  {
    id: 'jv-21',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Quel est le personnage principal de la série God of War ?',
    answer: 'Kratos',
    distractors: ['Aloy', 'Nathan Drake', 'Cloud'],
  },
  {
    id: 'jv-22',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Quel est le type du Pokémon Salamèche ?',
    answer: 'Feu',
    distractors: ['Eau', 'Plante', 'Électrik'],
  },
  {
    id: 'jv-23',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Quel studio a développé la série Grand Theft Auto ?',
    answer: 'Rockstar Games',
    acceptable: ['rockstar'],
    distractors: ['Ubisoft', 'Electronic Arts', 'Activision'],
  },
  {
    id: 'jv-24',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Dans quel jeu de combat affronte-t-on Ryu et Ken ?',
    answer: 'Street Fighter',
    distractors: ['Tekken', 'Mortal Kombat', 'Soulcalibur'],
  },
  {
    id: 'jv-25',
    theme: 'jeuxvideo',
    difficulty: 2,
    text: 'Dans Among Us, comment appelle-t-on le traître à démasquer ?',
    answer: "L'Imposteur",
    acceptable: ['imposteur', 'impostor'],
    distractors: ['Le Crewmate', 'Le Saboteur', 'Le Fantôme'],
  },
  {
    id: 'jv-26',
    theme: 'jeuxvideo',
    difficulty: 4,
    text: "Quel jeu d'arcade de 1978 a popularisé les invasions de vaisseaux extraterrestres ?",
    answer: 'Space Invaders',
    distractors: ['Pong', 'Pac-Man', 'Asteroids'],
  },
  {
    id: 'jv-27',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Dans League of Legends, comment appelle-t-on les petits sbires qui poussent sur les lignes ?',
    answer: 'Les minions',
    acceptable: ['minions', 'sbires'],
    distractors: ['Les bots', 'Les golems', 'Les nexus'],
  },
  {
    id: 'jv-28',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Quel jeu Nintendo fait combattre Mario, Link, Pikachu et bien d\'autres sur des plateformes ?',
    answer: 'Super Smash Bros.',
    acceptable: ['smash bros', 'smash'],
    distractors: ['Mario Party', 'Nintendo Land', 'Brawlhalla'],
  },
  {
    id: 'jv-29',
    theme: 'jeuxvideo',
    difficulty: 4,
    text: 'Quelle entreprise a commercialisé la console Dreamcast ?',
    answer: 'Sega',
    distractors: ['Sony', 'Atari', 'NEC'],
  },
  {
    id: 'jv-30',
    theme: 'jeuxvideo',
    difficulty: 3,
    text: 'Comment se nomme l\'épée légendaire récurrente de la série Zelda ?',
    answer: 'La Master Sword',
    acceptable: ['master sword', 'épée de légende', 'epee de legende'],
    distractors: ['Excalibur', 'La Buster Sword', 'Frostmourne'],
  },
];
