import type { Question } from '../../../core/models';

export const mangaQuestions: Question[] = [
  {
    id: 'manga-1',
    theme: 'manga',
    difficulty: 1,
    text: "Dans Naruto, quel est le grand rêve de Naruto Uzumaki ?",
    answer: 'Devenir Hokage',
    distractors: ['Devenir capitaine', 'Trouver le One Piece', 'Devenir Roi des Pirates'],
    hints: ['Le Hokage est le chef du village de Konoha.'],
  },
  {
    id: 'manga-2',
    theme: 'manga',
    difficulty: 1,
    text: "Dans One Piece, quel type de fruit du démon a mangé Luffy ?",
    answer: 'Le fruit du caoutchouc (Gomu Gomu)',
    acceptable: ['caoutchouc', 'gomu gomu', 'gum gum'],
    distractors: ['Le fruit du feu', 'Le fruit des ténèbres', 'Le fruit de la glace'],
  },
  {
    id: 'manga-3',
    theme: 'manga',
    difficulty: 2,
    text: "Dans Dragon Ball, comment s'appelle la première transformation aux cheveux dorés ?",
    answer: 'Super Saiyan',
    acceptable: ['super saiyen', 'ssj'],
    distractors: ['Ultra Instinct', 'Kaio-ken', 'Super Namek'],
    hints: ['Goku l\'atteint pour la première fois face à Freezer.'],
  },
  {
    id: 'manga-4',
    theme: 'manga',
    difficulty: 2,
    text: 'Qui est le mangaka (auteur) de One Piece ?',
    answer: 'Eiichirō Oda',
    acceptable: ['oda'],
    distractors: ['Masashi Kishimoto', 'Akira Toriyama', 'Tite Kubo'],
  },
  {
    id: 'manga-5',
    theme: 'manga',
    difficulty: 2,
    text: "Dans L'Attaque des Titans, comment s'appelle le héros principal ?",
    answer: 'Eren Jäger',
    acceptable: ['eren', 'eren yeager', 'eren jaeger'],
    distractors: ['Levi', 'Armin', 'Mikasa'],
  },
  {
    id: 'manga-6',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Death Note, quel est le vrai nom du détective « L » ?',
    answer: 'L Lawliet',
    acceptable: ['lawliet'],
    distractors: ['Light Yagami', 'Near', 'Mello'],
    hints: ['Son prénom est aussi la lettre L.', 'Nom de famille : Lawliet.'],
  },
  {
    id: 'manga-7',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans Naruto, quel démon-renard est scellé en lui ?',
    answer: 'Kurama (le démon à neuf queues)',
    acceptable: ['kurama', 'kyubi', 'kyūbi', 'neuf queues'],
    distractors: ['Shukaku', 'Gyuki', 'Son Goku le singe'],
  },
  {
    id: 'manga-8',
    theme: 'manga',
    difficulty: 1,
    text: 'Quel est le nom du chat-robot venu du futur dans le manga éponyme ?',
    answer: 'Doraemon',
    distractors: ['Doremi', 'Totoro', 'Luna'],
  },
  {
    id: 'manga-9',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Hunter x Hunter, qui est le meilleur ami de Gon ?',
    answer: 'Killua Zoldyck',
    acceptable: ['killua', 'kirua'],
    distractors: ['Kurapika', 'Leorio', 'Hisoka'],
  },
  {
    id: 'manga-10',
    theme: 'manga',
    difficulty: 2,
    text: "Dans Demon Slayer, comment s'appelle le héros dont la sœur est devenue un démon ?",
    answer: 'Tanjiro Kamado',
    acceptable: ['tanjiro'],
    distractors: ['Zenitsu', 'Inosuke', 'Giyu'],
    hints: ['Sa sœur s\'appelle Nezuko.'],
  },
  {
    id: 'manga-11',
    theme: 'manga',
    difficulty: 2,
    text: "Comment s'appelle l'équipage de Luffy dans One Piece ?",
    answer: 'L\'équipage du Chapeau de paille',
    acceptable: ['chapeau de paille', 'straw hat'],
    distractors: ['Les Pirates de Barbe Blanche', "L'équipage du Roux", 'Les Neuf Empereurs'],
  },
  {
    id: 'manga-12',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Fullmetal Alchemist, quel est le nom de famille des deux frères alchimistes ?',
    answer: 'Elric',
    distractors: ['Mustang', 'Armstrong', 'Hawkeye'],
    hints: ['Edward et Alphonse ___.'],
  },
  {
    id: 'manga-13',
    theme: 'manga',
    difficulty: 4,
    text: "Dans Bleach, comment s'appelle le zanpakutō d'Ichigo ?",
    answer: 'Zangetsu',
    distractors: ['Senbonzakura', 'Hyorinmaru', 'Zabimaru'],
  },
  {
    id: 'manga-14',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans My Hero Academia, comment se nomme le pouvoir hérité par Izuku ?',
    answer: 'One For All',
    distractors: ['All For One', 'Explosion', 'Half-Cold Half-Hot'],
  },
  {
    id: 'manga-15',
    theme: 'manga',
    difficulty: 4,
    text: "Dans JoJo's Bizarre Adventure, comment s'appelle le Stand de Jotaro Kujo ?",
    answer: 'Star Platinum',
    distractors: ['The World', 'Crazy Diamond', 'Gold Experience'],
    hints: ['« Ora ora ora ! »'],
  },
  {
    id: 'manga-16',
    theme: 'manga',
    difficulty: 2,
    text: "Dans One Piece, quel sabreur veut devenir le meilleur du monde ?",
    answer: 'Zoro',
    acceptable: ['roronoa zoro', 'zorro'],
    distractors: ['Sanji', 'Usopp', 'Brook'],
  },
  {
    id: 'manga-17',
    theme: 'manga',
    difficulty: 4,
    text: "Dans Berserk, comment s'appelle l'immense épée de Guts ?",
    answer: 'Le Dragon Slayer',
    acceptable: ['dragon slayer', 'dragonslayer'],
    distractors: ['Excalibur', 'Murasame', 'Le Rhongomyniad'],
  },
  {
    id: 'manga-18',
    theme: 'manga',
    difficulty: 3,
    text: "Dans Naruto, qui est le sensei (maître) de l'équipe 7 ?",
    answer: 'Kakashi Hatake',
    acceptable: ['kakashi'],
    distractors: ['Jiraiya', 'Itachi', 'Asuma'],
    hints: ['Le ninja copieur au Sharingan.'],
  },
  {
    id: 'manga-19',
    theme: 'manga',
    difficulty: 4,
    text: 'Dans Death Note, quel Shinigami laisse tomber le cahier dans le monde humain ?',
    answer: 'Ryuk',
    distractors: ['Rem', 'Sidoh', 'Gelus'],
    hints: ['Il adore les pommes.'],
  },
  {
    id: 'manga-20',
    theme: 'manga',
    difficulty: 2,
    text: 'Combien de Dragon Balls faut-il réunir pour invoquer Shenron ?',
    answer: '7',
    acceptable: ['sept'],
    distractors: ['5', '3', '9'],
  },
  {
    id: 'manga-21',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans One Piece, quel capitaine aux cheveux roux a inspiré Luffy et lui a confié son chapeau ?',
    answer: 'Shanks',
    acceptable: ['shanks le roux', 'le roux'],
    distractors: ['Barbe Blanche', 'Mihawk', 'Rayleigh'],
  },
  {
    id: 'manga-22',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans Dragon Ball Z, comment se nomme le fils aîné de Goku ?',
    answer: 'Gohan',
    distractors: ['Goten', 'Trunks', 'Vegeta'],
  },
  {
    id: 'manga-23',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Naruto, quel village ninja est dirigé par le Kazekage ?',
    answer: 'Le village du Sable (Suna)',
    acceptable: ['suna', 'village du sable', 'sable'],
    distractors: ['Kiri', 'Iwa', 'Kumo'],
  },
  {
    id: 'manga-24',
    theme: 'manga',
    difficulty: 4,
    text: "Dans L'Attaque des Titans, quel Titan « roi » contrôle tous les autres ?",
    answer: 'Le Titan Originel',
    acceptable: ['titan originel', 'originel', 'founding titan'],
    distractors: ['Le Titan Colossal', 'Le Titan Cuirassé', 'Le Titan Bestial'],
  },
  {
    id: 'manga-25',
    theme: 'manga',
    difficulty: 2,
    text: 'Dans Death Note, comment tue-t-on une personne avec le cahier ?',
    answer: 'En écrivant son nom (en pensant à son visage)',
    acceptable: ['en écrivant son nom', 'écrire son nom', 'son nom'],
    distractors: ['En brûlant sa photo', 'En prononçant une formule', 'En la touchant'],
  },
  {
    id: 'manga-26',
    theme: 'manga',
    difficulty: 3,
    text: 'Comment se nomme le célèbre lycée de héros dans My Hero Academia ?',
    answer: 'Yuei (U.A.)',
    acceptable: ['yuei', 'u.a.', 'ua'],
    distractors: ['Hosu', 'Shiketsu', 'Seirin'],
  },
  {
    id: 'manga-27',
    theme: 'manga',
    difficulty: 2,
    text: "Dans Demon Slayer, quel souffle Tanjiro maîtrise-t-il au début de l'aventure ?",
    answer: "Le souffle de l'eau",
    acceptable: ['eau', "souffle de l'eau"],
    distractors: ['Le souffle du feu', 'Le souffle de la foudre', 'Le souffle du vent'],
  },
  {
    id: 'manga-28',
    theme: 'manga',
    difficulty: 2,
    text: 'Quel mangaka a créé Dragon Ball ?',
    answer: 'Akira Toriyama',
    acceptable: ['toriyama'],
    distractors: ['Eiichirō Oda', 'Masashi Kishimoto', 'Yoshihiro Togashi'],
  },
  {
    id: 'manga-29',
    theme: 'manga',
    difficulty: 3,
    text: 'Dans Naruto, quelle technique de Kakashi concentre la foudre dans sa main ?',
    answer: 'Chidori',
    acceptable: ['chidori', 'raikiri'],
    distractors: ['Rasengan', 'Amaterasu', 'Susanoo'],
  },
  {
    id: 'manga-30',
    theme: 'manga',
    difficulty: 4,
    text: 'Dans Berserk, comment se nomme la bande de mercenaires menée par Griffith ?',
    answer: 'La Bande du Faucon',
    acceptable: ['bande du faucon', 'faucon', 'band of the hawk'],
    distractors: ['Les Chevaliers Sacrés', 'La Main de Dieu', 'Les Apôtres'],
  },
];
