import type { Question } from '../../../core/models';
import { universe } from './_build';

export const musiqueQuestions: Question[] = [
  ...universe('musique', 'Culture musicale', [
    // --- Faciles (5) ---
    { id: "cmus-f1", d: 1, t: "Quel groupe a chanté « Bohemian Rhapsody » ?", a: "Queen", x: ["The Beatles", "The Rolling Stones", "Led Zeppelin"] },
    { id: "cmus-f2", d: 1, t: "Combien de cordes possède une guitare classique standard ?", a: "6", x: ["4", "5", "12"], acc: ["six"] },
    { id: "cmus-f3", d: 1, t: "Quelle chanteuse a sorti « Shake It Off » et l'album « 1989 » ?", a: "Taylor Swift", x: ["Katy Perry", "Ariana Grande", "Selena Gomez"], acc: ["swift"] },
    { id: "cmus-f4", d: 1, t: "Quel instrument tient-on sous le menton et joue-t-on avec un archet ?", a: "Le violon", x: ["La guitare", "Le piano", "La flûte"] },
    { id: "cmus-f5", d: 1, t: "Dans un groupe de rock, quel instrument marque le rythme avec des fûts et des cymbales ?", a: "La batterie", x: ["Le clavier", "La basse", "Le micro"] },
    // --- Moyennes (10) ---
    { id: "cmus-m1", d: 2, t: "Quelle chanteuse est surnommée « Queen B » ?", a: "Beyoncé", x: ["Rihanna", "Lady Gaga", "Adele"], acc: ["beyonce"] },
    { id: "cmus-m2", d: 2, t: "Quel artiste a sorti l'album « Thriller » ?", a: "Michael Jackson", x: ["Prince", "Stevie Wonder", "Lionel Richie"], acc: ["jackson"] },
    { id: "cmus-m3", d: 2, t: "Quel duo français masqué a composé « Get Lucky » et « One More Time » ?", a: "Daft Punk", x: ["Justice", "Modjo", "Cassius"] },
    { id: "cmus-m4", d: 2, t: "Quel rappeur américain est surnommé « Slim Shady » ?", a: "Eminem", x: ["Jay-Z", "50 Cent", "Dr. Dre"] },
    { id: "cmus-m5", d: 2, t: "Quel groupe suédois a chanté « Dancing Queen » ?", a: "ABBA", x: ["Ace of Base", "Roxette", "A-ha"] },
    { id: "cmus-m6", d: 2, t: "De quel instrument Jimi Hendrix était-il le maître ?", a: "La guitare", x: ["La batterie", "Le piano", "La basse"], acc: ["guitare"] },
    { id: "cmus-m7", d: 2, t: "Quel DJ français a produit « Titanium » avec Sia ?", a: "David Guetta", x: ["Bob Sinclar", "Martin Solveig", "DJ Snake"] },
    { id: "cmus-m8", d: 2, t: "Quel chanteur britannique a sorti « Shape of You » ?", a: "Ed Sheeran", x: ["Sam Smith", "Harry Styles", "Lewis Capaldi"] },
    { id: "cmus-m9", d: 2, t: "Quel rappeur américain est surnommé « Yeezy » ?", a: "Kanye West", x: ["Drake", "Travis Scott", "Jay-Z"], acc: ["kanye", "ye"] },
    { id: "cmus-m10", d: 2, t: "Quelle artiste a chanté « Bad Romance » et « Poker Face » ?", a: "Lady Gaga", x: ["Katy Perry", "Rihanna", "Madonna"] },
    // --- Dures (15) ---
    { id: "cmus-d1", d: 3, t: "De quelle ville anglaise est originaire le groupe The Beatles ?", a: "Liverpool", x: ["Londres", "Manchester", "Birmingham"] },
    { id: "cmus-d2", d: 3, t: "Quel compositeur, devenu sourd, a écrit la 9e symphonie ?", a: "Beethoven", x: ["Mozart", "Bach", "Chopin"] },
    { id: "cmus-d3", d: 3, t: "De quel pays vient le groupe de metal Rammstein ?", a: "Allemagne", x: ["Autriche", "Suède", "Pays-Bas"] },
    { id: "cmus-d4", d: 3, t: "Quelle artiste britannique a interprété « Rolling in the Deep » ?", a: "Adele", x: ["Sia", "Duffy", "Amy Winehouse"] },
    { id: "cmus-d5", d: 3, t: "Quel groupe irlandais a pour chanteur Bono ?", a: "U2", x: ["Coldplay", "The Cranberries", "Oasis"] },
    { id: "cmus-d6", d: 3, t: "Quel groupe grunge a chanté « Smells Like Teen Spirit » ?", a: "Nirvana", x: ["Pearl Jam", "Soundgarden", "Foo Fighters"] },
    { id: "cmus-d7", d: 3, t: "Quelle chanteuse française a popularisé « La Vie en rose » ?", a: "Édith Piaf", x: ["Dalida", "Mireille Mathieu", "Barbara"], acc: ["piaf", "edith piaf"] },
    { id: "cmus-d8", d: 3, t: "Quel groupe britannique a sorti « Wonderwall » ?", a: "Oasis", x: ["Blur", "The Verve", "Radiohead"] },
    { id: "cmus-d9", d: 3, t: "Quel groupe a sorti l'album « The Dark Side of the Moon » ?", a: "Pink Floyd", x: ["Led Zeppelin", "The Who", "Genesis"] },
    { id: "cmus-d10", d: 3, t: "Quel groupe a chanté « Hotel California » ?", a: "Eagles", x: ["The Doors", "Fleetwood Mac", "Lynyrd Skynyrd"] },
    { id: "cmus-d11", d: 3, t: "Qui était le chanteur emblématique du groupe Queen ?", a: "Freddie Mercury", x: ["David Bowie", "Elton John", "Rod Stewart"] },
    { id: "cmus-d12", d: 3, t: "Quel chanteur américain est surnommé « The King of Rock and Roll » ?", a: "Elvis Presley", x: ["Chuck Berry", "Little Richard", "Buddy Holly"] },
    { id: "cmus-d13", d: 3, t: "Quel festival mythique de 1969 a réuni des centaines de milliers de personnes aux États-Unis ?", a: "Woodstock", x: ["Coachella", "Glastonbury", "Lollapalooza"] },
    { id: "cmus-d14", d: 3, t: "Quel style musical né en Jamaïque est associé à Bob Marley ?", a: "Le reggae", x: ["Le ska", "Le blues", "Le funk"] },
    { id: "cmus-d15", d: 3, t: "Quel groupe britannique mené par Mick Jagger existe depuis les années 1960 ?", a: "The Rolling Stones", x: ["The Who", "The Kinks", "The Beatles"] },
    // --- Pro (20) ---
    { id: "cmus-p1", d: 4, t: "Quel est le vrai nom de Lady Gaga ?", a: "Stefani Germanotta", x: ["Robyn Fenty", "Alecia Moore", "Katheryn Hudson"], acc: ["germanotta"] },
    { id: "cmus-p2", d: 4, t: "En quelle année les Beatles se sont-ils officiellement séparés ?", a: "1970", x: ["1968", "1972", "1965"] },
    { id: "cmus-p3", d: 4, t: "Combien de symphonies Beethoven a-t-il composées ?", a: "9", x: ["7", "5", "12"] },
    { id: "cmus-p4", d: 4, t: "Quel album est le plus vendu de toute l'histoire de la musique ?", a: "Thriller", x: ["Back in Black", "The Dark Side of the Moon", "Rumours"], acc: ["thriller"] },
    { id: "cmus-p5", d: 4, t: "En quelle année Elvis Presley est-il décédé ?", a: "1977", x: ["1981", "1973", "1969"] },
    { id: "cmus-p6", d: 4, t: "Quel compositeur a écrit l'opéra « La Flûte enchantée » ?", a: "Mozart", x: ["Beethoven", "Haydn", "Schubert"] },
    { id: "cmus-p7", d: 4, t: "Qui a composé « Les Quatre Saisons » ?", a: "Vivaldi", x: ["Bach", "Haendel", "Pachelbel"] },
    { id: "cmus-p8", d: 4, t: "En quelle année Michael Jackson est-il décédé ?", a: "2009", x: ["2005", "2011", "2007"] },
    { id: "cmus-p9", d: 4, t: "Quel est le vrai nom de Freddie Mercury ?", a: "Farrokh Bulsara", x: ["Reginald Dwight", "David Jones", "Gordon Sumner"] },
    { id: "cmus-p10", d: 4, t: "Quel producteur britannique est surnommé le « cinquième Beatle » ?", a: "George Martin", x: ["Brian Epstein", "Phil Spector", "Quincy Jones"] },
    { id: "cmus-p11", d: 4, t: "Quelle chanteuse américaine a interprété « I Will Always Love You » en 1992 ?", a: "Whitney Houston", x: ["Mariah Carey", "Céline Dion", "Tina Turner"] },
    { id: "cmus-p12", d: 4, t: "Quel guitariste, mort à 27 ans en 1970, reste une légende de la guitare électrique ?", a: "Jimi Hendrix", x: ["Eric Clapton", "Jimmy Page", "Keith Richards"] },
    { id: "cmus-p13", d: 4, t: "Le « Club des 27 » regroupe des artistes morts à 27 ans ; lequel n'en fait PAS partie ?", a: "Elvis Presley", x: ["Kurt Cobain", "Amy Winehouse", "Janis Joplin"] },
    { id: "cmus-p14", d: 4, t: "Quel compositeur autrichien, enfant prodige, est mort en 1791 à 35 ans ?", a: "Mozart", x: ["Beethoven", "Haydn", "Salieri"] },
    { id: "cmus-p15", d: 4, t: "Quel opéra de Bizet met en scène une bohémienne séductrice ?", a: "Carmen", x: ["La Traviata", "Aïda", "Tosca"] },
    { id: "cmus-p16", d: 4, t: "Quel violoniste virtuose italien du XIXe siècle avait une réputation quasi surnaturelle ?", a: "Niccolò Paganini", x: ["Antonio Vivaldi", "Arcangelo Corelli", "Giuseppe Tartini"] },
    { id: "cmus-p17", d: 4, t: "Quel groupe de rock a sorti l'album concept « The Wall » en 1979 ?", a: "Pink Floyd", x: ["Led Zeppelin", "The Who", "Genesis"] },
    { id: "cmus-p18", d: 4, t: "Quelle chanteuse britannique soul est morte en 2011 à 27 ans ?", a: "Amy Winehouse", x: ["Adele", "Duffy", "Lily Allen"] },
    { id: "cmus-p19", d: 4, t: "Quel groupe britannique a sorti l'album « OK Computer » en 1997 ?", a: "Radiohead", x: ["Coldplay", "Blur", "Muse"] },
    { id: "cmus-p20", d: 4, t: "Quelle comédie musicale de Broadway raconte la vie d'Alexander Hamilton en rap ?", a: "Hamilton", x: ["Rent", "Wicked", "In the Heights"] },
  ]),

  ...universe('musique', 'Pop', [
    // --- Faciles (5) ---
    { id: 'pop-f1', d: 1, t: 'Qui est surnommé le « Roi de la Pop » ?', a: 'Michael Jackson', acc: ['jackson'], x: ['Elvis Presley', 'Freddie Mercury', 'Justin Timberlake'] },
    { id: 'pop-f2', d: 1, t: 'Quelle artiste est surnommée la « Reine de la Pop » ?', a: 'Madonna', x: ['Rihanna', 'Beyoncé', 'Shakira'] },
    { id: 'pop-f3', d: 1, t: 'Quel boys band a chanté « I Want It That Way » ?', a: 'Backstreet Boys', x: ['One Direction', 'NSYNC', 'Take That'] },
    { id: 'pop-f4', d: 1, t: 'Quelle chanteuse a lancé sa carrière avec « ...Baby One More Time » ?', a: 'Britney Spears', x: ['Christina Aguilera', 'Jessica Simpson', 'Mandy Moore'] },
    { id: 'pop-f5', d: 1, t: 'Quel groupe de K-pop a connu un succès mondial avec « Dynamite » ?', a: 'BTS', x: ['Blackpink', 'EXO', 'Stray Kids'] },

    // --- Moyennes (10) ---
    { id: 'pop-m1', d: 2, t: 'Quel duo électro-pop britannique a chanté « West End Girls » ?', a: 'Pet Shop Boys', x: ['Eurythmics', 'Erasure', 'Depeche Mode'] },
    { id: 'pop-m2', d: 2, t: 'Quelle chanteuse barbadienne a chanté « Umbrella » ?', a: 'Rihanna', x: ['Beyoncé', 'Ciara', 'Ashanti'] },
    { id: 'pop-m3', d: 2, t: 'Quel chanteur canadien a chanté « Blinding Lights » ?', a: 'The Weeknd', x: ['Drake', 'Usher', 'Akon'] },
    { id: 'pop-m4', d: 2, t: 'Quelle chanteuse américaine a chanté « Firework » et « Roar » ?', a: 'Katy Perry', x: ['Lady Gaga', 'Dua Lipa', 'Ariana Grande'] },
    { id: 'pop-m5', d: 2, t: 'Quel DJ suédois, décédé en 2018, a chanté « Wake Me Up » ?', a: 'Avicii', x: ['Alesso', 'Kygo', 'Zedd'] },
    { id: 'pop-m6', d: 2, t: 'Quel groupe britannique a chanté « Viva la Vida » ?', a: 'Coldplay', x: ['Muse', 'Keane', 'Snow Patrol'] },
    { id: 'pop-m7', d: 2, t: 'Quelle jeune chanteuse a raflé les Grammy avec « Bad Guy » ?', a: 'Billie Eilish', x: ['Olivia Rodrigo', 'Dua Lipa', 'Ariana Grande'] },
    { id: 'pop-m8', d: 2, t: 'Quel chanteur a chanté « Uptown Funk » et « 24K Magic » ?', a: 'Bruno Mars', x: ['Justin Timberlake', 'Chris Brown', 'John Legend'] },
    { id: 'pop-m9', d: 2, t: 'Quelle chanteuse britannique, décédée en 2011, a chanté « Back to Black » ?', a: 'Amy Winehouse', x: ['Lily Allen', 'Joss Stone', 'Leona Lewis'] },
    { id: 'pop-m10', d: 2, t: 'Quel chanteur belge a chanté « Alors on danse » et « Papaoutai » ?', a: 'Stromae', x: ['Orelsan', 'Angèle', 'Mika'] },

    // --- Dures (15) ---
    { id: 'pop-d1', d: 3, t: 'Quelle chanteuse néo-zélandaise a percé avec « Royals » ?', a: 'Lorde', x: ['Sia', 'Halsey', 'Banks'] },
    { id: 'pop-d2', d: 3, t: 'Quel groupe a chanté « Moves Like Jagger » et « Sugar » ?', a: 'Maroon 5', x: ['OneRepublic', 'Imagine Dragons', 'The Killers'] },
    { id: 'pop-d3', d: 3, t: 'Quelle chanteuse au visage souvent caché a chanté « Chandelier » ?', a: 'Sia', x: ['Halsey', 'Robyn', 'Grimes'] },
    { id: 'pop-d4', d: 3, t: 'Quel artiste a chanté « Purple Rain » ?', a: 'Prince', x: ['Sting', 'Seal', 'Beck'] },
    { id: 'pop-d5', d: 3, t: 'Quel rappeur canadien a chanté « God\'s Plan » ?', a: 'Drake', x: ['Future', 'Ludacris', 'Nelly'] },
    { id: 'pop-d6', d: 3, t: 'Quel chanteur britannique a chanté « Rocket Man » et « Your Song » ?', a: 'Elton John', x: ['David Bowie', 'Rod Stewart', 'Freddie Mercury'] },
    { id: 'pop-d7', d: 3, t: 'Quelle chanteuse québécoise a chanté « My Heart Will Go On » ?', a: 'Celine Dion', x: ['Mariah Carey', 'Whitney Houston', 'Barbra Streisand'] },
    { id: 'pop-d8', d: 3, t: 'Quel girl group comptait Mel B, Emma, Geri, Mel C et Victoria ?', a: 'Spice Girls', x: ['Little Mix', 'Girls Aloud', 'Sugababes'] },
    { id: 'pop-d9', d: 3, t: 'Quel chanteur du duo Wham! a chanté « Careless Whisper » en solo ?', a: 'George Michael', x: ['Andrew Ridgeley', 'Rick Astley', 'Boy George'] },
    { id: 'pop-d10', d: 3, t: 'Quel producteur suédois est derrière d\'innombrables tubes pop ?', a: 'Max Martin', x: ['Dr. Luke', 'Rick Rubin', 'David Foster'] },
    { id: 'pop-d11', d: 3, t: 'Quelle chanteuse islandaise excentrique a chanté « It\'s Oh So Quiet » ?', a: 'Björk', x: ['Grimes', 'Robyn', 'Sia'] },
    { id: 'pop-d12', d: 3, t: 'Quel boys band comptait Harry Styles et Zayn Malik ?', a: 'One Direction', x: ['The Wanted', 'JLS', 'Westlife'] },
    { id: 'pop-d13', d: 3, t: 'Quel groupe suédois a chanté « The Sign » dans les années 90 ?', a: 'Ace of Base', x: ['Roxette', 'Aqua', 'A-ha'] },
    { id: 'pop-d14', d: 3, t: 'Quel groupe de filles sud-coréen a chanté « Ddu-Du Ddu-Du » ?', a: 'Blackpink', x: ['Twice', 'Red Velvet', 'Aespa'] },
    { id: 'pop-d15', d: 3, t: 'Quel groupe a chanté « Californication » et « Under the Bridge » ?', a: 'Red Hot Chili Peppers', x: ['Foo Fighters', 'Green Day', 'Weezer'] },

    // --- Pro (20) ---
    { id: 'pop-p1', d: 4, t: 'En quelle année Freddie Mercury, chanteur de Queen, est-il décédé ?', a: '1991', x: ['1989', '1993', '1985'] },
    { id: 'pop-p2', d: 4, t: 'Quel groupe a sorti l\'album « Rumours » en 1977 ?', a: 'Fleetwood Mac', x: ['Eagles', 'The Doors', 'Steely Dan'] },
    { id: 'pop-p3', d: 4, t: 'Quel groupe britannique des années 80 a chanté « Karma Chameleon » ?', a: 'Culture Club', x: ['Duran Duran', 'Spandau Ballet', 'Tears for Fears'] },
    { id: 'pop-p4', d: 4, t: 'Dans quelle ville américaine est né le label Motown ?', a: 'Détroit', x: ['Chicago', 'Memphis', 'Atlanta'] },
    { id: 'pop-p5', d: 4, t: 'Quelle chanteuse est surnommée « The Queen of Soul » ?', a: 'Aretha Franklin', x: ['Diana Ross', 'Tina Turner', 'Gladys Knight'] },
    { id: 'pop-p6', d: 4, t: 'Quelle chanteuse a interprété « I Will Always Love You » dans Bodyguard ?', a: 'Whitney Houston', x: ['Mariah Carey', 'Celine Dion', 'Toni Braxton'] },
    { id: 'pop-p7', d: 4, t: 'Quel chanteur britannique a incarné le personnage de Ziggy Stardust ?', a: 'David Bowie', x: ['Freddie Mercury', 'Elton John', 'Marc Bolan'] },
    { id: 'pop-p8', d: 4, t: 'Quel chanteur portoricain a chanté le tube mondial « Despacito » ?', a: 'Luis Fonsi', x: ['Enrique Iglesias', 'Ricky Martin', 'Marc Anthony'] },
    { id: 'pop-p9', d: 4, t: 'Quel Beatle a écrit et chanté « Imagine » en solo ?', a: 'John Lennon', x: ['Paul McCartney', 'George Harrison', 'Ringo Starr'] },
    { id: 'pop-p10', d: 4, t: 'Quel rappeur a sorti l\'album « good kid, m.A.A.d city » ?', a: 'Kendrick Lamar', x: ['J. Cole', 'Travis Scott', 'Big Sean'] },
    { id: 'pop-p11', d: 4, t: 'Quelle chanteuse a battu des records de streaming avec « Flowers » en 2023 ?', a: 'Miley Cyrus', x: ['Dua Lipa', 'Olivia Rodrigo', 'Ariana Grande'] },
    { id: 'pop-p12', d: 4, t: 'Quel chanteur canadien, découvert sur YouTube, a chanté « Baby » ?', a: 'Justin Bieber', x: ['Shawn Mendes', 'Charlie Puth', 'Troye Sivan'] },
    { id: 'pop-p13', d: 4, t: 'Quelle chanteuse a sorti l\'album « SOUR » avec « drivers license » ?', a: 'Olivia Rodrigo', x: ['Billie Eilish', 'Dua Lipa', 'Gracie Abrams'] },
    { id: 'pop-p14', d: 4, t: 'Quel duo norvégien a chanté « Take On Me » ?', a: 'A-ha', x: ['Roxette', 'Erasure', 'Modern Talking'] },
    { id: 'pop-p15', d: 4, t: 'Quel groupe britannique a chanté « Bitter Sweet Symphony » ?', a: 'The Verve', x: ['Oasis', 'Blur', 'Pulp'] },
    { id: 'pop-p16', d: 4, t: 'Quelle chanteuse colombienne a chanté « Waka Waka » et « Hips Don\'t Lie » ?', a: 'Shakira', x: ['Beyoncé', 'Rihanna', 'Ciara'] },
    { id: 'pop-p17', d: 4, t: 'Quelle chanteuse cubano-américaine a chanté « Havana » ?', a: 'Camila Cabello', x: ['Selena Gomez', 'Becky G', 'Sofia Reyes'] },
    { id: 'pop-p18', d: 4, t: 'Quel rappeur américain, lié au festival Astroworld, a chanté « Sicko Mode » ?', a: 'Travis Scott', x: ['Post Malone', 'Young Thug', 'Playboi Carti'] },
    { id: 'pop-p19', d: 4, t: 'Quel groupe britannique a sorti l\'album culte « OK Computer » en 1997 ?', a: 'Radiohead', x: ['Blur', 'Oasis', 'Pulp'] },
    { id: 'pop-p20', d: 4, t: 'Quel groupe de rock a pour chanteuse Hayley Williams ?', a: 'Paramore', x: ['Evanescence', 'No Doubt', 'Garbage'] },
  ]),

  ...universe('musique', 'Métal', [
    // --- Faciles (5) ---
    { id: 'metal-f1', d: 1, t: 'Quel groupe a pour chanteur Bruce Dickinson et une mascotte nommée Eddie ?', a: 'Iron Maiden', x: ['Metallica', 'Slayer', 'Megadeth'] },
    { id: 'metal-f2', d: 1, t: 'Quel groupe américain a sorti « Master of Puppets » ?', a: 'Metallica', x: ['Megadeth', 'Anthrax', 'Pantera'] },
    { id: 'metal-f3', d: 1, t: 'Quel chanteur surnommé « the Prince of Darkness » a débuté dans Black Sabbath ?', a: 'Ozzy Osbourne', x: ['Ronnie James Dio', 'Rob Halford', 'Bruce Dickinson'] },
    { id: 'metal-f4', d: 1, t: 'Quel groupe britannique pionnier du heavy metal a pour guitariste Tony Iommi ?', a: 'Black Sabbath', x: ['Deep Purple', 'Judas Priest', 'Led Zeppelin'] },
    { id: 'metal-f5', d: 1, t: 'Comment se nomme la mascotte squelette du groupe Iron Maiden ?', a: 'Eddie', x: ['Vic', 'Snaggletooth', 'Murray'] },
    // --- Moyennes (10) ---
    { id: 'metal-m1', d: 2, t: 'Quel groupe a pour chanteur et guitariste rythmique James Hetfield ?', a: 'Metallica', x: ['Slayer', 'Megadeth', 'Pantera'] },
    { id: 'metal-m2', d: 2, t: 'Quel groupe de thrash a été fondé par Dave Mustaine après son renvoi de Metallica ?', a: 'Megadeth', x: ['Slayer', 'Anthrax', 'Testament'] },
    { id: 'metal-m3', d: 2, t: 'Quel chanteur de Judas Priest est surnommé « the Metal God » ?', a: 'Rob Halford', x: ['Bruce Dickinson', 'Ozzy Osbourne', 'Ronnie James Dio'] },
    { id: 'metal-m4', d: 2, t: 'Quel groupe finlandais joue en costumes de monstres et a gagné l\'Eurovision ?', a: 'Lordi', x: ['Nightwish', 'Children of Bodom', 'Amorphis'] },
    { id: 'metal-m5', d: 2, t: 'Comment appelle-t-on les « Big Four » du thrash metal ?', a: 'Metallica, Slayer, Megadeth et Anthrax', x: ['Metallica, Pantera, Slayer et Sepultura', 'Slayer, Testament, Exodus et Death', 'Megadeth, Kreator, Sodom et Tankard'] },
    { id: 'metal-m6', d: 2, t: 'Quel groupe suédois de death metal mélodique a sorti « The Jester Race » ?', a: 'In Flames', x: ['At the Gates', 'Dark Tranquillity', 'Arch Enemy'] },
    { id: 'metal-m7', d: 2, t: 'Quel groupe allemand de power metal a été fondé par Kai Hansen ?', a: 'Helloween', x: ['Blind Guardian', 'Gamma Ray', 'Rage'] },
    { id: 'metal-m8', d: 2, t: 'Quel groupe de nu metal a sorti l\'album « Hybrid Theory » ?', a: 'Linkin Park', x: ['Korn', 'Limp Bizkit', 'Slipknot'] },
    { id: 'metal-m9', d: 2, t: 'Quel groupe américain porte des masques et compte neuf membres ?', a: 'Slipknot', x: ['Mushroomhead', 'Slayer', 'Gwar'] },
    { id: 'metal-m10', d: 2, t: 'Quel chanteur, successeur d\'Ozzy dans Black Sabbath, a popularisé le signe des cornes ?', a: 'Ronnie James Dio', x: ['Rob Halford', 'Bruce Dickinson', 'Ozzy Osbourne'] },
    // --- Dures (15) ---
    { id: 'metal-d1', d: 3, t: 'Quel groupe norvégien est un pilier du black metal, mené par Ihsahn ?', a: 'Emperor', x: ['Mayhem', 'Darkthrone', 'Immortal'] },
    { id: 'metal-d2', d: 3, t: 'Quel groupe de death metal de Floride a été fondé par Chuck Schuldiner ?', a: 'Death', x: ['Obituary', 'Morbid Angel', 'Cannibal Corpse'] },
    { id: 'metal-d3', d: 3, t: 'Quel groupe brésilien de thrash/groove a sorti « Roots » ?', a: 'Sepultura', x: ['Soulfly', 'Pantera', 'Kreator'] },
    { id: 'metal-d4', d: 3, t: 'Quel groupe de groove metal du Texas avait Dimebag Darrell à la guitare ?', a: 'Pantera', x: ['Machine Head', 'Lamb of God', 'Exhorder'] },
    { id: 'metal-d5', d: 3, t: 'Quel album de Metallica surnommé « the Black Album » est éponyme ?', a: 'Metallica', x: ['Master of Puppets', 'Ride the Lightning', 'Load'] },
    { id: 'metal-d6', d: 3, t: 'Quel groupe finlandais de metal symphonique a eu pour chanteuse Tarja Turunen ?', a: 'Nightwish', x: ['Within Temptation', 'Epica', 'Lacuna Coil'] },
    { id: 'metal-d7', d: 3, t: 'Quel groupe suédois occulte met en scène des personnages nommés « Papa Emeritus » ?', a: 'Ghost', x: ['Behemoth', 'Watain', 'In Flames'] },
    { id: 'metal-d8', d: 3, t: 'Quel groupe suédois est pionnier du « djent » avec ses rythmiques complexes ?', a: 'Meshuggah', x: ['Periphery', 'Gojira', 'TesseracT'] },
    { id: 'metal-d9', d: 3, t: 'Quel groupe français de metal, mené par les frères Duplantier, chante sur l\'écologie ?', a: 'Gojira', x: ['Mass Hysteria', 'Dagoba', 'Trust'] },
    { id: 'metal-d10', d: 3, t: 'Quel groupe allemand de metal industriel chante en allemand avec beaucoup de pyrotechnie ?', a: 'Rammstein', x: ['Oomph!', 'Megaherz', 'KMFDM'] },
    { id: 'metal-d11', d: 3, t: 'Quel groupe allemand de thrash est un pilier du genre avec Sodom et Destruction ?', a: 'Kreator', x: ['Exodus', 'Overkill', 'Testament'] },
    { id: 'metal-d12', d: 3, t: 'Quel batteur cofondateur de Metallica est d\'origine danoise ?', a: 'Lars Ulrich', x: ['Dave Lombardo', 'Nicko McBrain', 'Vinnie Paul'] },
    { id: 'metal-d13', d: 3, t: 'Quel guitariste virtuose suédois a popularisé le style « néoclassique » ?', a: 'Yngwie Malmsteen', x: ['Steve Vai', 'Joe Satriani', 'John Petrucci'] },
    { id: 'metal-d14', d: 3, t: 'Quel groupe américain de metal progressif a sorti « Images and Words » ?', a: 'Dream Theater', x: ['Symphony X', 'Fates Warning', 'Queensrÿche'] },
    { id: 'metal-d15', d: 3, t: 'Quel sous-genre lent et lourd Black Sabbath a-t-il inspiré ?', a: 'le doom metal', x: ['le power metal', 'le speed metal', 'le glam metal'] },
    // --- Pro (20) ---
    { id: 'metal-p1', d: 4, t: 'Quel groupe norvégien de black metal fut marqué par des meurtres au début des années 90 ?', a: 'Mayhem', x: ['Immortal', 'Darkthrone', 'Satyricon'] },
    { id: 'metal-p2', d: 4, t: 'Comment s\'appelle le premier album de Black Sabbath, sorti en 1970 ?', a: 'Black Sabbath', x: ['Paranoid', 'Master of Reality', 'Vol. 4'] },
    { id: 'metal-p3', d: 4, t: 'Quel chanteur a précédé Bruce Dickinson sur les premiers albums d\'Iron Maiden ?', a: "Paul Di'Anno", x: ['Blaze Bayley', 'Ronnie James Dio', 'Rob Halford'] },
    { id: 'metal-p4', d: 4, t: 'Quel groupe suédois de death metal mélodique a aujourd\'hui pour chanteuse Alissa White-Gluz ?', a: 'Arch Enemy', x: ['Amon Amarth', 'In Flames', 'Soilwork'] },
    { id: 'metal-p5', d: 4, t: 'Quel groupe suédois chante le death metal sur des thèmes vikings ?', a: 'Amon Amarth', x: ['Ensiferum', 'Bathory', 'Unleashed'] },
    { id: 'metal-p6', d: 4, t: 'Quel projet solo norvégien de black metal est celui de Varg Vikernes ?', a: 'Burzum', x: ['Ulver', 'Satyricon', 'Taake'] },
    { id: 'metal-p7', d: 4, t: 'Quel groupe américain de death metal est connu pour ses pochettes gore et « Hammer Smashed Face » ?', a: 'Cannibal Corpse', x: ['Deicide', 'Obituary', 'Suffocation'] },
    { id: 'metal-p8', d: 4, t: 'Quel groupe polonais de blackened death metal est mené par Nergal ?', a: 'Behemoth', x: ['Vader', 'Decapitated', 'Batushka'] },
    { id: 'metal-p9', d: 4, t: 'Quel sous-genre extrême se caractérise par des morceaux très courts et des « blast beats » ?', a: 'le grindcore', x: ['le power metal', 'le glam metal', 'le doom metal'] },
    { id: 'metal-p10', d: 4, t: 'Quel groupe britannique a lancé le grindcore avec l\'album « Scum » ?', a: 'Napalm Death', x: ['Carcass', 'Extreme Noise Terror', 'Bolt Thrower'] },
    { id: 'metal-p11', d: 4, t: 'Quel groupe de metalcore a pour chanteur Randy Blythe ?', a: 'Lamb of God', x: ['Killswitch Engage', 'As I Lay Dying', 'Trivium'] },
    { id: 'metal-p12', d: 4, t: 'Quel guitariste de Pantera est mort sur scène en 2004 ?', a: 'Dimebag Darrell', x: ['Chuck Schuldiner', 'Randy Rhoads', 'Cliff Burton'] },
    { id: 'metal-p13', d: 4, t: 'Quel bassiste de Metallica est mort dans un accident de bus en 1986 ?', a: 'Cliff Burton', x: ['Jason Newsted', 'Robert Trujillo', 'Steve Harris'] },
    { id: 'metal-p14', d: 4, t: 'Quel groupe norvégien de black metal symphonique est mené par Shagrath ?', a: 'Dimmu Borgir', x: ['Cradle of Filth', 'Emperor', 'Old Man\'s Child'] },
    { id: 'metal-p15', d: 4, t: 'Quel festival allemand est l\'un des plus grands rassemblements de metal au monde ?', a: 'Wacken Open Air', x: ['Hellfest', 'Download', 'Graspop'] },
    { id: 'metal-p16', d: 4, t: 'Quel grand festival de metal a lieu chaque année à Clisson, en France ?', a: 'Hellfest', x: ['Wacken Open Air', 'Download', 'Graspop'] },
    { id: 'metal-p17', d: 4, t: 'Quel groupe de metalcore a sorti « The End of Heartache » ?', a: 'Killswitch Engage', x: ['All That Remains', 'Shadows Fall', 'Unearth'] },
    { id: 'metal-p18', d: 4, t: 'Quel guitariste d\'Ozzy Osbourne, mort en 1982, est une légende du heavy metal ?', a: 'Randy Rhoads', x: ['Zakk Wylde', 'Jake E. Lee', 'Dimebag Darrell'] },
    { id: 'metal-p19', d: 4, t: 'Quel groupe de la « NWOBHM » a influencé Metallica avec « Am I Evil » ?', a: 'Diamond Head', x: ['Saxon', 'Angel Witch', 'Venom'] },
    { id: 'metal-p20', d: 4, t: 'Quel groupe pionnier a posé les bases du black metal avec « Welcome to Hell » ?', a: 'Venom', x: ['Bathory', 'Hellhammer', 'Celtic Frost'] },
  ]),

  ...universe('musique', 'Rock', [
    // --- Faciles (5) ---
    { id: 'rock-f1', d: 1, t: 'Quel groupe britannique de John, Paul, George et Ringo est le plus célèbre de l\'histoire ?', a: 'les Beatles', x: ['les Rolling Stones', 'les Who', 'les Kinks'] },
    { id: 'rock-f2', d: 1, t: 'Quel groupe a pour chanteur Mick Jagger et guitariste Keith Richards ?', a: 'les Rolling Stones', x: ['les Beatles', 'les Who', 'les Doors'] },
    { id: 'rock-f3', d: 1, t: 'Quel groupe australien en uniforme d\'écolier a fait « Highway to Hell » ?', a: 'AC/DC', x: ["Guns N' Roses", 'Kiss', 'Aerosmith'] },
    { id: 'rock-f4', d: 1, t: 'Quel chanteur de Queen a écrit « Bohemian Rhapsody » ?', a: 'Freddie Mercury', x: ['Robert Plant', 'Roger Daltrey', 'David Bowie'] },
    { id: 'rock-f5', d: 1, t: 'Quel groupe a composé « Stairway to Heaven » ?', a: 'Led Zeppelin', x: ['Deep Purple', 'Pink Floyd', 'Black Sabbath'] },
    // --- Moyennes (10) ---
    { id: 'rock-m1', d: 2, t: 'Quel guitariste a joué à Woodstock et est mort en 1970 ?', a: 'Jimi Hendrix', x: ['Eric Clapton', 'Jimmy Page', 'Jeff Beck'] },
    { id: 'rock-m2', d: 2, t: 'Quel groupe britannique a sorti l\'album concept « The Dark Side of the Moon » ?', a: 'Pink Floyd', x: ['Genesis', 'Yes', 'King Crimson'] },
    { id: 'rock-m3', d: 2, t: 'Quel chanteur américain surnommé « the King » a lancé le rock\'n\'roll dans les années 50 ?', a: 'Elvis Presley', x: ['Chuck Berry', 'Buddy Holly', 'Little Richard'] },
    { id: 'rock-m4', d: 2, t: 'Quel groupe de Seattle mené par Kurt Cobain a lancé le grunge avec « Nevermind » ?', a: 'Nirvana', x: ['Pearl Jam', 'Soundgarden', 'Alice in Chains'] },
    { id: 'rock-m5', d: 2, t: 'Quel groupe irlandais a pour chanteur Bono ?', a: 'U2', x: ['Coldplay', 'Simple Minds', 'the Cranberries'] },
    { id: 'rock-m6', d: 2, t: 'Quel groupe américain du New Jersey a fait « Livin\' on a Prayer » ?', a: 'Bon Jovi', x: ['Aerosmith', 'Journey', 'Def Leppard'] },
    { id: 'rock-m7', d: 2, t: 'Quel groupe de Manchester, rival de Blur, réunit les frères Gallagher ?', a: 'Oasis', x: ['Blur', 'Pulp', 'the Stone Roses'] },
    { id: 'rock-m8', d: 2, t: 'Quel chanteur surnommé « the Boss » incarne le rock américain avec le E Street Band ?', a: 'Bruce Springsteen', x: ['Tom Petty', 'Bob Seger', 'John Mellencamp'] },
    { id: 'rock-m9', d: 2, t: 'Quel groupe californien mené par Anthony Kiedis mêle rock et funk ?', a: 'les Red Hot Chili Peppers', x: ['les Foo Fighters', 'les Pixies', "les Jane's Addiction"] },
    { id: 'rock-m10', d: 2, t: 'Quel groupe Dave Grohl a-t-il fondé après la fin de Nirvana ?', a: 'les Foo Fighters', x: ['les Queens of the Stone Age', 'les Pearl Jam', 'les Weezer'] },
    // --- Dures (15) ---
    { id: 'rock-d1', d: 3, t: 'Quel guitariste britannique surnommé « Slowhand » a joué chez Cream ?', a: 'Eric Clapton', x: ['Jeff Beck', 'Jimmy Page', 'George Harrison'] },
    { id: 'rock-d2', d: 3, t: 'Quel groupe américain mené par Jim Morrison a fait « Light My Fire » ?', a: 'les Doors', x: ['les Byrds', 'Jefferson Airplane', 'the Grateful Dead'] },
    { id: 'rock-d3', d: 3, t: 'Quel chanteur caméléon a créé le personnage de « Ziggy Stardust » ?', a: 'David Bowie', x: ['Lou Reed', 'Iggy Pop', 'Bryan Ferry'] },
    { id: 'rock-d4', d: 3, t: 'Quel power trio canadien de rock progressif compte Geddy Lee ?', a: 'Rush', x: ['Triumph', 'Saga', 'Yes'] },
    { id: 'rock-d5', d: 3, t: 'Quel groupe de rock progressif a été mené par Peter Gabriel puis Phil Collins ?', a: 'Genesis', x: ['Yes', 'King Crimson', 'Jethro Tull'] },
    { id: 'rock-d6', d: 3, t: 'Quel guitariste a rejoint les Rolling Stones en 1975 après Mick Taylor ?', a: 'Ronnie Wood', x: ['Brian Jones', 'Bill Wyman', 'Ian Stewart'] },
    { id: 'rock-d7', d: 3, t: 'Quel groupe américain a fait « Hotel California » ?', a: 'les Eagles', x: ['Fleetwood Mac', 'the Doobie Brothers', 'Lynyrd Skynyrd'] },
    { id: 'rock-d8', d: 3, t: 'Quel groupe anglo-américain a fait l\'album « Rumours » avec Stevie Nicks ?', a: 'Fleetwood Mac', x: ['the Eagles', 'Heart', 'Journey'] },
    { id: 'rock-d9', d: 3, t: 'Quel groupe punk britannique a choqué avec « God Save the Queen » en 1977 ?', a: 'les Sex Pistols', x: ['the Clash', 'the Damned', 'the Ramones'] },
    { id: 'rock-d10', d: 3, t: 'Quel groupe punk de New York criait « Hey Ho, Let\'s Go » ?', a: 'les Ramones', x: ['the Stooges', 'Television', 'Talking Heads'] },
    { id: 'rock-d11', d: 3, t: 'Quel groupe mené par Robert Smith incarne le rock gothique et le maquillage pâle ?', a: 'the Cure', x: ['Joy Division', 'Bauhaus', 'the Sisters of Mercy'] },
    { id: 'rock-d12', d: 3, t: 'Quel groupe post-punk mené par Ian Curtis a fait « Love Will Tear Us Apart » ?', a: 'Joy Division', x: ['New Order', 'the Smiths', 'the Cure'] },
    { id: 'rock-d13', d: 3, t: 'Quel groupe de Manchester réunissait Morrissey et Johnny Marr ?', a: 'the Smiths', x: ['the Stone Roses', 'Joy Division', 'Oasis'] },
    { id: 'rock-d14', d: 3, t: 'Quel groupe américain de Géorgie a fait « Losing My Religion » ?', a: 'R.E.M.', x: ['the Pixies', 'Sonic Youth', 'Dinosaur Jr.'] },
    { id: 'rock-d15', d: 3, t: 'Quel groupe de Seattle mené par Eddie Vedder a sorti l\'album « Ten » ?', a: 'Pearl Jam', x: ['Nirvana', 'Soundgarden', 'Mudhoney'] },
    // --- Pro (20) ---
    { id: 'rock-p1', d: 4, t: 'Quel groupe britannique, avec Pete Townshend, détruisait ses instruments sur scène ?', a: 'the Who', x: ['the Kinks', 'the Yardbirds', 'Small Faces'] },
    { id: 'rock-p2', d: 4, t: 'Quel bassiste des Beatles est gaucher ?', a: 'Paul McCartney', x: ['John Lennon', 'George Harrison', 'Ringo Starr'] },
    { id: 'rock-p3', d: 4, t: 'Quel guitariste de Led Zeppelin est réputé pour son jeu à l\'archet ?', a: 'Jimmy Page', x: ['Jeff Beck', 'Eric Clapton', 'Ritchie Blackmore'] },
    { id: 'rock-p4', d: 4, t: 'Quel groupe britannique a créé le riff de « Smoke on the Water » ?', a: 'Deep Purple', x: ['Black Sabbath', 'Rainbow', 'Uriah Heep'] },
    { id: 'rock-p5', d: 4, t: 'Quel groupe de Los Angeles a sorti « Appetite for Destruction » en 1987 ?', a: "Guns N' Roses", x: ['Mötley Crüe', 'Poison', 'Ratt'] },
    { id: 'rock-p6', d: 4, t: 'Quel groupe glam de Los Angeles réunit Vince Neil et Nikki Sixx ?', a: 'Mötley Crüe', x: ['Poison', 'Ratt', 'Cinderella'] },
    { id: 'rock-p7', d: 4, t: 'Quel groupe de hard rock a été fondé par Ritchie Blackmore après Deep Purple ?', a: 'Rainbow', x: ['Whitesnake', 'Uriah Heep', 'Foreigner'] },
    { id: 'rock-p8', d: 4, t: 'Quel groupe du Sud des États-Unis a fait « Sweet Home Alabama » ?', a: 'Lynyrd Skynyrd', x: ['the Allman Brothers Band', 'ZZ Top', 'Molly Hatchet'] },
    { id: 'rock-p9', d: 4, t: 'Quel trio texan barbu a fait « La Grange » et « Gimme All Your Lovin\' » ?', a: 'ZZ Top', x: ['Lynyrd Skynyrd', 'the Doobie Brothers', 'Creedence Clearwater Revival'] },
    { id: 'rock-p10', d: 4, t: 'Quel Canadien, surnommé « the Godfather of Grunge », a fait « Heart of Gold » ?', a: 'Neil Young', x: ['Bob Dylan', 'Bruce Springsteen', 'Tom Petty'] },
    { id: 'rock-p11', d: 4, t: 'Quel auteur-compositeur du folk-rock a fait « Like a Rolling Stone » et a eu le Nobel ?', a: 'Bob Dylan', x: ['Neil Young', 'Leonard Cohen', 'Bruce Springsteen'] },
    { id: 'rock-p12', d: 4, t: 'Quel groupe britannique mené par Thom Yorke a fait « Creep » puis « OK Computer » ?', a: 'Radiohead', x: ['Blur', 'Muse', 'Coldplay'] },
    { id: 'rock-p13', d: 4, t: 'Quel trio anglais mené par Matthew Bellamy mêle rock et symphonique ?', a: 'Muse', x: ['Radiohead', 'Coldplay', 'Placebo'] },
    { id: 'rock-p14', d: 4, t: 'Quel duo de garage rock a fait « Seven Nation Army » ?', a: 'the White Stripes', x: ['the Strokes', 'the Black Keys', 'the Hives'] },
    { id: 'rock-p15', d: 4, t: 'Quel groupe de New York a lancé le renouveau rock des années 2000 avec « Is This It » ?', a: 'the Strokes', x: ['the White Stripes', 'Interpol', 'the Killers'] },
    { id: 'rock-p16', d: 4, t: 'Quel groupe de Sheffield mené par Alex Turner a percé avec son premier album en 2006 ?', a: 'Arctic Monkeys', x: ['the Libertines', 'Franz Ferdinand', 'Kasabian'] },
    { id: 'rock-p17', d: 4, t: 'Quel groupe mené par Billie Joe Armstrong a fait « Dookie » puis « American Idiot » ?', a: 'Green Day', x: ['the Offspring', 'Blink-182', 'Rancid'] },
    { id: 'rock-p18', d: 4, t: 'Quel groupe de pop-punk californien a fait « All the Small Things » ?', a: 'Blink-182', x: ['Green Day', 'Sum 41', 'Good Charlotte'] },
    { id: 'rock-p19', d: 4, t: 'Quel groupe mené par Chris Martin a fait « Yellow » et « Viva la Vida » ?', a: 'Coldplay', x: ['Keane', 'Snow Patrol', 'Travis'] },
    { id: 'rock-p20', d: 4, t: 'Quel groupe de rock alternatif mené par Billy Corgan a fait « 1979 » ?', a: 'the Smashing Pumpkins', x: ['Weezer', 'the Flaming Lips', 'Sonic Youth'] },
  ]),

  ...universe('musique', 'Rap', [
    // --- Faciles (5) ---
    { id: "rap-f1", d: 1, t: "De quel genre musical Eminem est-il une star ?", a: "Le rap", x: ["Le jazz", "La country", "Le reggae"] },
    { id: "rap-f2", d: 1, t: "Dans quel pays le hip-hop est-il né dans les années 1970 ?", a: "Aux États-Unis", x: ["En France", "Au Royaume-Uni", "En Jamaïque"] },
    { id: "rap-f3", d: 1, t: "Comment appelle-t-on celui qui pose des paroles rythmées sur un beat ?", a: "Un rappeur", x: ["Un chef d'orchestre", "Un crooner", "Un choriste"], acc: ["rappeur", "mc"] },
    { id: "rap-f4", d: 1, t: "Quel rappeur canadien a explosé avec « God's Plan » et « One Dance » ?", a: "Drake", x: ["Eminem", "Kanye West", "Travis Scott"] },
    { id: "rap-f5", d: 1, t: "Quel art de rue accompagne souvent la culture hip-hop sur les murs ?", a: "Le graffiti", x: ["La sculpture", "L'aquarelle", "La broderie"] },
    // --- Moyennes (10) ---
    { id: "rap-m1", d: 2, t: "Dans quel quartier de New York le hip-hop est-il né ?", a: "Le Bronx", x: ["Brooklyn", "Harlem", "Queens"] },
    { id: "rap-m2", d: 2, t: "Quel rappeur français forme le groupe NTM avec JoeyStarr ?", a: "Kool Shen", x: ["MC Solaar", "Booba", "Oxmo Puccino"] },
    { id: "rap-m3", d: 2, t: "Quel pionnier français du rap a sorti « Caroline » et « Bouge de là » ?", a: "MC Solaar", x: ["Booba", "Nekfeu", "Orelsan"] },
    { id: "rap-m4", d: 2, t: "Quel rappeur d'Orléans a sorti l'album « Civilisation » ?", a: "Orelsan", x: ["Nekfeu", "Kaaris", "Damso"] },
    { id: "rap-m5", d: 2, t: "Quel groupe de Compton, avec Dr. Dre et Ice Cube, a marqué le gangsta rap ?", a: "N.W.A", x: ["Wu-Tang Clan", "Public Enemy", "Run-D.M.C."] },
    { id: "rap-m6", d: 2, t: "Quel producteur de la côte Ouest a lancé les carrières d'Eminem et de 50 Cent ?", a: "Dr. Dre", x: ["Snoop Dogg", "Jay-Z", "Diddy"] },
    { id: "rap-m7", d: 2, t: "Quel rappeur new-yorkais, mari de Beyoncé, est un magnat du hip-hop ?", a: "Jay-Z", x: ["Nas", "Kanye West", "Diddy"] },
    { id: "rap-m8", d: 2, t: "Quel duo de frères toulousains chante « Dommage » ?", a: "Bigflo & Oli", x: ["PNL", "Casseurs Flowters", "1995"] },
    { id: "rap-m9", d: 2, t: "Quel duo français au style planant a sorti « À l'ammoniaque » ?", a: "PNL", x: ["Bigflo & Oli", "1995", "Suprême NTM"] },
    { id: "rap-m10", d: 2, t: "Quel rappeur belge sombre a sorti « Ipséité » et « Lithopédion » ?", a: "Damso", x: ["Booba", "Gazo", "Ninho"] },
    // --- Dures (15) ---
    { id: "rap-d1", d: 3, t: "Quel rappeur de la côte Ouest a été assassiné par balle en 1996 ?", a: "2Pac", x: ["The Notorious B.I.G.", "Snoop Dogg", "Nas"], acc: ["tupac", "2pac", "tupac shakur"] },
    { id: "rap-d2", d: 3, t: "Quel rappeur new-yorkais, rival de 2Pac, a été tué en 1997 ?", a: "The Notorious B.I.G.", x: ["Nas", "Jay-Z", "Ice Cube"], acc: ["biggie", "notorious big"] },
    { id: "rap-d3", d: 3, t: "Quel collectif new-yorkais au style « kung-fu » compte RZA, GZA et Method Man ?", a: "Wu-Tang Clan", x: ["N.W.A", "Public Enemy", "A Tribe Called Quest"] },
    { id: "rap-d4", d: 3, t: "Quel album d'Eminem de 2000 est l'un des plus vendus du rap ?", a: "The Marshall Mathers LP", x: ["The Eminem Show", "Recovery", "Encore"] },
    { id: "rap-d5", d: 3, t: "Quel est le vrai nom d'Eminem ?", a: "Marshall Mathers", x: ["Curtis Jackson", "Shawn Carter", "Aubrey Graham"], acc: ["marshall mathers"] },
    { id: "rap-d6", d: 3, t: "Quel est le vrai nom de Jay-Z ?", a: "Shawn Carter", x: ["Marshall Mathers", "Curtis Jackson", "Andre Young"], acc: ["shawn carter"] },
    { id: "rap-d7", d: 3, t: "Quel rappeur français, ancien du groupe Lunatic, est surnommé « B2O » ?", a: "Booba", x: ["Rohff", "La Fouine", "Kaaris"], acc: ["booba"] },
    { id: "rap-d8", d: 3, t: "Quel rappeur a connu une célèbre altercation avec Booba à l'aéroport d'Orly ?", a: "Kaaris", x: ["Rohff", "Gims", "Nekfeu"] },
    { id: "rap-d9", d: 3, t: "Quel ex-membre de la Sexion d'Assaut a cartonné en solo avec « Sapés comme jamais » ?", a: "Gims", x: ["Black M", "Dadju", "Lefa"], acc: ["maître gims", "gims"] },
    { id: "rap-d10", d: 3, t: "Quel producteur américain a cofondé le label Def Jam ?", a: "Rick Rubin", x: ["Dr. Dre", "Timbaland", "Pharrell Williams"] },
    { id: "rap-d11", d: 3, t: "Quel rappeur d'Atlanta est connu pour le tube « Sicko Mode » ?", a: "Travis Scott", x: ["Future", "Lil Baby", "Gunna"] },
    { id: "rap-d12", d: 3, t: "Quel style de rap né à Atlanta se reconnaît à ses hi-hats rapides et ses 808 ?", a: "La trap", x: ["Le boom bap", "Le G-funk", "Le drill"], acc: ["trap"] },
    { id: "rap-d13", d: 3, t: "Quel rappeur américain a sorti « good kid, m.A.A.d city » et « DAMN. » ?", a: "Kendrick Lamar", x: ["J. Cole", "Drake", "Kanye West"] },
    { id: "rap-d14", d: 3, t: "Quel prix prestigieux Kendrick Lamar a-t-il remporté en 2018 pour l'album « DAMN. » ?", a: "Le prix Pulitzer", x: ["Un Oscar", "Le prix Nobel", "Une Victoire de la musique"], acc: ["pulitzer"] },
    { id: "rap-d15", d: 3, t: "Quel collectif de Marseille réunit Akhenaton et Shurik'n ?", a: "IAM", x: ["NTM", "Fonky Family", "Psy 4 de la Rime"] },
    // --- Pro (20) ---
    { id: "rap-p1", d: 4, t: "Quelle chanson de 1979 du Sugarhill Gang est l'un des premiers tubes hip-hop ?", a: "Rapper's Delight", x: ["The Message", "Fight the Power", "Walk This Way"] },
    { id: "rap-p2", d: 4, t: "Quel groupe engagé, avec Chuck D, a sorti « Fight the Power » ?", a: "Public Enemy", x: ["N.W.A", "Wu-Tang Clan", "Run-D.M.C."] },
    { id: "rap-p3", d: 4, t: "Quel morceau de N.W.A a fait scandale et attiré l'attention du FBI ?", a: "Fuck tha Police", x: ["California Love", "Nuthin' but a G Thang", "Gin and Juice"] },
    { id: "rap-p4", d: 4, t: "Quel rappeur et acteur français, ex-1995, a sorti « Feu » et « Les Étoiles vagabondes » ?", a: "Nekfeu", x: ["Orelsan", "Damso", "Vald"] },
    { id: "rap-p5", d: 4, t: "Quelle série documentaire retrace la vie d'Orelsan sur Prime Video ?", a: "Montre jamais ça à personne", x: ["Validé", "Le Monde de demain", "Rimes et châtiments"] },
    { id: "rap-p6", d: 4, t: "Quel label de Suge Knight et Dr. Dre dominait le rap West Coast dans les années 1990 ?", a: "Death Row Records", x: ["Bad Boy Records", "Def Jam", "Cash Money"] },
    { id: "rap-p7", d: 4, t: "Quel label de la côte Est, fondé par Puff Daddy, était le rival de Death Row ?", a: "Bad Boy Records", x: ["Death Row Records", "Roc-A-Fella", "Aftermath"] },
    { id: "rap-p8", d: 4, t: "Quel rappeur a fondé le label Aftermath et une célèbre marque de casques audio ?", a: "Dr. Dre", x: ["Jay-Z", "50 Cent", "Snoop Dogg"] },
    { id: "rap-p9", d: 4, t: "Quel rappeur a fondé le label Roc-A-Fella puis dirigé Def Jam ?", a: "Jay-Z", x: ["Nas", "Diddy", "Dr. Dre"] },
    { id: "rap-p10", d: 4, t: "Quel jeune rappeur américain est mort en 2018, popularisant « SAD! » ?", a: "XXXTentacion", x: ["Juice WRLD", "Lil Peep", "Pop Smoke"] },
    { id: "rap-p11", d: 4, t: "Quel rappeur de Chicago a sorti « The College Dropout » en 2004 ?", a: "Kanye West", x: ["Common", "Lupe Fiasco", "Chance the Rapper"] },
    { id: "rap-p12", d: 4, t: "Comment appelle-t-on un duel de rap improvisé où chacun cherche à humilier l'autre ?", a: "Un rap battle", x: ["Un sample", "Un featuring", "Un remix"], acc: ["battle", "clash"] },
    { id: "rap-p13", d: 4, t: "Comment appelle-t-on le fait de réutiliser un extrait d'un morceau existant dans un beat ?", a: "Un sample", x: ["Un clash", "Un featuring", "Un skit"], acc: ["sample", "sampling"] },
    { id: "rap-p14", d: 4, t: "Quel album de NTM de 1998 contient « Laisse pas traîner ton fils » ?", a: "Suprême NTM", x: ["Paris sous les bombes", "1993... J'appuie sur la gâchette", "Authentik"] },
    { id: "rap-p15", d: 4, t: "Quel rappeur a sorti « To Pimp a Butterfly », salué pour son jazz et son engagement ?", a: "Kendrick Lamar", x: ["J. Cole", "Kanye West", "Childish Gambino"] },
    { id: "rap-p16", d: 4, t: "Quel rappeur et acteur, ancien des Fugees, a fait équipe avec Lauryn Hill ?", a: "Wyclef Jean", x: ["Pras", "will.i.am", "Andre 3000"] },
    { id: "rap-p17", d: 4, t: "Quel duo d'Atlanta, avec André 3000 et Big Boi, a sorti « Hey Ya! » ?", a: "OutKast", x: ["Wu-Tang Clan", "Mobb Deep", "UGK"] },
    { id: "rap-p18", d: 4, t: "Quelle rappeuse américaine a dominé les charts avec « WAP » et « Bodak Yellow » ?", a: "Cardi B", x: ["Nicki Minaj", "Megan Thee Stallion", "Doja Cat"] },
    { id: "rap-p19", d: 4, t: "Quelle rappeuse a lancé sa carrière avec l'album « Pink Friday » ?", a: "Nicki Minaj", x: ["Cardi B", "Lil' Kim", "Missy Elliott"] },
    { id: "rap-p20", d: 4, t: "Quel rappeur marseillais très prolifique a créé son label « D'or et de platine » ?", a: "Jul", x: ["SCH", "Soprano", "Alonzo"] },
  ]),
];
