import type { Question } from '../../../core/models';

export const musiqueQuestions: Question[] = [
  {
    id: 'musique-1',
    theme: 'musique',
    difficulty: 1,
    text: 'Quel groupe a chanté « Bohemian Rhapsody » ?',
    answer: 'Queen',
    distractors: ['The Beatles', 'The Rolling Stones', 'Led Zeppelin'],
  },
  {
    id: 'musique-2',
    theme: 'musique',
    difficulty: 2,
    text: 'Quelle chanteuse est surnommée « Queen B » ?',
    answer: 'Beyoncé',
    acceptable: ['beyonce'],
    distractors: ['Rihanna', 'Lady Gaga', 'Adele'],
  },
  {
    id: 'musique-3',
    theme: 'musique',
    difficulty: 1,
    text: 'Combien de cordes possède une guitare classique standard ?',
    answer: '6',
    acceptable: ['six'],
    distractors: ['4', '5', '12'],
    hints: ['Une basse en a quatre.'],
  },
  {
    id: 'musique-4',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel artiste a sorti l\'album « Thriller » ?',
    answer: 'Michael Jackson',
    acceptable: ['jackson'],
    distractors: ['Prince', 'Stevie Wonder', 'Lionel Richie'],
  },
  {
    id: 'musique-5',
    theme: 'musique',
    difficulty: 3,
    text: 'De quelle ville anglaise est originaire le groupe The Beatles ?',
    answer: 'Liverpool',
    distractors: ['Londres', 'Manchester', 'Birmingham'],
  },
  {
    id: 'musique-6',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel duo français masqué a composé « Get Lucky » et « One More Time » ?',
    answer: 'Daft Punk',
    distractors: ['Justice', 'Modjo', 'Cassius'],
  },
  {
    id: 'musique-7',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel rappeur américain est surnommé « Slim Shady » ?',
    answer: 'Eminem',
    distractors: ['Jay-Z', '50 Cent', 'Dr. Dre'],
  },
  {
    id: 'musique-8',
    theme: 'musique',
    difficulty: 3,
    text: 'Quel compositeur, devenu sourd, a écrit la 9e symphonie (« Ode à la joie ») ?',
    answer: 'Beethoven',
    distractors: ['Mozart', 'Bach', 'Chopin'],
  },
  {
    id: 'musique-9',
    theme: 'musique',
    difficulty: 1,
    text: 'Quelle chanteuse a sorti « Shake It Off » et l\'album « 1989 » ?',
    answer: 'Taylor Swift',
    acceptable: ['swift'],
    distractors: ['Katy Perry', 'Ariana Grande', 'Selena Gomez'],
  },
  {
    id: 'musique-10',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel groupe suédois a chanté « Dancing Queen » ?',
    answer: 'ABBA',
    distractors: ['Ace of Base', 'Roxette', 'A-ha'],
  },
  {
    id: 'musique-11',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel groupe a sorti l\'album « The Dark Side of the Moon » ?',
    answer: 'Pink Floyd',
    distractors: ['Led Zeppelin', 'The Who', 'Genesis'],
  },
  {
    id: 'musique-12',
    theme: 'musique',
    difficulty: 4,
    text: 'Quel est le vrai nom de Lady Gaga ?',
    answer: 'Stefani Germanotta',
    acceptable: ['germanotta'],
    distractors: ['Robyn Fenty', 'Alecia Moore', 'Katheryn Hudson'],
  },
  {
    id: 'musique-13',
    theme: 'musique',
    difficulty: 3,
    text: 'De quel pays vient le groupe de metal Rammstein ?',
    answer: 'Allemagne',
    distractors: ['Autriche', 'Suède', 'Pays-Bas'],
  },
  {
    id: 'musique-14',
    theme: 'musique',
    difficulty: 4,
    text: 'En quelle année les Beatles se sont-ils officiellement séparés ?',
    answer: '1970',
    distractors: ['1968', '1972', '1965'],
  },
  {
    id: 'musique-15',
    theme: 'musique',
    difficulty: 3,
    text: 'Quelle artiste britannique a interprété « Rolling in the Deep » ?',
    answer: 'Adele',
    distractors: ['Sia', 'Duffy', 'Amy Winehouse'],
  },
  {
    id: 'musique-16',
    theme: 'musique',
    difficulty: 2,
    text: 'De quel instrument Jimi Hendrix était-il le maître ?',
    answer: 'La guitare',
    acceptable: ['guitare'],
    distractors: ['La batterie', 'Le piano', 'La basse'],
  },
  {
    id: 'musique-17',
    theme: 'musique',
    difficulty: 4,
    text: 'Combien de symphonies Beethoven a-t-il composées ?',
    answer: '9',
    distractors: ['7', '5', '12'],
  },
  {
    id: 'musique-18',
    theme: 'musique',
    difficulty: 2,
    text: 'Quel DJ français a produit « Titanium » avec Sia ?',
    answer: 'David Guetta',
    distractors: ['Bob Sinclar', 'Martin Solveig', 'DJ Snake'],
  },
  {
    id: 'musique-19',
    theme: 'musique',
    difficulty: 4,
    text: 'Quel album est le plus vendu de toute l\'histoire de la musique ?',
    answer: 'Thriller (Michael Jackson)',
    acceptable: ['thriller'],
    distractors: ['Back in Black', 'The Dark Side of the Moon', 'Their Greatest Hits (Eagles)'],
  },
  {
    id: 'musique-20',
    theme: 'musique',
    difficulty: 3,
    text: 'Quel groupe irlandais a pour chanteur Bono ?',
    answer: 'U2',
    distractors: ['Coldplay', 'The Cranberries', 'Oasis'],
  },
];
