import type { Question } from '../../../core/models';

// Rébus : devine le titre à partir des emojis affichés en grand.
export const rebusQuestions: Question[] = [
  {
    id: 'rebus-1',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🦁👑' },
    answer: 'Le Roi Lion',
    acceptable: ['roi lion', 'lion king'],
    distractors: ['Madagascar', 'Tarzan', 'Le Livre de la Jungle'],
  },
  {
    id: 'rebus-2',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🤖❤️🌱' },
    answer: 'Wall-E',
    acceptable: ['walle', 'wall e'],
    distractors: ['Transformers', 'Big Hero 6', 'Terminator'],
  },
  {
    id: 'rebus-3',
    theme: 'rebus',
    difficulty: 2,
    text: 'Quel super-héros ?',
    media: { type: 'emoji', emoji: '🕷️🧑' },
    answer: 'Spider-Man',
    acceptable: ['spiderman', 'spider man'],
    distractors: ['Ant-Man', 'Venom', 'Batman'],
  },
  {
    id: 'rebus-4',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🔍🐠' },
    answer: 'Le Monde de Nemo',
    acceptable: ['nemo', 'trouver nemo', 'finding nemo'],
    distractors: ['Le Monde de Dory', 'La Petite Sirène', 'Gang de requins'],
  },
  {
    id: 'rebus-5',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '👻🚫' },
    answer: 'SOS Fantômes',
    acceptable: ['ghostbusters', 'sos fantomes'],
    distractors: ['Casper', 'Beetlejuice', 'Insidious'],
  },
  {
    id: 'rebus-6',
    theme: 'rebus',
    difficulty: 2,
    text: 'Quel jeu vidéo ?',
    media: { type: 'emoji', emoji: '🍄🔧👨' },
    answer: 'Super Mario',
    acceptable: ['mario', 'super mario bros'],
    distractors: ["Luigi's Mansion", 'Donkey Kong', 'Sonic'],
  },
  {
    id: 'rebus-7',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quel jeu vidéo ?',
    media: { type: 'emoji', emoji: '🗡️🛡️🧝‍♂️🐉' },
    answer: 'The Legend of Zelda',
    acceptable: ['zelda'],
    distractors: ['Dark Souls', 'Skyrim', 'Monster Hunter'],
  },
  {
    id: 'rebus-8',
    theme: 'rebus',
    difficulty: 4,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '🦇🃏' },
    answer: 'The Dark Knight',
    acceptable: ['the dark knight', 'batman the dark knight', 'chevalier noir'],
    distractors: ['Joker', 'Batman Begins', 'The Batman'],
  },
  {
    id: 'rebus-9',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '❄️⛄👑' },
    answer: 'La Reine des Neiges',
    acceptable: ['frozen', 'reine des neiges'],
    distractors: ["L'Âge de Glace", 'Happy Feet', 'Raiponce'],
  },
  {
    id: 'rebus-10',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quelle série ?',
    media: { type: 'emoji', emoji: '⚗️👨‍🔬🔵' },
    answer: 'Breaking Bad',
    distractors: ['Dexter', 'The Wire', 'Ozark'],
  },
  {
    id: 'rebus-11',
    theme: 'rebus',
    difficulty: 2,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '🚢🧊💔' },
    answer: 'Titanic',
    distractors: ['Poséidon', 'En pleine tempête', 'Le Chant du loup'],
  },
  {
    id: 'rebus-12',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '👽📞🏠' },
    answer: 'E.T.',
    acceptable: ['et', "et l'extraterrestre", 'e t'],
    distractors: ['Paul', 'Mars Attacks', 'La Soupe aux choux'],
  },
  {
    id: 'rebus-13',
    theme: 'rebus',
    difficulty: 2,
    text: 'Quel jeu vidéo ?',
    media: { type: 'emoji', emoji: '🟩🟫⛏️🐷' },
    answer: 'Minecraft',
    distractors: ['Roblox', 'Lego', 'Terraria'],
  },
  {
    id: 'rebus-14',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quelle saga de films ?',
    media: { type: 'emoji', emoji: '🧙‍♂️💍🌋' },
    answer: 'Le Seigneur des Anneaux',
    acceptable: ['seigneur des anneaux', 'lotr'],
    distractors: ['Harry Potter', 'Le Hobbit', 'Willow'],
  },
  {
    id: 'rebus-15',
    theme: 'rebus',
    difficulty: 2,
    text: 'Quelle saga ?',
    media: { type: 'emoji', emoji: '⚡🤓🧙‍♂️' },
    answer: 'Harry Potter',
    distractors: ['Le Seigneur des Anneaux', 'Merlin', 'Le Monde de Narnia'],
  },
  {
    id: 'rebus-16',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quel manga ?',
    media: { type: 'emoji', emoji: '🏴‍☠️👒🍖' },
    answer: 'One Piece',
    distractors: ['Naruto', 'Bleach', 'Hunter x Hunter'],
  },
  {
    id: 'rebus-17',
    theme: 'rebus',
    difficulty: 4,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🤠🚀♾️' },
    answer: 'Toy Story',
    distractors: ["Buzz l'Éclair", 'Cars', 'Là-haut'],
    hints: ['« Vers lʼinfini et au-delà ! »'],
  },
  {
    id: 'rebus-18',
    theme: 'rebus',
    difficulty: 3,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🟢👹🧅' },
    answer: 'Shrek',
    distractors: ['Hulk', 'Monstres et Cie', 'Le Grinch'],
    hints: ["« Les ogres, c'est comme les oignons. »"],
  },
  {
    id: 'rebus-19',
    theme: 'rebus',
    difficulty: 4,
    text: 'Quel jeu vidéo ?',
    media: { type: 'emoji', emoji: '🔫🟠🌀' },
    answer: 'Portal',
    distractors: ['Half-Life', 'Splatoon', 'Quantum Break'],
  },
  {
    id: 'rebus-20',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🚗⚡🏁' },
    answer: 'Cars',
    distractors: ['Turbo', 'Ratchet', 'Fast & Furious'],
  },
  {
    id: 'rebus-21',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quelle série ?',
    media: { type: 'emoji', emoji: '🐉👑⚔️🩸' },
    answer: 'Game of Thrones',
    acceptable: ['got', 'le trône de fer'],
    distractors: ['Vikings', 'The Witcher', 'House of the Dragon'],
  },
  {
    id: 'rebus-22',
    theme: 'rebus',
    difficulty: 4,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '👨‍🚀🥔🔴' },
    answer: 'Seul sur Mars',
    acceptable: ['the martian', 'seul sur mars'],
    distractors: ['Gravity', 'Interstellar', 'Apollo 13'],
  },
  {
    id: 'rebus-23',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quel jeu vidéo ?',
    media: { type: 'emoji', emoji: '🐦🟩🐷💥' },
    answer: 'Angry Birds',
    distractors: ['Bad Piggies', 'Flappy Bird', 'Crossy Road'],
  },
  {
    id: 'rebus-24',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '👵🎈🏠🐶' },
    answer: 'Là-haut',
    acceptable: ['la-haut', 'là-haut', 'up'],
    distractors: ['Coco', 'Vice-versa', 'Ratatouille'],
  },
  {
    id: 'rebus-25',
    theme: 'rebus',
    difficulty: 3,
    text: 'Quel personnage de film ?',
    media: { type: 'emoji', emoji: '🕴️🔫🇬🇧🍸' },
    answer: 'James Bond',
    acceptable: ['james bond', '007'],
    distractors: ['Mission Impossible', 'Kingsman', 'John Wick'],
  },
  {
    id: 'rebus-26',
    theme: 'rebus',
    difficulty: 4,
    text: 'Quel film Marvel ?',
    media: { type: 'emoji', emoji: '🧤💎🫰💨' },
    answer: 'Avengers: Infinity War',
    acceptable: ['infinity war', 'avengers infinity war'],
    distractors: ['Avengers: Endgame', 'Justice League', 'Eternals'],
  },
  {
    id: 'rebus-27',
    theme: 'rebus',
    difficulty: 2,
    text: 'Quel jeu vidéo rétro ?',
    media: { type: 'emoji', emoji: '🟡👻👾' },
    answer: 'Pac-Man',
    acceptable: ['pacman', 'pac-man'],
    distractors: ['Snake', 'Dig Dug', 'Q*bert'],
  },
  {
    id: 'rebus-28',
    theme: 'rebus',
    difficulty: 4,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '🤐🐑🍷' },
    answer: 'Le Silence des agneaux',
    acceptable: ['silence des agneaux', 'silence of the lambs'],
    distractors: ['Seven', 'Hannibal', 'Zodiac'],
  },
  {
    id: 'rebus-29',
    theme: 'rebus',
    difficulty: 2,
    text: "Quel film d'animation ?",
    media: { type: 'emoji', emoji: '🐀👨‍🍳🍝' },
    answer: 'Ratatouille',
    distractors: ['Bee Movie', 'Cuisine', 'Gusteau'],
  },
  {
    id: 'rebus-30',
    theme: 'rebus',
    difficulty: 4,
    text: 'Quel film ?',
    media: { type: 'emoji', emoji: '🦖🏝️🧬' },
    answer: 'Jurassic Park',
    acceptable: ['jurassic park'],
    distractors: ['King Kong', 'Godzilla', 'Le Monde Perdu'],
  },
];
