import type { Question } from '../../../core/models';

export const seriesQuestions: Question[] = [
  {
    id: 'serie-1',
    theme: 'series',
    difficulty: 1,
    text: 'Dans Game of Thrones, quelle maison a pour devise « Winter is coming » ?',
    answer: 'Stark',
    distractors: ['Lannister', 'Targaryen', 'Baratheon'],
  },
  {
    id: 'serie-2',
    theme: 'series',
    difficulty: 2,
    text: 'Quelle série espagnole suit un braquage avec masques de Dalí et combinaisons rouges ?',
    answer: 'La Casa de Papel',
    acceptable: ['casa de papel', 'money heist'],
    distractors: ['Vis a vis', 'Élite', 'Toy Boy'],
  },
  {
    id: 'serie-3',
    theme: 'series',
    difficulty: 1,
    text: 'Dans Breaking Bad, quel est le métier initial de Walter White ?',
    answer: 'Professeur de chimie',
    acceptable: ['prof de chimie', 'chimie'],
    distractors: ['Médecin', 'Avocat', 'Policier'],
    hints: ['Il enseigne dans un lycée.'],
  },
  {
    id: 'serie-4',
    theme: 'series',
    difficulty: 2,
    text: 'Dans Stranger Things, comment surnomme-t-on la jeune fille aux pouvoirs ?',
    answer: 'Eleven (Onze)',
    acceptable: ['eleven', 'onze', 'el'],
    distractors: ['Max', 'Nancy', 'Robin'],
  },
  {
    id: 'serie-5',
    theme: 'series',
    difficulty: 3,
    text: 'Dans Friends, quel est le nom de famille de Chandler ?',
    answer: 'Bing',
    distractors: ['Geller', 'Tribbiani', 'Green'],
    hints: ['Chandler ___ .'],
  },
  {
    id: 'serie-6',
    theme: 'series',
    difficulty: 1,
    text: 'Quelle série animée suit une famille jaune vivant à Springfield ?',
    answer: 'Les Simpson',
    acceptable: ['simpsons', 'the simpsons'],
    distractors: ['Family Guy', 'Futurama', 'South Park'],
  },
  {
    id: 'serie-7',
    theme: 'series',
    difficulty: 2,
    text: 'Dans The Office (US), qui est le patron de la succursale de Scranton ?',
    answer: 'Michael Scott',
    acceptable: ['michael'],
    distractors: ['Jim Halpert', 'Dwight Schrute', 'Andy Bernard'],
  },
  {
    id: 'serie-8',
    theme: 'series',
    difficulty: 3,
    text: 'En quelle année a débuté la série britannique Doctor Who (série classique) ?',
    answer: '1963',
    distractors: ['1970', '1955', '1980'],
  },
  {
    id: 'serie-9',
    theme: 'series',
    difficulty: 2,
    text: 'Dans Peaky Blinders, quelle famille règne sur Birmingham ?',
    answer: 'Les Shelby',
    acceptable: ['shelby'],
    distractors: ['Les Solomons', 'Les Gray', 'Les Changretta'],
  },
  {
    id: 'serie-10',
    theme: 'series',
    difficulty: 1,
    text: 'Quelle série met en scène des chirurgiens au Seattle Grace Hospital ?',
    answer: "Grey's Anatomy",
    acceptable: ['greys anatomy'],
    distractors: ['Dr House', 'Urgences', 'New Amsterdam'],
  },
  {
    id: 'serie-11',
    theme: 'series',
    difficulty: 2,
    text: 'Dans la série Netflix The Witcher, quel acteur incarne Geralt de Riv ?',
    answer: 'Henry Cavill',
    distractors: ['Chris Hemsworth', 'Hugh Jackman', 'Charlie Hunnam'],
  },
  {
    id: 'serie-12',
    theme: 'series',
    difficulty: 3,
    text: 'Dans Breaking Bad, quel pseudonyme se donne Walter White ?',
    answer: 'Heisenberg',
    distractors: ['Capone', 'Scarface', 'Maverick'],
  },
  {
    id: 'serie-13',
    theme: 'series',
    difficulty: 2,
    text: 'Dans How I Met Your Mother, quel personnage répète « Legen... wait for it... dary » ?',
    answer: 'Barney',
    acceptable: ['barney stinson'],
    distractors: ['Ted', 'Marshall', 'Lily'],
  },
  {
    id: 'serie-14',
    theme: 'series',
    difficulty: 3,
    text: 'Combien de saisons compte la série Game of Thrones ?',
    answer: '8',
    distractors: ['7', '9', '10'],
  },
  {
    id: 'serie-15',
    theme: 'series',
    difficulty: 4,
    text: 'Dans quelle ville américaine se déroule la série The Wire ?',
    answer: 'Baltimore',
    distractors: ['Detroit', 'Chicago', 'Philadelphie'],
  },
  {
    id: 'serie-16',
    theme: 'series',
    difficulty: 2,
    text: 'Quel est le thème central de la série allemande Dark ?',
    answer: 'Le voyage dans le temps',
    acceptable: ['voyage dans le temps', 'temps'],
    distractors: ['Les extraterrestres', 'Les fantômes', 'La télépathie'],
  },
  {
    id: 'serie-17',
    theme: 'series',
    difficulty: 3,
    text: 'Dans Better Call Saul, quel est le vrai nom de Saul Goodman ?',
    answer: 'Jimmy McGill',
    acceptable: ['jimmy', 'mcgill'],
    distractors: ['Chuck McGill', 'Howard Hamlin', 'Gus Fring'],
  },
  {
    id: 'serie-18',
    theme: 'series',
    difficulty: 4,
    text: "En quelle année s'est terminée la série Friends ?",
    answer: '2004',
    distractors: ['2006', '2002', '2000'],
  },
  {
    id: 'serie-19',
    theme: 'series',
    difficulty: 2,
    text: 'Dans Squid Game, de quelle couleur sont les survêtements des joueurs ?',
    answer: 'Vert',
    distractors: ['Rouge', 'Bleu', 'Jaune'],
  },
  {
    id: 'serie-20',
    theme: 'series',
    difficulty: 3,
    text: "Dans Lost, comment appelle-t-on les habitants mystérieux de l'île ?",
    answer: 'Les Autres',
    acceptable: ['the others', 'autres'],
    distractors: ['Les Initiés', 'Les Anciens', 'Les Perdus'],
  },
];
