/**
 * Banque d'affirmations « Qui est le plus susceptible… ». Chaque entrée complète
 * la phrase « Qui est le plus susceptible … ? » (affichée par l'écran de jeu).
 * On reste bon enfant et taquin, jamais méchant ou intime.
 */
export const PROMPTS: string[] = [
  "de finir la soirée endormi sur le canapé",
  "d'envoyer un message qu'il regrettera demain",
  "de devenir célèbre un jour",
  "de rire à sa propre blague",
  "d'oublier où il a garé la voiture",
  "de pleurer devant un film d'animation",
  "de danser sur la table",
  "de répondre au téléphone en réunion",
  "de manger le dernier bout de pizza sans demander",
  "de se perdre dans une ville qu'il connaît",
  "de survivre à une apocalypse zombie",
  "de devenir prof un jour",
  "d'oublier l'anniversaire d'un proche",
  "de dire « je t'aime » trop tôt",
  "de rater son réveil un jour important",
  "de commander toujours la même chose au restau",
  "de parler à un inconnu dans le métro",
  "de croire à une théorie farfelue",
  "de gagner à un jeu télévisé",
  "d'exploser son forfait data",
  "de refaire trois fois la même histoire",
  "de chanter sous la douche à tue-tête",
  "de garder un secret… ou pas",
  "de tomber amoureux en vacances",
  "de rater un penalty décisif",
  "de finir milliardaire",
  "de se disputer pour une série",
  "de pleurer de rire en soirée",
  "de tout miser sur un coup de tête",
  "de devenir influenceur",
  "d'avoir toujours une anecdote sur tout",
  "de perdre son téléphone en soirée",
  "de dire oui à n'importe quel défi",
  "de cuisiner un plat immangeable",
  "de retweeter une fake news",
  "d'arriver en retard à son propre mariage",
  "de faire une sieste à une fête",
  "de collectionner un truc bizarre",
  "de se relever la nuit pour grignoter",
  "de rougir pour un rien",
  "de devenir le boss un jour",
  "de proposer un after à 4h du matin",
  "de parler tout seul",
  "d'oublier ce qu'il allait dire en plein milieu",
  "de fondre devant un chiot",
  "de sécher un cours pour dormir",
  "de râler pour la température de la pièce",
  "de connaître les paroles de toutes les chansons",
  "de prendre 100 photos du même plat",
  "de lancer un débat interminable",
  "de rester le dernier à table",
  "de vouloir toujours avoir raison",
  "de partir en voyage sur un coup de tête",
  "de rire au pire moment",
  "de devenir la mascotte du groupe",
];
