import { filterHot } from '../../core/contentLevel';
import type { CancelLevel } from '../../core/models';

/**
 * Banque d'affirmations « Qui est le plus susceptible… ». Chaque entrée complète
 * la phrase « Qui est le plus susceptible … ? » (affichée par l'écran de jeu).
 * On reste bon enfant et taquin, jamais méchant ou intime.
 */
export const PROMPTS: string[] = [
  "de finir la soirée endormi sur le canapé",
  "d'envoyer un message qu'il regrettera demain",
  "de devenir célèbre un jour",
  "de rire à sa propre blague",
  "d'oublier où il a garé la voiture",
  "de pleurer devant un film d'animation",
  "de danser sur la table",
  "de répondre au téléphone en réunion",
  "de manger le dernier bout de pizza sans demander",
  "de se perdre dans une ville qu'il connaît",
  "de survivre à une apocalypse zombie",
  "de devenir prof un jour",
  "d'oublier l'anniversaire d'un proche",
  "de dire « je t'aime » trop tôt",
  "de rater son réveil un jour important",
  "de commander toujours la même chose au restau",
  "de parler à un inconnu dans le métro",
  "de croire à une théorie farfelue",
  "de gagner à un jeu télévisé",
  "d'exploser son forfait data",
  "de refaire trois fois la même histoire",
  "de chanter sous la douche à tue-tête",
  "de garder un secret… ou pas",
  "de tomber amoureux en vacances",
  "de rater un penalty décisif",
  "de finir milliardaire",
  "de se disputer pour une série",
  "de pleurer de rire en soirée",
  "de tout miser sur un coup de tête",
  "de devenir influenceur",
  "d'avoir toujours une anecdote sur tout",
  "de perdre son téléphone en soirée",
  "de dire oui à n'importe quel défi",
  "de cuisiner un plat immangeable",
  "de retweeter une fake news",
  "d'arriver en retard à son propre mariage",
  "de faire une sieste à une fête",
  "de collectionner un truc bizarre",
  "de se relever la nuit pour grignoter",
  "de rougir pour un rien",
  "de devenir le boss un jour",
  "de proposer un after à 4h du matin",
  "de parler tout seul",
  "d'oublier ce qu'il allait dire en plein milieu",
  "de fondre devant un chiot",
  "de sécher un cours pour dormir",
  "de râler pour la température de la pièce",
  "de connaître les paroles de toutes les chansons",
  "de prendre 100 photos du même plat",
  "de lancer un débat interminable",
  "de rester le dernier à table",
  "de vouloir toujours avoir raison",
  "de partir en voyage sur un coup de tête",
  "de rire au pire moment",
  "de devenir la mascotte du groupe",
  // --- Soirée & fêtes ---
  "de lancer la première danse de la soirée",
  "de proposer un dernier verre alors qu'il est tard",
  "de s'endormir avant la fin du film",
  "de connaître le nom de tous les invités en 5 minutes",
  "d'organiser la prochaine soirée du groupe",
  "de ramener quelque chose à grignoter sans qu'on lui demande",
  "de perdre au premier jeu et vouloir une revanche",
  "de raconter la même anecdote à chaque soirée",
  "de rester discuter dans l'entrée pendant une heure",
  "de transformer une réunion en fou rire",
  "de proposer un karaoké improvisé",
  "de finir la playlist à sa sauce",
  "de rater la photo de groupe en fermant les yeux",
  "de vouloir refaire une partie « juste une dernière »",
  "d'être le dernier à comprendre la blague",
  // --- Voyage & aventure ---
  "de rater son train pour cinq minutes",
  "de partir en voyage avec un seul sac",
  "de vouloir tout visiter en une journée",
  "d'oublier son passeport le jour du départ",
  "de improviser un itinéraire au dernier moment",
  "de goûter le plat le plus étrange du menu",
  "de se lier d'amitié avec un inconnu en vacances",
  "de prendre 500 photos et n'en garder aucune",
  "de vouloir dormir à la belle étoile",
  "de négocier un prix sur un marché",
  "de se perdre volontairement pour explorer",
  "de rater l'heure du réveil un jour d'excursion",
  // --- Tech & réseaux ---
  "de répondre à un mail à 2h du matin",
  "d'avoir 300 onglets ouverts",
  "de tomber dans un tunnel de vidéos jusqu'à l'aube",
  "de commenter tout ce qu'il regarde",
  "d'oublier de mettre son téléphone en silencieux",
  "de partager un article sans l'avoir lu",
  "de garder 10 000 photos non triées",
  "de demander de l'aide à une IA pour un rien",
  "de perdre une heure à choisir un fond d'écran",
  "de recharger son téléphone toutes les deux heures",
  "de découvrir une appli et en parler pendant une semaine",
  "de répondre « ok » à un long message",
  // --- Cuisine & nourriture ---
  "de tester une recette compliquée un soir de semaine",
  "de manger debout devant le frigo",
  "de saler avant même de goûter",
  "de commander le même plat partout",
  "de finir les restes de tout le monde",
  "de rater un gâteau mais le servir quand même",
  "de connaître le meilleur resto de chaque quartier",
  "de reprendre du dessert « juste un peu »",
  "de cacher des snacks pour lui tout seul",
  "de tenter le piment le plus fort par défi",
  "de faire brûler des pâtes",
  "d'improviser un plat avec trois ingrédients",
  // --- Boulot & études ---
  "d'arriver pile à l'heure, jamais en avance",
  "de prendre des notes que personne ne comprend",
  "de proposer une idée en réunion et la regretter",
  "de repousser une tâche jusqu'à la dernière minute",
  "de devenir le chef un jour",
  "de transformer une pause café en longue discussion",
  "de répondre présent pour un projet de dernière minute",
  "de garder son calme sous pression",
  "de tout planifier dans un agenda coloré",
  "de bosser mieux la veille au soir",
  // --- Sport & défis ---
  "de s'inscrire à la salle en janvier et arrêter en février",
  "de vouloir gagner même à un jeu pour enfants",
  "de tenter un record inutile pour la gloire",
  "de courir un marathon sur un coup de tête",
  "de commenter le match plus fort que les joueurs",
  "d'oublier de s'échauffer et le regretter",
  "de relever n'importe quel pari",
  "de danser plus longtemps que tout le monde",
  "de proposer une rando « facile » qui n'en est pas une",
  "de fêter une victoire comme si c'était la finale",
  // --- Caractère & habitudes (bon enfant) ---
  "de rire nerveusement dans un moment sérieux",
  "de dire oui puis de le regretter",
  "de tout ranger par couleur",
  "de parler aux animaux comme à des humains",
  "de s'excuser même quand ce n'est pas sa faute",
  "de garder un ticket de caisse « au cas où »",
  "de commencer dix projets en même temps",
  "de connaître un raccourci pour tout",
  "de fredonner sans s'en rendre compte",
  "de retenir les anniversaires de tout le monde",
  "de donner un surnom à chacun",
  "de vérifier trois fois s'il a bien fermé la porte",
  "de prendre la parole pour défendre les autres",
  "de garder son sang-froid quand tout part en vrille",
  "de dire tout haut ce que les autres pensent tout bas",
  // --- Situations cocasses ---
  "de saluer quelqu'un qui ne lui disait pas bonjour",
  "de se tromper d'étage dans un immeuble",
  "de rire tout seul en repensant à un souvenir",
  "d'applaudir au mauvais moment",
  "de confondre deux personnes qui ne se ressemblent pas",
  "de chercher ses lunettes qu'il a sur le nez",
  "de tenir la porte trop longtemps à quelqu'un de loin",
  "d'oublier pourquoi il est entré dans une pièce",
  "de répondre à une question qu'on n'a pas posée",
  "de se relire trois fois avant d'envoyer un message",
  "de klaxonner d'un signe amical un inconnu",
  "de garder une plante en vie contre toute attente",
  // --- Argent & organisation ---
  "de proposer de partager l'addition en parts égales",
  "de retrouver un vieux billet dans une poche",
  "de comparer les prix pendant vingt minutes",
  "de craquer pour un gadget inutile",
  "de faire une liste puis de l'oublier à la maison",
  "de mettre de l'argent de côté « pour plus tard »",
  "d'offrir le meilleur cadeau du groupe",
  "de prêter sans jamais réclamer",
  // --- Culture & talents ---
  "de connaître les paroles d'une chanson des années 80",
  "de citer une réplique de film au bon moment",
  "de gagner à un quiz de culture générale",
  "de reconnaître une musique en deux notes",
  "de recommander un livre à tout le monde",
  "de repérer une erreur dans un film",
  "de retenir des dates historiques par cœur",
  "d'improviser une histoire pour endormir un enfant",
  // --- Nature & maison ---
  "de sauver une araignée au lieu de l'écraser",
  "d'avoir trop de plantes chez lui",
  "de vouloir adopter tous les animaux qu'il croise",
  "de recycler méticuleusement",
  "de repeindre une pièce sur un coup de tête",
  "de connaître le prénom du chat des voisins",
  "de ramasser un joli caillou en balade",
  "de râler dès qu'il fait trop chaud… ou trop froid",
  // --- Petites bravades du quotidien ---
  "de doubler tout le monde à pied dans la rue",
  "de finir le paquet et remettre l'emballage vide",
  "de chanter dans la voiture aux feux rouges",
  "de garder le meilleur pour la fin",
  "de tester le bouton « au cas où »",
  "de relancer un débat déjà clos",
  "de proposer de « juste jeter un œil » dans un magasin",
  "de dire « je gère » avant de ne rien gérer",
  // --- Rab ---
  "de garder un ticket de cinéma en souvenir",
  "de refaire le monde à 3h du matin",
  "d'apprendre un mot rare et le placer partout",
  "de féliciter tout le monde après une victoire d'équipe",
  "de connaître un bon plan pour chaque situation",
  "de proposer une pause quand ça devient tendu",
  "de rire avant même la chute de la blague",
  "de s'installer à la meilleure place du canapé",
  "de vouloir goûter à l'assiette des autres",
  "de garder espoir jusqu'au bout d'une partie mal engagée",
  "de motiver le groupe quand tout le monde fatigue",
  "de retenir le chemin après y être allé une fois",
  "de proposer un jeu quand il y a un blanc",
  "de complimenter la tenue de quelqu'un en premier",
  "de finir la phrase des autres",
  "de garder son calme dans une file d'attente interminable",
  "d'improviser un toast au bon moment",
  "de retrouver un objet perdu par quelqu'un d'autre",
  "de proposer de raccompagner tout le monde",
  "de transformer une galère en bonne histoire à raconter",
];

/** Affirmation taguée du niveau minimum de « cancellabilité » requis. */
export interface HotPrompt {
  text: string;
  lvl: CancelLevel;
}

/**
 * Contenu osé, du plus léger (2) au plus trash (4). Échantillon démonstratif (à
 * étoffer). Esprit « soirée entre adultes » — coquin, tabou, humour noir — sans
 * jamais viser ni rabaisser un groupe. Chaque entrée complète « Qui est le plus
 * susceptible … ? », comme la banque de base.
 */
export const PROMPTS_HOT: HotPrompt[] = [
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { text: "de finir la nuit chez quelqu'un rencontré ce soir", lvl: 2 },
  { text: "d'avoir un date secret que personne ne connaît", lvl: 2 },
  { text: "d'envoyer un message coquin à la mauvaise personne", lvl: 2 },
  { text: "de retomber dans les bras de son ex après deux verres", lvl: 2 },
  { text: "de flirter pour obtenir un service", lvl: 2 },
  { text: "de mentir sur son nombre de rencards", lvl: 2 },
  { text: "de craquer sur un(e) inconnu(e) en vacances", lvl: 2 },
  { text: "de stalker un ex à 2 h du matin", lvl: 2 },
  { text: "d'avoir déjà embrassé quelqu'un présent dans cette pièce", lvl: 2 },
  { text: "de tomber amoureux(se) en une seule soirée", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { text: "d'avoir un coup d'un soir cette semaine", lvl: 3 },
  { text: "d'avoir déjà couché dès le premier soir", lvl: 3 },
  { text: "d'avoir un fantasme qu'il/elle n'avouera jamais ici", lvl: 3 },
  { text: "d'avoir déjà envoyé une photo très osée", lvl: 3 },
  { text: "d'avoir une appli de rencontre ouverte en ce moment", lvl: 3 },
  { text: "d'avoir déjà tenté un plan à plusieurs", lvl: 3 },
  { text: "d'assumer le plus ses coups d'un soir", lvl: 3 },
  { text: "d'avoir couché avec quelqu'un présent ce soir", lvl: 3 },
  { text: "de parler de sa vie intime sans le moindre filtre", lvl: 3 },
  { text: "d'avoir déjà menti sur ses performances", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ -------------------------------------------
  { text: "d'avoir déjà trompé quelqu'un sans se faire prendre", lvl: 4 },
  { text: "de trahir un ami pour de l'argent", lvl: 4 },
  { text: "de finir en garde à vue un jour", lvl: 4 },
  { text: "de mentir à la police sans ciller", lvl: 4 },
  { text: "de garder l'argent d'un portefeuille trouvé", lvl: 4 },
  { text: "de rire au mauvais moment à un enterrement", lvl: 4 },
  { text: "de ghoster quelqu'un sans le moindre remords", lvl: 4 },
  { text: "de balancer un proche pour sauver sa peau", lvl: 4 },
  { text: "de cacher un secret qui détruirait le groupe", lvl: 4 },
  { text: "de revendre les cadeaux qu'on lui offre", lvl: 4 },

  // ===== Vague 2 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { text: "de retomber amoureux(se) de son ex pour la troisième fois", lvl: 2 },
  { text: "de draguer quelqu'un déjà en couple", lvl: 2 },
  { text: "d'avoir un crush secret sur quelqu'un dans cette pièce", lvl: 2 },
  { text: "de mentir sur son âge sur une appli de rencontre", lvl: 2 },
  { text: "de pleurer une rupture pendant des mois", lvl: 2 },
  { text: "de collectionner les matchs sans jamais oser y aller", lvl: 2 },
  { text: "de sortir avec quelqu'un juste pour rendre un ex jaloux", lvl: 2 },
  { text: "de flasher sur le/la pote de son/sa pote", lvl: 2 },
  { text: "de faire le premier pas très maladroitement", lvl: 2 },
  { text: "de garder les cadeaux d'un ex par nostalgie", lvl: 2 },
  { text: "de craquer sur quelqu'un rien que pour son physique", lvl: 2 },
  { text: "de raconter sa vie amoureuse à des inconnus", lvl: 2 },
  { text: "de retourner voir son ex « juste pour parler »", lvl: 2 },
  { text: "d'avoir trois applis de rencontre en même temps", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { text: "d'avoir déjà couché sur son lieu de travail", lvl: 3 },
  { text: "d'avoir un nombre de partenaires à deux chiffres", lvl: 3 },
  { text: "d'avoir déjà fait semblant au lit", lvl: 3 },
  { text: "d'avoir eu un coup d'un soir dont il/elle ignore le prénom", lvl: 3 },
  { text: "d'avoir déjà réalisé un fantasme original", lvl: 3 },
  { text: "d'avoir déjà couché avec deux personnes le même jour", lvl: 3 },
  { text: "d'avoir déjà filmé ses ébats", lvl: 3 },
  { text: "d'avoir déjà eu une aventure en vacances", lvl: 3 },
  { text: "de coucher pour obtenir un avantage", lvl: 3 },
  { text: "d'assumer un plan cul régulier en ce moment", lvl: 3 },
  { text: "d'avoir la sextape la plus gênante du groupe", lvl: 3 },
  { text: "d'avoir déjà dragué deux personnes du même groupe", lvl: 3 },
  { text: "d'avoir menti sur son expérience au lit", lvl: 3 },
  { text: "d'avoir déjà envoyé un nude à la mauvaise personne", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { text: "d'avoir déjà trompé sans jamais l'avouer", lvl: 4 },
  { text: "de coucher avec l'ex de son/sa meilleur(e) ami(e)", lvl: 4 },
  { text: "de faire de la prison un jour", lvl: 4 },
  { text: "de vendre un secret de famille pour de l'argent", lvl: 4 },
  { text: "de mentir à un enterrement pour toucher l'héritage", lvl: 4 },
  { text: "de piétiner un ami pour réussir", lvl: 4 },
  { text: "de rire en apprenant une très mauvaise nouvelle", lvl: 4 },
  { text: "de saboter la relation d'un(e) ami(e) par jalousie", lvl: 4 },
  { text: "d'avoir déjà volé quelqu'un de proche", lvl: 4 },
  { text: "de tout balancer pour 500 € ou sous la torture", lvl: 4 },
  { text: "de coucher avec quelqu'un juste pour l'héritage", lvl: 4 },
  { text: "de simuler des sentiments pour de l'argent", lvl: 4 },
  { text: "de se venger des années après, à froid", lvl: 4 },
  { text: "de trahir le groupe pour percer en solo", lvl: 4 },
  { text: "d'avoir un secret capable de briser un couple ici", lvl: 4 },

  // ===== Vague 3 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { text: "de rougir dès qu'on parle de son/sa crush", lvl: 2 },
  { text: "de garder une photo de son ex dans son téléphone", lvl: 2 },
  { text: "de tomber amoureux(se) de quelqu'un rencontré en ligne", lvl: 2 },
  { text: "de flirter sans même s'en rendre compte", lvl: 2 },
  { text: "de relire dix fois un message avant de l'envoyer", lvl: 2 },
  { text: "de craquer pour quelqu'un de totalement inaccessible", lvl: 2 },
  { text: "d'oser aborder un(e) inconnu(e) dans la rue", lvl: 2 },
  { text: "de replonger dans une relation compliquée", lvl: 2 },
  { text: "de mentir sur le nombre de ses ex", lvl: 2 },
  { text: "de pleurer devant une comédie romantique", lvl: 2 },
  { text: "de draguer le/la serveur(se) toute la soirée", lvl: 2 },
  { text: "d'avoir un coup de cœur en vacances chaque été", lvl: 2 },
  { text: "de sortir avec quelqu'un juste pour son physique", lvl: 2 },
  { text: "de retomber dans les bras de son ex à Noël", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { text: "d'avoir déjà eu une aventure au bureau", lvl: 3 },
  { text: "d'avoir un dossier « privé » bien caché", lvl: 3 },
  { text: "d'avoir déjà couché le soir même d'une rencontre", lvl: 3 },
  { text: "d'avoir simulé plus d'une fois", lvl: 3 },
  { text: "d'avoir un fantasme qui surprendrait tout le monde", lvl: 3 },
  { text: "d'avoir déjà envoyé un sexto au mauvais destinataire", lvl: 3 },
  { text: "d'assumer complètement sa vie sexuelle en public", lvl: 3 },
  { text: "d'avoir déjà eu un plan cul avec un(e) ami(e)", lvl: 3 },
  { text: "d'avoir déjà couché dans un lieu public", lvl: 3 },
  { text: "d'avoir un compteur bien plus élevé qu'il/elle ne l'avoue", lvl: 3 },
  { text: "d'avoir déjà proposé un plan à trois", lvl: 3 },
  { text: "d'avoir gardé des photos très intimes", lvl: 3 },
  { text: "d'avoir menti sur sa première fois", lvl: 3 },
  { text: "d'avoir déjà eu une relation secrète interdite", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { text: "d'avoir déjà trompé et laissé quelqu'un d'autre porter le chapeau", lvl: 4 },
  { text: "de coucher avec le/la partenaire d'un(e) ami(e) proche", lvl: 4 },
  { text: "de finir un jour recherché(e) par la police", lvl: 4 },
  { text: "de vendre un proche pour une très grosse somme", lvl: 4 },
  { text: "de mentir sous serment sans transpirer", lvl: 4 },
  { text: "de saboter discrètement un(e) rival(e)", lvl: 4 },
  { text: "de balancer une vanne déplacée en plein enterrement", lvl: 4 },
  { text: "de garder un secret qui pourrait envoyer quelqu'un en prison", lvl: 4 },
  { text: "d'avoir déjà volé dans un magasin", lvl: 4 },
  { text: "de retourner sa veste au pire moment", lvl: 4 },
  { text: "de se faire passer pour quelqu'un d'autre pour séduire", lvl: 4 },
  { text: "de disparaître du jour au lendemain sans un mot", lvl: 4 },
  { text: "de ne jamais pardonner, même après des années", lvl: 4 },
  { text: "de tricher le jour de son propre mariage", lvl: 4 },
  { text: "d'avoir déjà menti pour séparer deux personnes", lvl: 4 },

  // ===== Vague 4 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { text: "de liker une photo par accident en pleine nuit", lvl: 2 },
  { text: "de tomber amoureux(se) de quelqu'un juste pour sa voix", lvl: 2 },
  { text: "de garder une capture d'écran d'une conversation gênante", lvl: 2 },
  { text: "d'avoir une appli de rencontre ouverte « juste pour regarder »", lvl: 2 },
  { text: "de rougir en croisant quelqu'un qui lui plaît", lvl: 2 },
  { text: "de refaire sa coiffure dix fois avant un rencard", lvl: 2 },
  { text: "de complimenter quelqu'un très maladroitement", lvl: 2 },
  { text: "d'écrire un long message puis de tout effacer", lvl: 2 },
  { text: "de craquer sur quelqu'un de complètement à l'opposé", lvl: 2 },
  { text: "d'organiser toute sa soirée autour d'une seule personne", lvl: 2 },
  { text: "de mentir sur ses goûts pour plaire", lvl: 2 },
  { text: "de relancer un ex un soir de déprime", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { text: "d'avoir eu un plan cul qui a duré bien plus longtemps que prévu", lvl: 3 },
  { text: "d'avoir une story privée réservée à quelques personnes", lvl: 3 },
  { text: "d'avoir déjà quitté quelqu'un en plein milieu", lvl: 3 },
  { text: "d'avoir un chiffre bien plus élevé qu'on ne l'imagine", lvl: 3 },
  { text: "d'avoir déjà envoyé un message très osé en pleine réunion", lvl: 3 },
  { text: "d'assumer des goûts très particuliers au lit", lvl: 3 },
  { text: "d'avoir déjà eu une aventure interdite", lvl: 3 },
  { text: "d'avoir un objet coquin bien caché quelque part", lvl: 3 },
  { text: "d'avoir tout raconté à ses amis dès le lendemain", lvl: 3 },
  { text: "d'avoir déjà menti sur avec qui il/elle passait la nuit", lvl: 3 },
  { text: "d'avoir un profil très différent sur les applis", lvl: 3 },
  { text: "d'avoir osé une proposition coquine dès le premier rendez-vous", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { text: "d'avoir déjà détruit une amitié par pure jalousie", lvl: 4 },
  { text: "de mentir sur son CV sans le moindre scrupule", lvl: 4 },
  { text: "de garder rancune toute sa vie", lvl: 4 },
  { text: "d'avoir déjà pris quelque chose qui ne lui appartenait pas", lvl: 4 },
  { text: "de doubler un(e) collègue pour une promotion", lvl: 4 },
  { text: "de faire semblant de pleurer pour s'en sortir", lvl: 4 },
  { text: "d'avoir un plan pour disparaître si tout s'écroule", lvl: 4 },
  { text: "de critiquer ses amis dès qu'ils ont le dos tourné", lvl: 4 },
  { text: "d'avoir déjà fait porter le chapeau à un innocent", lvl: 4 },
  { text: "de tout faire pour de l'argent, même le pire", lvl: 4 },
  { text: "de cacher une double vie à tout le monde", lvl: 4 },
  { text: "d'avoir un secret qui choquerait même ses proches", lvl: 4 },

  // ===== Vague 5 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { text: "de préparer une phrase de drague et de l'oublier au moment M", lvl: 2 },
  { text: "de suivre secrètement le compte de son crush", lvl: 2 },
  { text: "de rougir en recevant un simple emoji cœur", lvl: 2 },
  { text: "de tomber amoureux(se) de son/sa prof de sport", lvl: 2 },
  { text: "de garder le ticket de ciné d'un premier date", lvl: 2 },
  { text: "de refaire trois fois sa photo de profil", lvl: 2 },
  { text: "d'écrire à son ex un soir de nostalgie", lvl: 2 },
  { text: "de flirter maladroitement avec le/la barman(aid)", lvl: 2 },
  { text: "de mentir sur ses hobbies pour matcher", lvl: 2 },
  { text: "de craquer pour quelqu'un juste parce qu'il/elle cuisine bien", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { text: "d'avoir déjà pris une douche à deux « pour gagner du temps »", lvl: 3 },
  { text: "d'avoir un tiroir secret qu'on préfère ne pas ouvrir", lvl: 3 },
  { text: "d'avoir déjà eu un coup de foudre purement physique", lvl: 3 },
  { text: "d'avoir déjà proposé de pimenter le couple", lvl: 3 },
  { text: "d'avoir déjà été surpris(e) en plein ébat", lvl: 3 },
  { text: "d'avoir un profil très osé quelque part", lvl: 3 },
  { text: "d'avoir tout tenté pour séduire quelqu'un de déjà pris", lvl: 3 },
  { text: "d'assumer un plan cul avec un(e) ex", lvl: 3 },
  { text: "d'avoir déjà couché juste par ennui", lvl: 3 },
  { text: "d'avoir déjà menti sur le nombre pour paraître plus sage", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { text: "d'avoir déjà saboté le bonheur de quelqu'un exprès", lvl: 4 },
  { text: "de mentir à ses proches sur ce qu'il/elle fait vraiment", lvl: 4 },
  { text: "d'avoir un plan B secret au cas où le couple explose", lvl: 4 },
  { text: "de balancer un(e) ami(e) pour redorer sa propre image", lvl: 4 },
  { text: "d'avoir déjà souhaité très fort du mal à quelqu'un", lvl: 4 },
  { text: "de cacher une addiction à tout le monde", lvl: 4 },
  { text: "de trahir un secret dès qu'on lui promet quelque chose", lvl: 4 },
  { text: "d'avoir déjà séduit le/la partenaire de quelqu'un par pur jeu", lvl: 4 },
  { text: "de mentir sur tout son passé pour repartir à zéro", lvl: 4 },
  { text: "d'avoir déjà fait quelque chose d'illégal sans se faire prendre", lvl: 4 },

  // ===== Vague 6 ===========================================================
  // --- Niveau 2 · Épicé 🌶️ -------------------------------------------------
  { text: "de faire semblant d'aimer un film pour impressionner un date", lvl: 2 },
  { text: "d'avoir une playlist spéciale « soir de déprime amoureuse »", lvl: 2 },
  { text: "de connaître par cœur le planning de son crush", lvl: 2 },
  { text: "de changer de trottoir pour éviter un ex", lvl: 2 },
  { text: "de liker puis unliker dans la seconde", lvl: 2 },
  { text: "de tomber amoureux(se) de son coach ou de son/sa prof", lvl: 2 },
  { text: "d'inventer une excuse pour reparler à son crush", lvl: 2 },
  { text: "de garder ses vieux tickets de rencard", lvl: 2 },
  { text: "de stresser une semaine avant un premier date", lvl: 2 },
  { text: "de confondre gentillesse et flirt", lvl: 2 },

  // --- Niveau 3 · +18 🔞 ---------------------------------------------------
  { text: "d'avoir menti sur son expérience pour impressionner", lvl: 3 },
  { text: "d'avoir un tiroir de sous-vêtements « spéciaux »", lvl: 3 },
  { text: "d'avoir eu un coup de foudre uniquement physique", lvl: 3 },
  { text: "d'avoir déjà tenté quelque chose de risqué en public", lvl: 3 },
  { text: "d'avoir un ex qu'il/elle recontacte « par accident »", lvl: 3 },
  { text: "d'avoir déjà comparé ses partenaires à voix haute", lvl: 3 },
  { text: "d'assumer une appli de rencontre plutôt coquine", lvl: 3 },
  { text: "d'avoir déjà fait le mur pour rejoindre quelqu'un", lvl: 3 },
  { text: "d'avoir un fantasme lié à un uniforme", lvl: 3 },
  { text: "d'avoir déjà couché sans retenir le prénom", lvl: 3 },

  // --- Niveau 4 · Cancellable ☠️ (le plus trash) ---------------------------
  { text: "de faire capoter un mariage par pure jalousie", lvl: 4 },
  { text: "d'avoir déjà piqué le/la partenaire d'un(e) proche", lvl: 4 },
  { text: "de faire un faux témoignage sans ciller", lvl: 4 },
  { text: "de cacher de l'argent à ses proches", lvl: 4 },
  { text: "d'avoir déjà fait chanter quelqu'un", lvl: 4 },
  { text: "de trahir n'importe qui pour réussir", lvl: 4 },
  { text: "d'avoir un plan secret pour disparaître du jour au lendemain", lvl: 4 },
  { text: "de garder une rancune tenace pendant des années", lvl: 4 },
  { text: "d'exagérer un malheur pour attirer la pitié", lvl: 4 },
  { text: "de retourner sa veste dès que ça l'arrange", lvl: 4 },
];

/**
 * Pioche pour un niveau donné : le grand public (niveau 1) + tout le contenu osé
 * de niveau ≤ `level`. Au niveau 1, strictement identique à avant.
 */
export function promptsForLevels(levels: CancelLevel[]): string[] {
  return [...(levels.includes(1) ? PROMPTS : []), ...filterHot(PROMPTS_HOT, levels).map((p) => p.text)];
}
