/**
 * Banque d'affirmations « Qui est le plus susceptible… ». Chaque entrée complète
 * la phrase « Qui est le plus susceptible … ? » (affichée par l'écran de jeu).
 * On reste bon enfant et taquin, jamais méchant ou intime.
 */
export const PROMPTS: string[] = [
  "de finir la soirée endormi sur le canapé",
  "d'envoyer un message qu'il regrettera demain",
  "de devenir célèbre un jour",
  "de rire à sa propre blague",
  "d'oublier où il a garé la voiture",
  "de pleurer devant un film d'animation",
  "de danser sur la table",
  "de répondre au téléphone en réunion",
  "de manger le dernier bout de pizza sans demander",
  "de se perdre dans une ville qu'il connaît",
  "de survivre à une apocalypse zombie",
  "de devenir prof un jour",
  "d'oublier l'anniversaire d'un proche",
  "de dire « je t'aime » trop tôt",
  "de rater son réveil un jour important",
  "de commander toujours la même chose au restau",
  "de parler à un inconnu dans le métro",
  "de croire à une théorie farfelue",
  "de gagner à un jeu télévisé",
  "d'exploser son forfait data",
  "de refaire trois fois la même histoire",
  "de chanter sous la douche à tue-tête",
  "de garder un secret… ou pas",
  "de tomber amoureux en vacances",
  "de rater un penalty décisif",
  "de finir milliardaire",
  "de se disputer pour une série",
  "de pleurer de rire en soirée",
  "de tout miser sur un coup de tête",
  "de devenir influenceur",
  "d'avoir toujours une anecdote sur tout",
  "de perdre son téléphone en soirée",
  "de dire oui à n'importe quel défi",
  "de cuisiner un plat immangeable",
  "de retweeter une fake news",
  "d'arriver en retard à son propre mariage",
  "de faire une sieste à une fête",
  "de collectionner un truc bizarre",
  "de se relever la nuit pour grignoter",
  "de rougir pour un rien",
  "de devenir le boss un jour",
  "de proposer un after à 4h du matin",
  "de parler tout seul",
  "d'oublier ce qu'il allait dire en plein milieu",
  "de fondre devant un chiot",
  "de sécher un cours pour dormir",
  "de râler pour la température de la pièce",
  "de connaître les paroles de toutes les chansons",
  "de prendre 100 photos du même plat",
  "de lancer un débat interminable",
  "de rester le dernier à table",
  "de vouloir toujours avoir raison",
  "de partir en voyage sur un coup de tête",
  "de rire au pire moment",
  "de devenir la mascotte du groupe",
  // --- Soirée & fêtes ---
  "de lancer la première danse de la soirée",
  "de proposer un dernier verre alors qu'il est tard",
  "de s'endormir avant la fin du film",
  "de connaître le nom de tous les invités en 5 minutes",
  "d'organiser la prochaine soirée du groupe",
  "de ramener quelque chose à grignoter sans qu'on lui demande",
  "de perdre au premier jeu et vouloir une revanche",
  "de raconter la même anecdote à chaque soirée",
  "de rester discuter dans l'entrée pendant une heure",
  "de transformer une réunion en fou rire",
  "de proposer un karaoké improvisé",
  "de finir la playlist à sa sauce",
  "de rater la photo de groupe en fermant les yeux",
  "de vouloir refaire une partie « juste une dernière »",
  "d'être le dernier à comprendre la blague",
  // --- Voyage & aventure ---
  "de rater son train pour cinq minutes",
  "de partir en voyage avec un seul sac",
  "de vouloir tout visiter en une journée",
  "d'oublier son passeport le jour du départ",
  "de improviser un itinéraire au dernier moment",
  "de goûter le plat le plus étrange du menu",
  "de se lier d'amitié avec un inconnu en vacances",
  "de prendre 500 photos et n'en garder aucune",
  "de vouloir dormir à la belle étoile",
  "de négocier un prix sur un marché",
  "de se perdre volontairement pour explorer",
  "de rater l'heure du réveil un jour d'excursion",
  // --- Tech & réseaux ---
  "de répondre à un mail à 2h du matin",
  "d'avoir 300 onglets ouverts",
  "de tomber dans un tunnel de vidéos jusqu'à l'aube",
  "de commenter tout ce qu'il regarde",
  "d'oublier de mettre son téléphone en silencieux",
  "de partager un article sans l'avoir lu",
  "de garder 10 000 photos non triées",
  "de demander de l'aide à une IA pour un rien",
  "de perdre une heure à choisir un fond d'écran",
  "de recharger son téléphone toutes les deux heures",
  "de découvrir une appli et en parler pendant une semaine",
  "de répondre « ok » à un long message",
  // --- Cuisine & nourriture ---
  "de tester une recette compliquée un soir de semaine",
  "de manger debout devant le frigo",
  "de saler avant même de goûter",
  "de commander le même plat partout",
  "de finir les restes de tout le monde",
  "de rater un gâteau mais le servir quand même",
  "de connaître le meilleur resto de chaque quartier",
  "de reprendre du dessert « juste un peu »",
  "de cacher des snacks pour lui tout seul",
  "de tenter le piment le plus fort par défi",
  "de faire brûler des pâtes",
  "d'improviser un plat avec trois ingrédients",
  // --- Boulot & études ---
  "d'arriver pile à l'heure, jamais en avance",
  "de prendre des notes que personne ne comprend",
  "de proposer une idée en réunion et la regretter",
  "de repousser une tâche jusqu'à la dernière minute",
  "de devenir le chef un jour",
  "de transformer une pause café en longue discussion",
  "de répondre présent pour un projet de dernière minute",
  "de garder son calme sous pression",
  "de tout planifier dans un agenda coloré",
  "de bosser mieux la veille au soir",
  // --- Sport & défis ---
  "de s'inscrire à la salle en janvier et arrêter en février",
  "de vouloir gagner même à un jeu pour enfants",
  "de tenter un record inutile pour la gloire",
  "de courir un marathon sur un coup de tête",
  "de commenter le match plus fort que les joueurs",
  "d'oublier de s'échauffer et le regretter",
  "de relever n'importe quel pari",
  "de danser plus longtemps que tout le monde",
  "de proposer une rando « facile » qui n'en est pas une",
  "de fêter une victoire comme si c'était la finale",
  // --- Caractère & habitudes (bon enfant) ---
  "de rire nerveusement dans un moment sérieux",
  "de dire oui puis de le regretter",
  "de tout ranger par couleur",
  "de parler aux animaux comme à des humains",
  "de s'excuser même quand ce n'est pas sa faute",
  "de garder un ticket de caisse « au cas où »",
  "de commencer dix projets en même temps",
  "de connaître un raccourci pour tout",
  "de fredonner sans s'en rendre compte",
  "de retenir les anniversaires de tout le monde",
  "de donner un surnom à chacun",
  "de vérifier trois fois s'il a bien fermé la porte",
  "de prendre la parole pour défendre les autres",
  "de garder son sang-froid quand tout part en vrille",
  "de dire tout haut ce que les autres pensent tout bas",
  // --- Situations cocasses ---
  "de saluer quelqu'un qui ne lui disait pas bonjour",
  "de se tromper d'étage dans un immeuble",
  "de rire tout seul en repensant à un souvenir",
  "d'applaudir au mauvais moment",
  "de confondre deux personnes qui ne se ressemblent pas",
  "de chercher ses lunettes qu'il a sur le nez",
  "de tenir la porte trop longtemps à quelqu'un de loin",
  "d'oublier pourquoi il est entré dans une pièce",
  "de répondre à une question qu'on n'a pas posée",
  "de se relire trois fois avant d'envoyer un message",
  "de klaxonner d'un signe amical un inconnu",
  "de garder une plante en vie contre toute attente",
  // --- Argent & organisation ---
  "de proposer de partager l'addition en parts égales",
  "de retrouver un vieux billet dans une poche",
  "de comparer les prix pendant vingt minutes",
  "de craquer pour un gadget inutile",
  "de faire une liste puis de l'oublier à la maison",
  "de mettre de l'argent de côté « pour plus tard »",
  "d'offrir le meilleur cadeau du groupe",
  "de prêter sans jamais réclamer",
  // --- Culture & talents ---
  "de connaître les paroles d'une chanson des années 80",
  "de citer une réplique de film au bon moment",
  "de gagner à un quiz de culture générale",
  "de reconnaître une musique en deux notes",
  "de recommander un livre à tout le monde",
  "de repérer une erreur dans un film",
  "de retenir des dates historiques par cœur",
  "d'improviser une histoire pour endormir un enfant",
  // --- Nature & maison ---
  "de sauver une araignée au lieu de l'écraser",
  "d'avoir trop de plantes chez lui",
  "de vouloir adopter tous les animaux qu'il croise",
  "de recycler méticuleusement",
  "de repeindre une pièce sur un coup de tête",
  "de connaître le prénom du chat des voisins",
  "de ramasser un joli caillou en balade",
  "de râler dès qu'il fait trop chaud… ou trop froid",
  // --- Petites bravades du quotidien ---
  "de doubler tout le monde à pied dans la rue",
  "de finir le paquet et remettre l'emballage vide",
  "de chanter dans la voiture aux feux rouges",
  "de garder le meilleur pour la fin",
  "de tester le bouton « au cas où »",
  "de relancer un débat déjà clos",
  "de proposer de « juste jeter un œil » dans un magasin",
  "de dire « je gère » avant de ne rien gérer",
  // --- Rab ---
  "de garder un ticket de cinéma en souvenir",
  "de refaire le monde à 3h du matin",
  "d'apprendre un mot rare et le placer partout",
  "de féliciter tout le monde après une victoire d'équipe",
  "de connaître un bon plan pour chaque situation",
  "de proposer une pause quand ça devient tendu",
  "de rire avant même la chute de la blague",
  "de s'installer à la meilleure place du canapé",
  "de vouloir goûter à l'assiette des autres",
  "de garder espoir jusqu'au bout d'une partie mal engagée",
  "de motiver le groupe quand tout le monde fatigue",
  "de retenir le chemin après y être allé une fois",
  "de proposer un jeu quand il y a un blanc",
  "de complimenter la tenue de quelqu'un en premier",
  "de finir la phrase des autres",
  "de garder son calme dans une file d'attente interminable",
  "d'improviser un toast au bon moment",
  "de retrouver un objet perdu par quelqu'un d'autre",
  "de proposer de raccompagner tout le monde",
  "de transformer une galère en bonne histoire à raconter",
];
