import { universe } from "../_build";

export const animes90 = universe("manga", "Animés des années 90-2000", [
  // --- Faciles (5) ---
  { id: "an90-f1", d: 1, t: "Quel manga des années 90 suit des collégiennes guerrières portant des noms de planètes ?", a: "Sailor Moon", x: ["Cardcaptor Sakura", "Magic Knight Rayearth", "Wedding Peach"] },
  { id: "an90-f2", d: 1, t: "Quelle créature jaune électrique est la mascotte de « Pokémon » ?", a: "Pikachu", x: ["Bulbizarre", "Salamèche", "Carapuce"] },
  { id: "an90-f3", d: 1, t: "Dans l'anime « Pokémon », comment s'appelle le jeune dresseur héros ?", a: "Sacha", x: ["Pierre", "Régis", "Ondine"], acc: ["sacha", "ash"] },
  { id: "an90-f4", d: 1, t: "Quel anime de foot, connu en France sous « Olive et Tom », suit de jeunes footballeurs ?", a: "Captain Tsubasa", x: ["Inazuma Eleven", "Slam Dunk", "Le Prince du tennis"], acc: ["captain tsubasa", "olive et tom"] },
  { id: "an90-f5", d: 1, t: "Quel anime policier suit un détective transformé en enfant qui résout des meurtres ?", a: "Détective Conan", x: ["Death Note", "Monster", "Erased"], acc: ["détective conan", "conan"] },
  // --- Moyennes (10) ---
  { id: "an90-m1", d: 2, t: "Quel anime suit des chevaliers en armures sacrées protégeant la déesse Athéna ?", a: "Saint Seiya", x: ["Ronin Warriors", "Yu Yu Hakusho", "Bastard"], acc: ["saint seiya", "les chevaliers du zodiaque"] },
  { id: "an90-m2", d: 2, t: "Sous quel nom « Saint Seiya » a-t-il été diffusé en France ?", a: "Les Chevaliers du Zodiaque", x: ["Les Chevaliers d'Athéna", "Les Chevaliers de bronze", "Les Gardiens du cosmos"] },
  { id: "an90-m3", d: 2, t: "Quel anime, connu en France sous « Nicky Larson », suit un détective privé dragueur ?", a: "City Hunter", x: ["Cat's Eye", "Cobra", "Golgo 13"], acc: ["city hunter", "nicky larson"] },
  { id: "an90-m4", d: 2, t: "Quel anime de basket suit Hanamichi Sakuragi, un délinquant devenu joueur ?", a: "Slam Dunk", x: ["Kuroko's Basket", "Ahiru no Sora", "Dear Boys"] },
  { id: "an90-m5", d: 2, t: "Quel anime d'arts martiaux met en scène un garçon qui devient fille au contact de l'eau froide ?", a: "Ranma ½", x: ["Inuyasha", "Urusei Yatsura", "Maison Ikkoku"], acc: ["ranma", "ranma 1/2"] },
  { id: "an90-m6", d: 2, t: "Quel anime suit une collégienne propulsée dans le Japon féodal aux côtés d'un demi-démon ?", a: "Inuyasha", x: ["Ranma ½", "Urusei Yatsura", "Fushigi Yugi"] },
  { id: "an90-m7", d: 2, t: "Quel professeur, ancien loubard, enseigne au lycée dans « GTO » ?", a: "Onizuka", x: ["Kimura", "Sakuragi", "Kamiya"], acc: ["onizuka", "eikichi onizuka"] },
  { id: "an90-m8", d: 2, t: "Quels monstres numériques accompagnent des enfants dans le monde digital ?", a: "Digimon", x: ["Pokémon", "Monster Rancher", "Medabots"] },
  { id: "an90-m9", d: 2, t: "Quel anime de duel de cartes met en scène Yugi et le « Cœur des cartes » ?", a: "Yu-Gi-Oh!", x: ["Duel Masters", "Bakugan", "Cardfight Vanguard"], acc: ["yu-gi-oh", "yugioh"] },
  { id: "an90-m10", d: 2, t: "Quelle magical girl de CLAMP capture des cartes magiques ?", a: "Cardcaptor Sakura", x: ["Sailor Moon", "Magical Doremi", "Pretty Cure"], acc: ["cardcaptor sakura", "sakura chasseuse de cartes"] },
  // --- Dures (15) ---
  { id: "an90-d1", d: 3, t: "Quel anime de science-fiction de 1998 suit le chasseur de primes Spike Spiegel ?", a: "Cowboy Bebop", x: ["Trigun", "Outlaw Star", "Samurai Champloo"] },
  { id: "an90-d2", d: 3, t: "Quel anime culte de 1995 met en scène des ados pilotant des Evas contre des Anges ?", a: "Neon Genesis Evangelion", x: ["RahXephon", "Gundam Wing", "Gunbuster"], acc: ["evangelion", "neon genesis evangelion"] },
  { id: "an90-d3", d: 3, t: "Comment s'appelle le pilote de l'Eva-01 dans Evangelion ?", a: "Shinji Ikari", x: ["Rei Ayanami", "Asuka Langley", "Kaworu Nagisa"] },
  { id: "an90-d4", d: 3, t: "Quel anime des années 90 suit Yusuke Urameshi, détective des Enfers ?", a: "Yu Yu Hakusho", x: ["Saint Seiya", "Flame of Recca", "Rurouni Kenshin"], acc: ["yu yu hakusho"] },
  { id: "an90-d5", d: 3, t: "Quel samouraï errant à la cicatrice en croix est le héros de « Kenshin » ?", a: "Kenshin", x: ["Kenshiro", "Mugen", "Jin"], acc: ["kenshin", "himura kenshin"] },
  { id: "an90-d6", d: 3, t: "Quel anime post-apocalyptique suit Kenshiro, maître du Hokuto Shinken ?", a: "Ken le survivant", x: ["Cobra", "Berserk", "Casshern"], acc: ["ken le survivant", "hokuto no ken"] },
  { id: "an90-d7", d: 3, t: "Quel anime suit trois sœurs qui tiennent un café le jour et volent des œuvres d'art la nuit ?", a: "Cat's Eye", x: ["City Hunter", "Lupin III", "Golgo 13"], acc: ["cat's eye", "signé cat's eye"] },
  { id: "an90-d8", d: 3, t: "Quel gentleman cambrioleur japonais est le héros d'un anime au long cours ?", a: "Lupin III", x: ["Cat's Eye", "City Hunter", "Golgo 13"], acc: ["lupin iii", "edgar de la cambriole"] },
  { id: "an90-d9", d: 3, t: "Quel anime de course de toupies a lancé une mode dans les années 2000 ?", a: "Beyblade", x: ["Crush Gear", "Bakugan", "Medabots"] },
  { id: "an90-d10", d: 3, t: "Quel petit hamster est la star d'un anime kawaii du début des années 2000 ?", a: "Hamtaro", x: ["Pucca", "Doraemon", "Chi"] },
  { id: "an90-d11", d: 3, t: "Quel robot-chat venu du futur aide le jeune Nobita dans cet anime japonais ?", a: "Doraemon", x: ["Astro", "Hamtaro", "Chi"] },
  { id: "an90-d12", d: 3, t: "Quel anime de sport suit l'ascension du boxeur Ippo Makunouchi ?", a: "Hajime no Ippo", x: ["Ashita no Joe", "Megalo Box", "Baki"] },
  { id: "an90-d13", d: 3, t: "Quel anime de 1997 suit un tournoi d'arts martiaux avec Recca, maître du feu ?", a: "Flame of Recca", x: ["Yu Yu Hakusho", "Shaman King", "Rurouni Kenshin"], acc: ["flame of recca"] },
  { id: "an90-d14", d: 3, t: "Quel jeune médium combat des fantômes pour devenir roi dans « Shaman King » ?", a: "Yoh Asakura", x: ["Yusuke Urameshi", "Ichigo Kurosaki", "Allen Walker"] },
  { id: "an90-d15", d: 3, t: "Quel studio, fondé par Hayao Miyazaki, a produit « Princesse Mononoké » en 1997 ?", a: "Le Studio Ghibli", x: ["Le Studio Gainax", "Le Studio Madhouse", "Le Studio Toei"], acc: ["ghibli", "studio ghibli"] },
  // --- Pro (20) ---
  { id: "an90-p1", d: 4, t: "En quelle année l'anime « Pokémon » a-t-il été diffusé pour la première fois au Japon ?", a: "1997", x: ["1992", "2001", "2005"] },
  { id: "an90-p2", d: 4, t: "Quel épisode de « Pokémon » a été censuré pour avoir provoqué des crises chez des enfants ?", a: "Le soldat Porygon", x: ["Le fantôme de Lavanville", "L'île de Pikachu", "Le stade de Safrania"], acc: ["porygon"] },
  { id: "an90-p3", d: 4, t: "Quel studio a produit « Neon Genesis Evangelion » ?", a: "Gainax", x: ["Ghibli", "Madhouse", "Bones"] },
  { id: "an90-p4", d: 4, t: "Quel réalisateur est à l'origine d'« Evangelion » ?", a: "Hideaki Anno", x: ["Hayao Miyazaki", "Shinichirō Watanabe", "Satoshi Kon"] },
  { id: "an90-p5", d: 4, t: "Quel réalisateur de « Cowboy Bebop » a aussi signé « Samurai Champloo » ?", a: "Shinichirō Watanabe", x: ["Hideaki Anno", "Mamoru Oshii", "Satoshi Kon"] },
  { id: "an90-p6", d: 4, t: "Quel film d'animation de 1988 de Katsuhiro Otomo suit Kaneda et Tetsuo à Neo-Tokyo ?", a: "Akira", x: ["Ghost in the Shell", "Jin-Roh", "Metropolis"] },
  { id: "an90-p7", d: 4, t: "Quel film de 1995 de Mamoru Oshii suit la cyborg Motoko Kusanagi ?", a: "Ghost in the Shell", x: ["Akira", "Appleseed", "Patlabor"] },
  { id: "an90-p8", d: 4, t: "Quelle émission française diffusait ces animes le mercredi et le matin dans les années 90 ?", a: "Le Club Dorothée", x: ["Récré A2", "Les Minikeums", "Amuse 3"], acc: ["club dorothée", "club dorothee"] },
  { id: "an90-p9", d: 4, t: "Quel anime de Naoki Urasawa suit le Dr Tenma traquant un tueur qu'il a sauvé ?", a: "Monster", x: ["Perfect Blue", "Paranoia Agent", "Texhnolyze"] },
  { id: "an90-p10", d: 4, t: "Quel réalisateur culte a signé « Perfect Blue » et « Paprika » ?", a: "Satoshi Kon", x: ["Mamoru Oshii", "Hideaki Anno", "Makoto Shinkai"] },
  { id: "an90-p11", d: 4, t: "Quel anime de 1998 suit Vash the Stampede, un hors-la-loi à la prime colossale ?", a: "Trigun", x: ["Cowboy Bebop", "Outlaw Star", "Gungrave"] },
  { id: "an90-p12", d: 4, t: "Quel anime mecha de 1995 met en scène cinq pilotes et leurs Gundam ?", a: "Gundam Wing", x: ["Macross", "Escaflowne", "Patlabor"], acc: ["gundam wing"] },
  { id: "an90-p13", d: 4, t: "Quel anime fantastique de 1996 suit Hitomi transportée sur la planète Gaïa ?", a: "Escaflowne", x: ["Fushigi Yugi", "El-Hazard", "Nadia"] },
  { id: "an90-p14", d: 4, t: "Quel anime de Rumiko Takahashi met en scène un lycéen et l'extraterrestre Lum en bikini tigré ?", a: "Urusei Yatsura", x: ["Ranma ½", "Maison Ikkoku", "Inuyasha"], acc: ["urusei yatsura", "lamu"] },
  { id: "an90-p15", d: 4, t: "Quel anime de vampires de 2001 met en scène Alucard au service de l'organisation Hellsing ?", a: "Hellsing", x: ["Vampire Hunter D", "Blood+", "Trinity Blood"] },
  { id: "an90-p16", d: 4, t: "Quel long-métrage de 2001 de Miyazaki suit Chihiro dans un monde de bains pour esprits ?", a: "Le Voyage de Chihiro", x: ["Princesse Mononoké", "Le Château ambulant", "Ponyo"] },
  { id: "an90-p17", d: 4, t: "Quel anime de tennis suit le prodige Ryoma Echizen ?", a: "Le Prince du tennis", x: ["Slam Dunk", "Captain Tsubasa", "Eyeshield 21"], acc: ["prince du tennis"] },
  { id: "an90-p18", d: 4, t: "Quel anime de 1998 suit Lain, une adolescente reliée au réseau « Wired » ?", a: "Serial Experiments Lain", x: ["Boogiepop Phantom", "Paranoia Agent", "Texhnolyze"], acc: ["lain", "serial experiments lain"] },
  { id: "an90-p19", d: 4, t: "Quel anime de Toei, connu en France sous « Magical Doremi », suit des apprenties sorcières ?", a: "Ojamajo Doremi", x: ["Sailor Moon", "Pretty Cure", "Cardcaptor Sakura"], acc: ["magical doremi", "ojamajo doremi"] },
  { id: "an90-p20", d: 4, t: "Quel anime de 2004 de Shinichirō Watanabe mêle hip-hop et samouraïs de l'ère Edo ?", a: "Samurai Champloo", x: ["Cowboy Bebop", "Afro Samurai", "Rurouni Kenshin"] },
]);
