import { universe } from "../_build";

export const bleach = universe("manga", "Bleach", [
  // --- Faciles (5) ---
  { id: "bleach-f1", d: 1, t: "Qui est le héros de Bleach, aux cheveux orange ?", a: "Ichigo Kurosaki", acc: ["ichigo", "kurosaki"], x: ["Renji", "Uryu", "Chad"] },
  { id: "bleach-f2", d: 1, t: "En quoi Ichigo se transforme-t-il pour combattre ?", a: "Un Shinigami", acc: ["shinigami", "dieu de la mort"], x: ["Un Hollow", "Un Quincy", "Un Arrancar"] },
  { id: "bleach-f3", d: 1, t: "Comment s'appelle l'arme des Shinigami ?", a: "Le zanpakuto", acc: ["zanpakuto"], x: ["L'arc", "La lance", "Le fouet"] },
  { id: "bleach-f4", d: 1, t: "Comment s'appelle le zanpakuto d'Ichigo ?", a: "Zangetsu", x: ["Senbonzakura", "Hyorinmaru", "Zabimaru"] },
  { id: "bleach-f5", d: 1, t: "Comment appelle-t-on les monstres masqués qui dévorent les âmes ?", a: "Les Hollows", acc: ["hollows", "hollow"], x: ["Les Titans", "Les Démons", "Les Arrancars"] },

  // --- Moyennes (10) ---
  { id: "bleach-m1", d: 2, t: "Quelle Shinigami transmet ses pouvoirs à Ichigo au début ?", a: "Rukia Kuchiki", acc: ["rukia", "kuchiki"], x: ["Orihime", "Rangiku", "Yoruichi"] },
  { id: "bleach-m2", d: 2, t: "Quelle amie d'Ichigo possède des pouvoirs de soin et de rejet ?", a: "Orihime Inoue", acc: ["orihime", "inoue"], x: ["Rukia", "Tatsuki", "Rangiku"] },
  { id: "bleach-m3", d: 2, t: "Quel ami d'Ichigo est un Quincy à lunettes ?", a: "Uryu Ishida", acc: ["uryu", "ishida"], x: ["Chad", "Keigo", "Renji"] },
  { id: "bleach-m4", d: 2, t: "Quel ami costaud d'Ichigo a un bras surpuissant ?", a: "Chad", acc: ["chad", "sado"], x: ["Uryu", "Keigo", "Mizuiro"] },
  { id: "bleach-m5", d: 2, t: "Comment appelle-t-on la première libération d'un zanpakuto ?", a: "Le Shikai", acc: ["shikai"], x: ["Le Bankai", "Le Kido", "Le Hollowfication"] },
  { id: "bleach-m6", d: 2, t: "Comment appelle-t-on la libération ultime d'un zanpakuto ?", a: "Le Bankai", acc: ["bankai"], x: ["Le Shikai", "Le Kido", "Le Reiatsu"] },
  { id: "bleach-m7", d: 2, t: "Comment s'appelle le monde où résident les Shinigami ?", a: "La Soul Society", acc: ["soul society"], x: ["Hueco Mundo", "Las Noches", "Karakura"] },
  { id: "bleach-m8", d: 2, t: "Quel lieutenant tatoué au zanpakuto Zabimaru est l'ami-rival d'Ichigo ?", a: "Renji Abarai", acc: ["renji", "abarai"], x: ["Byakuya", "Ikkaku", "Kenpachi"] },
  { id: "bleach-m9", d: 2, t: "Quel capitaine noble est le frère adoptif de Rukia ?", a: "Byakuya Kuchiki", acc: ["byakuya"], x: ["Toshiro", "Kenpachi", "Ukitake"] },
  { id: "bleach-m10", d: 2, t: "Quel capitaine traître est le grand méchant de la première partie ?", a: "Sosuke Aizen", acc: ["aizen"], x: ["Gin", "Tosen", "Ulquiorra"] },

  // --- Dures (15) ---
  { id: "bleach-d1", d: 3, t: "Combien de divisions compte le Gotei ?", a: "13", acc: ["treize"], x: ["10", "12", "9"] },
  { id: "bleach-d2", d: 3, t: "Quel jeune capitaine génie manie le zanpakuto de glace Hyorinmaru ?", a: "Toshiro Hitsugaya", acc: ["toshiro", "hitsugaya"], x: ["Byakuya", "Kenpachi", "Ukitake"] },
  { id: "bleach-d3", d: 3, t: "Quel capitaine sanguinaire de la 11e division adore se battre ?", a: "Kenpachi Zaraki", acc: ["kenpachi", "zaraki"], x: ["Byakuya", "Toshiro", "Mayuri"] },
  { id: "bleach-d4", d: 3, t: "Quel zanpakuto de Byakuya se disperse en pétales de cerisier ?", a: "Senbonzakura", x: ["Zabimaru", "Hyorinmaru", "Zangetsu"] },
  { id: "bleach-d5", d: 3, t: "Quel capitaine scientifique dirige la 12e division ?", a: "Mayuri Kurotsuchi", acc: ["mayuri", "kurotsuchi"], x: ["Aizen", "Ukitake", "Komamura"] },
  { id: "bleach-d6", d: 3, t: "Qui est le Commandant en chef du Gotei 13 ?", a: "Genryusai Yamamoto", acc: ["yamamoto", "genryusai"], x: ["Aizen", "Byakuya", "Ukitake"] },
  { id: "bleach-d7", d: 3, t: "Comment s'appelle le zanpakuto de feu de Yamamoto ?", a: "Ryujin Jakka", acc: ["ryujin jakka"], x: ["Senbonzakura", "Zangetsu", "Hyorinmaru"] },
  { id: "bleach-d8", d: 3, t: "Comment appelle-t-on les Hollows humanoïdes créés par Aizen ?", a: "Les Arrancars", acc: ["arrancars", "arrancar"], x: ["Les Quincy", "Les Fullbringers", "Les Vizards"] },
  { id: "bleach-d9", d: 3, t: "Comment appelle-t-on les 10 Arrancars les plus puissants d'Aizen ?", a: "Les Espada", acc: ["espada"], x: ["Les Piliers", "Les Lunes", "Les Captains"] },
  { id: "bleach-d10", d: 3, t: "Quel Espada n°4, sombre et froid, affronte Ichigo à Hueco Mundo ?", a: "Ulquiorra Cifer", acc: ["ulquiorra"], x: ["Grimmjow", "Nnoitra", "Starrk"] },
  { id: "bleach-d11", d: 3, t: "Quel Espada n°6 bleu et félin est un rival d'Ichigo ?", a: "Grimmjow Jaegerjaquez", acc: ["grimmjow"], x: ["Ulquiorra", "Nnoitra", "Yammy"] },
  { id: "bleach-d12", d: 3, t: "Comment s'appelle le monde désertique des Hollows ?", a: "Hueco Mundo", x: ["Soul Society", "Karakura", "Las Noches"] },
  { id: "bleach-d13", d: 3, t: "Comment s'appelle le palais d'Aizen à Hueco Mundo ?", a: "Las Noches", x: ["Seireitei", "Hueco Mundo", "Karakura"] },
  { id: "bleach-d14", d: 3, t: "Quel chat noir se révèle être une ancienne capitaine ?", a: "Yoruichi Shihoin", acc: ["yoruichi"], x: ["Soi Fon", "Rangiku", "Unohana"] },
  { id: "bleach-d15", d: 3, t: "Quel ex-capitaine tient une boutique et porte chapeau et sabots ?", a: "Kisuke Urahara", acc: ["urahara", "kisuke"], x: ["Yoruichi", "Isshin", "Ryuken"] },

  // --- Pro (20) ---
  { id: "bleach-p1", d: 4, t: "Dans quelle ville vit Ichigo ?", a: "Karakura", x: ["Naruto", "Seireitei", "Rukongai"] },
  { id: "bleach-p2", d: 4, t: "Comment appelle-t-on l'entité blanche qui vit à l'intérieur d'Ichigo ?", a: "Son Hollow intérieur", acc: ["hollow interieur", "hollow ichigo"], x: ["Un Arrancar", "Un Quincy", "Un Zanpakuto"] },
  { id: "bleach-p3", d: 4, t: "Comment appelle-t-on les ex-capitaines mi-Shinigami mi-Hollow ?", a: "Les Vizards", acc: ["vizards", "visored"], x: ["Les Espada", "Les Quincy", "Les Fullbringers"] },
  { id: "bleach-p4", d: 4, t: "Qui est le père d'Ichigo, un ancien Shinigami ?", a: "Isshin Kurosaki", acc: ["isshin"], x: ["Ryuken", "Kisuke", "Ryujin"] },
  { id: "bleach-p5", d: 4, t: "Quels deux capitaines trahissent la Soul Society aux côtés d'Aizen ?", a: "Gin Ichimaru et Kaname Tosen", acc: ["gin et tosen", "gin ichimaru et tosen"], x: ["Byakuya et Toshiro", "Kenpachi et Mayuri", "Ukitake et Kyoraku"] },
  { id: "bleach-p6", d: 4, t: "Comment s'appelle le zanpakuto de Gin, qui s'allonge à grande vitesse ?", a: "Shinso", x: ["Kyoka Suigetsu", "Senbonzakura", "Zabimaru"] },
  { id: "bleach-p7", d: 4, t: "Quel zanpakuto d'Aizen crée une hypnose totale des sens ?", a: "Kyoka Suigetsu", acc: ["kyoka suigetsu"], x: ["Shinso", "Ryujin Jakka", "Zangetsu"] },
  { id: "bleach-p8", d: 4, t: "Quel objet Aizen convoite-t-il pour transcender Shinigami et Hollows ?", a: "Le Hogyoku", acc: ["hogyoku"], x: ["L'Oken", "Le Reiatsu", "Le Senkaimon"] },
  { id: "bleach-p9", d: 4, t: "Qui règne au sommet de la Soul Society ?", a: "Le Roi des Âmes", acc: ["roi des ames", "soul king"], x: ["Yamamoto", "Aizen", "Le Central 46"] },
  { id: "bleach-p10", d: 4, t: "Quelle race d'humains spirituels combat les Hollows avec des arcs ?", a: "Les Quincy", acc: ["quincy"], x: ["Les Arrancars", "Les Vizards", "Les Fullbringers"] },
  { id: "bleach-p11", d: 4, t: "Qui est l'empereur des Quincy, grand méchant de l'arc final ?", a: "Yhwach", acc: ["yhwach", "juhabach"], x: ["Aizen", "Ulquiorra", "Baraggan"] },
  { id: "bleach-p12", d: 4, t: "Comment s'appelle l'empire des Quincy de Yhwach ?", a: "La Wandenreich", acc: ["wandenreich"], x: ["Le Gotei", "L'Espada", "Las Noches"] },
  { id: "bleach-p13", d: 4, t: "Comment s'appelle finalement le zanpakuto de Kenpachi ?", a: "Nozarashi", x: ["Zangetsu", "Zabimaru", "Ryujin Jakka"] },
  { id: "bleach-p14", d: 4, t: "Quelle lieutenante de la 10e division, à forte poitrine, est une amie d'enfance de Gin ?", a: "Rangiku Matsumoto", acc: ["rangiku", "matsumoto"], x: ["Nemu", "Nanao", "Isane"] },
  { id: "bleach-p15", d: 4, t: "Quel Espada n°1, solitaire, est le plus puissant des Espada ?", a: "Coyote Starrk", acc: ["starrk", "coyote starrk"], x: ["Baraggan", "Ulquiorra", "Yammy"] },
  { id: "bleach-p16", d: 4, t: "Comment appelle-t-on les humains dotés de pouvoirs ?", a: "Les Fullbringers", acc: ["fullbringers", "fullbring"], x: ["Les Quincy", "Les Vizards", "Les Arrancars"] },
  { id: "bleach-p17", d: 4, t: "Quel chef des Fullbringers manipule Ichigo pour lui voler ses pouvoirs ?", a: "Kugo Ginjo", acc: ["ginjo", "kugo ginjo"], x: ["Tsukishima", "Yhwach", "Aizen"] },
  { id: "bleach-p18", d: 4, t: "Quelle capitaine guérisseuse de la 4e division cache un passé terrifiant ?", a: "Retsu Unohana", acc: ["unohana", "retsu"], x: ["Nanao", "Isane", "Nemu"] },
  { id: "bleach-p19", d: 4, t: "Comment appelle-t-on le passage qui mène à Hueco Mundo ?", a: "Le Garganta", acc: ["garganta"], x: ["Le Senkaimon", "Le Dangai", "Le Precipice"] },
  { id: "bleach-p20", d: 4, t: "Comment appelle-t-on la porte reliant la Soul Society au monde des vivants ?", a: "Le Senkaimon", acc: ["senkaimon"], x: ["Le Garganta", "Le Dangai", "Las Noches"] },
]);
