import { universe } from "../_build";

export const bluelock = universe("manga", "Blue Lock", [
  // --- Faciles (5) ---
  { id: "bluelock-f1", d: 1, t: "Autour de quel sport tourne le manga Blue Lock ?", a: "Le football", x: ["Le basket", "Le tennis", "Le baseball"], acc: ["football", "foot"] },
  { id: "bluelock-f2", d: 1, t: "Quel type de joueur le projet Blue Lock veut-il créer ?", a: "Le meilleur attaquant du monde", x: ["Le meilleur gardien", "Le meilleur arbitre", "Le meilleur entraîneur"], acc: ["meilleur attaquant", "meilleur buteur", "attaquant"] },
  { id: "bluelock-f3", d: 1, t: "Comment s'appelle le héros de Blue Lock ?", a: "Yoichi Isagi", x: ["Meguru Bachira", "Rin Itoshi", "Seishiro Nagi"], acc: ["isagi", "yoichi isagi"] },
  { id: "bluelock-f4", d: 1, t: "Quelle couleur donne son nom au centre de formation ?", a: "Le bleu", x: ["Le rouge", "Le noir", "Le vert"], acc: ["bleu", "le bleu"] },
  { id: "bluelock-f5", d: 1, t: "Quelle sélection nationale le projet Blue Lock veut-il renforcer ?", a: "Le Japon", x: ["La Corée", "La Chine", "Le Brésil"], acc: ["japon", "le japon"] },
  // --- Moyennes (10) ---
  { id: "bluelock-m1", d: 2, t: "Comment s'appelle le mystérieux fondateur et coach du projet Blue Lock ?", a: "Jinpachi Ego", x: ["Rin Itoshi", "Yoichi Isagi", "Michael Kaiser"], acc: ["ego", "jinpachi ego"] },
  { id: "bluelock-m2", d: 2, t: "Quelle qualité Ego veut-il développer chez ses attaquants ?", a: "L'égoïsme", x: ["L'altruisme", "La patience", "La discipline"], acc: ["egoisme", "égoïsme", "egoist"] },
  { id: "bluelock-m3", d: 2, t: "Quel échec a déclenché la création de Blue Lock ?", a: "Une élimination en Coupe du monde", x: ["Une victoire en finale", "Un scandale d'arbitrage", "La faillite d'un club"], acc: ["elimination en coupe du monde", "coupe du monde", "defaite"] },
  { id: "bluelock-m4", d: 2, t: "Comment s'appelle le dribbleur imprévisible, ami d'Isagi, qui parle de son « monstre » ?", a: "Meguru Bachira", x: ["Rin Itoshi", "Seishiro Nagi", "Shoei Barou"], acc: ["bachira", "meguru bachira"] },
  { id: "bluelock-m5", d: 2, t: "Comment s'appelle l'attaquant froid considéré comme le meilleur de Blue Lock ?", a: "Rin Itoshi", x: ["Yoichi Isagi", "Meguru Bachira", "Hyoma Chigiri"], acc: ["rin itoshi", "rin"] },
  { id: "bluelock-m6", d: 2, t: "Qui a écrit le manga Blue Lock ?", a: "Muneyuki Kaneshiro", x: ["Eiichiro Oda", "Gege Akutami", "Koyoharu Gotouge"], acc: ["kaneshiro", "muneyuki kaneshiro"] },
  { id: "bluelock-m7", d: 2, t: "Comment s'appelle le génie paresseux, prodige du contrôle de balle ?", a: "Seishiro Nagi", x: ["Reo Mikage", "Shoei Barou", "Rensuke Kunigami"], acc: ["nagi", "seishiro nagi"] },
  { id: "bluelock-m8", d: 2, t: "Quel garçon riche recrute Nagi et devient son partenaire ?", a: "Reo Mikage", x: ["Michael Kaiser", "Rin Itoshi", "Yoichi Isagi"], acc: ["reo", "reo mikage"] },
  { id: "bluelock-m9", d: 2, t: "Que perdent définitivement les joueurs éliminés de Blue Lock ?", a: "Le droit de jouer pour le Japon", x: ["Leur maison", "Leur argent", "Leur nom"], acc: ["droit de jouer pour le japon", "selection nationale", "jouer pour le japon"] },
  { id: "bluelock-m10", d: 2, t: "Quel studio a produit l'anime Blue Lock, sorti en 2022 ?", a: "Le studio 8bit", x: ["Le studio Ghibli", "MAPPA", "Ufotable"], acc: ["8bit", "studio 8bit"] },
  // --- Dures (15) ---
  { id: "bluelock-d1", d: 3, t: "Combien d'attaquants sont réunis au départ dans le programme Blue Lock ?", a: "300", x: ["50", "100", "1000"], acc: ["300"] },
  { id: "bluelock-d2", d: 3, t: "Comment s'appelle l'attaquant surnommé « le Roi », obsédé par sa suprématie ?", a: "Shoei Barou", x: ["Rin Itoshi", "Meguru Bachira", "Reo Mikage"], acc: ["barou", "shoei barou"] },
  { id: "bluelock-d3", d: 3, t: "Comment s'appelle le joueur ultra-rapide aux cheveux rouges, ancien espoir blessé ?", a: "Hyoma Chigiri", x: ["Rensuke Kunigami", "Gurimu Igarashi", "Jingo Raichi"], acc: ["chigiri", "hyoma chigiri"] },
  { id: "bluelock-d4", d: 3, t: "Comment s'appelle le grand frère de Rin, milieu parti jouer en Espagne ?", a: "Sae Itoshi", x: ["Michael Kaiser", "Shoei Barou", "Seishiro Nagi"], acc: ["sae", "sae itoshi"] },
  { id: "bluelock-d5", d: 3, t: "Quelle arme secrète d'Isagi lui permet de lire le jeu et de se placer parfaitement ?", a: "Sa vision spatiale", x: ["Sa vitesse", "Sa force physique", "Sa frappe lourde"], acc: ["vision spatiale", "vision", "sens spatial"] },
  { id: "bluelock-d6", d: 3, t: "Comment s'appelle l'attaquant allemand prodige, rival d'Isagi en ligue pro ?", a: "Michael Kaiser", x: ["Alexis Ness", "Sae Itoshi", "Shoei Barou"], acc: ["kaiser", "michael kaiser"] },
  { id: "bluelock-d7", d: 3, t: "Quel club fictif allemand Isagi rejoint-il dans la ligue Neo Egoist ?", a: "Bastard München", x: ["Paris X Gen", "Manshine City", "Ubers"], acc: ["bastard munchen", "bastard munich", "bastard"] },
  { id: "bluelock-d8", d: 3, t: "Quel match oppose les joueurs de Blue Lock à la vraie sélection nationale ?", a: "Le match contre le Japon U-20", x: ["La finale de Ligue 1", "Le derby de Tokyo", "La Coupe du monde"], acc: ["japon u-20", "u-20", "match contre le japon"] },
  { id: "bluelock-d9", d: 3, t: "Comment s'appelle le fidèle acolyte allemand de Kaiser, adorateur de son génie ?", a: "Alexis Ness", x: ["Reo Mikage", "Meguru Bachira", "Yo Hiori"], acc: ["ness", "alexis ness"] },
  { id: "bluelock-d10", d: 3, t: "Comment s'appelle l'attaquant droit et héroïque, transformé après un passage en Wildcard ?", a: "Rensuke Kunigami", x: ["Shoei Barou", "Hyoma Chigiri", "Meguru Bachira"], acc: ["kunigami", "rensuke kunigami"] },
  { id: "bluelock-d11", d: 3, t: "Comment appelle-t-on l'état de concentration extrême des joueurs ?", a: "Le Flow", x: ["Le Zen", "Le Boost", "Le Rush"], acc: ["flow", "le flow"] },
  { id: "bluelock-d12", d: 3, t: "Comment s'appelle le gardien de but à l'allure de zombie, ami d'Isagi ?", a: "Gagamaru", x: ["Aoshi Tokimitsu", "Jyubei Aryu", "Wataru Kuon"], acc: ["gagamaru", "gin gagamaru"] },
  { id: "bluelock-d13", d: 3, t: "Quelle ligue oppose les meilleurs de Blue Lock à des clubs pros ?", a: "La Neo Egoist League", x: ["La Ligue des Champions", "La J-League", "La Super League"], acc: ["neo egoist league", "nel"] },
  { id: "bluelock-d14", d: 3, t: "Comment s'appelle le dessinateur du manga Blue Lock ?", a: "Yusuke Nomura", x: ["Yusuke Murata", "Takehiko Inoue", "Tsugumi Ohba"], acc: ["yusuke nomura", "nomura"] },
  { id: "bluelock-d15", d: 3, t: "Quel joueur, meilleur attaquant du monde, est l'idole d'Isagi à Bastard München ?", a: "Noel Noa", x: ["Michael Kaiser", "Sae Itoshi", "Chris Prince"], acc: ["noel noa", "noa"] },
  // --- Pro (20) ---
  { id: "bluelock-p1", d: 4, t: "En quelle année l'anime Blue Lock a-t-il été diffusé pour la première fois ?", a: "2022", x: ["2018", "2020", "2024"], acc: ["2022"] },
  { id: "bluelock-p2", d: 4, t: "Dans quel magazine le manga Blue Lock est-il prépublié ?", a: "Le Weekly Shonen Magazine", x: ["Le Weekly Shonen Jump", "Le Shonen Sunday", "Le Young Jump"], acc: ["shonen magazine", "weekly shonen magazine"] },
  { id: "bluelock-p3", d: 4, t: "Comment s'appelle le film dérivé de 2024 centré sur un joueur prodige ?", a: "Blue Lock: Episode Nagi", x: ["Blue Lock: Episode Isagi", "Blue Lock: Episode Rin", "Blue Lock: Le Film"], acc: ["episode nagi", "blue lock episode nagi"] },
  { id: "bluelock-p4", d: 4, t: "Comment s'appelle le club parisien fictif de la Neo Egoist League ?", a: "Paris X Gen", x: ["Bastard München", "Manshine City", "Ubers"], acc: ["paris x gen", "paris"] },
  { id: "bluelock-p5", d: 4, t: "Comment appelle-t-on la vision panoramique du terrain qu'Isagi développe ?", a: "La métavision", x: ["La télépathie", "La superforce", "L'hypervitesse"], acc: ["metavision", "métavision", "meta vision"] },
  { id: "bluelock-p6", d: 4, t: "Comment s'appelle le milieu manipulateur et provocateur, rival puis allié d'Isagi ?", a: "Tabito Karasu", x: ["Yo Hiori", "Nijiro Nanase", "Jyubei Aryu"], acc: ["karasu", "tabito karasu"] },
  { id: "bluelock-p7", d: 4, t: "Comment s'appelle le défenseur charismatique et retors mis en avant dans la ligue ?", a: "Oliver Aiku", x: ["Michael Kaiser", "Shoei Barou", "Noel Noa"], acc: ["aiku", "oliver aiku"] },
  { id: "bluelock-p8", d: 4, t: "Comment s'appelle le géant timide à la puissance physique impressionnante ?", a: "Aoshi Tokimitsu", x: ["Gin Gagamaru", "Jingo Raichi", "Wataru Kuon"], acc: ["tokimitsu", "aoshi tokimitsu"] },
  { id: "bluelock-p9", d: 4, t: "Quelle phase initiale départage les joueurs par un classement individuel impitoyable ?", a: "La première sélection", x: ["La finale", "Le tournoi amical", "Les qualifications"], acc: ["premiere selection", "first selection", "selection"] },
  { id: "bluelock-p10", d: 4, t: "Comment s'appelle le club fictif de Manshine, autre équipe de la ligue ?", a: "Manshine City", x: ["Bastard München", "Paris X Gen", "Ubers"], acc: ["manshine city", "manshine"] },
  { id: "bluelock-p11", d: 4, t: "Quel poste Sae Itoshi, le prodige parti en Espagne, occupe-t-il ?", a: "Milieu de terrain", x: ["Gardien", "Défenseur central", "Ailier"], acc: ["milieu", "milieu de terrain"] },
  { id: "bluelock-p12", d: 4, t: "À quoi Isagi compare-t-il mentalement l'action de marquer un but ?", a: "À résoudre une équation", x: ["À peindre un tableau", "À écrire un poème", "À gravir une montagne"], acc: ["equation", "resoudre une equation", "équation"] },
  { id: "bluelock-p13", d: 4, t: "Dans quel pays part jouer Sae Itoshi avant de revenir ?", a: "L'Espagne", x: ["L'Angleterre", "L'Allemagne", "Le Brésil"], acc: ["espagne", "l'espagne"] },
  { id: "bluelock-p14", d: 4, t: "Comment s'appelle le joueur roublard et rapide, spécialiste des espaces, prénommé Eita ?", a: "Eita Otoya", x: ["Tabito Karasu", "Yo Hiori", "Gin Gagamaru"], acc: ["otoya", "eita otoya"] },
  { id: "bluelock-p15", d: 4, t: "Quelle responsable de la Fédération recrute Ego pour lancer le projet ?", a: "Anri Teieri", x: ["Une journaliste sportive", "La mère d'Isagi", "Une ancienne joueuse"], acc: ["anri", "anri teieri"] },
  { id: "bluelock-p16", d: 4, t: "Quel ancien attaquant anglais déchu encadre une phase de Blue Lock ?", a: "Chris Prince", x: ["Noel Noa", "Jinpachi Ego", "Oliver Aiku"], acc: ["chris prince", "prince"] },
  { id: "bluelock-p17", d: 4, t: "Comment s'appelle la frappe surpuissante signature de Kaiser ?", a: "Le Kaiser Impact", x: ["Le Barou Shot", "Le Nagi Trap", "Le Rin Strike"], acc: ["kaiser impact"] },
  { id: "bluelock-p18", d: 4, t: "Dans quel club évoluent Sae Itoshi et Ryusei Shidou dans la ligue ?", a: "Ubers", x: ["Bastard München", "Paris X Gen", "Manshine City"], acc: ["ubers"] },
  { id: "bluelock-p19", d: 4, t: "Comment s'appelle l'attaquant déjanté et instinctif, coéquipier de Sae chez Ubers ?", a: "Ryusei Shidou", x: ["Michael Kaiser", "Oliver Aiku", "Alexis Ness"], acc: ["shidou", "ryusei shidou"] },
  { id: "bluelock-p20", d: 4, t: "Quelle rupture Ego impose-t-il à la culture du football japonais ?", a: "Abandonner le collectif au profit de l'égoïsme", x: ["Interdire les gardiens", "Jouer sans ballon", "Supprimer les entraîneurs"], acc: ["egoisme", "abandonner le collectif", "individualisme"] },
]);
