import { universe } from "../_build";

export const drstone = universe("manga", "Dr. Stone", [
  // --- Faciles (5) ---
  { id: "drstone-f1", d: 1, t: "Que devient toute l'humanité au début de Dr. Stone ?", a: "Elle est pétrifiée en pierre", x: ["Elle est congelée", "Elle disparaît dans l'espace", "Elle rétrécit"], acc: ["petrifiee", "pétrifiée", "pierre"] },
  { id: "drstone-f2", d: 1, t: "Quel est le domaine de génie du héros Senku ?", a: "La science", x: ["La magie", "Le sport", "La cuisine"], acc: ["science", "la science"] },
  { id: "drstone-f3", d: 1, t: "Combien de temps environ s'écoule avant le réveil de Senku ?", a: "Environ 3700 ans", x: ["Environ 100 ans", "Environ 500 ans", "Environ un million d'années"], acc: ["3700", "3700 ans"] },
  { id: "drstone-f4", d: 1, t: "Quel est le grand objectif de Senku dans ce monde de pierre ?", a: "Reconstruire la civilisation", x: ["Fuir sur la Lune", "Devenir roi", "Trouver un trésor"], acc: ["reconstruire la civilisation"] },
  { id: "drstone-f5", d: 1, t: "Que s'exclame souvent Senku face à un défi scientifique ?", a: "C'est excitant", x: ["C'est fini", "C'est magique", "C'est interdit"], acc: ["c'est excitant", "get excited"] },
  // --- Moyennes (10) ---
  { id: "drstone-m1", d: 2, t: "Comment se nomme le héros scientifique de Dr. Stone ?", a: "Senku Ishigami", x: ["Taiju Oki", "Tsukasa Shishio", "Chrome"], acc: ["senku", "senku ishigami"] },
  { id: "drstone-m2", d: 2, t: "Quel ami costaud et increvable est réveillé en premier avec Senku ?", a: "Taiju", x: ["Chrome", "Gen", "Ryusui"], acc: ["taiju", "taiju oki"] },
  { id: "drstone-m3", d: 2, t: "Quel lycéen surpuissant veut fonder un monde neuf sans les adultes ?", a: "Tsukasa", x: ["Chrome", "Kinro", "Ukyo"], acc: ["tsukasa", "tsukasa shishio"] },
  { id: "drstone-m4", d: 2, t: "Que faut-il fabriquer pour dépétrifier les humains ?", a: "Un fluide de réveil", x: ["Une potion magique", "Un vaccin", "Une machine à remonter le temps"], acc: ["fluide de reveil", "nital"] },
  { id: "drstone-m5", d: 2, t: "Quel jeune « sorcier » du village, en réalité savant autodidacte, rejoint Senku ?", a: "Chrome", x: ["Taiju", "Gen", "Kinro"], acc: ["chrome"] },
  { id: "drstone-m6", d: 2, t: "Quelle guerrière agile et blonde devient une alliée clé de Senku au village ?", a: "Kohaku", x: ["Suika", "Yuzuriha", "Ruri"], acc: ["kohaku"] },
  { id: "drstone-m7", d: 2, t: "Comment Senku baptise-t-il le camp qu'il fonde pour rebâtir le savoir ?", a: "Le Royaume de la Science", x: ["L'Empire Tsukasa", "Le Village de pierre", "La Guilde"], acc: ["royaume de la science"] },
  { id: "drstone-m8", d: 2, t: "Quel détail marque la coiffure verte de Senku ?", a: "Une mèche en éclair", x: ["Une couronne", "Des tresses", "Un chignon"], acc: ["meche en eclair", "eclair"] },
  { id: "drstone-m9", d: 2, t: "En quelle année l'anime Dr. Stone a-t-il été diffusé ?", a: "2019", x: ["2014", "2016", "2022"], acc: ["2019"] },
  { id: "drstone-m10", d: 2, t: "Sur quel thème central, rare pour un shonen, repose Dr. Stone ?", a: "La science", x: ["La cuisine", "Le football", "La musique"], acc: ["science", "la science"] },
  // --- Dures (15) ---
  { id: "drstone-d1", d: 3, t: "Sur quel acide, tiré de nids de chauves-souris, repose le premier fluide de réveil ?", a: "L'acide nitrique", x: ["L'acide citrique", "L'acide sulfurique", "Le vinaigre"], acc: ["acide nitrique", "nital"] },
  { id: "drstone-d2", d: 3, t: "Quelle jeune fille, dont Taiju est amoureux, est déterrée intacte ?", a: "Yuzuriha", x: ["Kohaku", "Suika", "Ruri"], acc: ["yuzuriha"] },
  { id: "drstone-d3", d: 3, t: "Quelle fillette porte un casque troué en écorce de pastèque ?", a: "Suika", x: ["Kohaku", "Ruri", "Yuzuriha"], acc: ["suika"] },
  { id: "drstone-d4", d: 3, t: "Quel mentaliste manipulateur finit par passer du côté de Senku ?", a: "Gen Asagiri", x: ["Ryusui", "Ukyo", "Chrome"], acc: ["gen", "gen asagiri"] },
  { id: "drstone-d5", d: 3, t: "Quels deux gardes du village, l'un sérieux l'autre trouillard, protègent Ruri ?", a: "Kinro et Ginro", x: ["Chrome et Gen", "Taiju et Senku", "Ukyo et Ryusui"], acc: ["kinro et ginro"] },
  { id: "drstone-d6", d: 3, t: "Quel vieil artisan surdoué fabrique les inventions de Senku ?", a: "Kaseki", x: ["Chrome", "Kinro", "Ginro"], acc: ["kaseki"] },
  { id: "drstone-d7", d: 3, t: "Comment s'appelle le village où Senku découvre des descendants d'humains ?", a: "Ishigami", x: ["Tsukasa", "Treasure Town", "Stone City"], acc: ["ishigami"] },
  { id: "drstone-d8", d: 3, t: "Quelle prêtresse du village conserve les « 100 récits », un savoir précieux ?", a: "Ruri", x: ["Kohaku", "Suika", "Yuzuriha"], acc: ["ruri"] },
  { id: "drstone-d9", d: 3, t: "Qui a transmis à l'origine ces « 100 récits », l'astronaute père adoptif de Senku ?", a: "Byakuya", x: ["Tsukasa", "Kaseki", "Xeno"], acc: ["byakuya"] },
  { id: "drstone-d10", d: 3, t: "Comment le père de Senku et ses collègues ont-ils échappé à la pétrification ?", a: "Ils étaient dans l'espace", x: ["Ils étaient sous terre", "Ils dormaient profondément", "Ils portaient une armure"], acc: ["dans l'espace", "espace"] },
  { id: "drstone-d11", d: 3, t: "Quel navigateur avide, aimant l'argent et le luxe, pilote le navire du Royaume de la Science ?", a: "Ryusui", x: ["Ukyo", "Gen", "Chrome"], acc: ["ryusui"] },
  { id: "drstone-d12", d: 3, t: "Quel archer à l'ouïe exceptionnelle rejoint Senku ?", a: "Ukyo", x: ["Ryusui", "Kinro", "Gen"], acc: ["ukyo"] },
  { id: "drstone-d13", d: 3, t: "Quel appareil de communication Senku parvient-il à reconstruire à partir de rien ?", a: "Un téléphone", x: ["Une télévision", "Un avion à réaction", "Un ordinateur portable"], acc: ["telephone", "téléphone"] },
  { id: "drstone-d14", d: 3, t: "Quelle boisson pétillante Senku recrée-t-il pour séduire de nouveaux alliés ?", a: "Du cola", x: ["Du champagne", "Du café", "Du thé glacé"], acc: ["cola"] },
  { id: "drstone-d15", d: 3, t: "Comment s'appelle le camp rival de Tsukasa, fondé sur la seule force ?", a: "L'Empire de la Force", x: ["Le Royaume de la Science", "Le Village Ishigami", "La Guilde des marchands"], acc: ["empire de la force", "empire tsukasa"] },
  // --- Pro (20) ---
  { id: "drstone-p1", d: 4, t: "Quel scénariste, aussi derrière Eyeshield 21, a écrit Dr. Stone ?", a: "Riichiro Inagaki", x: ["Boichi", "Yusuke Murata", "Takeshi Obata"], acc: ["inagaki", "riichiro inagaki"] },
  { id: "drstone-p2", d: 4, t: "Quel dessinateur coréen illustre Dr. Stone ?", a: "Boichi", x: ["Riichiro Inagaki", "Takeshi Obata", "Tite Kubo"], acc: ["boichi"] },
  { id: "drstone-p3", d: 4, t: "D'où semblait provenir le mystérieux flash qui a pétrifié l'humanité ?", a: "De l'espace", x: ["Des océans", "Du noyau terrestre", "Des volcans"], acc: ["de l'espace", "espace"] },
  { id: "drstone-p4", d: 4, t: "Quel mystérieux interlocuteur, à l'origine de la pétrification, communique par messages ?", a: "Why-man", x: ["Xeno", "Tsukasa", "Byakuya"], acc: ["why-man", "whyman"] },
  { id: "drstone-p5", d: 4, t: "Où se cache finalement la source de la pétrification, cible ultime de Senku ?", a: "Sur la Lune", x: ["Au fond de l'océan", "Au pôle Nord", "Sous un volcan"], acc: ["lune", "sur la lune"] },
  { id: "drstone-p6", d: 4, t: "Quelle expression chiffrée démesurée Senku emploie-t-il pour dire qu'il est sûr de lui ?", a: "Dix milliards de pour cent", x: ["Cent pour cent", "Mille pour cent", "Un pour cent"], acc: ["dix milliards", "10 milliards"] },
  { id: "drstone-p7", d: 4, t: "Quel scientifique américain, ancien mentor de Senku, devient un rival aux États-Unis ?", a: "Xeno", x: ["Stanley", "Byakuya", "Chrome"], acc: ["xeno"] },
  { id: "drstone-p8", d: 4, t: "Quel redoutable tireur d'élite sert de bras armé à Xeno ?", a: "Stanley", x: ["Ukyo", "Tsukasa", "Ryusui"], acc: ["stanley"] },
  { id: "drstone-p9", d: 4, t: "Quelle propriété inattendue de la pétrification permet de « conserver » puis de soigner un corps ?", a: "Elle met le corps en pause", x: ["Elle le rajeunit", "Elle le clone", "Elle le rend invisible"], acc: ["met le corps en pause", "conserve"] },
  { id: "drstone-p10", d: 4, t: "Que fait Senku du corps de Tsukasa, mortellement blessé, en attendant de pouvoir le sauver ?", a: "Il le repétrifie pour le conserver", x: ["Il l'enterre", "Il le congèle", "Il l'abandonne"], acc: ["repetrifie", "le conserve"] },
  { id: "drstone-p11", d: 4, t: "Comment nomme-t-on l'affrontement entre le Royaume de la Science et l'empire de Tsukasa ?", a: "La Guerre de pierre", x: ["La Grande Dépétrification", "La Guerre du feu", "La Bataille du savoir"], acc: ["guerre de pierre", "stone wars"] },
  { id: "drstone-p12", d: 4, t: "Comment Senku a-t-il su combien de temps s'était écoulé, s'étant réveillé lucide ?", a: "Il a compté les secondes", x: ["Il a lu un calendrier", "On le lui a dit", "Il a deviné au hasard"], acc: ["compte les secondes", "compté les secondes"] },
  { id: "drstone-p13", d: 4, t: "Quel « médicament miracle » Senku fabrique-t-il pour guérir Ruri ?", a: "Un antibiotique", x: ["Un vaccin", "De la morphine", "De l'aspirine"], acc: ["antibiotique", "sulfamide"] },
  { id: "drstone-p14", d: 4, t: "Que collectionnait Chrome dans sa cabane avant de rencontrer Senku ?", a: "Des minéraux et objets étranges", x: ["Des armes", "Des pièces d'or", "Des livres anciens"], acc: ["mineraux", "tresors", "trésors"] },
  { id: "drstone-p15", d: 4, t: "Dans quel magazine Dr. Stone a-t-il été prépublié ?", a: "Weekly Shonen Jump", x: ["Shonen Magazine", "Young Jump", "Ribon"], acc: ["shonen jump", "weekly shonen jump"] },
  { id: "drstone-p16", d: 4, t: "Vers quel continent le Royaume de la Science met-il le cap pour trouver de nouvelles ressources ?", a: "L'Amérique", x: ["L'Afrique", "L'Australie", "L'Antarctique"], acc: ["amerique", "amérique"] },
  { id: "drstone-p17", d: 4, t: "Quel lien unit Byakuya à Senku ?", a: "C'est son père adoptif", x: ["C'est son frère", "C'est son oncle", "C'est son professeur"], acc: ["pere adoptif", "père adoptif"] },
  { id: "drstone-p18", d: 4, t: "Qui Senku ramène-t-il volontairement à la vie en premier grâce à son fluide ?", a: "Taiju", x: ["Tsukasa", "Yuzuriha", "Chrome"], acc: ["taiju"] },
  { id: "drstone-p19", d: 4, t: "Pourquoi Senku réveille-t-il d'abord le puissant Tsukasa ?", a: "Pour avoir de la force au combat", x: ["Pour se venger de lui", "Par pure erreur", "Pour l'emprisonner"], acc: ["force au combat", "sa force"] },
  { id: "drstone-p20", d: 4, t: "Comment surnomme-t-on le petit appareil capable de pétrifier, retrouvé plus tard ?", a: "Méduse", x: ["Gorgone", "Basilic", "Cerbère"], acc: ["meduse", "méduse", "medusa"] },
]);
