import { universe } from "../_build";

export const eightysix = universe("manga", "86", [
  // --- Faciles (5) ---
  { id: "e86-f1", d: 1, t: "Autour de quel type de machines de guerre l'histoire de 86 tourne-t-elle ?", a: "Des robots de combat", x: ["Des voitures de course", "Des avions de ligne", "Des sous-marins"], acc: ["robots", "mechas", "robots de combat"] },
  { id: "e86-f2", d: 1, t: "Comment la République traite-t-elle les « 86 » qu'elle envoie combattre ?", a: "Comme des sous-hommes", x: ["Comme des héros", "Comme des rois", "Comme des invités"], acc: ["sous-hommes"] },
  { id: "e86-f3", d: 1, t: "Comment se nomment les armées de drones autonomes ennemis ?", a: "La Legion", x: ["Les Titans", "Les Cylons", "Les Terminators"], acc: ["legion", "la legion"] },
  { id: "e86-f4", d: 1, t: "Comment Lena, l'officier, communique-t-elle d'abord avec l'escadron ?", a: "Par radio", x: ["Par lettres", "En personne", "Par télépathie animale"], acc: ["radio", "par radio"] },
  { id: "e86-f5", d: 1, t: "86 est adapté de quel type d'œuvre littéraire japonaise ?", a: "Un light novel", x: ["Un roman policier", "Une pièce de kabuki", "Un journal intime"], acc: ["light novel"] },
  // --- Moyennes (10) ---
  { id: "e86-m1", d: 2, t: "Quelle République prétend mener une guerre « sans morts » ?", a: "San Magnolia", x: ["Giad", "Roa Gracia", "Wald"], acc: ["san magnolia"] },
  { id: "e86-m2", d: 2, t: "Quel est le surnom au combat de Shinei Nouzen ?", a: "Undertaker", x: ["Reaper", "Ghost", "Phantom"], acc: ["undertaker", "croque-mort"] },
  { id: "e86-m3", d: 2, t: "Comment se nomme le capitaine de l'escadron Spearhead, héros de la série ?", a: "Shinei Nouzen", x: ["Raiden Shuga", "Theoto Rikka", "Vladilena Milizé"], acc: ["shin", "shinei", "shinei nouzen"] },
  { id: "e86-m4", d: 2, t: "Comment se nomme la jeune major qui commande l'escadron à distance ?", a: "Vladilena Milizé", x: ["Frederica Rosenfort", "Anju Emma", "Kurena Kukumila"], acc: ["lena", "vladilena", "vladilena milize"] },
  { id: "e86-m5", d: 2, t: "Comment s'appelle l'escadron dont Shin prend la tête ?", a: "Spearhead", x: ["Nordlicht", "Sirius", "Cyclops"], acc: ["spearhead"] },
  { id: "e86-m6", d: 2, t: "Quels engins à peine blindés les 86 pilotent-ils au début de la guerre ?", a: "Des Juggernaut", x: ["Des Gundam", "Des Eva", "Des Jaeger"], acc: ["juggernaut"] },
  { id: "e86-m7", d: 2, t: "Quel numéro de secteur, inexistant sur les cartes, donne son nom à la série ?", a: "Le 86e", x: ["Le 42e", "Le 7e", "Le 100e"], acc: ["86", "86e"] },
  { id: "e86-m8", d: 2, t: "Quel don particulier Shin possède-t-il sur le champ de bataille ?", a: "Entendre la voix des morts", x: ["Voler", "Devenir invisible", "Lire l'avenir"], acc: ["voix des morts", "entendre les morts"] },
  { id: "e86-m9", d: 2, t: "En quelle année l'anime 86 a-t-il été diffusé ?", a: "2021", x: ["2015", "2018", "2023"], acc: ["2021"] },
  { id: "e86-m10", d: 2, t: "Quel dispositif de synchronisation mentale relie Lena à ses soldats ?", a: "Le Para-RAID", x: ["Le Nerv-Gear", "Le Para-Link", "Le Neuro-Sync"], acc: ["para-raid", "para raid"] },
  // --- Dures (15) ---
  { id: "e86-d1", d: 3, t: "Contre quel Empire la République est-elle d'abord en guerre ?", a: "L'Empire de Giad", x: ["L'Empire de San Magnolia", "L'Empire Britannia", "L'Empire Galactique"], acc: ["giad", "empire de giad"] },
  { id: "e86-d2", d: 3, t: "Quelle faiblesse la Legion était-elle censée avoir, avant de la dépasser ?", a: "Une durée de vie limitée", x: ["Une peur du feu", "Un besoin d'eau", "Une seule unité"], acc: ["duree de vie limitee", "durée de vie"] },
  { id: "e86-d3", d: 3, t: "Quel proche de Shin est devenu une unité de la Legion qu'il doit affronter ?", a: "Son frère", x: ["Son père", "Sa sœur", "Son fils"], acc: ["son frere", "frère", "frere"] },
  { id: "e86-d4", d: 3, t: "Comment nomme-t-on les Legion d'élite ayant absorbé un cerveau humain ?", a: "Les Bergers", x: ["Les Rois", "Les Anges", "Les Sentinelles"], acc: ["bergers", "shepherd", "berger"] },
  { id: "e86-d5", d: 3, t: "Quelle caractéristique physique distingue les 86 des citoyens « Alba » ?", a: "Des cheveux et yeux colorés", x: ["Une grande taille", "Une peau bleue", "Des ailes"], acc: ["cheveux et yeux colores", "colores"] },
  { id: "e86-d6", d: 3, t: "De quelle couleur sont les cheveux et les yeux de la population dominante, les Alba ?", a: "Argentés", x: ["Roux", "Verts", "Dorés"], acc: ["argentes", "argentés", "argent"] },
  { id: "e86-d7", d: 3, t: "Quelle nation recueille Shin et ses camarades après la chute du front de la République ?", a: "La Fédération de Giad", x: ["La République de San Magnolia", "Le Royaume de Roa Gracia", "La Principauté de Wald"], acc: ["federation de giad", "federation", "fédération"] },
  { id: "e86-d8", d: 3, t: "Quelle fillette, ancienne impératrice de Giad, rejoint le groupe ?", a: "Frederica", x: ["Lena", "Anju", "Kurena"], acc: ["frederica", "frederica rosenfort"] },
  { id: "e86-d9", d: 3, t: "Quel soldat fidèle et solide est le bras droit de Shin dans l'escadron ?", a: "Raiden", x: ["Theo", "Ernst", "Daiya"], acc: ["raiden"] },
  { id: "e86-d10", d: 3, t: "Quel nouveau modèle de mecha, bien plus performant, remplace le Juggernaut ?", a: "Le Reginleif", x: ["Le Vanargand", "Le Juggernaut II", "Le Sirin"], acc: ["reginleif"] },
  { id: "e86-d11", d: 3, t: "Quel dirigeant de la Fédération recueille et adopte officieusement les jeunes 86 ?", a: "Ernst", x: ["Willem", "Raiden", "Shin"], acc: ["ernst", "ernst zimerman"] },
  { id: "e86-d12", d: 3, t: "Que peignent ou gravent les 86 en mémoire de leurs camarades tombés ?", a: "Leurs noms", x: ["Des fleurs", "Des numéros", "Des drapeaux"], acc: ["noms", "leurs noms"] },
  { id: "e86-d13", d: 3, t: "Quelle jeune tireuse d'élite de l'escadron nourrit des sentiments pour Shin ?", a: "Kurena", x: ["Anju", "Lena", "Frederica"], acc: ["kurena"] },
  { id: "e86-d14", d: 3, t: "Quel membre de l'escadron aime dessiner et sert d'éclaireur ?", a: "Theo", x: ["Raiden", "Shin", "Daiya"], acc: ["theo"] },
  { id: "e86-d15", d: 3, t: "Pourquoi la République peut-elle prétendre n'avoir « aucun mort » malgré la guerre ?", a: "Les 86 ne sont pas comptés comme humains", x: ["La guerre est virtuelle", "Personne ne meurt vraiment", "Des robots se battent seuls"], acc: ["pas comptes comme humains"] },
  // --- Pro (20) ---
  { id: "e86-p1", d: 4, t: "Quel auteur a écrit les light novels 86 ?", a: "Asato Asato", x: ["Reki Kawahara", "Fujino Omori", "Kugane Maruyama"], acc: ["asato asato", "asato"] },
  { id: "e86-p2", d: 4, t: "Quel studio a produit l'anime 86 ?", a: "A-1 Pictures", x: ["MAPPA", "Ufotable", "Bones"], acc: ["a-1 pictures", "a1 pictures"] },
  { id: "e86-p3", d: 4, t: "Quel compositeur, connu pour L'Attaque des Titans, signe aussi la musique de 86 ?", a: "Hiroyuki Sawano", x: ["Yoko Kanno", "Yuki Kajiura", "Joe Hisaishi"], acc: ["sawano", "hiroyuki sawano"] },
  { id: "e86-p4", d: 4, t: "Le don de Shin lui permet surtout de percevoir quoi à l'avance ?", a: "L'approche de la Legion", x: ["La météo", "Les pensées de Lena", "Les pannes moteur"], acc: ["approche de la legion"] },
  { id: "e86-p5", d: 4, t: "Quel grade militaire Lena détient-elle malgré son jeune âge ?", a: "Major", x: ["Général", "Caporal", "Amiral"], acc: ["major"] },
  { id: "e86-p6", d: 4, t: "Contrairement aux autres « Handlers », qu'est-ce qui distingue Lena ?", a: "Elle respecte les 86", x: ["Elle combat au front", "Elle est une 86", "Elle refuse de parler"], acc: ["respecte les 86"] },
  { id: "e86-p7", d: 4, t: "Qui a créé la Legion à l'origine ?", a: "L'Empire de Giad", x: ["La République", "La Fédération", "Le Royaume de Roa Gracia"], acc: ["empire de giad", "giad"] },
  { id: "e86-p8", d: 4, t: "Quel drone de soutien fidèle accompagne l'escadron comme une mascotte ?", a: "Fido", x: ["Boo", "Rei", "Kero"], acc: ["fido"] },
  { id: "e86-p9", d: 4, t: "Que collectionne Shin pour honorer chaque camarade mort au combat ?", a: "Leurs plaques d'identité", x: ["Leurs armes", "Leurs photos", "Leurs lettres"], acc: ["plaques d'identite", "plaques"] },
  { id: "e86-p10", d: 4, t: "Quel indicatif radio Lena porte-t-elle auprès de l'escadron ?", a: "Handler One", x: ["Undertaker", "Big Boss", "Reaper"], acc: ["handler one"] },
  { id: "e86-p11", d: 4, t: "Comment les 86 surnomment-ils amèrement leurs Juggernaut si fragiles ?", a: "Des cercueils", x: ["Des forteresses", "Des jouets", "Des chars lourds"], acc: ["cercueils", "cercueil"] },
  { id: "e86-p12", d: 4, t: "Quelle promesse mensongère la République fait-elle aux 86 après cinq ans de service ?", a: "La liberté", x: ["La richesse", "Un titre de noblesse", "Un long voyage"], acc: ["liberte", "liberté"] },
  { id: "e86-p13", d: 4, t: "Combien de secteurs « officiels » la République compte-t-elle, le 86e n'existant pas ?", a: "85", x: ["50", "100", "42"], acc: ["85", "quatre-vingt-cinq"] },
  { id: "e86-p14", d: 4, t: "Comment se prénomme le grand frère de Shin, devenu un Berger de la Legion ?", a: "Rei", x: ["Raiden", "Ernst", "Theo"], acc: ["rei", "shourei"] },
  { id: "e86-p15", d: 4, t: "Quelle membre posée de l'escadron cache une lourde histoire familiale ?", a: "Anju", x: ["Kurena", "Frederica", "Lena"], acc: ["anju"] },
  { id: "e86-p16", d: 4, t: "Quelle unité d'élite de la Fédération Shin et ses amis rejoignent-ils ?", a: "Le Strike Package", x: ["La Spearhead", "La Nordlicht", "La Task Force 141"], acc: ["strike package"] },
  { id: "e86-p17", d: 4, t: "Quel message fort l'œuvre porte-t-elle à travers ses personnages morts ?", a: "Se souvenir de leurs noms", x: ["La gloire de la guerre", "L'inutilité des sentiments", "La supériorité des machines"], acc: ["se souvenir de leurs noms"] },
  { id: "e86-p18", d: 4, t: "Comment la Legion a-t-elle contourné sa durée de vie limitée ?", a: "En absorbant des cerveaux humains", x: ["En se rechargeant au soleil", "En fusionnant entre elles", "En creusant sous terre"], acc: ["cerveaux humains"] },
  { id: "e86-p19", d: 4, t: "Vers quelle mission quasi suicide la République envoie-t-elle finalement l'escadron ?", a: "Une reconnaissance spéciale", x: ["Une parade", "Une permission", "Une retraite"], acc: ["reconnaissance speciale", "special reconnaissance"] },
  { id: "e86-p20", d: 4, t: "Qui illustre les light novels originaux de 86 ?", a: "Shirabii", x: ["Abec", "Yasuda Suzuhito", "Fujichoco"], acc: ["shirabii"] },
]);
