import { universe } from "../_build";

export const fma = universe("manga", "Fullmetal Alchemist", [
  // --- Faciles (5) ---
  { id: "fma-f1", d: 1, t: "Qui est le jeune héros alchimiste de Fullmetal Alchemist ?", a: "Edward Elric", acc: ["edward", "ed", "edward elric"], x: ["Alphonse", "Roy", "Winry"] },
  { id: "fma-f2", d: 1, t: "Qui est le frère d'Edward, dont l'âme est scellée dans une armure ?", a: "Alphonse Elric", acc: ["alphonse", "al"], x: ["Roy", "Ling", "Scar"] },
  { id: "fma-f3", d: 1, t: "Quelle science est au cœur de l'univers de FMA ?", a: "L'alchimie", acc: ["alchimie"], x: ["La magie", "Le Nen", "Le Ki"] },
  { id: "fma-f4", d: 1, t: "Quelle loi fondamentale régit l'alchimie ?", a: "L'échange équivalent", acc: ["echange equivalent"], x: ["Le sacrifice de sang", "La prière", "La chance"] },
  { id: "fma-f5", d: 1, t: "Quel est le surnom d'Edward ?", a: "Le Fullmetal Alchemist", acc: ["fullmetal", "alchimiste d'acier", "fullmetal alchemist"], x: ["Le Flame Alchemist", "Le Strong Arm", "L'Alchimiste de fer"] },

  // --- Moyennes (10) ---
  { id: "fma-m1", d: 2, t: "Qu'ont tenté de faire les frères Elric enfants, brisant le tabou ultime ?", a: "Ressusciter leur mère", acc: ["ressusciter leur mere", "ramener leur mere"], x: ["Créer de l'or", "Devenir immortels", "Voler la pierre"] },
  { id: "fma-m2", d: 2, t: "Quel objet amplifie énormément l'alchimie et est très convoité ?", a: "La Pierre Philosophale", acc: ["pierre philosophale"], x: ["L'Œil du dragon", "Le Graal", "L'Orbe"] },
  { id: "fma-m3", d: 2, t: "Quelle amie d'enfance mécanicienne répare les prothèses d'Ed ?", a: "Winry Rockbell", acc: ["winry"], x: ["Riza", "Lan Fan", "May"] },
  { id: "fma-m4", d: 2, t: "Comment appelle-t-on les prothèses métalliques d'Edward ?", a: "L'automail", acc: ["automail"], x: ["Le cyberware", "L'exosquelette", "La ferraille"] },
  { id: "fma-m5", d: 2, t: "Quel colonel est surnommé le « Flame Alchemist » ?", a: "Roy Mustang", acc: ["roy mustang", "mustang"], x: ["Armstrong", "Hughes", "King Bradley"] },
  { id: "fma-m6", d: 2, t: "Quel ami militaire de Mustang, adorant sa famille, est assassiné ?", a: "Maes Hughes", acc: ["hughes", "maes hughes"], x: ["Armstrong", "Falman", "Havoc"] },
  { id: "fma-m7", d: 2, t: "Comment appelle-t-on les ennemis nommés d'après les péchés capitaux ?", a: "Les Homonculus", acc: ["homonculus", "homoncules"], x: ["Les Ishvals", "Les Chimères", "Les Alchimistes"] },
  { id: "fma-m8", d: 2, t: "Quelle homonculus séductrice incarne la Luxure ?", a: "Lust", x: ["Envy", "Gluttony", "Sloth"] },
  { id: "fma-m9", d: 2, t: "Quel homonculus glouton dévore tout ?", a: "Gluttony", acc: ["gluttony", "gloutonnerie", "gula"], x: ["Lust", "Greed", "Wrath"] },
  { id: "fma-m10", d: 2, t: "Quelle lieutenante tireuse d'élite est fidèle à Mustang ?", a: "Riza Hawkeye", acc: ["riza", "hawkeye"], x: ["Winry", "Lan Fan", "Olivier"] },

  // --- Dures (15) ---
  { id: "fma-d1", d: 3, t: "Que perd Edward lors de la transmutation humaine ratée ?", a: "Une jambe", acc: ["une jambe", "jambe et bras", "un bras et une jambe"], x: ["Un œil", "Sa mémoire", "Une main"] },
  { id: "fma-d2", d: 3, t: "Que perd Alphonse lors de ce même accident ?", a: "Son corps entier", acc: ["son corps", "tout son corps"], x: ["Ses jambes", "Ses souvenirs", "Sa voix"] },
  { id: "fma-d3", d: 3, t: "Quel meurtrier balafré tue les alchimistes d'État ?", a: "Scar", x: ["Kimblee", "Greed", "Envy"] },
  { id: "fma-d4", d: 3, t: "De quel peuple massacré Scar est-il issu ?", a: "Les Ishvals", acc: ["ishvals", "ishval", "ishbal"], x: ["Les Xing", "Les Drachma", "Les Amestriens"] },
  { id: "fma-d5", d: 3, t: "Qui est le « Père », créateur des Homonculus et grand méchant ?", a: "Father", acc: ["father", "le pere"], x: ["King Bradley", "Dante", "Hohenheim"] },
  { id: "fma-d6", d: 3, t: "Quel homonculus incarne l'Orgueil et se cache derrière un enfant ?", a: "Pride", acc: ["pride", "orgueil", "selim"], x: ["Wrath", "Envy", "Greed"] },
  { id: "fma-d7", d: 3, t: "Quel homonculus dirige en réalité le pays d'Amestris ?", a: "Wrath", acc: ["wrath", "king bradley", "bradley", "colere"], x: ["Pride", "Greed", "Sloth"] },
  { id: "fma-d8", d: 3, t: "Quel homonculus jaloux a déclenché en partie la guerre d'Ishval ?", a: "Envy", acc: ["envy", "envie"], x: ["Lust", "Wrath", "Sloth"] },
  { id: "fma-d9", d: 3, t: "Quel prince de Xing en quête d'immortalité devient l'hôte de Greed ?", a: "Ling Yao", acc: ["ling", "ling yao"], x: ["Scar", "Alphonse", "Kimblee"] },
  { id: "fma-d10", d: 3, t: "Qui est le père des frères Elric, un alchimiste quasi immortel ?", a: "Van Hohenheim", acc: ["hohenheim", "van hohenheim"], x: ["Mustang", "Bradley", "Father"] },
  { id: "fma-d11", d: 3, t: "Comment appelle-t-on l'alchimie alternative de Xing, orientée soin ?", a: "L'alkahestry", acc: ["alkahestry", "alchimie de xing"], x: ["La nécromancie", "Le Nen", "La géomancie"] },
  { id: "fma-d12", d: 3, t: "Quelle jeune princesse alchimiste de Xing voyage avec un petit panda ?", a: "May Chang", acc: ["may", "may chang", "mei chang"], x: ["Lan Fan", "Winry", "Riza"] },
  { id: "fma-d13", d: 3, t: "Quelle générale surnommée la « reine des glaces » commande la forteresse de Briggs ?", a: "Olivier Mira Armstrong", acc: ["olivier", "olivier armstrong"], x: ["Riza", "Izumi", "Lust"] },
  { id: "fma-d14", d: 3, t: "Quelle femme redoutable a été le maître d'alchimie des frères Elric ?", a: "Izumi Curtis", acc: ["izumi", "izumi curtis"], x: ["Winry", "Riza", "Trisha"] },
  { id: "fma-d15", d: 3, t: "Que découvre-t-on derrière la Porte de la Vérité ?", a: "La Vérité", acc: ["la verite", "verite", "truth"], x: ["Dieu", "Le futur", "Les morts"] },

  // --- Pro (20) ---
  { id: "fma-p1", d: 4, t: "De quoi une Pierre Philosophale est-elle réellement faite ?", a: "De vies humaines", acc: ["vies humaines", "ames humaines", "des ames"], x: ["D'or", "De sang de dragon", "De charbon"] },
  { id: "fma-p2", d: 4, t: "Comment se nomme l'entité qui garde la Porte de la Vérité ?", a: "La Vérité", acc: ["la verite", "verite", "truth"], x: ["Dieu", "Le Père", "Le Néant"] },
  { id: "fma-p3", d: 4, t: "Quel homonculus incarne l'Avidité et finit par trahir Father ?", a: "Greed", acc: ["greed", "avidite"], x: ["Envy", "Lust", "Pride"] },
  { id: "fma-p4", d: 4, t: "Sous quelle apparence Pride, l'aîné des homonculus, se cache-t-il ?", a: "Selim Bradley", acc: ["selim", "selim bradley"], x: ["Wrath", "Envy", "Van Hohenheim"] },
  { id: "fma-p5", d: 4, t: "Quel homonculus paresseux, géant, creuse un immense tunnel sous Amestris ?", a: "Sloth", acc: ["sloth", "paresse"], x: ["Gluttony", "Wrath", "Greed"] },
  { id: "fma-p6", d: 4, t: "Quel est le but de Father lors du « Jour Promis » ?", a: "Devenir Dieu", acc: ["devenir dieu", "absorber dieu", "absorber la verite"], x: ["Détruire la Lune", "Créer de l'or", "Ouvrir un portail vers Xing"] },
  { id: "fma-p7", d: 4, t: "De quel pays vient l'alkahestry, patrie de Ling et May ?", a: "Xing", x: ["Drachma", "Aerugo", "Creta"] },
  { id: "fma-p8", d: 4, t: "Quel alchimiste psychopathe surnommé « l'Écarlate » fait tout exploser ?", a: "Solf J. Kimblee", acc: ["kimblee", "l'ecarlate"], x: ["Scar", "Mustang", "Armstrong"] },
  { id: "fma-p9", d: 4, t: "Pourquoi Edward peut-il transmuter sans tracer de cercle ?", a: "Parce qu'il a vu la Porte de la Vérité", acc: ["il a vu la porte", "la porte de la verite", "la verite"], x: ["Grâce à l'automail", "Grâce à un tatouage", "Grâce à un gant"] },
  { id: "fma-p10", d: 4, t: "Que sacrifie Edward à la fin pour récupérer le corps d'Alphonse ?", a: "Sa capacité à faire de l'alchimie", acc: ["son alchimie", "sa porte", "ses pouvoirs"], x: ["Sa jambe", "Sa mémoire", "Sa vie"] },
  { id: "fma-p11", d: 4, t: "Comment s'appelle le chien fidèle de Riza Hawkeye ?", a: "Black Hayate", acc: ["black hayate", "hayate"], x: ["Den", "Xiao Mei", "Alexander"] },
  { id: "fma-p12", d: 4, t: "Quel titre porte le dirigeant d'Amestris ?", a: "Le Führer", acc: ["fuhrer", "führer"], x: ["Le roi", "L'empereur", "Le président"] },
  { id: "fma-p13", d: 4, t: "À quel massacre Mustang et Hawkeye ont-ils participé, qu'ils regrettent ?", a: "La guerre civile d'Ishval", acc: ["guerre d'ishval", "ishval", "guerre civile d'ishval"], x: ["La bataille de Briggs", "Le Jour Promis", "La guerre de Xing"] },
  { id: "fma-p14", d: 4, t: "Quel homonculus se régénère et prend l'apparence de n'importe qui ?", a: "Envy", x: ["Lust", "Pride", "Greed"] },
  { id: "fma-p15", d: 4, t: "Comment appelle-t-on le jour de l'éclipse choisi par Father pour son plan ?", a: "Le Jour Promis", acc: ["jour promis", "promised day"], x: ["La Nuit de sang", "L'Éclipse rouge", "La Grande Guerre"] },
  { id: "fma-p16", d: 4, t: "Sous quelle forme Father est-il apparu à l'origine ?", a: "Un petit être dans une fiole", acc: ["dans une fiole", "homoncule dans la fiole", "le nain dans la fiole"], x: ["La Vérité", "Hohenheim", "Dante"] },
  { id: "fma-p17", d: 4, t: "Quelle chimère tragique crée l'alchimiste Tucker ?", a: "Nina", acc: ["nina", "nina tucker"], x: ["May", "Winry", "Xiao Mei"] },
  { id: "fma-p18", d: 4, t: "Quel alchimiste musclé et théâtral est surnommé « Strong Arm » ?", a: "Alex Louis Armstrong", acc: ["armstrong", "alex louis armstrong"], x: ["Mustang", "Kimblee", "Hughes"] },
  { id: "fma-p19", d: 4, t: "Combien d'Homonculus sert Father au total ?", a: "7", acc: ["sept"], x: ["5", "8", "6"] },
  { id: "fma-p20", d: 4, t: "Qui tue l'homonculus Lust avec ses flammes ?", a: "Roy Mustang", acc: ["mustang", "roy mustang"], x: ["Edward", "Scar", "Alphonse"] },
]);
