import { universe } from "../_build";

export const haikyuu = universe("manga", "Haikyu", [
  // --- Faciles (5) ---
  { id: "haik-f1", d: 1, t: "Quel sport est au cœur de Haikyu ?", a: "Le volley-ball", x: ["Le basket-ball", "Le football", "Le tennis"], acc: ["volley", "volley-ball", "volleyball"] },
  { id: "haik-f2", d: 1, t: "Quel héros de petite taille compense par une détente exceptionnelle ?", a: "Shoyo Hinata", x: ["Tobio Kageyama", "Daichi Sawamura", "Kei Tsukishima"], acc: ["hinata", "shoyo hinata"] },
  { id: "haik-f3", d: 1, t: "Quel passeur de génie, surnommé « le Roi », fait équipe avec Hinata ?", a: "Tobio Kageyama", x: ["Toru Oikawa", "Koshi Sugawara", "Yu Nishinoya"], acc: ["kageyama", "tobio kageyama"] },
  { id: "haik-f4", d: 1, t: "Dans quel lycée Hinata et Kageyama jouent-ils ?", a: "Karasuno", x: ["Nekoma", "Aoba Johsai", "Shiratorizawa"], acc: ["karasuno"] },
  { id: "haik-f5", d: 1, t: "Quel oiseau symbolise l'équipe de Karasuno ?", a: "Le corbeau", x: ["Le chat", "Le hibou", "L'aigle"], acc: ["corbeau", "corbeaux", "crows"] },
  // --- Moyennes (10) ---
  { id: "haik-m1", d: 2, t: "Quel ancien joueur vedette de Karasuno, petit comme lui, inspire Hinata ?", a: "Le Petit Géant", x: ["Le Grand Roi", "L'As", "Le Gardien"], acc: ["petit geant", "petit géant", "little giant"] },
  { id: "haik-m2", d: 2, t: "Quel surnom peu flatteur Kageyama traîne-t-il depuis le collège ?", a: "Le Roi du terrain", x: ["Le Petit Géant", "Le Gardien", "Le Renard"], acc: ["roi du terrain", "king of the court"] },
  { id: "haik-m3", d: 2, t: "Quel joueur solide et fiable est le capitaine de Karasuno ?", a: "Daichi", x: ["Sugawara", "Asahi", "Tanaka"], acc: ["daichi", "daichi sawamura"] },
  { id: "haik-m4", d: 2, t: "Quel poste défensif, au maillot différent, Nishinoya occupe-t-il ?", a: "Libéro", x: ["Passeur", "Central", "Pointu"], acc: ["libero", "libéro"] },
  { id: "haik-m5", d: 2, t: "Quel grand joueur à la barbe naissante est l'as de Karasuno ?", a: "Asahi", x: ["Tanaka", "Tsukishima", "Yamaguchi"], acc: ["asahi", "azumane"] },
  { id: "haik-m6", d: 2, t: "Quel grand blond à lunettes est un redoutable contreur, souvent moqueur ?", a: "Tsukishima", x: ["Yamaguchi", "Hinata", "Nishinoya"], acc: ["tsukishima"] },
  { id: "haik-m7", d: 2, t: "Sur quelle attaque ultra-rapide repose d'abord le duo Hinata-Kageyama ?", a: "La quick", x: ["Le smash sauté", "Le service flottant", "Le bloc"], acc: ["quick", "la quick", "attaque rapide"] },
  { id: "haik-m8", d: 2, t: "Quel entraîneur, petit-fils de l'ancien coach, reprend l'équipe de Karasuno ?", a: "Ukai", x: ["Takeda", "Nekomata", "Washijo"], acc: ["ukai", "keishin ukai"] },
  { id: "haik-m9", d: 2, t: "Quel mangaka a créé Haikyu ?", a: "Haruichi Furudate", x: ["Takehiko Inoue", "Yoichi Takahashi", "Eiichiro Oda"], acc: ["furudate", "haruichi furudate"] },
  { id: "haik-m10", d: 2, t: "En quelle année l'anime Haikyu a-t-il débuté ?", a: "2014", x: ["2010", "2017", "2020"], acc: ["2014"] },
  // --- Dures (15) ---
  { id: "haik-d1", d: 3, t: "Quel surnom, évoquant une « divinité gardienne », Nishinoya porte-t-il ?", a: "Le Dieu gardien", x: ["Le Roi", "Le Petit Géant", "Le Renard"], acc: ["dieu gardien", "guardian deity"] },
  { id: "haik-d2", d: 3, t: "Dans quelle préfecture du Japon Karasuno est-il situé ?", a: "Miyagi", x: ["Tokyo", "Osaka", "Hyogo"], acc: ["miyagi"] },
  { id: "haik-d3", d: 3, t: "Quel passeur talentueux et charismatique dirige Aoba Johsai ?", a: "Oikawa", x: ["Kuroo", "Bokuto", "Ushijima"], acc: ["oikawa", "toru oikawa"] },
  { id: "haik-d4", d: 3, t: "Quel as, meilleur ami d'Oikawa, le calme sur le terrain ?", a: "Iwaizumi", x: ["Kunimi", "Kindaichi", "Kyotani"], acc: ["iwaizumi"] },
  { id: "haik-d5", d: 3, t: "Quel passeur discret, accro aux jeux vidéo, mène l'équipe de Nekoma ?", a: "Kenma", x: ["Kuroo", "Lev", "Yaku"], acc: ["kenma", "kozume kenma"] },
  { id: "haik-d6", d: 3, t: "Quel capitaine rusé, excellent contreur, dirige Nekoma aux côtés de Kenma ?", a: "Kuroo", x: ["Bokuto", "Oikawa", "Ushijima"], acc: ["kuroo", "tetsuro kuroo"] },
  { id: "haik-d7", d: 3, t: "Comment surnomme-t-on la rivalité amicale entre Karasuno et Nekoma ?", a: "La bataille de la décharge", x: ["Le duel des rois", "La guerre des ailes", "Le choc des titans"], acc: ["bataille de la decharge", "décharge", "trash heap"] },
  { id: "haik-d8", d: 3, t: "Quel as exubérant de Fukurodani, dans le top 5 du pays, adore Hinata ?", a: "Bokuto", x: ["Akaashi", "Kuroo", "Ushijima"], acc: ["bokuto", "kotaro bokuto"] },
  { id: "haik-d9", d: 3, t: "Quel passeur posé canalise l'énergie de Bokuto à Fukurodani ?", a: "Akaashi", x: ["Kenma", "Sugawara", "Oikawa"], acc: ["akaashi"] },
  { id: "haik-d10", d: 3, t: "Quel as gaucher surpuissant est la star de Shiratorizawa ?", a: "Ushijima", x: ["Oikawa", "Bokuto", "Kageyama"], acc: ["ushijima", "wakatoshi ushijima"] },
  { id: "haik-d11", d: 3, t: "Quel remplaçant de Karasuno se spécialise dans un service flottant sauté ?", a: "Yamaguchi", x: ["Tsukishima", "Tanaka", "Asahi"], acc: ["yamaguchi", "tadashi yamaguchi"] },
  { id: "haik-d12", d: 3, t: "Quel passeur bienveillant, vice-capitaine, cède peu à peu sa place à Kageyama ?", a: "Sugawara", x: ["Daichi", "Asahi", "Ennoshita"], acc: ["sugawara", "suga"] },
  { id: "haik-d13", d: 3, t: "Quel joueur au crâne rasé, débordant d'énergie, est un attaquant de Karasuno ?", a: "Tanaka", x: ["Nishinoya", "Tsukishima", "Kageyama"], acc: ["tanaka", "ryunosuke tanaka"] },
  { id: "haik-d14", d: 3, t: "Quels jumeaux, l'un passeur l'autre attaquant, brillent à Inarizaki ?", a: "Les jumeaux Miya", x: ["Les frères Kuroo", "Les frères Bokuto", "Les frères Ukai"], acc: ["jumeaux miya", "miya", "atsumu et osamu"] },
  { id: "haik-d15", d: 3, t: "Quel est le rôle principal d'un passeur au volley ?", a: "Faire la passe pour l'attaquant", x: ["Recevoir le service", "Contrer au filet", "Servir uniquement"], acc: ["passe", "faire la passe"] },
  // --- Pro (20) ---
  { id: "haik-p1", d: 4, t: "Quel jeune professeur, sans expérience du volley, devient le responsable du club ?", a: "Takeda", x: ["Ukai", "Nekomata", "Washijo"], acc: ["takeda", "ittetsu takeda"] },
  { id: "haik-p2", d: 4, t: "Quelle réputation Karasuno traîne-t-il, en tant qu'ancien grand club en déclin ?", a: "Les corbeaux déchus", x: ["Les rois invaincus", "Les nouveaux venus", "Les éternels seconds"], acc: ["corbeaux dechus", "déchus"] },
  { id: "haik-p3", d: 4, t: "Quel poste Hinata occupe-t-il, servant souvent de leurre ?", a: "Central", x: ["Libéro", "Passeur", "Réceptionneur"], acc: ["central", "middle blocker"] },
  { id: "haik-p4", d: 4, t: "Quel studio a produit l'anime Haikyu ?", a: "Production I.G", x: ["MAPPA", "Ufotable", "Bones"], acc: ["production i.g", "production ig"] },
  { id: "haik-p5", d: 4, t: "Quel lycée surpuissant Karasuno doit-il battre pour accéder aux nationaux ?", a: "Shiratorizawa", x: ["Nekoma", "Fukurodani", "Inarizaki"], acc: ["shiratorizawa"] },
  { id: "haik-p6", d: 4, t: "Par quel service redoutable Oikawa met-il l'adversaire sous pression ?", a: "Un service sauté puissant", x: ["Un service à la cuillère", "Un service flottant faible", "Aucun service"], acc: ["service saute", "service sauté"] },
  { id: "haik-p7", d: 4, t: "De quel collège Kageyama vient-il, où il a gagné son surnom de Roi ?", a: "Kitagawa Daiichi", x: ["Karasuno", "Aoba Johsai", "Shiratorizawa"], acc: ["kitagawa daiichi", "kitagawa"] },
  { id: "haik-p8", d: 4, t: "Combien de joueurs par équipe se trouvent sur le terrain au volley ?", a: "Six", x: ["Cinq", "Sept", "Onze"], acc: ["6", "six"] },
  { id: "haik-p9", d: 4, t: "Quel film de 2024 met en scène le match Karasuno contre Nekoma ?", a: "La Bataille de la décharge", x: ["Le Duel des As", "Le Roi du terrain", "La Dernière Passe"], acc: ["bataille de la decharge", "dumpster battle"] },
  { id: "haik-p10", d: 4, t: "Lequel des jumeaux Miya est un passeur au service redoutable ?", a: "Atsumu", x: ["Osamu", "Kuroo", "Kenma"], acc: ["atsumu"] },
  { id: "haik-p11", d: 4, t: "Que préfère finalement faire Osamu Miya plutôt que le volley professionnel ?", a: "Ouvrir un restaurant", x: ["Devenir médecin", "Entraîner", "Voyager"], acc: ["ouvrir un restaurant", "cuisine", "onigiri"] },
  { id: "haik-p12", d: 4, t: "Quelle carrière Kenma embrasse-t-il après le lycée ?", a: "Créateur de jeux et streamer", x: ["Chirurgien", "Professeur", "Pompier"], acc: ["streamer", "createur de jeux", "gaming"] },
  { id: "haik-p13", d: 4, t: "Dans quel pays Hinata part-il s'entraîner au beach-volley après le lycée ?", a: "Le Brésil", x: ["Les États-Unis", "L'Italie", "La Chine"], acc: ["bresil", "brésil"] },
  { id: "haik-p14", d: 4, t: "Quel contreur au « flair » déroutant seconde Ushijima à Shiratorizawa ?", a: "Tendo", x: ["Iwaizumi", "Yaku", "Akaashi"], acc: ["tendo"] },
  { id: "haik-p15", d: 4, t: "Quelle règle s'applique au libéro, reconnaissable à son maillot différent ?", a: "Il ne peut pas attaquer au filet", x: ["Il sert à chaque point", "Il joue seul", "Il ne défend jamais"], acc: ["ne peut pas attaquer", "pas d'attaque"] },
  { id: "haik-p16", d: 4, t: "Dans quel club professionnel Hinata joue-t-il, aux côtés de Bokuto et Atsumu ?", a: "Les MSBY Black Jackals", x: ["Les Schweiden Adlers", "Karasuno", "Nekoma"], acc: ["msby", "black jackals", "msby black jackals"] },
  { id: "haik-p17", d: 4, t: "Dans quel club professionnel Kageyama évolue-t-il, avec Ushijima ?", a: "Les Schweiden Adlers", x: ["Les MSBY Black Jackals", "Nekoma", "Fukurodani"], acc: ["schweiden adlers", "adlers"] },
  { id: "haik-p18", d: 4, t: "Quel joueur de deuxième année, posé, deviendra le prochain capitaine de Karasuno ?", a: "Ennoshita", x: ["Tanaka", "Kinoshita", "Narita"], acc: ["ennoshita"] },
  { id: "haik-p19", d: 4, t: "Quelle image l'équipe de Nekoma emploie-t-elle pour décrire son jeu de passes lié ?", a: "Le sang dans les veines", x: ["La meute de loups", "Le mur de fer", "La tempête"], acc: ["sang dans les veines", "connect"] },
  { id: "haik-p20", d: 4, t: "À combien de points, en général, se termine un set gagné au volley ?", a: "25 points", x: ["15 points", "21 points", "30 points"], acc: ["25", "25 points"] },
]);
