import { universe } from "../_build";

export const jujutsukaisen = universe("manga", "Jujutsu Kaisen", [
  // --- Faciles (5) ---
  { id: "jjk-f1", d: 1, t: "Quel adolescent avale un doigt maudit et devient le réceptacle de Sukuna ?", a: "Yuji Itadori", x: ["Megumi Fushiguro", "Satoru Gojo", "Aoi Todo"] },
  { id: "jjk-f2", d: 1, t: "Comment appelle-t-on l'énergie utilisée par les sorciers dans Jujutsu Kaisen ?", a: "L'énergie maudite", x: ["Le chakra", "Le haki", "Le nen"] },
  { id: "jjk-f3", d: 1, t: "Quel professeur, le plus puissant des sorciers, porte un bandeau sur les yeux ?", a: "Satoru Gojo", x: ["Kento Nanami", "Suguru Geto", "Masamichi Yaga"] },
  { id: "jjk-f4", d: 1, t: "Comment se nomme le roi des fléaux dont Yuji devient le réceptacle ?", a: "Sukuna", x: ["Mahito", "Jogo", "Kenjaku"] },
  { id: "jjk-f5", d: 1, t: "De quoi naissent les fléaux dans Jujutsu Kaisen ?", a: "Des émotions négatives des humains", x: ["De la magie noire", "Des météorites", "Des expériences ratées"] },
  // --- Moyennes (10) ---
  { id: "jjk-m1", d: 2, t: "Qui a créé le manga Jujutsu Kaisen ?", a: "Gege Akutami", x: ["Tite Kubo", "Masashi Kishimoto", "Koyoharu Gotouge"] },
  { id: "jjk-m2", d: 2, t: "Quelle technique de Megumi invoque des shikigami comme les chiens divins ?", a: "La technique des Dix Ombres", x: ["Le Limitless", "La parole maudite", "La poupée de paille"] },
  { id: "jjk-m3", d: 2, t: "Quelle arme Nobara utilise-t-elle avec des clous ?", a: "Un marteau", x: ["Un katana", "Un arc", "Une lance"] },
  { id: "jjk-m4", d: 2, t: "Combien de doigts de Sukuna existent au total ?", a: "20", x: ["10", "15", "9"] },
  { id: "jjk-m5", d: 2, t: "Quel type d'établissement Yuji fréquente-t-il à Tokyo ?", a: "Un lycée d'exorcisme", x: ["Une académie de héros", "Une école de ninjas", "Un institut de pirates"] },
  { id: "jjk-m6", d: 2, t: "Quel ancien sorcier manipule les fléaux et veut éliminer les non-sorciers ?", a: "Suguru Geto", x: ["Kento Nanami", "Aoi Todo", "Choso"] },
  { id: "jjk-m7", d: 2, t: "Quel ancien salarié combat selon un principe de ratio 7:3 ?", a: "Kento Nanami", x: ["Satoru Gojo", "Aoi Todo", "Megumi Fushiguro"] },
  { id: "jjk-m8", d: 2, t: "Comment appelle-t-on la technique ultime qui déploie un espace clos et infaillible ?", a: "L'extension du domaine", x: ["La transe", "Le mode démon", "Le bankai"] },
  { id: "jjk-m9", d: 2, t: "Quel fléau de niveau spécial remodèle les âmes avec sa « Métamorphose oisive » ?", a: "Mahito", x: ["Jogo", "Hanami", "Dagon"] },
  { id: "jjk-m10", d: 2, t: "Quel studio a produit l'anime Jujutsu Kaisen ?", a: "MAPPA", x: ["Ufotable", "Studio Pierrot", "Bones"] },
  // --- Dures (15) ---
  { id: "jjk-d1", d: 3, t: "Comment s'appelle l'extension du domaine de Gojo ?", a: "Le Vide illimité", x: ["Le Sanctuaire malveillant", "Le Jardin des ombres", "La Perfection incarnée"], acc: ["unlimited void", "muryokusho"] },
  { id: "jjk-d2", d: 3, t: "Comment s'appelle l'extension du domaine de Sukuna ?", a: "Le Sanctuaire malveillant", x: ["Le Vide illimité", "Le Jardin des ombres", "La Perfection incarnée"], acc: ["malevolent shrine"] },
  { id: "jjk-d3", d: 3, t: "Quelle technique innée de Gojo lui permet de manipuler l'infini ?", a: "Le Limitless", x: ["Les Dix Ombres", "La parole maudite", "Le Boogie Woogie"], acc: ["limitless", "infini"] },
  { id: "jjk-d4", d: 3, t: "Quels yeux hérités accompagnent la technique de Gojo ?", a: "Les Six Yeux", x: ["Le Sharingan", "Le Byakugan", "Les Yeux de la Méduse"] },
  { id: "jjk-d5", d: 3, t: "Quelle élève, sans énergie maudite, ne combat qu'avec des armes maudites ?", a: "Maki Zenin", x: ["Nobara Kugisaki", "Rika Orimoto", "Yuki Tsukumo"] },
  { id: "jjk-d6", d: 3, t: "Quel élève ne parle qu'avec des ingrédients d'onigiri à cause de sa parole maudite ?", a: "Toge Inumaki", x: ["Kento Nanami", "Megumi Fushiguro", "Aoi Todo"] },
  { id: "jjk-d7", d: 3, t: "Quelle est la particularité de Panda, élève du lycée de Tokyo ?", a: "C'est un cadavre maudit", x: ["C'est un fléau déguisé", "C'est un robot", "C'est un humain transformé"] },
  { id: "jjk-d8", d: 3, t: "Qui est le héros du film Jujutsu Kaisen 0, hanté par l'esprit de Rika ?", a: "Yuta Okkotsu", x: ["Yuji Itadori", "Megumi Fushiguro", "Aoi Todo"] },
  { id: "jjk-d9", d: 3, t: "Quelle technique d'Aoi Todo échange les positions d'un claquement de mains ?", a: "Le Boogie Woogie", x: ["Le Limitless", "La parole maudite", "La Métamorphose oisive"] },
  { id: "jjk-d10", d: 3, t: "Quel événement, un soir d'Halloween, piège Gojo dans le Plein Vide ?", a: "L'Incident de Shibuya", x: ["Le Jeu d'abattage", "L'échange inter-écoles", "La Nuit noire"] },
  { id: "jjk-d11", d: 3, t: "Quel sorcier millénaire change de corps et porte des coutures sur le front ?", a: "Kenjaku", x: ["Sukuna", "Mahito", "Uraume"] },
  { id: "jjk-d12", d: 3, t: "Quel fléau à tête de volcan manie le feu ?", a: "Jogo", x: ["Hanami", "Dagon", "Mahito"] },
  { id: "jjk-d13", d: 3, t: "Quel fléau à l'apparence végétale attaque le lycée lors de l'échange inter-écoles ?", a: "Hanami", x: ["Jogo", "Dagon", "Mahito"] },
  { id: "jjk-d14", d: 3, t: "Quel frère aîné de Yuji manipule le sang et vient d'une « peinture de mort » ?", a: "Choso", x: ["Kenjaku", "Naoya", "Toji"] },
  { id: "jjk-d15", d: 3, t: "Quelle médecin du lycée de Tokyo soigne grâce à la technique maudite inversée ?", a: "Shoko Ieiri", x: ["Utahime Iori", "Mei Mei", "Maki Zenin"] },
  // --- Pro (20) ---
  { id: "jjk-p1", d: 4, t: "À quel clan appartiennent Megumi et Maki, l'une des trois grandes familles ?", a: "Le clan Zenin", x: ["Le clan Gojo", "Le clan Kamo", "Le clan Uchiha"] },
  { id: "jjk-p2", d: 4, t: "Quel shikigami ultime des Dix Ombres s'adapte à toute technique et n'a jamais été dompté ?", a: "Mahoraga", x: ["Nue", "Le Grand Serpent", "Le Chien divin"] },
  { id: "jjk-p3", d: 4, t: "Comment se nomme l'attaque de découpe à distance de Sukuna ?", a: "Le Démantèlement", x: ["Le Vide violet", "La Résonance", "La parole maudite"], acc: ["dismantle", "démantèlement"] },
  { id: "jjk-p4", d: 4, t: "Quel sortilège combine le bleu et le rouge de Gojo en un tir violet destructeur ?", a: "Le Vide violet", x: ["Le Bleu", "Le Rouge", "Le Sanctuaire malveillant"], acc: ["hollow purple", "violet"] },
  { id: "jjk-p5", d: 4, t: "Quels furent les derniers mots du grand-père de Yuji ?", a: "Aide les autres", x: ["Deviens le plus fort", "Venge-moi", "Fuis toujours"], acc: ["aide les gens", "sauve les autres"] },
  { id: "jjk-p6", d: 4, t: "Quel sorcier borgne, ancien avocat, manie le « Glaive du bourreau » ?", a: "Hiromi Higuruma", x: ["Kento Nanami", "Choso", "Naoya Zenin"] },
  { id: "jjk-p7", d: 4, t: "Quel fidèle serviteur de Sukuna, à la peau pâle, manie la glace ?", a: "Uraume", x: ["Kenjaku", "Yorozu", "Choso"] },
  { id: "jjk-p8", d: 4, t: "Comment s'appelle l'arme maudite en forme de bâton, utilisée par Nanami puis Yuji ?", a: "Le Nuage joueur", x: ["L'Inversion céleste", "Le Katana à âme fendue", "La Corde noire"], acc: ["playful cloud"] },
  { id: "jjk-p9", d: 4, t: "Quelle jeune fille est l'esprit vengeur qui accompagne Yuta dans Jujutsu Kaisen 0 ?", a: "Rika Orimoto", x: ["Nobara Kugisaki", "Maki Zenin", "Yuki Tsukumo"] },
  { id: "jjk-p10", d: 4, t: "Quel « jeu » mortel oppose des sorciers dans des colonies après Shibuya ?", a: "Le Jeu d'abattage", x: ["Le Tournoi de Kyoto", "L'échange inter-écoles", "Le Grand Concours"], acc: ["culling game", "jeu d'abattage"] },
  { id: "jjk-p11", d: 4, t: "Quel est le niveau de dangerosité le plus élevé pour un fléau ou un sorcier ?", a: "Le niveau spécial", x: ["Le niveau 1", "Le niveau S", "Le niveau A"], acc: ["special grade", "niveau spécial"] },
  { id: "jjk-p12", d: 4, t: "Quelle technique de Nobara, en clouant une poupée, blesse l'ennemi à distance ?", a: "La Résonance", x: ["Le Boogie Woogie", "La parole maudite", "Le Démantèlement"], acc: ["resonance", "résonance"] },
  { id: "jjk-p13", d: 4, t: "Dans quel quartier de Tokyo se déroule l'incident d'Halloween ?", a: "Shibuya", x: ["Shinjuku", "Roppongi", "Akihabara"] },
  { id: "jjk-p14", d: 4, t: "Quel autre lycée d'exorcisme, rival, se trouve à l'ouest du Japon ?", a: "Le lycée d'exorcisme de Kyoto", x: ["Le lycée de Nagoya", "Le lycée d'Osaka", "Le lycée de Sapporo"] },
  { id: "jjk-p15", d: 4, t: "Quel fléau de niveau spécial, allié de Mahito, règne sur un domaine aquatique ?", a: "Dagon", x: ["Jogo", "Hanami", "Kenjaku"] },
  { id: "jjk-p16", d: 4, t: "Quel principal du lycée de Tokyo, mentor de Gojo, a créé Panda ?", a: "Masamichi Yaga", x: ["Yoshinobu Gakuganji", "Kiyotaka Ijichi", "Atsuya Kusakabe"] },
  { id: "jjk-p17", d: 4, t: "Quelle technique héréditaire du clan Kamo permet de manipuler le sang ?", a: "La manipulation du sang", x: ["Les Dix Ombres", "Le Limitless", "La parole maudite"], acc: ["blood manipulation"] },
  { id: "jjk-p18", d: 4, t: "Quel katana maudit tranche jusqu'à l'âme de la cible ?", a: "Le Katana à âme fendue", x: ["Le Nuage joueur", "L'Inversion céleste", "La Corde noire"], acc: ["split soul katana"] },
  { id: "jjk-p19", d: 4, t: "Quelle arme maudite annule les techniques innées comme l'Infini de Gojo ?", a: "L'Inversion céleste", x: ["Le Nuage joueur", "Le Katana à âme fendue", "Le Glaive du bourreau"], acc: ["inverted spear of heaven", "lance inversée"] },
  { id: "jjk-p20", d: 4, t: "En quelle année l'anime Jujutsu Kaisen a-t-il été diffusé pour la première fois ?", a: "2020", x: ["2018", "2022", "2016"] },
]);
