import { universe } from "../_build";

export const mha = universe("manga", "My Hero Academia", [
  // --- Faciles (5) ---
  { id: "mha-f1", d: 1, t: "Qui est le héros principal de My Hero Academia ?", a: "Izuku Midoriya", acc: ["midoriya", "deku", "izuku"], x: ["Bakugo", "Todoroki", "All Might"] },
  { id: "mha-f2", d: 1, t: "Quel est le surnom de Midoriya ?", a: "Deku", x: ["Kacchan", "Shoto", "Red Riot"] },
  { id: "mha-f3", d: 1, t: "Quel héros n°1 musclé est le « Symbole de la Paix » ?", a: "All Might", x: ["Endeavor", "Aizawa", "Mirio"] },
  { id: "mha-f4", d: 1, t: "Comment appelle-t-on un super-pouvoir dans MHA ?", a: "Un Alter (Quirk)", acc: ["alter", "quirk"], x: ["Un Nen", "Un Stand", "Un Haki"] },
  { id: "mha-f5", d: 1, t: "Dans quel lycée les héros sont-ils formés ?", a: "Yuei (U.A.)", acc: ["yuei", "u.a.", "ua"], x: ["Shiketsu", "Hosu", "Seirin"] },

  // --- Moyennes (10) ---
  { id: "mha-m1", d: 2, t: "Quel pouvoir All Might transmet-il à Deku ?", a: "One For All", x: ["All For One", "Explosion", "Half-Cold Half-Hot"] },
  { id: "mha-m2", d: 2, t: "Quel ami d'enfance explosif et colérique rivalise avec Deku ?", a: "Katsuki Bakugo", acc: ["bakugo", "kacchan"], x: ["Todoroki", "Kirishima", "Iida"] },
  { id: "mha-m3", d: 2, t: "Quel est l'Alter de Bakugo ?", a: "L'explosion", acc: ["explosion", "nitroglycerine"], x: ["Le feu et la glace", "La gravité", "L'électricité"] },
  { id: "mha-m4", d: 2, t: "Quel élève au visage mi-rouge mi-blanc est le fils d'Endeavor ?", a: "Shoto Todoroki", acc: ["todoroki", "shoto"], x: ["Bakugo", "Iida", "Kirishima"] },
  { id: "mha-m5", d: 2, t: "Quel est l'Alter de Todoroki ?", a: "Mi-glace mi-feu", acc: ["glace et feu", "half cold half hot", "mi-glace mi-feu"], x: ["L'explosion", "One For All", "La gravité"] },
  { id: "mha-m6", d: 2, t: "Quel professeur de la classe 1-A peut annuler les Alters du regard ?", a: "Shota Aizawa (Eraserhead)", acc: ["aizawa", "eraserhead"], x: ["All Might", "Present Mic", "Endeavor"] },
  { id: "mha-m7", d: 2, t: "Quelle élève aux joues roses peut annuler la gravité des objets ?", a: "Ochaco Uraraka", acc: ["uraraka", "ochaco"], x: ["Tsuyu", "Momo", "Jiro"] },
  { id: "mha-m8", d: 2, t: "Quel est le grand méchant principal, disciple d'All For One ?", a: "Tomura Shigaraki", acc: ["shigaraki", "tomura"], x: ["Dabi", "Stain", "Toga"] },
  { id: "mha-m9", d: 2, t: "Comment s'appelle l'organisation des méchants ?", a: "La Ligue des Vilains", acc: ["ligue des vilains", "league of villains"], x: ["L'Akatsuki", "Les Méta-Libérateurs", "Yotsuba"] },
  { id: "mha-m10", d: 2, t: "Quel délégué sérieux à lunettes a des moteurs dans les jambes ?", a: "Tenya Iida", acc: ["iida", "tenya"], x: ["Kirishima", "Sero", "Kaminari"] },

  // --- Dures (15) ---
  { id: "mha-d1", d: 3, t: "Quel ennemi juré d'All Might peut voler les Alters des autres ?", a: "All For One", x: ["Shigaraki", "Stain", "Dabi"] },
  { id: "mha-d2", d: 3, t: "Quel est l'Alter de Shigaraki ?", a: "La désintégration (Decay)", acc: ["desintegration", "decay"], x: ["L'explosion", "Le feu", "Le givre"] },
  { id: "mha-d3", d: 3, t: "Quelle vilaine peut prendre l'apparence des gens grâce à leur sang ?", a: "Himiko Toga", acc: ["toga", "himiko"], x: ["Mt Lady", "Mina", "Jiro"] },
  { id: "mha-d4", d: 3, t: "Quel vilain aux flammes bleues cache l'identité de Touya ?", a: "Dabi", x: ["Stain", "Spinner", "Twice"] },
  { id: "mha-d5", d: 3, t: "Quel « Hero Killer » idéaliste paralyse ses victimes en goûtant leur sang ?", a: "Stain", x: ["Dabi", "Muscular", "Overhaul"] },
  { id: "mha-d6", d: 3, t: "Quel héros de feu, père de Todoroki, devient n°1 après All Might ?", a: "Endeavor", x: ["Hawks", "Best Jeanist", "Mirko"] },
  { id: "mha-d7", d: 3, t: "Quel héros n°2, aux ailes faites de plumes-armes, est très rapide ?", a: "Hawks", x: ["Endeavor", "Mirko", "Best Jeanist"] },
  { id: "mha-d8", d: 3, t: "Quelle élève de la 1-A est une fille-grenouille (Froppy) ?", a: "Tsuyu Asui", acc: ["tsuyu", "froppy", "asui"], x: ["Uraraka", "Mina", "Momo"] },
  { id: "mha-d9", d: 3, t: "Quel élève peut durcir son corps comme la roche (Red Riot) ?", a: "Eijiro Kirishima", acc: ["kirishima", "red riot"], x: ["Kaminari", "Sero", "Tetsutetsu"] },
  { id: "mha-d10", d: 3, t: "Quelle élève peut créer n'importe quel objet depuis son corps ?", a: "Momo Yaoyorozu", acc: ["momo", "yaoyorozu"], x: ["Jiro", "Mina", "Tsuyu"] },
  { id: "mha-d11", d: 3, t: "Les « Big Three » de Yuei sont Mirio, Nejire et… ?", a: "Tamaki Amajiki", acc: ["tamaki", "amajiki"], x: ["Aoyama", "Shinso", "Togata"] },
  { id: "mha-d12", d: 3, t: "Quel Alter permet à Mirio Togata de traverser la matière ?", a: "La perméation (Permeation)", acc: ["permeation", "permeabilite"], x: ["Manifest", "Big Hand", "Wave Motion"] },
  { id: "mha-d13", d: 3, t: "Quel vilain instable peut se cloner à l'infini ?", a: "Twice", x: ["Spinner", "Mr Compress", "Magne"] },
  { id: "mha-d14", d: 3, t: "Quelle petite fille aux cheveux blancs Overhaul exploite-t-il pour ses balles anti-Alter ?", a: "Eri", x: ["Kota", "Mei", "Nejire"] },
  { id: "mha-d15", d: 3, t: "Quel chef yakuza peut désassembler et réassembler la matière ?", a: "Overhaul (Kai Chisaki)", acc: ["overhaul", "chisaki"], x: ["Stain", "Muscular", "Gentle"] },

  // --- Pro (20) ---
  { id: "mha-p1", d: 4, t: "Combien de détenteurs One For All ont précédé Deku ?", a: "8 (Deku est le 9e)", acc: ["8", "huit"], x: ["5", "6", "10"] },
  { id: "mha-p2", d: 4, t: "Qui fut le tout premier détenteur de One For All, frère d'All For One ?", a: "Yoichi Shigaraki", acc: ["yoichi"], x: ["Nana Shimura", "Daigoro Banjo", "En"] },
  { id: "mha-p3", d: 4, t: "Quelle 7e détentrice de One For All fut le mentor d'All Might ?", a: "Nana Shimura", acc: ["nana shimura", "nana"], x: ["Gran Torino", "Recovery Girl", "Midnight"] },
  { id: "mha-p4", d: 4, t: "Quel est le véritable nom d'All Might ?", a: "Toshinori Yagi", acc: ["toshinori yagi", "toshinori"], x: ["Sorahiko Torino", "Shota Aizawa", "Keigo Takami"] },
  { id: "mha-p5", d: 4, t: "Quel petit héros vétéran aux bottes à réaction a entraîné All Might puis Deku ?", a: "Gran Torino", acc: ["gran torino"], x: ["Aizawa", "Present Mic", "Endeavor"] },
  { id: "mha-p6", d: 4, t: "Quel est le véritable nom de Hawks ?", a: "Keigo Takami", acc: ["keigo takami", "keigo"], x: ["Toshinori Yagi", "Touya Todoroki", "Tenko"] },
  { id: "mha-p7", d: 4, t: "Quel est le véritable nom de naissance de Shigaraki ?", a: "Tenko Shimura", acc: ["tenko shimura", "tenko"], x: ["Keigo Takami", "Touya", "Yoichi"] },
  { id: "mha-p8", d: 4, t: "Quel est l'Alter de Hawks ?", a: "Des ailes aux plumes acérées", acc: ["ailes", "plumes", "fierce wings"], x: ["La désintégration", "L'explosion", "Mi-glace mi-feu"] },
  { id: "mha-p9", d: 4, t: "De quel ancien détenteur de OFA Deku hérite-t-il l'Alter « Fouet Noir » ?", a: "Daigoro Banjo", acc: ["banjo", "daigoro banjo"], x: ["Yoichi", "Nana", "En"] },
  { id: "mha-p10", d: 4, t: "Quel Alter de flottaison Deku hérite-t-il de Nana Shimura via OFA ?", a: "Float (Flottaison)", acc: ["float", "flottaison"], x: ["Blackwhip", "Danger Sense", "Fa Jin"] },
  { id: "mha-p11", d: 4, t: "Comment s'appelle l'Alter « fouet noir » que Deku manifeste ?", a: "Blackwhip", acc: ["blackwhip", "fouet noir"], x: ["Float", "Smokescreen", "Fa Jin"] },
  { id: "mha-p12", d: 4, t: "Quel est l'objectif de Shigaraki et All For One concernant Deku ?", a: "S'emparer de One For All", acc: ["one for all", "voler one for all"], x: ["Simplement le tuer", "Le recruter", "L'enfermer"] },
  { id: "mha-p13", d: 4, t: "Comment s'appelle le grand tournoi où s'affrontent les élèves de Yuei ?", a: "Le Festival du sport", acc: ["festival du sport", "sports festival"], x: ["L'examen de licence", "Le camp d'été", "Le Provisional"] },
  { id: "mha-p14", d: 4, t: "Quel vilain géant et surpuissant tue les parents de Kota dans la forêt ?", a: "Muscular", x: ["Moonfish", "Magne", "Mustard"] },
  { id: "mha-p15", d: 4, t: "Quelle vaste organisation fusionne la Ligue des Vilains et les Méta-Libérateurs ?", a: "Le Front de Libération du Paranormal", acc: ["front de liberation du paranormal", "paranormal liberation front"], x: ["La Ligue des Vilains", "Les Huit Préceptes", "Yotsuba"] },
  { id: "mha-p16", d: 4, t: "Quel groupe yakuza (les Huit Préceptes de la Mort) Overhaul dirige-t-il ?", a: "Les Huit Préceptes de la Mort (Shie Hassaikai)", acc: ["huit preceptes", "shie hassaikai"], x: ["La Ligue des Vilains", "Le Front Paranormal", "La Triade"] },
  { id: "mha-p17", d: 4, t: "Quel est le véritable nom de Dabi, fils aîné d'Endeavor ?", a: "Touya Todoroki", acc: ["touya", "touya todoroki"], x: ["Natsuo", "Shoto", "Tenko"] },
  { id: "mha-p18", d: 4, t: "Quel est l'Alter d'Endeavor ?", a: "Hellflame (Flammes infernales)", acc: ["hellflame", "flammes infernales", "flammes"], x: ["Mi-glace mi-feu", "La perméation", "L'explosion"] },
  { id: "mha-p19", d: 4, t: "Quel élève au pouvoir de « lavage de cerveau » par la voix rejoint la 1-A plus tard ?", a: "Hitoshi Shinso", acc: ["shinso", "hitoshi shinso"], x: ["Aoyama", "Mineta", "Ojiro"] },
  { id: "mha-p20", d: 4, t: "Quel élève de la 1-A se révèle être l'espion d'All For One ?", a: "Yuga Aoyama", acc: ["aoyama", "yuga aoyama"], x: ["Mineta", "Kaminari", "Shinso"] },
]);
