import { universe } from "../_build";

export const nana = universe("manga", "Nana", [
  // --- Faciles (5) ---
  { id: "nana-f1", d: 1, t: "Combien d'héroïnes principales prénommées Nana l'histoire suit-elle ?", a: "Deux", x: ["Une", "Trois", "Quatre"], acc: ["2", "deux"] },
  { id: "nana-f2", d: 1, t: "Dans quelle ville les deux Nana partent-elles vivre ?", a: "Tokyo", x: ["Osaka", "Kyoto", "Yokohama"] },
  { id: "nana-f3", d: 1, t: "Quel style de musique chante Nana Osaki ?", a: "Le punk rock", x: ["La pop", "Le jazz", "Le classique"] },
  { id: "nana-f4", d: 1, t: "Comment les deux Nana se rencontrent-elles ?", a: "Dans un train", x: ["À l'école", "Au travail", "À un concert"] },
  { id: "nana-f5", d: 1, t: "Quel surnom Nana Osaki donne-t-elle à Nana Komatsu ?", a: "Hachi", x: ["Chibi", "Michiko", "Nana K"], acc: ["hachi"] },
  // --- Moyennes (10) ---
  { id: "nana-m1", d: 2, t: "Qui est l'autrice du manga Nana ?", a: "Ai Yazawa", x: ["Naoko Takeuchi", "Rumiko Takahashi", "Kaoru Mori"] },
  { id: "nana-m2", d: 2, t: "Comment s'appelle le groupe de Nana Osaki ?", a: "Black Stones", x: ["Trapnest", "Sex Pistols", "Guilty Kiss"], acc: ["black stones", "blast"] },
  { id: "nana-m3", d: 2, t: "Comment s'appelle le célèbre groupe rival ?", a: "Trapnest", x: ["Black Stones", "Beck", "Bakuten"] },
  { id: "nana-m4", d: 2, t: "Qui est le petit ami guitariste de Nana Osaki ?", a: "Ren", x: ["Takumi", "Nobu", "Yasu"] },
  { id: "nana-m5", d: 2, t: "Quel numéro porte l'appartement que partagent les deux Nana ?", a: "707", x: ["101", "404", "202"] },
  { id: "nana-m6", d: 2, t: "Quel groupe Ren rejoint-il après avoir quitté Black Stones ?", a: "Trapnest", x: ["Sex Pistols", "Beck", "Bakuten"] },
  { id: "nana-m7", d: 2, t: "Quel groupe punk britannique Nana Osaki admire-t-elle ?", a: "Les Sex Pistols", x: ["Les Ramones", "Les Clash", "Nirvana"] },
  { id: "nana-m8", d: 2, t: "Comment décrit-on le tempérament de Nana Komatsu, alias Hachi ?", a: "Naïve et sentimentale", x: ["Froide et distante", "Violente", "Cynique"] },
  { id: "nana-m9", d: 2, t: "Quel bassiste manipulateur de Trapnest épouse Hachi ?", a: "Takumi", x: ["Ren", "Nobu", "Shin"] },
  { id: "nana-m10", d: 2, t: "Combien d'épisodes compte l'anime Nana ?", a: "47", x: ["12", "24", "100"] },
  // --- Dures (15) ---
  { id: "nana-d1", d: 3, t: "Quel est le nom de famille de Nana la chanteuse punk ?", a: "Osaki", x: ["Komatsu", "Ichinose", "Honjo"] },
  { id: "nana-d2", d: 3, t: "Quel est le nom de famille de Nana surnommée Hachi ?", a: "Komatsu", x: ["Osaki", "Ichinose", "Serizawa"] },
  { id: "nana-d3", d: 3, t: "De quel instrument joue Ren dans les groupes ?", a: "La guitare", x: ["La basse", "La batterie", "Le clavier"] },
  { id: "nana-d4", d: 3, t: "Qui est le leader et batteur de Black Stones, avocat et chauve ?", a: "Yasu", x: ["Nobu", "Shin", "Takumi"] },
  { id: "nana-d5", d: 3, t: "Quel guitariste roux de Black Stones tombe amoureux de Hachi ?", a: "Nobu", x: ["Yasu", "Shin", "Ren"] },
  { id: "nana-d6", d: 3, t: "Qui est le plus jeune membre de Black Stones, le bassiste ?", a: "Shin", x: ["Nobu", "Yasu", "Ren"] },
  { id: "nana-d7", d: 3, t: "Comment s'appelle la chanteuse de Trapnest ?", a: "Reira", x: ["Junko", "Sachiko", "Misato"], acc: ["reira", "layla"] },
  { id: "nana-d8", d: 3, t: "Quel est le nom de famille de Ren, le guitariste ?", a: "Honjo", x: ["Ichinose", "Osaki", "Terashima"] },
  { id: "nana-d9", d: 3, t: "Quel est le nom de famille de Takumi, bassiste de Trapnest ?", a: "Ichinose", x: ["Honjo", "Osaki", "Komatsu"] },
  { id: "nana-d10", d: 3, t: "D'où vient le surnom « Hachi » donné à Nana Komatsu ?", a: "Du chien fidèle Hachiko", x: ["D'un chiffre porte-bonheur", "D'une marque", "D'une chanson"], acc: ["hachiko"] },
  { id: "nana-d11", d: 3, t: "Quel studio a animé la série Nana ?", a: "Madhouse", x: ["Bones", "Kyoto Animation", "Sunrise"] },
  { id: "nana-d12", d: 3, t: "Quel autre manga d'Ai Yazawa parle de mode et de haute couture ?", a: "Paradise Kiss", x: ["Fruits Basket", "Honey and Clover", "Skip Beat"] },
  { id: "nana-d13", d: 3, t: "Quel premier petit ami de Hachi la trompe au début de l'histoire ?", a: "Shoji", x: ["Takumi", "Ren", "Nobu"] },
  { id: "nana-d14", d: 3, t: "Quelle créatrice de mode punk Nana Osaki adore-t-elle porter ?", a: "Vivienne Westwood", x: ["Coco Chanel", "Rei Kawakubo", "Stella McCartney"] },
  { id: "nana-d15", d: 3, t: "Dans quel magazine de prépublication Nana a-t-il paru ?", a: "Cookie", x: ["Shonen Jump", "Ribon", "Nakayoshi"] },
  // --- Pro (20) ---
  { id: "nana-p1", d: 4, t: "En quelle année le manga Nana a-t-il commencé ?", a: "2000", x: ["1995", "2005", "2010"] },
  { id: "nana-p2", d: 4, t: "Depuis quelle année le manga est-il en pause à cause de la maladie de l'autrice ?", a: "2009", x: ["2003", "2015", "2020"] },
  { id: "nana-p3", d: 4, t: "Quel est le vrai nom complet du leader de Black Stones, « Yasu » ?", a: "Yasushi Takagi", x: ["Nobuo Terashima", "Shinichi Okazaki", "Ren Honjo"] },
  { id: "nana-p4", d: 4, t: "Quel est le nom complet de « Nobu » de Black Stones ?", a: "Nobuo Terashima", x: ["Yasushi Takagi", "Shinichi Okazaki", "Takumi Ichinose"] },
  { id: "nana-p5", d: 4, t: "Quel est le vrai nom du jeune bassiste « Shin » ?", a: "Shinichi Okazaki", x: ["Nobuo Terashima", "Yasushi Takagi", "Ren Honjo"] },
  { id: "nana-p6", d: 4, t: "De quelle origine à moitié étrangère est le personnage de Shin ?", a: "À moitié suédois", x: ["À moitié américain", "À moitié français", "À moitié coréen"] },
  { id: "nana-p7", d: 4, t: "Comment s'appelle la fille de Hachi et Takumi ?", a: "Satsuki", x: ["Ren", "Nana", "Miu"], acc: ["satsuki"] },
  { id: "nana-p8", d: 4, t: "De quel membre de Trapnest Reira est-elle une amie d'enfance ?", a: "Takumi", x: ["Ren", "Naoki", "Shin"] },
  { id: "nana-p9", d: 4, t: "Quel est le batteur de Trapnest ?", a: "Naoki", x: ["Yasu", "Shin", "Nobu"] },
  { id: "nana-p10", d: 4, t: "Quelle amie de longue date de Hachi vit aussi à Tokyo et la soutient ?", a: "Junko", x: ["Reira", "Sachiko", "Misato"] },
  { id: "nana-p11", d: 4, t: "Quel fruit revient comme motif décoratif autour de Nana Osaki ?", a: "La fraise", x: ["La cerise", "La pomme", "La pêche"] },
  { id: "nana-p12", d: 4, t: "À quel lectorat est destiné le manga Nana ?", a: "Aux jeunes femmes", x: ["Aux jeunes garçons", "Aux enfants", "Aux hommes adultes"], acc: ["josei"] },
  { id: "nana-p13", d: 4, t: "Combien de membres compte le groupe Black Stones ?", a: "4", x: ["3", "5", "6"], acc: ["quatre"] },
  { id: "nana-p14", d: 4, t: "Combien de membres compte le groupe Trapnest ?", a: "4", x: ["3", "5", "6"], acc: ["quatre"] },
  { id: "nana-p15", d: 4, t: "Quel âge ont les deux Nana lorsqu'elles se rencontrent dans le train ?", a: "20 ans", x: ["16 ans", "18 ans", "25 ans"], acc: ["20"] },
  { id: "nana-p16", d: 4, t: "Quel personnage raconte souvent l'histoire en repensant au passé ?", a: "Hachi", x: ["Yasu", "Ren", "Takumi"] },
  { id: "nana-p17", d: 4, t: "Quel membre de Black Stones se prostitue auprès de femmes plus âgées pour de l'argent ?", a: "Shin", x: ["Nobu", "Yasu", "Takumi"] },
  { id: "nana-p18", d: 4, t: "Quelle chanteuse réelle prête sa voix chantée à Nana Osaki dans l'anime ?", a: "Anna Tsuchiya", x: ["Mika Nakashima", "Olivia Lufkin", "Yui"] },
  { id: "nana-p19", d: 4, t: "Quelle chanteuse réelle prête sa voix chantée à Reira dans l'anime ?", a: "Olivia Lufkin", x: ["Anna Tsuchiya", "Mika Nakashima", "Yui"] },
  { id: "nana-p20", d: 4, t: "Quelle chanteuse a incarné et chanté Nana Osaki dans le film en prises de vues réelles ?", a: "Mika Nakashima", x: ["Aoi Miyazaki", "Anna Tsuchiya", "Yui"] },
]);
