import { universe } from "../_build";

export const naruto = universe("manga", "Naruto", [
  // --- Faciles (5) ---
  { id: "naruto-f1", d: 1, t: "Comment s'appelle le héros de Naruto ?", a: "Naruto Uzumaki", x: ["Sasuke Uchiha", "Sakura Haruno", "Kakashi Hatake"] },
  { id: "naruto-f2", d: 1, t: "Quel est le rêve de Naruto ?", a: "Devenir Hokage", x: ["Devenir Kazekage", "Diriger l'Akatsuki", "Devenir Roi des Pirates"] },
  { id: "naruto-f3", d: 1, t: "Quel démon-renard est scellé en Naruto ?", a: "Kurama", acc: ["kurama", "kyubi", "neuf queues"], x: ["Shukaku", "Gyuki", "Son Goku"] },
  { id: "naruto-f4", d: 1, t: "De quelle couleur est la tenue emblématique du jeune Naruto ?", a: "Orange", x: ["Bleue", "Verte", "Rouge"] },
  { id: "naruto-f5", d: 1, t: "Dans quel village vit Naruto ?", a: "Konoha", acc: ["konoha", "feuille"], x: ["Suna", "Kiri", "Iwa"] },

  // --- Moyennes (10) ---
  { id: "naruto-m1", d: 2, t: "Qui est le sensei de l'équipe 7 ?", a: "Kakashi Hatake", acc: ["kakashi"], x: ["Jiraiya", "Asuma", "Maito Gai"] },
  { id: "naruto-m2", d: 2, t: "Quelle est la technique fétiche de Naruto, une boule de chakra tournante ?", a: "Rasengan", x: ["Chidori", "Amaterasu", "Katon"] },
  { id: "naruto-m3", d: 2, t: "Quelle technique d'éclair est la signature de Sasuke ?", a: "Chidori", x: ["Rasengan", "Susanoo", "Kamui"] },
  { id: "naruto-m4", d: 2, t: "De quel clan Sasuke est-il issu ?", a: "Uchiha", x: ["Hyuga", "Senju", "Uzumaki"] },
  { id: "naruto-m5", d: 2, t: "Lequel des trois Sannin, ermite des crapauds, entraîne Naruto ?", a: "Jiraiya", x: ["Orochimaru", "Tsunade", "Hiruzen"] },
  { id: "naruto-m6", d: 2, t: "Qui devient le 5e Hokage ?", a: "Tsunade", x: ["Hiruzen", "Minato", "Danzo"] },
  { id: "naruto-m7", d: 2, t: "Quel dojutsu possède le clan Hyuga ?", a: "Byakugan", x: ["Sharingan", "Rinnegan", "Tenseigan"] },
  { id: "naruto-m8", d: 2, t: "Quelle kunoichi blonde du clan Yamanaka est la rivale de Sakura ?", a: "Ino", x: ["Hinata", "Tenten", "Temari"] },
  { id: "naruto-m9", d: 2, t: "Quels animaux Naruto invoque-t-il ?", a: "Les crapauds", acc: ["crapauds", "grenouilles"], x: ["Les serpents", "Les limaces", "Les chiens"] },
  { id: "naruto-m10", d: 2, t: "Comment se nomme l'organisation aux capes noires à nuages rouges ?", a: "L'Akatsuki", acc: ["akatsuki"], x: ["L'Anbu", "La Racine", "Les Sept Épéistes"] },

  // --- Dures (15) ---
  { id: "naruto-d1", d: 3, t: "Quel est le nom du 4e Hokage, père de Naruto ?", a: "Minato Namikaze", acc: ["minato"], x: ["Hashirama Senju", "Hiruzen Sarutobi", "Tobirama Senju"] },
  { id: "naruto-d2", d: 3, t: "Comment s'appelle la mère de Naruto ?", a: "Kushina Uzumaki", acc: ["kushina"], x: ["Mikoto Uchiha", "Tsunade", "Mei Terumi"] },
  { id: "naruto-d3", d: 3, t: "Quel frère de Sasuke a massacré le clan Uchiha ?", a: "Itachi", x: ["Madara", "Obito", "Shisui"] },
  { id: "naruto-d4", d: 3, t: "Quelle version vent du Rasengan Naruto a-t-il créée ?", a: "Rasenshuriken", x: ["Bijudama", "Odama Rasengan", "Chidori Nagashi"] },
  { id: "naruto-d5", d: 3, t: "Comment se nomme le mode utilisant le chakra naturel des crapauds ?", a: "Le mode Ermite", acc: ["ermite", "sennin", "mode ermite"], x: ["Le mode Kyubi", "Le Susanoo", "Le mode Baryon"] },
  { id: "naruto-d6", d: 3, t: "Quel membre de l'Akatsuki est un marionnettiste empoisonneur ?", a: "Sasori", x: ["Deidara", "Kakuzu", "Hidan"] },
  { id: "naruto-d7", d: 3, t: "Avec quel matériau explosif Deidara crée-t-il son art ?", a: "L'argile", acc: ["argile"], x: ["Le papier", "Le sable", "Le fil"] },
  { id: "naruto-d8", d: 3, t: "Quel membre immortel de l'Akatsuki voue un culte au dieu Jashin ?", a: "Hidan", x: ["Kakuzu", "Kisame", "Zetsu"] },
  { id: "naruto-d9", d: 3, t: "Quel partenaire d'Itachi manie l'épée vivante Samehada ?", a: "Kisame Hoshigaki", acc: ["kisame"], x: ["Zabuza", "Suigetsu", "Mangetsu"] },
  { id: "naruto-d10", d: 3, t: "Comment s'appelle l'immense sabre de Zabuza ?", a: "Kubikiribocho", acc: ["kubikiribocho", "decapiteuse"], x: ["Samehada", "Kusanagi", "Nuibari"] },
  { id: "naruto-d11", d: 3, t: "Comment se nomme le fils de Naruto ?", a: "Boruto", x: ["Himawari", "Konohamaru", "Shikadai"] },
  { id: "naruto-d12", d: 3, t: "Quelle est la fille de Sasuke et Sakura ?", a: "Sarada Uchiha", acc: ["sarada"], x: ["Himawari", "Karin", "Mitsuki"] },
  { id: "naruto-d13", d: 3, t: "Quel Sannin au thème serpent expérimente sur les humains ?", a: "Orochimaru", x: ["Jiraiya", "Kabuto", "Danzo"] },
  { id: "naruto-d14", d: 3, t: "Quel assistant à lunettes sert d'espion à Orochimaru ?", a: "Kabuto", x: ["Yamato", "Sai", "Kimimaro"] },
  { id: "naruto-d15", d: 3, t: "Quel village est dirigé par le Kazekage Gaara ?", a: "Suna", acc: ["suna", "sable"], x: ["Kiri", "Kumo", "Iwa"] },

  // --- Pro (20) ---
  { id: "naruto-p1", d: 4, t: "Quelle technique interdite permet de réanimer les morts au combat ?", a: "L'Edo Tensei", acc: ["edo tensei", "reincarnation des ames impures"], x: ["Le Kuchiyose", "L'Izanagi", "Le Shiki Fujin"] },
  { id: "naruto-p2", d: 4, t: "Quel sceau de Minato emprisonne une âme dans le ventre du Dieu de la Mort ?", a: "Le Shiki Fujin", acc: ["shiki fujin", "sceau du demon de la mort"], x: ["Le Hakke Fuin", "L'Edo Tensei", "Le Mugen Tsukuyomi"] },
  { id: "naruto-p3", d: 4, t: "Quelle est la véritable identité de « Tobi », le chef masqué ?", a: "Obito Uchiha", acc: ["obito"], x: ["Madara Uchiha", "Izuna Uchiha", "Kagami Uchiha"] },
  { id: "naruto-p4", d: 4, t: "Quel dojutsu ultime aux anneaux concentriques possède Pain/Nagato ?", a: "Le Rinnegan", x: ["Le Byakugan", "Le Tenseigan", "Le Mangekyo Sharingan"] },
  { id: "naruto-p5", d: 4, t: "Comment se nomme le plan d'illusion mondiale d'Obito et Madara ?", a: "Le Mugen Tsukuyomi", acc: ["mugen tsukuyomi", "tsukuyomi infini"], x: ["L'Izanami", "Le Kotoamatsukami", "Le Kamui"] },
  { id: "naruto-p6", d: 4, t: "Quelle ancêtre est à l'origine du chakra sur Terre ?", a: "Kaguya Otsutsuki", acc: ["kaguya"], x: ["Hagoromo Otsutsuki", "Hamura Otsutsuki", "Mito Uzumaki"] },
  { id: "naruto-p7", d: 4, t: "Quel est le surnom d'Hagoromo Otsutsuki ?", a: "L'Ermite des Six Chemins", acc: ["ermite des six chemins", "rikudo sennin"], x: ["Le Sage des crapauds", "Le Dieu Shinobi", "Le Premier Hokage"] },
  { id: "naruto-p8", d: 4, t: "Quel kekkei genkai de glace Haku utilise-t-il ?", a: "Le Hyoton", acc: ["hyoton", "glace"], x: ["Le Yoton", "Le Mokuton", "Le Futton"] },
  { id: "naruto-p9", d: 4, t: "Quel kekkei genkai le Premier Hokage Hashirama maîtrise-t-il ?", a: "Le Mokuton", acc: ["mokuton", "bois"], x: ["Le Hyoton", "Le Yoton", "Le Jinton"] },
  { id: "naruto-p10", d: 4, t: "Quel genjutsu d'hypnotisme suprême est l'œil de Shisui ?", a: "Le Kotoamatsukami", acc: ["kotoamatsukami"], x: ["Le Tsukuyomi", "L'Izanami", "Le Kamui"] },
  { id: "naruto-p11", d: 4, t: "Quel pouvoir spatio-temporel partagent Kakashi et Obito ?", a: "Le Kamui", acc: ["kamui"], x: ["L'Amaterasu", "Le Susanoo", "Le Tsukuyomi"] },
  { id: "naruto-p12", d: 4, t: "Comment se nomme le démon à huit queues ?", a: "Gyuki", x: ["Kurama", "Shukaku", "Son Goku"] },
  { id: "naruto-p13", d: 4, t: "Qui est le jinchuriki rappeur du Hachibi à Kumo ?", a: "Killer Bee", acc: ["killer bee", "killer b"], x: ["A", "Darui", "Omoi"] },
  { id: "naruto-p14", d: 4, t: "Quelle technique vaut à Minato le surnom d'« Éclair Jaune de Konoha » ?", a: "Le Hiraishin", acc: ["hiraishin", "dieu du tonnerre volant"], x: ["Le Rasengan", "Le Kage Bunshin", "Le Shunshin"] },
  { id: "naruto-p15", d: 4, t: "À quel clan appartiennent Neji et Hinata ?", a: "Hyuga", x: ["Uchiha", "Aburame", "Inuzuka"] },
  { id: "naruto-p16", d: 4, t: "Quel art martial « souple » du clan Hyuga vise les points de chakra ?", a: "Le Juken", acc: ["juken", "poing souple"], x: ["Le Goken", "Le Suiken", "Le Rokushiki"] },
  { id: "naruto-p17", d: 4, t: "Quels animaux le clan Aburame utilise-t-il ?", a: "Les insectes", acc: ["insectes", "kikaichu"], x: ["Les abeilles", "Les papillons", "Les fourmis"] },
  { id: "naruto-p18", d: 4, t: "Quel clan utilise l'agrandissement du corps ?", a: "Le clan Akimichi", acc: ["akimichi"], x: ["Le clan Nara", "Le clan Yamanaka", "Le clan Inuzuka"] },
  { id: "naruto-p19", d: 4, t: "Quelle technique d'ombre est la spécialité du clan Nara ?", a: "Le Kagemane", acc: ["kagemane", "possession des ombres"], x: ["Le Shintenshin", "Le Baika", "Le Hijutsu"] },
  { id: "naruto-p20", d: 4, t: "Comment se nomme l'épée légendaire que manie Sasuke ?", a: "L'épée de Kusanagi", acc: ["kusanagi"], x: ["Samehada", "Kubikiribocho", "Nuibari"] },
]);
