import { universe } from "../_build";

export const opm = universe("manga", "One Punch Man", [
  // --- Faciles (5) ---
  { id: "opm-f1", d: 1, t: "Quel est le pouvoir de Saitama dans One Punch Man ?", a: "Vaincre en un seul coup de poing", x: ["Voler", "Lire les pensées", "Devenir invisible"], acc: ["un coup de poing", "un seul coup de poing", "one punch"] },
  { id: "opm-f2", d: 1, t: "Quelle particularité physique caractérise Saitama ?", a: "Il est chauve", x: ["Il est géant", "Il a des ailes", "Il est bleu"], acc: ["chauve", "il est chauve"] },
  { id: "opm-f3", d: 1, t: "De quelle couleur est la tenue de héros de Saitama ?", a: "Jaune", x: ["Rouge", "Bleue", "Noire"], acc: ["jaune"] },
  { id: "opm-f4", d: 1, t: "Quel sentiment envahit souvent Saitama à cause de sa force ?", a: "L'ennui", x: ["La peur", "La colère", "La tristesse"], acc: ["ennui", "l'ennui", "il s'ennuie"] },
  { id: "opm-f5", d: 1, t: "Comment s'appelle le disciple cyborg de Saitama ?", a: "Genos", x: ["Sonic", "King", "Garou"], acc: ["genos"] },
  // --- Moyennes (10) ---
  { id: "opm-m1", d: 2, t: "Quel entraînement quotidien a rendu Saitama si fort ?", a: "100 pompes, 100 abdos, 100 squats et 10 km de course", x: ["Soulever des voitures", "Méditer chaque jour", "Manger sainement"], acc: ["100 pompes", "pompes abdos squats"] },
  { id: "opm-m2", d: 2, t: "Qu'aurait perdu Saitama à cause de son entraînement intense ?", a: "Ses cheveux", x: ["Sa mémoire", "Sa vue", "Sa voix"], acc: ["cheveux", "ses cheveux"] },
  { id: "opm-m3", d: 2, t: "Quelle organisation classe et emploie les héros ?", a: "L'Association des héros", x: ["L'Association des monstres", "La Team 7", "Le Bureau des Aventuriers"], acc: ["association des heros", "hero association"] },
  { id: "opm-m4", d: 2, t: "Comment sont classés les héros, de la plus basse à la plus haute catégorie ?", a: "De classe C à classe S", x: ["De 1 à 10", "De Bronze à Or", "De Novice à Légende"], acc: ["classe c a s", "classe s", "c a s"] },
  { id: "opm-m5", d: 2, t: "Qui est le dessinateur du manga One Punch Man, au style très détaillé ?", a: "Yusuke Murata", x: ["Eiichiro Oda", "Masashi Kishimoto", "Gege Akutami"], acc: ["yusuke murata", "murata"] },
  { id: "opm-m6", d: 2, t: "Quelle est l'expression favorite et blasée de Saitama ?", a: "OK", x: ["Plus ultra", "Dattebayo", "Bankai"], acc: ["ok"] },
  { id: "opm-m7", d: 2, t: "Comment les villes sont-elles nommées dans One Punch Man ?", a: "Par des lettres, de A à Z", x: ["Par des chiffres", "Par des couleurs", "Par des animaux"], acc: ["par des lettres", "lettres", "a a z"] },
  { id: "opm-m8", d: 2, t: "Quel studio a animé la première saison acclamée en 2015 ?", a: "Madhouse", x: ["MAPPA", "Toei", "Bones"], acc: ["madhouse"] },
  { id: "opm-m9", d: 2, t: "Pourquoi Saitama est-il devenu un héros au départ ?", a: "Pour le plaisir", x: ["Pour l'argent", "Pour la gloire", "Par vengeance"], acc: ["pour le plaisir", "plaisir", "loisir"] },
  { id: "opm-m10", d: 2, t: "Comment s'appelle le héros cycliste courageux de classe C, très aimé ?", a: "Mumen Rider", x: ["Sonic", "King", "Metal Bat"], acc: ["mumen rider", "mumen"] },
  // --- Dures (15) ---
  { id: "opm-d1", d: 3, t: "Comment s'appelle le « chasseur de héros » qui rêve de devenir un monstre ?", a: "Garou", x: ["Sonic", "Boros", "Genos"], acc: ["garou"] },
  { id: "opm-d2", d: 3, t: "Comment s'appelle l'esper de rang S surnommée « Tornade Terrible » ?", a: "Tatsumaki", x: ["Fubuki", "Psykos", "Do-S"], acc: ["tatsumaki", "tornade terrible"] },
  { id: "opm-d3", d: 3, t: "Comment s'appelle le ninja rival autoproclamé de Saitama ?", a: "Sonic", x: ["Genos", "Garou", "Flashy Flash"], acc: ["sonic", "speed-o'-sound sonic"] },
  { id: "opm-d4", d: 3, t: "Comment s'appelle le premier grand adversaire alien de Saitama ?", a: "Boros", x: ["Garou", "Vaccine Man", "Carnage Kabuto"], acc: ["boros", "lord boros"] },
  { id: "opm-d5", d: 3, t: "Quel héros de rang S est réputé le plus fort, mais n'a en réalité aucun pouvoir ?", a: "King", x: ["Blast", "Bang", "Metal Knight"], acc: ["king"] },
  { id: "opm-d6", d: 3, t: "Comment appelle-t-on l'organisation ennemie qui regroupe les monstres ?", a: "L'Association des monstres", x: ["L'Akatsuki", "La Team Rocket", "Le Syndicat"], acc: ["association des monstres", "monster association"] },
  { id: "opm-d7", d: 3, t: "Comment s'appelle la sœur cadette de Tatsumaki, héroïne de classe B ?", a: "Fubuki", x: ["Tatsumaki", "Psykos", "Do-S"], acc: ["fubuki", "blizzard"] },
  { id: "opm-d8", d: 3, t: "Quel vieux maître d'arts martiaux de rang S entraîne Garou ?", a: "Bang", x: ["Atomic Samurai", "King", "Blast"], acc: ["bang", "silver fang"] },
  { id: "opm-d9", d: 3, t: "Comment s'appelle le héros de rang 1, le plus mystérieux de tous ?", a: "Blast", x: ["King", "Bang", "Genos"], acc: ["blast"] },
  { id: "opm-d10", d: 3, t: "Comment s'appelle le monstre qui humilie plusieurs héros sous la pluie ?", a: "Le Roi des profondeurs", x: ["Carnage Kabuto", "Vaccine Man", "Boros"], acc: ["roi des profondeurs", "deep sea king"] },
  { id: "opm-d11", d: 3, t: "Quel héros de rang S au katana est un maître du sabre ?", a: "Atomic Samurai", x: ["Metal Bat", "Bang", "Zombieman"], acc: ["atomic samurai", "samurai atomique"] },
  { id: "opm-d12", d: 3, t: "Quel héros de rang S, quasi immortel, guérit de toutes ses blessures ?", a: "Zombieman", x: ["Metal Bat", "King", "Pig God"], acc: ["zombieman"] },
  { id: "opm-d13", d: 3, t: "Quel jeune héros de rang S se bat avec une batte de baseball ?", a: "Metal Bat", x: ["Atomic Samurai", "Zombieman", "Sonic"], acc: ["metal bat"] },
  { id: "opm-d14", d: 3, t: "Comment surnomme-t-on Genos en tant que héros ?", a: "Le Cyborg Démoniaque", x: ["Le Chauve à la cape", "Le Samouraï d'acier", "L'Homme-fusée"], acc: ["cyborg demoniaque", "demon cyborg"] },
  { id: "opm-d15", d: 3, t: "Comment surnomme-t-on Saitama, à cause de sa cape et de son crâne ?", a: "Le Chauve à la cape", x: ["Le Cyborg Démoniaque", "Le Roi", "L'Éclair"], acc: ["chauve a la cape", "caped baldy"] },
  // --- Pro (20) ---
  { id: "opm-p1", d: 4, t: "Sous quel pseudonyme l'auteur original de One Punch Man est-il connu ?", a: "ONE", x: ["TWO", "Boichi", "Gosho"], acc: ["one"] },
  { id: "opm-p2", d: 4, t: "En quelle année la première saison de l'anime est-elle sortie ?", a: "2015", x: ["2010", "2019", "2022"], acc: ["2015"] },
  { id: "opm-p3", d: 4, t: "Quel studio a repris l'animation pour la deuxième saison en 2019 ?", a: "J.C.Staff", x: ["Madhouse", "Ufotable", "Wit Studio"], acc: ["j.c.staff", "jc staff", "jcstaff"] },
  { id: "opm-p4", d: 4, t: "Comment s'appelle le premier monstre vaincu par Saitama au début de la série ?", a: "Vaccine Man", x: ["Boros", "Carnage Kabuto", "Le Roi des profondeurs"], acc: ["vaccine man"] },
  { id: "opm-p5", d: 4, t: "Quel monstre-insecte Saitama affronte-t-il dans la Maison de l'évolution ?", a: "Carnage Kabuto", x: ["Vaccine Man", "Boros", "Garou"], acc: ["carnage kabuto", "kabuto"] },
  { id: "opm-p6", d: 4, t: "Comment appelle-t-on le battement de cœur de King, pris à tort pour une aura de puissance ?", a: "Le King Engine", x: ["Le Boros Beat", "Le Genos Drive", "Le Saitama Pulse"], acc: ["king engine"] },
  { id: "opm-p7", d: 4, t: "Quel héros efféminé et musclé de rang S se bat par amour ?", a: "Puri-Puri Prisoner", x: ["Metal Bat", "Pig God", "King"], acc: ["puri-puri prisoner", "puri puri"] },
  { id: "opm-p8", d: 4, t: "Quel héros géant de rang S dévore tout sur son passage ?", a: "Pig God", x: ["Superalloy", "Metal Bat", "Tanktop Master"], acc: ["pig god"] },
  { id: "opm-p9", d: 4, t: "Quel héros de rang S ultra-rapide, aux cheveux blonds, est un ninja d'élite ?", a: "Flashy Flash", x: ["Sonic", "Atomic Samurai", "Drive Knight"], acc: ["flashy flash", "flash"] },
  { id: "opm-p10", d: 4, t: "Quel héros inventeur de rang S envoie des robots au combat ?", a: "Metal Knight", x: ["Drive Knight", "Genos", "Zombieman"], acc: ["metal knight", "bofoi"] },
  { id: "opm-p11", d: 4, t: "Quel est le vrai but de Garou : détruire quoi ?", a: "L'idée même des héros", x: ["L'Association des monstres", "La ville Z", "Saitama uniquement"], acc: ["l'idee des heros", "les heros", "idee meme des heros"] },
  { id: "opm-p12", d: 4, t: "Comment s'appelle le maître d'arts martiaux, grand frère de Bang ?", a: "Bomb", x: ["Blast", "Atomic Samurai", "Silver Fang"], acc: ["bomb"] },
  { id: "opm-p13", d: 4, t: "Quel cerveau maléfique, une esper, dirige secrètement l'Association des monstres ?", a: "Psykos", x: ["Do-S", "Tatsumaki", "Fubuki"], acc: ["psykos"] },
  { id: "opm-p14", d: 4, t: "Quel monstre-roi dragon dirige l'Association des monstres ?", a: "Orochi", x: ["Boros", "Garou", "Elder Centipede"], acc: ["orochi", "monster king orochi"] },
  { id: "opm-p15", d: 4, t: "Comment s'appelle le mille-pattes géant, monstre de niveau Dragon ?", a: "Elder Centipede", x: ["Orochi", "Carnage Kabuto", "Vaccine Man"], acc: ["elder centipede", "centipede"] },
  { id: "opm-p16", d: 4, t: "Quel niveau de menace, le plus élevé avant « Dieu », désignent les pires monstres ?", a: "Le niveau Dragon", x: ["Le niveau Loup", "Le niveau Tigre", "Le niveau Démon"], acc: ["niveau dragon", "dragon"] },
  { id: "opm-p17", d: 4, t: "Comment s'appelle le club de héros musclés en marcel, mené par Tanktop Master ?", a: "Les Tanktop", x: ["Les Bodybuilders", "Les Musclors", "Les Débardeurs d'acier"], acc: ["tanktop", "les tanktop"] },
  { id: "opm-p18", d: 4, t: "Quel héros de rang S, un robot, se méfie même des autres héros ?", a: "Drive Knight", x: ["Metal Knight", "Genos", "King"], acc: ["drive knight"] },
  { id: "opm-p19", d: 4, t: "Quel héros-chien de rang S protège seul une ville entière ?", a: "Watchdog Man", x: ["Pig God", "King", "Puri-Puri Prisoner"], acc: ["watchdog man"] },
  { id: "opm-p20", d: 4, t: "Quel niveau de menace correspond à un monstre pouvant détruire une ville ?", a: "Le niveau Démon", x: ["Le niveau Loup", "Le niveau Tigre", "Le niveau Serpent"], acc: ["niveau demon", "demon"] },
]);
