import { universe } from "../_build";

export const promisedneverland = universe("manga", "The Promised Neverland", [
  // --- Faciles (5) ---
  { id: "tpn-f1", d: 1, t: "Où vivent les enfants au début de The Promised Neverland ?", a: "Dans un orphelinat", x: ["Dans un château", "Dans une école de magie", "Sur un bateau"], acc: ["orphelinat"] },
  { id: "tpn-f2", d: 1, t: "Quel terrible secret les enfants découvrent-ils sur leur sort ?", a: "Ils sont élevés pour être mangés", x: ["Ils sont vendus comme esclaves", "Ils sont des robots", "Ils sont clonés"], acc: ["eleves pour etre manges", "manges"] },
  { id: "tpn-f3", d: 1, t: "Quelles créatures se nourrissent des enfants ?", a: "Des démons", x: ["Des vampires", "Des zombies", "Des dragons"], acc: ["demons", "démons"] },
  { id: "tpn-f4", d: 1, t: "Combien d'enfants forment le trio de tête qui mène l'évasion ?", a: "Trois", x: ["Deux", "Cinq", "Sept"], acc: ["3", "trois"] },
  { id: "tpn-f5", d: 1, t: "Quel est le principal objectif des enfants ?", a: "S'évader de l'orphelinat", x: ["Gagner un concours", "Devenir démons", "Retrouver un trésor"], acc: ["s'evader", "evasion"] },
  // --- Moyennes (10) ---
  { id: "tpn-m1", d: 2, t: "Quelle fillette rousse, pleine d'espoir, refuse d'abandonner qui que ce soit ?", a: "Emma", x: ["Norman", "Ray", "Gilda"], acc: ["emma"] },
  { id: "tpn-m2", d: 2, t: "Quel garçon génie aux cheveux blancs élabore les premiers plans d'évasion ?", a: "Norman", x: ["Ray", "Phil", "Don"], acc: ["norman"] },
  { id: "tpn-m3", d: 2, t: "Quel garçon cynique aux cheveux noirs se révèle d'abord être une taupe ?", a: "Ray", x: ["Norman", "Emma", "Don"], acc: ["ray"] },
  { id: "tpn-m4", d: 2, t: "Comment les enfants appellent-ils Isabella, leur gardienne ?", a: "Maman", x: ["Sœur", "Tante", "Reine"], acc: ["maman", "mom"] },
  { id: "tpn-m5", d: 2, t: "Où les enfants portent-ils un numéro d'identification tatoué ?", a: "Sur le cou", x: ["Sur le poignet", "Dans le dos", "Sur la cheville"], acc: ["cou", "le cou"] },
  { id: "tpn-m6", d: 2, t: "Que leur est-il formellement interdit de franchir autour de l'orphelinat ?", a: "Le mur et la porte", x: ["La rivière", "La forêt magique", "Le pont-levis"], acc: ["mur et la porte", "le mur"] },
  { id: "tpn-m7", d: 2, t: "La mort de quelle petite fille ouvre les yeux d'Emma et Norman ?", a: "Conny", x: ["Gilda", "Anna", "Phil"], acc: ["conny"] },
  { id: "tpn-m8", d: 2, t: "Qu'obtiennent systématiquement les trois héros aux tests quotidiens ?", a: "Le score maximum", x: ["La note zéro", "La moyenne", "Des points bonus"], acc: ["score maximum", "score parfait"] },
  { id: "tpn-m9", d: 2, t: "En quelle année la première saison de l'anime est-elle sortie ?", a: "2019", x: ["2015", "2017", "2021"], acc: ["2019"] },
  { id: "tpn-m10", d: 2, t: "À quel genre The Promised Neverland appartient-il ?", a: "Le thriller horrifique", x: ["La comédie romantique", "Le sport", "L'heroic fantasy joyeuse"], acc: ["thriller", "thriller horrifique"] },
  // --- Dures (15) ---
  { id: "tpn-d1", d: 3, t: "Comment s'appelle l'orphelinat où débute l'histoire ?", a: "Grace Field", x: ["Goldy Pond", "Grand Valley", "Glory Bell"], acc: ["grace field"] },
  { id: "tpn-d2", d: 3, t: "Quelle partie des enfants les démons convoitent-ils particulièrement ?", a: "Le cerveau", x: ["Le cœur", "Le sang", "Les os"], acc: ["cerveau", "le cerveau"] },
  { id: "tpn-d3", d: 3, t: "Quelle seconde « sœur » est envoyée surveiller Isabella et les enfants ?", a: "Krone", x: ["Gilda", "Mujika", "Anna"], acc: ["krone"] },
  { id: "tpn-d4", d: 3, t: "Quel passé Isabella partage-t-elle secrètement avec les enfants ?", a: "Elle a grandi dans une ferme d'élevage", x: ["Elle est une démone", "Elle est un robot", "Elle vient d'un autre monde"], acc: ["grandi dans une ferme", "ancienne enfant"] },
  { id: "tpn-d5", d: 3, t: "Quel lien de sang unit Ray à « Maman » Isabella ?", a: "C'est son fils", x: ["C'est son neveu", "C'est son frère", "Aucun lien"], acc: ["son fils", "fils"] },
  { id: "tpn-d6", d: 3, t: "Lors de la grande évasion, qui les héros doivent-ils laisser derrière eux ?", a: "Les plus jeunes enfants", x: ["Les plus âgés", "Personne", "Les malades seulement"], acc: ["plus jeunes", "les petits"] },
  { id: "tpn-d7", d: 3, t: "Quel mystérieux bienfaiteur laisse des indices cachés dans les livres de la bibliothèque ?", a: "William Minerva", x: ["Yugo", "Sonju", "Peter Ratri"], acc: ["william minerva", "minerva"] },
  { id: "tpn-d8", d: 3, t: "Grâce à quel objet dissimulé les enfants déchiffrent-ils le message secret de Minerva ?", a: "Un stylo", x: ["Une montre", "Une boussole", "Une clé"], acc: ["stylo", "un stylo"] },
  { id: "tpn-d9", d: 3, t: "Dans quel abri souterrain les évadés trouvent-ils refuge, gardé par Yugo ?", a: "L'abri B06-32", x: ["Goldy Pond", "Grace Field", "Le Temple"], acc: ["b06-32", "abri b06-32"] },
  { id: "tpn-d10", d: 3, t: "Quel lieu secret sert de terrain où des démons traquent des enfants pour le sport ?", a: "Goldy Pond", x: ["Grace Field", "Cuvitidala", "Le Sanctuaire"], acc: ["goldy pond"] },
  { id: "tpn-d11", d: 3, t: "Quelle démone bienveillante n'a pas besoin de manger des humains pour garder sa forme ?", a: "Mujika", x: ["Krone", "Isabella", "Emma"], acc: ["mujika"] },
  { id: "tpn-d12", d: 3, t: "Quel démon accompagne Mujika et enseigne la chasse à Emma ?", a: "Sonju", x: ["Yugo", "Norman", "Ray"], acc: ["sonju"] },
  { id: "tpn-d13", d: 3, t: "Que risquent les démons ordinaires s'ils cessent de manger des humains ?", a: "De dégénérer en bêtes", x: ["De rajeunir", "De devenir humains", "De s'endormir"], acc: ["degenerer", "degenerer en betes"] },
  { id: "tpn-d14", d: 3, t: "Il y a mille ans, un pacte a séparé le monde des humains de celui des démons : comment l'appelle-t-on ?", a: "La Promesse", x: ["Le Traité", "L'Alliance", "Le Serment de sang"], acc: ["promesse", "la promesse", "promise"] },
  { id: "tpn-d15", d: 3, t: "Quel héros, cru mort après avoir été « expédié », réapparaît à la tête d'un groupe d'enfants ?", a: "Norman", x: ["Ray", "Yugo", "Emma"], acc: ["norman"] },
  // --- Pro (20) ---
  { id: "tpn-p1", d: 4, t: "Qui a écrit le scénario de The Promised Neverland ?", a: "Kaiu Shirai", x: ["Posuka Demizu", "Tatsuya Endo", "Gege Akutami"], acc: ["kaiu shirai", "shirai"] },
  { id: "tpn-p2", d: 4, t: "Qui a dessiné le manga The Promised Neverland ?", a: "Posuka Demizu", x: ["Kaiu Shirai", "Yusuke Murata", "Takeshi Obata"], acc: ["posuka demizu", "demizu"] },
  { id: "tpn-p3", d: 4, t: "Dans quel magazine le manga a-t-il été prépublié ?", a: "Weekly Shonen Jump", x: ["Shonen Magazine", "Young Jump", "Ribon"], acc: ["shonen jump", "weekly shonen jump"] },
  { id: "tpn-p4", d: 4, t: "Quel studio a animé The Promised Neverland ?", a: "CloverWorks", x: ["MAPPA", "Ufotable", "Kyoto Animation"], acc: ["cloverworks"] },
  { id: "tpn-p5", d: 4, t: "Quel numéro est tatoué sur le cou d'Emma ?", a: "63194", x: ["22194", "81194", "63149"], acc: ["63194"] },
  { id: "tpn-p6", d: 4, t: "Selon quel critère les enfants au « meilleur cerveau » sont-ils les plus prisés ?", a: "Leur intelligence", x: ["Leur âge", "Leur force", "Leur taille"], acc: ["intelligence"] },
  { id: "tpn-p7", d: 4, t: "Dans quel centre d'expérimentation Norman a-t-il été envoyé après Grace Field ?", a: "Lambda", x: ["Goldy Pond", "Cuvitidala", "Grace Field"], acc: ["lambda", "lambda 7214"] },
  { id: "tpn-p8", d: 4, t: "Quel clan humain veille, en traître, au respect de la Promesse côté humain ?", a: "Le clan Ratri", x: ["Le clan Minerva", "Le clan Nouzen", "Le clan Grace"], acc: ["ratri", "clan ratri"] },
  { id: "tpn-p9", d: 4, t: "Quel homme du clan Ratri devient un antagoniste majeur, traquant les évadés ?", a: "Peter Ratri", x: ["William Minerva", "Yugo", "Sonju"], acc: ["peter ratri", "peter"] },
  { id: "tpn-p10", d: 4, t: "Comment surnomme-t-on le sang de Mujika, qui libère les démons de leur faim d'humains ?", a: "Le sang maudit", x: ["Le sang royal", "Le sang d'or", "Le sang pur"], acc: ["sang maudit", "cursed blood"] },
  { id: "tpn-p11", d: 4, t: "Quel lieu mystérieux Emma doit-elle atteindre pour renégocier la Promesse ?", a: "Les Sept Murs", x: ["Goldy Pond", "Le Temple d'or", "La Grande Vallée"], acc: ["sept murs", "seven walls"] },
  { id: "tpn-p12", d: 4, t: "À quel âge, au plus tard, un enfant est-il « expédié » depuis Grace Field ?", a: "Douze ans", x: ["Six ans", "Dix-huit ans", "Vingt ans"], acc: ["12", "douze", "douze ans"] },
  { id: "tpn-p13", d: 4, t: "Quel jeune garçon perspicace Emma promet-elle de revenir chercher ?", a: "Phil", x: ["Don", "Gilda", "Yugo"], acc: ["phil"] },
  { id: "tpn-p14", d: 4, t: "Quels deux autres enfants Emma et Ray finissent-ils par mettre dans la confidence ?", a: "Don et Gilda", x: ["Phil et Conny", "Norman et Ray", "Krone et Isabella"], acc: ["don et gilda"] },
  { id: "tpn-p15", d: 4, t: "Combien de tomes compte le manga, achevé en 2020 ?", a: "Vingt", x: ["Dix", "Trente-cinq", "Cinquante"], acc: ["20", "vingt"] },
  { id: "tpn-p16", d: 4, t: "Comment se conclut l'accord final entre Emma et les démons ?", a: "Tous les humains rejoignent le monde humain", x: ["Les démons sont exterminés", "L'orphelinat rouvre", "Emma devient reine des démons"], acc: ["rejoignent le monde humain"] },
  { id: "tpn-p17", d: 4, t: "Quel lourd prix Emma paie-t-elle en scellant la nouvelle promesse ?", a: "Elle est séparée des autres enfants", x: ["Elle perd la vue", "Elle devient démone", "Elle rajeunit"], acc: ["separee des autres", "perd ses souvenirs"] },
  { id: "tpn-p18", d: 4, t: "Quel adulte bourru, survivant d'une autre ferme, protège malgré lui les enfants à l'abri ?", a: "Yugo", x: ["Sonju", "Peter Ratri", "William Minerva"], acc: ["yugo"] },
  { id: "tpn-p19", d: 4, t: "Quel animal symbolise les messages secrets de William Minerva ?", a: "La chouette", x: ["Le corbeau", "Le renard", "Le loup"], acc: ["chouette", "hibou"] },
  { id: "tpn-p20", d: 4, t: "De quelle catégorie de ferme, produisant les meilleurs enfants, Grace Field fait-elle partie ?", a: "Une ferme premium", x: ["Une ferme de masse", "Une ferme sauvage", "Une ferme abandonnée"], acc: ["premium", "ferme premium", "haut de gamme"] },
]);
