import { universe } from "../_build";

export const slime = universe("manga", "Moi quand je me réincarne en slime", [
  // --- Faciles (5) ---
  { id: "slime-f1", d: 1, t: "En quelle créature le héros se réincarne-t-il ?", a: "Un slime", x: ["Un dragon", "Un gobelin", "Un humain"], acc: ["slime", "un slime"] },
  { id: "slime-f2", d: 1, t: "Quel nom le slime se choisit-il dans son nouveau monde ?", a: "Rimuru", x: ["Satoru", "Veldora", "Benimaru"], acc: ["rimuru", "rimuru tempest"] },
  { id: "slime-f3", d: 1, t: "Qu'était le héros dans sa vie précédente, avant de mourir ?", a: "Un employé de bureau", x: ["Un roi", "Un chevalier", "Un enfant"], acc: ["employe de bureau", "salaryman"] },
  { id: "slime-f4", d: 1, t: "Que finit par bâtir Rimuru dans la forêt de Jura ?", a: "Une nation de monstres", x: ["Une prison", "Une école de magie", "Un cirque"], acc: ["nation de monstres", "pays", "tempest"] },
  { id: "slime-f5", d: 1, t: "À quel genre, celui du transfert dans un autre monde, l'œuvre appartient-elle ?", a: "L'isekai", x: ["Le policier", "Le sport", "La tranche de vie scolaire"], acc: ["isekai"] },
  // --- Moyennes (10) ---
  { id: "slime-m1", d: 2, t: "Comment s'appelait le héros dans sa vie humaine ?", a: "Satoru Mikami", x: ["Rimuru Tempest", "Ken Kaneki", "Subaru Natsuki"], acc: ["satoru mikami", "satoru"] },
  { id: "slime-m2", d: 2, t: "Quel dragon-tempête scellé devient le premier ami de Rimuru ?", a: "Veldora", x: ["Milim", "Ranga", "Charybde"], acc: ["veldora", "veldora tempest"] },
  { id: "slime-m3", d: 2, t: "Quel nom de famille Rimuru partage-t-il avec le dragon Veldora ?", a: "Tempest", x: ["Nava", "Crimson", "Mikami"], acc: ["tempest"] },
  { id: "slime-m4", d: 2, t: "Quelle capacité permet à Rimuru d'absorber et de copier ce qu'il dévore ?", a: "Le Prédateur", x: ["Le Grand Sage", "La Barrière", "Le Vol"], acc: ["predateur", "prédateur", "predator"] },
  { id: "slime-m5", d: 2, t: "Quelle compétence d'analyse, à la voix neutre, conseille Rimuru en permanence ?", a: "Le Grand Sage", x: ["Le Prédateur", "L'Œil du Dragon", "La Barrière absolue"], acc: ["grand sage", "great sage"] },
  { id: "slime-m6", d: 2, t: "Quel peuple, d'abord menacé, devient les tout premiers sujets de Rimuru ?", a: "Les gobelins", x: ["Les nains", "Les elfes", "Les ogres"], acc: ["gobelins"] },
  { id: "slime-m7", d: 2, t: "Quelle Démone surpuissante aux cheveux roses devient l'amie de Rimuru ?", a: "Milim", x: ["Shion", "Shuna", "Hinata"], acc: ["milim", "milim nava"] },
  { id: "slime-m8", d: 2, t: "Quel loup géant, chef de meute, devient une monture fidèle de Rimuru ?", a: "Ranga", x: ["Gobta", "Benimaru", "Souei"], acc: ["ranga"] },
  { id: "slime-m9", d: 2, t: "Sous quel nom de plume l'auteur original du light novel écrit-il ?", a: "Fuse", x: ["ONE", "Fujino Omori", "Reki Kawahara"], acc: ["fuse"] },
  { id: "slime-m10", d: 2, t: "En quelle année l'anime a-t-il commencé sa diffusion ?", a: "2018", x: ["2014", "2016", "2021"], acc: ["2018"] },
  // --- Dures (15) ---
  { id: "slime-d1", d: 3, t: "Comment se nomme la nation fondée par Rimuru dans la forêt de Jura ?", a: "La Fédération Jura Tempest", x: ["L'Empire de Falmuth", "Le Royaume de Blumund", "L'Octogramme"], acc: ["jura tempest", "tempest", "federation jura tempest"] },
  { id: "slime-d2", d: 3, t: "De quelle humaine Rimuru adopte-t-il l'apparence après l'avoir absorbée ?", a: "Shizu", x: ["Milim", "Hinata", "Shuna"], acc: ["shizu", "shizue"] },
  { id: "slime-d3", d: 3, t: "Quel esprit de feu Shizu hébergeait-elle en elle ?", a: "Ifrit", x: ["Veldora", "Charybde", "Ranga"], acc: ["ifrit"] },
  { id: "slime-d4", d: 3, t: "Quel jeune chef ogre, maître du feu, devient le bras droit militaire de Rimuru ?", a: "Benimaru", x: ["Souei", "Hakurou", "Gobta"], acc: ["benimaru"] },
  { id: "slime-d5", d: 3, t: "Quelle ogresse devient la secrétaire dévouée de Rimuru, redoutable mais piètre cuisinière ?", a: "Shion", x: ["Shuna", "Milim", "Shizu"], acc: ["shion"] },
  { id: "slime-d6", d: 3, t: "Quelle douce ogresse, sœur de Benimaru, sert de prêtresse et de couturière ?", a: "Shuna", x: ["Shion", "Milim", "Treyni"], acc: ["shuna"] },
  { id: "slime-d7", d: 3, t: "Quel ogre discret devient l'espion et le messager de Rimuru ?", a: "Souei", x: ["Benimaru", "Hakurou", "Kurobe"], acc: ["souei"] },
  { id: "slime-d8", d: 3, t: "Quel vieil ogre, maître épéiste, entraîne les troupes de Tempest ?", a: "Hakurou", x: ["Souei", "Benimaru", "Gobta"], acc: ["hakurou"] },
  { id: "slime-d9", d: 3, t: "Quel gobelin maladroit mais étonnamment doué chevauche Ranga au combat ?", a: "Gobta", x: ["Rigurd", "Benimaru", "Souei"], acc: ["gobta"] },
  { id: "slime-d10", d: 3, t: "Quel statut Rimuru acquiert-il en éveillant tout son potentiel ?", a: "Roi-Démon", x: ["Héros", "Empereur humain", "Dieu-dragon"], acc: ["roi-demon", "roi démon", "maou", "demon lord"] },
  { id: "slime-d11", d: 3, t: "Que doit rassembler Rimuru pour s'éveiller pleinement en Roi-Démon ?", a: "Des milliers d'âmes humaines", x: ["Sa mémoire", "Son slime d'origine", "Le dragon Veldora"], acc: ["ames humaines", "milliers d'ames"] },
  { id: "slime-d12", d: 3, t: "Quel Roi-Démon manipulateur orchestre l'attaque contre Tempest ?", a: "Clayman", x: ["Guy Crimson", "Milim", "Diablo"], acc: ["clayman"] },
  { id: "slime-d13", d: 3, t: "Quel puissant démon noir, d'une politesse glaçante, jure allégeance à Rimuru ?", a: "Diablo", x: ["Clayman", "Veldora", "Geld"], acc: ["diablo"] },
  { id: "slime-d14", d: 3, t: "Quel seigneur orc, poussé par la famine, menace la forêt avant d'être vaincu ?", a: "Geld", x: ["Clayman", "Charybde", "Hinata"], acc: ["geld", "orc disaster"] },
  { id: "slime-d15", d: 3, t: "Quelle redoutable chevalière sainte de l'Église occidentale affronte Rimuru ?", a: "Hinata", x: ["Milim", "Shion", "Shizu"], acc: ["hinata", "hinata sakaguchi"] },
  // --- Pro (20) ---
  { id: "slime-p1", d: 4, t: "En quelle compétence supérieure le Grand Sage évolue-t-il après l'éveil de Rimuru ?", a: "Raphaël", x: ["Uriel", "Michaël", "Gabriel"], acc: ["raphael", "raphaël"] },
  { id: "slime-p2", d: 4, t: "Quel prénom l'intelligence Raphaël finit-elle par prendre ?", a: "Ciel", x: ["Shizu", "Milim", "Ceres"], acc: ["ciel"] },
  { id: "slime-p3", d: 4, t: "Comment nomme-t-on l'alliance des plus grands Rois-Démons, au nombre de huit ?", a: "L'Octogramme", x: ["Le Conseil", "La Table ronde", "Le Décagramme"], acc: ["octogramme", "octagram"] },
  { id: "slime-p4", d: 4, t: "Quel Roi-Démon primordial, parmi les plus anciens et puissants, règne sur les glaces ?", a: "Guy Crimson", x: ["Clayman", "Milim", "Geld"], acc: ["guy crimson", "guy"] },
  { id: "slime-p5", d: 4, t: "Quel studio produit l'anime Tensura ?", a: "Eight Bit", x: ["MAPPA", "Ufotable", "Bones"], acc: ["eight bit", "8bit", "8-bit"] },
  { id: "slime-p6", d: 4, t: "Sous quel diminutif japonais l'œuvre est-elle connue ?", a: "Tensura", x: ["Konosuba", "Re:Zero", "Overlord"], acc: ["tensura"] },
  { id: "slime-p7", d: 4, t: "À quel âge Satoru Mikami est-il mort dans sa vie humaine ?", a: "37 ans", x: ["18 ans", "25 ans", "50 ans"], acc: ["37", "37 ans"] },
  { id: "slime-p8", d: 4, t: "Comment Satoru meurt-il au tout début de l'histoire ?", a: "Poignardé dans la rue", x: ["Dans un accident d'avion", "D'une longue maladie", "Noyé en mer"], acc: ["poignarde", "poignardé"] },
  { id: "slime-p9", d: 4, t: "Quelle particularité Rimuru a-t-il concernant son genre, en tant que slime ?", a: "Il n'a plus de sexe défini", x: ["Il est une femme", "Il change chaque jour", "Il reste un homme robuste"], acc: ["pas de sexe", "asexue", "sans genre"] },
  { id: "slime-p10", d: 4, t: "De quel élément Veldora, l'ami dragon de Rimuru, est-il le maître ?", a: "La tempête", x: ["La glace", "Le feu", "La terre"], acc: ["tempete", "tempête", "storm"] },
  { id: "slime-p11", d: 4, t: "Quel royaume humain, manipulé par Clayman, attaque et massacre des habitants de Tempest ?", a: "Falmuth", x: ["Blumund", "Ingracia", "Dwargon"], acc: ["falmuth"] },
  { id: "slime-p12", d: 4, t: "Quelle proche de Rimuru, tuée lors de l'attaque, est ressuscitée grâce à son éveil ?", a: "Shion", x: ["Shuna", "Milim", "Shizu"], acc: ["shion"] },
  { id: "slime-p13", d: 4, t: "Quel royaume nain, dirigé par le roi Gazel, est un voisin de Tempest ?", a: "Dwargon", x: ["Falmuth", "Blumund", "Ingracia"], acc: ["dwargon"] },
  { id: "slime-p14", d: 4, t: "Quel métier Rimuru exerce-t-il un temps auprès d'enfants dotés de pouvoirs, à Ingracia ?", a: "Professeur", x: ["Forgeron", "Cuisinier", "Soldat"], acc: ["professeur", "enseignant"] },
  { id: "slime-p15", d: 4, t: "Quel monstre-calamité volant, lié à Milim, menace un temps la forêt ?", a: "Charybde", x: ["Geld", "Clayman", "Ifrit"], acc: ["charybde", "charybdis"] },
  { id: "slime-p16", d: 4, t: "Quel gobelin âgé devient le premier chef administratif du village de Rimuru ?", a: "Rigurd", x: ["Gobta", "Ranga", "Benimaru"], acc: ["rigurd"] },
  { id: "slime-p17", d: 4, t: "Quelle dryade veille sur la forêt de Jura et respecte Rimuru ?", a: "Treyni", x: ["Milim", "Shuna", "Hinata"], acc: ["treyni"] },
  { id: "slime-p18", d: 4, t: "Quelle approche Rimuru privilégie-t-il pour agrandir sa nation ?", a: "Nouer des alliances", x: ["La conquête sanglante", "L'esclavage", "L'isolement total"], acc: ["alliances", "nouer des alliances"] },
  { id: "slime-p19", d: 4, t: "Quel petit royaume humain devient le premier partenaire commercial de Tempest ?", a: "Blumund", x: ["Falmuth", "Dwargon", "Ingracia"], acc: ["blumund"] },
  { id: "slime-p20", d: 4, t: "Sur quel type de plateforme l'œuvre a-t-elle d'abord été publiée ?", a: "Un site de romans amateurs", x: ["Un journal papier", "Une chaîne YouTube", "Un magazine de mode"], acc: ["site de romans", "web novel", "narou"] },
]);
