import { universe } from "../_build";

export const sololeveling = universe("manga", "Solo Leveling", [
  // --- Faciles (5) ---
  { id: "solo-f1", d: 1, t: "De quel type d'œuvre coréenne Solo Leveling est-il d'abord issu ?", a: "Un webtoon", x: ["Un film", "Une pièce de théâtre", "Un jeu de société"], acc: ["webtoon", "un webtoon", "manhwa"] },
  { id: "solo-f2", d: 1, t: "Comment s'appelle le héros de Solo Leveling ?", a: "Sung Jinwoo", x: ["Cha Hae-in", "Go Gun-hee", "Baek Yoonho"], acc: ["sung jinwoo", "jinwoo", "jin-woo"] },
  { id: "solo-f3", d: 1, t: "Au début, quel est le niveau de Jinwoo parmi les chasseurs ?", a: "Le plus faible", x: ["Le plus fort", "Un niveau moyen", "Chasseur retraité"], acc: ["le plus faible", "faible", "e-rank"] },
  { id: "solo-f4", d: 1, t: "Par quoi les chasseurs accèdent-ils aux donjons remplis de monstres ?", a: "Des portails", x: ["Des trains", "Des bateaux", "Des fusées"], acc: ["portails", "portes", "gates"] },
  { id: "solo-f5", d: 1, t: "Quel studio a réalisé l'anime Solo Leveling en 2024 ?", a: "A-1 Pictures", x: ["MAPPA", "Ufotable", "Toei Animation"], acc: ["a-1 pictures", "a1 pictures", "a-1"] },
  // --- Moyennes (10) ---
  { id: "solo-m1", d: 2, t: "Quel pouvoir permet à Jinwoo de progresser comme dans un jeu vidéo ?", a: "Le Système", x: ["La magie noire", "Un artefact ancien", "Une potion"], acc: ["systeme", "le systeme", "système"] },
  { id: "solo-m2", d: 2, t: "Quel titre Jinwoo finit-il par porter, maître d'une armée d'ombres ?", a: "Le Monarque des Ombres", x: ["Le Roi des Dragons", "L'Empereur du Feu", "Le Seigneur des Portails"], acc: ["monarque des ombres", "shadow monarch", "monarque"] },
  { id: "solo-m3", d: 2, t: "Que fait Jinwoo des ennemis puissants qu'il vainc ?", a: "Il les transforme en ombres à ses ordres", x: ["Il les emprisonne", "Il les vend", "Il les soigne"], acc: ["les transforme en ombres", "ombres", "armee d'ombres"] },
  { id: "solo-m4", d: 2, t: "Comment classe-t-on la puissance des chasseurs, de E jusqu'au sommet ?", a: "Par rangs de E à S", x: ["Par étoiles de 1 à 10", "Par couleurs", "Par âge"], acc: ["rangs", "e a s", "rang s"] },
  { id: "solo-m5", d: 2, t: "Comment s'appelle la chasseuse de rang S capable de « sentir » les chasseurs ?", a: "Cha Hae-in", x: ["Sung Jin-ah", "Lee Joohee", "Yoo Soohyun"], acc: ["cha hae-in", "hae-in", "cha"] },
  { id: "solo-m6", d: 2, t: "Quel mot Jinwoo prononce-t-il pour faire surgir ses ombres ?", a: "Lève-toi", x: ["Disparais", "Attaque", "Repose"], acc: ["leve-toi", "arise", "lève-toi"] },
  { id: "solo-m7", d: 2, t: "Dans quel pays se déroule principalement Solo Leveling ?", a: "La Corée du Sud", x: ["Le Japon", "La Chine", "Les États-Unis"], acc: ["coree du sud", "corée", "coree"] },
  { id: "solo-m8", d: 2, t: "Où Jinwoo a-t-il obtenu son pouvoir, après avoir failli mourir ?", a: "Dans un double donjon", x: ["Dans un hôpital", "Dans une forêt", "Dans une école"], acc: ["double donjon", "donjon"] },
  { id: "solo-m9", d: 2, t: "Comment s'appelle le premier chevalier-ombre majeur de Jinwoo ?", a: "Igris", x: ["Beru", "Tank", "Iron"], acc: ["igris"] },
  { id: "solo-m10", d: 2, t: "Comment appelle-t-on les organisations qui régissent le métier de chasseur ?", a: "Les guildes", x: ["Les syndicats", "Les clans ninja", "Les écoles de magie"], acc: ["guildes", "guildes de chasseurs", "guilde"] },
  // --- Dures (15) ---
  { id: "solo-d1", d: 3, t: "Qui a écrit le roman web original de Solo Leveling ?", a: "Chugong", x: ["DUBU", "Boichi", "SIU"], acc: ["chugong"] },
  { id: "solo-d2", d: 3, t: "Quel illustrateur, décédé en 2022, a dessiné le webtoon Solo Leveling ?", a: "Jang Sung-rak", x: ["Chugong", "Yusuke Murata", "SIU"], acc: ["jang sung-rak", "dubu", "jang sung rak"] },
  { id: "solo-d3", d: 3, t: "Comment s'appelle le roi des fourmis, devenu l'une des ombres les plus puissantes ?", a: "Beru", x: ["Igris", "Tank", "Iron"], acc: ["beru"] },
  { id: "solo-d4", d: 3, t: "Sur quelle île se déroule le grand raid contre le roi des fourmis ?", a: "L'île de Jeju", x: ["L'île de Nami", "L'île d'Okinawa", "L'île de Busan"], acc: ["jeju", "ile de jeju"] },
  { id: "solo-d5", d: 3, t: "Comment s'appelle le président de l'Association des chasseurs coréenne ?", a: "Go Gun-hee", x: ["Choi Jong-in", "Baek Yoonho", "Woo Jinchul"], acc: ["go gun-hee", "gun-hee"] },
  { id: "solo-d6", d: 3, t: "Comment s'appelle le maître de la guilde du Tigre Blanc, capable de se changer en bête ?", a: "Baek Yoonho", x: ["Choi Jong-in", "Go Gun-hee", "Woo Jinchul"], acc: ["baek yoonho", "yoonho"] },
  { id: "solo-d7", d: 3, t: "Quelle maladie plonge la mère de Jinwoo dans un long sommeil ?", a: "Le Sommeil éternel", x: ["La peste", "Le coma glacé", "La fièvre des portails"], acc: ["sommeil eternel", "sommeil éternel", "eternal sleep"] },
  { id: "solo-d8", d: 3, t: "Comment s'appelle la petite sœur de Jinwoo ?", a: "Sung Jin-ah", x: ["Cha Hae-in", "Lee Joohee", "Yoo Soohyun"], acc: ["jin-ah", "sung jin-ah"] },
  { id: "solo-d9", d: 3, t: "Comment s'appelle l'ancien Monarque des Ombres qui lègue son pouvoir à Jinwoo ?", a: "Ashborn", x: ["Antares", "Kamish", "Beru"], acc: ["ashborn"] },
  { id: "solo-d10", d: 3, t: "Quel puissant dragon, tué des années plus tôt, est une légende chez les chasseurs ?", a: "Kamish", x: ["Antares", "Ashborn", "Igris"], acc: ["kamish"] },
  { id: "solo-d11", d: 3, t: "Comment appelle-t-on l'armée que Jinwoo commande ?", a: "L'armée des ombres", x: ["La légion de feu", "La garde royale", "Le clan des portails"], acc: ["armee des ombres", "shadow army"] },
  { id: "solo-d12", d: 3, t: "Comment s'appelle le jeune héritier de guilde qui devient l'ami loyal de Jinwoo ?", a: "Yoo Jin-ho", x: ["Choi Jong-in", "Baek Yoonho", "Woo Jinchul"], acc: ["yoo jin-ho", "jin-ho"] },
  { id: "solo-d13", d: 3, t: "Comment s'appelle le mage de rang S, maître de la guilde des Chasseurs ?", a: "Choi Jong-in", x: ["Baek Yoonho", "Go Gun-hee", "Yoo Jin-ho"], acc: ["choi jong-in", "jong-in"] },
  { id: "solo-d14", d: 3, t: "Comment appelle-t-on les entités cosmiques qui s'opposent aux Monarques ?", a: "Les Souverains", x: ["Les Titans", "Les Anciens", "Les Gardiens"], acc: ["souverains", "rulers", "les souverains"] },
  { id: "solo-d15", d: 3, t: "Quel rang très rare désigne les chasseurs les plus puissants, au-dessus du rang S ?", a: "Le rang national", x: ["Le rang X", "Le rang or", "Le rang oméga"], acc: ["rang national", "national level", "niveau national"] },
  // --- Pro (20) ---
  { id: "solo-p1", d: 4, t: "En quelle année le roman web Solo Leveling a-t-il commencé à paraître ?", a: "2016", x: ["2010", "2020", "2023"], acc: ["2016"] },
  { id: "solo-p2", d: 4, t: "Quel sous-titre porte la deuxième saison de l'anime, sortie en 2025 ?", a: "Arise from the Shadow", x: ["Rise of the Monarch", "Shadow Army", "The Final Gate"], acc: ["arise from the shadow", "arise"] },
  { id: "solo-p3", d: 4, t: "Comment s'appelle le grand dragon, Monarque de la Destruction, ennemi ultime ?", a: "Antares", x: ["Kamish", "Ashborn", "Beru"], acc: ["antares"] },
  { id: "solo-p4", d: 4, t: "Comment s'appelle l'ombre canine à plusieurs têtes de Jinwoo ?", a: "Tank", x: ["Igris", "Beru", "Iron"], acc: ["tank"] },
  { id: "solo-p5", d: 4, t: "Comment s'appelle le temple du double donjon où Jinwoo reçoit le Système ?", a: "Le temple de Cartenon", x: ["Le temple de Jeju", "Le temple du Dragon", "Le donjon rouge"], acc: ["cartenon", "temple de cartenon"] },
  { id: "solo-p6", d: 4, t: "Que doit respecter Jinwoo dans le double donjon, sous peine de mort ?", a: "Les commandements des statues", x: ["Le silence total", "Un compte à rebours", "Le jeûne"], acc: ["commandements des statues", "commandements", "statues"] },
  { id: "solo-p7", d: 4, t: "Quel parfum Cha Hae-in perçoit-elle chez Jinwoo, contrairement aux autres chasseurs ?", a: "Un parfum agréable", x: ["Une odeur de soufre", "Aucune odeur", "Une odeur de fumée"], acc: ["parfum agreable", "bonne odeur", "agreable"] },
  { id: "solo-p8", d: 4, t: "Quel métier Jinwoo exerce-t-il malgré sa faiblesse, pour payer les soins de sa mère ?", a: "Chasseur de donjons", x: ["Médecin", "Professeur", "Cuisinier"], acc: ["chasseur", "chasseur de donjons"] },
  { id: "solo-p9", d: 4, t: "Comment s'appelle le père de Jinwoo, chasseur disparu dans un portail ?", a: "Sung Il-hwan", x: ["Go Gun-hee", "Choi Jong-in", "Baek Yoonho"], acc: ["sung il-hwan", "il-hwan"] },
  { id: "solo-p10", d: 4, t: "Que le Système attribue-t-il à Jinwoo pour le faire progresser ?", a: "Des quêtes et de l'expérience", x: ["Des cartes à collectionner", "Des diplômes", "Des médailles"], acc: ["quetes et experience", "quetes", "experience"] },
  { id: "solo-p11", d: 4, t: "Quelle classe cachée le Système attribue-t-il d'abord à Jinwoo ?", a: "Assassin", x: ["Mage", "Tank", "Archer"], acc: ["assassin", "classe assassin"] },
  { id: "solo-p12", d: 4, t: "Comment s'appelle l'enquêteur bras droit de Go Gun-hee à l'Association ?", a: "Woo Jinchul", x: ["Yoo Jin-ho", "Choi Jong-in", "Baek Yoonho"], acc: ["woo jinchul", "jinchul"] },
  { id: "solo-p13", d: 4, t: "De quelle couleur est l'aura des ombres et du pouvoir de Jinwoo ?", a: "Violette", x: ["Rouge", "Dorée", "Blanche"], acc: ["violette", "violet", "mauve"] },
  { id: "solo-p14", d: 4, t: "Comment s'appelle la guérisseuse, amie du début, traumatisée par le double donjon ?", a: "Lee Joohee", x: ["Cha Hae-in", "Sung Jin-ah", "Yoo Soohyun"], acc: ["lee joohee", "joohee"] },
  { id: "solo-p15", d: 4, t: "Quelle arme de prédilection Jinwoo manie-t-il souvent ?", a: "Une dague", x: ["Un arc", "Une lance", "Un marteau"], acc: ["dague", "une dague", "poignard"] },
  { id: "solo-p16", d: 4, t: "Comment appelle-t-on les puissantes entités dont Jinwoo devient l'un des chefs ?", a: "Les Monarques", x: ["Les Souverains", "Les Chasseurs", "Les Gardiens"], acc: ["monarques", "les monarques", "monarchs"] },
  { id: "solo-p17", d: 4, t: "De quel pays viennent des chasseurs de rang S lors de l'arc de Jeju ?", a: "Le Japon", x: ["La Chine", "Les États-Unis", "La Russie"], acc: ["japon", "le japon"] },
  { id: "solo-p18", d: 4, t: "Quel gigantesque insecte-roi Jinwoo affronte-t-il sur l'île de Jeju ?", a: "Le roi des fourmis", x: ["Le roi des araignées", "Le roi des scorpions", "Le roi des serpents"], acc: ["roi des fourmis", "ant king", "fourmis"] },
  { id: "solo-p19", d: 4, t: "Quel type de créature est Kamish, la légende que peu ont pu vaincre ?", a: "Un dragon", x: ["Un golem", "Un démon", "Un kraken"], acc: ["dragon", "un dragon"] },
  { id: "solo-p20", d: 4, t: "Quel pouvoir unique distingue Jinwoo de tous les autres chasseurs ?", a: "Il peut monter de niveau", x: ["Il peut voler", "Il est immortel de naissance", "Il lit dans les pensées"], acc: ["monter de niveau", "leveling", "level up"] },
]);
