import { universe } from "../_build";

export const spyfamily = universe("manga", "Spy x Family", [
  // --- Faciles (5) ---
  { id: "spy-f1", d: 1, t: "Que cache la famille Forger de Spy x Family ?", a: "Chacun a un secret", x: ["Ils sont richissimes", "Ils sont célèbres", "Ils sont extraterrestres"], acc: ["chacun a un secret", "des secrets"] },
  { id: "spy-f2", d: 1, t: "Quel est le vrai métier du père, Loid Forger ?", a: "Espion", x: ["Médecin", "Cuisinier", "Facteur"], acc: ["espion"] },
  { id: "spy-f3", d: 1, t: "Quel pouvoir la petite Anya possède-t-elle en secret ?", a: "Lire dans les pensées", x: ["Voler", "Devenir invisible", "Voir le futur"], acc: ["lire dans les pensees", "telepathie", "télépathie"] },
  { id: "spy-f4", d: 1, t: "Quel est le secret de la mère, Yor Forger ?", a: "Elle est tueuse à gages", x: ["Elle est chanteuse", "Elle est policière", "Elle est reine"], acc: ["tueuse a gages", "assassin", "tueuse"] },
  { id: "spy-f5", d: 1, t: "Comment s'appelle le grand chien blanc de la famille Forger ?", a: "Bond", x: ["Anya", "Loid", "Franky"], acc: ["bond"] },
  // --- Moyennes (10) ---
  { id: "spy-m1", d: 2, t: "Quel est le nom de code d'espion de Loid ?", a: "Twilight", x: ["Thorn", "Nightfall", "Shadow"], acc: ["twilight", "crepuscule"] },
  { id: "spy-m2", d: 2, t: "Comment se nomme la mission que Loid doit accomplir ?", a: "Opération Strix", x: ["Opération Owl", "Opération Eden", "Opération Bond"], acc: ["operation strix", "strix"] },
  { id: "spy-m3", d: 2, t: "D'où Loid a-t-il « recruté » Anya pour sa mission ?", a: "D'un orphelinat", x: ["D'une école privée", "D'un hôpital", "D'un cirque"], acc: ["orphelinat"] },
  { id: "spy-m4", d: 2, t: "Dans quelle prestigieuse école Loid doit-il faire entrer Anya ?", a: "L'académie Eden", x: ["Poudlard", "L'académie Berlint", "L'institut WISE"], acc: ["eden", "academie eden"] },
  { id: "spy-m5", d: 2, t: "Quel surnom Yor porte-t-elle en tant qu'assassin ?", a: "La Princesse Épine", x: ["La Veuve Noire", "La Rose de Fer", "Nightfall"], acc: ["princesse epine", "thorn princess", "ibara-hime"] },
  { id: "spy-m6", d: 2, t: "Quel aliment Anya adore-t-elle par-dessus tout ?", a: "Les cacahuètes", x: ["Les sushis", "Le chocolat", "Les ramen"], acc: ["cacahuetes", "cacahuètes"] },
  { id: "spy-m7", d: 2, t: "Quel proche de Yor travaille pour la police secrète, sans la savoir tueuse ?", a: "Son frère Yuri", x: ["Son père", "Son cousin", "Son oncle"], acc: ["yuri", "son frere yuri"] },
  { id: "spy-m8", d: 2, t: "Entre quels deux pays Loid tente-t-il d'éviter la guerre ?", a: "Westalis et Ostania", x: ["La France et l'Allemagne", "Le Nord et le Sud", "L'Est et l'Ouest de Berlin"], acc: ["westalis et ostania"] },
  { id: "spy-m9", d: 2, t: "Quel mangaka a créé Spy x Family ?", a: "Tatsuya Endo", x: ["Gege Akutami", "Koyoharu Gotouge", "Eiichiro Oda"], acc: ["tatsuya endo", "endo"] },
  { id: "spy-m10", d: 2, t: "En quelle année l'anime Spy x Family a-t-il été diffusé pour la première fois ?", a: "2022", x: ["2018", "2020", "2024"], acc: ["2022"] },
  // --- Dures (15) ---
  { id: "spy-d1", d: 3, t: "Quel métier de couverture Loid exerce-t-il auprès de ses voisins ?", a: "Psychiatre", x: ["Avocat", "Professeur", "Chirurgien"], acc: ["psychiatre"] },
  { id: "spy-d2", d: 3, t: "Quel homme politique reclus Loid doit-il approcher pour sa mission ?", a: "Donovan Desmond", x: ["Damian Desmond", "Henry Henderson", "Yuri Briar"], acc: ["donovan desmond", "donovan"] },
  { id: "spy-d3", d: 3, t: "Quel camarade de classe d'Anya, fils de sa cible, la fascine malgré leur rivalité ?", a: "Damian Desmond", x: ["Becky Blackbell", "Ewen Egeburg", "Bill Watkins"], acc: ["damian desmond", "damian"] },
  { id: "spy-d4", d: 3, t: "Quelles distinctions Anya doit-elle décrocher à l'école pour la réussite du plan ?", a: "Des Stella", x: ["Des Tonitrus", "Des médailles", "Des couronnes"], acc: ["stella", "stella stars", "etoiles"] },
  { id: "spy-d5", d: 3, t: "Comment nomme-t-on les mauvais points qui, cumulés, font renvoyer un élève d'Eden ?", a: "Des Tonitrus", x: ["Des Stella", "Des blâmes", "Des cartons rouges"], acc: ["tonitrus"] },
  { id: "spy-d6", d: 3, t: "Quelle riche petite fille devient la meilleure amie d'Anya à l'école ?", a: "Becky Blackbell", x: ["Yor Forger", "Fiona Frost", "Sylvia Sherwood"], acc: ["becky", "becky blackbell"] },
  { id: "spy-d7", d: 3, t: "Pour quelle agence de renseignement de Westalis Loid travaille-t-il ?", a: "WISE", x: ["Le SSS", "Le Jardin", "La CIA"], acc: ["wise"] },
  { id: "spy-d8", d: 3, t: "Quelle redoutable police secrète d'Ostania emploie Yuri ?", a: "Le SSS", x: ["WISE", "Le Jardin", "Le KGB"], acc: ["sss", "le sss"] },
  { id: "spy-d9", d: 3, t: "Pour quelle organisation d'assassins Yor exécute-t-elle ses contrats ?", a: "Le Jardin", x: ["WISE", "Le SSS", "Le Syndicat"], acc: ["jardin", "garden", "le jardin"] },
  { id: "spy-d10", d: 3, t: "Quel pouvoir le chien Bond possède-t-il ?", a: "Voir des bribes du futur", x: ["Lire les pensées", "Parler", "Devenir invisible"], acc: ["voir le futur", "bribes du futur"] },
  { id: "spy-d11", d: 3, t: "D'où provient Bond avant d'être adopté par la famille ?", a: "D'une expérience de laboratoire", x: ["D'un refuge classique", "D'un élevage", "D'un cirque"], acc: ["laboratoire", "experience de laboratoire"] },
  { id: "spy-d12", d: 3, t: "Quel informateur et ami de Loid l'aide avec gadgets et renseignements ?", a: "Franky", x: ["Yuri", "Henderson", "Bond"], acc: ["franky", "franky franklin"] },
  { id: "spy-d13", d: 3, t: "Quelle femme est la supérieure de Loid, surnommée « le Contrôleur » ?", a: "Sylvia Sherwood", x: ["Fiona Frost", "Yor Briar", "Becky Blackbell"], acc: ["sylvia sherwood", "sylvia", "handler"] },
  { id: "spy-d14", d: 3, t: "Quelle collègue espionne, au nom de code « Nightfall », est secrètement éprise de Loid ?", a: "Fiona Frost", x: ["Sylvia Sherwood", "Yor Forger", "Becky Blackbell"], acc: ["fiona frost", "fiona", "nightfall"] },
  { id: "spy-d15", d: 3, t: "Quel professeur d'Eden juge tout à l'aune de l'« élégance » ?", a: "Henry Henderson", x: ["Donovan Desmond", "Franky", "Yuri Briar"], acc: ["henderson", "henry henderson"] },
  // --- Pro (20) ---
  { id: "spy-p1", d: 4, t: "En quelle année le manga Spy x Family a-t-il commencé sa publication ?", a: "2019", x: ["2015", "2021", "2023"], acc: ["2019"] },
  { id: "spy-p2", d: 4, t: "Quels deux studios coproduisent l'anime Spy x Family ?", a: "Wit Studio et CloverWorks", x: ["MAPPA et Ufotable", "Bones et Trigger", "Madhouse et Pierrot"], acc: ["wit et cloverworks", "wit cloverworks"] },
  { id: "spy-p3", d: 4, t: "Quelle mimique narquoise d'Anya est devenue un mème très populaire ?", a: "Son sourire malicieux", x: ["Son clin d'œil", "Sa langue tirée", "Ses grosses larmes"], acc: ["sourire malicieux", "heh", "sourire narquois"] },
  { id: "spy-p4", d: 4, t: "Quelle onomatopée Anya lance-t-elle quand elle est tout excitée ?", a: "Waku waku", x: ["Nya nya", "Doki doki", "Pika pika"], acc: ["waku waku", "waku"] },
  { id: "spy-p5", d: 4, t: "Que sait-on du véritable passé de Loid ?", a: "C'est un orphelin de guerre", x: ["C'est un prince", "C'est un ancien policier", "C'est un acteur"], acc: ["orphelin de guerre"] },
  { id: "spy-p6", d: 4, t: "Quel emploi de bureau tout à fait ordinaire Yor occupe-t-elle en journée ?", a: "Employée de mairie", x: ["Infirmière", "Serveuse", "Bibliothécaire"], acc: ["employee de mairie", "mairie"] },
  { id: "spy-p7", d: 4, t: "Comment Anya décroche-t-elle sa toute première Stella ?", a: "En sauvant un enfant de la noyade", x: ["En gagnant un concours de maths", "En remportant une course", "En dessinant"], acc: ["sauvant un enfant", "noyade"] },
  { id: "spy-p8", d: 4, t: "Pourquoi Anya doit-elle se rapprocher de Damian pour la mission ?", a: "Pour atteindre son père Donovan", x: ["Parce qu'il est espion", "Parce qu'il est riche", "Parce qu'il triche"], acc: ["atteindre son pere", "donovan"] },
  { id: "spy-p9", d: 4, t: "Avec quel type d'arme Yor élimine-t-elle surtout ses cibles ?", a: "Des armes blanches", x: ["Un fusil de sniper", "Du poison seul", "Ses poings nus"], acc: ["armes blanches", "dagues", "aiguilles"] },
  { id: "spy-p10", d: 4, t: "Quel dessin animé d'espionnage Anya regarde-t-elle avec passion ?", a: "Bondman", x: ["Spy Kids", "Détective Conan", "Lupin"], acc: ["bondman"] },
  { id: "spy-p11", d: 4, t: "Dans quelle ville, capitale d'Ostania, vit la famille Forger ?", a: "Berlint", x: ["Westalis", "Eden", "Berlin"], acc: ["berlint"] },
  { id: "spy-p12", d: 4, t: "Quel titre d'élève d'élite, accordé après huit Stella, permettrait à Anya d'approcher les Desmond ?", a: "Imperial Scholar", x: ["Préfet", "Major de promo", "Délégué"], acc: ["imperial scholar", "erudit imperial"] },
  { id: "spy-p13", d: 4, t: "Comment s'intitule le film d'animation Spy x Family sorti fin 2023 ?", a: "Code: White", x: ["Code: Red", "Operation Strix", "Eden"], acc: ["code white", "code: white"] },
  { id: "spy-p14", d: 4, t: "À quel double genre Spy x Family appartient-il surtout ?", a: "Action et comédie", x: ["Horreur et drame", "Sport et romance", "Policier sombre"], acc: ["action et comedie", "comedie d'action"] },
  { id: "spy-p15", d: 4, t: "Quel trait de caractère excessif Yuri montre-t-il envers sa sœur Yor ?", a: "Une dévotion obsessionnelle", x: ["De la haine", "De l'indifférence", "De la peur"], acc: ["devotion obsessionnelle", "obsession"] },
  { id: "spy-p16", d: 4, t: "Quelle règle d'or régit la vie de la famille Forger ?", a: "Chacun ignore le secret des autres", x: ["Ils se disent tout", "Ils vivent séparés", "Ils changent de nom chaque jour"], acc: ["ignore le secret des autres"] },
  { id: "spy-p17", d: 4, t: "D'où vient le pouvoir de télépathie d'Anya ?", a: "D'une expérience secrète", x: ["D'un héritage familial", "D'un accident de voiture", "D'un vœu magique"], acc: ["experience secrete", "experience"] },
  { id: "spy-p18", d: 4, t: "Quel est le but ultime de la mission Strix menée par Loid ?", a: "Maintenir la paix", x: ["Renverser un roi", "Voler un trésor", "Conquérir Eden"], acc: ["maintenir la paix", "paix"] },
  { id: "spy-p19", d: 4, t: "Quel poste occupe Sylvia Sherwood au sein de WISE ?", a: "Cheffe des opérations", x: ["Simple recrue", "Cuisinière", "Institutrice"], acc: ["cheffe des operations", "handler", "controleur"] },
  { id: "spy-p20", d: 4, t: "Anya a nommé le chien « Bond » en référence à quoi ?", a: "Un dessin animé d'espions", x: ["Un chanteur célèbre", "Un plat", "Un jeu vidéo"], acc: ["dessin anime d'espions", "bondman"] },
]);
