import { universe } from "../_build";

export const tokyoghoul = universe("manga", "Tokyo Ghoul", [
  // --- Faciles (5) ---
  { id: "tg-f1", d: 1, t: "De quoi les goules se nourrissent-elles dans Tokyo Ghoul ?", a: "De chair humaine", x: ["De sang animal", "De légumes", "D'énergie électrique"], acc: ["chair humaine", "humains"] },
  { id: "tg-f2", d: 1, t: "Comment se nomme l'étudiant héros de Tokyo Ghoul ?", a: "Ken Kaneki", x: ["Touka Kirishima", "Renji Yomo", "Hideyoshi Nagachika"], acc: ["kaneki", "ken kaneki"] },
  { id: "tg-f3", d: 1, t: "Que devient Kaneki après une transplantation d'organes ?", a: "Une demi-goule", x: ["Un vampire", "Un robot", "Un fantôme"], acc: ["demi-goule", "half-ghoul", "hybride"] },
  { id: "tg-f4", d: 1, t: "De quelle couleur les cheveux de Kaneki deviennent-ils après ses tortures ?", a: "Blancs", x: ["Rouges", "Verts", "Bleus"], acc: ["blancs", "blanc"] },
  { id: "tg-f5", d: 1, t: "À quel genre sombre Tokyo Ghoul appartient-il ?", a: "L'horreur", x: ["La comédie", "Le sport", "La romance légère"], acc: ["horreur", "dark fantasy"] },
  // --- Moyennes (10) ---
  { id: "tg-m1", d: 2, t: "Comment nomme-t-on l'organe-arme que les goules déploient au combat ?", a: "Le kagune", x: ["Le kakugan", "Le quinque", "Le byakugan"], acc: ["kagune"] },
  { id: "tg-m2", d: 2, t: "Comment appelle-t-on les yeux noirs aux iris rouges des goules ?", a: "Le kakugan", x: ["Le kagune", "Le sharingan", "Le rinnegan"], acc: ["kakugan"] },
  { id: "tg-m3", d: 2, t: "Quel café sert de refuge aux goules pacifiques ?", a: "L'Anteiku", x: ["Le Re:", "Le Helter Skelter", "Le Big Madam"], acc: ["anteiku"] },
  { id: "tg-m4", d: 2, t: "Quelle serveuse goule de l'Anteiku devient proche de Kaneki ?", a: "Touka", x: ["Rize", "Eto", "Hinami"], acc: ["touka"] },
  { id: "tg-m5", d: 2, t: "Quelle goule gourmande est à l'origine de la transformation de Kaneki ?", a: "Rize", x: ["Touka", "Eto", "Itori"], acc: ["rize", "rize kamishiro"] },
  { id: "tg-m6", d: 2, t: "Quelle organisation traque et extermine les goules ?", a: "Le CCG", x: ["L'Aogiri", "L'Anteiku", "Le clan V"], acc: ["ccg", "le ccg"] },
  { id: "tg-m7", d: 2, t: "De quoi sont fabriquées les armes « quinque » des enquêteurs ?", a: "Des kagune de goules", x: ["Du fer forgé", "De l'argent béni", "Du bois sacré"], acc: ["kagune de goules", "kagune"] },
  { id: "tg-m8", d: 2, t: "Quel mangaka a créé Tokyo Ghoul ?", a: "Sui Ishida", x: ["Tsugumi Ohba", "Kentaro Miura", "Gege Akutami"], acc: ["sui ishida", "ishida"] },
  { id: "tg-m9", d: 2, t: "En quelle année l'anime Tokyo Ghoul a-t-il été diffusé ?", a: "2014", x: ["2010", "2017", "2020"], acc: ["2014"] },
  { id: "tg-m10", d: 2, t: "Dans quelle ville l'action de Tokyo Ghoul se déroule-t-elle ?", a: "Tokyo", x: ["Osaka", "Kyoto", "Yokohama"], acc: ["tokyo"] },
  // --- Dures (15) ---
  { id: "tg-d1", d: 3, t: "Quel tortionnaire de l'Aogiri force Kaneki à compter à rebours durant son supplice ?", a: "Jason", x: ["Arima", "Amon", "Tsukiyama"], acc: ["jason", "yamori"] },
  { id: "tg-d2", d: 3, t: "Quel calcul obsédant Kaneki répète-t-il durant sa torture ?", a: "Mille moins sept", x: ["Sept fois huit", "La racine de deux", "Cent moins un"], acc: ["mille moins sept", "1000 moins 7"] },
  { id: "tg-d3", d: 3, t: "Quelle organisation extrémiste de goules kidnappe Kaneki ?", a: "L'Arbre Aogiri", x: ["Le CCG", "L'Anteiku", "Le clan V"], acc: ["aogiri", "arbre aogiri"] },
  { id: "tg-d4", d: 3, t: "Quel vieux gérant bienveillant dirige l'Anteiku ?", a: "Yoshimura", x: ["Yomo", "Uta", "Itori"], acc: ["yoshimura"] },
  { id: "tg-d5", d: 3, t: "Comment se nomme le meilleur ami humain de Kaneki ?", a: "Hide", x: ["Nishiki", "Banjo", "Amon"], acc: ["hide", "hideyoshi"] },
  { id: "tg-d6", d: 3, t: "Quel surnom d'oiseau les goules donnent-elles aux enquêteurs du CCG ?", a: "Des colombes", x: ["Des corbeaux", "Des faucons", "Des vautours"], acc: ["colombes", "doves"] },
  { id: "tg-d7", d: 3, t: "Quel enquêteur du CCG, rival récurrent de Kaneki, veut venger son mentor ?", a: "Amon", x: ["Arima", "Jason", "Tsukiyama"], acc: ["amon", "koutarou amon"] },
  { id: "tg-d8", d: 3, t: "Quel enquêteur, surnommé « la Faucheuse du CCG », est réputé invincible ?", a: "Arima", x: ["Amon", "Mado", "Juuzou"], acc: ["arima", "kishou arima"] },
  { id: "tg-d9", d: 3, t: "Quelle goule dandy, surnommée « le Gourmet », s'obsède pour Kaneki ?", a: "Tsukiyama", x: ["Jason", "Nishiki", "Yomo"], acc: ["tsukiyama"] },
  { id: "tg-d10", d: 3, t: "Combien de types de kagune différents existe-t-il ?", a: "Quatre", x: ["Deux", "Six", "Dix"], acc: ["4", "quatre"] },
  { id: "tg-d11", d: 3, t: "Lequel de ces mots désigne un type de kagune ?", a: "Ukaku", x: ["Ukiyo", "Uchiha", "Usagi"], acc: ["ukaku"] },
  { id: "tg-d12", d: 3, t: "Quelle est la classe de danger la plus élevée attribuée à une goule ?", a: "SSS", x: ["SS", "S", "A"], acc: ["sss"] },
  { id: "tg-d13", d: 3, t: "Quelle goule se cache derrière le monstre surnommé « la Chouette borgne » ?", a: "Eto", x: ["Touka", "Rize", "Itori"], acc: ["eto"] },
  { id: "tg-d14", d: 3, t: "Quel jeune enquêteur excentrique, couvert de coutures, se bat avec allégresse ?", a: "Juuzou", x: ["Amon", "Arima", "Mado"], acc: ["juuzou", "suzuya"] },
  { id: "tg-d15", d: 3, t: "Qu'ont de particulier les goules « borgnes » comme Kaneki ?", a: "Un seul œil de goule", x: ["Deux kagune", "Aucun kagune", "Une force nulle"], acc: ["un seul oeil", "borgne"] },
  // --- Pro (20) ---
  { id: "tg-p1", d: 4, t: "Quel surnom la goule Rize porte-t-elle pour sa gloutonnerie ?", a: "La Gloutonne", x: ["Le Gourmet", "La Chouette", "La Faucheuse"], acc: ["gloutonne", "binge eater"] },
  { id: "tg-p2", d: 4, t: "Comment s'intitule la suite du manga, où Kaneki a perdu la mémoire ?", a: "Tokyo Ghoul:re", x: ["Tokyo Ghoul Zero", "Tokyo Ghoul X", "Tokyo Ghoul Next"], acc: ["tokyo ghoul:re", "re"] },
  { id: "tg-p3", d: 4, t: "Sous quel nom Kaneki, amnésique, réapparaît-il dans :re ?", a: "Haise Sasaki", x: ["Ken Kirishima", "Arata Kirishima", "Kishou Arima"], acc: ["haise sasaki", "haise", "sasaki"] },
  { id: "tg-p4", d: 4, t: "Quelle escouade d'enquêteurs mi-goules Sasaki dirige-t-il dans :re ?", a: "Les Quinx", x: ["Les Quinque", "Les Doves", "Les S3"], acc: ["quinx", "les quinx"] },
  { id: "tg-p5", d: 4, t: "Quel insecte hante Kaneki, en écho à son kagune de type rinkaku ?", a: "Le mille-pattes", x: ["L'araignée", "La mante", "La sauterelle"], acc: ["mille-pattes", "centipede"] },
  { id: "tg-p6", d: 4, t: "De quel type est le kagune de Kaneki, aux tentacules régénérants ?", a: "Rinkaku", x: ["Ukaku", "Koukaku", "Bikaku"], acc: ["rinkaku"] },
  { id: "tg-p7", d: 4, t: "Quel spin-off préquel suit un jeune Arima et Taishi Fura ?", a: "Tokyo Ghoul: Jack", x: ["Tokyo Ghoul:re", "Tokyo Ghoul Zero", "Tokyo Ghoul Days"], acc: ["tokyo ghoul jack", "jack"] },
  { id: "tg-p8", d: 4, t: "Quel artiste tatoué fabrique les masques des goules, dont celui de Kaneki ?", a: "Uta", x: ["Yomo", "Nishiki", "Banjo"], acc: ["uta"] },
  { id: "tg-p9", d: 4, t: "Quel accessoire couvre l'un des yeux du masque emblématique de Kaneki ?", a: "Un cache-œil", x: ["Une corne", "Une plume", "Un bec"], acc: ["cache-oeil", "eyepatch", "cache oeil"] },
  { id: "tg-p10", d: 4, t: "Quel médecin a greffé en secret les organes de Rize à Kaneki ?", a: "Le docteur Kanou", x: ["Le docteur Mado", "Le docteur Akihiro", "Le docteur Arima"], acc: ["kanou", "docteur kanou"] },
  { id: "tg-p11", d: 4, t: "Quel générique culte de Tokyo Ghoul est chanté par TK ?", a: "Unravel", x: ["Silhouette", "Guren no Yumiya", "Blue Bird"], acc: ["unravel"] },
  { id: "tg-p12", d: 4, t: "Que signifie le sigle CCG, l'organisation anti-goules ?", a: "Commission de Contrôle des Goules", x: ["Corps Central de la Garde", "Cellule Criminelle Générale", "Comité de Chasse Génétique"], acc: ["commission de controle des goules"] },
  { id: "tg-p13", d: 4, t: "Quel titre de meneur des goules Kaneki finit-il par endosser ?", a: "Le Roi borgne", x: ["Le Gourmet", "La Faucheuse", "Le Roi-Liche"], acc: ["roi borgne", "one-eyed king"] },
  { id: "tg-p14", d: 4, t: "Dans quel magazine seinen Tokyo Ghoul a-t-il été publié ?", a: "Young Jump", x: ["Weekly Shonen Jump", "Shonen Magazine", "Ribon"], acc: ["young jump"] },
  { id: "tg-p15", d: 4, t: "Quelle jeune goule orpheline Kaneki prend-il sous son aile à l'Anteiku ?", a: "Hinami", x: ["Touka", "Eto", "Rize"], acc: ["hinami"] },
  { id: "tg-p16", d: 4, t: "Quel enquêteur obsédé par les quinques, mentor d'Amon, est tué par les goules ?", a: "Mado", x: ["Arima", "Juuzou", "Kanou"], acc: ["mado", "kureo mado"] },
  { id: "tg-p17", d: 4, t: "Quelle goule, étudiant plus âgé, devient un allié réticent de Kaneki ?", a: "Nishiki", x: ["Tsukiyama", "Yomo", "Banjo"], acc: ["nishiki"] },
  { id: "tg-p18", d: 4, t: "Comment nomme-t-on l'organe qui produit et stocke le kagune ?", a: "Le kakuhou", x: ["Le kakugan", "Le quinque", "Le byakugan"], acc: ["kakuhou"] },
  { id: "tg-p19", d: 4, t: "Quelles cellules particulières, mesurées par le CCG, trahissent la nature d'une goule ?", a: "Les cellules RC", x: ["Les globules rouges", "Les cellules souches", "Les neurones"], acc: ["cellules rc", "rc"] },
  { id: "tg-p20", d: 4, t: "Sous quel pseudonyme d'écrivaine à succès la goule Eto se cache-t-elle ?", a: "Sen Takatsuki", x: ["Rize Kamishiro", "Itori", "Hinami"], acc: ["sen takatsuki", "takatsuki"] },
]);
