import { universe } from "../_build";

export const cinemafrancais = universe("france", "Cinéma français", [
  // --- Faciles (5) ---
  { id: "frcine-f1", d: 1, t: "Quel film de 2001 suit une jeune serveuse au grand cœur dans Montmartre ?", a: "Le Fabuleux Destin d'Amélie Poulain", x: ["Intouchables", "La Môme", "Le Dîner de cons"], acc: ["amélie poulain", "amélie"] },
  { id: "frcine-f2", d: 1, t: "Quelle comédie de 2011 réunit un riche tétraplégique et son aide de banlieue ?", a: "Intouchables", x: ["Le Prénom", "Le Dîner de cons", "Les Ch'tis"] },
  { id: "frcine-f3", d: 1, t: "Quel acteur incarne les héros gaffeurs de « La Chèvre » et « Les Compères » ?", a: "Pierre Richard", x: ["Louis de Funès", "Jean Lefebvre", "Michel Galabru"] },
  { id: "frcine-f4", d: 1, t: "Quel comique culte joue le maréchal des logis dans « Le Gendarme de Saint-Tropez » ?", a: "Louis de Funès", x: ["Michel Serrault", "Pierre Richard", "Jean Lefebvre"] },
  { id: "frcine-f5", d: 1, t: "Quelle actrice a incarné Édith Piaf dans « La Môme » ?", a: "Marion Cotillard", x: ["Audrey Tautou", "Juliette Binoche", "Cécile de France"] },
  // --- Moyennes (10) ---
  { id: "frcine-m1", d: 2, t: "Quel film de 1966 avec Bourvil et de Funès fut longtemps le plus gros succès du cinéma français ?", a: "La Grande Vadrouille", x: ["Le Corniaud", "La Folie des grandeurs", "Rabbi Jacob"] },
  { id: "frcine-m2", d: 2, t: "Quel film de 2008 sur un professeur et sa classe difficile a remporté la Palme d'or ?", a: "Entre les murs", x: ["La Journée de la jupe", "Les Choristes", "Le Maître d'école"] },
  { id: "frcine-m3", d: 2, t: "Quel film de 2004 suit un surveillant qui monte une chorale dans un internat ?", a: "Les Choristes", x: ["Entre les murs", "Être et avoir", "Le Petit Nicolas"] },
  { id: "frcine-m4", d: 2, t: "Quelle comédie de 2008 envoie un postier du Sud dans le Nord de la France ?", a: "Bienvenue chez les Ch'tis", x: ["Rien à déclarer", "La Ch'tite Famille", "Camping"] },
  { id: "frcine-m5", d: 2, t: "Quel réalisateur a signé « Bienvenue chez les Ch'tis » et y joue Antoine ?", a: "Dany Boon", x: ["Kad Merad", "Franck Dubosc", "Gad Elmaleh"] },
  { id: "frcine-m6", d: 2, t: "Quelle comédie de 2014 met en scène un couple bourgeois et ses quatre gendres de cultures différentes ?", a: "Qu'est-ce qu'on a fait au Bon Dieu ?", x: ["Le Prénom", "La Vérité si je mens", "Neuilly sa mère"], acc: ["qu'est-ce qu'on a fait au bon dieu"] },
  { id: "frcine-m7", d: 2, t: "Quel acteur au visage buriné incarne le gangster de « L'Armée des ombres » et du « Clan des Siciliens » ?", a: "Lino Ventura", x: ["Alain Delon", "Jean Gabin", "Jean-Paul Belmondo"] },
  { id: "frcine-m8", d: 2, t: "Quel acteur à la classe froide incarne « Le Samouraï » de Melville ?", a: "Alain Delon", x: ["Jean-Paul Belmondo", "Lino Ventura", "Yves Montand"] },
  { id: "frcine-m9", d: 2, t: "Quel acteur cascadeur et charmeur est surnommé « Bébel » ?", a: "Jean-Paul Belmondo", x: ["Alain Delon", "Jean Gabin", "Lino Ventura"], acc: ["belmondo", "bébel"] },
  { id: "frcine-m10", d: 2, t: "Quel film de 1966 de Claude Lelouch, palmé à Cannes, a pour thème une histoire d'amour ?", a: "Un homme et une femme", x: ["Le Mépris", "Jules et Jim", "Hiroshima mon amour"] },
  // --- Dures (15) ---
  { id: "frcine-d1", d: 3, t: "Quel mouvement du cinéma français des années 60 réunit Godard et Truffaut ?", a: "La Nouvelle Vague", x: ["Le Réalisme poétique", "La Qualité française", "Le Cinéma du look"], acc: ["nouvelle vague"] },
  { id: "frcine-d2", d: 3, t: "Quel film de 1960 de Godard, avec Belmondo, est un manifeste de la Nouvelle Vague ?", a: "À bout de souffle", x: ["Le Mépris", "Pierrot le Fou", "Les 400 Coups"] },
  { id: "frcine-d3", d: 3, t: "Quel film de 1959 de François Truffaut suit l'enfant Antoine Doinel ?", a: "Les 400 Coups", x: ["Jules et Jim", "Baisers volés", "La Nuit américaine"] },
  { id: "frcine-d4", d: 3, t: "Quel cinéaste a réalisé « Le Mépris » et « Pierrot le Fou » ?", a: "Jean-Luc Godard", x: ["François Truffaut", "Claude Chabrol", "Éric Rohmer"] },
  { id: "frcine-d5", d: 3, t: "Quel réalisateur a signé « Les Tontons flingueurs », aux dialogues d'Audiard ?", a: "Georges Lautner", x: ["Henri Verneuil", "Gérard Oury", "Claude Zidi"] },
  { id: "frcine-d6", d: 3, t: "Quel dialoguiste est célèbre pour ses répliques dans « Les Tontons flingueurs » ?", a: "Michel Audiard", x: ["Francis Veber", "Jean-Loup Dabadie", "Henri Jeanson"] },
  { id: "frcine-d7", d: 3, t: "Quel réalisateur a signé « La Grande Vadrouille » et « Le Corniaud » ?", a: "Gérard Oury", x: ["Georges Lautner", "Claude Zidi", "Édouard Molinaro"] },
  { id: "frcine-d8", d: 3, t: "Quel film de 1995 de Mathieu Kassovitz suit trois jeunes de banlieue après une bavure ?", a: "La Haine", x: ["L'Esquive", "Banlieue 13", "Les Misérables"] },
  { id: "frcine-d9", d: 3, t: "Quel film de 1990 de Rappeneau adapte la pièce de Rostand avec Depardieu ?", a: "Cyrano de Bergerac", x: ["Germinal", "Le Hussard sur le toit", "Jean de Florette"] },
  { id: "frcine-d10", d: 3, t: "Quel film de Claude Berri, d'après Pagnol, met en scène un bossu et une source bouchée ?", a: "Jean de Florette", x: ["La Gloire de mon père", "Le Château de ma mère", "Marius et Jeannette"] },
  { id: "frcine-d11", d: 3, t: "Quel réalisateur a signé « Le Grand Bleu » et « Léon » ?", a: "Luc Besson", x: ["Jean-Jacques Beineix", "Leos Carax", "Jean-Pierre Jeunet"] },
  { id: "frcine-d12", d: 3, t: "Quel réalisateur a signé « Amélie Poulain » et « Delicatessen » ?", a: "Jean-Pierre Jeunet", x: ["Luc Besson", "Jean-Jacques Beineix", "Cédric Klapisch"] },
  { id: "frcine-d13", d: 3, t: "Quel film français de 2011, muet et en noir et blanc, a triomphé aux Oscars ?", a: "The Artist", x: ["Un homme et une femme", "La Môme", "OSS 117"] },
  { id: "frcine-d14", d: 3, t: "Quel espion français ringard et machiste est incarné par Jean Dujardin ?", a: "OSS 117", x: ["Hubert Bonisseur", "Le Gendarme", "Fantômas"], acc: ["oss 117"] },
  { id: "frcine-d15", d: 3, t: "Quel réalisateur a signé « De battre mon cœur s'est arrêté » et « Un prophète » ?", a: "Jacques Audiard", x: ["Michel Audiard", "Xavier Beauvois", "Cédric Kahn"] },
  // --- Pro (20) ---
  { id: "frcine-p1", d: 4, t: "Quel prix récompense le meilleur film au Festival de Cannes ?", a: "La Palme d'or", x: ["Le Lion d'or", "L'Ours d'or", "Le César"], acc: ["palme d'or"] },
  { id: "frcine-p2", d: 4, t: "En quelle année a eu lieu le premier Festival de Cannes ?", a: "1946", x: ["1939", "1955", "1968"] },
  { id: "frcine-p3", d: 4, t: "Quels frères, pionniers du cinéma, ont projeté un film à Lyon en 1895 ?", a: "Les frères Lumière", x: ["Les frères Pathé", "Les frères Gaumont", "Les frères Méliès"], acc: ["lumière", "frères lumière"] },
  { id: "frcine-p4", d: 4, t: "Quel magicien devenu cinéaste a réalisé « Le Voyage dans la Lune » en 1902 ?", a: "Georges Méliès", x: ["Louis Lumière", "Émile Cohl", "Léon Gaumont"], acc: ["méliès"] },
  { id: "frcine-p5", d: 4, t: "Quelle actrice américaine à Paris est l'égérie de « À bout de souffle » ?", a: "Jean Seberg", x: ["Anna Karina", "Jeanne Moreau", "Brigitte Bardot"] },
  { id: "frcine-p6", d: 4, t: "Quelle muse de Godard a joué dans « Pierrot le Fou » et « Vivre sa vie » ?", a: "Anna Karina", x: ["Jean Seberg", "Jeanne Moreau", "Catherine Deneuve"] },
  { id: "frcine-p7", d: 4, t: "Quel réalisateur du « cinéma du look » a signé « Diva » et « 37°2 le matin » ?", a: "Jean-Jacques Beineix", x: ["Luc Besson", "Leos Carax", "Jean-Pierre Jeunet"] },
  { id: "frcine-p8", d: 4, t: "Quelle icône des années 50-60 a tourné « Et Dieu... créa la femme » ?", a: "Brigitte Bardot", x: ["Jeanne Moreau", "Catherine Deneuve", "Michèle Morgan"] },
  { id: "frcine-p9", d: 4, t: "Quel monstre sacré incarne « Jean de Florette » et Obélix ?", a: "Gérard Depardieu", x: ["Christian Clavier", "Jean Reno", "Daniel Auteuil"] },
  { id: "frcine-p10", d: 4, t: "Quel film de 1937 de Jean Renoir est un chef-d'œuvre pacifiste ?", a: "La Grande Illusion", x: ["La Règle du jeu", "Le Quai des brumes", "Hôtel du Nord"] },
  { id: "frcine-p11", d: 4, t: "Quel acteur à la gueule légendaire joue « Le Quai des brumes » et « Pépé le Moko » ?", a: "Jean Gabin", x: ["Michel Simon", "Louis Jouvet", "Pierre Fresnay"] },
  { id: "frcine-p12", d: 4, t: "Quel réalisateur a signé « Les Enfants du paradis », classique de 1945 ?", a: "Marcel Carné", x: ["Jean Renoir", "Julien Duvivier", "Sacha Guitry"] },
  { id: "frcine-p13", d: 4, t: "Quel film de Jacques Tati met en scène le maladroit Monsieur Hulot en vacances ?", a: "Les Vacances de Monsieur Hulot", x: ["Mon Oncle", "Playtime", "Jour de fête"] },
  { id: "frcine-p14", d: 4, t: "Quel cinéaste-acteur incarne le silencieux Monsieur Hulot ?", a: "Jacques Tati", x: ["Pierre Étaix", "Jacques Demy", "Louis Malle"] },
  { id: "frcine-p15", d: 4, t: "Quel réalisateur a signé « Les Parapluies de Cherbourg », film entièrement chanté ?", a: "Jacques Demy", x: ["Jacques Tati", "Claude Lelouch", "François Truffaut"] },
  { id: "frcine-p16", d: 4, t: "Quelle actrice chante dans « Les Parapluies de Cherbourg » de 1964 ?", a: "Catherine Deneuve", x: ["Brigitte Bardot", "Jeanne Moreau", "Anouk Aimée"] },
  { id: "frcine-p17", d: 4, t: "Quel film de 2017 de Robin Campillo raconte le combat d'Act Up contre le sida ?", a: "120 battements par minute", x: ["Les Nuits fauves", "Théo et Hugo", "L'Inconnu du lac"], acc: ["120 battements par minute"] },
  { id: "frcine-p18", d: 4, t: "Quel film de 2019 de Ladj Ly, sur une bavure à Montfermeil, a représenté la France aux Oscars ?", a: "Les Misérables", x: ["La Haine", "Bande de filles", "Divines"] },
  { id: "frcine-p19", d: 4, t: "Quelle réalisatrice a remporté la Palme d'or 2021 pour « Titane » ?", a: "Julia Ducournau", x: ["Céline Sciamma", "Mia Hansen-Løve", "Justine Triet"] },
  { id: "frcine-p20", d: 4, t: "Quelle réalisatrice a remporté la Palme d'or 2023 pour « Anatomie d'une chute » ?", a: "Justine Triet", x: ["Julia Ducournau", "Céline Sciamma", "Coralie Fargeat"] },
]);
