import { universe } from "../_build";

export const culturefrancaise = universe("france", "Culture française", [
  // --- Faciles (5) ---
  { id: "frcult-f1", d: 1, t: "Quelle est la capitale de la France ?", a: "Paris", x: ["Lyon", "Marseille", "Bordeaux"] },
  { id: "frcult-f2", d: 1, t: "Quel monument de fer parisien est le symbole de la France ?", a: "La tour Eiffel", x: ["L'Arc de Triomphe", "Notre-Dame", "Le Sacré-Cœur"], acc: ["tour eiffel"] },
  { id: "frcult-f3", d: 1, t: "Quelle est la devise de la République française ?", a: "Liberté, Égalité, Fraternité", x: ["Un pour tous, tous pour un", "Dieu et mon droit", "Travail, Famille, Patrie"], acc: ["liberté égalité fraternité"] },
  { id: "frcult-f4", d: 1, t: "Quel est l'hymne national français ?", a: "La Marseillaise", x: ["Le Chant du départ", "La Marche lorraine", "L'Internationale"], acc: ["marseillaise"] },
  { id: "frcult-f5", d: 1, t: "Quel animal est un emblème de la France, symbole de fierté ?", a: "Le coq gaulois", x: ["L'aigle", "Le lion", "Le taureau"], acc: ["coq", "coq gaulois"] },
  // --- Moyennes (10) ---
  { id: "frcult-m1", d: 2, t: "Quel fleuve traverse Paris ?", a: "La Seine", x: ["La Loire", "Le Rhône", "La Garonne"] },
  { id: "frcult-m2", d: 2, t: "Quel est le plus long fleuve de France ?", a: "La Loire", x: ["La Seine", "Le Rhône", "La Garonne"] },
  { id: "frcult-m3", d: 2, t: "Quelle chaîne de montagnes sépare la France de l'Espagne ?", a: "Les Pyrénées", x: ["Les Alpes", "Le Jura", "Les Vosges"] },
  { id: "frcult-m4", d: 2, t: "Quel est le plus haut sommet de France et des Alpes ?", a: "Le mont Blanc", x: ["Le mont Ventoux", "Le puy de Dôme", "La Meije"], acc: ["mont blanc"] },
  { id: "frcult-m5", d: 2, t: "Quel événement de 1789 la fête nationale du 14 juillet commémore-t-elle ?", a: "La prise de la Bastille", x: ["Le sacre de Napoléon", "L'Armistice", "La bataille de Valmy"], acc: ["prise de la bastille"] },
  { id: "frcult-m6", d: 2, t: "Quel palais est la résidence officielle du président de la République ?", a: "Le palais de l'Élysée", x: ["Le château de Versailles", "Matignon", "Le Louvre"], acc: ["élysée", "elysee"] },
  { id: "frcult-m7", d: 2, t: "Où siège l'Assemblée nationale, à Paris ?", a: "Le palais Bourbon", x: ["Le palais du Luxembourg", "L'Élysée", "Matignon"], acc: ["palais bourbon"] },
  { id: "frcult-m8", d: 2, t: "Quel château près de Paris était la résidence des rois, dont Louis XIV ?", a: "Versailles", x: ["Fontainebleau", "Chambord", "Vincennes"], acc: ["versailles", "château de versailles"] },
  { id: "frcult-m9", d: 2, t: "Quel célèbre musée parisien abrite « La Joconde » ?", a: "Le Louvre", x: ["Le musée d'Orsay", "Le Centre Pompidou", "Le Grand Palais"], acc: ["louvre"] },
  { id: "frcult-m10", d: 2, t: "Combien de régions la France métropolitaine compte-t-elle depuis 2016 ?", a: "Treize", x: ["Vingt-deux", "Dix-huit", "Huit"], acc: ["13", "treize"] },
  // --- Dures (15) ---
  { id: "frcult-d1", d: 3, t: "Quelle République la France connaît-elle actuellement ?", a: "La Ve République", x: ["La IIIe République", "La IVe République", "La VIe République"], acc: ["cinquième", "ve"] },
  { id: "frcult-d2", d: 3, t: "Qui a fondé la Ve République en 1958 ?", a: "Charles de Gaulle", x: ["Georges Pompidou", "François Mitterrand", "Vincent Auriol"] },
  { id: "frcult-d3", d: 3, t: "Quelle avenue parisienne est surnommée « la plus belle avenue du monde » ?", a: "Les Champs-Élysées", x: ["Le boulevard Haussmann", "La rue de Rivoli", "L'avenue Montaigne"], acc: ["champs-élysées", "champs elysees"] },
  { id: "frcult-d4", d: 3, t: "Quel arc parisien domine la place de l'Étoile, au bout des Champs-Élysées ?", a: "L'Arc de Triomphe", x: ["La porte Saint-Denis", "L'arc du Carrousel", "La Grande Arche"], acc: ["arc de triomphe"] },
  { id: "frcult-d5", d: 3, t: "Quelle cathédrale gothique parisienne, sur l'île de la Cité, a brûlé en 2019 ?", a: "Notre-Dame de Paris", x: ["La Sainte-Chapelle", "Le Sacré-Cœur", "Saint-Sulpice"], acc: ["notre-dame", "notre dame"] },
  { id: "frcult-d6", d: 3, t: "Quelle abbaye-forteresse sur un îlot normand est cernée par les marées ?", a: "Le Mont-Saint-Michel", x: ["Saint-Malo", "Carnac", "L'île de Ré"], acc: ["mont saint michel", "mont-saint-michel"] },
  { id: "frcult-d7", d: 3, t: "Quelle grande région viticole entoure la ville de Bordeaux ?", a: "Le Bordelais", x: ["La Bourgogne", "La Champagne", "Le Beaujolais"], acc: ["bordelais", "bordeaux"] },
  { id: "frcult-d8", d: 3, t: "Quelle héroïne a mené la France contre les Anglais avant d'être brûlée en 1431 ?", a: "Jeanne d'Arc", x: ["Aliénor d'Aquitaine", "Catherine de Médicis", "Blanche de Castille"], acc: ["jeanne d'arc"] },
  { id: "frcult-d9", d: 3, t: "Quel empereur français s'est couronné en 1804 et a dominé l'Europe ?", a: "Napoléon Ier", x: ["Louis XIV", "Charlemagne", "Napoléon III"], acc: ["napoléon", "napoleon", "napoléon ier"] },
  { id: "frcult-d10", d: 3, t: "En quelle année débute la Révolution française ?", a: "1789", x: ["1815", "1848", "1799"] },
  { id: "frcult-d11", d: 3, t: "Quel roi, surnommé le « Roi-Soleil », a régné 72 ans ?", a: "Louis XIV", x: ["Louis XV", "Louis XVI", "François Ier"], acc: ["louis xiv", "louis 14"] },
  { id: "frcult-d12", d: 3, t: "Quelle grotte de Dordogne est célèbre pour ses peintures préhistoriques ?", a: "Lascaux", x: ["Chauvet", "Les Eyzies", "Pech Merle"], acc: ["lascaux"] },
  { id: "frcult-d13", d: 3, t: "Quels menhirs et dolmens alignés se trouvent en Bretagne ?", a: "Les alignements de Carnac", x: ["Stonehenge", "Le cromlech de Rennes", "Les mégalithes d'Évora"], acc: ["carnac"] },
  { id: "frcult-d14", d: 3, t: "Quelle région du sud-est borde la Méditerranée, de Cannes à Menton ?", a: "La Côte d'Azur", x: ["La Camargue", "Le Languedoc", "La Corse"], acc: ["côte d'azur", "cote d'azur"] },
  { id: "frcult-d15", d: 3, t: "Quelle grande course cycliste traverse la France chaque été ?", a: "Le Tour de France", x: ["Paris-Roubaix", "Le Giro", "La Vuelta"], acc: ["tour de france"] },
  // --- Pro (20) ---
  { id: "frcult-p1", d: 4, t: "Quelle institution protège la langue française et publie un dictionnaire depuis 1635 ?", a: "L'Académie française", x: ["La Sorbonne", "Le Collège de France", "L'Alliance française"], acc: ["académie française"] },
  { id: "frcult-p2", d: 4, t: "Combien de membres, ou « immortels », compte l'Académie française ?", a: "Quarante", x: ["Cinquante", "Trente", "Cent"], acc: ["40", "quarante"] },
  { id: "frcult-p3", d: 4, t: "Quelle région de l'est, longtemps disputée avec l'Allemagne, a pour capitale Strasbourg ?", a: "L'Alsace", x: ["La Lorraine", "La Bourgogne", "La Franche-Comté"], acc: ["alsace"] },
  { id: "frcult-p4", d: 4, t: "Quel plus grand château de la Loire a été bâti pour François Ier ?", a: "Chambord", x: ["Chenonceau", "Amboise", "Blois"], acc: ["chambord"] },
  { id: "frcult-p5", d: 4, t: "Quel château de la Loire enjambe le Cher et est surnommé « le château des Dames » ?", a: "Chenonceau", x: ["Chambord", "Villandry", "Azay-le-Rideau"], acc: ["chenonceau"] },
  { id: "frcult-p6", d: 4, t: "Dans quel ordre se lisent les bandes du drapeau français ?", a: "Bleu, blanc, rouge", x: ["Rouge, blanc, bleu", "Bleu, blanc, vert", "Rouge, blanc, vert"], acc: ["bleu blanc rouge"] },
  { id: "frcult-p7", d: 4, t: "Quelle figure féminine coiffée d'un bonnet phrygien incarne la République française ?", a: "Marianne", x: ["Jeanne", "La Semeuse", "Germinal"], acc: ["marianne"] },
  { id: "frcult-p8", d: 4, t: "Quel philosophe des Lumières a écrit « Candide » ?", a: "Voltaire", x: ["Rousseau", "Montesquieu", "Diderot"], acc: ["voltaire"] },
  { id: "frcult-p9", d: 4, t: "Quel scientifique français a mis au point le vaccin contre la rage ?", a: "Louis Pasteur", x: ["Claude Bernard", "Antoine Lavoisier", "Pierre Curie"], acc: ["pasteur", "louis pasteur"] },
  { id: "frcult-p10", d: 4, t: "Quelle scientifique franco-polonaise a reçu deux prix Nobel, en physique et en chimie ?", a: "Marie Curie", x: ["Irène Joliot-Curie", "Rosalind Franklin", "Émilie du Châtelet"], acc: ["marie curie"] },
  { id: "frcult-p11", d: 4, t: "Quelle est la plus haute distinction honorifique française, créée par Napoléon ?", a: "La Légion d'honneur", x: ["L'ordre national du Mérite", "Les Palmes académiques", "La médaille militaire"], acc: ["légion d'honneur"] },
  { id: "frcult-p12", d: 4, t: "Quel massif ancien du centre de la France est parsemé de volcans endormis ?", a: "Le Massif central", x: ["Les Vosges", "Les Ardennes", "Le Morvan"], acc: ["massif central"] },
  { id: "frcult-p13", d: 4, t: "Quel volcan endormi domine Clermont-Ferrand ?", a: "Le puy de Dôme", x: ["Le Cantal", "Le puy Mary", "Le mont Aigoual"], acc: ["puy de dôme"] },
  { id: "frcult-p14", d: 4, t: "Quel territoire français forme une grande île de la Méditerranée ?", a: "La Corse", x: ["Les Bouches-du-Rhône", "Le Var", "Les Alpes-Maritimes"], acc: ["corse"] },
  { id: "frcult-p15", d: 4, t: "Quelle région humide du delta du Rhône est connue pour ses chevaux et ses taureaux ?", a: "La Camargue", x: ["La Sologne", "Les Landes", "La Brenne"], acc: ["camargue"] },
  { id: "frcult-p16", d: 4, t: "Quel roi a fait édifier le château de Versailles tel qu'on le connaît ?", a: "Louis XIV", x: ["Louis XIII", "Louis XV", "Henri IV"], acc: ["louis xiv"] },
  { id: "frcult-p17", d: 4, t: "Quel peuple, mené par Vercingétorix, a résisté à Jules César à Alésia ?", a: "Les Gaulois", x: ["Les Francs", "Les Wisigoths", "Les Burgondes"], acc: ["gaulois"] },
  { id: "frcult-p18", d: 4, t: "Quel roi franc a été sacré empereur d'Occident en l'an 800 ?", a: "Charlemagne", x: ["Clovis", "Hugues Capet", "Dagobert"], acc: ["charlemagne"] },
  { id: "frcult-p19", d: 4, t: "Quel premier roi des Francs, baptisé à Reims, a unifié la Gaule ?", a: "Clovis", x: ["Charlemagne", "Dagobert", "Clotaire"], acc: ["clovis"] },
  { id: "frcult-p20", d: 4, t: "Quel pont-aqueduc romain enjambe le Gardon, près de Nîmes ?", a: "Le pont du Gard", x: ["Le pont d'Avignon", "Le viaduc de Millau", "Le pont Valentré"], acc: ["pont du gard"] },
]);
