import { universe } from "../_build";

export const gastronomiefrancaise = universe("france", "Gastronomie française", [
  // --- Faciles (5) ---
  { id: "frfood-f1", d: 1, t: "Quel pain long et croustillant est un symbole de la France ?", a: "La baguette", x: ["Le croissant", "La brioche", "La ficelle"], acc: ["baguette"] },
  { id: "frfood-f2", d: 1, t: "Quelle viennoiserie feuilletée en forme de croissant se mange au petit-déjeuner ?", a: "Le croissant", x: ["Le pain au chocolat", "La brioche", "Le chausson"], acc: ["croissant"] },
  { id: "frfood-f3", d: 1, t: "De quel aliment la France produit-elle des centaines de variétés, une par jour de l'année ?", a: "Le fromage", x: ["Le vin", "Le pain", "La charcuterie"], acc: ["fromage"] },
  { id: "frfood-f4", d: 1, t: "Quel plat d'escargots au beurre et à l'ail est une spécialité française ?", a: "Les escargots de Bourgogne", x: ["Les moules-frites", "Les cuisses de grenouille", "Le foie gras"], acc: ["escargots"] },
  { id: "frfood-f5", d: 1, t: "Quel dessert à la crème est caramélisé et croustillant sur le dessus ?", a: "La crème brûlée", x: ["La crème caramel", "Le flan", "La panna cotta"], acc: ["crème brûlée"] },
  // --- Moyennes (10) ---
  { id: "frfood-m1", d: 2, t: "Quel plat mijoté de bœuf au vin rouge est une spécialité bourguignonne ?", a: "Le bœuf bourguignon", x: ["Le pot-au-feu", "La daube", "Le coq au vin"], acc: ["bœuf bourguignon", "boeuf bourguignon"] },
  { id: "frfood-m2", d: 2, t: "Quel plat de poulet mijoté au vin est un classique français ?", a: "Le coq au vin", x: ["Le bœuf bourguignon", "Le pot-au-feu", "La blanquette"], acc: ["coq au vin"] },
  { id: "frfood-m3", d: 2, t: "Quel ragoût de veau à la sauce blanche est un plat familial français ?", a: "La blanquette de veau", x: ["Le bœuf bourguignon", "Le pot-au-feu", "La daube"], acc: ["blanquette"] },
  { id: "frfood-m4", d: 2, t: "Quelle soupe à l'oignon gratinée est un classique des bistrots parisiens ?", a: "La soupe à l'oignon", x: ["La bouillabaisse", "La garbure", "Le velouté"], acc: ["soupe à l'oignon"] },
  { id: "frfood-m5", d: 2, t: "Quelle soupe de poissons est la spécialité emblématique de Marseille ?", a: "La bouillabaisse", x: ["La soupe à l'oignon", "La garbure", "La bourride"], acc: ["bouillabaisse"] },
  { id: "frfood-m6", d: 2, t: "Quel plat alsacien réunit chou fermenté, saucisses et charcuterie ?", a: "La choucroute", x: ["La raclette", "La tartiflette", "La potée"], acc: ["choucroute"] },
  { id: "frfood-m7", d: 2, t: "Quel plat savoyard fait fondre un fromage à racler sur des pommes de terre ?", a: "La raclette", x: ["La fondue", "La tartiflette", "La choucroute"], acc: ["raclette"] },
  { id: "frfood-m8", d: 2, t: "Quel gratin savoyard associe reblochon, lardons et pommes de terre ?", a: "La tartiflette", x: ["La raclette", "La fondue", "La croziflette"], acc: ["tartiflette"] },
  { id: "frfood-m9", d: 2, t: "Quel plat consiste à tremper des morceaux de pain dans du fromage fondu ?", a: "La fondue savoyarde", x: ["La raclette", "La tartiflette", "La pierrade"], acc: ["fondue", "fondue savoyarde"] },
  { id: "frfood-m10", d: 2, t: "Quel foie d'oie ou de canard engraissé est un mets de fête français ?", a: "Le foie gras", x: ["Le pâté", "Les rillettes", "Le confit"], acc: ["foie gras"] },
  // --- Dures (15) ---
  { id: "frfood-d1", d: 3, t: "Quelle pâtisserie ronde à deux coques et une ganache existe en mille parfums ?", a: "Le macaron", x: ["La meringue", "Le financier", "Le canelé"], acc: ["macaron"] },
  { id: "frfood-d2", d: 3, t: "Quel petit gâteau bordelais caramélisé et parfumé au rhum a une forme cannelée ?", a: "Le canelé", x: ["Le macaron", "Le financier", "Le kouign-amann"], acc: ["canelé", "cannelé"] },
  { id: "frfood-d3", d: 3, t: "Quel gâteau breton ultra-beurré et caramélisé porte un nom breton ?", a: "Le kouign-amann", x: ["Le far breton", "Le canelé", "Le financier"], acc: ["kouign-amann"] },
  { id: "frfood-d4", d: 3, t: "Quelle pâtisserie à la crème pralinée, en forme d'anneau, évoque une roue de vélo ?", a: "Le Paris-Brest", x: ["L'éclair", "La religieuse", "Le saint-honoré"], acc: ["paris-brest"] },
  { id: "frfood-d5", d: 3, t: "Quel gâteau de pâte à choux fourré de crème est glacé sur le dessus ?", a: "L'éclair", x: ["Le Paris-Brest", "La religieuse", "Le mille-feuille"], acc: ["éclair"] },
  { id: "frfood-d6", d: 3, t: "Quel dessert à trois couches de pâte feuilletée et de crème s'appelle aussi « Napoléon » ?", a: "Le mille-feuille", x: ["L'éclair", "Le Paris-Brest", "Le saint-honoré"], acc: ["mille-feuille"] },
  { id: "frfood-d7", d: 3, t: "Quelle tarte aux pommes caramélisées est cuite à l'envers ?", a: "La tarte Tatin", x: ["La tarte aux pommes", "Le clafoutis", "La tarte normande"], acc: ["tarte tatin", "tatin"] },
  { id: "frfood-d8", d: 3, t: "Quel dessert aux cerises entières prises dans un flan vient du Limousin ?", a: "Le clafoutis", x: ["La tarte Tatin", "Le far breton", "La flognarde"], acc: ["clafoutis"] },
  { id: "frfood-d9", d: 3, t: "Quel plat provençal mijote aubergines, courgettes, poivrons et tomates ?", a: "La ratatouille", x: ["La piperade", "La bohémienne", "La caponata"], acc: ["ratatouille"] },
  { id: "frfood-d10", d: 3, t: "Quel plat du Sud-Ouest mijote des haricots blancs avec confit et saucisse ?", a: "Le cassoulet", x: ["La garbure", "Le confit", "La daube"], acc: ["cassoulet"] },
  { id: "frfood-d11", d: 3, t: "Quelle terrine de porc effiloché, spécialité du Mans et de Tours, se tartine ?", a: "Les rillettes", x: ["Le pâté", "Le foie gras", "Les rillons"], acc: ["rillettes"] },
  { id: "frfood-d12", d: 3, t: "Quelle galette de sarrasin bretonne se garnit d'œuf, jambon et fromage ?", a: "La galette bretonne", x: ["La crêpe sucrée", "La socca", "La ficelle picarde"], acc: ["galette", "galette bretonne", "galette de sarrasin"] },
  { id: "frfood-d13", d: 3, t: "Quel fromage à pâte persillée de l'Aveyron est affiné en cave ?", a: "Le roquefort", x: ["Le bleu d'Auvergne", "Le comté", "Le cantal"], acc: ["roquefort"] },
  { id: "frfood-d14", d: 3, t: "Quel fromage à croûte fleurie de Normandie est un symbole de la France ?", a: "Le camembert", x: ["Le brie", "Le munster", "Le reblochon"], acc: ["camembert"] },
  { id: "frfood-d15", d: 3, t: "Quel vin effervescent d'une région du nord-est se boit lors des fêtes ?", a: "Le champagne", x: ["Le crémant", "Le prosecco", "Le cava"], acc: ["champagne"] },
  // --- Pro (20) ---
  { id: "frfood-p1", d: 4, t: "Quel guide gastronomique décerne des étoiles aux restaurants ?", a: "Le Guide Michelin", x: ["Le Gault et Millau", "Le Fooding", "Le Pudlo"], acc: ["michelin", "guide michelin"] },
  { id: "frfood-p2", d: 4, t: "Combien d'étoiles au maximum un restaurant peut-il obtenir au Guide Michelin ?", a: "Trois", x: ["Deux", "Cinq", "Quatre"], acc: ["3", "trois"] },
  { id: "frfood-p3", d: 4, t: "Quel chef, « empereur des cuisiniers », a codifié la cuisine française au début du XXe siècle ?", a: "Auguste Escoffier", x: ["Paul Bocuse", "Marie-Antoine Carême", "Alain Ducasse"] },
  { id: "frfood-p4", d: 4, t: "Quel chef lyonnais, figure de la nouvelle cuisine, a donné son nom à un concours mondial ?", a: "Paul Bocuse", x: ["Alain Ducasse", "Joël Robuchon", "Bernard Loiseau"] },
  { id: "frfood-p5", d: 4, t: "Quel chef français compte le plus d'étoiles Michelin au monde, avec ses nombreux restaurants ?", a: "Alain Ducasse", x: ["Paul Bocuse", "Joël Robuchon", "Guy Savoy"] },
  { id: "frfood-p6", d: 4, t: "Quel pâtissier du XIXe siècle, dit « roi des chefs », a inventé de grandes pièces montées ?", a: "Marie-Antoine Carême", x: ["Auguste Escoffier", "Gaston Lenôtre", "Pierre Hermé"] },
  { id: "frfood-p7", d: 4, t: "Quel pâtissier contemporain est surnommé le « Picasso de la pâtisserie » pour ses macarons ?", a: "Pierre Hermé", x: ["Gaston Lenôtre", "Cédric Grolet", "Philippe Conticini"] },
  { id: "frfood-p8", d: 4, t: "Quel jeune chef pâtissier est célèbre pour ses fruits en trompe-l'œil au Meurice ?", a: "Cédric Grolet", x: ["Pierre Hermé", "Christophe Michalak", "Yann Couvreur"] },
  { id: "frfood-p9", d: 4, t: "Quelle appellation protège l'origine géographique d'un vin ou d'un fromage français ?", a: "L'AOC", x: ["Le label rouge", "L'IGP", "Le bio"], acc: ["aoc", "appellation d'origine contrôlée"] },
  { id: "frfood-p10", d: 4, t: "Quel vignoble produit les grands rouges à base de cabernet et de merlot ?", a: "Le Bordelais", x: ["La Bourgogne", "Le Rhône", "Le Languedoc"], acc: ["bordelais", "bordeaux"] },
  { id: "frfood-p11", d: 4, t: "Quel cépage roi fait les grands vins rouges de Bourgogne ?", a: "Le pinot noir", x: ["Le cabernet sauvignon", "Le merlot", "La syrah"], acc: ["pinot noir"] },
  { id: "frfood-p12", d: 4, t: "Quel vin blanc doux et liquoreux du Bordelais est un grand cru sucré ?", a: "Le sauternes", x: ["Le muscadet", "Le sancerre", "Le chablis"], acc: ["sauternes"] },
  { id: "frfood-p13", d: 4, t: "Quel apéritif anisé du Sud se boit allongé d'eau ?", a: "Le pastis", x: ["Le pineau", "Le kir", "Le porto"], acc: ["pastis"] },
  { id: "frfood-p14", d: 4, t: "Quel apéritif mêle vin blanc et crème de cassis ?", a: "Le kir", x: ["Le pastis", "Le spritz", "Le pineau"], acc: ["kir"] },
  { id: "frfood-p15", d: 4, t: "Quel fromage à pâte pressée cuite du Jura est affiné de longs mois ?", a: "Le comté", x: ["Le beaufort", "Le gruyère", "L'emmental"], acc: ["comté"] },
  { id: "frfood-p16", d: 4, t: "Quel gratin de pommes de terre à la crème vient du Dauphiné ?", a: "Le gratin dauphinois", x: ["La tartiflette", "Le hachis parmentier", "L'aligot"], acc: ["gratin dauphinois"] },
  { id: "frfood-p17", d: 4, t: "Quelle purée filante de l'Aveyron mêle pommes de terre, tomme et ail ?", a: "L'aligot", x: ["Le gratin dauphinois", "La truffade", "La tartiflette"], acc: ["aligot"] },
  { id: "frfood-p18", d: 4, t: "Quel plat traditionnel fait bouillir viandes et légumes dans un bouillon ?", a: "Le pot-au-feu", x: ["La blanquette", "Le bœuf bourguignon", "La potée"], acc: ["pot-au-feu"] },
  { id: "frfood-p19", d: 4, t: "Quel gâteau roulé garni de crème au beurre est traditionnel à Noël ?", a: "La bûche de Noël", x: ["La galette des rois", "Le pain d'épices", "Le kouglof"], acc: ["bûche", "bûche de noël"] },
  { id: "frfood-p20", d: 4, t: "Quelle pâtisserie feuilletée à la frangipane se mange à l'Épiphanie, avec une fève ?", a: "La galette des rois", x: ["La bûche de Noël", "Le kouglof", "Le pain d'épices"], acc: ["galette des rois"] },
]);
