import { universe } from "../_build";

export const kaamelott = universe("france", "Kaamelott", [
  // --- Faciles (5) ---
  { id: "kaamelott-f1", d: 1, t: "Qui a créé la série Kaamelott ?", a: "Alexandre Astier", x: ["Éric Judor", "Dany Boon", "Gad Elmaleh"], acc: ["alexandre astier", "astier"] },
  { id: "kaamelott-f2", d: 1, t: "De quelle légende Kaamelott est-elle une parodie ?", a: "La légende du roi Arthur", x: ["La mythologie grecque", "Robin des Bois", "Les Trois Mousquetaires"], acc: ["roi arthur", "legende du roi arthur", "arthur"] },
  { id: "kaamelott-f3", d: 1, t: "Quel roi Alexandre Astier incarne-t-il dans la série ?", a: "Le roi Arthur", x: ["Lancelot", "Léodagan", "Perceval"], acc: ["arthur", "le roi arthur", "roi arthur"] },
  { id: "kaamelott-f4", d: 1, t: "Quel objet sacré les chevaliers de Kaamelott cherchent-ils ?", a: "Le Graal", x: ["L'Excalibur d'or", "La Toison d'or", "L'Anneau"], acc: ["graal", "le graal", "saint graal"] },
  { id: "kaamelott-f5", d: 1, t: "Autour de quelle table se réunissent les chevaliers ?", a: "La Table Ronde", x: ["La Table Carrée", "La Grande Table", "La Table du Roi"], acc: ["table ronde", "la table ronde"] },
  // --- Moyennes (10) ---
  { id: "kaamelott-m1", d: 2, t: "Comment s'appelle le chevalier benêt, connu pour dire « C'est pas faux » ?", a: "Perceval", x: ["Karadoc", "Bohort", "Lancelot"], acc: ["perceval"] },
  { id: "kaamelott-m2", d: 2, t: "Quelle réplique culte Perceval lance-t-il quand il ne comprend rien ?", a: "C'est pas faux", x: ["Sans déconner", "Évidemment", "Je le savais"], acc: ["c'est pas faux", "cest pas faux"] },
  { id: "kaamelott-m3", d: 2, t: "Comment s'appelle le gros chevalier glouton, ami de Perceval ?", a: "Karadoc", x: ["Bohort", "Léodagan", "Caius"], acc: ["karadoc"] },
  { id: "kaamelott-m4", d: 2, t: "Comment s'appelle l'épouse d'Arthur, la reine ?", a: "Guenièvre", x: ["Séli", "Mevanwi", "Angharad"], acc: ["guenievre", "guenièvre"] },
  { id: "kaamelott-m5", d: 2, t: "Comment s'appelle l'enchanteur maladroit de Kaamelott ?", a: "Merlin", x: ["Élias", "Bohort", "Blaise"], acc: ["merlin"] },
  { id: "kaamelott-m6", d: 2, t: "Sur quelle chaîne française Kaamelott a-t-elle été diffusée ?", a: "M6", x: ["TF1", "France 2", "Canal+"], acc: ["m6"] },
  { id: "kaamelott-m7", d: 2, t: "Comment s'appelle le chevalier noble et peureux, prompt à pleurer ?", a: "Bohort", x: ["Léodagan", "Karadoc", "Perceval"], acc: ["bohort"] },
  { id: "kaamelott-m8", d: 2, t: "Comment s'appelle le beau-père guerrier et sanguin d'Arthur ?", a: "Léodagan", x: ["Bohort", "Merlin", "Loth"], acc: ["leodagan", "léodagan"] },
  { id: "kaamelott-m9", d: 2, t: "Quelle particularité ont les épisodes de la série à ses débuts ?", a: "Ils sont très courts", x: ["Ils durent 2 heures", "Ils sont muets", "Ils sont en noir et blanc"], acc: ["tres courts", "courts", "format court"] },
  { id: "kaamelott-m10", d: 2, t: "En quelle année la série Kaamelott a-t-elle été lancée ?", a: "2005", x: ["1999", "2010", "2015"], acc: ["2005"] },
  // --- Dures (15) ---
  { id: "kaamelott-d1", d: 3, t: "Comment s'appelle le beau chevalier idéaliste qui finit par trahir Arthur ?", a: "Lancelot", x: ["Bohort", "Karadoc", "Léodagan"], acc: ["lancelot"] },
  { id: "kaamelott-d2", d: 3, t: "Comment appelle-t-on les parties de la série, numérotées de I à VI ?", a: "Des Livres", x: ["Des Saisons", "Des Tomes", "Des Chants"], acc: ["livres", "des livres", "livre"] },
  { id: "kaamelott-d3", d: 3, t: "Quelle actrice rousse incarne la Dame du Lac ?", a: "Audrey Fleurot", x: ["Anne Girouard", "Alexandra Lamy", "Bérénice Bejo"], acc: ["audrey fleurot", "fleurot"] },
  { id: "kaamelott-d4", d: 3, t: "Quel proche parent d'Alexandre Astier joue le rôle de Léodagan ?", a: "Son père, Lionnel Astier", x: ["Son frère", "Son oncle", "Son fils"], acc: ["lionnel astier", "son pere", "lionnel"] },
  { id: "kaamelott-d5", d: 3, t: "Comment s'appelle le centurion romain, allié encombrant d'Arthur ?", a: "Caius", x: ["Loth", "Venec", "Blaise"], acc: ["caius", "caius camulus"] },
  { id: "kaamelott-d6", d: 3, t: "Quels rôles Alexandre Astier cumule-t-il sur Kaamelott ?", a: "Auteur, réalisateur et acteur principal", x: ["Uniquement acteur", "Uniquement producteur", "Uniquement musicien"], acc: ["auteur realisateur acteur", "auteur realisateur et acteur", "tout a la fois"] },
  { id: "kaamelott-d7", d: 3, t: "Qui compose la musique de Kaamelott ?", a: "Alexandre Astier lui-même", x: ["Éric Serra", "Hans Zimmer", "Alexandre Desplat"], acc: ["alexandre astier", "astier", "astier lui-meme"] },
  { id: "kaamelott-d8", d: 3, t: "Comment s'appelle l'épée légendaire d'Arthur ?", a: "Excalibur", x: ["Durandal", "Joyeuse", "Curtana"], acc: ["excalibur"] },
  { id: "kaamelott-d9", d: 3, t: "Comment s'appelle la mère de Guenièvre, épouse de Léodagan ?", a: "Dame Séli", x: ["Mevanwi", "Angharad", "La Dame du Lac"], acc: ["seli", "dame seli", "séli"] },
  { id: "kaamelott-d10", d: 3, t: "Comment s'appelle la femme de Karadoc, qui devient la maîtresse d'Arthur ?", a: "Mevanwi", x: ["Séli", "Guenièvre", "Angharad"], acc: ["mevanwi"] },
  { id: "kaamelott-d11", d: 3, t: "Quel roi rival, beau-frère d'Arthur, est joué par François Rollin ?", a: "Le roi Loth", x: ["Léodagan", "Caius", "Lancelot"], acc: ["loth", "le roi loth"] },
  { id: "kaamelott-d12", d: 3, t: "Comment s'appelle le trafiquant combinard qui vend de tout à Kaamelott ?", a: "Venec", x: ["Guethenoc", "Roparzh", "Blaise"], acc: ["venec"] },
  { id: "kaamelott-d13", d: 3, t: "Comment s'appelle le prêtre-scribe qui consigne les aventures ?", a: "Le Père Blaise", x: ["Merlin", "Bohort", "Élias"], acc: ["pere blaise", "blaise", "père blaise"] },
  { id: "kaamelott-d14", d: 3, t: "Quel jeu absurde inventé par Perceval et Karadoc revient dans la série ?", a: "Le Sloubi", x: ["Le Pousse-Cailloux", "Le Passe-Grimaud", "Le Trou-Madame"], acc: ["sloubi", "le sloubi"] },
  { id: "kaamelott-d15", d: 3, t: "Dans quelle grande capitale antique Arthur a-t-il été formé avant de régner ?", a: "Rome", x: ["Athènes", "Alexandrie", "Byzance"], acc: ["rome"] },
  // --- Pro (20) ---
  { id: "kaamelott-p1", d: 4, t: "Comment s'appelle le film Kaamelott sorti au cinéma en 2021 ?", a: "Kaamelott: Premier Volet", x: ["Kaamelott: Le Graal", "Kaamelott: Le Retour", "Kaamelott: La Légende"], acc: ["premier volet", "kaamelott premier volet"] },
  { id: "kaamelott-p2", d: 4, t: "Comment s'intitule la suite au cinéma, sortie en 2025 ?", a: "Kaamelott: Deuxième Volet", x: ["Kaamelott: Troisième Volet", "Kaamelott: Le Retour", "Kaamelott: Final"], acc: ["deuxieme volet", "kaamelott deuxieme volet", "deuxième volet"] },
  { id: "kaamelott-p3", d: 4, t: "Combien de Livres compte la série télévisée à l'origine ?", a: "6", x: ["3", "9", "12"], acc: ["6", "six"] },
  { id: "kaamelott-p4", d: 4, t: "Quel acteur joue le naïf Perceval ?", a: "Franck Pitiot", x: ["Jean-Christophe Hembert", "Nicolas Gabion", "Thomas Cousseau"], acc: ["franck pitiot", "pitiot"] },
  { id: "kaamelott-p5", d: 4, t: "Quel acteur joue le glouton Karadoc ?", a: "Jean-Christophe Hembert", x: ["Franck Pitiot", "Nicolas Gabion", "Lionnel Astier"], acc: ["jean-christophe hembert", "hembert"] },
  { id: "kaamelott-p6", d: 4, t: "Quelle actrice incarne la reine Guenièvre ?", a: "Anne Girouard", x: ["Audrey Fleurot", "Alexandra Lamy", "Josée Drevon"], acc: ["anne girouard", "girouard"] },
  { id: "kaamelott-p7", d: 4, t: "Quelle particularité a la Dame du Lac face aux autres personnages ?", a: "Seul Arthur peut la voir", x: ["Elle est invisible pour tous", "Elle est muette", "Tout le monde la connaît"], acc: ["seul arthur peut la voir", "arthur peut la voir", "seul arthur la voit"] },
  { id: "kaamelott-p8", d: 4, t: "Comment s'appelle l'inquisiteur zélé qui traque l'hérésie à Kaamelott ?", a: "Le Répurgateur", x: ["Le Tavernier", "Le Répartiteur", "L'Aiguiseur"], acc: ["repurgateur", "le repurgateur", "répurgateur"] },
  { id: "kaamelott-p9", d: 4, t: "Quels deux paysans se disputent sans cesse à propos de leurs terres ?", a: "Guethenoc et Roparzh", x: ["Venec et Blaise", "Caius et Loth", "Merlin et Élias"], acc: ["guethenoc et roparzh", "guethenoc", "roparzh"] },
  { id: "kaamelott-p10", d: 4, t: "Comment s'appelle l'enchanteur rival de Merlin, bien plus compétent ?", a: "Élias de Kelliwic'h", x: ["Blaise", "Venec", "Caius"], acc: ["elias", "elias de kelliwic'h", "élias"] },
  { id: "kaamelott-p11", d: 4, t: "Comment surnomme-t-on souvent Perceval, à cause de sa région d'origine ?", a: "Le Gallois", x: ["Le Breton", "Le Normand", "Le Picard"], acc: ["gallois", "le gallois", "perceval de galles"] },
  { id: "kaamelott-p12", d: 4, t: "Quel type d'humour caractérise Kaamelott ?", a: "Un humour anachronique et absurde", x: ["Un humour d'horreur", "Un humour uniquement visuel", "Un humour musical"], acc: ["anachronique", "absurde", "anachronique et absurde"] },
  { id: "kaamelott-p13", d: 4, t: "Comment s'appelle la guerrière éprise d'Arthur, apparue dans les derniers Livres ?", a: "Angharad", x: ["Mevanwi", "Séli", "Guenièvre"], acc: ["angharad"] },
  { id: "kaamelott-p14", d: 4, t: "Au début du film Premier Volet, dans quelle situation se trouve Arthur ?", a: "En exil, loin du trône", x: ["Au sommet de sa gloire", "En prison à Rome", "Mort depuis longtemps"], acc: ["en exil", "exil", "loin du trone"] },
  { id: "kaamelott-p15", d: 4, t: "Contre quel ancien chevalier devenu tyran Arthur lutte-t-il dans le film ?", a: "Lancelot", x: ["Léodagan", "Loth", "Caius"], acc: ["lancelot"] },
  { id: "kaamelott-p16", d: 4, t: "Quel registre de langage, très moderne, les personnages emploient-ils malgré l'époque ?", a: "Un langage familier et actuel", x: ["Le latin", "Le vieux français", "L'occitan"], acc: ["langage familier", "familier", "moderne"] },
  { id: "kaamelott-p17", d: 4, t: "Quel neveu turbulent d'Arthur est le fils du roi Loth ?", a: "Gauvain", x: ["Yvain", "Perceval", "Bohort"], acc: ["gauvain"] },
  { id: "kaamelott-p18", d: 4, t: "Quel autre talent artistique Alexandre Astier met-il en avant ?", a: "Il est musicien et compositeur", x: ["Il est danseur", "Il est peintre", "Il est sculpteur"], acc: ["musicien", "compositeur", "musicien et compositeur"] },
  { id: "kaamelott-p19", d: 4, t: "Comment se nomme le royaume et le château d'Arthur, qui donne son titre à la série ?", a: "Kaamelott", x: ["Camelot-sur-Mer", "Tintagel", "Avalon"], acc: ["kaamelott"] },
  { id: "kaamelott-p20", d: 4, t: "Quel ton prennent les derniers Livres de la série, en s'éloignant de la comédie ?", a: "Un ton dramatique", x: ["Un ton burlesque", "Un ton documentaire", "Un ton musical"], acc: ["dramatique", "ton dramatique", "sombre"] },
]);
