import { universe } from "../_build";

export const musiquefrancaise = universe("france", "Musique française", [
  // --- Faciles (5) ---
  { id: "frmus-f1", d: 1, t: "Quel chanteur est surnommé « le taulier » du rock français, décédé en 2017 ?", a: "Johnny Hallyday", x: ["Eddy Mitchell", "Jacques Dutronc", "Michel Sardou"] },
  { id: "frmus-f2", d: 1, t: "Quelle chanteuse à la voix puissante a chanté « L'Hymne à l'amour » et « Non, je ne regrette rien » ?", a: "Édith Piaf", x: ["Dalida", "Barbara", "Mireille Mathieu"], acc: ["piaf", "édith piaf"] },
  { id: "frmus-f3", d: 1, t: "Quel chanteur belge a écrit « Ne me quitte pas » et « Amsterdam » ?", a: "Jacques Brel", x: ["Georges Brassens", "Léo Ferré", "Charles Aznavour"] },
  { id: "frmus-f4", d: 1, t: "Quel chanteur à moustache et à la guitare a écrit « Les Copains d'abord » ?", a: "Georges Brassens", x: ["Jacques Brel", "Léo Ferré", "Serge Gainsbourg"] },
  { id: "frmus-f5", d: 1, t: "Quel artiste provocateur a écrit « La Javanaise » et « Je t'aime... moi non plus » ?", a: "Serge Gainsbourg", x: ["Jacques Dutronc", "Alain Bashung", "Michel Polnareff"] },
  // --- Moyennes (10) ---
  { id: "frmus-m1", d: 2, t: "Quel chanteur d'origine arménienne a interprété « La Bohème » et « Emmenez-moi » ?", a: "Charles Aznavour", x: ["Charles Trenet", "Gilbert Bécaud", "Yves Montand"] },
  { id: "frmus-m2", d: 2, t: "Quel chanteur au chapeau a écrit « La Mer » et « Y'a d'la joie » ?", a: "Charles Trenet", x: ["Charles Aznavour", "Maurice Chevalier", "Tino Rossi"] },
  { id: "frmus-m3", d: 2, t: "Quelle chanteuse d'origine égyptienne a marqué la variété avec « Gigi l'Amoroso » et « Paroles, paroles » ?", a: "Dalida", x: ["Sheila", "Mireille Mathieu", "France Gall"] },
  { id: "frmus-m4", d: 2, t: "Quelle chanteuse yé-yé a interprété « Poupée de cire, poupée de son », écrite par Gainsbourg ?", a: "France Gall", x: ["Sylvie Vartan", "Françoise Hardy", "Sheila"] },
  { id: "frmus-m5", d: 2, t: "Quelle icône yé-yé a chanté « Tous les garçons et les filles » ?", a: "Françoise Hardy", x: ["France Gall", "Sylvie Vartan", "Jane Birkin"] },
  { id: "frmus-m6", d: 2, t: "Quel chanteur populaire a écrit « Les Lacs du Connemara » et « La Maladie d'amour » ?", a: "Michel Sardou", x: ["Michel Delpech", "Joe Dassin", "Michel Fugain"] },
  { id: "frmus-m7", d: 2, t: "Quel chanteur américain installé en France a chanté « Les Champs-Élysées » et « L'Été indien » ?", a: "Joe Dassin", x: ["Michel Sardou", "Michel Delpech", "Claude François"] },
  { id: "frmus-m8", d: 2, t: "Quel chanteur a lancé « Alexandrie Alexandra » et « Le Téléphone pleure » ?", a: "Claude François", x: ["Joe Dassin", "Michel Polnareff", "Sacha Distel"], acc: ["claude françois", "cloclo"] },
  { id: "frmus-m9", d: 2, t: "Quel chanteur à lunettes et boucles blondes a chanté « Holidays » et « Lettre à France » ?", a: "Michel Polnareff", x: ["Christophe", "Alain Souchon", "Julien Clerc"] },
  { id: "frmus-m10", d: 2, t: "Quel duo électro français masqué a conquis le monde avec « Get Lucky » et « One More Time » ?", a: "Daft Punk", x: ["Justice", "Air", "Cassius"] },
  // --- Dures (15) ---
  { id: "frmus-d1", d: 3, t: "Quel groupe électro français a sorti l'album « Moon Safari » en 1998 ?", a: "Air", x: ["Daft Punk", "Justice", "Phoenix"] },
  { id: "frmus-d2", d: 3, t: "Quel duo français au logo en croix a sorti l'album « Cross » et le tube « D.A.N.C.E. » ?", a: "Justice", x: ["Daft Punk", "Air", "Cassius"] },
  { id: "frmus-d3", d: 3, t: "Quel groupe de rock français, mené par Thomas Mars, a chanté « 1901 » et « Lisztomania » ?", a: "Phoenix", x: ["Air", "Tahiti 80", "The Dø"] },
  { id: "frmus-d4", d: 3, t: "Quel chanteur à la voix rauque a signé « Gaby oh Gaby » et « La Nuit je mens » ?", a: "Alain Bashung", x: ["Alain Souchon", "Jacques Higelin", "Christophe"] },
  { id: "frmus-d5", d: 3, t: "Quel chanteur, complice de Laurent Voulzy, a écrit « Foule sentimentale » ?", a: "Alain Souchon", x: ["Alain Bashung", "Julien Clerc", "Francis Cabrel"] },
  { id: "frmus-d6", d: 3, t: "Quel chanteur du Sud-Ouest a écrit « Petite Marie » et « L'Encre de tes yeux » ?", a: "Francis Cabrel", x: ["Jean-Jacques Goldman", "Alain Souchon", "Michel Berger"] },
  { id: "frmus-d7", d: 3, t: "Quel auteur-compositeur discret a écrit « Envole-moi » et « Comme toi » ?", a: "Jean-Jacques Goldman", x: ["Michel Berger", "Francis Cabrel", "Daniel Balavoine"] },
  { id: "frmus-d8", d: 3, t: "Quel chanteur engagé, mort en 1986 dans un crash d'hélicoptère, a chanté « Mon fils, ma bataille » ?", a: "Daniel Balavoine", x: ["Michel Berger", "Michel Delpech", "Alain Bashung"] },
  { id: "frmus-d9", d: 3, t: "Quel compositeur a créé l'opéra-rock « Starmania » avec Luc Plamondon ?", a: "Michel Berger", x: ["Jean-Jacques Goldman", "Daniel Balavoine", "William Sheller"] },
  { id: "frmus-d10", d: 3, t: "Quelle chanteuse, épouse de Michel Berger, a chanté « Résiste » et « Message personnel » ?", a: "France Gall", x: ["Véronique Sanson", "Catherine Lara", "Julie Pietri"] },
  { id: "frmus-d11", d: 3, t: "Quel groupe de rock alternatif, mené par Bertrand Cantat, a marqué les années 80-90 ?", a: "Noir Désir", x: ["Téléphone", "Indochine", "Mano Negra"] },
  { id: "frmus-d12", d: 3, t: "Quel groupe de rock français, avec Jean-Louis Aubert, a chanté « Cendrillon » et « Un autre monde » ?", a: "Téléphone", x: ["Trust", "Indochine", "Noir Désir"] },
  { id: "frmus-d13", d: 3, t: "Quel groupe mené par Nicola Sirkis a chanté « L'Aventurier » et « J'ai demandé à la lune » ?", a: "Indochine", x: ["Téléphone", "Kyo", "Noir Désir"] },
  { id: "frmus-d14", d: 3, t: "Quel groupe métissé de Manu Chao a chanté « Mala Vida » ?", a: "Mano Negra", x: ["Les Négresses Vertes", "Zebda", "La Rue Kétanou"] },
  { id: "frmus-d15", d: 3, t: "Quel maître de la chanson à texte engagée a chanté « Avec le temps » ?", a: "Léo Ferré", x: ["Georges Brassens", "Jacques Brel", "Jean Ferrat"] },
  // --- Pro (20) ---
  { id: "frmus-p1", d: 4, t: "Quelle chanteuse québécoise a chanté « Pour que tu m'aimes encore » ?", a: "Céline Dion", x: ["Lara Fabian", "Patricia Kaas", "Isabelle Boulay"] },
  { id: "frmus-p2", d: 4, t: "Quel opéra-rock de 1998 de Cocciante et Plamondon a lancé le tube « Belle » ?", a: "Notre-Dame de Paris", x: ["Starmania", "Les Dix Commandements", "Roméo et Juliette"], acc: ["notre-dame de paris"] },
  { id: "frmus-p3", d: 4, t: "Quel trio a interprété « Belle » dans « Notre-Dame de Paris » ?", a: "Garou, Lavoie et Fiori", x: ["Balavoine, Berger et Goldman", "Bruel, Cabrel et Obispo", "Calogero, Kaas et Zazie"], acc: ["garou lavoie fiori"] },
  { id: "frmus-p4", d: 4, t: "Quel chanteur québécois à la voix rauque a percé avec le rôle de Quasimodo ?", a: "Garou", x: ["Roch Voisine", "Corneille", "Grégory Lemarchal"] },
  { id: "frmus-p5", d: 4, t: "Quel membre du groupe de rap marseillais IAM porte le pseudonyme « Akhenaton » ?", a: "Akhenaton", x: ["Shurik'n", "Soprano", "Sat"], acc: ["akhenaton"] },
  { id: "frmus-p6", d: 4, t: "Quel groupe de rap marseillais a chanté « Je danse le Mia » ?", a: "IAM", x: ["NTM", "Fonky Family", "Psy 4 de la Rime"] },
  { id: "frmus-p7", d: 4, t: "Quelle chanteuse à texte, poétesse de la nuit, a chanté « L'Aigle noir » ?", a: "Barbara", x: ["Juliette Gréco", "Anne Sylvestre", "Cora Vaucaire"] },
  { id: "frmus-p8", d: 4, t: "Quelle égérie de Saint-Germain-des-Prés a chanté « Déshabillez-moi » ?", a: "Juliette Gréco", x: ["Barbara", "Cora Vaucaire", "Catherine Sauvage"] },
  { id: "frmus-p9", d: 4, t: "Quelle star du music-hall d'avant-guerre chantait « Prosper » et « Ma pomme » ?", a: "Maurice Chevalier", x: ["Charles Trenet", "Tino Rossi", "Fernandel"] },
  { id: "frmus-p10", d: 4, t: "Quel compositeur français a écrit le « Boléro », pièce orchestrale répétitive ?", a: "Maurice Ravel", x: ["Claude Debussy", "Erik Satie", "Camille Saint-Saëns"] },
  { id: "frmus-p11", d: 4, t: "Quel compositeur impressionniste a écrit « Clair de lune » et « La Mer » ?", a: "Claude Debussy", x: ["Maurice Ravel", "Gabriel Fauré", "Erik Satie"] },
  { id: "frmus-p12", d: 4, t: "Quel compositeur excentrique a écrit les « Gymnopédies » ?", a: "Erik Satie", x: ["Claude Debussy", "Maurice Ravel", "Francis Poulenc"] },
  { id: "frmus-p13", d: 4, t: "Quel pionnier français de la musique électronique a composé « Oxygène » ?", a: "Jean-Michel Jarre", x: ["Vangelis", "Space", "Cerrone"] },
  { id: "frmus-p14", d: 4, t: "Quelle chanteuse et actrice, fille de Serge Gainsbourg et Jane Birkin, a chanté « Lemon Incest » enfant ?", a: "Charlotte Gainsbourg", x: ["Vanessa Paradis", "Lou Doillon", "Jane Birkin"] },
  { id: "frmus-p15", d: 4, t: "Quelle jeune chanteuse a percé à quatorze ans avec « Joe le taxi » en 1987 ?", a: "Vanessa Paradis", x: ["Charlotte Gainsbourg", "Elsa", "Lio"] },
  { id: "frmus-p16", d: 4, t: "Quel groupe de rap, avec Kool Shen et JoeyStarr, vient de Seine-Saint-Denis ?", a: "NTM", x: ["IAM", "Ministère A.M.E.R.", "Assassin"], acc: ["ntm", "suprême ntm"] },
  { id: "frmus-p17", d: 4, t: "Qui a écrit « Comme d'habitude », reprise par Frank Sinatra en « My Way » ?", a: "Claude François", x: ["Michel Sardou", "Gilbert Bécaud", "Hervé Vilard"], acc: ["claude françois"] },
  { id: "frmus-p18", d: 4, t: "Quel groupe de world music toulousain a chanté « Tomber la chemise » ?", a: "Zebda", x: ["Mano Negra", "Les Négresses Vertes", "Louise Attaque"] },
  { id: "frmus-p19", d: 4, t: "Quel groupe folk-rock a chanté « J't'emmène au vent » et « Léa » ?", a: "Louise Attaque", x: ["Tryo", "Les Wampas", "La Rue Kétanou"] },
  { id: "frmus-p20", d: 4, t: "Quel artiste belge a chanté « Formidable » et « Alors on danse » ?", a: "Stromae", x: ["Angèle", "Damso", "Roméo Elvis"] },
]);
