import { universe } from "../_build";

export const seriesfrancaises = universe("france", "Séries françaises", [
  // --- Faciles (5) ---
  { id: "frserie-f1", d: 1, t: "Quelle série de Canal+ suit les agents d'une agence artistique dans « Dix pour cent » ?", a: "Dix pour cent", x: ["Fais pas ci fais pas ça", "Un gars une fille", "Kaamelott"], acc: ["dix pour cent", "call my agent"] },
  { id: "frserie-f2", d: 1, t: "Quelle série humoristique médiévale d'Alexandre Astier parodie la légende du roi Arthur ?", a: "Kaamelott", x: ["Hero Corp", "Visiteurs", "Camelot"], acc: ["kaamelott"] },
  { id: "frserie-f3", d: 1, t: "Quel programme court met en scène le couple Jean et Alex, joué par Dujardin et Lamy ?", a: "Un gars, une fille", x: ["Caméra Café", "Scènes de ménages", "Nos chers voisins"], acc: ["un gars une fille"] },
  { id: "frserie-f4", d: 1, t: "Quelle série se déroule autour de la machine à café d'une entreprise ?", a: "Caméra Café", x: ["Un gars une fille", "Kaamelott", "Bref"] },
  { id: "frserie-f5", d: 1, t: "Quelle mini-série de Canal+ raconte à toute vitesse le quotidien d'un trentenaire paumé ?", a: "Bref", x: ["Kaamelott", "Caméra Café", "Serge le Mytho"], acc: ["bref"] },
  // --- Moyennes (10) ---
  { id: "frserie-m1", d: 2, t: "Quelle série d'espionnage de Canal+ suit les agents de la DGSE, dont Malotru ?", a: "Le Bureau des légendes", x: ["Le Baron noir", "Braquo", "Engrenages"], acc: ["bureau des légendes"] },
  { id: "frserie-m2", d: 2, t: "Quelle série politique de Canal+ suit l'ascension du maire Philippe Rickwaert ?", a: "Le Baron noir", x: ["Le Bureau des légendes", "Les Hommes de l'ombre", "Marseille"] },
  { id: "frserie-m3", d: 2, t: "Quelle série policière de Canal+ suit une juge et les flics du « 36 » à Paris ?", a: "Engrenages", x: ["Braquo", "Section de recherches", "Profilage"], acc: ["engrenages", "spiral"] },
  { id: "frserie-m4", d: 2, t: "Quelle série fantastique de 2012 voit des morts revenir dans une ville de montagne ?", a: "Les Revenants", x: ["Zone Blanche", "Marianne", "La Forêt"] },
  { id: "frserie-m5", d: 2, t: "Quelle série de France 2 suit une famille recomposée dans « Fais pas ci, fais pas ça » ?", a: "Fais pas ci, fais pas ça", x: ["Clem", "Une famille formidable", "En famille"] },
  { id: "frserie-m6", d: 2, t: "Quelle série jeunesse des années 90, avec Hélène, était un pilier du Club Dorothée ?", a: "Hélène et les Garçons", x: ["Premiers Baisers", "Le Miel et les Abeilles", "Salut les Musclés"], acc: ["hélène et les garçons"] },
  { id: "frserie-m7", d: 2, t: "Quel feuilleton quotidien de France 3, à Marseille, a duré de 2004 à 2022 ?", a: "Plus belle la vie", x: ["Un si grand soleil", "Demain nous appartient", "Ici tout commence"], acc: ["plus belle la vie"] },
  { id: "frserie-m8", d: 2, t: "Quelle série d'humour de M6 met en scène des couples à table et au quotidien ?", a: "Scènes de ménages", x: ["Nos chers voisins", "En famille", "Parents mode d'emploi"], acc: ["scènes de ménages"] },
  { id: "frserie-m9", d: 2, t: "Quel feuilleton quotidien de TF1 suit les habitants de la ville fictive de Sète ?", a: "Demain nous appartient", x: ["Ici tout commence", "Plus belle la vie", "Un si grand soleil"], acc: ["demain nous appartient"] },
  { id: "frserie-m10", d: 2, t: "Quelle série sur une école de cuisine prolonge l'univers de « Demain nous appartient » ?", a: "Ici tout commence", x: ["Demain nous appartient", "Plus belle la vie", "Un si grand soleil"], acc: ["ici tout commence"] },
  // --- Dures (15) ---
  { id: "frserie-d1", d: 3, t: "Quelle série de TF1 suit Morgane Alvaro, femme de ménage surdouée aidant la police ?", a: "HPI", x: ["Astrid et Raphaëlle", "Balthazar", "Munch"], acc: ["hpi"] },
  { id: "frserie-d2", d: 3, t: "Quelle série de France 2 associe une documentaliste autiste à une commandante de police ?", a: "Astrid et Raphaëlle", x: ["HPI", "Balthazar", "Candice Renoir"], acc: ["astrid et raphaëlle"] },
  { id: "frserie-d3", d: 3, t: "Quel médecin légiste charmeur résout des crimes dans la série de TF1 « Balthazar » ?", a: "Balthazar", x: ["Profilage", "Munch", "Section de recherches"], acc: ["balthazar"] },
  { id: "frserie-d4", d: 3, t: "Quelle série de Canal+ plonge dans le milieu du rap français, avec le personnage d'Apash ?", a: "Validé", x: ["Le Bureau des légendes", "Engrenages", "Braqueurs"], acc: ["validé"] },
  { id: "frserie-d5", d: 3, t: "Quelle série d'Arte de Fanny Herrero suit de jeunes humoristes qui montent à Paris ?", a: "Drôle", x: ["Dix pour cent", "En thérapie", "Standing Ovation"], acc: ["drôle"] },
  { id: "frserie-d6", d: 3, t: "Quelle série d'Arte adapte un format israélien, avec un psy après le 13-Novembre ?", a: "En thérapie", x: ["Dérapages", "Le Bazar de la Charité", "Les Sauvages"], acc: ["en thérapie"] },
  { id: "frserie-d7", d: 3, t: "Quelle série historique de TF1 sur l'incendie d'un bazar en 1897 réunit Audrey Fleurot et Julie de Bona ?", a: "Le Bazar de la Charité", x: ["Le Bonheur des Dames", "Guillaume Tell", "Ainsi soient-ils"], acc: ["bazar de la charité"] },
  { id: "frserie-d8", d: 3, t: "Quelle série chorale d'Arte suit un candidat d'origine maghrébine à la présidentielle ?", a: "Les Sauvages", x: ["Le Baron noir", "Les Hommes de l'ombre", "Section Zéro"], acc: ["les sauvages"] },
  { id: "frserie-d9", d: 3, t: "Quelle émission de sketchs de Canal+ des années 2000 a révélé le duo Omar et Fred ?", a: "Le SAV des émissions", x: ["Groland", "Les Guignols", "Action Discrète"], acc: ["sav des émissions", "omar et fred"] },
  { id: "frserie-d10", d: 3, t: "Quelle émission satirique de Canal+ met en scène des marionnettes de personnalités ?", a: "Les Guignols de l'info", x: ["Groland", "Le Petit Journal", "Le Bébête Show"], acc: ["guignols", "les guignols"] },
  { id: "frserie-d11", d: 3, t: "Quelle émission à marionnettes satiriques a précédé les Guignols sur TF1 ?", a: "Le Bébête Show", x: ["Les Guignols", "Groland", "Spitting Image"], acc: ["bébête show"] },
  { id: "frserie-d12", d: 3, t: "Quelle série de France 2 suit un enquêteur bourru en fauteuil roulant, « Caïn » ?", a: "Caïn", x: ["Balthazar", "Profilage", "Nicolas Le Floch"], acc: ["caïn"] },
  { id: "frserie-d13", d: 3, t: "Quelle série historique adapte les enquêtes du commissaire Nicolas Le Floch au XVIIIe siècle ?", a: "Nicolas Le Floch", x: ["Vidocq", "Les Petits Meurtres d'Agatha Christie", "Lupin"], acc: ["nicolas le floch"] },
  { id: "frserie-d14", d: 3, t: "Quelle série de France 2 transpose les enquêtes d'Agatha Christie en France ?", a: "Les Petits Meurtres d'Agatha Christie", x: ["Nicolas Le Floch", "Caïn", "Candice Renoir"], acc: ["petits meurtres d'agatha christie"] },
  { id: "frserie-d15", d: 3, t: "Quelle série policière de France 2, en bord de mer, suit la commandante Candice Renoir ?", a: "Candice Renoir", x: ["Balthazar", "Caïn", "Léo Matteï"], acc: ["candice renoir"] },
  // --- Pro (20) ---
  { id: "frserie-p1", d: 4, t: "Quelle série de TF1 des années 90, sur des sauveteurs, était tournée à Saint-Tropez ?", a: "Sous le soleil", x: ["Les Filles d'à côté", "Julie Lescaut", "Navarro"], acc: ["sous le soleil"] },
  { id: "frserie-p2", d: 4, t: "Quel commissaire incarné par Roger Hanin a marqué TF1 pendant des années ?", a: "Navarro", x: ["Julie Lescaut", "Maigret", "Nestor Burma"], acc: ["navarro"] },
  { id: "frserie-p3", d: 4, t: "Quelle femme commissaire, incarnée par Véronique Genest, a duré vingt ans sur TF1 ?", a: "Julie Lescaut", x: ["Candice Renoir", "Navarro", "Femmes de loi"], acc: ["julie lescaut"] },
  { id: "frserie-p4", d: 4, t: "Quelle série de Canal+ en costumes retrace la cour de Louis XIV à Versailles ?", a: "Versailles", x: ["Marseille", "Borgia", "Le Bureau des légendes"], acc: ["versailles"] },
  { id: "frserie-p5", d: 4, t: "Quelle série, première française de Netflix, met Gérard Depardieu en maire de Marseille ?", a: "Marseille", x: ["Versailles", "Plan Cœur", "Family Business"], acc: ["marseille"] },
  { id: "frserie-p6", d: 4, t: "Quel acteur incarne l'agent Malotru dans « Le Bureau des légendes » ?", a: "Mathieu Kassovitz", x: ["Jean Dujardin", "Vincent Cassel", "Roschdy Zem"] },
  { id: "frserie-p7", d: 4, t: "Quel humoriste incarne le roi Arthur dans « Kaamelott » ?", a: "Alexandre Astier", x: ["Franck Pitiot", "Lionnel Astier", "Thomas Cousseau"] },
  { id: "frserie-p8", d: 4, t: "Quelle actrice rousse incarne l'agente Andréa Martel dans « Dix pour cent » ?", a: "Camille Cottin", x: ["Audrey Fleurot", "Marina Foïs", "Laure Calamy"] },
  { id: "frserie-p9", d: 4, t: "Quelle actrice incarne l'assistante Noémie dans « Dix pour cent » ?", a: "Laure Calamy", x: ["Camille Cottin", "Audrey Fleurot", "Nathalie Baye"] },
  { id: "frserie-p10", d: 4, t: "Quelle série jeunesse des années 90, sur un groupe de musiciens, s'appelle « Le Miel et les Abeilles » ?", a: "Le Miel et les Abeilles", x: ["Hélène et les Garçons", "Premiers Baisers", "Salut les Musclés"], acc: ["miel et les abeilles"] },
  { id: "frserie-p11", d: 4, t: "Quel producteur d'AB Productions a produit « Hélène et les Garçons » ?", a: "Jean-Luc Azoulay", x: ["Claude Berda", "Dominique Farrugia", "Alain Chabat"], acc: ["azoulay", "jean-luc azoulay"] },
  { id: "frserie-p12", d: 4, t: "Quelle comédie française de Netflix suit une famille qui reconvertit sa boucherie dans le cannabis ?", a: "Family Business", x: ["Plan Cœur", "Mortel", "Lupin"], acc: ["family business"] },
  { id: "frserie-p13", d: 4, t: "Quelle série de France 2 sur de jeunes séminaristes s'intitule « Ainsi soient-ils » ?", a: "Ainsi soient-ils", x: ["En thérapie", "Les Sauvages", "P'tit Quinquin"], acc: ["ainsi soient-ils"] },
  { id: "frserie-p14", d: 4, t: "Quelle mini-série policière burlesque de Bruno Dumont se déroule dans le Nord ?", a: "P'tit Quinquin", x: ["Ainsi soient-ils", "Les Revenants", "Zone Blanche"], acc: ["p'tit quinquin"] },
  { id: "frserie-p15", d: 4, t: "Quelle série de Canal+ de Fabrice Gobert suit des morts revenus dans les Alpes ?", a: "Les Revenants", x: ["Zone Blanche", "Marianne", "La Forêt"], acc: ["les revenants"] },
  { id: "frserie-p16", d: 4, t: "Quelle émission satirique de Canal+ met en scène le pays fictif de Groland ?", a: "Groland", x: ["Les Guignols", "Action Discrète", "Le Petit Journal"], acc: ["groland"] },
  { id: "frserie-p17", d: 4, t: "Quelle sitcom de Canal+ des années 90, avec Jamel Debbouze, se déroule dans un hôpital ?", a: "H", x: ["Caméra Café", "Kaamelott", "Bref"], acc: ["série h"] },
  { id: "frserie-p18", d: 4, t: "Quelle série de France 3, en montagne, suit un gendarme nommé Alex Hugo ?", a: "Alex Hugo", x: ["Section de recherches", "Léo Matteï", "Cassandre"], acc: ["alex hugo"] },
  { id: "frserie-p19", d: 4, t: "Quelle mini-série thriller d'Arte, avec Éric Cantona, s'intitule « Dérapages » ?", a: "Dérapages", x: ["Les Sauvages", "En thérapie", "Le Bureau des légendes"], acc: ["dérapages"] },
  { id: "frserie-p20", d: 4, t: "Quelle série française de Netflix, thriller fantastique pour adolescents, s'intitule « Mortel » ?", a: "Mortel", x: ["Family Business", "Plan Cœur", "Osmosis"], acc: ["mortel"] },
]);
