import { universe } from "../_build";

export const beauteEtParfums = universe("mode", "Beauté et parfums", [
  // --- Faciles (5) ---
  { id: "beaute-f1", d: 1, t: "Quel parfum de Chanel, lancé en 1921, est l'un des plus célèbres au monde ?", a: "N°5", x: ["J'adore", "Opium", "Shalimar"], acc: ["n°5", "numéro 5", "no 5"] },
  { id: "beaute-f2", d: 1, t: "Comment appelle-t-on la version d'un parfum la plus concentrée et la plus tenace ?", a: "Le parfum", x: ["L'eau de toilette", "L'eau de Cologne", "Le déodorant"], acc: ["extrait", "parfum"] },
  { id: "beaute-f3", d: 1, t: "Quelle maison française de luxe vend le parfum « J'adore » ?", a: "Dior", x: ["Chanel", "Guerlain", "Lancôme"] },
  { id: "beaute-f4", d: 1, t: "Comment appelle-t-on le produit de maquillage qui colore les lèvres ?", a: "Le rouge à lèvres", x: ["Le mascara", "Le fond de teint", "Le fard à joues"], acc: ["rouge à lèvres"] },
  { id: "beaute-f5", d: 1, t: "Comment appelle-t-on le maquillage qui allonge et épaissit les cils ?", a: "Le mascara", x: ["L'eye-liner", "Le rouge à lèvres", "Le blush"], acc: ["mascara"] },
  // --- Moyennes (10) ---
  { id: "beaute-m1", d: 2, t: "Quelle maison française, pionnière de la parfumerie, a créé « Shalimar » ?", a: "Guerlain", x: ["Chanel", "Dior", "Caron"] },
  { id: "beaute-m2", d: 2, t: "Comment appelle-t-on les trois niveaux d'un parfum qui se révèlent dans le temps ?", a: "Les notes de tête, de cœur et de fond", x: ["Les couches", "Les accords majeurs", "Les strates"], acc: ["notes de tête de cœur et de fond"] },
  { id: "beaute-m3", d: 2, t: "Comment appelle-t-on le créateur de parfums ?", a: "Le nez", x: ["Le sommelier", "L'olfacteur", "Le distillateur"], acc: ["nez", "parfumeur"] },
  { id: "beaute-m4", d: 2, t: "Quelle marque française est le plus grand groupe de cosmétiques au monde ?", a: "L'Oréal", x: ["Estée Lauder", "Coty", "Shiseido"], acc: ["oréal", "l'oréal"] },
  { id: "beaute-m5", d: 2, t: "Quel slogan accompagne la marque L'Oréal ?", a: "Parce que je le vaux bien", x: ["La beauté est partout", "Vivez sans complexe", "La vie est belle"], acc: ["parce que je le vaux bien"] },
  { id: "beaute-m6", d: 2, t: "Quel parfum masculin culte de Dior existe depuis 1966 ?", a: "Eau Sauvage", x: ["Fahrenheit", "Sauvage", "Dior Homme"], acc: ["eau sauvage"] },
  { id: "beaute-m7", d: 2, t: "Quelle maison japonaise est un géant mondial des cosmétiques de luxe ?", a: "Shiseido", x: ["Shu Uemura", "SK-II", "Kanebo"] },
  { id: "beaute-m8", d: 2, t: "Comment appelle-t-on le produit qui unifie le teint du visage ?", a: "Le fond de teint", x: ["Le blush", "L'anticernes", "La poudre libre"], acc: ["fond de teint"] },
  { id: "beaute-m9", d: 2, t: "Quelle famille olfactive regroupe les parfums à la rose, au jasmin et aux fleurs ?", a: "La famille florale", x: ["La famille boisée", "La famille orientale", "La famille hespéridée"], acc: ["florale", "floral"] },
  { id: "beaute-m10", d: 2, t: "Quel type d'ingrédient domine les parfums « hespéridés », frais et pétillants ?", a: "Les agrumes", x: ["Les roses", "Les bois", "Les épices"], acc: ["agrumes", "citron"] },
  // --- Dures (15) ---
  { id: "beaute-d1", d: 3, t: "Quel parfumeur a composé le Chanel N°5 ?", a: "Ernest Beaux", x: ["Jacques Guerlain", "François Coty", "Edmond Roudnitska"] },
  { id: "beaute-d2", d: 3, t: "Quel « nez » a créé de nombreux parfums cultes, dont « Eau Sauvage » de Dior ?", a: "Edmond Roudnitska", x: ["Ernest Beaux", "Jean-Claude Ellena", "Jacques Polge"] },
  { id: "beaute-d3", d: 3, t: "Quel parfumeur maison a longtemps créé les parfums de Chanel après Ernest Beaux ?", a: "Jacques Polge", x: ["Jean-Claude Ellena", "François Demachy", "Alberto Morillas"] },
  { id: "beaute-d4", d: 3, t: "Quel « nez » minimaliste a été le parfumeur exclusif d'Hermès ?", a: "Jean-Claude Ellena", x: ["Jacques Polge", "François Demachy", "Alberto Morillas"] },
  { id: "beaute-d5", d: 3, t: "Quel matériau rare, sécrété par le cachalot, était utilisé en parfumerie ?", a: "L'ambre gris", x: ["Le musc", "Le santal", "La civette"], acc: ["ambre gris"] },
  { id: "beaute-d6", d: 3, t: "Quelle note animale, aujourd'hui synthétique, provenait à l'origine d'une glande de cervidé ?", a: "Le musc", x: ["L'ambre gris", "La civette", "Le castoréum"], acc: ["musc"] },
  { id: "beaute-d7", d: 3, t: "Quelle fleur, récoltée à la main à l'aube autour de Grasse, est un joyau de la parfumerie ?", a: "Le jasmin", x: ["La tubéreuse", "La rose de mai", "Le muguet"], acc: ["jasmin"] },
  { id: "beaute-d8", d: 3, t: "Quelle ville du sud de la France est la capitale mondiale du parfum ?", a: "Grasse", x: ["Cannes", "Nice", "Avignon"], acc: ["grasse"] },
  { id: "beaute-d9", d: 3, t: "Quel parfum d'Yves Saint Laurent de 1977 a fait scandale par son nom sulfureux ?", a: "Opium", x: ["Paris", "Kouros", "Rive Gauche"], acc: ["opium"] },
  { id: "beaute-d10", d: 3, t: "Quel parfum de Thierry Mugler, en flacon étoilé, sent le sucre et le patchouli ?", a: "Angel", x: ["Alien", "Womanity", "Aura"], acc: ["angel"] },
  { id: "beaute-d11", d: 3, t: "Quel parfum de Jean-Paul Gaultier est présenté dans un flacon en forme de buste de femme ?", a: "Classique", x: ["Le Mâle", "Scandal", "La Belle"], acc: ["classique"] },
  { id: "beaute-d12", d: 3, t: "Quel parfum masculin de Jean-Paul Gaultier a un flacon en forme de torse de marin ?", a: "Le Mâle", x: ["Classique", "Kokorico", "Ultra Male"], acc: ["le mâle"] },
  { id: "beaute-d13", d: 3, t: "Quelle marque de cosmétiques, fondée par une femme éponyme, était la rivale d'Helena Rubinstein ?", a: "Elizabeth Arden", x: ["Estée Lauder", "Max Factor", "Revlon"] },
  { id: "beaute-d14", d: 3, t: "Quelle marque de maquillage, prisée des professionnels, a pour initiales « M.A.C » ?", a: "MAC Cosmetics", x: ["NARS", "Bobbi Brown", "Make Up For Ever"], acc: ["mac", "mac cosmetics"] },
  { id: "beaute-d15", d: 3, t: "Quel maquilleur français a donné son nom à une marque de maquillage de luxe ?", a: "François Nars", x: ["Terry de Gunzburg", "Bobbi Brown", "Charlotte Tilbury"] },
  // --- Pro (20) ---
  { id: "beaute-p1", d: 4, t: "Quel roman de Patrick Süskind raconte l'histoire d'un parfumeur meurtrier ?", a: "Le Parfum", x: ["L'Écume des jours", "Le Nez", "Chanel Solitaire"], acc: ["le parfum"] },
  { id: "beaute-p2", d: 4, t: "Quelle famille olfactive, chaude et épicée, évoque l'ambre, la vanille et les épices ?", a: "La famille orientale", x: ["La famille florale", "La famille boisée", "La famille fougère"], acc: ["orientale"] },
  { id: "beaute-p3", d: 4, t: "Quelle famille de parfums masculins associe lavande, mousse de chêne et coumarine ?", a: "La famille fougère", x: ["La famille chyprée", "La famille orientale", "La famille hespéridée"], acc: ["fougère"] },
  { id: "beaute-p4", d: 4, t: "Quel accord, du nom d'une île, mêle bergamote, mousse de chêne et patchouli ?", a: "L'accord chypre", x: ["L'accord fougère", "L'accord ambré", "L'accord marin"], acc: ["chypre"] },
  { id: "beaute-p5", d: 4, t: "Quel parfum de Guerlain de 1925, poudré et sensuel, est une légende ?", a: "Shalimar", x: ["Mitsouko", "L'Heure Bleue", "Jicky"], acc: ["shalimar"] },
  { id: "beaute-p6", d: 4, t: "Quel parfum chypré de Guerlain de 1919 porte un nom japonais ?", a: "Mitsouko", x: ["Shalimar", "Samsara", "Nahéma"], acc: ["mitsouko"] },
  { id: "beaute-p7", d: 4, t: "Quel groupe américain, fondé par une femme, possède Clinique, La Mer et MAC ?", a: "Estée Lauder", x: ["L'Oréal", "Coty", "Shiseido"] },
  { id: "beaute-p8", d: 4, t: "Quelle rivale d'Elizabeth Arden a bâti un empire de cosmétiques au début du XXe siècle ?", a: "Helena Rubinstein", x: ["Estée Lauder", "Coco Chanel", "Madame Rochas"] },
  { id: "beaute-p9", d: 4, t: "Quel « nez » star a créé de nombreux best-sellers, dont « Angel » de Mugler ?", a: "Olivier Cresp", x: ["Alberto Morillas", "Jacques Cavallier", "Dominique Ropion"] },
  { id: "beaute-p10", d: 4, t: "Quel parfumeur suisse prolifique a créé « CK One » et « Acqua di Gio » ?", a: "Alberto Morillas", x: ["Olivier Cresp", "Dominique Ropion", "Jean-Claude Ellena"] },
  { id: "beaute-p11", d: 4, t: "Quel parfum unisexe de Calvin Klein de 1994 a lancé la mode des parfums mixtes ?", a: "CK One", x: ["Obsession", "Eternity", "Escape"], acc: ["ck one"] },
  { id: "beaute-p12", d: 4, t: "Quel parfum masculin de Dior de 2015, avec Johnny Depp, a battu des records de vente ?", a: "Sauvage", x: ["Eau Sauvage", "Fahrenheit", "Dior Homme"], acc: ["sauvage"] },
  { id: "beaute-p13", d: 4, t: "Quelle marque a popularisé le maquillage moderne à Hollywood et le mascara waterproof ?", a: "Max Factor", x: ["Revlon", "Maybelline", "Rimmel"] },
  { id: "beaute-p14", d: 4, t: "Quelle molécule de synthèse, un musc blanc, est omniprésente dans les parfums modernes ?", a: "Le galaxolide", x: ["L'ambroxan", "L'hédione", "Le calone"], acc: ["galaxolide"] },
  { id: "beaute-p15", d: 4, t: "Quelle note synthétique marine, évoquant l'air du large, a marqué les parfums des années 90 ?", a: "Le calone", x: ["L'ambroxan", "Le galaxolide", "L'Iso E Super"], acc: ["calone"] },
  { id: "beaute-p16", d: 4, t: "Quel parfum de Paco Rabanne, au flacon en lingot d'or, est un best-seller masculin ?", a: "1 Million", x: ["Invictus", "Phantom", "Pure XS"], acc: ["1 million", "one million"] },
  { id: "beaute-p17", d: 4, t: "Quel parfum féminin de Lancôme a pour égérie l'actrice oscarisée Julia Roberts ?", a: "La Vie est belle", x: ["Trésor", "Idôle", "Miracle"], acc: ["la vie est belle"] },
  { id: "beaute-p18", d: 4, t: "Quel soin anti-âge ultra-luxe à base d'algue est un produit culte du groupe Estée Lauder ?", a: "La crème de La Mer", x: ["La crème Nivea", "Le sérum Vichy", "La crème Embryolisse"], acc: ["la mer", "crème de la mer"] },
  { id: "beaute-p19", d: 4, t: "Quelle maison de parfums de niche est connue pour « Baccarat Rouge 540 » ?", a: "Maison Francis Kurkdjian", x: ["Le Labo", "Byredo", "Diptyque"], acc: ["francis kurkdjian", "kurkdjian"] },
  { id: "beaute-p20", d: 4, t: "Quelle marque de niche est connue pour ses parfums aux noms de codes, comme « Santal 33 » ?", a: "Le Labo", x: ["Byredo", "Diptyque", "Maison Margiela"], acc: ["le labo"] },
]);
