import { universe } from "../_build";

export const grandscouturiers = universe("mode", "Grands couturiers", [
  // --- Faciles (5) ---
  { id: "cout-f1", d: 1, t: "Quelle couturière a créé la petite robe noire et libéré la femme du corset ?", a: "Coco Chanel", x: ["Jeanne Lanvin", "Elsa Schiaparelli", "Madeleine Vionnet"] },
  { id: "cout-f2", d: 1, t: "Quel couturier a créé le « New Look » en 1947 ?", a: "Christian Dior", x: ["Yves Saint Laurent", "Hubert de Givenchy", "Pierre Balmain"] },
  { id: "cout-f3", d: 1, t: "Quel styliste allemand au catogan blanc a longtemps dirigé Chanel ?", a: "Karl Lagerfeld", x: ["Jean-Paul Gaultier", "Christian Lacroix", "Thierry Mugler"] },
  { id: "cout-f4", d: 1, t: "Quel couturier français, surnommé « l'enfant terrible de la mode », adore la marinière ?", a: "Jean-Paul Gaultier", x: ["Christian Lacroix", "Thierry Mugler", "Yves Saint Laurent"] },
  { id: "cout-f5", d: 1, t: "Quel couturier a imposé le smoking pour femme dans les années 60 ?", a: "Yves Saint Laurent", x: ["Christian Dior", "Karl Lagerfeld", "Pierre Cardin"] },
  // --- Moyennes (10) ---
  { id: "cout-m1", d: 2, t: "Quel styliste britannique provocateur, ancien de Givenchy, est mort en 2010 ?", a: "Alexander McQueen", x: ["John Galliano", "Vivienne Westwood", "Stella McCartney"] },
  { id: "cout-m2", d: 2, t: "Quelle créatrice britannique est surnommée la « reine du punk » ?", a: "Vivienne Westwood", x: ["Stella McCartney", "Mary Quant", "Phoebe Philo"] },
  { id: "cout-m3", d: 2, t: "À quelle créatrice attribue-t-on la popularisation de la minijupe dans les années 60 ?", a: "Mary Quant", x: ["Vivienne Westwood", "Coco Chanel", "Jean Shrimpton"] },
  { id: "cout-m4", d: 2, t: "Quel couturier a dirigé Dior avant d'être renvoyé après un scandale en 2011 ?", a: "John Galliano", x: ["Raf Simons", "Hedi Slimane", "Alexander McQueen"] },
  { id: "cout-m5", d: 2, t: "Quel créateur américain a relancé Gucci dans les années 1990 avant de fonder sa marque ?", a: "Tom Ford", x: ["Marc Jacobs", "Michael Kors", "Ralph Lauren"] },
  { id: "cout-m6", d: 2, t: "Quel couturier des années 80 est connu pour ses robes-sculptures et le parfum « Angel » ?", a: "Thierry Mugler", x: ["Claude Montana", "Christian Lacroix", "Azzedine Alaïa"] },
  { id: "cout-m7", d: 2, t: "Quel couturier tunisien moulait le corps de ses modèles dans les années 80-90 ?", a: "Azzedine Alaïa", x: ["Thierry Mugler", "Claude Montana", "Jean-Paul Gaultier"] },
  { id: "cout-m8", d: 2, t: "Quelle créatrice, fille d'un Beatle, refuse le cuir et la fourrure ?", a: "Stella McCartney", x: ["Phoebe Philo", "Clare Waight Keller", "Victoria Beckham"] },
  { id: "cout-m9", d: 2, t: "Quel styliste américain incarne le rêve américain avec son cavalier de polo ?", a: "Ralph Lauren", x: ["Tommy Hilfiger", "Calvin Klein", "Michael Kors"] },
  { id: "cout-m10", d: 2, t: "Quel couturier italien est associé à une nuance de rouge qui porte son nom ?", a: "Valentino", x: ["Giorgio Armani", "Gianni Versace", "Roberto Cavalli"] },
  // --- Dures (15) ---
  { id: "cout-d1", d: 3, t: "Quel directeur artistique a réinventé Gucci vers 2015 avec un style maximaliste ?", a: "Alessandro Michele", x: ["Tom Ford", "Frida Giannini", "Sabato De Sarno"] },
  { id: "cout-d2", d: 3, t: "Quel créateur a fait entrer Louis Vuitton dans le streetwear de luxe avant sa mort en 2021 ?", a: "Virgil Abloh", x: ["Kim Jones", "Marc Jacobs", "Nicolas Ghesquière"] },
  { id: "cout-d3", d: 3, t: "Quel créateur a poussé Balenciaga vers un style extrême dans les années 2020 ?", a: "Demna Gvasalia", x: ["Nicolas Ghesquière", "Alexander Wang", "Josephus Thimister"], acc: ["demna"] },
  { id: "cout-d4", d: 3, t: "Quelle maison japonaise d'avant-garde a été fondée par Rei Kawakubo ?", a: "Comme des Garçons", x: ["Issey Miyake", "Yohji Yamamoto", "Kenzo"] },
  { id: "cout-d5", d: 3, t: "Quel créateur japonais est connu pour ses plissés techniques et un parfum en flacon conique ?", a: "Issey Miyake", x: ["Yohji Yamamoto", "Rei Kawakubo", "Kenzo Takada"] },
  { id: "cout-d6", d: 3, t: "Quel couturier japonais aux drapés sombres a marqué la mode d'avant-garde parisienne ?", a: "Yohji Yamamoto", x: ["Issey Miyake", "Junya Watanabe", "Kenzo Takada"] },
  { id: "cout-d7", d: 3, t: "Quel couturier espagnol était surnommé « le maître » par ses pairs, dont Dior ?", a: "Cristóbal Balenciaga", x: ["Paco Rabanne", "Manuel Pertegaz", "Mariano Fortuny"] },
  { id: "cout-d8", d: 3, t: "Quel créateur espagnol des années 60 habillait ses modèles de métal et de plastique ?", a: "Paco Rabanne", x: ["André Courrèges", "Pierre Cardin", "Emanuel Ungaro"] },
  { id: "cout-d9", d: 3, t: "Quel couturier français, pionnier de la mode « espace » des années 60, a lancé la robe géométrique ?", a: "André Courrèges", x: ["Pierre Cardin", "Paco Rabanne", "Emanuel Ungaro"] },
  { id: "cout-d10", d: 3, t: "Quel couturier français a démocratisé le prêt-à-porter griffé via des licences mondiales ?", a: "Pierre Cardin", x: ["André Courrèges", "Ted Lapidus", "Guy Laroche"] },
  { id: "cout-d11", d: 3, t: "Quel homme d'affaires a cofondé la maison Yves Saint Laurent avec le couturier ?", a: "Pierre Bergé", x: ["François Pinault", "Bernard Arnault", "Marcel Boussac"] },
  { id: "cout-d12", d: 3, t: "Quel est le vrai prénom de Coco Chanel ?", a: "Gabrielle", x: ["Gaby", "Jeanne", "Colette"], acc: ["gabrielle"] },
  { id: "cout-d13", d: 3, t: "Quel créateur belge, membre des « Six d'Anvers », dirige une maison minimaliste à imprimés ?", a: "Dries Van Noten", x: ["Martin Margiela", "Raf Simons", "Ann Demeulemeester"] },
  { id: "cout-d14", d: 3, t: "Quel créateur belge énigmatique, jamais photographié, a fondé une maison à son nom ?", a: "Martin Margiela", x: ["Dries Van Noten", "Raf Simons", "Walter Van Beirendonck"] },
  { id: "cout-d15", d: 3, t: "Quel jeune créateur français du Sud a lancé sa maison éponyme minimaliste et ensoleillée ?", a: "Jacquemus", x: ["Marine Serre", "Coperni", "Ami"], acc: ["jacquemus", "simon porte jacquemus"] },
  // --- Pro (20) ---
  { id: "cout-p1", d: 4, t: "En quelle année Yves Saint Laurent présente-t-il son smoking pour femme ?", a: "1966", x: ["1947", "1954", "1983"] },
  { id: "cout-p2", d: 4, t: "Quelle maison Yves Saint Laurent dirigeait-il avant de fonder la sienne ?", a: "Dior", x: ["Chanel", "Givenchy", "Balenciaga"] },
  { id: "cout-p3", d: 4, t: "Quelle rédactrice en chef a longtemps régné sur le Vogue américain ?", a: "Anna Wintour", x: ["Carine Roitfeld", "Grace Coddington", "Diana Vreeland"] },
  { id: "cout-p4", d: 4, t: "Quelle créatrice de la maison McQueen a dessiné la robe de mariée de Kate Middleton ?", a: "Sarah Burton", x: ["Stella McCartney", "Vivienne Westwood", "Victoria Beckham"] },
  { id: "cout-p5", d: 4, t: "Quel couturier italien a fondé une maison célèbre pour ses imprimés colorés et la Dolce Vita ?", a: "Emilio Pucci", x: ["Roberto Cavalli", "Ottavio Missoni", "Gimmo Etro"] },
  { id: "cout-p6", d: 4, t: "Quel duo d'artistes-couturiers néerlandais est connu pour ses défilés-performances ?", a: "Viktor & Rolf", x: ["Proenza Schouler", "Rodarte", "Ackermann et Simons"], acc: ["viktor & rolf", "viktor and rolf"] },
  { id: "cout-p7", d: 4, t: "Quel jeune créateur a relancé Balmain dans les années 2010 avec un style rock et glamour ?", a: "Olivier Rousteing", x: ["Christophe Decarnin", "Pierpaolo Piccioli", "Riccardo Tisci"] },
  { id: "cout-p8", d: 4, t: "Quel créateur italien a dirigé Givenchy puis Burberry, connu pour son style gothique ?", a: "Riccardo Tisci", x: ["Matthew Williams", "Clare Waight Keller", "Christopher Bailey"] },
  { id: "cout-p9", d: 4, t: "Quel couturier libanais est une star des tapis rouges avec ses robes de gala ?", a: "Elie Saab", x: ["Zuhair Murad", "Georges Hobeika", "Reem Acra"] },
  { id: "cout-p10", d: 4, t: "Quel couturier français a créé la maison Givenchy et habillé Audrey Hepburn ?", a: "Hubert de Givenchy", x: ["Cristóbal Balenciaga", "Pierre Balmain", "Jacques Fath"] },
  { id: "cout-p11", d: 4, t: "Quel couturier italien, mort en 1997, a fondé une maison au logo de Méduse ?", a: "Gianni Versace", x: ["Valentino Garavani", "Giorgio Armani", "Ottavio Missoni"] },
  { id: "cout-p12", d: 4, t: "Quel styliste italien est le maître du costume masculin épuré et du tailleur souple ?", a: "Giorgio Armani", x: ["Gianni Versace", "Valentino Garavani", "Domenico Dolce"] },
  { id: "cout-p13", d: 4, t: "Quel créateur a redéfini Louis Vuitton femme depuis 2013, venu de Balenciaga ?", a: "Nicolas Ghesquière", x: ["Marc Jacobs", "Virgil Abloh", "Kim Jones"] },
  { id: "cout-p14", d: 4, t: "Quel créateur américain a habillé Louis Vuitton pendant seize ans avant Ghesquière ?", a: "Marc Jacobs", x: ["Tom Ford", "Michael Kors", "Alexander Wang"] },
  { id: "cout-p15", d: 4, t: "Quel styliste britannique a dirigé Chloé puis Céline, prônant un minimalisme culte ?", a: "Phoebe Philo", x: ["Stella McCartney", "Clare Waight Keller", "Hannah MacGibbon"] },
  { id: "cout-p16", d: 4, t: "Quelle créatrice a pris la tête de Chanel après la mort de Karl Lagerfeld en 2019 ?", a: "Virginie Viard", x: ["Bruno Pavlovsky", "Hedi Slimane", "Sarah Burton"] },
  { id: "cout-p17", d: 4, t: "Quel créateur belge a sublimé Bottega Veneta avant de rejoindre Chanel ?", a: "Matthieu Blazy", x: ["Daniel Lee", "Tomas Maier", "Raf Simons"] },
  { id: "cout-p18", d: 4, t: "Quel couturier français, dit « le magnifique », a signé de somptueuses robes à froufrous dans les années 80 ?", a: "Christian Lacroix", x: ["Thierry Mugler", "Jean-Paul Gaultier", "Emanuel Ungaro"] },
  { id: "cout-p19", d: 4, t: "Quel créateur belge minimaliste a dirigé Jil Sander, Dior puis Prada et Calvin Klein ?", a: "Raf Simons", x: ["Martin Margiela", "Dries Van Noten", "Kris Van Assche"] },
  { id: "cout-p20", d: 4, t: "Quel couturier français a fondé la première maison de haute couture parisienne au XIXe siècle ?", a: "Charles Frederick Worth", x: ["Paul Poiret", "Jacques Doucet", "Jeanne Paquin"] },
]);
