import { universe } from "../_build";

export const histoireDeLaMode = universe("mode", "Histoire de la mode", [
  // --- Faciles (5) ---
  { id: "histmode-f1", d: 1, t: "Quel sous-vêtement rigide comprimait la taille des femmes autrefois ?", a: "Le corset", x: ["Le jupon", "La crinoline", "Le bustier"], acc: ["corset"] },
  { id: "histmode-f2", d: 1, t: "Quelle couturière a libéré la femme du corset au début du XXe siècle ?", a: "Coco Chanel", x: ["Jeanne Lanvin", "Madeleine Vionnet", "Elsa Schiaparelli"] },
  { id: "histmode-f3", d: 1, t: "Quel vêtement court et scandaleux a symbolisé la libération des années 60 ?", a: "La minijupe", x: ["Le pantalon", "Le bikini", "La robe fourreau"], acc: ["minijupe"] },
  { id: "histmode-f4", d: 1, t: "Quelle toile de coton robuste, teinte en bleu, sert à faire les jeans ?", a: "Le denim", x: ["Le velours", "Le tweed", "La toile de lin"], acc: ["denim"] },
  { id: "histmode-f5", d: 1, t: "Quel style vestimentaire des années 70 se reconnaît aux pantalons à pattes d'éléphant et aux fleurs ?", a: "Le style hippie", x: ["Le style punk", "Le style disco", "Le style grunge"], acc: ["hippie"] },
  // --- Moyennes (10) ---
  { id: "histmode-m1", d: 2, t: "Quel couturier a inventé la haute couture parisienne au XIXe siècle ?", a: "Charles Frederick Worth", x: ["Paul Poiret", "Jacques Doucet", "Jean Patou"] },
  { id: "histmode-m2", d: 2, t: "Quel couturier a libéré la silhouette et supprimé le corset dans les années 1900-1910 ?", a: "Paul Poiret", x: ["Charles Frederick Worth", "Christian Dior", "Cristóbal Balenciaga"] },
  { id: "histmode-m3", d: 2, t: "Quelle décennie voit les femmes « garçonnes » aux cheveux courts et robes droites ?", a: "Les années 1920", x: ["Les années 1900", "Les années 1950", "Les années 1970"], acc: ["années 20", "1920"] },
  { id: "histmode-m4", d: 2, t: "Quel couturier a lancé le « New Look » en 1947, aux tailles fines et jupes amples ?", a: "Christian Dior", x: ["Coco Chanel", "Cristóbal Balenciaga", "Pierre Balmain"] },
  { id: "histmode-m5", d: 2, t: "Quel mouvement de jeunesse britannique des années 70 a inspiré une mode déchirée et à épingles ?", a: "Le punk", x: ["Le mod", "Le rocker", "Le hippie"], acc: ["punk"] },
  { id: "histmode-m6", d: 2, t: "Quel style des années 90, venu de Seattle, prône chemises à carreaux et allure négligée ?", a: "Le grunge", x: ["Le punk", "Le disco", "Le preppy"], acc: ["grunge"] },
  { id: "histmode-m7", d: 2, t: "Quel vêtement masculin est devenu un symbole de rébellion grâce à James Dean et Marlon Brando ?", a: "Le blouson en cuir", x: ["Le costume trois-pièces", "Le trench-coat", "Le smoking"], acc: ["blouson en cuir", "perfecto"] },
  { id: "histmode-m8", d: 2, t: "Quelle marque a inventé le jean rivé en 1873, aux États-Unis ?", a: "Levi Strauss", x: ["Lee", "Wrangler", "Diesel"], acc: ["levi strauss", "levi's"] },
  { id: "histmode-m9", d: 2, t: "Quel maillot de bain deux-pièces a fait scandale à sa sortie en 1946 ?", a: "Le bikini", x: ["Le monokini", "Le tankini", "Le trikini"], acc: ["bikini"] },
  { id: "histmode-m10", d: 2, t: "Quelle matière synthétique, apparue vers les années 1940, a révolutionné les bas pour femmes ?", a: "Le nylon", x: ["Le polyester", "L'élasthanne", "La viscose"], acc: ["nylon"] },
  // --- Dures (15) ---
  { id: "histmode-d1", d: 3, t: "Quelle couturière rivale de Chanel a collaboré avec les surréalistes, dont Dalí ?", a: "Elsa Schiaparelli", x: ["Madeleine Vionnet", "Jeanne Lanvin", "Madame Grès"] },
  { id: "histmode-d2", d: 3, t: "Quelle couturière a inventé la coupe en biais, rendant les robes plus fluides ?", a: "Madeleine Vionnet", x: ["Elsa Schiaparelli", "Coco Chanel", "Jeanne Paquin"] },
  { id: "histmode-d3", d: 3, t: "Quel couturier espagnol, « le maître », a sculpté des volumes architecturaux dans les années 50 ?", a: "Cristóbal Balenciaga", x: ["Christian Dior", "Hubert de Givenchy", "Pierre Balmain"] },
  { id: "histmode-d4", d: 3, t: "Quelle couleur, rare et coûteuse, était réservée aux empereurs romains ?", a: "Le pourpre", x: ["L'or", "Le bleu roi", "L'écarlate"], acc: ["pourpre"] },
  { id: "histmode-d5", d: 3, t: "Quelle armature légère gonflait les jupes au milieu du XIXe siècle ?", a: "La crinoline", x: ["Le corset", "La tournure", "Le jupon"], acc: ["crinoline"] },
  { id: "histmode-d6", d: 3, t: "Quel rembourrage placé à l'arrière des robes a suivi la crinoline vers 1870 ?", a: "La tournure", x: ["La crinoline", "Le panier", "Le vertugadin"], acc: ["tournure", "faux-cul"] },
  { id: "histmode-d7", d: 3, t: "Quel couturier a créé le « smoking » pour femme en 1966 ?", a: "Yves Saint Laurent", x: ["Christian Dior", "Pierre Cardin", "André Courrèges"] },
  { id: "histmode-d8", d: 3, t: "Quels couturiers des années 60 ont imaginé une mode « futuriste » aux formes géométriques ?", a: "Courrèges et Cardin", x: ["Dior et Balmain", "Chanel et Lanvin", "Worth et Poiret"], acc: ["courrèges et cardin"] },
  { id: "histmode-d9", d: 3, t: "Quelle sous-culture britannique des années 60, élégante et à scooter, a marqué la mode ?", a: "Les mods", x: ["Les teddy boys", "Les rockers", "Les skinheads"], acc: ["mods"] },
  { id: "histmode-d10", d: 3, t: "Quel procédé de teinture donne des motifs colorés en nouant le tissu ?", a: "Le tie and dye", x: ["Le pied-de-poule", "Le tartan", "Le vichy"], acc: ["tie and dye", "tie-dye"] },
  { id: "histmode-d11", d: 3, t: "Quelle créatrice britannique, « reine du punk », a habillé les Sex Pistols ?", a: "Vivienne Westwood", x: ["Mary Quant", "Zandra Rhodes", "Barbara Hulanicki"] },
  { id: "histmode-d12", d: 3, t: "Quelle décennie est marquée par les épaulettes, le clinquant et le « power dressing » ?", a: "Les années 1980", x: ["Les années 1960", "Les années 1990", "Les années 2000"], acc: ["années 80", "1980"] },
  { id: "histmode-d13", d: 3, t: "Quel style des années 90, minimaliste et sombre, est associé à Kate Moss et Calvin Klein ?", a: "Le heroin chic", x: ["Le grunge", "Le preppy", "Le gothique"], acc: ["heroin chic"] },
  { id: "histmode-d14", d: 3, t: "Quel vêtement, autrefois sous-vêtement, est devenu un basique grâce à Marlon Brando ?", a: "Le tee-shirt", x: ["Le pull", "La chemise", "Le débardeur"], acc: ["tee-shirt", "t-shirt"] },
  { id: "histmode-d15", d: 3, t: "Quelle chaussure à semelle épaisse et haute a marqué les années 70 puis 90 ?", a: "La plateforme", x: ["Le stiletto", "La ballerine", "La mule"], acc: ["plateforme", "semelle compensée"] },
  // --- Pro (20) ---
  { id: "histmode-p1", d: 4, t: "Quel roi français, amateur de talons rouges et de perruques, a imposé la mode à sa cour ?", a: "Louis XIV", x: ["François Ier", "Louis XV", "Henri IV"], acc: ["louis xiv"] },
  { id: "histmode-p2", d: 4, t: "Quelle reine de France, icône de mode, portait des coiffures extravagantes avant la Révolution ?", a: "Marie-Antoinette", x: ["Catherine de Médicis", "Joséphine de Beauharnais", "Madame de Pompadour"] },
  { id: "histmode-p3", d: 4, t: "Quelle marchande de modes habillait Marie-Antoinette, surnommée « ministre des Modes » ?", a: "Rose Bertin", x: ["Madame Grès", "Jeanne Lanvin", "Madeleine Vionnet"], acc: ["rose bertin"] },
  { id: "histmode-p4", d: 4, t: "Quel style vestimentaire, sous Napoléon, prône des robes fluides à taille haute ?", a: "Le style Empire", x: ["Le style Régence", "Le style Rococo", "Le style Directoire"], acc: ["empire", "style empire"] },
  { id: "histmode-p5", d: 4, t: "Quelle maison a imposé la « petite robe noire » comme uniforme chic dans les années 20 ?", a: "Chanel", x: ["Dior", "Lanvin", "Patou"] },
  { id: "histmode-p6", d: 4, t: "Quel couturier des années 20 a lancé la mode sportive et le bronzage chic ?", a: "Jean Patou", x: ["Paul Poiret", "Charles Frederick Worth", "Jacques Doucet"] },
  { id: "histmode-p7", d: 4, t: "Quel tissu écossais à carreaux tire son nom des clans ?", a: "Le tartan", x: ["Le tweed", "Le vichy", "Le pied-de-poule"], acc: ["tartan"] },
  { id: "histmode-p8", d: 4, t: "Quel motif à petits carreaux bicolores tient son nom d'une ville française ?", a: "Le vichy", x: ["Le tartan", "Le madras", "Le pied-de-poule"], acc: ["vichy"] },
  { id: "histmode-p9", d: 4, t: "Quel motif géométrique noir et blanc, cher à Dior, ressemble à des dents ?", a: "Le pied-de-poule", x: ["Le chevron", "Le tartan", "Le vichy"], acc: ["pied-de-poule"] },
  { id: "histmode-p10", d: 4, t: "Quelle chaussure à talon fin tire son nom d'un poignard italien ?", a: "Le stiletto", x: ["La mule", "L'escarpin", "La spartiate"], acc: ["stiletto"] },
  { id: "histmode-p11", d: 4, t: "Quel créateur a lancé la « robe bandage » moulante dans les années 80-90 ?", a: "Hervé Léger", x: ["Azzedine Alaïa", "Thierry Mugler", "Claude Montana"] },
  { id: "histmode-p12", d: 4, t: "Quel accessoire de tête, longtemps obligatoire pour les élégantes, a peu à peu disparu après les années 60 ?", a: "Le chapeau", x: ["Les gants", "L'ombrelle", "L'éventail"], acc: ["chapeau"] },
  { id: "histmode-p13", d: 4, t: "Quelle couturière, une des premières femmes à diriger une grande maison, a habillé la Belle Époque ?", a: "Jeanne Paquin", x: ["Jeanne Lanvin", "Madeleine Vionnet", "Madame Grès"] },
  { id: "histmode-p14", d: 4, t: "Quelle maison de couture française, encore active, a été fondée en 1889 par Jeanne Lanvin ?", a: "Lanvin", x: ["Chanel", "Hermès", "Dior"] },
  { id: "histmode-p15", d: 4, t: "Quelle maison française, d'abord sellier, s'est tournée vers la maroquinerie de luxe au XIXe siècle ?", a: "Hermès", x: ["Louis Vuitton", "Goyard", "Longchamp"] },
  { id: "histmode-p16", d: 4, t: "Quel défilé de 1973 a opposé cinq créateurs français à cinq américains au château de Versailles ?", a: "La Bataille de Versailles", x: ["Le Festival de la mode", "Le Gala des créateurs", "La Nuit de la mode"], acc: ["bataille de versailles"] },
  { id: "histmode-p17", d: 4, t: "Quel plastique ancien, imitant l'ivoire et la corne, a servi à faire bijoux et boutons au début du XXe siècle ?", a: "La Bakélite", x: ["Le celluloïd", "Le PVC", "Le Plexiglas"], acc: ["bakélite"] },
  { id: "histmode-p18", d: 4, t: "Quelle mode japonaise des années 2000, née à Harajuku, mêle robes à volants et esthétique de poupée ?", a: "Le style Lolita", x: ["Le style mod", "Le style preppy", "Le style boho"], acc: ["lolita", "kawaii"] },
  { id: "histmode-p19", d: 4, t: "Quel couturier a présenté ses modèles sur des femmes en mouvement, inventant le défilé moderne ?", a: "Charles Frederick Worth", x: ["Paul Poiret", "Jean Patou", "Lucien Lelong"] },
  { id: "histmode-p20", d: 4, t: "Quelle décennie a vu s'imposer le prêt-à-porter de créateur et la démocratisation de la mode ?", a: "Les années 1960", x: ["Les années 1920", "Les années 1980", "Les années 2000"], acc: ["années 60", "1960"] },
]);
