import { universe } from "../_build";

export const maisonsdeluxe = universe("mode", "Maisons de luxe", [
  // --- Faciles (5) ---
  { id: "luxe-f1", d: 1, t: "Quelle maison française a pour logo deux « C » entrelacés ?", a: "Chanel", x: ["Dior", "Gucci", "Prada"] },
  { id: "luxe-f2", d: 1, t: "Quelle maison française est célèbre pour son monogramme « LV » ?", a: "Louis Vuitton", x: ["Hermès", "Chanel", "Dior"] },
  { id: "luxe-f3", d: 1, t: "Quelle maison italienne a pour emblème une tête de Méduse ?", a: "Versace", x: ["Gucci", "Prada", "Armani"] },
  { id: "luxe-f4", d: 1, t: "Quelle maison française au logo de calèche est connue pour ses foulards et son sac Birkin ?", a: "Hermès", x: ["Louis Vuitton", "Chanel", "Céline"] },
  { id: "luxe-f5", d: 1, t: "Quelle ville est le berceau historique de la haute couture et du luxe ?", a: "Paris", x: ["Milan", "New York", "Londres"] },
  // --- Moyennes (10) ---
  { id: "luxe-m1", d: 2, t: "Quel groupe français, dirigé par Bernard Arnault, possède Louis Vuitton et Dior ?", a: "LVMH", x: ["Kering", "Richemont", "Chanel"], acc: ["lvmh"] },
  { id: "luxe-m2", d: 2, t: "Quel groupe de luxe, rival de LVMH, possède Gucci et Saint Laurent ?", a: "Kering", x: ["LVMH", "Richemont", "Prada"] },
  { id: "luxe-m3", d: 2, t: "Quelle maison italienne au logo de deux « F » est connue pour la fourrure ?", a: "Fendi", x: ["Ferragamo", "Fila", "Furla"] },
  { id: "luxe-m4", d: 2, t: "Quelle maison italienne au triangle inversé a révolutionné le luxe minimaliste ?", a: "Prada", x: ["Gucci", "Miu Miu", "Bottega Veneta"] },
  { id: "luxe-m5", d: 2, t: "Quelle maison italienne est célèbre pour son mors de cheval et ses rayures vertes et rouges ?", a: "Gucci", x: ["Versace", "Fendi", "Bulgari"] },
  { id: "luxe-m6", d: 2, t: "Quel sac matelassé de Chanel porte le numéro de sa date de création, février 1955 ?", a: "Le 2.55", x: ["Le Boy", "Le Classic Flap", "Le Timeless"], acc: ["2.55"] },
  { id: "luxe-m7", d: 2, t: "Quelle actrice a donné son nom au sac « Kelly » d'Hermès ?", a: "Grace Kelly", x: ["Audrey Hepburn", "Jane Birkin", "Brigitte Bardot"] },
  { id: "luxe-m8", d: 2, t: "Quelle chanteuse et actrice a inspiré le sac le plus convoité d'Hermès ?", a: "Jane Birkin", x: ["Grace Kelly", "Françoise Hardy", "Marianne Faithfull"] },
  { id: "luxe-m9", d: 2, t: "Quelle maison de joaillerie française à l'écrin rouge est place Vendôme ?", a: "Cartier", x: ["Van Cleef & Arpels", "Boucheron", "Chaumet"] },
  { id: "luxe-m10", d: 2, t: "Quelle maison de joaillerie américaine à l'écrin bleu est célébrée dans « Diamants sur canapé » ?", a: "Tiffany & Co.", x: ["Cartier", "Bulgari", "Harry Winston"], acc: ["tiffany"] },
  // --- Dures (15) ---
  { id: "luxe-d1", d: 3, t: "Quel homme dirige LVMH et a longtemps été l'homme le plus riche du monde ?", a: "Bernard Arnault", x: ["François-Henri Pinault", "Johann Rupert", "Patrizio Bertelli"] },
  { id: "luxe-d2", d: 3, t: "Quel groupe suisse possède Cartier, Van Cleef & Arpels et Montblanc ?", a: "Richemont", x: ["LVMH", "Kering", "Swatch Group"] },
  { id: "luxe-d3", d: 3, t: "Quelle maison a inventé la malle plate empilable au XIXe siècle ?", a: "Louis Vuitton", x: ["Goyard", "Moynat", "Hermès"] },
  { id: "luxe-d4", d: 3, t: "Comment appelle-t-on le motif emblématique de Louis Vuitton, à initiales et fleurs ?", a: "Le monogramme", x: ["Le Damier", "L'Épi", "Le Taïga"], acc: ["monogramme"] },
  { id: "luxe-d5", d: 3, t: "Quelle maison italienne est connue pour son cuir tressé « intrecciato » ?", a: "Bottega Veneta", x: ["Prada", "Gucci", "Loro Piana"] },
  { id: "luxe-d6", d: 3, t: "Quelle maison florentine est célèbre pour ses chaussures et ses sacs en cuir ?", a: "Salvatore Ferragamo", x: ["Gucci", "Tod's", "Sergio Rossi"] },
  { id: "luxe-d7", d: 3, t: "Quelle maison britannique est connue pour son tartan beige et ses trench-coats ?", a: "Burberry", x: ["Barbour", "Aquascutum", "Mackintosh"] },
  { id: "luxe-d8", d: 3, t: "Quelle maison française de maroquinerie, discrète, tisse ses toiles au chevron en « Y » ?", a: "Goyard", x: ["Moynat", "Delvaux", "Longchamp"] },
  { id: "luxe-d9", d: 3, t: "Quelle semelle rouge signe les escarpins de luxe d'un créateur français ?", a: "Christian Louboutin", x: ["Manolo Blahnik", "Jimmy Choo", "Roger Vivier"] },
  { id: "luxe-d10", d: 3, t: "Quel créateur de chaussures est vénéré par Carrie dans « Sex and the City » ?", a: "Manolo Blahnik", x: ["Christian Louboutin", "Jimmy Choo", "Salvatore Ferragamo"] },
  { id: "luxe-d11", d: 3, t: "Quelle maison italienne d'imprimés cachemire colorés est fondée à Milan ?", a: "Etro", x: ["Missoni", "Pucci", "Ferragamo"] },
  { id: "luxe-d12", d: 3, t: "Quelle maison de champagne, fleuron du luxe, appartient à LVMH ?", a: "Moët & Chandon", x: ["Louis Roederer", "Bollinger", "Taittinger"], acc: ["moët", "moet"] },
  { id: "luxe-d13", d: 3, t: "Quelle maison de joaillerie romaine est connue pour ses bijoux serpents « Serpenti » ?", a: "Bulgari", x: ["Cartier", "Tiffany & Co.", "Pomellato"], acc: ["bvlgari", "bulgari"] },
  { id: "luxe-d14", d: 3, t: "Quelle maison française vend le carré de soie imprimé le plus célèbre du monde ?", a: "Hermès", x: ["Louis Vuitton", "Chanel", "Dior"] },
  { id: "luxe-d15", d: 3, t: "Quelle maison a lancé le parfum le plus vendu au monde, « N°5 », en 1921 ?", a: "Chanel", x: ["Dior", "Guerlain", "Lanvin"] },
  // --- Pro (20) ---
  { id: "luxe-p1", d: 4, t: "Quel parfumeur a composé le Chanel N°5 pour Coco Chanel ?", a: "Ernest Beaux", x: ["Jacques Guerlain", "François Coty", "Edmond Roudnitska"] },
  { id: "luxe-p2", d: 4, t: "Quelle maison française de parfums a créé « Shalimar » ?", a: "Guerlain", x: ["Chanel", "Dior", "Lanvin"] },
  { id: "luxe-p3", d: 4, t: "En quelle année Bernard Arnault a-t-il pris le contrôle de LVMH ?", a: "1989", x: ["1979", "1999", "2005"] },
  { id: "luxe-p4", d: 4, t: "Quelle ligne du groupe Prada est la marque plus jeune de Miuccia Prada ?", a: "Miu Miu", x: ["Marni", "Max Mara", "Moschino"] },
  { id: "luxe-p5", d: 4, t: "Quel créateur excentrique a fondé Moschino, connu pour ses parodies de logos ?", a: "Franco Moschino", x: ["Elio Fiorucci", "Gianni Versace", "Roberto Cavalli"] },
  { id: "luxe-p6", d: 4, t: "Quelle maison espagnole du groupe LVMH est connue pour son cuir et son logo à quatre « L » ?", a: "Loewe", x: ["Balenciaga", "Delvaux", "Loro Piana"] },
  { id: "luxe-p7", d: 4, t: "Quel styliste britannique a hissé Loewe au sommet dans les années 2010 ?", a: "Jonathan Anderson", x: ["Daniel Lee", "Jonathan Saunders", "Christopher Kane"], acc: ["jonathan anderson", "jw anderson"] },
  { id: "luxe-p8", d: 4, t: "Quelle maison italienne de cachemire ultra-luxe, rachetée par LVMH, vient du Piémont ?", a: "Loro Piana", x: ["Brunello Cucinelli", "Ermenegildo Zegna", "Malo"] },
  { id: "luxe-p9", d: 4, t: "Quel joaillier américain, roi du diamant, a prêté des pierres aux stars d'Hollywood ?", a: "Harry Winston", x: ["Tiffany & Co.", "Cartier", "Graff"] },
  { id: "luxe-p10", d: 4, t: "Quelle manufacture horlogère suisse est un sommet de la haute horlogerie ?", a: "Patek Philippe", x: ["Rolex", "Omega", "TAG Heuer"] },
  { id: "luxe-p11", d: 4, t: "Quelle montre de luxe à la couronne est un symbole mondial de réussite ?", a: "Rolex", x: ["Omega", "Cartier", "Breitling"] },
  { id: "luxe-p12", d: 4, t: "Quel tissu, cher à Chanel, est fabriqué en Écosse et symbolise ses tailleurs ?", a: "Le tweed", x: ["Le cachemire", "La soie", "Le velours"] },
  { id: "luxe-p13", d: 4, t: "Quelle maison a lancé le sac « Lady Dior », rendu célèbre par Lady Diana ?", a: "Dior", x: ["Chanel", "Louis Vuitton", "Givenchy"] },
  { id: "luxe-p14", d: 4, t: "Quel sac « it-bag » de Fendi, tout en longueur, a explosé dans « Sex and the City » ?", a: "Le Baguette", x: ["Le Peekaboo", "Le Spy", "Le Kan I"], acc: ["baguette"] },
  { id: "luxe-p15", d: 4, t: "Quelle maison florentine est la locomotive du groupe Kering ?", a: "Gucci", x: ["Bottega Veneta", "Balenciaga", "Saint Laurent"] },
  { id: "luxe-p16", d: 4, t: "Quelle famille contrôle le groupe Kering ?", a: "La famille Pinault", x: ["La famille Arnault", "La famille Agnelli", "La famille Wertheimer"] },
  { id: "luxe-p17", d: 4, t: "Quelle famille, propriétaire discrète, contrôle la maison Chanel ?", a: "La famille Wertheimer", x: ["La famille Pinault", "La famille Arnault", "La famille Bettencourt"] },
  { id: "luxe-p18", d: 4, t: "Quel malletier, plus ancien que Vuitton, a habillé les voyages de l'impératrice Eugénie ?", a: "Moynat", x: ["Goyard", "Delvaux", "Hermès"] },
  { id: "luxe-p19", d: 4, t: "Quel créateur de souliers signe les célèbres nœuds « Vivier » et a chaussé des reines ?", a: "Roger Vivier", x: ["Christian Louboutin", "Manolo Blahnik", "Salvatore Ferragamo"] },
  { id: "luxe-p20", d: 4, t: "Quelle maison italienne est connue pour ses tricots en zigzag multicolores ?", a: "Missoni", x: ["Fendi", "Etro", "Marni"] },
]);
