import { universe } from "../_build";

export const mannequinsFashionWeek = universe("mode", "Mannequins et Fashion Week", [
  // --- Faciles (5) ---
  { id: "manneq-f1", d: 1, t: "Comment appelle-t-on une personne qui défile pour présenter des vêtements ?", a: "Un mannequin", x: ["Un styliste", "Un couturier", "Un modéliste"] },
  { id: "manneq-f2", d: 1, t: "Comment appelle-t-on le podium sur lequel défilent les mannequins ?", a: "Le podium", x: ["La scène", "Le tapis rouge", "L'estrade"], acc: ["podium", "catwalk"] },
  { id: "manneq-f3", d: 1, t: "Dans quelle ville française se tient l'une des quatre grandes Fashion Weeks ?", a: "Paris", x: ["Lyon", "Cannes", "Nice"] },
  { id: "manneq-f4", d: 1, t: "Quel magazine de mode est surnommé « la bible de la mode » ?", a: "Vogue", x: ["Elle", "Marie Claire", "Grazia"] },
  { id: "manneq-f5", d: 1, t: "Comment appelle-t-on un mannequin très célèbre et très demandé ?", a: "Un top model", x: ["Un figurant", "Un influenceur", "Un mécène"], acc: ["top model", "supermodel"] },
  // --- Moyennes (10) ---
  { id: "manneq-m1", d: 2, t: "Quelles quatre villes accueillent les grandes Fashion Weeks internationales ?", a: "New York, Londres, Milan, Paris", x: ["Paris, Tokyo, Los Angeles, Berlin", "Londres, Madrid, Rome, Paris", "New York, Miami, Milan, Nice"], acc: ["new york londres milan paris"] },
  { id: "manneq-m2", d: 2, t: "Quelle rédactrice en chef règne sur le Vogue américain depuis 1988 ?", a: "Anna Wintour", x: ["Carine Roitfeld", "Grace Coddington", "Emmanuelle Alt"] },
  { id: "manneq-m3", d: 2, t: "Quelle mannequin britannique menue a incarné le « heroin chic » des années 90 ?", a: "Kate Moss", x: ["Naomi Campbell", "Linda Evangelista", "Claudia Schiffer"] },
  { id: "manneq-m4", d: 2, t: "Quelle mannequin britannique noire, au fort caractère, est l'une des tops les plus célèbres ?", a: "Naomi Campbell", x: ["Kate Moss", "Iman", "Tyra Banks"] },
  { id: "manneq-m5", d: 2, t: "Quelle mannequin allemande blonde a été une égérie de Chanel et Guess dans les années 90 ?", a: "Claudia Schiffer", x: ["Cindy Crawford", "Linda Evangelista", "Eva Herzigová"] },
  { id: "manneq-m6", d: 2, t: "Quelle mannequin américaine au grain de beauté, égérie de Pepsi, a marqué les années 90 ?", a: "Cindy Crawford", x: ["Claudia Schiffer", "Kate Moss", "Christy Turlington"] },
  { id: "manneq-m7", d: 2, t: "Comment appelle-t-on collectivement les tops vedettes des années 90 comme Naomi, Cindy et Linda ?", a: "Les supermodels", x: ["Les égéries", "Les it-girls", "Les cover-girls"], acc: ["supermodels", "top models"] },
  { id: "manneq-m8", d: 2, t: "Quelle marque de lingerie américaine organisait un défilé télévisé avec ses « Anges » ?", a: "Victoria's Secret", x: ["Chantelle", "Aubade", "Etam"], acc: ["victoria's secret"] },
  { id: "manneq-m9", d: 2, t: "Comment surnomme-t-on les mannequins vedettes de Victoria's Secret, aux ailes de plumes ?", a: "Les Anges", x: ["Les Muses", "Les Fées", "Les Sirènes"], acc: ["anges", "angels"] },
  { id: "manneq-m10", d: 2, t: "Quelle animatrice et ex-mannequin a créé l'émission « America's Next Top Model » ?", a: "Tyra Banks", x: ["Heidi Klum", "Naomi Campbell", "Gisele Bündchen"] },
  // --- Dures (15) ---
  { id: "manneq-d1", d: 3, t: "Quelle mannequin brésilienne a longtemps été la mieux payée du monde ?", a: "Gisele Bündchen", x: ["Adriana Lima", "Alessandra Ambrosio", "Kate Moss"] },
  { id: "manneq-d2", d: 3, t: "Quelle mannequin canadienne a lancé « je ne me lève pas pour moins de 10 000 dollars » ?", a: "Linda Evangelista", x: ["Christy Turlington", "Cindy Crawford", "Naomi Campbell"] },
  { id: "manneq-d3", d: 3, t: "Quelle mannequin américaine, égérie de Calvin Klein, est devenue professeure de yoga ?", a: "Christy Turlington", x: ["Cindy Crawford", "Linda Evangelista", "Helena Christensen"] },
  { id: "manneq-d4", d: 3, t: "Quelle top model somalienne, épouse de David Bowie, a lancé une marque de cosmétiques ?", a: "Iman", x: ["Alek Wek", "Naomi Campbell", "Liya Kebede"] },
  { id: "manneq-d5", d: 3, t: "Quelle top model néerlandaise a été l'une des plus demandées des années 2000-2010 ?", a: "Doutzen Kroes", x: ["Lara Stone", "Karlie Kloss", "Cara Delevingne"] },
  { id: "manneq-d6", d: 3, t: "Quelle top model britannique aux sourcils marqués, aussi actrice, a été égérie de Burberry ?", a: "Cara Delevingne", x: ["Rosie Huntington-Whiteley", "Jourdan Dunn", "Suki Waterhouse"] },
  { id: "manneq-d7", d: 3, t: "Quelle famille de télé-réalité a propulsé la mannequin Kendall Jenner ?", a: "Les Kardashian", x: ["Les Hadid", "Les Hilton", "Les Delevingne"], acc: ["kardashian", "jenner"] },
  { id: "manneq-d8", d: 3, t: "Quelles deux sœurs mannequins, filles d'un promoteur immobilier, dominent les podiums des années 2010 ?", a: "Gigi et Bella Hadid", x: ["Kendall et Kylie Jenner", "Georgia et Coco May", "Amber et Alana Le Bon"], acc: ["hadid"] },
  { id: "manneq-d9", d: 3, t: "Quelle agence de mannequins new-yorkaise, prestigieuse, gère de nombreuses tops ?", a: "IMG Models", x: ["Elite", "Ford", "Next"], acc: ["img", "img models"] },
  { id: "manneq-d10", d: 3, t: "Quelle agence de mannequins parisienne, prestigieuse, a lancé de nombreuses tops ?", a: "Elite", x: ["IMG Models", "Ford", "Marilyn"], acc: ["elite"] },
  { id: "manneq-d11", d: 3, t: "Quelle mannequin transgenre brésilienne a défilé pour Victoria's Secret et fait la couverture de Vogue ?", a: "Valentina Sampaio", x: ["Leyna Bloom", "Teddy Quinlivan", "Hunter Schafer"] },
  { id: "manneq-d12", d: 3, t: "Quelle top model australienne, ex-Victoria's Secret, est l'égérie de nombreuses marques ?", a: "Miranda Kerr", x: ["Elle Macpherson", "Gemma Ward", "Shanina Shaik"] },
  { id: "manneq-d13", d: 3, t: "Quelle mannequin australienne surnommée « The Body » a marqué les années 80-90 ?", a: "Elle Macpherson", x: ["Miranda Kerr", "Rachel Hunter", "Rebecca Romijn"] },
  { id: "manneq-d14", d: 3, t: "Quelle top model danoise, muse des années 90, apparaît dans le clip « Wicked Game » ?", a: "Helena Christensen", x: ["Claudia Schiffer", "Eva Herzigová", "Karen Mulder"] },
  { id: "manneq-d15", d: 3, t: "Quelle mannequin tchèque a fait sensation avec le Wonderbra dans les années 90 ?", a: "Eva Herzigová", x: ["Claudia Schiffer", "Helena Christensen", "Karen Mulder"] },
  // --- Pro (20) ---
  { id: "manneq-p1", d: 4, t: "Quel organisme parisien fixe le calendrier officiel des défilés et de la haute couture ?", a: "La Fédération de la haute couture et de la mode", x: ["Le CFDA", "Le British Fashion Council", "La Camera della Moda"], acc: ["fédération de la haute couture"] },
  { id: "manneq-p2", d: 4, t: "Quel organisme organise la Fashion Week de New York et remet des prix aux créateurs ?", a: "Le CFDA", x: ["La Fédération de la haute couture", "Le British Fashion Council", "La Camera della Moda"], acc: ["cfda"] },
  { id: "manneq-p3", d: 4, t: "Quel gala new-yorkais, présidé par Anna Wintour, est la grande soirée mode de l'année ?", a: "Le Met Gala", x: ["Les CFDA Awards", "Les British Fashion Awards", "Le bal de la Rose"], acc: ["met gala", "met ball"] },
  { id: "manneq-p4", d: 4, t: "À quel musée le Met Gala est-il rattaché, finançant son département mode ?", a: "Le Metropolitan Museum", x: ["Le MoMA", "Le Guggenheim", "Le Whitney"], acc: ["metropolitan", "met"] },
  { id: "manneq-p5", d: 4, t: "Quelle mannequin est célèbre pour sa chute en plateformes Vivienne Westwood en 1993 ?", a: "Naomi Campbell", x: ["Kate Moss", "Linda Evangelista", "Christy Turlington"] },
  { id: "manneq-p6", d: 4, t: "Quelle photographe américaine est célèbre pour ses portraits de stars dans Vanity Fair ?", a: "Annie Leibovitz", x: ["Ellen von Unwerth", "Cindy Sherman", "Inez van Lamsweerde"] },
  { id: "manneq-p7", d: 4, t: "Quel photographe de mode allemand, au style sulfureux, a immortalisé les tops des années 90 ?", a: "Helmut Newton", x: ["Peter Lindbergh", "Mario Testino", "Steven Meisel"] },
  { id: "manneq-p8", d: 4, t: "Quel photographe a réuni cinq supermodels sur une couverture de Vogue en 1990 ?", a: "Peter Lindbergh", x: ["Helmut Newton", "Mario Testino", "Richard Avedon"] },
  { id: "manneq-p9", d: 4, t: "Quel clip de George Michael de 1990 réunit cinq supermodels en playback ?", a: "Freedom! '90", x: ["Vogue", "Supermodel", "Wicked Game"], acc: ["freedom", "freedom 90"] },
  { id: "manneq-p10", d: 4, t: "Quelle chanson de Madonna de 1990 rend hommage à la pose des mannequins ?", a: "Vogue", x: ["Material Girl", "Express Yourself", "Fashion"] },
  { id: "manneq-p11", d: 4, t: "Quel mannequin masculin britannique, ex-égérie de Dolce & Gabbana, est l'un des plus demandés ?", a: "David Gandy", x: ["Sean O'Pry", "Jon Kortajarena", "Lucky Blue Smith"] },
  { id: "manneq-p12", d: 4, t: "Comment appelle-t-on le recueil de photos qu'un mannequin présente aux clients ?", a: "Le book", x: ["Le catalogue", "L'affiche", "Le carnet"], acc: ["book", "portfolio"] },
  { id: "manneq-p13", d: 4, t: "Comment appelle-t-on la carte avec photos et mensurations d'un mannequin ?", a: "La composite", x: ["Le book", "Le lookbook", "La fiche"], acc: ["composite", "comp card"] },
  { id: "manneq-p14", d: 4, t: "Quelle Fashion Week clôt traditionnellement le mois des défilés, après New York, Londres et Milan ?", a: "Paris", x: ["New York", "Tokyo", "Berlin"] },
  { id: "manneq-p15", d: 4, t: "Quelle top model russe, ancienne étoile de Calvin Klein, est aussi une grande philanthrope ?", a: "Natalia Vodianova", x: ["Sasha Pivovarova", "Irina Shayk", "Anne Vyalitsyna"] },
  { id: "manneq-p16", d: 4, t: "Quelle top model russe, ex-Ange Victoria's Secret, a été la compagne de Cristiano Ronaldo ?", a: "Irina Shayk", x: ["Natalia Vodianova", "Sasha Pivovarova", "Anne Vyalitsyna"] },
  { id: "manneq-p17", d: 4, t: "Comment appelle-t-on les mannequins hors des standards de taille, de plus en plus présents ?", a: "Les mannequins grande taille", x: ["Les mannequins cabine", "Les mannequins mains", "Les égéries"], acc: ["grande taille", "plus size"] },
  { id: "manneq-p18", d: 4, t: "Quelle mannequin grande taille américaine a fait la couverture de Sports Illustrated, pionnière du body positive ?", a: "Ashley Graham", x: ["Tess Holliday", "Paloma Elsesser", "Precious Lee"] },
  { id: "manneq-p19", d: 4, t: "Quelle mannequin allemande présente l'émission « Germany's Next Topmodel » ?", a: "Heidi Klum", x: ["Claudia Schiffer", "Nadja Auermann", "Toni Garrn"] },
  { id: "manneq-p20", d: 4, t: "Comment appelle-t-on un mannequin qui ne défile que pour une seule marque sur une saison ?", a: "Une exclusivité", x: ["Une égérie", "Une cabine", "Une doublure"], acc: ["exclusivité", "exclusive"] },
]);
