import { universe } from '../_build';

export const maquillage = universe('mode', 'Maquillage', [
  // --- Faciles (5) ---
  { id: "maq-f1", d: 1, t: "Quel produit s'applique sur les lèvres pour les colorer ?", a: "Le rouge à lèvres", x: ["Le mascara", "Le fond de teint", "Le vernis"], acc: ["rouge a levres", "rouge à lèvres"] },
  { id: "maq-f2", d: 1, t: "Quel produit allonge et colore les cils ?", a: "Le mascara", x: ["Le rouge à lèvres", "Le fard à joues", "Le crayon"], acc: ["mascara"] },
  { id: "maq-f3", d: 1, t: "Quel produit uniformise le teint du visage ?", a: "Le fond de teint", x: ["Le mascara", "Le vernis", "Le démaquillant"], acc: ["fond de teint"] },
  { id: "maq-f4", d: 1, t: "Quel produit coloré s'applique sur les ongles ?", a: "Le vernis à ongles", x: ["Le mascara", "Le rouge à lèvres", "Le fard"], acc: ["vernis", "vernis a ongles"] },
  { id: "maq-f5", d: 1, t: "Comment appelle-t-on la poudre colorée appliquée sur les paupières ?", a: "Le fard à paupières", x: ["Le blush", "Le mascara", "Le rouge à lèvres"], acc: ["fard a paupieres", "fard à paupières", "ombre a paupieres"] },
  // --- Moyennes (10) ---
  { id: "maq-m1", d: 2, t: "Comment appelle-t-on le fard rosé appliqué sur les pommettes ?", a: "Le blush", x: ["L'enlumineur", "Le mascara", "L'eye-liner"], acc: ["blush", "fard a joues"] },
  { id: "maq-m2", d: 2, t: "Quel produit trace un trait précis le long des cils ?", a: "L'eye-liner", x: ["Le mascara", "Le blush", "Le gloss"], acc: ["eye-liner", "eyeliner"] },
  { id: "maq-m3", d: 2, t: "Comment appelle-t-on le produit brillant et transparent appliqué sur les lèvres ?", a: "Le gloss", x: ["Le blush", "Le mascara", "Le fond de teint"], acc: ["gloss"] },
  { id: "maq-m4", d: 2, t: "Quel produit illumine les points hauts du visage ?", a: "L'enlumineur", x: ["Le fond de teint", "Le mascara", "Le démaquillant"], acc: ["enlumineur", "highlighter"] },
  { id: "maq-m5", d: 2, t: "Comment appelle-t-on la technique qui sculpte et assombrit les creux du visage ?", a: "Le contouring", x: ["Le blush", "Le smoky", "Le strobing"], acc: ["contouring"] },
  { id: "maq-m6", d: 2, t: "Quel outil en forme d'éponge sert à appliquer le fond de teint ?", a: "L'éponge à maquillage", x: ["Le pinceau à lèvres", "Le recourbe-cils", "La lime"], acc: ["eponge", "beauty blender", "eponge a maquillage"] },
  { id: "maq-m7", d: 2, t: "Quel petit outil recourbe les cils avant le mascara ?", a: "Le recourbe-cils", x: ["La pince à épiler", "Le pinceau", "L'éponge"], acc: ["recourbe-cils"] },
  { id: "maq-m8", d: 2, t: "Comment appelle-t-on un maquillage des yeux sombre et estompé ?", a: "Le smoky eyes", x: ["Le no-make-up", "Le contouring", "Le strobing"], acc: ["smoky", "smoky eyes"] },
  { id: "maq-m9", d: 2, t: "Quel produit sert à retirer le maquillage le soir ?", a: "Le démaquillant", x: ["Le fond de teint", "Le fixateur", "L'apprêt"], acc: ["demaquillant", "démaquillant"] },
  { id: "maq-m10", d: 2, t: "Comment appelle-t-on la base appliquée avant le fond de teint pour lisser la peau ?", a: "La base de teint", x: ["Le fixateur", "L'anticernes", "L'enlumineur"], acc: ["base", "primer", "base de teint"] },
  // --- Dures (15) ---
  { id: "maq-d1", d: 3, t: "Quel produit couvre les cernes et les petites imperfections ?", a: "L'anticernes", x: ["Le blush", "Le mascara", "Le gloss"], acc: ["anticernes", "correcteur"] },
  { id: "maq-d2", d: 3, t: "Comment appelle-t-on la poudre qui fixe le fond de teint et matifie la peau ?", a: "La poudre libre", x: ["Le blush", "L'enlumineur", "Le fard"], acc: ["poudre libre", "poudre matifiante"] },
  { id: "maq-d3", d: 3, t: "Quel produit vaporisé fait tenir le maquillage toute la journée ?", a: "Le spray fixateur", x: ["Le démaquillant", "La base", "Le tonique"], acc: ["spray fixateur", "fixateur", "fixing spray"] },
  { id: "maq-d4", d: 3, t: "Quelle maison française de luxe possède le maquillage et le parfum N° 5 ?", a: "Chanel", x: ["Dior", "Guerlain", "Lancôme"], acc: ["chanel"] },
  { id: "maq-d5", d: 3, t: "Quelle marque de maquillage prisée des professionnels est abrégée MAC ?", a: "MAC Cosmetics", x: ["Maybelline", "Sephora", "NYX"], acc: ["mac", "mac cosmetics"] },
  { id: "maq-d6", d: 3, t: "Comment appelle-t-on la technique lumineuse qui fait briller les points hauts sans poudre sculptante ?", a: "Le strobing", x: ["Le contouring", "Le baking", "Le smoky"], acc: ["strobing"] },
  { id: "maq-d7", d: 3, t: "Comment appelle-t-on la technique consistant à laisser poser une poudre puis l'épousseter pour un teint net ?", a: "Le baking", x: ["Le strobing", "Le contouring", "Le tightlining"], acc: ["baking"] },
  { id: "maq-d8", d: 3, t: "Que mesure l'indice noté FPS ou SPF sur une BB crème ?", a: "La protection solaire", x: ["La couvrance", "La matité", "La tenue"], acc: ["protection solaire", "spf", "indice de protection solaire"] },
  { id: "maq-d9", d: 3, t: "Comment appelle-t-on une crème teintée légère, abrégée BB, née en Asie ?", a: "La BB crème", x: ["Le fond de teint fluide", "Le fard", "Le correcteur"], acc: ["bb creme", "bb crème", "blemish balm"] },
  { id: "maq-d10", d: 3, t: "Quel crayon ou poudre redessine et remplit les sourcils ?", a: "Le crayon à sourcils", x: ["L'eye-liner", "Le mascara", "L'enlumineur"], acc: ["crayon a sourcils", "crayon sourcils"] },
  { id: "maq-d11", d: 3, t: "Quelle marque de maquillage grand public a pour slogan « Parce que vous le valez bien » ?", a: "L'Oréal", x: ["Maybelline", "Bourjois", "Yves Rocher"], acc: ["l'oreal", "loreal", "l'oréal"] },
  { id: "maq-d12", d: 3, t: "De quel pays vient la forte culture beauté dite « K-beauty » ?", a: "La Corée du Sud", x: ["Le Japon", "La Chine", "La Thaïlande"], acc: ["coree du sud", "corée du sud", "coree"] },
  { id: "maq-d13", d: 3, t: "Comment appelle-t-on un maquillage discret imitant une peau nue et fraîche ?", a: "Le no-make-up", x: ["Le smoky", "Le glam", "Le cut crease"], acc: ["no-make-up", "nude", "effet bonne mine"] },
  { id: "maq-d14", d: 3, t: "Comment appelle-t-on la technique creusant nettement le pli de la paupière ?", a: "Le cut crease", x: ["Le smoky", "Le strobing", "Le baking"], acc: ["cut crease"] },
  { id: "maq-d15", d: 3, t: "Quel accessoire aux poils fins applique poudres et fards avec précision ?", a: "Le pinceau de maquillage", x: ["Le recourbe-cils", "La lime", "Le miroir"], acc: ["pinceau", "pinceau de maquillage"] },
  // --- Pro (20) ---
  { id: "maq-p1", d: 4, t: "Quel entrepreneur, pionnier du maquillage de cinéma à Hollywood, a donné son nom à une marque ?", a: "Max Factor", x: ["Estée Lauder", "Helena Rubinstein", "Charles Revson"], acc: ["max factor", "factor"] },
  { id: "maq-p2", d: 4, t: "Quelle femme d'affaires américaine a fondé un empire de cosmétiques à son nom en 1946 ?", a: "Estée Lauder", x: ["Helena Rubinstein", "Elizabeth Arden", "Mary Kay"], acc: ["estee lauder", "estée lauder", "lauder"] },
  { id: "maq-p3", d: 4, t: "Quelle pionnière de l'industrie a fondé la marque de cosmétiques portant son nom ?", a: "Helena Rubinstein", x: ["Estée Lauder", "Elizabeth Arden", "Charlotte Tilbury"], acc: ["helena rubinstein", "rubinstein"] },
  { id: "maq-p4", d: 4, t: "Quel colorant rouge, tiré de cochenilles, a longtemps coloré les rouges à lèvres ?", a: "Le carmin", x: ["L'indigo", "Le henné", "La garance"], acc: ["carmin"] },
  { id: "maq-p5", d: 4, t: "Quel ingrédient nacré, autrefois tiré d'écailles de poisson, donne l'effet brillant des produits ?", a: "La nacre", x: ["Le mica", "Le talc", "La cire"], acc: ["nacre", "essence de perle"] },
  { id: "maq-p6", d: 4, t: "Quel minéral scintillant est très utilisé pour l'effet lumineux des fards ?", a: "Le mica", x: ["Le talc", "Le kaolin", "Le gypse"], acc: ["mica"] },
  { id: "maq-p7", d: 4, t: "Dans l'Égypte antique, quel fard noir soulignait les yeux et protégeait du soleil ?", a: "Le khôl", x: ["Le henné", "L'ocre", "Le carmin"], acc: ["khol", "khôl", "kohl"] },
  { id: "maq-p8", d: 4, t: "Quel pigment naturel rouge ou brun sert de fard depuis la préhistoire ?", a: "L'ocre", x: ["Le khôl", "Le mica", "La nacre"], acc: ["ocre"] },
  { id: "maq-p9", d: 4, t: "Quelle poudre blanche au plomb, toxique, blanchissait les visages à la cour de Versailles ?", a: "La céruse", x: ["Le talc", "Le kaolin", "La craie"], acc: ["ceruse", "céruse", "blanc de ceruse"] },
  { id: "maq-p10", d: 4, t: "Comment appelle-t-on la petite pièce de tissu noir collée sur le visage au XVIIIe siècle ?", a: "La mouche", x: ["Le grain de beauté", "Le patch", "La perle"], acc: ["mouche", "mouche de beaute"] },
  { id: "maq-p11", d: 4, t: "Quelle marque de maquillage la chanteuse Rihanna a-t-elle lancée en 2017 ?", a: "Fenty Beauty", x: ["Kylie Cosmetics", "Rare Beauty", "KKW Beauty"], acc: ["fenty beauty", "fenty"] },
  { id: "maq-p12", d: 4, t: "Quelle chanteuse et actrice a lancé la marque de maquillage Rare Beauty ?", a: "Selena Gomez", x: ["Rihanna", "Kylie Jenner", "Ariana Grande"], acc: ["selena gomez", "gomez"] },
  { id: "maq-p13", d: 4, t: "Comment appelle-t-on l'artiste professionnel qui maquille mannequins et acteurs, abrégé MUA ?", a: "Le maquilleur", x: ["Le coiffeur", "Le styliste", "L'esthéticien"], acc: ["maquilleur", "make-up artist", "mua"] },
  { id: "maq-p14", d: 4, t: "Quelle marque créée par Kylie Jenner a explosé grâce à ses kits à lèvres ?", a: "Kylie Cosmetics", x: ["Fenty Beauty", "Rare Beauty", "Huda Beauty"], acc: ["kylie cosmetics", "kylie"] },
  { id: "maq-p15", d: 4, t: "Quelle maquilleuse et influenceuse a fondé la marque Huda Beauty ?", a: "Huda Kattan", x: ["Kylie Jenner", "Selena Gomez", "Pat McGrath"], acc: ["huda kattan", "huda"] },
  { id: "maq-p16", d: 4, t: "Quelle maquilleuse britannique de renom possède la marque Pat McGrath Labs ?", a: "Pat McGrath", x: ["Charlotte Tilbury", "Bobbi Brown", "Huda Kattan"], acc: ["pat mcgrath", "mcgrath"] },
  { id: "maq-p17", d: 4, t: "Quelle maquilleuse américaine prénommée Bobbi a donné son nom à une marque de teints naturels ?", a: "Bobbi Brown", x: ["Charlotte Tilbury", "Pat McGrath", "Laura Mercier"], acc: ["bobbi brown", "brown"] },
  { id: "maq-p18", d: 4, t: "Quel test cutané vérifie qu'un cosmétique ne provoque pas d'allergie ?", a: "Le test épicutané", x: ["Le peeling", "Le gommage", "Le masque"], acc: ["test epicutane", "patch test", "test cutane"] },
  { id: "maq-p19", d: 4, t: "Quelle mention indique qu'un cosmétique n'a pas été testé sur les animaux ?", a: "Cruelty-free", x: ["Bio", "Vegan", "Hypoallergénique"], acc: ["cruelty-free", "cruelty free", "sans cruaute"] },
  { id: "maq-p20", d: 4, t: "Selon le cercle chromatique, quelle couleur de correcteur neutralise les rougeurs de la peau ?", a: "Le vert", x: ["Le rouge", "Le bleu", "Le jaune"], acc: ["vert"] },
]);
