import { universe } from "../_build";

export const streetwear = universe("mode", "Streetwear et sneakers", [
  // --- Faciles (5) ---
  { id: "street-f1", d: 1, t: "Quelle marque new-yorkaise de skate au logo rouge et blanc est culte dans le streetwear ?", a: "Supreme", x: ["Off-White", "Palace", "Stüssy"] },
  { id: "street-f2", d: 1, t: "Quelle marque au logo en virgule, le « swoosh », domine la sneaker ?", a: "Nike", x: ["Adidas", "Puma", "Reebok"] },
  { id: "street-f3", d: 1, t: "Quelle marque allemande aux trois bandes est la grande rivale de Nike ?", a: "Adidas", x: ["Nike", "Puma", "New Balance"] },
  { id: "street-f4", d: 1, t: "Quelle silhouette mythique de Nike, née au basket, porte le nom d'un joueur légendaire ?", a: "La Air Jordan", x: ["La Stan Smith", "La Superstar", "La Air Max"], acc: ["air jordan", "jordan"] },
  { id: "street-f5", d: 1, t: "Comment appelle-t-on les passionnés qui collectionnent et revendent les sneakers rares ?", a: "Les sneakerheads", x: ["Les hypebeasts", "Les resellers", "Les swappers"], acc: ["sneakerhead", "sneakerheads"] },
  // --- Moyennes (10) ---
  { id: "street-m1", d: 2, t: "Quelle marque de streetwear de luxe fondée par Virgil Abloh détourne guillemets et flèches ?", a: "Off-White", x: ["Supreme", "A Bathing Ape", "Fear of God"] },
  { id: "street-m2", d: 2, t: "Quel créateur a fondé Off-White et habillé Louis Vuitton homme ?", a: "Virgil Abloh", x: ["Kanye West", "Nigo", "Jerry Lorenzo"] },
  { id: "street-m3", d: 2, t: "Quelle marque japonaise culte au singe, fondée par Nigo, est une icône du streetwear ?", a: "A Bathing Ape", x: ["Neighborhood", "Wtaps", "Undercover"], acc: ["a bathing ape", "bape"] },
  { id: "street-m4", d: 2, t: "Quelle collaboration de Kanye West avec Adidas a créé des sneakers très recherchées ?", a: "Yeezy", x: ["Fear of God", "Ivy Park", "Fenty"], acc: ["yeezy"] },
  { id: "street-m5", d: 2, t: "Quelle sneaker Adidas à coque en caoutchouc est une icône du hip-hop, chantée par Run-D.M.C. ?", a: "La Superstar", x: ["La Stan Smith", "La Gazelle", "La Samba"] },
  { id: "street-m6", d: 2, t: "Quelle sneaker Adidas au design tennis épuré porte le nom d'un joueur ?", a: "La Stan Smith", x: ["La Superstar", "La Gazelle", "La Forest Hills"] },
  { id: "street-m7", d: 2, t: "Quelle silhouette Nike à bulle d'air visible a révolutionné la basket en 1987 ?", a: "La Air Max", x: ["La Air Force 1", "La Cortez", "La Blazer"], acc: ["air max"] },
  { id: "street-m8", d: 2, t: "Quelle basket Nike montante, née au basket en 1982, est un classique intemporel ?", a: "La Air Force 1", x: ["La Air Max", "La Dunk", "La Blazer"], acc: ["air force 1", "af1"] },
  { id: "street-m9", d: 2, t: "Comment appelle-t-on la revente de produits hype à prix gonflé ?", a: "Le reselling", x: ["Le dropshipping", "Le thrifting", "Le restocking"], acc: ["reselling", "resell"] },
  { id: "street-m10", d: 2, t: "Comment appelle-t-on une sortie limitée d'un produit hype, souvent épuisé en minutes ?", a: "Un drop", x: ["Un raffle", "Un restock", "Un teaser"], acc: ["drop"] },
  // --- Dures (15) ---
  { id: "street-d1", d: 3, t: "Quel magasin new-yorkais, fondé par James Jebbia en 1994, est à l'origine de Supreme ?", a: "Supreme", x: ["Stüssy", "Palace", "Kith"] },
  { id: "street-d2", d: 3, t: "Quel surfeur californien a fondé la marque à la signature manuscrite, pionnière du streetwear ?", a: "Shawn Stussy", x: ["James Jebbia", "Nigo", "Bobby Hundreds"], acc: ["shawn stussy", "stussy"] },
  { id: "street-d3", d: 3, t: "Quelle marque de skate britannique au triangle est une rivale européenne de Supreme ?", a: "Palace", x: ["Supreme", "Carhartt WIP", "Corteiz"] },
  { id: "street-d4", d: 3, t: "Quelle plateforme au modèle « bourse » est devenue la référence de la revente de sneakers ?", a: "StockX", x: ["Grailed", "GOAT", "Vinted"] },
  { id: "street-d5", d: 3, t: "Quel Japonais, fondateur de Bape, a ensuite lancé la marque Human Made ?", a: "Nigo", x: ["Hiroshi Fujiwara", "Jun Takahashi", "Tetsu Nishiyama"] },
  { id: "street-d6", d: 3, t: "Quel « parrain » du streetwear japonais est à l'origine du mouvement Ura-Harajuku ?", a: "Hiroshi Fujiwara", x: ["Nigo", "Jun Takahashi", "Shawn Stussy"] },
  { id: "street-d7", d: 3, t: "Quelle marque de Jun Takahashi, sombre et arty, mêle punk et haute couture ?", a: "Undercover", x: ["Neighborhood", "Wtaps", "Visvim"] },
  { id: "street-d8", d: 3, t: "Quelle sneaker Nike de 1985, interdite en NBA, a fondé la légende Air Jordan ?", a: "La Air Jordan 1", x: ["La Air Jordan 3", "La Dunk", "La Air Max 1"], acc: ["air jordan 1", "aj1"] },
  { id: "street-d9", d: 3, t: "Quel designer Nike a créé la Air Jordan et de nombreuses silhouettes iconiques ?", a: "Tinker Hatfield", x: ["Peter Moore", "Bill Bowerman", "Mark Parker"] },
  { id: "street-d10", d: 3, t: "Quelle collaboration de 2017 entre deux géants a marqué la fusion luxe-street ?", a: "Louis Vuitton x Supreme", x: ["Dior x Jordan", "Gucci x The North Face", "Fendi x Skims"], acc: ["louis vuitton x supreme", "lv x supreme"] },
  { id: "street-d11", d: 3, t: "Quelle marque de workwear américaine, au logo carré, est adoptée par le streetwear ?", a: "Carhartt", x: ["Dickies", "Timberland", "The North Face"] },
  { id: "street-d12", d: 3, t: "Quelle marque outdoor au logo de montagne est un incontournable du streetwear urbain ?", a: "The North Face", x: ["Patagonia", "Columbia", "Arc'teryx"] },
  { id: "street-d13", d: 3, t: "Quelle sneaker Nike, longtemps mal-aimée puis culte via les collabs skate, porte un « SB » ?", a: "La Dunk", x: ["La Blazer", "La Cortez", "La Terminator"], acc: ["dunk", "nike sb dunk"] },
  { id: "street-d14", d: 3, t: "Quel rappeur a lancé la marque de skate et de streetwear « Golf Wang » ?", a: "Tyler, the Creator", x: ["Pharrell Williams", "A$AP Rocky", "Kid Cudi"] },
  { id: "street-d15", d: 3, t: "Quel rappeur et créateur a succédé à Virgil Abloh comme directeur de Louis Vuitton homme ?", a: "Pharrell Williams", x: ["Kanye West", "A$AP Rocky", "Tyler, the Creator"] },
  // --- Pro (20) ---
  { id: "street-p1", d: 4, t: "En quelle année Virgil Abloh est-il devenu directeur artistique de Louis Vuitton homme ?", a: "2018", x: ["2013", "2016", "2021"] },
  { id: "street-p2", d: 4, t: "Quelle marque Virgil Abloh a-t-il fondée avant Off-White, en 2012 ?", a: "Pyrex Vision", x: ["Been Trill", "Fear of God", "Rhude"], acc: ["pyrex vision", "pyrex"] },
  { id: "street-p3", d: 4, t: "Quel basketteur a rendu la Nike Air Jordan mondialement célèbre ?", a: "Michael Jordan", x: ["Kobe Bryant", "LeBron James", "Scottie Pippen"] },
  { id: "street-p4", d: 4, t: "Quel groupe, propriétaire de Vans et The North Face, a racheté Supreme en 2020 ?", a: "VF Corporation", x: ["Nike", "LVMH", "Kering"], acc: ["vf corporation", "vf corp"] },
  { id: "street-p5", d: 4, t: "Quelle collaboration entre Dior et Nike a fusionné haute couture et Air Jordan en 2020 ?", a: "La Air Jordan 1 Dior", x: ["La Yeezy 350", "La Air Force 1 Off-White", "La Dunk Travis Scott"], acc: ["dior jordan", "air jordan dior"] },
  { id: "street-p6", d: 4, t: "Quel rappeur a multiplié les collaborations Nike, dont des Air Jordan cousues à l'envers ?", a: "Travis Scott", x: ["Kanye West", "Drake", "A$AP Rocky"] },
  { id: "street-p7", d: 4, t: "Quelle marque de Jerry Lorenzo mêle streetwear et esthétique minimaliste beige ?", a: "Fear of God", x: ["Rhude", "Aimé Leon Dore", "Cactus Plant Flea Market"] },
  { id: "street-p8", d: 4, t: "Quelle marque new-yorkaise de Teddy Santis, au style universitaire, collabore avec New Balance ?", a: "Aimé Leon Dore", x: ["Kith", "Noah", "Rowing Blazers"] },
  { id: "street-p9", d: 4, t: "Quelle boutique-marque new-yorkaise de Ronnie Fieg est réputée pour ses collaborations ?", a: "Kith", x: ["Aimé Leon Dore", "Extra Butter", "Bodega"] },
  { id: "street-p10", d: 4, t: "Quelle marque britannique fondée par Clint a explosé auprès de la jeunesse dans les années 2020 ?", a: "Corteiz", x: ["Trapstar", "Palace", "Represent"], acc: ["corteiz", "crtz"] },
  { id: "street-p11", d: 4, t: "Quelle sneaker New Balance, chère aux « dad shoes », est devenue hype grâce aux collabs ?", a: "La 990", x: ["La 574", "La 327", "La 550"], acc: ["990"] },
  { id: "street-p12", d: 4, t: "Quel modèle New Balance rétro-basket a été relancé en collab avec Aimé Leon Dore ?", a: "La 550", x: ["La 990", "La 327", "La 992"], acc: ["550"] },
  { id: "street-p13", d: 4, t: "Quelle marque de doudounes italiennes de luxe est un statut dans le streetwear ?", a: "Moncler", x: ["Stone Island", "Canada Goose", "Herno"] },
  { id: "street-p14", d: 4, t: "Quelle marque italienne à la boussole sur la manche est culte chez les « casuals » ?", a: "Stone Island", x: ["Moncler", "C.P. Company", "Napapijri"] },
  { id: "street-p15", d: 4, t: "Comment appelle-t-on la tendance mêlant vêtements techniques de randonnée et style urbain ?", a: "Le gorpcore", x: ["Le normcore", "Le techwear", "Le cottagecore"], acc: ["gorpcore"] },
  { id: "street-p16", d: 4, t: "Comment appelle-t-on un vêtement ou une sneaker jamais porté, encore dans son emballage ?", a: "Deadstock", x: ["Vintage", "Grail", "Sample"], acc: ["deadstock", "ds"] },
  { id: "street-p17", d: 4, t: "Comment appelle-t-on la pièce ultime qu'un collectionneur rêve d'obtenir ?", a: "Un grail", x: ["Un drop", "Un deadstock", "Un sample"], acc: ["grail"] },
  { id: "street-p18", d: 4, t: "Quel créateur russe a fait défiler un streetwear post-soviétique soutenu par Comme des Garçons ?", a: "Gosha Rubchinskiy", x: ["Demna Gvasalia", "Lotta Volkova", "Heron Preston"], acc: ["gosha rubchinskiy", "gosha"] },
  { id: "street-p19", d: 4, t: "Quelle maison de luxe a lancé les sneakers massives « Triple S », icônes des « ugly sneakers » ?", a: "Balenciaga", x: ["Gucci", "Louis Vuitton", "Dior"] },
  { id: "street-p20", d: 4, t: "Quel site communautaire note et revend le streetwear et les pièces de créateurs d'occasion ?", a: "Grailed", x: ["StockX", "Depop", "Vestiaire Collective"] },
]);
