import { universe } from "../_build";

export const casadepapel = universe("series", "La Casa de Papel", [
  // --- Faciles (5) ---
  { id: "lcp-f1", d: 1, t: "Quel est le surnom du cerveau qui organise les braquages ?", a: "Le Professeur", acc: ["professeur", "el profesor"], x: ["Berlin", "Tokyo", "Rio"] },
  { id: "lcp-f2", d: 1, t: "Les braqueurs portent tous des noms de… ?", a: "Villes", acc: ["villes", "ville"], x: ["Pays", "Couleurs", "Animaux"] },
  { id: "lcp-f3", d: 1, t: "Quel masque emblématique portent les braqueurs ?", a: "Salvador Dalí", acc: ["dali", "salvador dali"], x: ["Guy Fawkes", "Scream", "Anonymous"] },
  { id: "lcp-f4", d: 1, t: "De quelle couleur sont les combinaisons des braqueurs ?", a: "Rouge", x: ["Bleu", "Noir", "Jaune"] },
  { id: "lcp-f5", d: 1, t: "Quel bâtiment est braqué dans les deux premières parties ?", a: "La Fabrique de la Monnaie", acc: ["fabrique de la monnaie", "maison de la monnaie", "monnaie"], x: ["La Banque d'Espagne", "Un casino", "Un musée"] },

  // --- Moyennes (10) ---
  { id: "lcp-m1", d: 2, t: "Quelle braqueuse est la narratrice principale de la série ?", a: "Tokyo", x: ["Nairobi", "Lisbonne", "Estocolmo"] },
  { id: "lcp-m2", d: 2, t: "Quel braqueur élégant, gravement malade, dirige l'équipe à l'intérieur ?", a: "Berlin", x: ["Rio", "Denver", "Moscou"] },
  { id: "lcp-m3", d: 2, t: "Quelle est la seconde grande cible ?", a: "La Banque d'Espagne", acc: ["banque d'espagne"], x: ["La Fabrique de la Monnaie", "La BCE", "Un casino"] },
  { id: "lcp-m4", d: 2, t: "Quelle inspectrice mène les négociations et tombe amoureuse du Professeur ?", a: "Raquel Murillo", acc: ["raquel", "murillo"], x: ["Alicia", "Nairobi", "Tokyo"] },
  { id: "lcp-m5", d: 2, t: "Sous quel faux nom le Professeur approche-t-il Raquel ?", a: "Salva", x: ["Sergio", "Berlin", "Rio"] },
  { id: "lcp-m6", d: 2, t: "Quel jeune hacker est amoureux de Tokyo ?", a: "Rio", x: ["Denver", "Moscou", "Helsinki"] },
  { id: "lcp-m7", d: 2, t: "Quelle braqueuse coordonne l'impression des billets ?", a: "Nairobi", x: ["Tokyo", "Estocolmo", "Lisbonne"] },
  { id: "lcp-m8", d: 2, t: "Quel duo père et fils fait partie des braqueurs ?", a: "Moscou et Denver", acc: ["moscou et denver", "denver et moscou"], x: ["Helsinki et Oslo", "Berlin et Rio", "Rio et Tokyo"] },
  { id: "lcp-m9", d: 2, t: "Quels deux gros bras cousins d'origine serbe rejoignent l'équipe ?", a: "Helsinki et Oslo", acc: ["helsinki et oslo"], x: ["Moscou et Denver", "Bogota et Rio", "Berlin et Palerme"] },
  { id: "lcp-m10", d: 2, t: "Quel braqueur est connu pour son rire particulier ?", a: "Denver", x: ["Rio", "Berlin", "Helsinki"] },

  // --- Dures (15) ---
  { id: "lcp-d1", d: 3, t: "Quel est le vrai prénom du Professeur ?", a: "Sergio Marquina", acc: ["sergio", "sergio marquina", "marquina"], x: ["Andrés", "Salva", "Aníbal"] },
  { id: "lcp-d2", d: 3, t: "Quel est le lien réel entre Berlin et le Professeur ?", a: "Ce sont des frères", acc: ["freres", "des freres"], x: ["Père et fils", "Cousins", "Simples amis"] },
  { id: "lcp-d3", d: 3, t: "Quel est le vrai nom de Berlin ?", a: "Andrés de Fonollosa", acc: ["andres", "andres de fonollosa", "fonollosa"], x: ["Sergio", "Martín", "Aníbal"] },
  { id: "lcp-d4", d: 3, t: "Quel nom de braqueuse Raquel adopte-t-elle en rejoignant la bande ?", a: "Lisbonne", x: ["Estocolmo", "Nairobi", "Tokyo"] },
  { id: "lcp-d5", d: 3, t: "Quelle employée devenue braqueuse tombe amoureuse de Denver ?", a: "Mónica Gaztambide", acc: ["monica", "monica gaztambide", "gaztambide"], x: ["Raquel", "Alicia", "Ariadna"] },
  { id: "lcp-d6", d: 3, t: "Quelle inspectrice enceinte et impitoyable traque la bande ?", a: "Alicia Sierra", acc: ["alicia", "alicia sierra", "sierra"], x: ["Raquel", "Mónica", "Tokyo"] },
  { id: "lcp-d7", d: 3, t: "Quel ami ingénieur du Professeur a conçu le plan du braquage de la Banque ?", a: "Martín", acc: ["martin", "palerme", "palermo"], x: ["Rio", "Bogota", "Helsinki"] },
  { id: "lcp-d8", d: 3, t: "Quel nom de code Martín porte-t-il lors du second braquage ?", a: "Palerme", acc: ["palerme", "palermo"], x: ["Marseille", "Lisbonne", "Berlin"] },
  { id: "lcp-d9", d: 3, t: "Quel braqueur orfèvre est chargé de fondre l'or à la Banque d'Espagne ?", a: "Bogota", x: ["Marseille", "Palerme", "Helsinki"] },
  { id: "lcp-d10", d: 3, t: "Quelle braqueuse meurt en héroïne, prise pour cible par un tireur ?", a: "Nairobi", x: ["Tokyo", "Estocolmo", "Lisbonne"] },
  { id: "lcp-d11", d: 3, t: "Comment Berlin meurt-il à la fin de la partie 2 ?", a: "Il se sacrifie sous les balles de la police", acc: ["il se sacrifie", "sous les balles", "sacrifie"], x: ["D'une overdose", "Trahi par Tokyo", "Dans une explosion"] },
  { id: "lcp-d12", d: 3, t: "De quelle maladie Berlin est-il atteint ?", a: "Une myopathie", acc: ["myopathie", "helmer"], x: ["Un cancer", "Le sida", "Alzheimer"] },
  { id: "lcp-d13", d: 3, t: "Quelle chanson devient l'hymne des braqueurs ?", a: "« Bella Ciao »", acc: ["bella ciao"], x: ["« Despacito »", "« La Bamba »", "« Ciao Bella »"] },
  { id: "lcp-d14", d: 3, t: "Quel petit ami braqueur de Tokyo meurt lors du flash-back initial ?", a: "René", x: ["Rio", "Denver", "Aníbal"] },
  { id: "lcp-d15", d: 3, t: "D'où le Professeur dirige-t-il les opérations pendant le braquage ?", a: "Depuis un poste de commandement extérieur", acc: ["hangar", "poste de commandement", "de l'exterieur"], x: ["De l'intérieur", "D'un bateau", "Du commissariat"] },

  // --- Pro (20) ---
  { id: "lcp-p1", d: 4, t: "Comment Tokyo meurt-elle ?", a: "Elle se sacrifie en se faisant exploser", acc: ["elle se sacrifie", "explosion", "grenades"], x: ["Abattue en fuyant", "Trahie", "D'une overdose"] },
  { id: "lcp-p2", d: 4, t: "Combien de jours dure environ le braquage de la Fabrique de la Monnaie ?", a: "Environ 11 jours", acc: ["11 jours", "11", "onze jours"], x: ["3 jours", "1 mois", "5 jours"] },
  { id: "lcp-p3", d: 4, t: "Que fabriquent les braqueurs à la Fabrique de la Monnaie ?", a: "Des billets d'euros", acc: ["des billets", "billets", "euros"], x: ["De l'or", "De faux passeports", "Des obligations"] },
  { id: "lcp-p4", d: 4, t: "Que veulent voler les braqueurs à la Banque d'Espagne ?", a: "De l'or", acc: ["or", "lingots", "de l'or"], x: ["Des billets", "Des bijoux", "Des documents"] },
  { id: "lcp-p5", d: 4, t: "Quel est le vrai prénom de Tokyo ?", a: "Silene Oliveira", acc: ["silene", "silene oliveira"], x: ["Ágata", "Mónica", "Raquel"] },
  { id: "lcp-p6", d: 4, t: "Quel est le vrai prénom de Nairobi ?", a: "Ágata Jiménez", acc: ["agata", "agata jimenez"], x: ["Silene", "Mónica", "Raquel"] },
  { id: "lcp-p7", d: 4, t: "Quel est le vrai prénom de Denver ?", a: "Daniel Ramos", acc: ["daniel", "daniel ramos"], x: ["Aníbal", "Martín", "Mirko"] },
  { id: "lcp-p8", d: 4, t: "Quel est le vrai prénom de Moscou ?", a: "Agustín Ramos", acc: ["agustin", "agustin ramos"], x: ["Aníbal Cortés", "Mirko Dragic", "Daniel"] },
  { id: "lcp-p9", d: 4, t: "Quel est le vrai prénom de Rio ?", a: "Aníbal Cortés", acc: ["anibal", "anibal cortes"], x: ["Silene", "Daniel", "Martín"] },
  { id: "lcp-p10", d: 4, t: "Quel est le lien entre Helsinki et Oslo ?", a: "Ce sont des cousins serbes", acc: ["cousins", "cousins serbes"], x: ["Frères", "Père et fils", "Amis d'enfance"] },
  { id: "lcp-p11", d: 4, t: "Qui prend la tête de l'équipe à l'intérieur de la Banque d'Espagne ?", a: "Palerme", x: ["Tokyo", "Denver", "Bogota"] },
  { id: "lcp-p12", d: 4, t: "Quel fils de Berlin rejoint le braquage de la Banque d'Espagne ?", a: "Rafael", x: ["Palerme", "Bogota", "Marseille"] },
  { id: "lcp-p13", d: 4, t: "Quel braqueur, expert en plongée et évasion, rejoint la bande ?", a: "Marseille", acc: ["marseille", "marsella"], x: ["Bogota", "Palerme", "Helsinki"] },
  { id: "lcp-p14", d: 4, t: "Que finit par faire l'inspectrice Alicia Sierra vis-à-vis de la bande ?", a: "Elle finit par les aider", acc: ["elle les aide", "elle finit par les aider"], x: ["Elle les tue", "Elle les fait arrêter", "Elle disparaît"] },
  { id: "lcp-p15", d: 4, t: "Combien de parties compte La Casa de Papel ?", a: "5", acc: ["cinq"], x: ["3", "4", "6"] },
  { id: "lcp-p16", d: 4, t: "Qui est le créateur de la série ?", a: "Álex Pina", acc: ["alex pina", "pina"], x: ["Pedro Almodóvar", "Álex de la Iglesia", "Alejandro Amenábar"] },
  { id: "lcp-p17", d: 4, t: "Comment les braqueurs comptent-ils sortir l'or de la Banque d'Espagne ?", a: "En le faisant fondre et évacuer par les canalisations", acc: ["fondre", "canalisations", "tuyaux"], x: ["Par un tunnel", "En hélicoptère", "Dans des camions"] },
  { id: "lcp-p18", d: 4, t: "Quel otage insupportable revient plus tard ?", a: "Arturo Román", acc: ["arturo", "arturo roman", "arturito"], x: ["Gandía", "Gaztambide", "Rafael"] },
  { id: "lcp-p19", d: 4, t: "Quel chef de la sécurité de la Banque d'Espagne sème le chaos et tue Nairobi ?", a: "Gandía", x: ["Arturo", "Tamayo", "Palerme"] },
  { id: "lcp-p20", d: 4, t: "Dans quelle ville se déroulent principalement les braquages ?", a: "Madrid", x: ["Barcelone", "Séville", "Valence"] },
]);
