import { universe } from "../_build";

export const enfance = universe("series", "Dessins animés de notre enfance", [
  // --- Faciles (5) ---
  { id: "enfance-f1", d: 1, t: "Quel dessin animé se déroule dans la ville sous-marine de Bikini Bottom ?", a: "Bob l'éponge", x: ["Oggy et les cafards", "Némo", "La Petite Sirène"], acc: ["bob l'éponge", "spongebob"] },
  { id: "enfance-f2", d: 1, t: "Quel chien parlant résout des mystères avec la bande du Mystery Machine ?", a: "Scooby-Doo", x: ["Droopy", "Pluto", "Rex"] },
  { id: "enfance-f3", d: 1, t: "Quelles trois super-héroïnes fillettes sauvent la ville de Townsville ?", a: "Les Supers Nanas", x: ["Totally Spies", "Les Winx", "W.I.T.C.H."], acc: ["supers nanas", "powerpuff girls"] },
  { id: "enfance-f4", d: 1, t: "Quel écolier suisse à la houppette est le héros d'une BD et série de Zep ?", a: "Titeuf", x: ["Cédric", "Kid Paddle", "Le Petit Spirou"] },
  { id: "enfance-f5", d: 1, t: "Quel duo formé d'une souris et d'un chat se poursuit sans fin dans ce dessin animé ?", a: "Tom et Jerry", x: ["Titi et Grosminet", "Bugs Bunny", "Woody Woodpecker"], acc: ["tom et jerry"] },
  // --- Moyennes (10) ---
  { id: "enfance-m1", d: 2, t: "Quel trio d'espionnes ados de Beverly Hills travaille pour le WOOHP ?", a: "Totally Spies", x: ["Les Winx", "W.I.T.C.H.", "Code Lyoko"] },
  { id: "enfance-m2", d: 2, t: "Quels ados voyagent dans le monde virtuel de Lyoko pour combattre XANA ?", a: "Code Lyoko", x: ["Totally Spies", "Oban Star-Racers", "Wakfu"] },
  { id: "enfance-m3", d: 2, t: "Quel maître de l'air, dernier de son espèce, doit sauver le monde des quatre nations ?", a: "Avatar, le dernier maître de l'air", x: ["Ben 10", "Danny Fantôme", "Jackie Chan"], acc: ["avatar", "aang"] },
  { id: "enfance-m4", d: 2, t: "Quel garçon peut se transformer en dix extraterrestres grâce à une montre ?", a: "Ben 10", x: ["Danny Fantôme", "Max Steel", "Générator Rex"], acc: ["ben 10"] },
  { id: "enfance-m5", d: 2, t: "Quel dessin animé suit des bébés menés par Tommy Pickles ?", a: "Les Razmoket", x: ["Rocket Power", "Hé Arnold", "La Cour de récré"], acc: ["razmoket", "rugrats"] },
  { id: "enfance-m6", d: 2, t: "Quel garçon à la tête en ballon de rugby vit dans une pension en pleine ville ?", a: "Hé Arnold", x: ["Doug", "Bobby", "Timmy Turner"], acc: ["hé arnold", "hey arnold"] },
  { id: "enfance-m7", d: 2, t: "Quels deux beaux-frères inventent des machines folles chaque jour d'été ?", a: "Phineas et Ferb", x: ["Ed, Edd et Eddy", "Kick Kasskoo", "Les Supers Nanas"], acc: ["phineas et ferb"] },
  { id: "enfance-m8", d: 2, t: "Quel enfant génie cache un laboratoire secret dans « Le Laboratoire de Dexter » ?", a: "Dexter", x: ["Mandark", "Jimmy", "Timmy"] },
  { id: "enfance-m9", d: 2, t: "Quel garçon obtient tout ce qu'il souhaite grâce à ses fées Cosmo et Wanda ?", a: "Timmy Turner", x: ["Jimmy Neutron", "Danny Fenton", "Bart Simpson"], acc: ["timmy turner", "parrains magiques"] },
  { id: "enfance-m10", d: 2, t: "Quelle famille jaune de Springfield est la plus célèbre du dessin animé ?", a: "Les Simpson", x: ["Les Griffin", "American Dad", "Futurama"], acc: ["simpson"] },
  // --- Dures (15) ---
  { id: "enfance-d1", d: 3, t: "Quel dessin animé met en scène un animal moitié chat, moitié chien, partageant un même corps ?", a: "CatDog", x: ["Oggy et les cafards", "Ren et Stimpy", "Angela Anaconda"], acc: ["catdog"] },
  { id: "enfance-d2", d: 3, t: "Quel chat bleu doit se débarrasser de trois cafards dans ce dessin animé français sans dialogues ?", a: "Oggy et les cafards", x: ["Titi et Grosminet", "CatDog", "Grabouillon"], acc: ["oggy"] },
  { id: "enfance-d3", d: 3, t: "Quel dessin animé suit trois garçons du même prénom coincés dans une impasse ?", a: "Ed, Edd et Eddy", x: ["Billy et Mandy", "Camp Lazlo", "Mes parrains sont magiques"], acc: ["ed edd et eddy"] },
  { id: "enfance-d4", d: 3, t: "Quels deux amis, un humain et un chien magique, vivent au pays de Ooo ?", a: "Adventure Time", x: ["Regular Show", "Steven Universe", "Clarence"], acc: ["adventure time"] },
  { id: "enfance-d5", d: 3, t: "Dans quelle maison les amis imaginaires abandonnés trouvent-ils refuge ?", a: "Foster, la maison des amis imaginaires", x: ["Le Monde incroyable de Gumball", "Chowder", "Flapjack"], acc: ["foster"] },
  { id: "enfance-d6", d: 3, t: "Quel chat bleu vit avec un poisson et une famille dans « Le Monde incroyable de Gumball » ?", a: "Gumball", x: ["Darwin", "Anaïs", "Richard"], acc: ["gumball"] },
  { id: "enfance-d7", d: 3, t: "Quel dessin animé suit un écureuil et un geai bleu employés dans un parc ?", a: "Regular Show", x: ["Adventure Time", "Clarence", "Uncle Grandpa"], acc: ["regular show", "au boulot les gars"] },
  { id: "enfance-d8", d: 3, t: "Quelle série animée française de type manga suit Yugo dans le monde des Douze ?", a: "Wakfu", x: ["Code Lyoko", "Oban Star-Racers", "Foot 2 Rue"], acc: ["wakfu"] },
  { id: "enfance-d9", d: 3, t: "Quelle série animée suit une course de vaisseaux intergalactique avec Molly et Jordan ?", a: "Oban Star-Racers", x: ["Code Lyoko", "Galactik Football", "Wakfu"], acc: ["oban star-racers", "oban"] },
  { id: "enfance-d10", d: 3, t: "Quelle sorcière adolescente, avec son chat parlant Salem, apprend la magie ?", a: "Sabrina, l'apprentie sorcière", x: ["Les Winx", "W.I.T.C.H.", "Charmed"], acc: ["sabrina"] },
  { id: "enfance-d11", d: 3, t: "Quelle série Disney Channel suit une ado, popstar secrète sous le nom d'Hannah Montana ?", a: "Hannah Montana", x: ["iCarly", "Violetta", "Sonny"] },
  { id: "enfance-d12", d: 3, t: "Quelle série de Nickelodeon suit une ado qui anime un webshow avec ses amis ?", a: "iCarly", x: ["Hannah Montana", "Victorious", "Drake et Josh"] },
  { id: "enfance-d13", d: 3, t: "Quel dessin animé DC réunit Robin, Starfire et Cyborg version ados ?", a: "Teen Titans", x: ["Young Justice", "Ben 10", "La Ligue des justiciers"], acc: ["teen titans", "les jeunes titans"] },
  { id: "enfance-d14", d: 3, t: "Quelle série animée suit un jeune héros et sa quête des talismans avec son oncle antiquaire ?", a: "Jackie Chan", x: ["Xiaolin Showdown", "Kung Fu Panda", "Avatar"], acc: ["jackie chan", "aventures de jackie chan"] },
  { id: "enfance-d15", d: 3, t: "Quels moines apprentis collectent des objets Shen Gong Wu dans cette série ?", a: "Xiaolin Showdown", x: ["Jackie Chan", "Kung Fu Panda", "Samurai Jack"], acc: ["xiaolin showdown"] },
  // --- Pro (20) ---
  { id: "enfance-p1", d: 4, t: "Quelle chaîne américaine a produit Bob l'éponge, Les Razmoket et Hé Arnold ?", a: "Nickelodeon", x: ["Cartoon Network", "Disney Channel", "Fox Kids"] },
  { id: "enfance-p2", d: 4, t: "Quelle chaîne a produit Le Laboratoire de Dexter, Les Supers Nanas et Ben 10 ?", a: "Cartoon Network", x: ["Nickelodeon", "Disney Channel", "France 3"] },
  { id: "enfance-p3", d: 4, t: "Qui a créé « Bob l'éponge » ?", a: "Stephen Hillenburg", x: ["Matt Groening", "Craig McCracken", "Butch Hartman"] },
  { id: "enfance-p4", d: 4, t: "Qui a créé « Les Supers Nanas » et « Foster » ?", a: "Craig McCracken", x: ["Stephen Hillenburg", "Genndy Tartakovsky", "Butch Hartman"] },
  { id: "enfance-p5", d: 4, t: "Qui a créé « Le Laboratoire de Dexter » et « Samurai Jack » ?", a: "Genndy Tartakovsky", x: ["Craig McCracken", "Matt Groening", "Seth MacFarlane"] },
  { id: "enfance-p6", d: 4, t: "Quel dessin animé français met en scène un petit garçon curieux nommé T'choupi ?", a: "T'choupi", x: ["Petit Ours brun", "Trotro", "Oui-Oui"] },
  { id: "enfance-p7", d: 4, t: "Quel âne bavard et farceur est le héros d'un dessin animé français pour tout-petits ?", a: "Trotro", x: ["Petit Ours brun", "T'choupi", "Caillou"] },
  { id: "enfance-p8", d: 4, t: "Quel petit Canadien chauve, héros d'une série pour enfants, fait souvent des caprices ?", a: "Caillou", x: ["Franklin", "Arthur", "Cédric"] },
  { id: "enfance-p9", d: 4, t: "Quelle tortue, héroïne d'une série pour enfants, apprend la vie de tous les jours ?", a: "Franklin", x: ["Caillou", "Arthur", "Petit Ours brun"] },
  { id: "enfance-p10", d: 4, t: "Quel aardvark à lunettes est le héros d'une série animée éducative américaine ?", a: "Arthur", x: ["Franklin", "Caillou", "Martin Matin"], acc: ["arthur"] },
  { id: "enfance-p11", d: 4, t: "Quelle série animée française suit un garçon qui se transforme chaque matin en héros ou créature ?", a: "Martin Matin", x: ["Code Lyoko", "Titeuf", "Lou"], acc: ["martin matin"] },
  { id: "enfance-p12", d: 4, t: "Quelle série de Disney Channel suit les jumeaux Zack et Cody dans un hôtel ?", a: "La Vie de palace de Zack et Cody", x: ["Hannah Montana", "Les Sorciers de Waverly Place", "Cory à la Maison-Blanche"], acc: ["zack et cody"] },
  { id: "enfance-p13", d: 4, t: "Quelle série Disney suit une famille de sorciers avec l'espiègle Alex Russo ?", a: "Les Sorciers de Waverly Place", x: ["Hannah Montana", "Zack et Cody", "Bonne chance Charlie"], acc: ["sorciers de waverly place"] },
  { id: "enfance-p14", d: 4, t: "Quel dessin animé Disney suit un vieux canard richissime et ses neveux chasseurs de trésors ?", a: "La Bande à Picsou", x: ["Myster Mask", "Super Baloo", "Tic et Tac"], acc: ["bande à picsou", "ducktales"] },
  { id: "enfance-p15", d: 4, t: "Quel justicier masqué est en réalité le canard Albert dans son dessin animé Disney ?", a: "Myster Mask", x: ["Super Baloo", "Picsou", "Donald"], acc: ["myster mask", "darkwing duck"] },
  { id: "enfance-p16", d: 4, t: "Quelle série animée des années 90 suit des mutants dirigés par le professeur Xavier ?", a: "X-Men", x: ["Spider-Man", "Batman", "Les Quatre Fantastiques"], acc: ["x-men"] },
  { id: "enfance-p17", d: 4, t: "Quelle série animée de 1992 est saluée pour son ambiance sombre autour de l'homme chauve-souris ?", a: "Batman, la série animée", x: ["Superman", "X-Men", "Spider-Man"], acc: ["batman la série animée"] },
  { id: "enfance-p18", d: 4, t: "Quelle série animée met en scène des lapins déjantés qui crient « Bwaaah » ?", a: "Les Lapins Crétins", x: ["Grabouillon", "Zig et Sharko", "Foot 2 Rue"], acc: ["lapins crétins", "rabbids"] },
  { id: "enfance-p19", d: 4, t: "Quelle série animée française de sport de rue suit une équipe de foot freestyle ?", a: "Foot 2 Rue", x: ["Galactik Football", "Inazuma Eleven", "Olive et Tom"], acc: ["foot 2 rue"] },
  { id: "enfance-p20", d: 4, t: "Quel dessin animé Disney suit un ours pilote en chemise hawaïenne, inspiré du Livre de la jungle ?", a: "Super Baloo", x: ["La Bande à Picsou", "Myster Mask", "Tic et Tac"], acc: ["super baloo", "talespin"] },
]);
