import { universe } from "../_build";

export const familyguy = universe("series", "Family Guy", [
  // --- Faciles (5) ---
  { id: "familyguy-f1", d: 1, t: "Comment s'appelle le père bêta et bedonnant de la famille Griffin ?", a: "Peter", x: ["Chris", "Brian", "Glenn"], acc: ["peter", "peter griffin"] },
  { id: "familyguy-f2", d: 1, t: "Dans quelle ville fictive vit la famille Griffin ?", a: "Quahog", x: ["Springfield", "Langley Falls", "South Park"], acc: ["quahog"] },
  { id: "familyguy-f3", d: 1, t: "Quel membre de la famille Griffin est un chien qui parle ?", a: "Brian", x: ["Stewie", "Chris", "Peter"], acc: ["brian"] },
  { id: "familyguy-f4", d: 1, t: "Comment s'appelle le bébé surdoué de la famille ?", a: "Stewie", x: ["Chris", "Meg", "Brian"], acc: ["stewie", "stewie griffin"] },
  { id: "familyguy-f5", d: 1, t: "Qui a créé la série Family Guy ?", a: "Seth MacFarlane", x: ["Matt Groening", "Trey Parker", "Mike Judge"], acc: ["seth macfarlane", "macfarlane"] },
  // --- Moyennes (10) ---
  { id: "familyguy-m1", d: 2, t: "Comment s'appelle la femme de Peter Griffin ?", a: "Lois", x: ["Marge", "Meg", "Bonnie"], acc: ["lois", "lois griffin"] },
  { id: "familyguy-m2", d: 2, t: "Comment s'appelle la fille souffre-douleur de la famille ?", a: "Meg", x: ["Lisa", "Bonnie", "Lois"], acc: ["meg", "meg griffin"] },
  { id: "familyguy-m3", d: 2, t: "Comment s'appelle le fils obèse et naïf des Griffin ?", a: "Chris", x: ["Bart", "Stewie", "Kyle"], acc: ["chris", "chris griffin"] },
  { id: "familyguy-m4", d: 2, t: "Sur quelle chaîne américaine Family Guy est-elle diffusée ?", a: "La FOX", x: ["HBO", "NBC", "ABC"], acc: ["fox", "la fox"] },
  { id: "familyguy-m5", d: 2, t: "Quel objectif obsède souvent le bébé Stewie ?", a: "Dominer le monde", x: ["Aller à l'école", "Devenir chanteur", "Ouvrir un restaurant"], acc: ["dominer le monde", "domination du monde", "tuer lois"] },
  { id: "familyguy-m6", d: 2, t: "Quelle réplique lance Quagmire, le voisin dragueur ?", a: "Giggity", x: ["Bazinga", "D'oh", "Cowabunga"], acc: ["giggity"] },
  { id: "familyguy-m7", d: 2, t: "Que boit souvent le chien Brian, très sophistiqué ?", a: "Des martinis", x: ["Du lait", "Des sodas", "Du jus d'orange"], acc: ["martinis", "martini", "des martinis"] },
  { id: "familyguy-m8", d: 2, t: "En quelle année Family Guy a-t-elle été diffusée pour la première fois ?", a: "1999", x: ["1989", "2005", "1995"], acc: ["1999"] },
  { id: "familyguy-m9", d: 2, t: "Quelle phrase la famille répète-t-elle pour rabrouer Meg ?", a: "La ferme, Meg", x: ["Bravo, Meg", "Merci, Meg", "Cours, Meg"], acc: ["la ferme meg", "shut up meg", "ta gueule meg"] },
  { id: "familyguy-m10", d: 2, t: "Dans quel État américain se trouve la ville de Quahog ?", a: "Le Rhode Island", x: ["Le Colorado", "La Virginie", "Le Texas"], acc: ["rhode island", "le rhode island"] },
  // --- Dures (15) ---
  { id: "familyguy-d1", d: 3, t: "Quel est le nom de jeune fille de Lois, issue d'une famille riche ?", a: "Pewterschmidt", x: ["Griffin", "Swanson", "Brown"], acc: ["pewterschmidt"] },
  { id: "familyguy-d2", d: 3, t: "Comment s'appelle le voisin policier paraplégique des Griffin ?", a: "Joe Swanson", x: ["Glenn Quagmire", "Cleveland Brown", "Mort Goldman"], acc: ["joe swanson", "joe", "swanson"] },
  { id: "familyguy-d3", d: 3, t: "Comment s'appelle le voisin noir et posé, ami de Peter ?", a: "Cleveland Brown", x: ["Glenn Quagmire", "Joe Swanson", "Tom Tucker"], acc: ["cleveland", "cleveland brown"] },
  { id: "familyguy-d4", d: 3, t: "Comment s'appelle l'ours en peluche que Stewie ne quitte jamais ?", a: "Rupert", x: ["Teddy", "Nounours", "Winnie"], acc: ["rupert"] },
  { id: "familyguy-d5", d: 3, t: "Où travaille Peter durant une grande partie de la série ?", a: "À la brasserie Pawtucket", x: ["À la centrale nucléaire", "Au commissariat", "À l'hôpital"], acc: ["brasserie pawtucket", "pawtucket", "brasserie"] },
  { id: "familyguy-d6", d: 3, t: "Comment s'appelle le bar où Peter et ses amis se retrouvent ?", a: "The Drunken Clam", x: ["Chez Moe", "Le Duff Bar", "Le Central Perk"], acc: ["drunken clam", "the drunken clam"] },
  { id: "familyguy-d7", d: 3, t: "Quel gigantesque adversaire Peter affronte-t-il dans des bagarres interminables ?", a: "Le poulet géant", x: ["Un ours géant", "Un robot géant", "Un requin géant"], acc: ["poulet geant", "poulet géant", "ernie the giant chicken", "poulet"] },
  { id: "familyguy-d8", d: 3, t: "Quel type de séquences humoristiques Family Guy utilise-t-elle sans cesse ?", a: "Les flash-backs décalés", x: ["Les interviews sérieuses", "Les documentaires", "Les journaux télévisés"], acc: ["flash-backs", "cutaways", "flashbacks decales"] },
  { id: "familyguy-d9", d: 3, t: "Comment s'appelle le père milliardaire de Lois ?", a: "Carter Pewterschmidt", x: ["Carter Griffin", "Mickey McFinnigan", "Tom Tucker"], acc: ["carter", "carter pewterschmidt"] },
  { id: "familyguy-d10", d: 3, t: "Comment s'appelle le présentateur du journal télévisé de Quahog ?", a: "Tom Tucker", x: ["Ollie Williams", "Tricia Takanawa", "Adam West"], acc: ["tom tucker", "tucker"] },
  { id: "familyguy-d11", d: 3, t: "Comment s'appelle le maire excentrique de Quahog, joué par un acteur de Batman ?", a: "Adam West", x: ["Quimby", "Carter", "Bruce Wayne"], acc: ["adam west", "maire adam west"] },
  { id: "familyguy-d12", d: 3, t: "Comment s'appelle le vieux voisin inquiétant qui guette Chris ?", a: "Herbert", x: ["Mort", "Neil", "Bruce"], acc: ["herbert"] },
  { id: "familyguy-d13", d: 3, t: "Quel personnage de Family Guy a eu droit à sa propre série dérivée ?", a: "Cleveland", x: ["Quagmire", "Joe", "Brian"], acc: ["cleveland", "cleveland brown", "the cleveland show"] },
  { id: "familyguy-d14", d: 3, t: "Comment s'appelle la femme de ménage hispanophone qui répète « no no no » ?", a: "Consuela", x: ["Bonnie", "Tricia", "Rosa"], acc: ["consuela"] },
  { id: "familyguy-d15", d: 3, t: "Quel animal imaginaire hante le placard de Chris ?", a: "Le singe maléfique", x: ["Le clown maléfique", "Le monstre vert", "Le fantôme"], acc: ["singe malefique", "singe", "evil monkey"] },
  // --- Pro (20) ---
  { id: "familyguy-p1", d: 4, t: "Quel créateur double lui-même Peter, Brian et Stewie ?", a: "Seth MacFarlane", x: ["Matt Groening", "Seth Rogen", "Mike Judge"], acc: ["seth macfarlane", "macfarlane"] },
  { id: "familyguy-p2", d: 4, t: "Quelle actrice double Meg depuis la saison 2 ?", a: "Mila Kunis", x: ["Lacey Chabert", "Julie Kavner", "Nancy Cartwright"], acc: ["mila kunis", "kunis"] },
  { id: "familyguy-p3", d: 4, t: "Quelle actrice doublait Meg lors de la première saison ?", a: "Lacey Chabert", x: ["Mila Kunis", "Alex Borstein", "Yeardley Smith"], acc: ["lacey chabert", "chabert"] },
  { id: "familyguy-p4", d: 4, t: "Quelle actrice prête sa voix à Lois en version originale ?", a: "Alex Borstein", x: ["Mila Kunis", "Lacey Chabert", "Julie Kavner"], acc: ["alex borstein", "borstein"] },
  { id: "familyguy-p5", d: 4, t: "Comment s'appelle la rue où habite la famille Griffin ?", a: "Spooner Street", x: ["Evergreen Terrace", "Spooner Avenue", "Quahog Lane"], acc: ["spooner street", "spooner"] },
  { id: "familyguy-p6", d: 4, t: "Comment s'appelle le monsieur météo qui hurle ses prévisions en une phrase ?", a: "Ollie Williams", x: ["Tom Tucker", "Tricia Takanawa", "Adam West"], acc: ["ollie williams", "ollie"] },
  { id: "familyguy-p7", d: 4, t: "Quelle bière est produite par la brasserie où travaille Peter ?", a: "La Pawtucket Patriot Ale", x: ["La Duff", "La Pabst", "La Buzz"], acc: ["pawtucket patriot", "pawtucket patriot ale", "pawtucket"] },
  { id: "familyguy-p8", d: 4, t: "Quelle voiture écolo le chien Brian conduit-il dans la série ?", a: "Une Prius", x: ["Une Ferrari", "Une Jeep", "Un pick-up"], acc: ["prius", "une prius"] },
  { id: "familyguy-p9", d: 4, t: "Quel métier exerce Brian, en plus d'être le chien de la famille ?", a: "Écrivain", x: ["Médecin", "Pompier", "Cuisinier"], acc: ["ecrivain", "écrivain", "auteur"] },
  { id: "familyguy-p10", d: 4, t: "Comment s'appelle le voisin pharmacien nerveux, père de l'amoureux de Meg ?", a: "Mort Goldman", x: ["Herbert", "Carter", "Bruce"], acc: ["mort goldman", "mort"] },
  { id: "familyguy-p11", d: 4, t: "Comment s'appelle le fils de Mort, amoureux transi de Meg ?", a: "Neil Goldman", x: ["Kevin Swanson", "Chris Griffin", "Bruce"], acc: ["neil goldman", "neil"] },
  { id: "familyguy-p12", d: 4, t: "Comment s'appelle la petite fille de Joe et Bonnie Swanson ?", a: "Susie", x: ["Meg", "Consuela", "Tricia"], acc: ["susie", "susie swanson"] },
  { id: "familyguy-p13", d: 4, t: "Comment s'appelle le fils de Joe Swanson, décédé dans la série ?", a: "Kevin", x: ["Neil", "Bruce", "Chris"], acc: ["kevin", "kevin swanson"] },
  { id: "familyguy-p14", d: 4, t: "Quel chien a brièvement remplacé Brian après sa mort dans la série ?", a: "Vinny", x: ["Rupert", "Bruce", "Jasper"], acc: ["vinny"] },
  { id: "familyguy-p15", d: 4, t: "Grâce à quoi la série a-t-elle été relancée après son annulation au début des années 2000 ?", a: "Les ventes de DVD et les rediffusions", x: ["Un concours", "Une pétition du maire", "Un film"], acc: ["ventes de dvd", "dvd", "rediffusions"] },
  { id: "familyguy-p16", d: 4, t: "Quel accent le bébé Stewie a-t-il en version originale ?", a: "Un accent britannique", x: ["Un accent texan", "Un accent australien", "Un accent français"], acc: ["britannique", "accent britannique", "anglais"] },
  { id: "familyguy-p17", d: 4, t: "Quelle forme particulière a la tête de Stewie ?", a: "Une forme de ballon de rugby", x: ["Une forme carrée", "Une forme ronde", "Une forme d'étoile"], acc: ["ballon de rugby", "ballon de football americain", "ovale"] },
  { id: "familyguy-p18", d: 4, t: "Quel gag récurrent montre Peter se tenant le genou en sifflant de douleur ?", a: "Le coup au tibia", x: ["Le coup de poulet", "La chute d'escalier", "Le coup de porte"], acc: ["coup au tibia", "genou", "tibia"] },
  { id: "familyguy-p19", d: 4, t: "Comment s'appelle la journaliste asiatique de la chaîne de Quahog ?", a: "Tricia Takanawa", x: ["Diane Simmons", "Ollie Williams", "Consuela"], acc: ["tricia takanawa", "takanawa"] },
  { id: "familyguy-p20", d: 4, t: "Comment s'appelle la coprésentatrice du journal, tuée dans un épisode ?", a: "Diane Simmons", x: ["Tricia Takanawa", "Bonnie Swanson", "Lois Griffin"], acc: ["diane simmons", "diane"] },
]);
