import { universe } from "../_build";

export const futurama = universe("series", "Futurama", [
  // --- Faciles (5) ---
  { id: "futurama-f1", d: 1, t: "Comment s'appelle le livreur cryogénisé, héros de Futurama ?", a: "Fry", x: ["Bender", "Zoidberg", "Hermes"], acc: ["fry", "philip fry"] },
  { id: "futurama-f2", d: 1, t: "Quel personnage de Futurama est un robot cynique amateur de bière ?", a: "Bender", x: ["Fry", "Zapp", "Nibbler"], acc: ["bender"] },
  { id: "futurama-f3", d: 1, t: "Qui a créé Futurama, également créateur des Simpson ?", a: "Matt Groening", x: ["Seth MacFarlane", "David X. Cohen", "Trey Parker"], acc: ["matt groening", "groening"] },
  { id: "futurama-f4", d: 1, t: "Combien d'yeux possède la capitaine Leela ?", a: "Un seul", x: ["Deux", "Trois", "Quatre"], acc: ["un", "un seul", "1"] },
  { id: "futurama-f5", d: 1, t: "En quelle année Fry se réveille-t-il après avoir été congelé ?", a: "L'an 3000", x: ["L'an 2000", "L'an 2500", "L'an 5000"], acc: ["3000", "an 3000", "l'an 3000"] },
  // --- Moyennes (10) ---
  { id: "futurama-m1", d: 2, t: "Comment s'appelle l'entreprise de livraison où travaillent les héros ?", a: "Planet Express", x: ["MomCorp", "Panucci's Pizza", "DOOP"], acc: ["planet express"] },
  { id: "futurama-m2", d: 2, t: "Comment s'appelle la capitaine borgne du vaisseau ?", a: "Leela", x: ["Amy", "Mom", "LaBarbara"], acc: ["leela", "turanga leela"] },
  { id: "futurama-m3", d: 2, t: "Comment s'appelle le vieux professeur savant qui dirige Planet Express ?", a: "Professeur Farnsworth", x: ["Professeur Zoidberg", "Professeur Wernstrom", "Professeur Frink"], acc: ["farnsworth", "professeur farnsworth", "hubert farnsworth"] },
  { id: "futurama-m4", d: 2, t: "Comment s'appelle le médecin extraterrestre en forme de homard ?", a: "Zoidberg", x: ["Kif", "Nibbler", "Zapp"], acc: ["zoidberg", "docteur zoidberg"] },
  { id: "futurama-m5", d: 2, t: "Quelle est la réplique culte de Bender pour envoyer balader les gens ?", a: "Mords mon métal luisant", x: ["Mange mes shorts", "D'oh", "Giggity"], acc: ["mords mon metal", "bite my shiny metal ass", "metal luisant"] },
  { id: "futurama-m6", d: 2, t: "Quelle phrase le professeur Farnsworth lance-t-il en entrant ?", a: "Bonne nouvelle tout le monde", x: ["La ferme", "Cowabunga", "Excellent"], acc: ["bonne nouvelle tout le monde", "good news everyone", "bonne nouvelle"] },
  { id: "futurama-m7", d: 2, t: "Quel métier Fry exerçait-il en l'an 2000 avant d'être congelé ?", a: "Livreur de pizzas", x: ["Astronaute", "Cuisinier", "Robot"], acc: ["livreur de pizzas", "livreur", "pizza"] },
  { id: "futurama-m8", d: 2, t: "Comment s'appelle la stagiaire riche et maladroite, originaire de Mars ?", a: "Amy", x: ["Leela", "Mom", "LaBarbara"], acc: ["amy", "amy wong"] },
  { id: "futurama-m9", d: 2, t: "Comment s'appelle le comptable jamaïcain et bureaucrate de Planet Express ?", a: "Hermes", x: ["Zoidberg", "Scruffy", "Kif"], acc: ["hermes", "hermes conrad"] },
  { id: "futurama-m10", d: 2, t: "Comment s'appelle la version futuriste de New York dans la série ?", a: "New New York", x: ["Neo Tokyo", "Mega City", "Springfield"], acc: ["new new york"] },
  // --- Dures (15) ---
  { id: "futurama-d1", d: 3, t: "Quel lien de parenté lointain unit Fry au professeur Farnsworth ?", a: "Farnsworth est son neveu lointain", x: ["C'est son frère", "C'est son père", "Aucun lien"], acc: ["neveu", "son neveu", "neveu lointain"] },
  { id: "futurama-d2", d: 3, t: "De quelle organisation spatiale Zapp Brannigan est-il le capitaine imbu de lui-même ?", a: "La DOOP", x: ["La NASA", "MomCorp", "Planet Express"], acc: ["doop", "la doop"] },
  { id: "futurama-d3", d: 3, t: "Comment s'appelle l'assistant amphibien et souffre-douleur de Zapp Brannigan ?", a: "Kif", x: ["Nibbler", "Zoidberg", "Hermes"], acc: ["kif", "kif kroker"] },
  { id: "futurama-d4", d: 3, t: "Comment s'appelle le petit animal de compagnie noir et mignon de Leela ?", a: "Nibbler", x: ["Seymour", "Snowball", "Rupert"], acc: ["nibbler"] },
  { id: "futurama-d5", d: 3, t: "Quelle tête d'ancien président des États-Unis dirige la Terre en bocal ?", a: "Richard Nixon", x: ["Abraham Lincoln", "John Kennedy", "George Washington"], acc: ["nixon", "richard nixon"] },
  { id: "futurama-d6", d: 3, t: "Comment s'appelle la méchante patronne de MomCorp, sous des airs gentils ?", a: "Mom", x: ["Leela", "Amy", "Munda"], acc: ["mom", "maman"] },
  { id: "futurama-d7", d: 3, t: "Sur quelle chaîne Futurama a-t-elle été diffusée à ses débuts en 1999 ?", a: "La FOX", x: ["HBO", "Comedy Central", "Netflix"], acc: ["fox", "la fox"] },
  { id: "futurama-d8", d: 3, t: "Quel amour Fry poursuit-il tout au long de la série ?", a: "Leela", x: ["Amy", "Mom", "LaBarbara"], acc: ["leela"] },
  { id: "futurama-d9", d: 3, t: "Comment s'appelle le crapaud hypnotique culte de la série ?", a: "L'Hypnocrapaud", x: ["Le Slurm", "Nibbler", "Calculon"], acc: ["hypnocrapaud", "hypnotoad"] },
  { id: "futurama-d10", d: 3, t: "Quelle boisson verte très addictive est une marque phare du futur ?", a: "Le Slurm", x: ["La Duff", "Le Brawndo", "Le Buzz Cola"], acc: ["slurm", "le slurm"] },
  { id: "futurama-d11", d: 3, t: "Dans quel pays le robot Bender a-t-il été fabriqué ?", a: "Au Mexique", x: ["Au Japon", "En Chine", "Aux États-Unis"], acc: ["mexique", "au mexique", "tijuana"] },
  { id: "futurama-d12", d: 3, t: "Comment s'appelle le concierge nonchalant de Planet Express ?", a: "Scruffy", x: ["Hermes", "Zoidberg", "URL"], acc: ["scruffy"] },
  { id: "futurama-d13", d: 3, t: "Comment s'appelle l'acteur robot vaniteux, star de la télé du futur ?", a: "Calculon", x: ["Bender", "Roberto", "Flexo"], acc: ["calculon"] },
  { id: "futurama-d14", d: 3, t: "Comment s'appelle le robot qui ressemble à Bender mais porte une barbiche ?", a: "Flexo", x: ["Calculon", "URL", "Roberto"], acc: ["flexo"] },
  { id: "futurama-d15", d: 3, t: "Quel est le nom complet du robot Bender ?", a: "Bender Bending Rodríguez", x: ["Bender Metal Smith", "Bender Robot Jones", "Bender Iron Cortez"], acc: ["bender bending rodriguez", "bending rodriguez"] },
  // --- Pro (20) ---
  { id: "futurama-p1", d: 4, t: "Qui a co-développé Futurama aux côtés de Matt Groening ?", a: "David X. Cohen", x: ["Seth MacFarlane", "Al Jean", "James L. Brooks"], acc: ["david x cohen", "cohen", "david cohen"] },
  { id: "futurama-p2", d: 4, t: "Quel acteur double Fry et le professeur Farnsworth en version originale ?", a: "Billy West", x: ["John DiMaggio", "Katey Sagal", "Phil LaMarr"], acc: ["billy west", "west"] },
  { id: "futurama-p3", d: 4, t: "Quel acteur prête sa voix au robot Bender ?", a: "John DiMaggio", x: ["Billy West", "Phil LaMarr", "Maurice LaMarche"], acc: ["john dimaggio", "dimaggio"] },
  { id: "futurama-p4", d: 4, t: "Quelle actrice double la capitaine Leela ?", a: "Katey Sagal", x: ["Tress MacNeille", "Nancy Cartwright", "Mila Kunis"], acc: ["katey sagal", "sagal"] },
  { id: "futurama-p5", d: 4, t: "Comment s'appelle le peuple dont fait partie Nibbler, protecteur de l'univers ?", a: "Les Nibbloniens", x: ["Les Martiens", "Les Décapodiens", "Les Amphibiens"], acc: ["nibbloniens", "nibblonians"] },
  { id: "futurama-p6", d: 4, t: "De quelle planète est originaire le docteur Zoidberg ?", a: "Décapod 10", x: ["Mars", "Oméga 3", "Neptune"], acc: ["decapod 10", "decapod", "décapod 10"] },
  { id: "futurama-p7", d: 4, t: "Comment s'appelle la pizzeria où travaillait Fry en l'an 2000 ?", a: "Panucci's Pizza", x: ["Luigi's", "Pizza Planet", "Krusty Pizza"], acc: ["panucci's pizza", "panucci", "panucci's"] },
  { id: "futurama-p8", d: 4, t: "Comment s'appelle le chien fidèle que Fry a laissé en l'an 2000 ?", a: "Seymour", x: ["Nibbler", "Rex", "Petit Papa Noël"], acc: ["seymour"] },
  { id: "futurama-p9", d: 4, t: "Comment s'appelle la femme d'Hermes Conrad ?", a: "LaBarbara", x: ["Munda", "Amy", "Mom"], acc: ["labarbara"] },
  { id: "futurama-p10", d: 4, t: "Comment s'appelle le clone du professeur Farnsworth, son fils artificiel ?", a: "Cubert", x: ["Dwight", "Igner", "Walt"], acc: ["cubert"] },
  { id: "futurama-p11", d: 4, t: "Quel diable rusé passe des marchés en échange d'âmes ?", a: "Le Robot Diable", x: ["Calculon", "Roberto", "Mom"], acc: ["robot diable", "robot devil"] },
  { id: "futurama-p12", d: 4, t: "Comment s'appelle le petit-ami amphibien d'Amy Wong ?", a: "Kif", x: ["Zapp", "Zoidberg", "Hermes"], acc: ["kif", "kif kroker"] },
  { id: "futurama-p13", d: 4, t: "Quelle particularité cérébrale rend Fry immunisé contre les cerveaux volants ?", a: "L'absence d'onde delta", x: ["Un cerveau géant", "Deux cerveaux", "Un cerveau en métal"], acc: ["absence d'onde delta", "onde delta", "delta brainwave"] },
  { id: "futurama-p14", d: 4, t: "Après son annulation, sur quelle chaîne Futurama a-t-elle été relancée en 2008 ?", a: "Comedy Central", x: ["La FOX", "HBO", "Netflix"], acc: ["comedy central"] },
  { id: "futurama-p15", d: 4, t: "Sur quelle plateforme Futurama a-t-elle été de nouveau relancée en 2023 ?", a: "Hulu", x: ["Netflix", "Disney+", "Amazon Prime"], acc: ["hulu"] },
  { id: "futurama-p16", d: 4, t: "Comment s'appellent les deux robots policiers costauds de New New York ?", a: "URL et Smitty", x: ["Fender et Flexo", "Roberto et Calculon", "Kang et Kodos"], acc: ["url et smitty", "url", "smitty"] },
  { id: "futurama-p17", d: 4, t: "Quelle phrase accompagne le crapaud hypnotique dans la série ?", a: "Gloire à l'Hypnocrapaud", x: ["Vive Bender", "La ferme Meg", "Bonne nouvelle"], acc: ["gloire a l'hypnocrapaud", "all glory to the hypnotoad"] },
  { id: "futurama-p18", d: 4, t: "Comment s'appellent les parents mutants de Leela, vivant dans les égouts ?", a: "Morris et Munda", x: ["Carter et Barbara", "Hubert et Mom", "Zapp et Kif"], acc: ["morris et munda", "morris", "munda"] },
  { id: "futurama-p19", d: 4, t: "Quel robot fou et violent, au ton menaçant, apparaît régulièrement ?", a: "Roberto", x: ["Calculon", "Flexo", "URL"], acc: ["roberto"] },
  { id: "futurama-p20", d: 4, t: "Quelle phrase d'accueil ouvre le générique de Futurama ?", a: "Bienvenue dans le monde de demain", x: ["Bonne nouvelle", "Vive le futur", "En avant l'an 3000"], acc: ["bienvenue dans le monde de demain", "welcome to the world of tomorrow"] },
]);
