import { universe } from "../_build";

export const lupin = universe("series", "Lupin", [
  // --- Faciles (5) ---
  { id: "lupin-f1", d: 1, t: "Sur quelle plateforme la série Lupin est-elle diffusée ?", a: "Netflix", x: ["Disney+", "Amazon Prime", "Canal+"], acc: ["netflix"] },
  { id: "lupin-f2", d: 1, t: "Quel acteur français incarne le héros de Lupin ?", a: "Omar Sy", x: ["Jean Dujardin", "Vincent Cassel", "Tahar Rahim"], acc: ["omar sy", "omar"] },
  { id: "lupin-f3", d: 1, t: "Comment s'appelle le héros de la série Lupin ?", a: "Assane Diop", x: ["Arsène Lupin", "Hubert Pellegrini", "Youssef Guedira"], acc: ["assane", "assane diop"] },
  { id: "lupin-f4", d: 1, t: "Quel « métier » hors-la-loi Assane exerce-t-il avec élégance ?", a: "Voleur", x: ["Policier", "Avocat", "Médecin"], acc: ["voleur", "cambrioleur", "gentleman cambrioleur"] },
  { id: "lupin-f5", d: 1, t: "Dans quelle ville se déroule principalement Lupin ?", a: "Paris", x: ["Marseille", "Lyon", "Bordeaux"], acc: ["paris"] },
  // --- Moyennes (10) ---
  { id: "lupin-m1", d: 2, t: "De quel personnage littéraire Assane s'inspire-t-il ?", a: "Arsène Lupin", x: ["Sherlock Holmes", "Fantômas", "Rocambole"], acc: ["arsene lupin", "lupin", "arsène lupin"] },
  { id: "lupin-m2", d: 2, t: "Quel écrivain a créé le personnage d'Arsène Lupin ?", a: "Maurice Leblanc", x: ["Georges Simenon", "Gaston Leroux", "Victor Hugo"], acc: ["maurice leblanc", "leblanc"] },
  { id: "lupin-m3", d: 2, t: "Quel objet, offert par son père, guide Assane ?", a: "Un livre d'Arsène Lupin", x: ["Un journal intime", "Une carte au trésor", "Un manuel de magie"], acc: ["livre d'arsene lupin", "livre", "les aventures d'arsene lupin"] },
  { id: "lupin-m4", d: 2, t: "Quelle est la grande motivation d'Assane tout au long de la série ?", a: "Venger son père", x: ["Devenir riche", "Fuir la police", "Retrouver la mémoire"], acc: ["venger son pere", "vengeance"] },
  { id: "lupin-m5", d: 2, t: "Dans quel célèbre musée a lieu le casse du premier épisode ?", a: "Le Louvre", x: ["Le musée d'Orsay", "Le Grand Palais", "Le château de Versailles"], acc: ["louvre", "le louvre"] },
  { id: "lupin-m6", d: 2, t: "En quelle année la première partie de Lupin est-elle sortie ?", a: "2021", x: ["2016", "2019", "2023"], acc: ["2021"] },
  { id: "lupin-m7", d: 2, t: "Quel bijou précieux est au cœur de l'intrigue du premier épisode ?", a: "Le collier de la Reine", x: ["La couronne d'Angleterre", "Le diamant Hope", "La bague du pape"], acc: ["collier de la reine", "collier", "le collier"] },
  { id: "lupin-m8", d: 2, t: "Quel talent Assane utilise-t-il pour ne jamais être reconnu ?", a: "Le déguisement", x: ["L'invisibilité", "Le piratage", "L'hypnose"], acc: ["deguisement", "le deguisement", "se deguiser"] },
  { id: "lupin-m9", d: 2, t: "Comment s'appelle le riche homme d'affaires, grand ennemi d'Assane ?", a: "Hubert Pellegrini", x: ["Youssef Guedira", "Benjamin Ferel", "Babakar Diop"], acc: ["pellegrini", "hubert pellegrini"] },
  { id: "lupin-m10", d: 2, t: "De quelle origine est la famille d'Assane, arrivée en France ?", a: "Sénégalaise", x: ["Marocaine", "Italienne", "Portugaise"], acc: ["senegalaise", "senegal", "sénégal"] },
  // --- Dures (15) ---
  { id: "lupin-d1", d: 3, t: "Comment s'appelle le père d'Assane, accusé à tort d'un vol ?", a: "Babakar Diop", x: ["Hubert Pellegrini", "Youssef Guedira", "Léonard"], acc: ["babakar", "babakar diop"] },
  { id: "lupin-d2", d: 3, t: "De quel vol le père d'Assane est-il injustement accusé ?", a: "Du vol du collier de la Reine", x: ["D'un braquage de banque", "D'un vol de voiture", "D'un vol de tableau"], acc: ["collier de la reine", "vol du collier", "collier"] },
  { id: "lupin-d3", d: 3, t: "Quel métier le père d'Assane exerçait-il chez les Pellegrini ?", a: "Chauffeur", x: ["Jardinier", "Cuisinier", "Majordome"], acc: ["chauffeur"] },
  { id: "lupin-d4", d: 3, t: "Comment s'appelle le policier fan d'Arsène Lupin qui traque Assane ?", a: "Youssef Guedira", x: ["Hubert Pellegrini", "Benjamin Ferel", "Léonard"], acc: ["guedira", "youssef guedira", "youssef"] },
  { id: "lupin-d5", d: 3, t: "Comment s'appelle le fils d'Assane ?", a: "Raoul", x: ["Babakar", "Benjamin", "Léo"], acc: ["raoul"] },
  { id: "lupin-d6", d: 3, t: "Comment s'appelle l'ex-compagne d'Assane, mère de son fils ?", a: "Claire", x: ["Juliette", "Fleur", "Manon"], acc: ["claire"] },
  { id: "lupin-d7", d: 3, t: "Comment s'appelle la fille d'Hubert Pellegrini, proche d'Assane ?", a: "Juliette", x: ["Claire", "Manon", "Fleur"], acc: ["juliette", "juliette pellegrini"] },
  { id: "lupin-d8", d: 3, t: "Comment s'appelle le meilleur ami d'Assane, antiquaire, qui l'aide dans ses coups ?", a: "Benjamin Ferel", x: ["Youssef Guedira", "Hubert Pellegrini", "Babakar"], acc: ["benjamin", "benjamin ferel", "ferel"] },
  { id: "lupin-d9", d: 3, t: "Quel duo de créateurs est à l'origine de la série Lupin ?", a: "George Kay et François Uzan", x: ["Les frères Dardenne", "Toledano et Nakache", "Jean-Xavier de Lestrade"], acc: ["george kay et francois uzan", "george kay", "francois uzan"] },
  { id: "lupin-d10", d: 3, t: "Dans quel autre grand film Omar Sy s'est-il fait connaître mondialement ?", a: "Intouchables", x: ["Le Dîner de cons", "La Haine", "Amélie Poulain"], acc: ["intouchables", "les intouchables"] },
  { id: "lupin-d11", d: 3, t: "Comment le père d'Assane meurt-il en prison, selon la version officielle ?", a: "Il se suicide", x: ["Il est libéré", "Il s'évade", "Il tombe malade"], acc: ["suicide", "il se suicide", "suicidé"] },
  { id: "lupin-d12", d: 3, t: "Quelle ville normande, liée à la légende de Lupin, apparaît dans la série ?", a: "Étretat", x: ["Deauville", "Honfleur", "Le Havre"], acc: ["etretat", "étretat"] },
  { id: "lupin-d13", d: 3, t: "Comment appelle-t-on le type d'intrigue de Lupin, centré sur des vols élaborés ?", a: "Le film de casse", x: ["Le western", "La comédie musicale", "Le film catastrophe"], acc: ["film de casse", "casse", "heist"] },
  { id: "lupin-d14", d: 3, t: "Comment surnomme-t-on Arsène Lupin, le modèle d'Assane ?", a: "Le gentleman cambrioleur", x: ["Le justicier masqué", "Le roi des détectives", "Le fantôme de l'Opéra"], acc: ["gentleman cambrioleur", "le gentleman cambrioleur"] },
  { id: "lupin-d15", d: 3, t: "Quelle qualité, plus que la force, fait la réussite des coups d'Assane ?", a: "La ruse", x: ["La violence", "La chance pure", "La magie"], acc: ["ruse", "la ruse", "l'intelligence"] },
  // --- Pro (20) ---
  { id: "lupin-p1", d: 4, t: "En quel mois la première partie de Lupin est-elle sortie en 2021 ?", a: "En janvier", x: ["En juillet", "En octobre", "En décembre"], acc: ["janvier", "en janvier"] },
  { id: "lupin-p2", d: 4, t: "Combien de parties de Lupin sont sorties dès 2021 ?", a: "Deux", x: ["Une", "Cinq", "Dix"], acc: ["deux", "2", "deux parties"] },
  { id: "lupin-p3", d: 4, t: "En quelle année la partie 3 de Lupin est-elle sortie ?", a: "2023", x: ["2021", "2022", "2024"], acc: ["2023"] },
  { id: "lupin-p4", d: 4, t: "Quel exploit rare Lupin a-t-il réalisé pour une production française sur Netflix ?", a: "Un succès mondial", x: ["Un échec critique", "Une diffusion limitée à la France", "Une annulation immédiate"], acc: ["succes mondial", "succes international", "carton mondial"] },
  { id: "lupin-p5", d: 4, t: "Quelle nouvelle de Maurice Leblanc, sur ce bijou, inspire l'intrigue de départ ?", a: "Le Collier de la Reine", x: ["L'Aiguille creuse", "813", "Le Bouchon de cristal"], acc: ["collier de la reine", "le collier de la reine"] },
  { id: "lupin-p6", d: 4, t: "Comment s'appelle le fidèle homme de main d'Hubert Pellegrini ?", a: "Léonard", x: ["Benjamin", "Youssef", "Babakar"], acc: ["leonard", "léonard"] },
  { id: "lupin-p7", d: 4, t: "Comment s'appelle la commissaire, supérieure de Guedira, d'abord sceptique ?", a: "Belkacem", x: ["Claire", "Juliette", "Sofia"], acc: ["belkacem", "sofia belkacem"] },
  { id: "lupin-p8", d: 4, t: "Quel roman de Leblanc, lié à Étretat, évoque une aiguille secrète ?", a: "L'Aiguille creuse", x: ["Le Collier de la Reine", "Le Triangle d'or", "La Comtesse de Cagliostro"], acc: ["aiguille creuse", "l'aiguille creuse"] },
  { id: "lupin-p9", d: 4, t: "Sous quelle fausse identité Assane s'infiltre-t-il au Louvre au tout début ?", a: "Un agent d'entretien", x: ["Un conservateur", "Un policier", "Un touriste"], acc: ["agent d'entretien", "femme de menage", "nettoyeur"] },
  { id: "lupin-p10", d: 4, t: "De quel pays d'Afrique de l'Ouest la famille Diop est-elle originaire ?", a: "Le Sénégal", x: ["Le Mali", "La Côte d'Ivoire", "Le Cameroun"], acc: ["senegal", "le senegal", "sénégal"] },
  { id: "lupin-p11", d: 4, t: "Quelle reine de France est historiquement associée au fameux collier ?", a: "Marie-Antoinette", x: ["Joséphine de Beauharnais", "Catherine de Médicis", "Madame de Pompadour"], acc: ["marie-antoinette", "marie antoinette"] },
  { id: "lupin-p12", d: 4, t: "Quelle profession de couverture Benjamin, complice d'Assane, exerce-t-il ?", a: "Antiquaire", x: ["Avocat", "Serrurier", "Journaliste"], acc: ["antiquaire"] },
  { id: "lupin-p13", d: 4, t: "Quel visage d'Assane, en plus du voleur, le rend attachant pour le public ?", a: "Celui d'un bon père", x: ["Celui d'un tueur", "Celui d'un escroc sans cœur", "Celui d'un lâche"], acc: ["bon pere", "un bon pere", "pere aimant"] },
  { id: "lupin-p14", d: 4, t: "Combien d'épisodes compte environ chaque partie de Lupin ?", a: "Cinq", x: ["Un", "Douze", "Vingt"], acc: ["cinq", "5"] },
  { id: "lupin-p15", d: 4, t: "Dans quelle partie de la série l'action se déplace-t-elle notamment à Étretat ?", a: "La partie 2", x: ["La partie 1", "La partie 4", "La partie 5"], acc: ["partie 2", "la partie 2", "part 2"] },
  { id: "lupin-p16", d: 4, t: "Quel acteur de la Comédie-Française incarne le méchant Hubert Pellegrini ?", a: "Hervé Pierre", x: ["Vincent Cassel", "Gilles Lellouche", "Benoît Magimel"], acc: ["herve pierre", "hervé pierre"] },
  { id: "lupin-p17", d: 4, t: "Quelle grande force de l'ordre est mobilisée pour arrêter le mystérieux voleur ?", a: "La police parisienne", x: ["Le FBI", "Interpol seul", "La gendarmerie rurale"], acc: ["police parisienne", "police de paris", "police"] },
  { id: "lupin-p18", d: 4, t: "À quelle période de la vie d'Assane remonte l'injustice subie par son père ?", a: "Son enfance", x: ["La semaine passée", "Le Moyen Âge", "La guerre"], acc: ["enfance", "son enfance", "quand il etait enfant"] },
  { id: "lupin-p19", d: 4, t: "Quel accessoire discret Assane change-t-il souvent pour brouiller les pistes ?", a: "Ses lunettes et ses tenues", x: ["Un masque de cire", "Un hologramme", "Un costume high-tech"], acc: ["lunettes", "deguisements", "tenues"] },
  { id: "lupin-p20", d: 4, t: "Quelle qualité de gentleman Assane conserve-t-il, à la manière d'Arsène Lupin ?", a: "L'élégance", x: ["La brutalité", "La vulgarité", "La paresse"], acc: ["elegance", "l'elegance", "le raffinement"] },
]);
