import { universe } from "../_build";

export const mercredi = universe("series", "Mercredi", [
  // --- Faciles (5) ---
  { id: "mercredi-f1", d: 1, t: "Sur quelle plateforme la série Mercredi est-elle diffusée ?", a: "Netflix", x: ["Disney+", "Amazon Prime", "HBO"], acc: ["netflix"] },
  { id: "mercredi-f2", d: 1, t: "De quelle famille macabre Mercredi est-elle la fille ?", a: "La famille Addams", x: ["La famille Munster", "La famille Simpson", "La famille Griffin"], acc: ["famille addams", "addams", "les addams"] },
  { id: "mercredi-f3", d: 1, t: "Quelle actrice incarne Mercredi Addams ?", a: "Jenna Ortega", x: ["Millie Bobby Brown", "Maddie Ziegler", "Kiernan Shipka"], acc: ["jenna ortega", "ortega"] },
  { id: "mercredi-f4", d: 1, t: "Quel réalisateur au style gothique est derrière la série ?", a: "Tim Burton", x: ["Steven Spielberg", "Guillermo del Toro", "Wes Anderson"], acc: ["tim burton", "burton"] },
  { id: "mercredi-f5", d: 1, t: "Quel trait de caractère définit le mieux Mercredi ?", a: "Elle est sombre et sarcastique", x: ["Elle est joyeuse et bavarde", "Elle est timide et rougissante", "Elle est peureuse"], acc: ["sombre et sarcastique", "sombre", "sarcastique"] },
  // --- Moyennes (10) ---
  { id: "mercredi-m1", d: 2, t: "Comment s'appelle l'académie pour marginaux où étudie Mercredi ?", a: "Nevermore", x: ["Poudlard", "Xavier's School", "Beauxbâtons"], acc: ["nevermore", "academie nevermore"] },
  { id: "mercredi-m2", d: 2, t: "Comment s'appelle la main vivante qui accompagne Mercredi ?", a: "La Chose", x: ["Igor", "Le Doigt", "Patte"], acc: ["la chose", "chose", "thing"] },
  { id: "mercredi-m3", d: 2, t: "De quel instrument de musique Mercredi joue-t-elle ?", a: "Le violoncelle", x: ["Le piano", "La guitare", "Le violon"], acc: ["violoncelle", "le violoncelle", "cello"] },
  { id: "mercredi-m4", d: 2, t: "Comment s'appelle la mère de Mercredi ?", a: "Morticia", x: ["Enid", "Larissa", "Bianca"], acc: ["morticia"] },
  { id: "mercredi-m5", d: 2, t: "Comment s'appelle le père de Mercredi ?", a: "Gomez", x: ["Fétide", "Pugsley", "Xavier"], acc: ["gomez", "gomez addams"] },
  { id: "mercredi-m6", d: 2, t: "Comment s'appelle la colocataire colorée et pétillante de Mercredi ?", a: "Enid", x: ["Bianca", "Yoko", "Divina"], acc: ["enid", "enid sinclair"] },
  { id: "mercredi-m7", d: 2, t: "Quelle scène de danse de Mercredi est devenue virale sur les réseaux ?", a: "Sa danse au bal", x: ["Sa danse sous la pluie", "Sa danse en boîte", "Sa danse de fin"], acc: ["danse au bal", "danse", "danse du bal"] },
  { id: "mercredi-m8", d: 2, t: "Quel don surnaturel Mercredi possède-t-elle ?", a: "Des visions", x: ["La téléportation", "La super-force", "L'invisibilité"], acc: ["visions", "des visions", "voyance"] },
  { id: "mercredi-m9", d: 2, t: "En quelle année la première saison de Mercredi est-elle sortie ?", a: "2022", x: ["2018", "2020", "2024"], acc: ["2022"] },
  { id: "mercredi-m10", d: 2, t: "Quelle créature Enid, la colocataire de Mercredi, est-elle en secret ?", a: "Une louve-garou", x: ["Une vampire", "Une sirène", "Une sorcière"], acc: ["louve-garou", "loup-garou", "louve garou"] },
  // --- Dures (15) ---
  { id: "mercredi-d1", d: 3, t: "Comment s'appelle le petit frère de Mercredi ?", a: "Pugsley", x: ["Fétide", "Ajax", "Xavier"], acc: ["pugsley"] },
  { id: "mercredi-d2", d: 3, t: "Comment s'appelle l'oncle chauve et électrique de Mercredi ?", a: "Oncle Fétide", x: ["Oncle Gomez", "Oncle Xavier", "Oncle Tyler"], acc: ["oncle fetide", "fetide", "fester", "fétide"] },
  { id: "mercredi-d3", d: 3, t: "Dans quelle petite ville se situe l'académie Nevermore ?", a: "Jericho", x: ["Hawkins", "Sleepy Hollow", "Riverdale"], acc: ["jericho"] },
  { id: "mercredi-d4", d: 3, t: "Comment s'appelle le fils du shérif, dont Mercredi se rapproche ?", a: "Tyler", x: ["Xavier", "Ajax", "Lucas"], acc: ["tyler", "tyler galpin"] },
  { id: "mercredi-d5", d: 3, t: "Comment s'appelle l'élève artiste de Nevermore, autre prétendant de Mercredi ?", a: "Xavier", x: ["Tyler", "Ajax", "Lucas"], acc: ["xavier", "xavier thorpe"] },
  { id: "mercredi-d6", d: 3, t: "Quel monstre terrorise la région autour de Nevermore dans la saison 1 ?", a: "Le Hyde", x: ["Le Loup", "Le Kraken", "Le Wendigo"], acc: ["hyde", "le hyde"] },
  { id: "mercredi-d7", d: 3, t: "Comment s'appelle la directrice de Nevermore dans la saison 1 ?", a: "Larissa Weems", x: ["Marilyn Thornhill", "Morticia Addams", "Bianca Barclay"], acc: ["weems", "larissa weems"] },
  { id: "mercredi-d8", d: 3, t: "À quelle œuvre d'Edgar Allan Poe le nom « Nevermore » fait-il référence ?", a: "Le Corbeau", x: ["Le Chat noir", "La Chute de la maison Usher", "Le Scarabée d'or"], acc: ["le corbeau", "corbeau", "the raven"] },
  { id: "mercredi-d9", d: 3, t: "Quelle actrice, ancienne Mercredi au cinéma, joue une enseignante dans la série ?", a: "Christina Ricci", x: ["Winona Ryder", "Anjelica Huston", "Catherine Zeta-Jones"], acc: ["christina ricci", "ricci"] },
  { id: "mercredi-d10", d: 3, t: "Comment s'appelle la lycéenne sirène, rivale de Mercredi ?", a: "Bianca", x: ["Enid", "Divina", "Yoko"], acc: ["bianca", "bianca barclay"] },
  { id: "mercredi-d11", d: 3, t: "Quel duo de créateurs a conçu la série Mercredi ?", a: "Alfred Gough et Miles Millar", x: ["Les frères Duffer", "Benioff et Weiss", "Chris Columbus et associés"], acc: ["gough et millar", "alfred gough", "miles millar"] },
  { id: "mercredi-d12", d: 3, t: "Quelle actrice incarne Morticia dans la série ?", a: "Catherine Zeta-Jones", x: ["Anjelica Huston", "Christina Ricci", "Winona Ryder"], acc: ["catherine zeta-jones", "zeta-jones"] },
  { id: "mercredi-d13", d: 3, t: "Comment s'appelle la société secrète de Nevermore que Mercredi veut intégrer ?", a: "Les Nightshades", x: ["Les Maraudeurs", "Les Serpents", "Les Ombres"], acc: ["nightshades", "les nightshades"] },
  { id: "mercredi-d14", d: 3, t: "Combien d'épisodes compte la première saison de Mercredi ?", a: "8", x: ["4", "13", "24"], acc: ["8", "huit"] },
  { id: "mercredi-d15", d: 3, t: "Comment communique La Chose, n'ayant ni voix ni visage ?", a: "Par gestes de la main", x: ["Par télépathie", "En écrivant", "En clignotant"], acc: ["gestes", "gestes de la main", "signes"] },
  // --- Pro (20) ---
  { id: "mercredi-p1", d: 4, t: "Quel est le deuxième prénom de Mercredi, encore un jour de la semaine ?", a: "Friday", x: ["Sunday", "Monday", "Tuesday"], acc: ["friday", "vendredi"] },
  { id: "mercredi-p2", d: 4, t: "Quelle chanson des Cramps accompagne la fameuse danse de Mercredi ?", a: "Goo Goo Muck", x: ["Bloody Mary", "Paint It Black", "Zombie"], acc: ["goo goo muck"] },
  { id: "mercredi-p3", d: 4, t: "Quel titre de Lady Gaga a explosé sur les réseaux avec la danse de Mercredi ?", a: "Bloody Mary", x: ["Poker Face", "Bad Romance", "Alejandro"], acc: ["bloody mary"] },
  { id: "mercredi-p4", d: 4, t: "Quel acteur incarne Gomez Addams dans la série ?", a: "Luis Guzmán", x: ["Oscar Isaac", "Javier Bardem", "Benicio del Toro"], acc: ["luis guzman", "guzman"] },
  { id: "mercredi-p5", d: 4, t: "Quel humoriste du Saturday Night Live joue l'oncle Fétide en saison 1 ?", a: "Fred Armisen", x: ["Bill Hader", "Steve Carell", "Adam Sandler"], acc: ["fred armisen", "armisen"] },
  { id: "mercredi-p6", d: 4, t: "Comment s'appelle la professeure de botanique révélée méchante en saison 1 ?", a: "Marilyn Thornhill", x: ["Larissa Weems", "Morticia Addams", "Rosaline Rotwood"], acc: ["thornhill", "marilyn thornhill"] },
  { id: "mercredi-p7", d: 4, t: "Quel dessinateur a créé à l'origine la famille Addams ?", a: "Charles Addams", x: ["Tim Burton", "Edgar Allan Poe", "Charles Schulz"], acc: ["charles addams"] },
  { id: "mercredi-p8", d: 4, t: "Quel objet démodé Mercredi utilise-t-elle pour écrire son roman ?", a: "Une machine à écrire", x: ["Un ordinateur portable", "Un stylo plume", "Un smartphone"], acc: ["machine a ecrire", "machine à écrire"] },
  { id: "mercredi-p9", d: 4, t: "Comment s'appelle le gorgone timide de Nevermore dont Enid est amoureuse ?", a: "Ajax", x: ["Xavier", "Tyler", "Lucas"], acc: ["ajax", "ajax petropolus"] },
  { id: "mercredi-p10", d: 4, t: "En quel mois de 2025 la saison 2 de Mercredi est-elle sortie ?", a: "En août", x: ["En janvier", "En mai", "En décembre"], acc: ["aout", "en aout", "août"] },
  { id: "mercredi-p11", d: 4, t: "Quelle superstar de la pop apparaît en enseignante dans la saison 2 ?", a: "Lady Gaga", x: ["Beyoncé", "Taylor Swift", "Dua Lipa"], acc: ["lady gaga", "gaga"] },
  { id: "mercredi-p12", d: 4, t: "Quel animal noir, cher à Poe, sert de motif récurrent dans la série ?", a: "Le corbeau", x: ["Le hibou", "La pie", "La chauve-souris"], acc: ["corbeau", "le corbeau", "raven"] },
  { id: "mercredi-p13", d: 4, t: "Quelle est la vraie nature de Tyler, révélée à la fin de la saison 1 ?", a: "Il est le Hyde", x: ["Il est un vampire", "Il est un loup-garou", "Il est un sorcier"], acc: ["le hyde", "hyde", "il est le hyde"] },
  { id: "mercredi-p14", d: 4, t: "Comment s'appelle le grand bal de Nevermore où Mercredi danse ?", a: "Le bal Rave'N", x: ["Le bal de promo", "Le bal masqué", "Le gala d'hiver"], acc: ["rave'n", "raven", "bal rave'n"] },
  { id: "mercredi-p15", d: 4, t: "Quel acteur culte rejoint la saison 2 dans le rôle d'un nouveau principal ?", a: "Steve Buscemi", x: ["Danny DeVito", "Willem Dafoe", "Christopher Walken"], acc: ["steve buscemi", "buscemi"] },
  { id: "mercredi-p16", d: 4, t: "Comment s'appelle le fils du maire, bagarreur, ennemi de Mercredi au début ?", a: "Lucas", x: ["Tyler", "Xavier", "Ajax"], acc: ["lucas", "lucas walker"] },
  { id: "mercredi-p17", d: 4, t: "De quelle couleur Mercredi s'habille-t-elle presque exclusivement ?", a: "En noir", x: ["En rose", "En blanc", "En rouge"], acc: ["noir", "en noir"] },
  { id: "mercredi-p18", d: 4, t: "Comment s'appelle l'amie vampire d'Enid à Nevermore ?", a: "Yoko", x: ["Bianca", "Divina", "Rowan"], acc: ["yoko"] },
  { id: "mercredi-p19", d: 4, t: "Quel exploit Enid réussit-elle enfin lors du combat final de la saison 1 ?", a: "Se transformer entièrement en loup", x: ["Voler", "Devenir invisible", "Lancer des sorts"], acc: ["se transformer en loup", "transformation en loup", "loup"] },
  { id: "mercredi-p20", d: 4, t: "Comment s'appelle le pèlerin fondateur de Jericho, ennemi juré des marginaux ?", a: "Joseph Crackstone", x: ["Edgar Allan Poe", "Garrett Gates", "Isaac Night"], acc: ["crackstone", "joseph crackstone"] },
]);
