import { universe } from "../_build";

export const netflix = universe("series", "Séries Netflix", [
  // --- Faciles (5) ---
  { id: "netflix-f1", d: 1, t: "Quel service de streaming au logo « N » rouge est connu pour ses séries originales ?", a: "Netflix", x: ["Disney+", "Amazon Prime Video", "Canal+"] },
  { id: "netflix-f2", d: 1, t: "Quelle série Netflix se déroule à Hawkins et met en scène le Démogorgon ?", a: "Stranger Things", x: ["Dark", "The OA", "Wednesday"] },
  { id: "netflix-f3", d: 1, t: "Quelle série espagnole de braqueurs en combinaison rouge est un carton mondial ?", a: "La Casa de Papel", x: ["Élite", "Vis-à-vis", "Toy Boy"] },
  { id: "netflix-f4", d: 1, t: "Quelle série coréenne à jeux d'enfants mortels a battu des records d'audience ?", a: "Squid Game", x: ["Sweet Home", "Hellbound", "Kingdom"] },
  { id: "netflix-f5", d: 1, t: "Quelle série animée Netflix se déroule dans le monde de League of Legends ?", a: "Arcane", x: ["Castlevania", "Blood of Zeus", "Cyberpunk: Edgerunners"] },
  // --- Moyennes (10) ---
  { id: "netflix-m1", d: 2, t: "Quelle série Netflix sur la royauté britannique retrace le règne d'Élisabeth II ?", a: "The Crown", x: ["Victoria", "The Windsors", "Downton Abbey"] },
  { id: "netflix-m2", d: 2, t: "Quelle série met en scène Geralt de Riv, un sorceleur chasseur de monstres ?", a: "The Witcher", x: ["Shadow and Bone", "Cursed", "The Last Kingdom"] },
  { id: "netflix-m3", d: 2, t: "Quelle série d'horreur de Mike Flanagan hante le manoir de Hill House ?", a: "The Haunting of Hill House", x: ["Midnight Mass", "Marianne", "The Fall of the House of Usher"] },
  { id: "netflix-m4", d: 2, t: "Quelle série française suit un gentleman cambrioleur inspiré d'Arsène Lupin ?", a: "Lupin", x: ["Family Business", "Marseille", "Braqueurs"] },
  { id: "netflix-m5", d: 2, t: "Quelle série teen espagnole se déroule dans un lycée privé huppé ?", a: "Élite", x: ["Toy Boy", "Cable Girls", "Welcome to Eden"] },
  { id: "netflix-m6", d: 2, t: "Quelle série met en scène la famille Byrde blanchissant de l'argent dans le Missouri ?", a: "Ozark", x: ["Bloodline", "Narcos", "Animal Kingdom"] },
  { id: "netflix-m7", d: 2, t: "Quelle mini-série sur une joueuse d'échecs a révélé Anya Taylor-Joy ?", a: "Le Jeu de la dame", x: ["Maid", "Godless", "Ratched"], acc: ["queen's gambit", "the queen's gambit"] },
  { id: "netflix-m8", d: 2, t: "Quelle série britannique dépeint un lycéen conseiller sexuel malgré lui ?", a: "Sex Education", x: ["Atypical", "Never Have I Ever", "Feel Good"] },
  { id: "netflix-m9", d: 2, t: "Quelle série Netflix retrace la vie du baron de la drogue Pablo Escobar ?", a: "Narcos", x: ["El Chapo", "Ozark", "ZeroZeroZero"] },
  { id: "netflix-m10", d: 2, t: "Quelle série d'anthologie britannique explore les dérives de la technologie ?", a: "Black Mirror", x: ["Love, Death & Robots", "Electric Dreams", "Maniac"] },
  // --- Dures (15) ---
  { id: "netflix-d1", d: 3, t: "Quelle série allemande de voyage dans le temps se déroule à Winden ?", a: "Dark", x: ["1899", "Tribes of Europa", "Biohackers"] },
  { id: "netflix-d2", d: 3, t: "Quelle mini-série d'Ava DuVernay retrace l'affaire des cinq de Central Park ?", a: "Dans leur regard", x: ["Unbelievable", "Godless", "Seven Seconds"], acc: ["when they see us"] },
  { id: "netflix-d3", d: 3, t: "Quel dessin animé Netflix suit le chasseur de vampires Trevor Belmont ?", a: "Castlevania", x: ["Arcane", "Blood of Zeus", "Devilman Crybaby"] },
  { id: "netflix-d4", d: 3, t: "Quelle série documentaire de 2020 sur un éleveur de fauves est devenue virale ?", a: "Tiger King", x: ["Making a Murderer", "Wild Wild Country", "Our Planet"] },
  { id: "netflix-d5", d: 3, t: "Quelle série sud-coréenne de zombies se déroule à l'époque Joseon ?", a: "Kingdom", x: ["Sweet Home", "Hellbound", "All of Us Are Dead"] },
  { id: "netflix-d6", d: 3, t: "Quelle série animée pour adultes suit un cheval humanoïde déprimé à Hollywood ?", a: "BoJack Horseman", x: ["Big Mouth", "Disenchantment", "F is for Family"] },
  { id: "netflix-d7", d: 3, t: "Quelle série créée par Shonda Rhimes suit la haute société londonienne de la Régence ?", a: "La Chronique des Bridgerton", x: ["The Crown", "Sanditon", "Harlots"], acc: ["bridgerton"] },
  { id: "netflix-d8", d: 3, t: "Quelle comédie française suit une famille qui transforme sa boucherie en coffee shop ?", a: "Family Business", x: ["Plan Cœur", "Lupin", "Dix pour cent"] },
  { id: "netflix-d9", d: 3, t: "Quelle série romantique française orchestre un faux petit ami rémunéré ?", a: "Plan Cœur", x: ["Family Business", "Mortel", "Osmosis"] },
  { id: "netflix-d10", d: 3, t: "Quelle série fantastique française suit des adolescents et la Mort à Paris ?", a: "Mortel", x: ["Mythomaniac", "Osmosis", "Vampires"] },
  { id: "netflix-d11", d: 3, t: "Quelle série true crime de 2015 suit l'affaire judiciaire de Steven Avery ?", a: "Making a Murderer", x: ["The Staircase", "The Keepers", "Wild Wild Country"] },
  { id: "netflix-d12", d: 3, t: "Quelle série post-apocalyptique danoise suit un virus transmis par la pluie ?", a: "The Rain", x: ["Ragnarök", "Equinox", "The Chestnut Man"] },
  { id: "netflix-d13", d: 3, t: "Quelle série met en scène l'école Nevermore de Wednesday Addams ?", a: "Wednesday", x: ["Chilling Adventures of Sabrina", "Locke & Key", "The Umbrella Academy"] },
  { id: "netflix-d14", d: 3, t: "Quelle série de super-héros dysfonctionnels est adaptée d'un comic de Gerard Way ?", a: "The Umbrella Academy", x: ["The Boys", "Doom Patrol", "Misfits"] },
  { id: "netflix-d15", d: 3, t: "Quelle série mexicaine à succès a pour titre original « La Casa de las Flores » ?", a: "La Maison des fleurs", x: ["Ingobernable", "Club de Cuervos", "Monarca"] },
  // --- Pro (20) ---
  { id: "netflix-p1", d: 4, t: "En quelle année Netflix a-t-il lancé son service de streaming en ligne ?", a: "2007", x: ["2000", "2010", "2013"] },
  { id: "netflix-p2", d: 4, t: "Comment Netflix a-t-il débuté son activité en 1997 ?", a: "La location de DVD par courrier", x: ["La vente de livres", "La diffusion de radio", "La location de jeux vidéo"] },
  { id: "netflix-p3", d: 4, t: "Qui a cofondé Netflix et en a longtemps été le PDG ?", a: "Reed Hastings", x: ["Ted Sarandos", "Jeff Bezos", "Bob Iger"] },
  { id: "netflix-p4", d: 4, t: "Quelle série politique avec Kevin Spacey fut la première grande série originale de Netflix en 2013 ?", a: "House of Cards", x: ["Orange Is the New Black", "Hemlock Grove", "Sense8"] },
  { id: "netflix-p5", d: 4, t: "Quelle série carcérale féminine de 2013 est créée par Jenji Kohan ?", a: "Orange Is the New Black", x: ["Wentworth", "Vis-à-vis", "Bad Girls"] },
  { id: "netflix-p6", d: 4, t: "Quelle série de science-fiction des sœurs Wachowski suit huit inconnus mentalement liés ?", a: "Sense8", x: ["The OA", "Travelers", "Dark"] },
  { id: "netflix-p7", d: 4, t: "Quel duo de frères a créé la série Stranger Things ?", a: "Les frères Duffer", x: ["Les frères Russo", "Les frères Coen", "Les frères Farrelly"] },
  { id: "netflix-p8", d: 4, t: "Quelle actrice incarne Eleven dans Stranger Things ?", a: "Millie Bobby Brown", x: ["Sadie Sink", "Natalia Dyer", "Maya Hawke"] },
  { id: "netflix-p9", d: 4, t: "Quel acteur espagnol incarne le Professeur dans La Casa de Papel ?", a: "Álvaro Morte", x: ["Pedro Alonso", "Miguel Herrán", "Jaime Lorente"] },
  { id: "netflix-p10", d: 4, t: "Quels pseudonymes portent les braqueurs de La Casa de Papel ?", a: "Des noms de villes", x: ["Des noms de fleurs", "Des noms de planètes", "Des noms d'animaux"] },
  { id: "netflix-p11", d: 4, t: "Quel jeu du premier tour élimine des joueurs dans Squid Game ?", a: "Un, deux, trois, soleil", x: ["Le tir à la corde", "Le jeu des billes", "Le pont de verre"] },
  { id: "netflix-p12", d: 4, t: "Quel acteur incarne le joueur 456 dans Squid Game ?", a: "Lee Jung-jae", x: ["Park Hae-soo", "Wi Ha-joon", "Gong Yoo"] },
  { id: "netflix-p13", d: 4, t: "Quel film interactif Netflix de 2018 laissait le spectateur choisir l'histoire ?", a: "Black Mirror: Bandersnatch", x: ["You vs. Wild", "Kimmy vs. the Reverend", "The Boss Baby"] },
  { id: "netflix-p14", d: 4, t: "Quelle série de Ryan Murphy imagine un Hollywood alternatif des années 40 ?", a: "Hollywood", x: ["Ratched", "The Politician", "Halston"] },
  { id: "netflix-p15", d: 4, t: "Quelle mini-série de 2020 sur une communauté juive orthodoxe a révélé Shira Haas ?", a: "Unorthodox", x: ["Shtisel", "Self Made", "Maid"] },
  { id: "netflix-p16", d: 4, t: "Quel réalisateur au style gothique a produit et réalisé la série Wednesday ?", a: "Tim Burton", x: ["Sam Raimi", "Wes Craven", "David Fincher"] },
  { id: "netflix-p17", d: 4, t: "Quelle série documentaire animalière narrée par David Attenborough a marqué 2019 ?", a: "Our Planet", x: ["Planet Earth", "Night on Earth", "Our Great National Parks"] },
  { id: "netflix-p18", d: 4, t: "Combien d'abonnés Netflix a-t-il dépassés dans le monde au début 2021 ?", a: "200 millions", x: ["50 millions", "1 milliard", "10 millions"] },
  { id: "netflix-p19", d: 4, t: "Quelle série indienne de Netflix sur les gangs de Mumbai est adaptée d'un roman de Vikram Chandra ?", a: "Sacred Games", x: ["Delhi Crime", "Mirzapur", "Paatal Lok"] },
  { id: "netflix-p20", d: 4, t: "Quelle mini-série de 2019 sur une enquête pour agressions a été saluée par la critique ?", a: "Unbelievable", x: ["The Keepers", "Seven Seconds", "Godless"] },
]);
