import { universe } from "../_build";

export const rickmorty = universe("series", "Rick et Morty", [
  // --- Faciles (5) ---
  { id: "rickmorty-f1", d: 1, t: "Comment s'appelle le vieux savant génial et alcoolique de la série ?", a: "Rick", x: ["Morty", "Jerry", "Summer"], acc: ["rick", "rick sanchez"] },
  { id: "rickmorty-f2", d: 1, t: "Comment s'appelle le petit-fils anxieux qui accompagne Rick ?", a: "Morty", x: ["Rick", "Jerry", "Summer"], acc: ["morty", "morty smith"] },
  { id: "rickmorty-f3", d: 1, t: "Quel lien de parenté unit Rick et Morty ?", a: "Grand-père et petit-fils", x: ["Père et fils", "Frères", "Oncle et neveu"], acc: ["grand-pere et petit-fils", "grand-pere", "petit-fils"] },
  { id: "rickmorty-f4", d: 1, t: "Quel appareil permet à Rick de voyager entre les dimensions ?", a: "Le pistolet à portails", x: ["Une fusée", "Une DeLorean", "Un télescope"], acc: ["pistolet a portails", "portal gun", "pistolet a portail"] },
  { id: "rickmorty-f5", d: 1, t: "À quel genre appartient Rick et Morty ?", a: "La science-fiction animée pour adultes", x: ["Le dessin animé pour enfants", "Le documentaire", "La télé-réalité"], acc: ["science-fiction", "sf", "animation pour adultes"] },
  // --- Moyennes (10) ---
  { id: "rickmorty-m1", d: 2, t: "Qui a co-créé Rick et Morty avec Justin Roiland ?", a: "Dan Harmon", x: ["Matt Groening", "Seth MacFarlane", "Trey Parker"], acc: ["dan harmon", "harmon"] },
  { id: "rickmorty-m2", d: 2, t: "Sur quel bloc de programmes nocturne la série est-elle diffusée ?", a: "Adult Swim", x: ["Nickelodeon", "Disney Channel", "PBS Kids"], acc: ["adult swim"] },
  { id: "rickmorty-m3", d: 2, t: "Quelle est la réplique culte et délirante de Rick ?", a: "Wubba lubba dub dub", x: ["Bazinga", "D'oh", "Giggity"], acc: ["wubba lubba dub dub", "wubba lubba"] },
  { id: "rickmorty-m4", d: 2, t: "Comment s'appelle la mère de Morty, fille de Rick ?", a: "Beth", x: ["Summer", "Jessica", "Unity"], acc: ["beth"] },
  { id: "rickmorty-m5", d: 2, t: "Comment s'appelle le père de Morty, souvent moqué pour sa nullité ?", a: "Jerry", x: ["Rick", "Birdperson", "Squanchy"], acc: ["jerry"] },
  { id: "rickmorty-m6", d: 2, t: "Comment s'appelle la grande sœur de Morty ?", a: "Summer", x: ["Beth", "Jessica", "Tammy"], acc: ["summer"] },
  { id: "rickmorty-m7", d: 2, t: "Dans quelle pièce de la maison se trouve le laboratoire de Rick ?", a: "Le garage", x: ["La cave", "Le grenier", "La cuisine"], acc: ["garage", "le garage"] },
  { id: "rickmorty-m8", d: 2, t: "Comment s'appellent les créatures bleues qui réalisent une tâche puis disparaissent ?", a: "Les Mr. Meeseeks", x: ["Les Minions", "Les Gremlins", "Les Schtroumpfs"], acc: ["meeseeks", "mr meeseeks", "mister meeseeks"] },
  { id: "rickmorty-m9", d: 2, t: "En quelle année Rick et Morty a-t-elle été diffusée pour la première fois ?", a: "2013", x: ["2005", "2018", "2021"], acc: ["2013"] },
  { id: "rickmorty-m10", d: 2, t: "En quoi Rick se transforme-t-il dans un épisode culte pour éviter une thérapie ?", a: "En cornichon", x: ["En robot", "En chat", "En arbre"], acc: ["cornichon", "en cornichon", "pickle", "pickle rick"] },
  // --- Dures (15) ---
  { id: "rickmorty-d1", d: 3, t: "Comment appelle-t-on l'ensemble infini d'univers parallèles exploré par Rick ?", a: "Le multivers", x: ["La galaxie", "Le vortex", "L'au-delà"], acc: ["multivers", "le multivers", "multiverse"] },
  { id: "rickmorty-d2", d: 3, t: "Quel code désigne la dimension d'origine de notre Rick ?", a: "C-137", x: ["B-612", "K-9", "X-23"], acc: ["c-137", "c137"] },
  { id: "rickmorty-d3", d: 3, t: "Comment s'appelle la cité qui regroupe tous les Rick de toutes les dimensions ?", a: "La Citadelle des Rick", x: ["Le Conseil galactique", "La Fédération", "Le Nexus"], acc: ["citadelle des rick", "citadelle", "citadel of ricks"] },
  { id: "rickmorty-d4", d: 3, t: "Quel antagoniste récurrent est une version maléfique du petit-fils ?", a: "Evil Morty", x: ["Evil Rick", "Doofus Rick", "Jerryboree"], acc: ["evil morty", "morty malefique"] },
  { id: "rickmorty-d5", d: 3, t: "Quelle phrase les Mr. Meeseeks disent-ils en apparaissant ?", a: "I'm Mr. Meeseeks, look at me", x: ["Wubba lubba dub dub", "Show me what you got", "Aw geez"], acc: ["i'm mr meeseeks", "look at me", "mr meeseeks look at me"] },
  { id: "rickmorty-d6", d: 3, t: "Quelle sauce de fast-food Rick est-il obsédé à retrouver ?", a: "La sauce Szechuan", x: ["Le ketchup", "La sauce barbecue", "La mayonnaise"], acc: ["szechuan", "sauce szechuan", "szechuan sauce"] },
  { id: "rickmorty-d7", d: 3, t: "De quelle chaîne de fast-food provient la fameuse sauce recherchée par Rick ?", a: "McDonald's", x: ["Burger King", "KFC", "Taco Bell"], acc: ["mcdonald's", "mcdo", "mcdonalds"] },
  { id: "rickmorty-d8", d: 3, t: "Comment s'appelle le meilleur ami de Rick, un humanoïde-oiseau ?", a: "Birdperson", x: ["Squanchy", "Mr. Poopybutthole", "Gearhead"], acc: ["birdperson", "bird person"] },
  { id: "rickmorty-d9", d: 3, t: "Comment s'appelle l'objet domestique totalement absurde fabriqué dans un épisode ?", a: "Le Plumbus", x: ["Le Gizmo", "Le Flurbo", "Le Meeseeks"], acc: ["plumbus", "le plumbus"] },
  { id: "rickmorty-d10", d: 3, t: "Quel titre porte la chanson que Rick et Morty inventent pour sauver la Terre ?", a: "Get Schwifty", x: ["Wubba Song", "Portal Anthem", "Schwifty Blues"], acc: ["get schwifty", "schwifty"] },
  { id: "rickmorty-d11", d: 3, t: "Quel métier exerce Beth, la mère de Morty ?", a: "Chirurgienne pour chevaux", x: ["Avocate", "Astronaute", "Professeure"], acc: ["chirurgienne pour chevaux", "chirurgien equin", "chirurgienne chevaux"] },
  { id: "rickmorty-d12", d: 3, t: "Comment s'appelle l'ex de Rick, une conscience collective contrôlant une planète ?", a: "Unity", x: ["Beth", "Tammy", "Jessica"], acc: ["unity"] },
  { id: "rickmorty-d13", d: 3, t: "Comment appelle-t-on le divertissement de Rick fait de chaînes venues d'autres dimensions ?", a: "Le câble interdimensionnel", x: ["Le portail TV", "Le multivision", "Le cosmo-flux"], acc: ["cable interdimensionnel", "interdimensional cable"] },
  { id: "rickmorty-d14", d: 3, t: "Comment s'appelle le conseil qui dirige la Citadelle des Rick ?", a: "Le Conseil des Rick", x: ["Le Sénat", "La Fédération", "Le Tribunal"], acc: ["conseil des rick", "council of ricks"] },
  { id: "rickmorty-d15", d: 3, t: "Comment s'appelle la salle de jeux extraterrestre que Rick et Morty adorent ?", a: "Blips and Chitz", x: ["Blip Arcade", "Galaxy Games", "Chitz World"], acc: ["blips and chitz", "blips et chitz"] },
  // --- Pro (20) ---
  { id: "rickmorty-p1", d: 4, t: "Quel doubleur a longtemps prêté sa voix à la fois à Rick et à Morty ?", a: "Justin Roiland", x: ["Dan Harmon", "Seth Rogen", "Chris Parnell"], acc: ["justin roiland", "roiland"] },
  { id: "rickmorty-p2", d: 4, t: "En quelle année Justin Roiland a-t-il quitté la série ?", a: "2023", x: ["2013", "2018", "2020"], acc: ["2023"] },
  { id: "rickmorty-p3", d: 4, t: "Comment s'appelle le jeu vidéo dans lequel on vit toute une vie, que Morty essaie ?", a: "Roy", x: ["Sims", "Life", "Existenz"], acc: ["roy", "roy a life well lived"] },
  { id: "rickmorty-p4", d: 4, t: "Comment s'appelle l'ami félin de Rick, au nom évocateur ?", a: "Squanchy", x: ["Birdperson", "Gearhead", "Snuffles"], acc: ["squanchy"] },
  { id: "rickmorty-p5", d: 4, t: "Comment s'appelle le chien de la famille que Rick rend super-intelligent ?", a: "Snuffles", x: ["Squanchy", "Rex", "Milou"], acc: ["snuffles", "snowball"] },
  { id: "rickmorty-p6", d: 4, t: "Comment appelle-t-on la boîte qui fait apparaître les Mr. Meeseeks ?", a: "La Meeseeks Box", x: ["Le Portal Gun", "La boîte de Pandore", "Le Cube"], acc: ["meeseeks box", "boite a meeseeks"] },
  { id: "rickmorty-p7", d: 4, t: "Sur quelle planète les habitants se reproduisent-ils par la testostérone, dans un épisode ?", a: "Gazorpazorp", x: ["Gearhead", "Blips", "Cronenberg"], acc: ["gazorpazorp", "gazorp"] },
  { id: "rickmorty-p8", d: 4, t: "Comment appelle-t-on les créatures monstrueuses issues d'une expérience ratée de Rick ?", a: "Les Cronenberg", x: ["Les Meeseeks", "Les Gromflomites", "Les Zigerions"], acc: ["cronenberg", "cronenbergs"] },
  { id: "rickmorty-p9", d: 4, t: "Quel personnage réapparaît l'air de rien après avoir été « oublié » de tous ?", a: "Mr. Poopybutthole", x: ["Birdperson", "Squanchy", "Gearhead"], acc: ["mr poopybutthole", "poopybutthole"] },
  { id: "rickmorty-p10", d: 4, t: "Quelle expression anxieuse Morty répète-t-il souvent ?", a: "Aw geez", x: ["Wubba lubba", "Oh boy howdy", "Bazinga"], acc: ["aw geez", "oh geez", "aw jeez"] },
  { id: "rickmorty-p11", d: 4, t: "Quel liquide alimente le pistolet à portails de Rick ?", a: "Le fluide à portails", x: ["Le plasma", "L'essence cosmique", "Le mercure"], acc: ["fluide a portails", "portal fluid", "fluide a portail"] },
  { id: "rickmorty-p12", d: 4, t: "Quelle grande organisation spatiale, ennemie de Rick, ressemble à un empire galactique ?", a: "La Fédération galactique", x: ["La Citadelle", "L'Alliance rebelle", "Le Conseil des Rick"], acc: ["federation galactique", "federation"] },
  { id: "rickmorty-p13", d: 4, t: "Comment s'appellent les extraterrestres-insectes soldats de la Fédération galactique ?", a: "Les Gromflomites", x: ["Les Zigerions", "Les Meeseeks", "Les Cronenberg"], acc: ["gromflomites", "gromflomite"] },
  { id: "rickmorty-p14", d: 4, t: "Combien d'épisodes la chaîne a-t-elle commandés d'un coup en 2018 ?", a: "70 épisodes", x: ["10 épisodes", "200 épisodes", "3 épisodes"], acc: ["70 episodes", "70", "soixante-dix"] },
  { id: "rickmorty-p15", d: 4, t: "Quel Rick benêt et gentil est méprisé par les autres Rick ?", a: "Doofus Rick", x: ["Evil Rick", "Rickest Rick", "Pickle Rick"], acc: ["doofus rick", "doofus"] },
  { id: "rickmorty-p16", d: 4, t: "Comment s'appelle la garderie où Jerry est déposé pendant les aventures ?", a: "Le Jerryboree", x: ["Le Jerry Camp", "La Jerry Zone", "Le Jerryland"], acc: ["jerryboree"] },
  { id: "rickmorty-p17", d: 4, t: "De quelle couleur sont la peau et le corps des Mr. Meeseeks ?", a: "Bleue", x: ["Verte", "Rouge", "Jaune"], acc: ["bleue", "bleu"] },
  { id: "rickmorty-p18", d: 4, t: "Quel type de boisson Rick garde-t-il en permanence dans sa flasque ?", a: "De l'alcool fort", x: ["Du jus de fruit", "De l'eau", "Du lait"], acc: ["alcool fort", "alcool", "whisky"] },
  { id: "rickmorty-p19", d: 4, t: "Quelle chaîne, propriétaire d'Adult Swim, diffuse la série aux États-Unis ?", a: "Cartoon Network", x: ["HBO", "Fox", "AMC"], acc: ["cartoon network"] },
  { id: "rickmorty-p20", d: 4, t: "Quelle ex de Birdperson devient une ennemie majeure de Rick ?", a: "Tammy", x: ["Unity", "Beth", "Jessica"], acc: ["tammy"] },
]);
