import { universe } from "../_build";

export const sexandthecity = universe("series", "Sex and the City", [
  // --- Faciles (5) ---
  { id: "satc-f1", d: 1, t: "Dans quelle ville se déroule Sex and the City ?", a: "New York", x: ["Los Angeles", "Chicago", "Miami"] },
  { id: "satc-f2", d: 1, t: "Combien d'amies principales la série suit-elle ?", a: "Quatre", x: ["Trois", "Cinq", "Deux"] },
  { id: "satc-f3", d: 1, t: "Quel métier exerce l'héroïne Carrie ?", a: "Chroniqueuse", x: ["Avocate", "Médecin", "Cheffe cuisinière"], acc: ["chroniqueuse", "journaliste"] },
  { id: "satc-f4", d: 1, t: "Quel cocktail rose est emblématique de la série ?", a: "Le Cosmopolitan", x: ["Le Mojito", "La Margarita", "Le Spritz"], acc: ["cosmopolitan", "cosmo"] },
  { id: "satc-f5", d: 1, t: "De quoi Carrie est-elle passionnée, collectionnant les Manolo Blahnik ?", a: "Les chaussures", x: ["Les sacs", "Les chapeaux", "Les montres"] },
  // --- Moyennes (10) ---
  { id: "satc-m1", d: 2, t: "Comment s'appelle l'héroïne narratrice de la série ?", a: "Carrie Bradshaw", x: ["Samantha Jones", "Charlotte York", "Miranda Hobbes"] },
  { id: "satc-m2", d: 2, t: "Quelle chaîne américaine a diffusé Sex and the City ?", a: "HBO", x: ["NBC", "ABC", "Netflix"] },
  { id: "satc-m3", d: 2, t: "Comment la série surnomme-t-elle l'amour compliqué et récurrent de Carrie ?", a: "Mr. Big", x: ["Mr. Wrong", "Mr. Perfect", "Mr. Right"] },
  { id: "satc-m4", d: 2, t: "Quelle amie, dans les relations publiques, est la plus libérée sexuellement ?", a: "Samantha", x: ["Charlotte", "Miranda", "Carrie"] },
  { id: "satc-m5", d: 2, t: "Quelle amie avocate, cynique et rousse, est la plus terre-à-terre ?", a: "Miranda", x: ["Samantha", "Charlotte", "Carrie"] },
  { id: "satc-m6", d: 2, t: "Quelle amie romantique rêve du mariage parfait et travaille dans l'art ?", a: "Charlotte", x: ["Samantha", "Miranda", "Carrie"] },
  { id: "satc-m7", d: 2, t: "Combien de saisons compte la série originale ?", a: "6", x: ["4", "8", "10"] },
  { id: "satc-m8", d: 2, t: "Sur quoi porte la chronique de Carrie intitulée « Sex and the City » ?", a: "Sur la vie amoureuse à New York", x: ["Sur la cuisine", "Sur la politique", "Sur le sport"] },
  { id: "satc-m9", d: 2, t: "Quelle actrice incarne Carrie Bradshaw ?", a: "Sarah Jessica Parker", x: ["Kim Cattrall", "Cynthia Nixon", "Kristin Davis"] },
  { id: "satc-m10", d: 2, t: "Quelle phrase Carrie répète-t-elle souvent en réfléchissant ?", a: "I couldn't help but wonder", x: ["That's what she said", "How you doin'", "Legen-dary"] },
  // --- Dures (15) ---
  { id: "satc-d1", d: 3, t: "Quelle actrice incarne Samantha Jones ?", a: "Kim Cattrall", x: ["Cynthia Nixon", "Kristin Davis", "Sarah Jessica Parker"] },
  { id: "satc-d2", d: 3, t: "Quelle actrice incarne Miranda Hobbes ?", a: "Cynthia Nixon", x: ["Kim Cattrall", "Kristin Davis", "Sarah Jessica Parker"] },
  { id: "satc-d3", d: 3, t: "Quelle actrice incarne Charlotte York ?", a: "Kristin Davis", x: ["Kim Cattrall", "Cynthia Nixon", "Sarah Jessica Parker"] },
  { id: "satc-d4", d: 3, t: "Quel acteur incarne Mr. Big ?", a: "Chris Noth", x: ["John Corbett", "David Eigenberg", "Mikhail Baryshnikov"] },
  { id: "satc-d5", d: 3, t: "Quel créateur de chaussures Carrie vénère-t-elle particulièrement ?", a: "Manolo Blahnik", x: ["Christian Louboutin", "Jimmy Choo", "Salvatore Ferragamo"] },
  { id: "satc-d6", d: 3, t: "Quel métier exerce Miranda ?", a: "Avocate", x: ["Médecin", "Galeriste", "Publicitaire"] },
  { id: "satc-d7", d: 3, t: "Quel métier exerce Samantha ?", a: "Attachée de presse", x: ["Avocate", "Médecin", "Journaliste"], acc: ["relations publiques"] },
  { id: "satc-d8", d: 3, t: "Quel designer de meubles est l'un des grands amours de Carrie ?", a: "Aidan Shaw", x: ["Jack Berger", "Harry Goldenblatt", "Steve Brady"] },
  { id: "satc-d9", d: 3, t: "Quel barman finit par épouser Miranda ?", a: "Steve Brady", x: ["Aidan Shaw", "Harry Goldenblatt", "Smith Jerrod"] },
  { id: "satc-d10", d: 3, t: "Comment s'appelle le fils de Miranda et Steve ?", a: "Brady", x: ["Rock", "Harry", "Aidan"], acc: ["brady"] },
  { id: "satc-d11", d: 3, t: "Pour épouser Harry, à quelle religion Charlotte se convertit-elle ?", a: "Au judaïsme", x: ["Au catholicisme", "À l'islam", "Au bouddhisme"], acc: ["judaïsme", "juive"] },
  { id: "satc-d12", d: 3, t: "Comment un petit ami rompt-il cruellement avec Carrie par un simple mot ?", a: "Par un Post-it", x: ["Par SMS", "Par lettre", "Par e-mail"], acc: ["post-it"] },
  { id: "satc-d13", d: 3, t: "Qui est le meilleur ami gay de Carrie ?", a: "Stanford Blatch", x: ["Anthony Marentino", "Harry Goldenblatt", "Smith Jerrod"] },
  { id: "satc-d14", d: 3, t: "Dans quelle ville européenne Carrie part-elle vivre avec Aleksandr dans la saison 6 ?", a: "Paris", x: ["Londres", "Rome", "Milan"] },
  { id: "satc-d15", d: 3, t: "Quel jeune acteur Samantha fréquente-t-elle et fait connaître ?", a: "Smith Jerrod", x: ["Steve Brady", "Aidan Shaw", "Harry Goldenblatt"] },
  // --- Pro (20) ---
  { id: "satc-p1", d: 4, t: "Quel est le vrai nom de Mr. Big, révélé plus tard ?", a: "John James Preston", x: ["Aleksandr Petrovsky", "Harry Goldenblatt", "Jack Berger"] },
  { id: "satc-p2", d: 4, t: "De quelle chroniqueuse et autrice le livre à l'origine de la série est-il tiré ?", a: "Candace Bushnell", x: ["Nora Ephron", "Erica Jong", "Helen Fielding"] },
  { id: "satc-p3", d: 4, t: "Quel danseur russe joue Aleksandr Petrovsky, l'artiste amant de Carrie ?", a: "Mikhail Baryshnikov", x: ["Rudolf Noureev", "Roberto Bolle", "Sergueï Polunin"] },
  { id: "satc-p4", d: 4, t: "Quel acteur joue Aidan Shaw ?", a: "John Corbett", x: ["Chris Noth", "David Eigenberg", "Evan Handler"] },
  { id: "satc-p5", d: 4, t: "Comment s'appelle le premier mari de Charlotte, un médecin de bonne famille ?", a: "Trey MacDougal", x: ["Harry Goldenblatt", "Aidan Shaw", "Steve Brady"] },
  { id: "satc-p6", d: 4, t: "Quel avocat chauve devient le second mari de Charlotte ?", a: "Harry Goldenblatt", x: ["Trey MacDougal", "Steve Brady", "Jack Berger"] },
  { id: "satc-p7", d: 4, t: "En quelle année le premier film Sex and the City est-il sorti ?", a: "2008", x: ["2004", "2010", "2012"] },
  { id: "satc-p8", d: 4, t: "Comment s'appelle la fille que Charlotte et Harry adoptent en Chine ?", a: "Lily", x: ["Rose", "Grace", "Emma"], acc: ["lily"] },
  { id: "satc-p9", d: 4, t: "Dans quel journal fictif Carrie publie-t-elle sa chronique ?", a: "Le New York Star", x: ["Le Daily Planet", "Le New York Ledger", "Le Gotham Gazette"], acc: ["new york star"] },
  { id: "satc-p10", d: 4, t: "Quel organisateur de mariages, plus tard mari de Stanford, conseille Charlotte ?", a: "Anthony Marentino", x: ["Smith Jerrod", "Harry Goldenblatt", "Jack Berger"] },
  { id: "satc-p11", d: 4, t: "En quelle année la série originale s'est-elle terminée ?", a: "2004", x: ["2000", "2006", "2008"] },
  { id: "satc-p12", d: 4, t: "Comment s'appelle la suite lancée en 2021 ?", a: "And Just Like That", x: ["The Carrie Diaries", "Emily in Paris", "Girls"], acc: ["and just like that"] },
  { id: "satc-p13", d: 4, t: "Quelle actrice n'est pas revenue dans la suite And Just Like That ?", a: "Kim Cattrall", x: ["Sarah Jessica Parker", "Cynthia Nixon", "Kristin Davis"] },
  { id: "satc-p14", d: 4, t: "Quel écrivain fréquente Carrie avant de la quitter par un Post-it ?", a: "Jack Berger", x: ["Aidan Shaw", "Aleksandr Petrovsky", "Steve Brady"] },
  { id: "satc-p15", d: 4, t: "Combien d'épisodes compte environ la série originale ?", a: "94", x: ["50", "120", "200"], acc: ["94"] },
  { id: "satc-p16", d: 4, t: "Quel est le métier de Charlotte au début de la série ?", a: "Galeriste", x: ["Avocate", "Médecin", "Publicitaire"], acc: ["galerie d'art"] },
  { id: "satc-p17", d: 4, t: "Quelle maladie touche Samantha dans la saison 6 ?", a: "Un cancer du sein", x: ["Une pneumonie", "Le diabète", "Une dépression"], acc: ["cancer du sein", "cancer"] },
  { id: "satc-p18", d: 4, t: "Dans quel pays se déroule en partie le film Sex and the City 2 ?", a: "Les Émirats arabes unis", x: ["La France", "Le Royaume-Uni", "Le Japon"], acc: ["abou dabi", "emirats"] },
  { id: "satc-p19", d: 4, t: "Comment s'appelle le chien de Charlotte, un cavalier King Charles ?", a: "Elizabeth Taylor", x: ["Lady", "Rocky", "Toto"], acc: ["elizabeth taylor"] },
  { id: "satc-p20", d: 4, t: "Combien de films dérivés de la série sont sortis au cinéma ?", a: "2", x: ["1", "3", "4"], acc: ["2", "deux"] },
]);
