import { universe } from "../_build";

export const simpsons = universe("series", "Les Simpson", [
  // --- Faciles (5) ---
  { id: "simpsons-f1", d: 1, t: "Comment s'appelle le père de la famille Simpson ?", a: "Homer", x: ["Bart", "Ned", "Moe"], acc: ["homer", "homer simpson"] },
  { id: "simpsons-f2", d: 1, t: "Dans quelle ville vivent les Simpson ?", a: "Springfield", x: ["Shelbyville", "Quahog", "Gotham"], acc: ["springfield"] },
  { id: "simpsons-f3", d: 1, t: "Quelle est l'exclamation favorite d'Homer Simpson ?", a: "D'oh !", x: ["Bazinga !", "Cowabunga !", "Yabba dabba !"], acc: ["d'oh", "doh"] },
  { id: "simpsons-f4", d: 1, t: "De quelle couleur est la peau des personnages des Simpson ?", a: "Jaune", x: ["Verte", "Bleue", "Rose"], acc: ["jaune"] },
  { id: "simpsons-f5", d: 1, t: "Comment s'appelle le fils aîné de la famille Simpson ?", a: "Bart", x: ["Lisa", "Maggie", "Milhouse"], acc: ["bart", "bart simpson"] },
  // --- Moyennes (10) ---
  { id: "simpsons-m1", d: 2, t: "Qui a créé la série Les Simpson ?", a: "Matt Groening", x: ["Seth MacFarlane", "Trey Parker", "Mike Judge"], acc: ["matt groening", "groening"] },
  { id: "simpsons-m2", d: 2, t: "Où travaille Homer Simpson ?", a: "À la centrale nucléaire", x: ["Au commissariat", "À la brasserie Duff", "Au Kwik-E-Mart"], acc: ["centrale nucleaire", "centrale"] },
  { id: "simpsons-m3", d: 2, t: "Comment s'appelle la fille intello qui joue du saxophone ?", a: "Lisa", x: ["Maggie", "Marge", "Patty"], acc: ["lisa", "lisa simpson"] },
  { id: "simpsons-m4", d: 2, t: "Comment s'appelle le bébé de la famille Simpson ?", a: "Maggie", x: ["Lisa", "Bart", "Marge"], acc: ["maggie"] },
  { id: "simpsons-m5", d: 2, t: "Quelle bière Homer boit-il tout le temps ?", a: "La Duff", x: ["La Pawtucket", "La Heineken", "La Corona"], acc: ["duff", "la duff"] },
  { id: "simpsons-m6", d: 2, t: "Comment s'appelle le patron d'Homer, propriétaire de la centrale ?", a: "Monsieur Burns", x: ["Monsieur Moe", "Monsieur Flanders", "Monsieur Skinner"], acc: ["burns", "monsieur burns", "mr burns"] },
  { id: "simpsons-m7", d: 2, t: "Quel est le voisin très pieux des Simpson ?", a: "Ned Flanders", x: ["Moe Szyslak", "Barney Gumble", "Apu"], acc: ["ned flanders", "flanders", "ned"] },
  { id: "simpsons-m8", d: 2, t: "Sur quelle chaîne américaine les Simpson sont-ils diffusés ?", a: "La FOX", x: ["CBS", "NBC", "ABC"], acc: ["fox", "la fox"] },
  { id: "simpsons-m9", d: 2, t: "Comment s'appelle le bar où Homer passe ses soirées ?", a: "Chez Moe", x: ["Le Kwik-E-Mart", "Le Krusty Burger", "Le Duff Bar"], acc: ["chez moe", "moe", "moe's"] },
  { id: "simpsons-m10", d: 2, t: "Quel aliment Homer adore-t-il par-dessus tout ?", a: "Les donuts", x: ["Les pizzas", "Les tacos", "Les sushis"], acc: ["donuts", "beignets"] },
  // --- Dures (15) ---
  { id: "simpsons-d1", d: 3, t: "En quelle année la série Les Simpson a-t-elle été lancée en épisodes complets ?", a: "1989", x: ["1985", "1993", "1999"], acc: ["1989"] },
  { id: "simpsons-d2", d: 3, t: "Comment s'appelle le clown vedette de la télé que regarde Bart ?", a: "Krusty", x: ["Bozo", "Ronald", "Pipo"], acc: ["krusty", "krusty le clown"] },
  { id: "simpsons-d3", d: 3, t: "Comment s'appelle le chien de la famille Simpson ?", a: "Petit Papa Noël", x: ["Rex", "Idéfix", "Milou"], acc: ["petit papa noel", "santa's little helper"] },
  { id: "simpsons-d4", d: 3, t: "Comment s'appelle le meilleur ami de Bart ?", a: "Milhouse", x: ["Nelson", "Ralph", "Martin"], acc: ["milhouse"] },
  { id: "simpsons-d5", d: 3, t: "Comment s'appelle le tenancier du Kwik-E-Mart ?", a: "Apu", x: ["Moe", "Sanjay", "Carl"], acc: ["apu"] },
  { id: "simpsons-d6", d: 3, t: "Comment s'appelle le chef de la police de Springfield ?", a: "Le chef Wiggum", x: ["Le chef Skinner", "Le chef Lovejoy", "Le chef Quimby"], acc: ["wiggum", "chef wiggum", "clancy wiggum"] },
  { id: "simpsons-d7", d: 3, t: "Comment s'appelle le directeur de l'école de Bart et Lisa ?", a: "Le principal Skinner", x: ["Le principal Chalmers", "Le principal Flanders", "Le principal Burns"], acc: ["skinner", "principal skinner", "seymour skinner"] },
  { id: "simpsons-d8", d: 3, t: "Quel est le nom de jeune fille de Marge ?", a: "Bouvier", x: ["Simpson", "Flanders", "Szyslak"], acc: ["bouvier"] },
  { id: "simpsons-d9", d: 3, t: "Comment s'appelle le grand-père de Bart, père d'Homer ?", a: "Abraham", x: ["Herb", "Clancy", "Seymour"], acc: ["abraham", "abraham simpson", "grampa"] },
  { id: "simpsons-d10", d: 3, t: "Quelle réplique culte Bart lance-t-il pour qu'on le laisse tranquille ?", a: "Mange mes shorts", x: ["Bazinga", "Cowabunga", "C'est la vie"], acc: ["mange mes shorts", "eat my shorts"] },
  { id: "simpsons-d11", d: 3, t: "Comment s'appellent les deux sœurs de Marge ?", a: "Patty et Selma", x: ["Thelma et Louise", "Mary et Sue", "Anna et Elsa"], acc: ["patty et selma", "patty", "selma"] },
  { id: "simpsons-d12", d: 3, t: "Quel ennemi juré de Bart est un ancien acolyte de Krusty ?", a: "Tahiti Bob", x: ["Tahiti Mel", "Gérard", "Nelson"], acc: ["tahiti bob", "sideshow bob"] },
  { id: "simpsons-d13", d: 3, t: "Comment s'appelle la ville rivale de Springfield ?", a: "Shelbyville", x: ["Ogdenville", "Capital City", "Quahog"], acc: ["shelbyville"] },
  { id: "simpsons-d14", d: 3, t: "Quel dessin animé ultra-violent Bart et Lisa regardent-ils à la télé ?", a: "Itchy et Scratchy", x: ["Tom et Jerry", "Ren et Stimpy", "Pinky et le Cerveau"], acc: ["itchy et scratchy", "itchy and scratchy"] },
  { id: "simpsons-d15", d: 3, t: "Quel garçon brutal crie « Ha-ha ! » pour se moquer des autres ?", a: "Nelson", x: ["Ralph", "Milhouse", "Martin"], acc: ["nelson", "nelson muntz"] },
  // --- Pro (20) ---
  { id: "simpsons-p1", d: 4, t: "Dans quelle émission les Simpson sont-ils d'abord apparus en courts métrages en 1987 ?", a: "Le Tracey Ullman Show", x: ["Le Saturday Night Live", "Le Ed Sullivan Show", "Le Muppet Show"], acc: ["tracey ullman show", "tracey ullman"] },
  { id: "simpsons-p2", d: 4, t: "Quel acteur double Homer Simpson en version originale ?", a: "Dan Castellaneta", x: ["Harry Shearer", "Hank Azaria", "Nancy Cartwright"], acc: ["dan castellaneta", "castellaneta"] },
  { id: "simpsons-p3", d: 4, t: "Quelle actrice prête sa voix à Bart en version originale ?", a: "Nancy Cartwright", x: ["Julie Kavner", "Yeardley Smith", "Pamela Hayden"], acc: ["nancy cartwright", "cartwright"] },
  { id: "simpsons-p4", d: 4, t: "Quelle actrice double Marge en version originale ?", a: "Julie Kavner", x: ["Nancy Cartwright", "Yeardley Smith", "Tress MacNeille"], acc: ["julie kavner", "kavner"] },
  { id: "simpsons-p5", d: 4, t: "Comment s'appelle l'assistant dévoué de Monsieur Burns ?", a: "Smithers", x: ["Homer", "Lenny", "Carl"], acc: ["smithers", "waylon smithers"] },
  { id: "simpsons-p6", d: 4, t: "Quel acteur célèbre pour Frasier double Tahiti Bob ?", a: "Kelsey Grammer", x: ["Kevin Spacey", "David Hyde Pierce", "John Mahoney"], acc: ["kelsey grammer", "grammer"] },
  { id: "simpsons-p7", d: 4, t: "Comment s'appelle le film des Simpson sorti au cinéma en 2007 ?", a: "Les Simpson le film", x: ["Les Simpson au cinéma", "Springfield le film", "Homer le film"], acc: ["les simpson le film", "the simpsons movie", "simpson le film"] },
  { id: "simpsons-p8", d: 4, t: "Comment s'appellent les deux collègues et amis d'Homer à la centrale ?", a: "Lenny et Carl", x: ["Moe et Barney", "Patty et Selma", "Itchy et Scratchy"], acc: ["lenny et carl", "lenny", "carl"] },
  { id: "simpsons-p9", d: 4, t: "Comment s'appelle l'ivrogne du bar, ami d'Homer ?", a: "Barney", x: ["Moe", "Lenny", "Otto"], acc: ["barney", "barney gumble"] },
  { id: "simpsons-p10", d: 4, t: "Comment s'appelle le fils un peu simplet du chef Wiggum ?", a: "Ralph", x: ["Nelson", "Milhouse", "Martin"], acc: ["ralph", "ralph wiggum"] },
  { id: "simpsons-p11", d: 4, t: "Comment s'appelle le jardinier écossais de l'école ?", a: "Willie", x: ["Otto", "Gil", "Angus"], acc: ["willie", "jardinier willie", "groundskeeper willie"] },
  { id: "simpsons-p12", d: 4, t: "Comment s'appelle le maire corrompu de Springfield ?", a: "Le maire Quimby", x: ["Le maire Burns", "Le maire Lovejoy", "Le maire Skinner"], acc: ["quimby", "maire quimby"] },
  { id: "simpsons-p13", d: 4, t: "Comment surnomme-t-on le vendeur obèse et sarcastique de la boutique de BD ?", a: "Le Marchand de BD", x: ["Comic Sans", "Krusty", "Gil"], acc: ["marchand de bd", "comic book guy"] },
  { id: "simpsons-p14", d: 4, t: "Quels épisodes spéciaux d'Halloween reviennent chaque année ?", a: "Simpson Horror Show", x: ["La Nuit des Simpson", "Simpson Frayeur", "Halloween à Springfield"], acc: ["simpson horror show", "treehouse of horror"] },
  { id: "simpsons-p15", d: 4, t: "Comment s'appelle le charlatan surnommé « Docteur Nick » ?", a: "Docteur Nick Riviera", x: ["Docteur Hibbert", "Docteur House", "Docteur Zoidberg"], acc: ["docteur nick", "nick riviera", "dr nick"] },
  { id: "simpsons-p16", d: 4, t: "Comment s'appelle le révérend de l'église de Springfield ?", a: "Le révérend Lovejoy", x: ["Le révérend Flanders", "Le révérend Quimby", "Le révérend Wiggum"], acc: ["lovejoy", "reverend lovejoy"] },
  { id: "simpsons-p17", d: 4, t: "Comment s'appelle l'institutrice de Bart, longtemps proche de Skinner ?", a: "Edna Krabappel", x: ["Miss Hoover", "Marge Bouvier", "Selma"], acc: ["edna krabappel", "krabappel"] },
  { id: "simpsons-p18", d: 4, t: "Comment surnomme-t-on le parrain de la mafia de Springfield ?", a: "Gros Tony", x: ["Petit Tony", "Don Vito", "Fat Moe"], acc: ["gros tony", "fat tony"] },
  { id: "simpsons-p19", d: 4, t: "Comment s'appellent les deux extraterrestres des épisodes d'Halloween ?", a: "Kang et Kodos", x: ["Zim et Dib", "Roger et Klaus", "Bip et Bop"], acc: ["kang et kodos", "kang", "kodos"] },
  { id: "simpsons-p20", d: 4, t: "Quel record les Simpson détiennent-ils à la télévision américaine ?", a: "La plus longue sitcom en prime time", x: ["La plus courte série", "La série la moins vue", "La seule série muette"], acc: ["plus longue sitcom", "plus longue serie", "longest running sitcom"] },
]);
