import { universe } from "../_build";

export const squidgame = universe("series", "Squid Game", [
  // --- Faciles (5) ---
  { id: "squid-f1", d: 1, t: "De quel pays vient la série Squid Game ?", a: "La Corée du Sud", x: ["Le Japon", "La Chine", "La Thaïlande"] },
  { id: "squid-f2", d: 1, t: "Sur quelle plateforme Squid Game est-elle sortie ?", a: "Netflix", x: ["Disney+", "Amazon Prime", "HBO"] },
  { id: "squid-f3", d: 1, t: "Que remportent les joueurs s'ils survivent à tous les jeux ?", a: "De l'argent", x: ["Une île", "La vie éternelle", "Un trône"] },
  { id: "squid-f4", d: 1, t: "De quelle couleur est la combinaison des joueurs ?", a: "Vert", x: ["Rose", "Rouge", "Bleu"] },
  { id: "squid-f5", d: 1, t: "Les jeux mortels de la série sont des versions de quoi ?", a: "De jeux d'enfants", x: ["De sports olympiques", "De jeux vidéo", "De jeux de casino"] },
  // --- Moyennes (10) ---
  { id: "squid-m1", d: 2, t: "Comment s'appelle le héros principal, le joueur 456 ?", a: "Seong Gi-hun", x: ["Cho Sang-woo", "Hwang Jun-ho", "Oh Il-nam"] },
  { id: "squid-m2", d: 2, t: "Combien de joueurs participent au jeu au début de la saison 1 ?", a: "456", x: ["100", "1000", "218"] },
  { id: "squid-m3", d: 2, t: "Quel premier jeu utilise une poupée géante qui élimine ceux qui bougent ?", a: "Un, deux, trois, soleil", x: ["La marelle", "Le chat perché", "Colin-maillard"], acc: ["1 2 3 soleil", "red light green light"] },
  { id: "squid-m4", d: 2, t: "De quelle couleur sont les combinaisons des gardes masqués ?", a: "Rose", x: ["Verte", "Noire", "Blanche"] },
  { id: "squid-m5", d: 2, t: "Quelles formes ornent les masques des gardes selon leur rang ?", a: "Cercle, triangle et carré", x: ["Étoile, lune et soleil", "Cœur, pique et trèfle", "Rond, croix et éclair"] },
  { id: "squid-m6", d: 2, t: "Quel bonbon coréen faut-il découper sans le briser dans un des jeux ?", a: "Le dalgona", x: ["Le mochi", "Le pocky", "Le caramel mou"], acc: ["dalgona", "sugar honeycomb"] },
  { id: "squid-m7", d: 2, t: "Qui dirige les jeux, masqué et vêtu de noir ?", a: "Le Front Man", x: ["Le recruteur", "Le vieil homme", "Le détective"], acc: ["front man"] },
  { id: "squid-m8", d: 2, t: "Quel jeu d'équipe consiste à tirer sur une corde au-dessus du vide ?", a: "Le tir à la corde", x: ["Le lancer de poids", "La course en sac", "Le bras de fer"] },
  { id: "squid-m9", d: 2, t: "En quelle année la première saison de Squid Game est-elle sortie ?", a: "2021", x: ["2019", "2023", "2020"] },
  { id: "squid-m10", d: 2, t: "Quel objet sert de mise dans le jeu entre partenaires, au 4e round ?", a: "Des billes", x: ["Des dés", "Des cartes", "Des pièces"], acc: ["billes", "marbles"] },
  // --- Dures (15) ---
  { id: "squid-d1", d: 3, t: "Qui a créé la série Squid Game ?", a: "Hwang Dong-hyuk", x: ["Bong Joon-ho", "Park Chan-wook", "Lee Jung-jae"] },
  { id: "squid-d2", d: 3, t: "Quel ami d'enfance de Gi-hun, ancien banquier, porte le numéro 218 ?", a: "Cho Sang-woo", x: ["Ali Abdul", "Jang Deok-su", "Oh Il-nam"] },
  { id: "squid-d3", d: 3, t: "Quelle joueuse, transfuge nord-coréenne, porte le numéro 067 ?", a: "Kang Sae-byeok", x: ["Han Mi-nyeo", "Cho Sang-woo", "Oh Il-nam"] },
  { id: "squid-d4", d: 3, t: "Quel travailleur immigré pakistanais, joueur 199, s'allie à Sang-woo ?", a: "Ali Abdul", x: ["Jang Deok-su", "Cho Sang-woo", "Oh Il-nam"] },
  { id: "squid-d5", d: 3, t: "Quel vieil homme porte le numéro 001 ?", a: "Oh Il-nam", x: ["Seong Gi-hun", "Cho Sang-woo", "Ali Abdul"] },
  { id: "squid-d6", d: 3, t: "Quel policier s'infiltre parmi les gardes pour retrouver son frère ?", a: "Hwang Jun-ho", x: ["Seong Gi-hun", "Cho Sang-woo", "Jang Deok-su"] },
  { id: "squid-d7", d: 3, t: "Quel jeu final donne son nom à la série ?", a: "Le jeu du calmar", x: ["Le jeu de la pieuvre", "Le jeu du dragon", "Le jeu du tigre"], acc: ["squid game", "jeu du calmar"] },
  { id: "squid-d8", d: 3, t: "Comment appelle-t-on les riches spectateurs masqués qui parient sur les joueurs ?", a: "Les VIP", x: ["Les Sponsors", "Les Juges", "Les Actionnaires"], acc: ["vip", "vips"] },
  { id: "squid-d9", d: 3, t: "Quel jeu consiste à traverser un pont fait de dalles de verre, certaines fragiles ?", a: "Le pont de verre", x: ["L'échelle de corde", "La poutre", "Le mur d'escalade"] },
  { id: "squid-d10", d: 3, t: "Quel gangster violent porte le numéro 101 ?", a: "Jang Deok-su", x: ["Ali Abdul", "Cho Sang-woo", "Oh Il-nam"] },
  { id: "squid-d11", d: 3, t: "Quel mot coréen désigne le partenaire de confiance dans le jeu des billes ?", a: "Gganbu", x: ["Oppa", "Hyung", "Ajumma"], acc: ["gganbu"] },
  { id: "squid-d12", d: 3, t: "Quel jeu enfantin le recruteur propose-t-il à Gi-hun dans le métro, avec des gifles ?", a: "Le ddakji", x: ["Le yut", "Le jenga", "Le morpion"], acc: ["ddakji"] },
  { id: "squid-d13", d: 3, t: "Quel rang de garde, selon la forme du masque, est le plus élevé ?", a: "Le carré", x: ["Le cercle", "Le triangle", "L'étoile"], acc: ["carré", "square"] },
  { id: "squid-d14", d: 3, t: "Combien de milliards de wons le grand vainqueur remporte-t-il ?", a: "45,6 milliards", x: ["10 milliards", "100 milliards", "4,56 milliards"], acc: ["45,6", "45.6"] },
  { id: "squid-d15", d: 3, t: "Quelle jeune joueuse, la numéro 240, se sacrifie pour Sae-byeok au jeu des billes ?", a: "Ji-yeong", x: ["Mi-nyeo", "Sae-byeok", "Mi-ok"] },
  // --- Pro (20) ---
  { id: "squid-p1", d: 4, t: "Quel acteur incarne Seong Gi-hun ?", a: "Lee Jung-jae", x: ["Park Hae-soo", "Wi Ha-joon", "Gong Yoo"] },
  { id: "squid-p2", d: 4, t: "Quel acteur joue Cho Sang-woo, le joueur 218 ?", a: "Park Hae-soo", x: ["Lee Jung-jae", "Wi Ha-joon", "O Yeong-su"] },
  { id: "squid-p3", d: 4, t: "Quel acteur célèbre incarne le recruteur qui joue au ddakji dans le métro ?", a: "Gong Yoo", x: ["Lee Byung-hun", "Wi Ha-joon", "Park Hae-soo"] },
  { id: "squid-p4", d: 4, t: "Quel acteur se cache derrière le masque du Front Man ?", a: "Lee Byung-hun", x: ["Gong Yoo", "Lee Jung-jae", "Park Hae-soo"] },
  { id: "squid-p5", d: 4, t: "Quelle est la véritable identité du Front Man ?", a: "Hwang In-ho", x: ["Oh Il-nam", "Hwang Jun-ho", "Cho Sang-woo"] },
  { id: "squid-p6", d: 4, t: "Quelle révélation surprend au sujet du vieil homme, le joueur 001 ?", a: "Il est le créateur des jeux", x: ["C'est un garde infiltré", "C'est le père de Gi-hun", "C'est un robot"] },
  { id: "squid-p7", d: 4, t: "Comment s'appelle la poupée géante du premier jeu ?", a: "Younghee", x: ["Cheolsu", "Hana", "Mina"], acc: ["young-hee"] },
  { id: "squid-p8", d: 4, t: "Quelles quatre formes de dalgona les joueurs doivent-ils découper ?", a: "Cercle, triangle, étoile et parapluie", x: ["Cœur, lune, éclair et fleur", "Carré, losange, croix et spirale", "Chien, chat, oiseau et poisson"] },
  { id: "squid-p9", d: 4, t: "Quelle forme de dalgona, la plus difficile, Gi-hun choisit-il ?", a: "Le parapluie", x: ["L'étoile", "Le cercle", "Le triangle"] },
  { id: "squid-p10", d: 4, t: "Quel numéro porte la joueuse Kang Sae-byeok ?", a: "067", x: ["240", "212", "199"] },
  { id: "squid-p11", d: 4, t: "Quel prix Lee Jung-jae a-t-il remporté aux Emmy Awards en 2022 ?", a: "Meilleur acteur", x: ["Meilleur second rôle", "Meilleur réalisateur", "Meilleur scénario"] },
  { id: "squid-p12", d: 4, t: "Quel numéro porte le gangster Jang Deok-su ?", a: "101", x: ["456", "001", "218"] },
  { id: "squid-p13", d: 4, t: "Sur quel type de lieu isolé se déroulent les jeux ?", a: "Une île isolée", x: ["Un gratte-ciel", "Un sous-marin", "Une station spatiale"] },
  { id: "squid-p14", d: 4, t: "À quoi ressemblent les escaliers colorés reliant les dortoirs aux salles de jeu ?", a: "À un labyrinthe à la Escher", x: ["À une cage d'ascenseur", "À un tunnel sombre", "À un pont suspendu"] },
  { id: "squid-p15", d: 4, t: "Que fait Gi-hun à ses cheveux à la toute fin de la saison 1 ?", a: "Il les teint en rouge", x: ["Il les rase", "Il les teint en blond", "Il les coupe court"], acc: ["rouge", "red"] },
  { id: "squid-p16", d: 4, t: "À la fin de la saison 1, que décide Gi-hun au lieu de monter dans l'avion ?", a: "Il fait demi-tour pour arrêter les jeux", x: ["Il part vivre à l'étranger", "Il rejoint les VIP", "Il se rend à la police"] },
  { id: "squid-p17", d: 4, t: "Combien de saisons compte Squid Game au total ?", a: "3", x: ["2", "4", "5"], acc: ["trois"] },
  { id: "squid-p18", d: 4, t: "Quel acteur incarne le détective infiltré Hwang Jun-ho ?", a: "Wi Ha-joon", x: ["Lee Byung-hun", "Gong Yoo", "Park Hae-soo"] },
  { id: "squid-p19", d: 4, t: "Quel lien unit le Front Man et le détective Jun-ho ?", a: "Ce sont des frères", x: ["Ce sont des cousins", "Ce sont des amis d'enfance", "Ce sont un père et son fils"] },
  { id: "squid-p20", d: 4, t: "Quel record Squid Game a-t-elle battu sur Netflix à sa sortie ?", a: "La série la plus regardée", x: ["Le film le plus cher", "La saison la plus courte", "La série la moins chère"], acc: ["plus regardée", "most watched"] },
]);
