import { universe } from "../_build";

export const theoffice = universe("series", "The Office (US)", [
  // --- Faciles (5) ---
  { id: "office-f1", d: 1, t: "Qui est le patron maladroit de la succursale de Scranton ?", a: "Michael Scott", acc: ["michael", "michael scott"], x: ["Jim", "Dwight", "Andy"] },
  { id: "office-f2", d: 1, t: "Dans quelle entreprise de papier travaillent les personnages ?", a: "Dunder Mifflin", x: ["Sabre", "Staples", "Vance Refrigeration"] },
  { id: "office-f3", d: 1, t: "Dans quelle ville se trouve la succursale principale ?", a: "Scranton", x: ["Stamford", "Utica", "Nashua"] },
  { id: "office-f4", d: 1, t: "Quel est le format (faux) de la série ?", a: "Un faux documentaire (mockumentary)", acc: ["mockumentary", "faux documentaire", "documentaire"], x: ["Une sitcom classique", "Un talk-show", "Un soap"] },
  { id: "office-f5", d: 1, t: "Quel commercial farceur est amoureux de Pam ?", a: "Jim Halpert", acc: ["jim", "halpert"], x: ["Dwight", "Andy", "Ryan"] },

  // --- Moyennes (10) ---
  { id: "office-m1", d: 2, t: "Quel vendeur zélé est fan de betteraves et de karaté ?", a: "Dwight Schrute", acc: ["dwight", "schrute"], x: ["Jim", "Stanley", "Kevin"] },
  { id: "office-m2", d: 2, t: "Quelle réceptionniste Jim finit-il par épouser ?", a: "Pam Beesly", acc: ["pam", "beesly"], x: ["Angela", "Kelly", "Erin"] },
  { id: "office-m3", d: 2, t: "Que cultive Dwight dans sa ferme (Schrute Farms) ?", a: "Des betteraves", acc: ["betteraves"], x: ["Du maïs", "Des pommes", "De la vigne"] },
  { id: "office-m4", d: 2, t: "Quelle comptable coincée adore les chats ?", a: "Angela", x: ["Kelly", "Phyllis", "Meredith"] },
  { id: "office-m5", d: 2, t: "Quel comptable bedonnant adore le chili et les M&M's ?", a: "Kevin", x: ["Stanley", "Oscar", "Creed"] },
  { id: "office-m6", d: 2, t: "Quel stagiaire ambitieux sort avec Kelly ?", a: "Ryan Howard", acc: ["ryan"], x: ["Andy", "Jim", "Darryl"] },
  { id: "office-m7", d: 2, t: "Quel comptable homosexuel et rationnel corrige souvent les autres ?", a: "Oscar", x: ["Kevin", "Stanley", "Toby"] },
  { id: "office-m8", d: 2, t: "Quel représentant des RH Michael déteste-t-il particulièrement ?", a: "Toby Flenderson", acc: ["toby", "flenderson"], x: ["Ryan", "Gabe", "Holly"] },
  { id: "office-m9", d: 2, t: "Quel chef d'entrepôt monte en grade au fil des saisons ?", a: "Darryl", x: ["Roy", "Stanley", "Andy"] },
  { id: "office-m10", d: 2, t: "Qui est l'ex-fiancé de Pam, magasinier ?", a: "Roy", x: ["Jim", "Andy", "Kevin"] },

  // --- Dures (15) ---
  { id: "office-d1", d: 3, t: "Qui devient le manager régional tout à la fin de la série ?", a: "Dwight Schrute", acc: ["dwight"], x: ["Andy", "Jim", "Kevin"] },
  { id: "office-d2", d: 3, t: "De quelle université Andy se vante-t-il sans arrêt ?", a: "Cornell", x: ["Harvard", "Yale", "Princeton"] },
  { id: "office-d3", d: 3, t: "Quel surnom Andy se donne-t-il à lui-même ?", a: "Nard Dog", acc: ["nard dog"], x: ["Big Tuna", "Boss", "Ace"] },
  { id: "office-d4", d: 3, t: "Quel surnom Andy donne-t-il à Jim ?", a: "Big Tuna", acc: ["big tuna", "tuna"], x: ["Nard Dog", "Jimbo", "Boss"] },
  { id: "office-d5", d: 3, t: "Quel employé le plus âgé et mystérieux partage le nom de l'acteur ?", a: "Creed Bratton", acc: ["creed", "creed bratton"], x: ["Stanley", "Hank", "Bob"] },
  { id: "office-d6", d: 3, t: "Quel vendeur ne pense qu'aux mots croisés et à la retraite ?", a: "Stanley Hudson", acc: ["stanley"], x: ["Kevin", "Oscar", "Creed"] },
  { id: "office-d7", d: 3, t: "Quelle société rachète Dunder Mifflin ?", a: "Sabre", x: ["Staples", "Prince Family Paper", "Athlead"] },
  { id: "office-d8", d: 3, t: "Quelle femme des RH devient l'amour de la vie de Michael ?", a: "Holly Flax", acc: ["holly", "holly flax"], x: ["Jan", "Carol", "Donna"] },
  { id: "office-d9", d: 3, t: "Quelle ancienne supérieure de Michael entretient une relation toxique avec lui ?", a: "Jan Levinson", acc: ["jan"], x: ["Holly", "Carol", "Pam"] },
  { id: "office-d10", d: 3, t: "Que sont les « Dundies » ?", a: "Les récompenses annuelles décernées par Michael", acc: ["recompenses", "les dundies", "prix"], x: ["Une fête de Noël", "Un tournoi", "Un pique-nique"] },
  { id: "office-d11", d: 3, t: "Quelle réceptionniste rousse et naïve remplace Pam ?", a: "Erin", x: ["Kelly", "Angela", "Meredith"] },
  { id: "office-d12", d: 3, t: "Quelle employée délurée des ventes boit beaucoup ?", a: "Meredith", x: ["Phyllis", "Angela", "Kelly"] },
  { id: "office-d13", d: 3, t: "Quelle entreprise de marketing sportif Jim co-fonde-t-il ?", a: "Athlead", x: ["Sabre", "Dunder Mifflin", "Vance Refrigeration"] },
  { id: "office-d14", d: 3, t: "Qui est le mari de Phyllis, patron d'une entreprise de frigos ?", a: "Bob Vance (Vance Refrigeration)", acc: ["bob vance", "vance"], x: ["Roy", "Darryl", "Hank"] },
  { id: "office-d15", d: 3, t: "Comment s'appelle le chat malade d'Angela que Dwight met au congélateur ?", a: "Sprinkles", x: ["Bandit", "Princess Lady", "Mr. Ash"] },

  // --- Pro (20) ---
  { id: "office-p1", d: 4, t: "Qui a créé la version britannique originale de The Office ?", a: "Ricky Gervais (et Stephen Merchant)", acc: ["ricky gervais", "gervais"], x: ["Greg Daniels", "Steve Carell", "Michael Schur"] },
  { id: "office-p2", d: 4, t: "Quel acteur incarne Michael Scott ?", a: "Steve Carell", acc: ["steve carell", "carell"], x: ["Rainn Wilson", "John Krasinski", "Ed Helms"] },
  { id: "office-p3", d: 4, t: "Quel acteur incarne Dwight ?", a: "Rainn Wilson", acc: ["rainn wilson"], x: ["Steve Carell", "John Krasinski", "Ed Helms"] },
  { id: "office-p4", d: 4, t: "Quel acteur incarne Jim ?", a: "John Krasinski", acc: ["john krasinski", "krasinski"], x: ["Ed Helms", "Rainn Wilson", "B.J. Novak"] },
  { id: "office-p5", d: 4, t: "Où Michael part-il s'installer avec Holly en quittant la série ?", a: "Au Colorado", acc: ["colorado"], x: ["En Floride", "À New York", "En Californie"] },
  { id: "office-p6", d: 4, t: "Comment s'appelle le groupe a cappella d'Andy à Cornell ?", a: "Here Comes Treble", acc: ["here comes treble"], x: ["The Whiffenpoofs", "Nard Dogs", "The Pitches"] },
  { id: "office-p7", d: 4, t: "Quel poste Ryan obtient-il au siège avant de tout faire capoter ?", a: "Vice-président", acc: ["vice-president", "vp", "vice president"], x: ["PDG", "Comptable", "Stagiaire"] },
  { id: "office-p8", d: 4, t: "Où Jim demande-t-il finalement Pam en mariage ?", a: "Dans une station-service, sous la pluie", acc: ["station-service", "station service", "sous la pluie"], x: ["Au bureau", "À la plage", "À Paris"] },
  { id: "office-p9", d: 4, t: "Où Jim et Pam se marient-ils ?", a: "Aux chutes du Niagara", acc: ["niagara", "chutes du niagara"], x: ["À Scranton", "À Hawaï", "À Las Vegas"] },
  { id: "office-p10", d: 4, t: "Combien d'enfants ont Jim et Pam ?", a: "2", acc: ["deux", "2"], x: ["1", "3", "4"] },
  { id: "office-p11", d: 4, t: "En quoi Dwight transforme-t-il sa ferme (Schrute Farms) ?", a: "En gîte d'agrotourisme (chambre d'hôtes)", acc: ["gite", "agrotourisme", "chambre d'hotes", "bed and breakfast"], x: ["Un motel", "Un camping", "Un restaurant"] },
  { id: "office-p12", d: 4, t: "Comment s'appelle le cousin un peu simplet de Dwight à la ferme ?", a: "Mose", x: ["Zeke", "Rolf", "Gabe"] },
  { id: "office-p13", d: 4, t: "Quel manager incompétent (joué par Will Ferrell) remplace brièvement Michael ?", a: "Deangelo Vickers", acc: ["deangelo", "deangelo vickers"], x: ["Robert California", "Gabe", "Nellie"] },
  { id: "office-p14", d: 4, t: "Quel PDG excentrique de Sabre s'incruste au bureau ?", a: "Robert California", acc: ["robert california"], x: ["Jo Bennett", "Deangelo", "Gabe"] },
  { id: "office-p15", d: 4, t: "Quelle PDG texane fonde Sabre et possède des chiens ?", a: "Jo Bennett", acc: ["jo bennett", "jo"], x: ["Jan", "Holly", "Nellie"] },
  { id: "office-p16", d: 4, t: "Quelle Britannique s'empare du poste de manager d'Andy ?", a: "Nellie Bertram", acc: ["nellie", "nellie bertram"], x: ["Holly", "Jan", "Erin"] },
  { id: "office-p17", d: 4, t: "Dans quel épisode culte Dwight déclenche un faux incendie pour tester ses collègues ?", a: "« Stress Relief » (l'exercice incendie)", acc: ["stress relief", "fire drill", "exercice incendie"], x: ["Dinner Party", "Diversity Day", "The Injury"] },
  { id: "office-p18", d: 4, t: "Comment Michael se blesse-t-il gravement au pied un matin ?", a: "En grillant du bacon sur un gril George Foreman", acc: ["george foreman", "gril foreman", "foreman grill"], x: ["Un barbecue", "Un radiateur", "De l'eau bouillante"] },
  { id: "office-p19", d: 4, t: "Quelle réplique Michael répète-t-il comme un gag récurrent ?", a: "« That's what she said »", acc: ["that's what she said", "thats what she said"], x: ["Bears. Beets. Battlestar Galactica.", "Boom, roasted", "I declare bankruptcy"] },
  { id: "office-p20", d: 4, t: "Complétez la réplique de Jim imitant Dwight : « Bears. Beets. … »", a: "Battlestar Galactica", acc: ["battlestar galactica", "battlestar"], x: ["Bruce Willis", "Beetlejuice", "Basketball"] },
]);
