import { universe } from "../_build";

export const walkingdead = universe("series", "The Walking Dead", [
  // --- Faciles (5) ---
  { id: "twd-f1", d: 1, t: "Quelles créatures menacent les survivants dans The Walking Dead ?", a: "Des zombies", x: ["Des vampires", "Des loups-garous", "Des extraterrestres"], acc: ["zombies", "des zombies"] },
  { id: "twd-f2", d: 1, t: "Comment les survivants surnomment-ils le plus souvent les zombies ?", a: "Des rôdeurs", x: ["Des mordus", "Des goules", "Des spectres"], acc: ["rodeurs", "rôdeurs", "walkers"] },
  { id: "twd-f3", d: 1, t: "Quel ancien shérif adjoint est le héros principal des premières saisons ?", a: "Rick Grimes", x: ["Daryl Dixon", "Negan", "Shane Walsh"], acc: ["rick", "rick grimes"] },
  { id: "twd-f4", d: 1, t: "À quel genre appartient The Walking Dead ?", a: "L'horreur post-apocalyptique", x: ["La comédie romantique", "La science-fiction spatiale", "Le western musical"], acc: ["horreur", "post-apocalyptique"] },
  { id: "twd-f5", d: 1, t: "De quel type d'œuvre la série The Walking Dead est-elle adaptée ?", a: "Un comic", x: ["Un roman classique", "Un jeu vidéo", "Une pièce de théâtre"], acc: ["comic", "bande dessinee", "comics"] },
  // --- Moyennes (10) ---
  { id: "twd-m1", d: 2, t: "Quelle arme silencieuse Daryl Dixon utilise-t-il de préférence ?", a: "Une arbalète", x: ["Un katana", "Un fusil à pompe", "Une batte"], acc: ["arbalete", "arbalète"] },
  { id: "twd-m2", d: 2, t: "Quelle arme blanche Michonne manie-t-elle avec maestria ?", a: "Un katana", x: ["Une arbalète", "Une hache", "Un fouet"], acc: ["katana"] },
  { id: "twd-m3", d: 2, t: "Comment s'appelle la batte de baseball entourée de fil barbelé de Negan ?", a: "Lucille", x: ["Betsy", "Bertha", "Dolores"], acc: ["lucille"] },
  { id: "twd-m4", d: 2, t: "Comment se prénomme le jeune fils de Rick Grimes ?", a: "Carl", x: ["Glenn", "Shane", "Daryl"], acc: ["carl"] },
  { id: "twd-m5", d: 2, t: "Près de quelle grande ville américaine l'histoire débute-t-elle ?", a: "Atlanta", x: ["New York", "Los Angeles", "Chicago"], acc: ["atlanta"] },
  { id: "twd-m6", d: 2, t: "Comment Rick découvre-t-il l'apocalypse au début de la série ?", a: "Il se réveille d'un coma à l'hôpital", x: ["Il rentre de voyage", "Il sort de prison", "Il descend d'un avion"], acc: ["coma", "reveille d'un coma"] },
  { id: "twd-m7", d: 2, t: "Que devient tout être humain à sa mort dans cet univers, quelle qu'en soit la cause ?", a: "Il se transforme en rôdeur", x: ["Il disparaît", "Il devient immunisé", "Il ressuscite sain"], acc: ["se transforme en rodeur", "rodeur"] },
  { id: "twd-m8", d: 2, t: "Comment tue-t-on définitivement un rôdeur ?", a: "En détruisant son cerveau", x: ["En lui perçant le cœur", "En l'affamant", "En l'attachant"], acc: ["cerveau", "detruisant son cerveau"] },
  { id: "twd-m9", d: 2, t: "Comment s'appelle le groupe impitoyable dirigé par Negan ?", a: "Les Sauveurs", x: ["Les Chuchoteurs", "Les Gouverneurs", "Les Rôdeurs"], acc: ["sauveurs", "saviors"] },
  { id: "twd-m10", d: 2, t: "Quel auteur a créé le comic original The Walking Dead ?", a: "Robert Kirkman", x: ["Stan Lee", "Frank Miller", "Alan Moore"], acc: ["kirkman", "robert kirkman"] },
  // --- Dures (15) ---
  { id: "twd-d1", d: 3, t: "Quel tyran borgne dirige la ville fortifiée de Woodbury ?", a: "Le Gouverneur", x: ["Negan", "Alpha", "Morgan"], acc: ["gouverneur", "le gouverneur"] },
  { id: "twd-d2", d: 3, t: "Quel refuge, promettant la sécurité, cache en réalité des cannibales ?", a: "Terminus", x: ["Alexandria", "Woodbury", "La Colline"], acc: ["terminus"] },
  { id: "twd-d3", d: 3, t: "Quelle communauté fortifiée près de Washington accueille le groupe de Rick ?", a: "Alexandria", x: ["Woodbury", "Terminus", "Le Royaume"], acc: ["alexandria"] },
  { id: "twd-d4", d: 3, t: "Quel roi de la communauté du Royaume possède une tigresse nommée Shiva ?", a: "Ezekiel", x: ["Negan", "Le Gouverneur", "Hershel"], acc: ["ezekiel"] },
  { id: "twd-d5", d: 3, t: "Quel groupe d'ennemis se déguise en portant la peau des rôdeurs ?", a: "Les Chuchoteurs", x: ["Les Sauveurs", "Les Loups", "Les Éboueurs"], acc: ["chuchoteurs", "whisperers"] },
  { id: "twd-d6", d: 3, t: "Quelle femme au crâne rasé dirige les Chuchoteurs ?", a: "Alpha", x: ["Michonne", "Carol", "Maggie"], acc: ["alpha"] },
  { id: "twd-d7", d: 3, t: "Quel ancien livreur de pizzas, mari de Maggie, fait partie du groupe d'origine ?", a: "Glenn", x: ["Abraham", "Eugene", "Daryl"], acc: ["glenn"] },
  { id: "twd-d8", d: 3, t: "De quel fermier vétérinaire Maggie est-elle la fille ?", a: "Hershel", x: ["Dale", "Morgan", "Tyreese"], acc: ["hershel"] },
  { id: "twd-d9", d: 3, t: "Quelle femme, d'abord épouse maltraitée, devient l'une des plus redoutables survivantes ?", a: "Carol", x: ["Andrea", "Lori", "Beth"], acc: ["carol"] },
  { id: "twd-d10", d: 3, t: "Quel meilleur ami de Rick, adjoint comme lui, entretient une liaison avec sa femme ?", a: "Shane", x: ["Glenn", "Daryl", "Merle"], acc: ["shane"] },
  { id: "twd-d11", d: 3, t: "Comment se prénomme le frère raciste et brutal de Daryl ?", a: "Merle", x: ["Shane", "Abraham", "Eugene"], acc: ["merle"] },
  { id: "twd-d12", d: 3, t: "Quel lieu fortifié le groupe de Rick occupe-t-il durant les saisons 3 et 4 ?", a: "Une prison", x: ["Un hôpital", "Un centre commercial", "Un stade"], acc: ["prison", "une prison"] },
  { id: "twd-d13", d: 3, t: "Comment se prénomme la petite fille née pendant l'apocalypse dans le groupe de Rick ?", a: "Judith", x: ["Lydia", "Sophia", "Enid"], acc: ["judith"] },
  { id: "twd-d14", d: 3, t: "Quel scientifique autoproclamé, à la coupe mulet, prétend d'abord détenir un remède ?", a: "Eugene", x: ["Abraham", "Aaron", "Gabriel"], acc: ["eugene"] },
  { id: "twd-d15", d: 3, t: "Quel centre de contrôle des maladies le groupe visite-t-il en fin de saison 1 ?", a: "Le CDC", x: ["Le FBI", "La NASA", "Le Pentagone"], acc: ["cdc", "le cdc"] },
  // --- Pro (20) ---
  { id: "twd-p1", d: 4, t: "En quelle année la série The Walking Dead a-t-elle débuté ?", a: "2010", x: ["2005", "2008", "2013"], acc: ["2010"] },
  { id: "twd-p2", d: 4, t: "Quel acteur britannique incarne Rick Grimes ?", a: "Andrew Lincoln", x: ["Norman Reedus", "Jeffrey Dean Morgan", "David Morrissey"], acc: ["andrew lincoln", "lincoln"] },
  { id: "twd-p3", d: 4, t: "Quel acteur incarne Daryl Dixon ?", a: "Norman Reedus", x: ["Andrew Lincoln", "Steven Yeun", "Jon Bernthal"], acc: ["norman reedus", "reedus"] },
  { id: "twd-p4", d: 4, t: "Quel acteur incarne le charismatique Negan ?", a: "Jeffrey Dean Morgan", x: ["David Morrissey", "Andrew Lincoln", "Norman Reedus"], acc: ["jeffrey dean morgan"] },
  { id: "twd-p5", d: 4, t: "Combien de saisons compte la série principale, achevée en 2022 ?", a: "Onze", x: ["Huit", "Neuf", "Quinze"], acc: ["11", "onze"] },
  { id: "twd-p6", d: 4, t: "Quel réalisateur, aussi derrière Les Évadés, a lancé la série en tant que showrunner ?", a: "Frank Darabont", x: ["Robert Kirkman", "Greg Nicotero", "Scott Gimple"], acc: ["darabont", "frank darabont"] },
  { id: "twd-p7", d: 4, t: "Quel maître des effets spéciaux crée les maquillages de zombies de la série ?", a: "Greg Nicotero", x: ["Rick Baker", "Tom Savini", "Rob Bottin"], acc: ["nicotero", "greg nicotero"] },
  { id: "twd-p8", d: 4, t: "Quelle particularité a Daryl Dixon par rapport au comic original ?", a: "Il n'existe pas dans le comic", x: ["Il meurt dès le premier tome", "Il est le héros du comic", "Il est le méchant du comic"], acc: ["n'existe pas dans le comic"] },
  { id: "twd-p9", d: 4, t: "Quel spin-off montre le tout début de l'épidémie, à Los Angeles ?", a: "Fear the Walking Dead", x: ["Dead City", "Daryl Dixon", "The Ones Who Live"], acc: ["fear the walking dead", "fear"] },
  { id: "twd-p10", d: 4, t: "Dans quel pays européen se déroule le spin-off consacré à Daryl Dixon ?", a: "La France", x: ["L'Italie", "L'Espagne", "L'Angleterre"], acc: ["france"] },
  { id: "twd-p11", d: 4, t: "Quel spin-off réunit Maggie et Negan dans une New York ravagée ?", a: "Dead City", x: ["Fear the Walking Dead", "World Beyond", "The Ones Who Live"], acc: ["dead city"] },
  { id: "twd-p12", d: 4, t: "Quel spin-off réunit enfin Rick et Michonne ?", a: "The Ones Who Live", x: ["Dead City", "Daryl Dixon", "World Beyond"], acc: ["the ones who live"] },
  { id: "twd-p13", d: 4, t: "En 2019, qu'est-il arrivé au comic original de Kirkman, à la surprise générale ?", a: "Il s'est brusquement terminé", x: ["Il a été racheté par Marvel", "Il est devenu un manga", "Il a doublé de pages"], acc: ["s'est termine", "termine"] },
  { id: "twd-p14", d: 4, t: "En hommage à qui Negan a-t-il baptisé sa batte « Lucille » ?", a: "Sa défunte épouse", x: ["Sa mère", "Sa fille", "Sa chienne"], acc: ["sa femme", "son epouse", "défunte épouse"] },
  { id: "twd-p15", d: 4, t: "Quelle communauté agricole, dirigée un temps par Gregory, produit et fait du commerce ?", a: "La Colline", x: ["Le Royaume", "Alexandria", "Le Commonwealth"], acc: ["colline", "la colline", "hilltop"] },
  { id: "twd-p16", d: 4, t: "Quel vaste réseau de communautés, presque une société d'avant, apparaît dans le dernier acte ?", a: "Le Commonwealth", x: ["Woodbury", "Terminus", "Le Sanctuaire"], acc: ["commonwealth"] },
  { id: "twd-p17", d: 4, t: "Comment se nomme le repaire industriel des Sauveurs de Negan ?", a: "Le Sanctuaire", x: ["Le Terminus", "Le Royaume", "La Colline"], acc: ["sanctuaire", "le sanctuaire"] },
  { id: "twd-p18", d: 4, t: "Quel gros revolver est l'arme de poing emblématique de Rick ?", a: "Un revolver Colt Python", x: ["Un fusil à pompe", "Un katana", "Une arbalète"], acc: ["colt python", "python", "revolver"] },
  { id: "twd-p19", d: 4, t: "Quelle jeune chanteuse, fille cadette d'Hershel, meurt à l'hôpital de Grady ?", a: "Beth", x: ["Sophia", "Enid", "Lydia"], acc: ["beth"] },
  { id: "twd-p20", d: 4, t: "Quelle fille d'Alpha quitte les Chuchoteurs pour rejoindre les survivants ?", a: "Lydia", x: ["Beth", "Judith", "Enid"], acc: ["lydia"] },
]);
