import { universe } from "../_build";

// Univers historique : la Seconde Guerre mondiale et le IIIe Reich, traités de
// façon factuelle et éducative (dates, événements, personnages historiques).
export const hitler = universe("politique", "Adolf Hitler", [
  // --- Faciles (5) ---
  { id: "hitler-f1", d: 1, t: "De quel parti Adolf Hitler a-t-il été le chef ?", a: "Le parti nazi", x: ["Le parti communiste", "Le parti socialiste", "Le parti libéral"], acc: ["parti nazi", "nazi", "nsdap"] },
  { id: "hitler-f2", d: 1, t: "Dans quel pays Adolf Hitler a-t-il pris le pouvoir en 1933 ?", a: "L'Allemagne", x: ["L'Italie", "L'Autriche", "La Pologne"], acc: ["allemagne", "l'allemagne"] },
  { id: "hitler-f3", d: 1, t: "Quel conflit mondial a été déclenché en Europe en 1939 sous Hitler ?", a: "La Seconde Guerre mondiale", x: ["La Première Guerre mondiale", "La guerre froide", "La guerre de Corée"], acc: ["seconde guerre mondiale", "2nde guerre mondiale"] },
  { id: "hitler-f4", d: 1, t: "Quel titre Hitler s'est-il attribué à la tête de l'Allemagne ?", a: "Führer", x: ["Roi", "Tsar", "Empereur"], acc: ["fuhrer", "führer", "le fuhrer"] },
  { id: "hitler-f5", d: 1, t: "Dans quelle ville se trouvait le principal siège du pouvoir nazi ?", a: "Berlin", x: ["Munich", "Vienne", "Hambourg"], acc: ["berlin"] },
  // --- Moyennes (10) ---
  { id: "hitler-m1", d: 2, t: "En quelle année Hitler est-il devenu chancelier d'Allemagne ?", a: "1933", x: ["1929", "1939", "1945"], acc: ["1933"] },
  { id: "hitler-m2", d: 2, t: "Dans quel pays est né Adolf Hitler ?", a: "L'Autriche", x: ["L'Allemagne", "La Suisse", "La Pologne"], acc: ["autriche", "l'autriche"] },
  { id: "hitler-m3", d: 2, t: "Quelle invasion, en septembre 1939, marque le début de la guerre en Europe ?", a: "L'invasion de la Pologne", x: ["L'invasion de la France", "L'invasion de la Russie", "L'invasion de l'Angleterre"], acc: ["invasion de la pologne", "pologne"] },
  { id: "hitler-m4", d: 2, t: "Comment s'appelle le livre écrit par Hitler exposant son idéologie ?", a: "Mein Kampf", x: ["Le Capital", "Le Prince", "Le Contrat social"], acc: ["mein kampf"] },
  { id: "hitler-m5", d: 2, t: "Quel type de régime Hitler a-t-il instauré en Allemagne ?", a: "Une dictature", x: ["Une démocratie", "Une monarchie", "Une république parlementaire"], acc: ["dictature", "une dictature"] },
  { id: "hitler-m6", d: 2, t: "Comment nommait-on l'État allemand sous Hitler, troisième du nom ?", a: "Le Troisième Reich", x: ["La République de Weimar", "L'Empire prussien", "La Confédération germanique"], acc: ["troisieme reich", "3e reich", "reich"] },
  { id: "hitler-m7", d: 2, t: "Quel symbole le parti nazi avait-il choisi comme emblème ?", a: "La croix gammée", x: ["L'aigle bicéphale", "La faucille et le marteau", "La fleur de lys"], acc: ["croix gammee", "croix gammée", "svastika"] },
  { id: "hitler-m8", d: 2, t: "En quelle année la Seconde Guerre mondiale s'est-elle terminée en Europe ?", a: "1945", x: ["1939", "1918", "1950"], acc: ["1945"] },
  { id: "hitler-m9", d: 2, t: "Comment Adolf Hitler a-t-il mis fin à ses jours en 1945 ?", a: "Il s'est suicidé", x: ["Il a été fusillé", "Il a été capturé", "Il est mort de maladie"], acc: ["suicide", "il s'est suicide", "suicidé"] },
  { id: "hitler-m10", d: 2, t: "Quel camp l'Allemagne nazie formait-elle avec l'Italie et le Japon ?", a: "Les forces de l'Axe", x: ["Les Alliés", "L'Entente", "Le Pacte de Varsovie"], acc: ["axe", "forces de l'axe", "l'axe"] },
  // --- Dures (15) ---
  { id: "hitler-d1", d: 3, t: "En quelle année Adolf Hitler est-il né ?", a: "1889", x: ["1879", "1899", "1901"], acc: ["1889"] },
  { id: "hitler-d2", d: 3, t: "Dans quelle ville autrichienne Hitler a-t-il vécu jeune en tentant d'être peintre ?", a: "Vienne", x: ["Salzbourg", "Graz", "Innsbruck"], acc: ["vienne"] },
  { id: "hitler-d3", d: 3, t: "Dans quel conflit Hitler a-t-il servi comme soldat pour l'Allemagne ?", a: "La Première Guerre mondiale", x: ["La guerre franco-prussienne", "La guerre des Boers", "La guerre d'Espagne"], acc: ["premiere guerre mondiale", "1ere guerre mondiale"] },
  { id: "hitler-d4", d: 3, t: "Comment s'appelait le putsch raté mené par Hitler à Munich en 1923 ?", a: "Le putsch de la Brasserie", x: ["Le putsch de Kapp", "La marche sur Rome", "La nuit des Longs Couteaux"], acc: ["putsch de la brasserie", "putsch de munich"] },
  { id: "hitler-d5", d: 3, t: "Quelle République allemande Hitler a-t-il renversée en accédant au pouvoir ?", a: "La République de Weimar", x: ["La République de Bonn", "La République de Berlin", "La République rhénane"], acc: ["republique de weimar", "weimar"] },
  { id: "hitler-d6", d: 3, t: "Comment s'appelait le chef de la propagande du régime nazi ?", a: "Joseph Goebbels", x: ["Heinrich Himmler", "Hermann Göring", "Rudolf Hess"], acc: ["goebbels", "joseph goebbels"] },
  { id: "hitler-d7", d: 3, t: "Quelle police politique agissait sous le régime nazi ?", a: "La Gestapo", x: ["Le KGB", "La Stasi", "Le NKVD"], acc: ["gestapo", "la gestapo"] },
  { id: "hitler-d8", d: 3, t: "Quelle opération désignait l'invasion de l'Union soviétique en 1941 ?", a: "L'opération Barbarossa", x: ["L'opération Overlord", "L'opération Market Garden", "L'opération Torch"], acc: ["barbarossa", "operation barbarossa"] },
  { id: "hitler-d9", d: 3, t: "Quelle bataille de 1942 et 1943 marqua un tournant sur le front de l'Est ?", a: "La bataille de Stalingrad", x: ["La bataille de Verdun", "La bataille de Normandie", "La bataille des Ardennes"], acc: ["stalingrad", "bataille de stalingrad"] },
  { id: "hitler-d10", d: 3, t: "Comment s'appelait le corps d'élite paramilitaire dirigé par Himmler ?", a: "La SS", x: ["La SA", "La Wehrmacht", "La Luftwaffe"], acc: ["ss", "la ss"] },
  { id: "hitler-d11", d: 3, t: "Quel Premier ministre britannique s'opposa fermement à Hitler durant la guerre ?", a: "Winston Churchill", x: ["Neville Chamberlain", "Clement Attlee", "Anthony Eden"], acc: ["churchill", "winston churchill"] },
  { id: "hitler-d12", d: 3, t: "Quels accords de 1938 laissèrent Hitler annexer une partie de la Tchécoslovaquie ?", a: "Les accords de Munich", x: ["Le traité de Versailles", "Le pacte de Varsovie", "Les accords de Yalta"], acc: ["accords de munich", "munich"] },
  { id: "hitler-d13", d: 3, t: "Comment appelle-t-on le rattachement de l'Autriche à l'Allemagne nazie en 1938 ?", a: "L'Anschluss", x: ["Le Blitzkrieg", "Le Kulturkampf", "Le Lebensraum"], acc: ["anschluss", "l'anschluss"] },
  { id: "hitler-d14", d: 3, t: "Quelle tactique de guerre éclair l'armée allemande employa-t-elle au début du conflit ?", a: "Le Blitzkrieg", x: ["La guerre de tranchées", "La ligne Maginot", "La guerre de position"], acc: ["blitzkrieg"] },
  { id: "hitler-d15", d: 3, t: "Quel pacte de non-agression Hitler signa-t-il avec Staline en 1939 ?", a: "Le pacte germano-soviétique", x: ["Le pacte de l'Axe", "Le pacte de Munich", "Le pacte atlantique"], acc: ["pacte germano-sovietique", "pacte germano-soviétique", "molotov-ribbentrop"] },
  // --- Pro (20) ---
  { id: "hitler-p1", d: 4, t: "Quel était le nom complet du parti nazi ?", a: "Parti national-socialiste des travailleurs allemands", x: ["Parti social-démocrate d'Allemagne", "Parti populaire allemand", "Parti ouvrier communiste"], acc: ["nsdap", "national-socialiste"] },
  { id: "hitler-p2", d: 4, t: "Dans quelle ville-frontière autrichienne Hitler est-il né ?", a: "Braunau am Inn", x: ["Linz", "Salzbourg", "Klagenfurt"], acc: ["braunau", "braunau am inn"] },
  { id: "hitler-p3", d: 4, t: "Dans quelle prison Hitler a-t-il rédigé Mein Kampf durant sa détention ?", a: "La prison de Landsberg", x: ["La prison de Spandau", "La prison de Moabit", "La forteresse de Königstein"], acc: ["landsberg", "prison de landsberg"] },
  { id: "hitler-p4", d: 4, t: "Comment s'appelait le maréchal du Reich, chef de l'aviation allemande ?", a: "Hermann Göring", x: ["Heinrich Himmler", "Joseph Goebbels", "Rudolf Hess"], acc: ["goring", "göring", "hermann goring"] },
  { id: "hitler-p5", d: 4, t: "Comment s'appelait l'armée régulière allemande sous le Troisième Reich ?", a: "La Wehrmacht", x: ["La Reichswehr", "La Bundeswehr", "La Luftwaffe"], acc: ["wehrmacht", "la wehrmacht"] },
  { id: "hitler-p6", d: 4, t: "Quel adjoint de Hitler s'envola vers l'Écosse en 1941 pour une tentative de paix ?", a: "Rudolf Hess", x: ["Martin Bormann", "Albert Speer", "Reinhard Heydrich"], acc: ["hess", "rudolf hess"] },
  { id: "hitler-p7", d: 4, t: "Quel architecte devint ministre de l'Armement de Hitler ?", a: "Albert Speer", x: ["Rudolf Hess", "Martin Bormann", "Adolf Eichmann"], acc: ["speer", "albert speer"] },
  { id: "hitler-p8", d: 4, t: "Quel officier mena l'attentat de l'opération Walkyrie contre Hitler en juillet 1944 ?", a: "Claus von Stauffenberg", x: ["Erwin Rommel", "Ludwig Beck", "Wilhelm Canaris"], acc: ["stauffenberg", "von stauffenberg", "claus von stauffenberg"] },
  { id: "hitler-p9", d: 4, t: "Comment s'appelait le chef de la SS, principal organisateur de la police du régime ?", a: "Heinrich Himmler", x: ["Hermann Göring", "Joseph Goebbels", "Reinhard Heydrich"], acc: ["himmler", "heinrich himmler"] },
  { id: "hitler-p10", d: 4, t: "Quel concept d'espace vital Hitler invoquait-il pour justifier ses conquêtes à l'Est ?", a: "Le Lebensraum", x: ["L'Anschluss", "Le Blitzkrieg", "Le Kulturkampf"], acc: ["lebensraum", "espace vital"] },
  { id: "hitler-p11", d: 4, t: "Dans quel abri souterrain de Berlin Hitler a-t-il passé ses derniers jours ?", a: "Le Führerbunker", x: ["Le nid d'Aigle", "La chancellerie de Weimar", "Le Reichstag"], acc: ["fuhrerbunker", "führerbunker", "bunker"] },
  { id: "hitler-p12", d: 4, t: "Comment s'appelait la résidence de montagne de Hitler dans les Alpes bavaroises ?", a: "Le Berghof", x: ["Le Wolfsschanze", "Le Reichstag", "Le Belvédère"], acc: ["berghof", "le berghof"] },
  { id: "hitler-p13", d: 4, t: "Quel incendie d'un bâtiment officiel en 1933 servit de prétexte pour renforcer le pouvoir nazi ?", a: "L'incendie du Reichstag", x: ["L'incendie de la chancellerie", "L'incendie de Dresde", "L'incendie de Munich"], acc: ["incendie du reichstag", "reichstag"] },
  { id: "hitler-p14", d: 4, t: "Quelles lois de 1935 privèrent les Juifs de leurs droits de citoyens allemands ?", a: "Les lois de Nuremberg", x: ["Les lois de Weimar", "Les décrets de Potsdam", "Les lois de Munich"], acc: ["lois de nuremberg", "nuremberg"] },
  { id: "hitler-p15", d: 4, t: "Comment s'appelait la purge de 1934 durant laquelle Hitler élimina des chefs de la SA ?", a: "La nuit des Longs Couteaux", x: ["La nuit de Cristal", "Le putsch de la Brasserie", "La nuit des Barricades"], acc: ["nuit des longs couteaux"] },
  { id: "hitler-p16", d: 4, t: "Comment nomme-t-on le pogrom antijuif organisé en Allemagne en novembre 1938 ?", a: "La nuit de Cristal", x: ["La nuit des Longs Couteaux", "La rafle du Vél d'Hiv", "La marche de la faim"], acc: ["nuit de cristal", "kristallnacht"] },
  { id: "hitler-p17", d: 4, t: "Qui succéda brièvement à Hitler comme chef de l'État allemand après sa mort ?", a: "L'amiral Dönitz", x: ["Joseph Goebbels", "Hermann Göring", "Heinrich Himmler"], acc: ["donitz", "dönitz", "karl donitz", "amiral donitz"] },
  { id: "hitler-p18", d: 4, t: "Quel chef nazi, surnommé le boucher de Prague, organisa la terreur du régime ?", a: "Reinhard Heydrich", x: ["Adolf Eichmann", "Rudolf Höss", "Klaus Barbie"], acc: ["heydrich", "reinhard heydrich"] },
  { id: "hitler-p19", d: 4, t: "Quel procès international jugea les principaux dirigeants nazis survivants ?", a: "Le procès de Nuremberg", x: ["Le procès de La Haye", "Le procès de Tokyo", "Le procès de Leipzig"], acc: ["proces de nuremberg", "procès de nuremberg"] },
  { id: "hitler-p20", d: 4, t: "En quel mois de 1945 Hitler s'est-il donné la mort dans son bunker ?", a: "En avril", x: ["En mai", "En septembre", "En janvier"], acc: ["avril", "en avril", "avril 1945"] },
]);
