import { universe } from "../_build";

// Univers factuel : parcours et faits marquants de Donald Trump, homme
// d'affaires et président des États-Unis (dates, fonctions, événements).
export const trump = universe("politique", "Donald Trump", [
  // --- Faciles (5) ---
  { id: "trump-f1", d: 1, t: "Quelle haute fonction Donald Trump a-t-il exercée aux États-Unis ?", a: "Président", x: ["Premier ministre", "Sénateur à vie", "Gouverneur général"], acc: ["president", "président"] },
  { id: "trump-f2", d: 1, t: "De quel parti politique américain Donald Trump est-il membre ?", a: "Le parti républicain", x: ["Le parti démocrate", "Le parti libertarien", "Le parti vert"], acc: ["republicain", "parti republicain", "gop"] },
  { id: "trump-f3", d: 1, t: "Dans quel secteur Donald Trump a-t-il fait fortune avant la politique ?", a: "L'immobilier", x: ["Le pétrole", "L'informatique", "L'automobile"], acc: ["immobilier", "l'immobilier"] },
  { id: "trump-f4", d: 1, t: "Quel célèbre slogan Donald Trump a-t-il utilisé lors de ses campagnes ?", a: "Make America Great Again", x: ["Yes We Can", "I Like Ike", "The New Deal"], acc: ["make america great again", "maga"] },
  { id: "trump-f5", d: 1, t: "Quelle émission de téléréalité Donald Trump a-t-il animée ?", a: "The Apprentice", x: ["Big Brother", "Survivor", "American Idol"], acc: ["the apprentice", "apprentice"] },
  // --- Moyennes (10) ---
  { id: "trump-m1", d: 2, t: "En quelle année Donald Trump a-t-il été élu président pour la première fois ?", a: "2016", x: ["2008", "2012", "2020"], acc: ["2016"] },
  { id: "trump-m2", d: 2, t: "Quel numéro de président des États-Unis Donald Trump a-t-il d'abord été ?", a: "Le 45e", x: ["Le 43e", "Le 44e", "Le 46e"], acc: ["45", "45e", "quarante-cinquieme"] },
  { id: "trump-m3", d: 2, t: "Contre quelle candidate démocrate Donald Trump a-t-il gagné en 2016 ?", a: "Hillary Clinton", x: ["Kamala Harris", "Nancy Pelosi", "Michelle Obama"], acc: ["hillary clinton", "clinton", "hillary"] },
  { id: "trump-m4", d: 2, t: "Dans quelle ville américaine Donald Trump est-il né ?", a: "New York", x: ["Chicago", "Los Angeles", "Washington"], acc: ["new york"] },
  { id: "trump-m5", d: 2, t: "Comment s'appelle la célèbre tour qui porte le nom de Trump à New York ?", a: "La Trump Tower", x: ["L'Empire State Building", "La Willis Tower", "Le Chrysler Building"], acc: ["trump tower", "la trump tower"] },
  { id: "trump-m6", d: 2, t: "Quel réseau social Donald Trump a-t-il beaucoup utilisé durant sa présidence ?", a: "Twitter", x: ["Facebook", "Instagram", "LinkedIn"], acc: ["twitter", "x"] },
  { id: "trump-m7", d: 2, t: "Contre quel adversaire démocrate Donald Trump a-t-il perdu l'élection de 2020 ?", a: "Joe Biden", x: ["Barack Obama", "Bernie Sanders", "Al Gore"], acc: ["joe biden", "biden"] },
  { id: "trump-m8", d: 2, t: "Quelle construction à la frontière mexicaine Trump a-t-il promise en 2016 ?", a: "Un mur", x: ["Un pont", "Un canal", "Un tunnel"], acc: ["un mur", "mur"] },
  { id: "trump-m9", d: 2, t: "Comment s'appelle l'épouse de Donald Trump devenue Première dame en 2017 ?", a: "Melania Trump", x: ["Ivanka Trump", "Marla Maples", "Ivana Trump"], acc: ["melania", "melania trump"] },
  { id: "trump-m10", d: 2, t: "En quelle année Donald Trump a-t-il été réélu président ?", a: "2024", x: ["2020", "2022", "2018"], acc: ["2024"] },
  // --- Dures (15) ---
  { id: "trump-d1", d: 3, t: "En quelle année Donald Trump est-il né ?", a: "1946", x: ["1936", "1956", "1950"], acc: ["1946"] },
  { id: "trump-d2", d: 3, t: "Comment se nomme la fille aînée de Donald Trump, conseillère à la Maison-Blanche ?", a: "Ivanka Trump", x: ["Melania Trump", "Tiffany Trump", "Marla Maples"], acc: ["ivanka", "ivanka trump"] },
  { id: "trump-d3", d: 3, t: "Quel gendre de Trump fut son conseiller principal à la Maison-Blanche ?", a: "Jared Kushner", x: ["Donald Trump Jr.", "Eric Trump", "Mike Pence"], acc: ["kushner", "jared kushner"] },
  { id: "trump-d4", d: 3, t: "Qui était le vice-président de Donald Trump durant son premier mandat ?", a: "Mike Pence", x: ["Mike Pompeo", "JD Vance", "Dick Cheney"], acc: ["mike pence", "pence"] },
  { id: "trump-d5", d: 3, t: "Quelle université au nom de Trump a fait l'objet de poursuites pour ses formations ?", a: "La Trump University", x: ["La Harvard Business School", "La Wharton School", "La Trump Academy"], acc: ["trump university", "universite trump"] },
  { id: "trump-d6", d: 3, t: "Dans quelle prestigieuse école de commerce Donald Trump a-t-il étudié ?", a: "Wharton", x: ["Harvard", "Yale", "Stanford"], acc: ["wharton", "wharton school"] },
  { id: "trump-d7", d: 3, t: "Combien de fois Donald Trump a-t-il fait l'objet d'une procédure de destitution ?", a: "Deux fois", x: ["Une fois", "Trois fois", "Jamais"], acc: ["deux", "deux fois", "2"] },
  { id: "trump-d8", d: 3, t: "Comment s'appelle le vaste domaine de Trump en Floride ?", a: "Mar-a-Lago", x: ["Camp David", "Trump Plaza", "Palm Beach House"], acc: ["mar-a-lago", "mar a lago"] },
  { id: "trump-d9", d: 3, t: "Quel livre à succès de 1987 a bâti l'image de Trump homme d'affaires ?", a: "The Art of the Deal", x: ["How to Get Rich", "The Wealth of Nations", "Think Big"], acc: ["the art of the deal", "art of the deal", "l'art de la negociation"] },
  { id: "trump-d10", d: 3, t: "Qui est devenu le vice-président de Donald Trump à partir de 2025 ?", a: "JD Vance", x: ["Mike Pence", "Ron DeSantis", "Marco Rubio"], acc: ["jd vance", "vance"] },
  { id: "trump-d11", d: 3, t: "Contre quelle candidate démocrate Donald Trump a-t-il gagné l'élection de 2024 ?", a: "Kamala Harris", x: ["Hillary Clinton", "Nancy Pelosi", "Elizabeth Warren"], acc: ["kamala harris", "harris", "kamala"] },
  { id: "trump-d12", d: 3, t: "Quel accord climatique international Trump a-t-il quitté durant son premier mandat ?", a: "L'accord de Paris", x: ["Le protocole de Kyoto", "L'accord de Genève", "Le pacte de Rio"], acc: ["accord de paris", "paris"] },
  { id: "trump-d13", d: 3, t: "Quelle compagnie aérienne Trump a-t-il brièvement possédée à la fin des années 1980 ?", a: "La Trump Shuttle", x: ["La Pan Am", "La TWA", "La Delta"], acc: ["trump shuttle", "shuttle"] },
  { id: "trump-d14", d: 3, t: "Quel dirigeant nord-coréen Donald Trump a-t-il rencontré lors de sommets ?", a: "Kim Jong-un", x: ["Xi Jinping", "Vladimir Poutine", "Shinzo Abe"], acc: ["kim jong-un", "kim jong un", "kim"] },
  { id: "trump-d15", d: 3, t: "Quel réseau social Donald Trump a-t-il lui-même lancé après 2020 ?", a: "Truth Social", x: ["Parler", "Gettr", "Rumble"], acc: ["truth social"] },
  // --- Pro (20) ---
  { id: "trump-p1", d: 4, t: "Quel est le deuxième prénom de Donald Trump ?", a: "John", x: ["James", "Fred", "Robert"], acc: ["john", "donald john trump"] },
  { id: "trump-p2", d: 4, t: "Comment s'appelait le père promoteur immobilier de Donald Trump ?", a: "Fred Trump", x: ["John Trump", "Robert Trump", "Frederick Barron"], acc: ["fred trump", "fred"] },
  { id: "trump-p3", d: 4, t: "Quel hôtel-casino de Trump à Atlantic City portait le nom d'un monument indien ?", a: "Le Trump Taj Mahal", x: ["Le Caesars Palace", "Le Bellagio", "Le MGM Grand"], acc: ["trump taj mahal", "taj mahal"] },
  { id: "trump-p4", d: 4, t: "Combien de mandats présidentiels non consécutifs Trump a-t-il remportés en 2016 puis 2024 ?", a: "Deux", x: ["Un", "Trois", "Quatre"], acc: ["deux", "2"] },
  { id: "trump-p5", d: 4, t: "Quel président américain, avant Trump, avait exercé deux mandats non consécutifs ?", a: "Grover Cleveland", x: ["Theodore Roosevelt", "Woodrow Wilson", "Andrew Jackson"], acc: ["grover cleveland", "cleveland"] },
  { id: "trump-p6", d: 4, t: "Quelle grande réforme fiscale Trump a-t-il fait adopter en 2017 ?", a: "Une baisse des impôts", x: ["Une hausse de la TVA", "Une taxe carbone", "Un impôt sur la fortune"], acc: ["baisse des impots", "tax cuts", "reforme fiscale"] },
  { id: "trump-p7", d: 4, t: "Comment appelait-on la politique de droits de douane de Trump, surtout envers la Chine ?", a: "La guerre commerciale", x: ["Le libre-échange", "L'union douanière", "Le marché commun"], acc: ["guerre commerciale", "guerre des tarifs"] },
  { id: "trump-p8", d: 4, t: "Quels accords entre Israël et des pays arabes ont été signés sous Trump en 2020 ?", a: "Les accords d'Abraham", x: ["Les accords d'Oslo", "Les accords de Camp David", "Les accords de Genève"], acc: ["accords d'abraham", "abraham"] },
  { id: "trump-p9", d: 4, t: "En quelle année a eu lieu la première procédure de destitution de Trump ?", a: "2019", x: ["2017", "2021", "2016"], acc: ["2019"] },
  { id: "trump-p10", d: 4, t: "Quel événement au Capitole a marqué la fin du premier mandat de Trump en janvier 2021 ?", a: "L'assaut du Capitole", x: ["Un discours d'adieu", "Une fête nationale", "Un défilé militaire"], acc: ["assaut du capitole", "capitole", "6 janvier"] },
  { id: "trump-p11", d: 4, t: "Quelle juge conservatrice Trump a-t-il nommée à la Cour suprême en 2020 ?", a: "Amy Coney Barrett", x: ["Ruth Bader Ginsburg", "Sonia Sotomayor", "Elena Kagan"], acc: ["amy coney barrett", "barrett"] },
  { id: "trump-p12", d: 4, t: "Combien de juges Trump a-t-il nommés à la Cour suprême durant son premier mandat ?", a: "Trois", x: ["Un", "Deux", "Cinq"], acc: ["trois", "3"] },
  { id: "trump-p13", d: 4, t: "Quelle ville Trump a-t-il reconnue comme capitale d'Israël en y déplaçant l'ambassade ?", a: "Jérusalem", x: ["Tel-Aviv", "Haïfa", "Ramallah"], acc: ["jerusalem", "jérusalem"] },
  { id: "trump-p14", d: 4, t: "Comment s'appelle le fils aîné de Donald Trump ?", a: "Donald Trump Jr.", x: ["Eric Trump", "Barron Trump", "Jared Kushner"], acc: ["donald trump jr", "don jr", "donald junior"] },
  { id: "trump-p15", d: 4, t: "De quel pays étaient originaires les parents de la mère de Donald Trump ?", a: "L'Écosse", x: ["L'Irlande", "L'Allemagne", "L'Italie"], acc: ["ecosse", "écosse", "ecossaise"] },
  { id: "trump-p16", d: 4, t: "Comment s'appelait la première épouse de Trump, mère de ses trois aînés ?", a: "Ivana Trump", x: ["Marla Maples", "Melania Knauss", "Blaine Trump"], acc: ["ivana", "ivana trump"] },
  { id: "trump-p17", d: 4, t: "Quel milliardaire de la tech a soutenu Trump et rejoint son administration en 2025 ?", a: "Elon Musk", x: ["Bill Gates", "Mark Zuckerberg", "Jeff Bezos"], acc: ["elon musk", "musk"] },
  { id: "trump-p18", d: 4, t: "Dans quel arrondissement de New York Donald Trump est-il né ?", a: "Le Queens", x: ["Manhattan", "Brooklyn", "Le Bronx"], acc: ["queens", "le queens"] },
  { id: "trump-p19", d: 4, t: "Quelle agence fédérale Trump a-t-il souvent critiquée durant son premier mandat ?", a: "Le FBI", x: ["La NASA", "La FDA", "La FEMA"], acc: ["fbi", "le fbi"] },
  { id: "trump-p20", d: 4, t: "Quel qualificatif Trump employait-il pour dénoncer la presse qu'il jugeait hostile ?", a: "Fake news", x: ["Breaking news", "Hot news", "Old news"], acc: ["fake news"] },
]);
